### ISSUE TITLE
Cleaning ammo freeze

### ISSUE THREAD

**Issue by InePetrine** [tullamods/Bagnon#1001]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.2.13
 - Server patch: [e.g. Build 8.0.1.27178]

 **Have you read the changelog? (please don't waste our time)**
 Yes

**Describe the bug**
Cleaning gets stuck when there are bullets in the first slot of the ammo pouch and there are more bullets in the other bags to be sorted.

**To Reproduce**
Steps to reproduce the behaviour:
1. Have a full stack of bullets in the first slot of the ammo pouch
2. Have any number of bullets in other bag
3. Click on "Click to clean items" in the bag
4. See first item in ammo pouch blink and make the sorting/moving sound on repeat

**Expected behaviour**
Sorting of the items

**Screenshots**

![image](https://user-images.githubusercontent.com/4227612/65382821-0170e500-dd0d-11e9-88d7-58cfd2fdb7c9.png)

**Error Logs**
No error

**Additional context**
Seems like it tries to put ammo in the first slot and since that slot is full it retries forever. This is an issue when having more bullets than there are room for in the ammo pouch. 

(Love the add-on, keep up the good work)

**Comment by Nisverah** [comment]
Also having this issue when having more ammo than can fit in quiver, it occurs indefinitely until I enter combat or reloadui.

**Comment by dacool** [comment]
I can also confirm this.

**Comment by Jaliborc** [comment]
fixed internally
