### ISSUE TITLE
Bagbreak just for quivers and ammo pouch - CLASSIC

### ISSUE THREAD

**Issue by Rawhuntress** [tullamods/Bagnon#1002]
Might I suggest to add a feture were quivers and ammo pouch gets a separate window in bagnon not go confuse with the other bag spaces. I know you can change color but I'd like this simply to clean the Ui a bit. Sometimes I open just the quiver, and sometimes i open just the bags. Would be neat.

Thank you!

/ Rawhuntress (a classic huntard)

**Comment by Jaliborc** [comment]
Sorry but this is not a feature I'll implement I think. The entire point of Bagnon is to have everything in a single window, this goes against its core principle.

**Comment by datagutten** [comment]
There should be some way to identify the quiver slots because it is only possible to put ammo in them, not other items like regular slots. This also makes trouble for the sorting function.
