### ISSUE TITLE
Cached reagent bank is shown as not purchased and cannot be toggled

### ISSUE THREAD

**Issue by LudiusMaximus** [tullamods/Bagnon#1005]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.2.15
 - Server patch: Build 8.2.5.31961

 **Have you read the changelog? (please don't waste our time)**
Yes!

**Describe the bug**
Cached reagent bank is shown as not purchased and cannot be clicked

**To Reproduce**
View the bank of the current or another cached character while not actually at the bank.

**Expected behaviour**
Reagent bank icon should be possible to toggle (if it is purchased).

**Comment by Stormers16** [comment]
I have the exactly the same problem.

**Comment by Jaliborc** [comment]
Fixed
