### ISSUE TITLE
[Classic] Can't move items in combat

### ISSUE THREAD

**Issue by ShetiPhian** [tullamods/Bagnon#1006]
**Running Software (issues missing this information will be deleted):**
 - Addon version: Bagnon-8.2.12 and up
 - Server patch: Version 1.13.1(31882) (Release x64) Sept 17 2019

 **Have you read the changelog? (please don't waste our time)**
Yes

**Describe the bug**
While in combat you can no longer move items in your bags

**To Reproduce**
Install version 8.2.12 or higher
Enter combat
Try to move an item in your bag

**Expected behaviour**
Same behaviour as 8.2.11 and lower
Being able to move items in combat

**Error Logs**
None

**Additional context**
I suspect it is a bug introduced with the sorting function, and how it is disabled in combat.

I noticed in 8.2.15 I couldn't move items, reading the change log made me suspect 8.2.12, so I deleted the .15 folders and installed .11 and tested.
When that worked correctly, I deleted the .11 folders and installed .12 and tested again and found it broken again. I have dropped back to .11 for now.

**Comment by ascholz** [comment]
I have the same issue. What was the solution?
