### ISSUE TITLE
FEATURE REQUEST: Highlight Least Valuable Item

### ISSUE THREAD

**Issue by Lothaer** [tullamods/Bagnon#1010]
**Is your feature request related to a problem? Please describe.**
Often when questing ones bags tend to get a bit full and there isn't always a vendor close by to sell items for room, sometimes you have to destroy some items so you can pick up a quest item.

**Describe the solution you'd like**
To make the decision of destroying an item easier and quick it would be great if BAGNON could highlight which ever item/stack of items is the LEAST valuable as a suggestion to the player if they're looking for an item to destroy.

**Describe alternatives you've considered**
Checking the items/stacks one by one multiple times.

**Additional context**
Nil

**Comment by Jaliborc** [comment]
Out of scope of bagnon. Sorry
