### ISSUE TITLE
[Classic] Sorting with ammo bags involved

### ISSUE THREAD

**Issue by Morphyloon** [tullamods/Bagnon#1011]
The issue: I've noticed that the sorting routine doesn't seem to know that ammo bags only take ammo, thus when sorting and Bagnon is throwing items around, it causes a soft-error "That item doesn't go in that bag" (to paraphrase) and halts mid-sort with an item in-hand. It's not a fatal error or even a LUA error.

The workaround: I only have to put the in-hand item back into an empty slot and try sorting again. Usually it takes one more try to get it done although I've had to sort three times rarely.

Is there any way to smarten Bagnon to realize that it should only sort the ammo bags by themselves, then go for the normal ones in a second phase?  I'm curious if other users have noticed the behavior with other types of limited-item-type bags? (Herb, Enchanting, etc)

**Comment by Bliss1338** [comment]
Yap, have the same issue with my hunter.
it seems like the the order of the bags are reversed. if the ammo bag is equipt, the addon starts to sort he picked up items in the last bag.
