### ISSUE TITLE
classic and retail versions

### ISSUE THREAD

**Issue by Racerx323** [tullamods/Bagnon#1014]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.2.16
 - Server patch: 8.2.5

 **Have you read the changelog? (please don't waste our time)**
 yes

**Describe the bug**
Twitch client keeps replacing the retail version of the addon with the classic version. I opened a ticket with Twitch and they stated it was an addon author issue.

**To Reproduce**
Update the addon in Twitch client

**Expected behaviour**
Update to latest retail version of the addon

**Comment by Jaliborc** [comment]
It isn't from our end, but shouldn't even matter anyway, as they are the same version with a different ID number.
