### ISSUE TITLE
1812x TinyInspect\libs\LibItemInfo.lua:130: attempt to compare string with number

### ISSUE THREAD

**Issue by Thrumbar** [tullamods/Bagnon#1016]
Posted this in TinyInspect as a possible bug and did not know which addon is at fault

**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.2.16-8.2.5
 - Server patch: 8.2.5.32305

 **Have you read the changelog? (please don't waste our time)**
 Mark if read. Yes

**Describe the bug**
Moving items into void storage upon clicking button to transfer the error happened but items were moved.

**To Reproduce**
Steps to reproduce the behaviour:
Was putting items into void storage

**Expected behaviour**
No error

**Error Logs**
1812x TinyInspect\libs\LibItemInfo.lua:130: attempt to compare string with number
TinyInspect\libs\LibItemInfo.lua:130: in function `GetContainerItemLevel'
TinyInspect\ItemLevel.lua:122: in function <TinyInspect\ItemLevel.lua:111>
TinyInspect\ItemLevel.lua:320: in function <TinyInspect\ItemLevel.lua:319>
[C]: in function `Update'
...eBagnon\common\Wildpants\components\item.lua:124: in function <...eBagnon\common\Wildpants\components\item.lua:119>
[C]: in function `Show'
...eBagnon\common\Wildpants\components\item.lua:29: in function `New'
...Ons\Bagnon\common\Wildpants\components\itemFrame.lua:123: in function `Layout'
Bagnon\components\vault\itemFrame.lua:49: in function <Bagnon\components\vault\itemFrame.lua:48>

Locals:
self = <table> {
 GetUnitItemLevel = <function> defined @TinyInspect\libs\LibItemInfo.lua:182
 GetStatsViaTooltip = <function> defined @TinyInspect\libs\LibItemInfo.lua:33
 HasLocalCached = <function> defined @TinyInspect\libs\LibItemInfo.lua:22
 GetContainerItemLevel = <function> defined @TinyInspect\libs\LibItemInfo.lua:129
 GetUnitItemInfo = <function> defined @TinyInspect\libs\LibItemInfo.lua:150
 GetItemInfo = <function> defined @TinyInspect\libs\LibItemInfo.lua:98
}
pid = "vault"
id = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare string with number"
tooltip = LibItemLevelTooltip1 {
 TopOverlay = <unnamed> {
 }
 shownMoneyFrames = 1
 numMoneyFrames = 1
 needsReset = true
 hasMoney = 1
 0 = <userdata>
 BottomOverlay = <unnamed> {
 }
 updateTooltip = 0.200000
}
ItemLevelPattern = "Item Level (%d+)"

**Additional context**

**Comment by Jaliborc** [comment]
This is a TinyInspect error
