### ISSUE TITLE
Keyring window

### ISSUE THREAD

**Issue by Morphyloon** [tullamods/Bagnon#1027]
This might also be a bug report since using Bagnon prevents the keyring window from appearing. Not sure if Bagnon ever supported the keyring in the past but it's here now as of the latest patch today.

I surmise the only support it requires is automatically dumping all items flagged as "keys" to go into that container when using the sorting function? Same as moving all (or as much as it can) "ammo" into the various ammo bags. Beyond that, I rather doubt any true sorting of the keyring contents ever needs to be performed unless aesthetics matter?

**Comment by Jaliborc** [comment]
Its not out yet in europe, will update tomorrow. Shouldn't be too hard, its just a new bag slot.

**Comment by shadowglen** [comment]
Any update?
I think you may need to make a change in wildpants.

**Comment by Ganbin** [comment]
I also don't see my keys in WoW classic. Something is planned for this?

**Comment by Jaliborc** [comment]
Still working on it

**Comment by ramboozer** [comment]
Must disable Bagnon and then you can open keyring using following script
/script ToggleBag(KEYRING_CONTAINER)

**Comment by Road-block** [comment]
Depending your level easiest key to get is workshop key from Gnomeregan probably.

**Comment by Jaliborc** [comment]
Released new beta version with keyring

**Comment by b-morgan** [comment]
Don't forget to change .toc to 11303

**Comment by Jaliborc** [comment]
Noted, changed for next version

**Comment by Jaliborc** [comment]
Unless someone reports an issue with the keyring (besides sorting), closing this issue tomorrow.

**Comment by ramboozer** [comment]
Only bug now is it displayed the wrong amount of open slots. Says I have 27 unused slots on Keyring...but the number is way over the amount. I think the MOST you can have on keyring is 12 unless im mistaken

**Comment by Road-block** [comment]
You are correct, max is 12.

**Comment by b-morgan** [comment]
I believe the max is 4, 8, or 12 depending on level. I'd be happy if there wasn't a "free slot" count on the keyring.

**Comment by Road-block** [comment]
It expands according to keys you collect but caps at 12

**Comment by ramboozer** [comment]
Yeah well it worked for all of 5minutes...gave me an error now bagnon ANY version will not work..

**Comment by Road-block** [comment]
It was a big refactoring of the addon and included libraries it'll probably take a while till all the kinks are ironed out.

**Comment by Hillage** [comment]
Hoping this helps - Tried beta version 8.2.19. Keyring slots show fine in Bagnon window, when I click on a keyring slot BugSack catches errors. Two errors are posted on pastebin below.

https://pastebin.com/ehyLmzc7

Seems like it's erroring trying to open another window or setting the highlight/focus. The keyring slots are empty, no key.

Side note - is the keyring bag slot icon handled by Bagnon or another mod? Having another full size bag seems weird, wondering if it can be made smaller or hidden, especially since the slots appear at the bottom of the Bagnon windows as-is.

**Comment by Road-block** [comment]
> Having another full size bag seems weird, wondering if it can be made smaller or hidden

You can show the bag bar and click the keyring to hide it.

**Comment by LynkOne** [comment]
Sorting inventory makes keys go to bags and left the keyring empty, so useless

**Comment by Jaliborc** [comment]
@Hillage I know what is casing all the click errors, but still trying to think of a solution. The current one is a "hotfix" that stops the "action blocked" problem, but causes those error messages.

**Comment by Herdna** [comment]
Hi i still cant use the keyring in wow classic! when i click on it,it just opens my bags.

**Comment by b-morgan** [comment]
@Herdna There is a beta version available with keyring support but it has bugs that might make it more painful to use than not having keyring support. Just be patient as keyring support is coming.

**Comment by Hillage** [comment]
Just checking in here - do we have specific reports of the bugs in the current 8.2.19 beta build? After getting the click bugs I reverted to the current release to avoid future issues until we have an update.

Please do let me/us know if we can do anything to help make the process of updating/bugfixing easier.

**Comment by Herdna** [comment]
> @Herdna There is a beta version available with keyring support but it has bugs that might make it more painful to use than not having keyring support. Just be patient as keyring support is coming.

Okey thanks for the info friend! Atleast now i know a fix is coming. :D

**Comment by Jaliborc** [comment]
@Hillage No just wait till the weekend when I'll have time to fix the issue. Its not a simple one.

**Comment by Jaliborc** [comment]
Clicking items fixed, so closing issue.
Better to start new thread for remaining issues (like sorting)

**Comment by Ganbin** [comment]
Thank you for the time to fix this issue. The last version work great for me and show the keyring bag :) Nice job
