### ISSUE TITLE
LUA Error when using item

### ISSUE THREAD

**Issue by Aergernis** [tullamods/Bagnon#1031]
when using item (right click) i get the following error:

1x [ADDON_ACTION_FORBIDDEN] AddOn 'Bagnon' hat versucht die geschützte Funktion 'UNKNOWN()' aufzurufen.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: ?
[C]: ?
[C]: ?
[C]: in function `UseContainerItem'
FrameXML\ContainerFrame.lua:1254: in function `ContainerFrameItemButton_OnClick'
[string "*:OnClick"]:12: in function <[string "*:OnClick"]:1>
[C]: ?

bagnon 8.2.18
wow classic 11303

**Comment by Road-block** [comment]
I was posting the same on the now closed ticket, I'll add it here as well to keep it in one place.

[issue 1023#comment](https://github.com/tullamods/Bagnon/issues/1023#issuecomment-565658271)

This is English client Classic 1.13.3, Bagnon 8.2.18

**Comment by Road-block** [comment]
#1029 is also the same issue
