### ISSUE TITLE
Sorting Keys

### ISSUE THREAD

**Issue by chkmyid** [tullamods/Bagnon#1032]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.2.18-1.13.2

 **Have you read the changelog? (please don't waste our time)**
Read

**Describe the bug**
When I click the Sort button, there is a phenomenon where items are arranged continuously and continuously without moving.
I had to type '/reload' to stop sorting.

**Screenshots**
Blizzard error frame loop: ERR_WRONG_BAG_TYPE
![WoWScrnShot_121419_152013](https://user-images.githubusercontent.com/55096941/70844584-dc60be00-1e86-11ea-8cc7-7d9284833e07.jpg)

**Comment by Road-block** [comment]
This also happens with 8.2.19 in Classic.

Other than reloadui you can also drag an item manually to another slot to stop it.

No Lua errors but it gets into an infinite loop of "That item doesn't go in that container" in errorframe.

**Comment by chkmyid** [comment]
8.2.19-1.13.3

When I pressed the Sort button, the key for the keyring did not appear in the inventory frame, but the sorting function was still not working properly.
The item does not move, but it looks like it is holding and leaving the quest item. This symptom repeats indefinitely and does not cause an error message.
I had to enter "/reload" in the chat window because there was no way I could stop this bug symptom.

**Comment by cherry-wave** [comment]
Came here to say that too, sorting is now broken thanks to the key bag^^

**Comment by thethufir** [comment]
I have just posted a similar issue. It attempts to sort the relic coffer key into the keyring where it can't go. Causing this same issue.

**Comment by agirmar92** [comment]
I am also having this problem :(

**Comment by jslamartina** [comment]
I'm seeing the same issue. If I then move the keys to my bags, then do a sort, it will sort fine. But then subsequently moving my keys back to my keyring will then cause the sort to move those keys from my keyring into my bags.

**Comment by eaigner** [comment]
I don't get why keyrings and soulbags arent excluded from sorting.

**Comment by semlieguy** [comment]
(classic) Having the same issue. However it also tries to put the scepter for mara in the keyring as well. 
The sorting option also pulls the keys from the bag. I did not have to /reload when it would continuously try to put items that wouldn't go into keyring, I just clicked a different item in my bag as if I were to pull it out and it stopped.

**Comment by thebgpikester** [comment]
Coffer key victim here too.

**Comment by dmikov** [comment]
Why not make sort on visible bags only. Will take care of any special bags or the ones we sorted ourselves. Like my healing gear on feral druid.

**Comment by Paragon1337** [comment]
I am also having this problem

**Comment by chkmyid** [comment]
8.2.25-1.13.3

When the item was blinking without moving in a certain slot, the mouse pointer showed me the two keys that I had crossed. The key in the keyring slot hasn't moved, but I think this is the bug associated with the keyring.

@semlieguy Wow..Thank you for giving me a hint to stop this without reloading.

**Comment by d3spwn** [comment]
Bug still present in 8.2.25-1.13.3.

**Comment by slappieh** [comment]
Same issue.

**Comment by rafa2k** [comment]
Same issue.  I updated yesterday and got the continuous sort loop when I have keys in my bag.  It continues to pop up the message "That item doesn't go in that container."  If I take the keys out of my bag (put them in the bank) the sort works fine.   Even if I manually move all the keys to the keyring, it breaks the sort.

I updated again this morning hoping the new update would fix it but the issue remains.

**Comment by thethufir** [comment]
Yep, issue is still here in the newest version. This bug makes this addon useless currently, i'll have to switch to another :/

**Comment by Pendraig** [comment]
Same issue, endless loop while trying to sort items when keys are stored directly in the new keyring bag.  Sort works correctly when *no* keys are in the keyring bag.  Appears the sort logic is having problems with quest-related keys, e.g. Scarlet Key, Key to Searing Gorge.

**Comment by StephenHepp** [comment]
my dirty fix is you gotta edit Sort:GetSpaces() in Bagnon\common\Wildpants\api\sorting.lua
and wrap the body of the for loop in

> if not (bag == KEYRING_CONTAINER) then

**Comment by chkmyid** [comment]
8.2.26-1.13.3

This issue is not resolved in the latest release version yet.

**Comment by dahager** [comment]
also have the same issue with key/keychain... so cleanup is broken..

**Comment by Pendraig** [comment]
Latest update still has not corrected the key sort issue.  Testing methodology:

* Disabled *all* installed addons *except* BagBrother, Bagnon, Bagnon Config, Bagnon Guild Bank & Bagnon Void Storage
* Displayed bags with various keys present in the key ring\bag, both soulbound (e.g. Crescent Key, Key to Searing Gorge) and quest items (e.g. Skeleton Key, Shadowforge Key)
* Launched cleanup - endless loop ... broke via /console reloadui
* Put all keys into the bank
* Cleaned bank ... no problem
* Cleaned bags ... no problem

**Comment by Jaliborc** [comment]
how's 8.2.27 performing regarding this?

**Comment by innominat3** [comment]
> how's 8.2.27 performing regarding this?

It seems to be working fine now

**Comment by Jaliborc** [comment]
Great! Hopefully it will even sort the keys.

**Comment by Jaliborc** [comment]
Unless an issue is reported with 8.2.27, I'll be closing this tomorrow.

...
27th try is the charm?

**Comment by LukeTinyT** [comment]
Seems fixed on my end at least!

**Comment by chkmyid** [comment]
@Jaliborc It's working well with the latest version. Thank you for your efforts.

**Comment by Paragon1337** [comment]
Fixed, thanks for the effort and time
