### ISSUE TITLE
[Classic] Shift-linking items from bags.

### ISSUE THREAD

**Issue by Road-block** [tullamods/Bagnon#1040]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.2.19
 - Server patch: 1.13.3

 **Have you read the changelog? (please don't waste our time)**
 Yes

**Describe the bug**
Shift-clicking an item in bags to link it to chat causes a Lua error

**To Reproduce**
Steps to reproduce the behaviour:
1. Open bags.
2. Shift-click an item to link to chat.

**Expected behaviour**

**Screenshots**

**Error Logs**
```
1x ...mon\Wildpants\libs\MutexDelay-1.0\MutexDelay-1.0-1.lua:33: attempt to call field '?' (a nil value)
...mon\Wildpants\libs\MutexDelay-1.0\MutexDelay-1.0-1.lua:33: in function <...mon\Wildpants\libs\MutexDelay-1.0\MutexDelay-1.0.lua:30>
```
```
1x ...face\Bagnon\common\Wildpants\classes\item-[Dark Iron Residue]x7.lua:215: attempt to call method 'Super' (a nil value)
...face\Bagnon\common\Wildpants\classes\item-[Dark Iron Residue]x7.lua:215: in function <...face\Bagnon\common\Wildpants\classes\item.lua:214>
```
```
1x ...face\Bagnon\common\Wildpants\classes\item-[Dark Iron Residue]x7.lua:123: attempt to call method 'IsNew' (a nil value)
...face\Bagnon\common\Wildpants\classes\item-[Dark Iron Residue]x7.lua:123: in function <...face\Bagnon\common\Wildpants\classes\item.lua:118>
[C]:: in function 'Hide'
...erface\Bagnon\common\Wildpants\api\frames.lua:94: in function 'Hide'
Bagnon\addons\main\frame.lua:28: in function <Bagnon\addons\main\frame.lua:28>
```

**Additional context**

**Comment by gomisensei** [comment]
i get the same error opening auction house, closing auction house and similar errors (all wildpants) when pressing b to open bags, and opening bank.  The actions work, but the errors keep popping up.

**Comment by Jaliborc** [comment]
fixed
