### ISSUE TITLE
...ce\AddOns\Bagnon\common\Wildpants\classes\tipped.lua:14: attempt to call method 'IsOwned' (a nil value)

### ISSUE THREAD

**Issue by shamdanirms** [tullamods/Bagnon#1041]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.2.18
 - Server patch: [e.g. Build 8.2.5]

 **Have you read the changelog? (please don't waste our time)**
 Mark if read.

**Describe the bug**
Everytime i open bags in bagnon

Message: ...ce\AddOns\Bagnon\common\Wildpants\classes\tipped.lua:14: attempt to call method 'IsOwned' (a nil value)
Time: Sat Dec 14 11:48:26 2019
Count: 15
Stack: ...ce\AddOns\Bagnon\common\Wildpants\classes\tipped.lua:14: attempt to call method 'IsOwned' (a nil value)
[C]: in function `IsOwned'
...ce\AddOns\Bagnon\common\Wildpants\classes\tipped.lua:14: in function <...ce\AddOns\Bagnon\common\Wildpants\classes\tipped.lua:9>
(tail call): ?
...face\AddOns\Bagnon\common\Wildpants\classes\item.lua:215: in function <...face\AddOns\Bagnon\common\Wildpants\classes\item.lua:214>

**To Reproduce**
Steps to reproduce the behaviour:
1) Open bags

**Expected behaviour**
No errors on opening bags.

**Screenshots**

**Error Logs**
Message: ...ce\AddOns\Bagnon\common\Wildpants\classes\tipped.lua:14: attempt to call method 'IsOwned' (a nil value)
Time: Sat Dec 14 11:48:26 2019
Count: 15
Stack: ...ce\AddOns\Bagnon\common\Wildpants\classes\tipped.lua:14: attempt to call method 'IsOwned' (a nil value)
[C]: in function `IsOwned'
...ce\AddOns\Bagnon\common\Wildpants\classes\tipped.lua:14: in function <...ce\AddOns\Bagnon\common\Wildpants\classes\tipped.lua:9>
(tail call): ?
...face\AddOns\Bagnon\common\Wildpants\classes\item.lua:215: in function <...face\AddOns\Bagnon\common\Wildpants\classes\item.lua:214>

**Additional context**

**Comment by Wyzbang** [comment]
I am getting a similar error when I try to access anything in my bags, Disenchant, feed pet, etc.

**Comment by Owndead** [comment]
> 
> 
> I am getting a similar error when I try to access anything in my bags, Disenchant, feed pet, etc.

Same, can't disenchant. Also after the error msg pops up from trying to disenchant and I swap items in my inventory, this happens: https://i.imgur.com/76aRCLy.jpg

**Comment by backzter** [comment]
I have the same issue

**Comment by AGirlYouKnow** [comment]
I also have this issue. Happens when I try to split stacks of items as well.

**Comment by the-quality** [comment]
jap, same here

47x ...ceBagnon\common\Wildpants\classes\tipped.lua:14: attempt to call method 'IsOwned' (a nil value)
...ceBagnon\common\Wildpants\classes\tipped.lua:14: in function <...ceBagnon\common\Wildpants\classes\tipped.lua:9>
(tail call): ?
...faceBagnon\common\Wildpants\classes\item.lua:215: in function `OnLeave'
...faceBagnon\common\Wildpants\classes\item.lua:210: in function <...faceBagnon\common\Wildpants\classes\item.lua:200>

Locals:
self = ContainerFrame3Item10 {
 timeSinceUpgradeCheck = 0
 PostOnLoad = <function> defined @FrameXML\ItemButtonTemplate.lua:169
 BattlepayItemTexture = <unnamed> {
 }
 IconOverlay = <unnamed> {
 }
 BagStaticTop = <unnamed> {
 }
 Flash = <unnamed> {
 }
 GetItemContextMatchResult = <function> defined @FrameXML\ContainerFrame.lua:1463
 IconBorder = <unnamed> {
 }
 newitemglowAnim = <unnamed> {
 }
 icon = ContainerFrame3Item10IconTexture {
 }
 LevelLinkLockTexture = <unnamed> {
 }
 RegisterCallback = <function> defined @FrameXML\ItemButtonTemplate.lua:175
 UnregisterCallback = <function> defined @FrameXML\ItemButtonTemplate.lua:182
 PostOnHide = <function> defined @FrameXML\ItemButtonTemplate.lua:198
 NewItemTexture = <unnamed> {
 }
 Cooldown = ContainerFrame3Item10Cooldown {
 }
 BagStaticBottom = <unnamed> {
 }
 0 = <userdata>
 ItemContextOverlay = <unnamed> {
 }
 PostOnShow = <function> defined @FrameXML\ItemButtonTemplate.lua:189
 flash = <unnamed> {
 }
 itemContextChangedCallbackIsSet = true
 itemContextMatchResult = 3
 count = 0
 ExtendedSlot = <unnamed> {
 }
 ExtendedOverlay2 = <unnamed> {
 }
 flashAnim = <unnamed> {
 }
 info = <table> {
 }
 JunkIcon = <unnamed> {
 }
 SetMatchesSearch = <function> defined @FrameXML\ItemButtonTemplate.lua:202
 UpdateItemContextOverlay = <function> defined @FrameXML\ItemButtonTemplate.lua:222
 bag = 3
 frame = <unnamed> {
 }
 QuestBorder = ContainerFrame3Item10IconQuestTexture {
 }
 IconGlow = <unnamed> {
 }
 itemContextChangedCallback = <function> defined @FrameXML\ItemButtonTemplate.lua:170
 Count = ContainerFrame3Item10Count {
 }
 ExtendedOverlay = <unnamed> {
 }
 UpgradeIcon = <unnamed> {
 }
 GetMatchesSearch = <function> defined @FrameXML\ItemButtonTemplate.lua:207
 UpdateItemContextMatching = <function> defined @FrameXML\ItemButtonTemplate.lua:211
 searchOverlay = ContainerFrame3Item10SearchOverlay {
 }
}
(*temporary) = nil
(*temporary) = BattlePetTooltip {
 0 = <userdata>
 BorderBottomLeft = <unnamed> {
 }
 Owned = <unnamed> {
 }
 SpeedTexture = <unnamed> {
 }
 Background = <unnamed> {
 }
 HealthTexture = <unnamed> {
 }
 Speed = <unnamed> {
 }
 BorderTop = <unnamed> {
 }
 PetType = <unnamed> {
 }
 BorderTopLeft = <unnamed> {
 }
 BorderTopRight = <unnamed> {
 }
 BorderLeft = <unnamed> {
 }
 Power = <unnamed> {
 }
 PowerTexture = <unnamed> {
 }
 PetTypeTexture = <unnamed> {
 }
 BattlePet = <unnamed> {
 }
 Name = <unnamed> {
 }
 Health = <unnamed> {
 }
 Level = <unnamed> {
 }
 BorderBottom = <unnamed> {
 }
 BorderBottomRight = <unnamed> {
 }
 BorderRight = <unnamed> {
 }
}
(*temporary) = ContainerFrame3Item10 {
 timeSinceUpgradeCheck = 0
 PostOnLoad = <function> defined @FrameXML\ItemButtonTemplate.lua:169
 BattlepayItemTexture = <unnamed> {
 }
 IconOverlay = <unnamed> {
 }
 BagStaticTop = <unnamed> {
 }
 Flash = <unnamed> {
 }
 GetItemContextMatchResult = <function> defined @FrameXML\ContainerFrame.lua:1463
 IconBorder = <unnamed> {
 }
 newitemglowAnim = <unnamed> {
 }
 icon = ContainerFrame3Item10IconTexture {
 }
 LevelLinkLockTexture = <unnamed> {
 }
 RegisterCallback = <function> defined @FrameXML\ItemButtonTemplate.lua:175
 UnregisterCallback = <function> defined @FrameXML\ItemButtonTemplate.lua:182
 PostOnHide = <function> defined @FrameXML\ItemButtonTemplate.lua:198
 NewItemTexture = <unnamed> {
 }
 Cooldown = ContainerFrame3Item10Cooldown {
 }
 BagStaticBottom = <unnamed> {
 }
 0 = <userdata>
 ItemContextOverlay = <unnamed> {
 }
 PostOnShow = <function> defined @FrameXML\ItemButtonTemplate.lua:189
 flash = <unnamed> {
 }
 itemContextChangedCallbackIsSet = true
 itemContextMatchResult = 3
 count = 0
 ExtendedSlot = <unnamed> {
 }
 ExtendedOverlay2 = <unnamed> {
 }
 flashAnim = <unnamed> {
 }
 info = <table> {
 }
 JunkIcon = <unnamed> {
 }
 SetMatchesSearch = <function> defined @FrameXML\ItemButtonTemplate.lua:202
 UpdateItemContextOverlay = <function> defined @FrameXML\ItemButtonTemplate.l
