### ISSUE TITLE
Just a small problem Wow Classic

### ISSUE THREAD

**Issue by Owndead** [tullamods/Bagnon#1049]
Just a small problem on Wow Classic.

When I hover over an item (like a trinket) and hold shift, it doesn't show the current equipped items for comparison like it used to. But if I continue to hold shift and move the cursor to a new item in my inventory, then it works, and if I move the cursor back to the first item, it works again. 

So if I'm already hovering over the item and then press shift it doesn't work, but when I'm already holding shift when I hover over the item it works.

I'm on Wow classic and using the version that released yesterday (8.2.20 I think it is). There was no error message that popped up.

Thanks in advance, this is probably the addon I depend most on in wow classic. So thank you.

**Comment by Jaliborc** [comment]
Nice catch. Thats weird af btw

**Comment by radevm** [comment]
confirming for retail

**Comment by Jaliborc** [comment]
Think I found the cause
