### ISSUE TITLE
Number of free slots display on Keyring

### ISSUE THREAD

**Issue by b-morgan** [tullamods/Bagnon#1050]
When empty, the keyring displays 32 as the number of free slots. The maximum size of the keyring in Classic is 12 slots so 32 is just plain wrong. The keyring also varies in capacity depending on level:
- Levels 1-40 players will have 4 slots on their keyring.
- Levels 41-50 players will have 8 slots on their keyring.
- Levels 51-60 players will have 12 slots on their keyring.

IMO, the best solution is to not display a free slot count at all.

**Comment by Jaliborc** [comment]
Yeah, the server acts as if there were 32 slots. Its really annoying

**Comment by Jaliborc** [comment]
Fixed
