### ISSUE TITLE
Lua errors while mousing over or moving items in bags

### ISSUE THREAD

**Issue by b-morgan** [tullamods/Bagnon#1051]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.2.21-1.13.2
 - Server patch: 1.13.3-32836

 **Have you read the changelog? (please don't waste our time)**
Yes

**Describe the bug**
Moused over bags while Auction House window was open caused a Lua error.

**To Reproduce**
Steps to reproduce the behaviour:
I cannot reproduce this error.

**Expected behaviour**
I did not expect a Lua error.

**Error Logs**
1x ...faceBagnon\common\Wildpants\classes\item.lua:254: attempt to call method 'UpdateTooltip' (a nil value)
...faceBagnon\common\Wildpants\classes\item.lua:254: in function `func'
...mon\Wildpants\libs\MutexDelay-1.0\MutexDelay-1.0-2.lua:36: in function <...mon\Wildpants\libs\MutexDelay-1.0\MutexDelay-1.0.lua:30>

Locals:
self = ContainerFrame1Item4 {
 CreateDummySlot = <function> defined @Bagnon\common\Wildpants\classes\item.lua:451
 OnEnter = <function> defined @Bagnon\common\Wildpants\classes\item.lua:207
 __super = <table> {
 }
 GetSlotType = <function> defined @Bagnon\common\Wildpants\classes\item.lua:433
 IconOverlay = <unnamed> {
 }
 SlotTypes = <table> {
 }
 UpdateCooldown = <function> defined @Bagnon\common\Wildpants\classes\item.lua:322
 Bind = <function> defined @Bagnon\common\Wildpants\classes\item.lua:102
 IconBorder = <unnamed> {
 }
 flashAnim = <unnamed> {
 }
 SetLocked = <function> defined @Bagnon\common\Wildpants\classes\item.lua:318
 OnShow = <function> defined @Bagnon\common\Wildpants\classes\item.lua:123
 ExtendedOverlay = <unnamed> {
 }
 __type = "Button"
 __count = 3
 GetFrameID = <function> defined @Bagnon\common\Wildpants\classes\parented.lua:19
 IsAbstract = <function> defined @Bagnon\common\Wildpants\libs\Poncho-2.0\Poncho-2.0.lua:97
 NewItemTexture = <unnamed> {
 }
 IsQuestItem = <function> defined @Bagnon\common\Wildpants\classes\item.lua:392
 SplitStack = <function> defined @FrameXML\ContainerFrame.lua:1060
 count = 2
 readable = false
 BagStaticBottom = <unnamed> {
 }
 frame = <unnamed> {
 }
 UpdateLocked = <function> defined @Bagnon\common\Wildpants\classes\item.lua:241
 UnregisterMessage = <function> defined @Accountant_Classic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 Update = <function> defined @Bagnon\common\Wildpants\classes\item.lua:229
 flash = <unnamed> {
 }
 info = <table> {
 }
 RegisterFrameSignal = <function> defined @Bagnon\common\Wildpants\classes\base.lua:15
 Super = <function> defined @Bagnon\common\Wildpants\libs\Poncho-2.0\Poncho-2.0.lua:138
 GetBlizzard = <function> defined @Bagnon\common\Wildpants\classes\item.lua:89
 UpdateSearch = <function> defined @Bagnon\common\Wildpants\classes\item.lua:334
 hasItem = true
 RegisterMessage = <function> defined @Accountant_Classic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 SendFrameSignal = <function> defined @Bagnon\common\Wildpants\classes\base.lua:23
 UnregisterSignal = <function> defined @Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:78
 IconGlow = <unnamed> {
 }
 GetOwner = <function> defined @Bagnon\common\Wildpants\classes\parented.lua:31
 __name = "BagnonItem"
 GetProfile = <function> defined @Bagnon\common\Wildpants\classes\parented.lua:23
 SendMessage = <function> defined @Accountant_Classic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 0 = <userdata>
 GetClass = <function> defined @Bagnon\common\Wildpants\libs\Poncho-2.0\Poncho-2.0.lua:116
 GetSuper = <function> defined @Bagnon\common\Wildpants\libs\Poncho-2.0\Poncho-2.0.lua:85
 Count = ContainerFrame1Item4Count {
 }
 OnPreClick = <function> defined @Bagnon\common\Wildpants\classes\item.lua:147
 searchOverlay = ContainerFrame1Item4SearchOverlay {
 }
 Construct = <function> defined @Bagnon\common\Wildpants\classes\item.lua:47
 GetTemplate = <function> defined @Bagnon\common\Wildpants\libs\Poncho-2.0\Poncho-2.0.lua:89
 IsSlot = <function> defined @Bagnon\common\Wildpants\classes\item.lua:417
 bag = 0
 BattlepayItemTexture = <unnamed> {
 }
 OnModifiedClick = <function> defined @Bagnon\common\Wildpants\classes\item.lua:200
 NumInactive = <function> defined @Bagnon\common\Wildpants\libs\Poncho-2.0\Poncho-2.0.lua:105
 GetTipAnchor = <function> defined @Bagnon\common\Wildpants\classes\tipped.lua:19
 BagStaticTop = <unnamed> {
 }
 Flash = <unnamed> {
 }
 GetFrameType = <function> defined @Bagno

**Comment by b-morgan** [comment]
This happened again on a different toon. I collected a locked box from the mail, unlocked it, and got the error when I opened the box and removed the contents. I won't be able to attempt to reproduce
until I get another locked box. 

1x ...faceBagnon\common\Wildpants\classes\item.lua:254: attempt to call method 'UpdateTooltip' (a nil value)
...faceBagnon\common\Wildpants\classes\item.lua:254: in function `func'
...mon\Wildpants\libs\MutexDelay-1.0\MutexDelay-1.0-2.lua:36: in function <...mon\Wildpants\libs\MutexDelay-1.0\MutexDelay-1.0.lua:30>

Locals:
self = ContainerFrame1Item33 {
 CreateDummySlot = <function> defined @Bagnon\common\Wildpants\classes\item.lua:451
 OnEnter = <function> defined @Bagnon\common\Wildpants\classes\item.lua:207
 __super = <table> {
 }
 GetSlotType = <function> defined @Bagnon\common\Wildpants\classes\item.lua:433
 IconOverlay = <unnamed> {
 }
 SlotTypes = <table> {
 }
 UpdateCooldown = <function> defined @Bagnon\common\Wildpants\classes\item.lua:322
 Bind = <function> defined @Bagnon\common\Wildpants\classes\item.lua:102
 IconBorder = <unnamed> {
 }
 flashAnim = <unnamed> {
 }
 SetLocked = <function> defined @Bagnon\common\Wildpants\classes\item.lua:318
 OnShow = <function> defined @Bagnon\common\Wildpants\classes\item.lua:123
 ExtendedOverlay = <unnamed> {
 }
 __type = "Button"
 __count = 32
 GetFrameID = <function> defined @Bagnon\common\Wildpants\classes\parented.lua:19
 NewItemTexture = <unnamed> {
 }
 IsQuestItem = <function> defined @Bagnon\common\Wildpants\classes\item.lua:392
 SplitStack = <function> defined @FrameXML\ContainerFrame.lua:1060
 count = 0
 BagStaticBottom = <unnamed> {
 }
 frame = <unnamed> {
 }
 UpdateLocked = <function> defined @Bagnon\common\Wildpants\classes\item.lua:241
 UnregisterMessage = <function> defined @Accountant_Classic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 Update = <function> defined @Bagnon\common\Wildpants\classes\item.lua:229
 flash = <unnamed> {
 }
 info = <table> {
 }
 RegisterFrameSignal = <function> defined @Bagnon\common\Wildpants\classes\base.lua:15
 Super = <function> defined @Bagnon\common\Wildpants\libs\Poncho-2.0\Poncho-2.0.lua:138
 GetBlizzard = <function> defined @Bagnon\common\Wildpants\classes\item.lua:89
 UpdateSearch = <function> defined @Bagnon\common\Wildpants\classes\item.lua:334
 RegisterMessage = <function> defined @Accountant_Classic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 SendFrameSignal = <function> defined @Bagnon\common\Wildpants\classes\base.lua:23
 UnregisterSignal = <function> defined @Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:78
 IconGlow = <unnamed> {
 }
 GetOwner = <function> defined @Bagnon\common\Wildpants\classes\parented.lua:31
 __name = "BagnonItem"
 GetProfile = <function> defined @Bagnon\common\Wildpants\classes\parented.lua:23
 SendMessage = <function> defined @Accountant_Classic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 0 = <userdata>
 GetClass = <function> defined @Bagnon\common\Wildpants\libs\Poncho-2.0\Poncho-2.0.lua:116
 IsAbstract = <function> defined @Bagnon\common\Wildpants\libs\Poncho-2.0\Poncho-2.0.lua:97
 GetSuper = <function> defined @Bagnon\common\Wildpants\libs\Poncho-2.0\Poncho-2.0.lua:85
 Count = ContainerFrame1Item33Count {
 }
 OnPreClick = <function> defined @Bagnon\common\Wildpants\classes\item.lua:147
 searchOverlay = ContainerFrame1Item33SearchOverlay {
 }
 Construct = <function> defined @Bagnon\common\Wildpants\classes\item.lua:47
 GetTemplate = <function> defined @Bagnon\common\Wildpants\libs\Poncho-2.0\Poncho-2.0.lua:89
 IsSlot = <function> defined @Bagnon\common\Wildpants\classes\item.lua:417
 bag = 2
 BattlepayItemTexture = <unnamed> {
 }
 OnModifiedClick = <function> defined @Bagnon\common\Wildpants\classes\item.lua:200
 NumInactive = <function> defined @Bagnon\common\Wildpants\libs\Poncho-2.0\Poncho-2.0.lua:105
 GetTipAnchor = <function> defined @Bagnon\common\Wildpants\classes\tipped.lua:19
 BagStaticTop = <unnamed> {
 }
 Flash = <unnamed> {
 }
 GetFrameType = <function> defined @Bagnon\common\Wildpants\libs\Poncho

**Comment by b-morgan** [comment]
Another one, right click an item in my inventory while at the bank.

1x ...faceBagnon\common\Wildpants\classes\item.lua:254: attempt to call method 'UpdateTooltip' (a nil value)
...faceBagnon\common\Wildpants\classes\item.lua:254: in function `func'
...mon\Wildpants\libs\MutexDelay-1.0\MutexDelay-1.0-2.lua:36: in function <...mon\Wildpants\libs\MutexDelay-1.0\MutexDelay-1.0.lua:30>

Locals:
self = ContainerFrame1Item32 {
 CreateDummySlot = <function> defined @Bagnon\common\Wildpants\classes\item.lua:451
 OnEnter = <function> defined @Bagnon\common\Wildpants\classes\item.lua:207
 __super = <table> {
 }
 GetSlotType = <function> defined @Bagnon\common\Wildpants\classes\item.lua:433
 IconOverlay = <unnamed> {
 }
 SlotTypes = <table> {
 }
 UpdateCooldown = <function> defined @Bagnon\common\Wildpants\classes\item.lua:322
 Bind = <function> defined @Bagnon\common\Wildpants\classes\item.lua:102
 IconBorder = <unnamed> {
 }
 flashAnim = <unnamed> {
 }
 SetLocked = <function> defined @Bagnon\common\Wildpants\classes\item.lua:318
 OnShow = <function> defined @Bagnon\common\Wildpants\classes\item.lua:123
 ExtendedOverlay = <unnamed> {
 }
 __type = "Button"
 __count = 31
 GetFrameID = <function> defined @Bagnon\common\Wildpants\classes\parented.lua:19
 IsAbstract = <function> defined @Bagnon\common\Wildpants\libs\Poncho-2.0\Poncho-2.0.lua:97
 NewItemTexture = <unnamed> {
 }
 IsQuestItem = <function> defined @Bagnon\common\Wildpants\classes\item.lua:392
 SplitStack = <function> defined @FrameXML\ContainerFrame.lua:1060
 count = 0
 BagStaticBottom = <unnamed> {
 }
 frame = <unnamed> {
 }
 UpdateLocked = <function> defined @Bagnon\common\Wildpants\classes\item.lua:241
 UnregisterMessage = <function> defined @Accountant_Classic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 Update = <function> defined @Bagnon\common\Wildpants\classes\item.lua:229
 flash = <unnamed> {
 }
 info = <table> {
 }
 RegisterFrameSignal = <function> defined @Bagnon\common\Wildpants\classes\base.lua:15
 Super = <function> defined @Bagnon\common\Wildpants\libs\Poncho-2.0\Poncho-2.0.lua:138
 GetBlizzard = <function> defined @Bagnon\common\Wildpants\classes\item.lua:89
 UpdateSearch = <function> defined @Bagnon\common\Wildpants\classes\item.lua:334
 RegisterMessage = <function> defined @Accountant_Classic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 SendFrameSignal = <function> defined @Bagnon\common\Wildpants\classes\base.lua:23
 UnregisterSignal = <function> defined @Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:78
 IconGlow = <unnamed> {
 }
 GetOwner = <function> defined @Bagnon\common\Wildpants\classes\parented.lua:31
 __name = "BagnonItem"
 GetProfile = <function> defined @Bagnon\common\Wildpants\classes\parented.lua:23
 SendMessage = <function> defined @Accountant_Classic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 0 = <userdata>
 GetClass = <function> defined @Bagnon\common\Wildpants\libs\Poncho-2.0\Poncho-2.0.lua:116
 GetSuper = <function> defined @Bagnon\common\Wildpants\libs\Poncho-2.0\Poncho-2.0.lua:85
 Count = ContainerFrame1Item32Count {
 }
 OnPreClick = <function> defined @Bagnon\common\Wildpants\classes\item.lua:147
 searchOverlay = ContainerFrame1Item32SearchOverlay {
 }
 Construct = <function> defined @Bagnon\common\Wildpants\classes\item.lua:47
 GetTemplate = <function> defined @Bagnon\common\Wildpants\libs\Poncho-2.0\Poncho-2.0.lua:89
 IsSlot = <function> defined @Bagnon\common\Wildpants\classes\item.lua:417
 bag = 2
 BattlepayItemTexture = <unnamed> {
 }
 OnModifiedClick = <function> defined @Bagnon\common\Wildpants\classes\item.lua:200
 NumInactive = <function> defined @Bagnon\common\Wildpants\libs\Poncho-2.0\Poncho-2.0.lua:105
 GetTipAnchor = <function> defined @Bagnon\common\Wildpants\classes\tipped.lua:19
 BagStaticTop = <unnamed> {
 }
 Flash = <unnamed> {
 }
 GetFrameType = <function> defined @Bagnon\common\Wildpants\libs\Poncho

**Comment by b-morgan** [comment]
I'm returning to version 8.2.16-1.13.2 until this gets sorted out.

**Comment by Jaliborc** [comment]
already fixed internally
