### ISSUE TITLE
Keyring Display

### ISSUE THREAD

**Issue by witchpiggie** [tullamods/Bagnon#1053]
**Add Option: Show/Hide Keyring**

Thanks for adding keyring support. What I am missing from this is an option to hide the keyring from the display. Most of the time I will not need to look at it and would like the frame to be more compact. If this option already exists, I am not seeing it.

**Comment by tehKD** [comment]
It is allready there. Click the Bag Slots button (the one that looks like a bag) and then select the bags you want to be displayed.

**Comment by witchpiggie** [comment]
Oh. I knew this was possible with the standard bags, but I didn't look there for this feature. Thanks.
