### ISSUE TITLE
8.2.21 LUA error when mousing around in the bag item frame, repeatable

### ISSUE THREAD

**Issue by raysmith59** [tullamods/Bagnon#1059]
18x ...ceBagnon\common\Wildpants\classes\tipped.lua:14: attempt to call method 'IsOwned' (a nil value)
...ceBagnon\common\Wildpants\classes\tipped.lua:14: in function <...ceBagnon\common\Wildpants\classes\tipped.lua:9>
(tail call): ?
...faceBagnon\common\Wildpants\classes\item.lua:222: in function <...faceBagnon\common\Wildpants\classes\item.lua:221>

Locals:
self = ContainerFrame1Item2 {
 timeSinceUpgradeCheck = 0
 PostOnLoad = <function> defined @FrameXML\ItemButtonTemplate.lua:169
 GetSlotType = <function> defined @Bagnon\common\Wildpants\classes\item.lua:433
 IconOverlay = <unnamed> {
 }
 SlotTypes = <table> {
 }
 Super = <function> defined @Bagnon\common\Wildpants\libs\Poncho-2.0\Poncho-2.0.lua:138
 flashAnim = <unnamed> {
 }
 SetLocked = <function> defined @Bagnon\common\Wildpants\classes\item.lua:318
 GetTemplate = <function> defined @Bagnon\common\Wildpants\libs\Poncho-2.0\Poncho-2.0.lua:89
 IsCached = <function> defined @Bagnon\common\Wildpants\classes\parented.lua:35
 itemContextChangedCallbackIsSet = true
 GetFrame = <function> defined @Bagnon\common\Wildpants\classes\parented.lua:39
 PostOnHide = <function> defined @FrameXML\ItemButtonTemplate.lua:198
 NewItemTexture = <unnamed> {
 }
 IsQuestItem = <function> defined @Bagnon\common\Wildpants\classes\item.lua:392
 GetBaseProfile = <function> defined @Bagnon\common\Wildpants\classes\parented.lua:27
 RegisterMessage = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 Update = <function> defined @Bagnon\common\Wildpants\classes\item.lua:229
 GetInfo = <function> defined @Bagnon\common\Wildpants\classes\item.lua:421
 UpdateItemContextOverlay = <function> defined @FrameXML\ItemButtonTemplate.lua:222
 Count = ContainerFrame1Item2Count {
 }
 OnPreClick = <function> defined @Bagnon\common\Wildpants\classes\item.lua:147
 searchOverlay = ContainerFrame1Item2SearchOverlay {
 }
 Construct = <function> defined @Bagnon\common\Wildpants\classes\item.lua:47
 SendSignal = <function> defined @Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:82
 bag = 0
 GetTipAnchor = <function> defined @Bagnon\common\Wildpants\classes\tipped.lua:19
 __template = "ContainerFrameItemButtonTemplate"
 Flash = <unnamed> {
 }
 OnItemFlashed = <function> defined @Bagnon\common\Wildpants\classes\item.lua:350
 OnClick = <function> defined @Bagnon\common\Wildpants\classes\item.lua:186
 GetSuper = <function> defined @Bagnon\common\Wildpants\libs\Poncho-2.0\Poncho-2.0.lua:85
 RegisterCallback = <function> defined @FrameXML\ItemButtonTemplate.lua:175
 UnregisterCallback = <function> defined @FrameXML\ItemButtonTemplate.lua:182
 UnregisterFrameSignal = <function> defined @Bagnon\common\Wildpants\classes\base.lua:19
 Release = <function> defined @Bagnon\common\Wildpants\libs\Poncho-2.0\Poncho-2.0.lua:120
 Cooldown = ContainerFrame1Item2Cooldown {
 }
 Tag = "BAGNON_"
 NewClass = <function> defined @Bagnon\common\Wildpants\classes\base.lua:9
 GetOwnerInfo = <function> defined @Bagnon\common\Wildpants\classes\base.lua:32
 IsNew = <function> defined @Bagnon\common\Wildpants\classes\item.lua:409
 ExtendedOverlay2 = <unnamed> {
 }
 IsPaid = <function> defined @Bagnon\common\Wildpants\classes\item.lua:413
 __index = <table> {
 }
 __name = "BagnonItem"
 RegisterSignal = <function> defined @Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:74
 IsActive = <function> defined @Bagnon\common\Wildpants\libs\Poncho-2.0\Poncho-2.0.lua:134
 IsUpgrade = <function> defined @Bagnon\common\Wildpants\classes\item.lua:403
 UpdateFocus = <function> defined @Bagnon\common\Wildpants\classes\item.lua:342
 NumActive = <function> defined @Bagnon\common\Wildpants\libs\Poncho-2.0\Poncho-2.0.lua:101
 GetItem = <function> defined @Bagnon\common\Wildpants\classes\item.lua:

**Comment by Spherikal** [comment]
Not sure why this is closed since it's still a issue in the latest version?

**Comment by raysmith59** [comment]
Confirmed, the startup issue *may* be fixed (I'm getting new errors related to another add-on, Caerdon Wardrobe, that hooks to Bagnon so that fix seems to have broken that add-on - never sure whose ultimate responsibility that is but for now I've reported it to that add-on rather than here) but this one is still happening.
