### ISSUE TITLE
Retail 8.2.21- addon doesnt even load

### ISSUE THREAD

**Issue by Nillx** [tullamods/Bagnon#1060]
Getting this errors

```
2x ...s\Bagnon\common\Wildpants\features\tooltipCounts.lua:179: attempt to index field 'sets' (a nil value)
...s\Bagnon\common\Wildpants\features\tooltipCounts.lua:179: in function `?'
...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0-1.lua:20: in function <...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:18>
...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0-1.lua:56: in function <...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:53>
[C]: ?
...rWeights\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...rWeights\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...rWeights\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:119>
[C]: in function `resume'
WeakAuras\WeakAuras-2.15.5.lua:1580: in function `Login'
WeakAuras\WeakAuras-2.15.5.lua:1661: in function <WeakAuras\WeakAuras.lua:1613>
```

```
2x ...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:70: attempt to index field 'sets' (a nil value)
...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:70: in function `RegisterDisplayEvents'
...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:28: in function `RegisterGameEvents'
...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:13: in function `?'
...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0-1.lua:20: in function <...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:18>
...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0-1.lua:56: in function <...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:53>
[C]: ?
...rWeights\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...rWeights\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...rWeights\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:119>
```

**Comment by Odaxis** [comment]
the addon "Bagnon ItemLevel" made by goldpawthenotsogreat was preventing this addon from loading for me, I'm still getting the same wildpants error though.

**Comment by Morindra** [comment]
Same issue.  mine also has BagBrother issues:
Date: 2019-12-21 14:44:15
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\BagBrother\Startup.lua line 78:
   attempt to call global 'HasKey' (a nil value)
Debug:
   BagBrother\Startup.lua:78: UpdateData()
   BagBrother\Startup.lua:30: ?()
   BagBrother\Startup.lua:20:
      BagBrother\Startup.lua:20
Locals:
self = BagBrother {
 BANKFRAME_OPENED = <function> defined @Interface\AddOns\BagBrother\Events.lua:42
 ParseItem = <function> defined @Interface\AddOns\BagBrother\API.lua:47
 SetupEvents = <function> defined @Interface\AddOns\BagBrother\Startup.lua:49
 VOID_STORAGE_CLOSE = <function> defined @Interface\AddOns\BagBrother\Events.lua:68
 SaveBag = <function> defined @Interface\AddOns\BagBrother\API.lua:19
 PLAYER_EQUIPMENT_CHANGED = <function> defined @Interface\AddOns\BagBrother\Events.lua:31
 SaveEquip = <function> defined @Interface\AddOns\BagBrother\API.lua:40
 GUILDBANKFRAME_OPENED = <function> defined @Interface\AddOns\BagBrother\Events.lua:83
 Realm = <table> {
 }
 StartupCache = <function> defined @Interface\AddOns\BagBrother\Startup.lua:33
 PLAYER_MONEY = <function> defined @Interface\AddOns\BagBrother\Events.lua:35
 BANKFRAME_CLOSED = <function> defined @Interface\AddOns\BagBrother\Events.lua:46
 GUILDBANKFRAME_CLOSED = <function> defined @Interface\AddOns\BagBrother\Events.lua:87
 VOID_STORAGE_OPEN = <function> defined @Interface\AddOns\BagBrother\Events.lua:64
 Player = <table> {
 }
 RemoveEvent = <function> defined @Interface\AddOns\BagBrother\Startup.lua:89
 GUILDBANKBAGSLOTS_CHANGED = <function> defined @Interface\AddOns\BagBrother\Events.lua:95
 0 = <userdata>
 GUILD_ROSTER_UPDATE = <function> defined @Interface\AddOns\BagBrother\Events.lua:91
 UpdateData = <function> defined @Interface\AddOns\BagBrother\Startup.lua:69
 BAG_UPDATE = <function> defined @Interface\AddOns\BagBrother\Events.lua:25
}
(*temporary) = nil
(*temporary) = "attempt to call global 'HasKey' (a nil value)"

AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  ACP, v3.5.6 
  Altoholic, vr191
  AskMrRobot, v80
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.21
  Bartender4, v4.8.9
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  Carbonite, v@project-version@
  CarboniteInfo, vv8.1.5
  CarboniteNotes, vv8.1.5
  CarboniteQuests, vv8.2.0
  CarboniteSocial, vv8.1.5
  CarboniteWarehouse, v@project-version@
  CarboniteWeekly, vv8.1
  DataStore, vr66
  DataStoreAchievements, vr48
  DataStoreAgenda, vr30
  DataStoreAuctions, vr51
  DataStoreCharacters, vr44
  DataStoreContainers, vr60
  DataStoreCrafts, vr83
  DataStoreCurrencies, vr39
  DataStoreGarrisons, vr25
  DataStoreInventory, vr54
  DataStoreMails, vr53
  DataStorePets, vr45
  DataStoreQuests, vr47
  DataStoreReputations, vr44
  DataStoreSpells, vr33
  DataStoreStats, vr32
  DataStoreTalents, vr62
  DBMArchaeology, v
  DBMCore, v8.2.31
  DBMCountPackHotS, v1.7.4
  DBMCountPackOverwatch, v1.4.8
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  Enchantrix, v8.2.6506 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6507 (SwimmingSeadragon)
  GatherMate2, v1.45.5
  GTFO, v4.51
  GuildGreet, v8.2.0-beta1
  HandyNotes, vv1.5.9
  HandyNotesArgus, v0.20.0
  HandyNotesBattleForAzerothTreasures, v1
  HandyNotesBrokenShore, vv1.31
  HandyNotesLegionTreasures, v1
  HealBot, v8.2.5.8
  HealBotData, v8.2.5.0
  HealBoten, v8.2.5.0
  HealBotOptions, v8.2.5.0
  HealBotTips, v8.2.5.8
  Informant, v8.2.6508 (SwimmingSeadragon)
  LibSharedMedia30, v3.0-112
  MageNuggets, v6.1.1
  MageNuggetsCooldownMonitor, v6.0.2
  MageNuggetsStatMonitor, v6.0.2
  MikScrollingBattleText, v5.7.150
  OmniCC, v8.2.5
  oRA3, vv8.2.5
  Pawn, v2.3.12
  Postal, vv3.6.0
  Prat30, v3.7.45
  Prat30Libraries, v
  Quartz, v3.5.2
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  Stubby, v8.2.6510 (SwimmingSeadragon)
  Titan, v5.18.4.80205
  TitanBag, v5.18.4.80205
  TitanClock, v5.18.4.80205
  TitanGold, v5.18.4.80205
  TitanLocation, v5.18.4.80205
  TitanLootType, v5.18.4.80205
  TitanPerformance, v5.18.4.80205
  TitanRepair, v5.18.4.80205
  TitanVolume, v5.18.4.80205
  TitanXP, v5.18.4.80205
  WeakAuras, v2.15.5
  WorldQuestTracker, v
  BlizRuntimeLib_enUS v8.2.5.80205 <none>
  (ck=a78)

**Comment by Spherikal** [comment]
Yep, something broke with the latest update. Getting lots of errors when I log in now 😞

**Comment by GeoffreyEmerson** [comment]
Same. Turned off all other addons (except Swatter) and got this: 

Date: 2019-12-21 14:18:57
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\BagBrother\Startup.lua line 78:
   attempt to call global 'HasKey' (a nil value)
Debug:
   BagBrother\Startup.lua:78: UpdateData()
   BagBrother\Startup.lua:30: ?()
   BagBrother\Startup.lua:20:
      BagBrother\Startup.lua:20
Locals:
self = BagBrother {
 BANKFRAME_OPENED = <function> defined @Interface\AddOns\BagBrother\Events.lua:42
 ParseItem = <function> defined @Interface\AddOns\BagBrother\API.lua:47
 SetupEvents = <function> defined @Interface\AddOns\BagBrother\Startup.lua:49
 VOID_STORAGE_CLOSE = <function> defined @Interface\AddOns\BagBrother\Events.lua:68
 SaveBag = <function> defined @Interface\AddOns\BagBrother\API.lua:19
 PLAYER_EQUIPMENT_CHANGED = <function> defined @Interface\AddOns\BagBrother\Events.lua:31
 SaveEquip = <function> defined @Interface\AddOns\BagBrother\API.lua:40
 GUILDBANKFRAME_OPENED = <function> defined @Interface\AddOns\BagBrother\Events.lua:83
 Realm = <table> {
 }
 StartupCache = <function> defined @Interface\AddOns\BagBrother\Startup.lua:33
 PLAYER_MONEY = <function> defined @Interface\AddOns\BagBrother\Events.lua:35
 BANKFRAME_CLOSED = <function> defined @Interface\AddOns\BagBrother\Events.lua:46
 GUILDBANKFRAME_CLOSED = <function> defined @Interface\AddOns\BagBrother\Events.lua:87
 VOID_STORAGE_OPEN = <function> defined @Interface\AddOns\BagBrother\Events.lua:64
 Player = <table> {
 }
 RemoveEvent = <function> defined @Interface\AddOns\BagBrother\Startup.lua:89
 GUILDBANKBAGSLOTS_CHANGED = <function> defined @Interface\AddOns\BagBrother\Events.lua:95
 0 = <userdata>
 GUILD_ROSTER_UPDATE = <function> defined @Interface\AddOns\BagBrother\Events.lua:91
 UpdateData = <function> defined @Interface\AddOns\BagBrother\Startup.lua:69
 BAG_UPDATE = <function> defined @Interface\AddOns\BagBrother\Events.lua:25
}
(*temporary) = nil
(*temporary) = "attempt to call global 'HasKey' (a nil value)"

AddOns:
  Swatter, v7.3.1 (<%codename%>)
  ACP, v3.5.6 
  BagBrother, v
  BlizRuntimeLib_enUS v8.2.5.80205 <none>
  (ck=6a)
