### ISSUE TITLE
New Update broke Shift to Compare 

### ISSUE THREAD

**Issue by Laxxboy** [tullamods/Bagnon#1061]
As the title states, since the newest update, pressing SHIFT to compare items no longer works. Disabling Bagnon fixes it everytime.

**Comment by r3v0luti0n** [comment]
[bagnon error 2.txt](https://github.com/tullamods/Bagnon/files/3991816/bagnon.error.2.txt)
[bagnon error 1.txt](https://github.com/tullamods/Bagnon/files/3991817/bagnon.error.1.txt)

Here are my error traces with the same problem. I have rolled back to the last stable release of 8.2.16 to temporarily resolve the issue.

**Comment by Laxxboy** [comment]
appreciate the speedy response, good luck diagnosing and fixing o/
