### ISSUE TITLE
Sorting not working

### ISSUE THREAD

**Issue by tangiblethoughts** [tullamods/Bagnon#1062]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.2.21
 - Server patch: [e.g. Build 8.0.1.27178]

 **Have you read the changelog? (please don't waste our time)**
 Mark if read. Y

**Describe the bug**
Sort function is not working properly with new update. After trying to click sort, I receive a message that an item doesnt belong in that container and the mouse cursor continues to blink until a /reload.

**To Reproduce**
Steps to reproduce the behaviour:
Click sort bags.

**Expected behaviour**
Bags should properly sort.

**Screenshots**

**Error Logs**
No errors appeared now but one did pop up previously

**Additional context**

**Comment by Molbork** [comment]
Same issue, looks like it is sorting the keyring in with normal bags. Keys are pulled out to the top row of the normal bag. Then when an item is in the normal bag slot after the key, it tries to swap the item with key in keyring over and over which it can't do. Hence the 'item does not belong in this bag error"
