### ISSUE TITLE
Lua errors as of today

### ISSUE THREAD

**Issue by micahawitt** [tullamods/Bagnon#1064]
Message: ...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:66: attempt to index field 'profile' (a nil value)
Time: Sat Dec 21 18:25:09 2019
Count: 1
Stack: ...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:66: attempt to index field 'profile' (a nil value)
[C]: ?
...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:66: in function `IsEnabled'
...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:41: in function `New'
...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:81: in function `Show'
...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:77: in function `Toggle'
...s\Bagnon\common\Wildpants\features\slashCommands.lua:36: in function `?'
Interface\FrameXML\ChatFrame.lua:4839: in function `ChatEdit_ParseText'
Interface\FrameXML\ChatFrame.lua:4502: in function `ChatEdit_SendText'
Interface\FrameXML\ChatFrame.lua:4538: in function <Interface\FrameXML\ChatFrame.lua:4534>
[C]: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:

this is one of 6 errors, it started with initially throwin error for Azerite tooltip, and boags just show all 4 instead of addon.  Once i disabled ATT, then i get the bagnon error as above

**Comment by a2line** [comment]
```
2x Bagnon_ItemLevel\main.lua:210: Usage: hooksecurefunc([table,] "function", hookfunc)
[C]: in function `hooksecurefunc'
Bagnon_ItemLevel\main.lua:210: in function `?'
...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0-1.lua:20: in function <...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:18>
...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0-1.lua:56: in function **<...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:53>**
[C]: ?
...ker\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...ker\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...ker\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
AutoVendor\libs\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <AutoVendor\libs\AceEvent-3.0\AceEvent-3.0.lua:119>
[C]: ?
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:448: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:491: in function `CombatLog_LoadUI'
FrameXML\UIParent.lua:1242: in function <FrameXML\UIParent.lua:1138>
```

**Comment by a2line** [comment]
```
2x ...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:70: attempt to index field 'sets' (a nil value)
...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:70: in function `RegisterDisplayEvents'
...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:28: in function `RegisterGameEvents'
...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:13: in function `?'
...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0-1.lua:20: in function <...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:18>
...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0-1.lua:56: in function <...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:53>
[C]: ?
...ker\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...ker\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...ker\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
AutoVendor\libs\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <AutoVendor\libs\AceEvent-3.0\AceEvent-3.0.lua:119>
```

**Comment by jimkillian** [comment]
Everything was working fine until I updated to 8.2.22 today. When I pressed [B], I got all the bags separately. I checked the key bindings to be sure they were correct and checked to be sure Bagnon was enabled. Next time I tried, NOTHING. Reloaded the UI, NOTHING. Exited, restarted, NOTHING.

Really hope this gets solved soon, as I'd hate to be stuck playing without it!

Here's what I got in BugSack:

### 

5x Bagnon\common\Wildpants\api\frames.lua:66: attempt to index field 'profile' (a nil value)
Bagnon\common\Wildpants\api\frames.lua:66: in function `IsEnabled'
Bagnon\common\Wildpants\api\frames.lua:41: in function `New'
Bagnon\common\Wildpants\api\frames.lua:81: in function `Show'
Bagnon\common\Wildpants\api\frames.lua:77: in function `Toggle'
[string "BAGNON_TOGGLE"]:1: in function <[string "BAGNON_TOGGLE"]:1>

Locals:
self = <table> {
 SendSignal = <function> defined @Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:82
 RegisterMessage = <function> defined @WorldQuestTracker\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 UnregisterMessage = <function> defined @WorldQuestTracker\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:179
 Update = <function> defined @Bagnon\common\Wildpants\api\frames.lua:72
 NewModule = <function> defined @Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:68
 HasBag = <function> defined @Bagnon\common\Wildpants\api\frames.lua:125
 AreBasicsEnabled = <function> defined @Bagnon\common\Wildpants\api\frames.lua:58
 UnregisterAllEvents = <function> defined @WorldQuestTracker\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:200
 ShowBag = <function> defined @Bagnon\common\Wildpants\api\frames.lua:113
 Toggle = <function> defined @Bagnon\common\Wildpants\api\frames.lua:76
 SendMessage = <function> defined @WorldQuestTracker\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:85
 ToggleBag = <function> defined @Bagnon\common\Wildpants\api\frames.lua:107
 New = <function> defined @Bagnon\common\Wildpants\api\frames.lua:40
 UnregisterSignal = <function> defined @Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:78
 registry = <table> {
 }
 Hide = <function> defined @Bagnon\common\Wildpants\api\frames.lua:90
 Get = <function> defined @Bagnon\common\Wildpants\api\frames.lua:50
 RegisterEvent = <function> defined @WorldQuestTracker\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 UnregisterAllMessages = <function> defined @WorldQuestTracker\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:200
 IsShown = <function> defined @Bagnon\common\Wildpants\api\frames.lua:99
 Iterate = <function> defined @Bagnon\common\Wildpants\api\frames.lua:54
 Show = <function> defined @Bagnon\common\Wildpants\api\frames.lua:80
 OnEnable = <function> defined @Bagnon\common\Wildpants\api\frames.lua:12
 RegisterSignal = <function> defined @Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:74
 NewLoader = <function> defined @Bagnon\common\Wildpants\api\frames.lua:21
 IsEnabled = <function> defined @Bagnon\common\Wildpants\api\frames.lua:62
 HideBag = <function> defined @Bagnon\common\Wildpants\api\frames.lua:119
 UnregisterEvent = <function> defined @WorldQuestTracker\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:179
 Tag = "BAGNON_"
}
id = "inventory"
(*temporary) = nil
(*temporary) = <table> {
 SendSignal = <function> defined @Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:82
 RegisterMessage = <function> defined @WorldQuestTracker\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 UnregisterMessage = <function> defined @WorldQuestTracker\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:179
 Update = <function> defined @Bagnon\common\Wildpants\api\frames.lua:72
 NewModule = <function> defined @Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:68
 HasBag = <function> defined @Bagnon\common\Wildpants\api\frames.lua:125
 AreBasicsEnabled = <function> defined @Bagnon\common\Wildpants\api\frames.lua:58
 UnregisterAllEvents = <function> defined @WorldQuestTracker\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:200
 ShowBag = <function> defined @Bagnon\common\Wildpants\api\frames.lua:113
 Toggle = <function> defined @Bagnon\common\Wildpants\api\frames.lua:76
 SendMessage = <function> defined @WorldQuestTracker\libs\CallbackHandler-1.

**Comment by a2line** [comment]
Only thing I've got working is rolling back to release 8.2.16

**Comment by micahawitt** [comment]
how do you "rollback"?

**Comment by Morindra** [comment]
Posting mine as the line numbers are different than those above.  I opened my bags and moused over an item.  that is when I got the error.

Date: 2019-12-21 19:06:35
ID: 1
Error occured in: Global
Count: 1
Message: ...ce\AddOns\Bagnon\common\Wildpants\classes\tipped.lua line 14:
   attempt to call method 'IsOwned' (a nil value)
Debug:
   ...ce\AddOns\Bagnon\common\Wildpants\classes\tipped.lua:14:
      ...ce\AddOns\Bagnon\common\Wildpants\classes\tipped.lua:9
   (tail call): ?
   ...face\AddOns\Bagnon\common\Wildpants\classes\item.lua:221: OnLeave()
   ...face\AddOns\Bagnon\common\Wildpants\classes\item.lua:216:
      ...face\AddOns\Bagnon\common\Wildpants\classes\item.lua:206
Locals:
self = ContainerFrame1Item26 {
 timeSinceUpgradeCheck = 0
 PostOnLoad = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:169
 __super = <table> {
 }
 UnregisterAll = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\classes\base.lua:27
 IconOverlay = <unnamed> {
 }
 icon = ContainerFrame1Item26IconTexture {
 }
 CreateDummySlot = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\classes\item.lua:450
 SlotTypes = <table> {
 }
 UpdateCooldown = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\classes\item.lua:321
 Bind = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\classes\item.lua:101
 IconBorder = <unnamed> {
 }
 OnDragStart = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\classes\item.lua:142
 OnLeave = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\classes\item.lua:220
 SetLocked = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\classes\item.lua:317
 itemContextMatchResult = 3
 GetSlotType = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\classes\item.lua:432
 count = 0
 GetTemplate = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\Poncho-2.0\Poncho-2.0.lua:89
 IsCached = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\classes\parented.lua:35
 itemContextChangedCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:170
 flashAnim = <unnamed> {
 }
 Super = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\Poncho-2.0\Poncho-2.0.lua:138
 itemContextChangedCallbackIsSet = true
 info = <table> {
 }
 __type = "ItemButton"
 GetFrame = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\classes\parented.lua:39
 GetFrameID = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\classes\parented.lua:19
 NewModule = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:68
 NewItemTexture = <unnamed> {
 }
 Delay = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\MutexDelay-1.0\MutexDelay-1.0.lua:27
 frame = <unnamed> {
 }
 OnShow = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\classes\item.lua:122
 ExtendedOverlay = <unnamed> {
 }
 BagStaticBottom = <unnamed> {
 }
 UpdateSecondary = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\classes\item.lua:245
 RegisterMessage = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 NumInactive = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\Poncho-2.0\Poncho-2.0.lua:105
 Update = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\classes\item.lua:228
 flash = <unnamed> {
 }
 IconGlow = <unnamed> {
 }
 RegisterFrameSignal = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\classes\base.lua:15
 UpdateTooltip = <function> defined @Interface\FrameXML\ContainerFrame.lua:1375
 GetBlizzard = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\classes\item.lua:88
 GetInfo = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\classes\item.lua:420
 NumActive = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\Poncho-2.0\Poncho-2.0.lua:101
 __count = 25
 UpdateItemContextMatching = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:211
 UnregisterSignal = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:78
 GetBaseProfile = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\classes\parented.lua:27
 UpdateItemContextOverlay = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:222
 GetEmptyItemIcon = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\classes\item.lua:437
 RegisterEvent = <function> defined =[C]:-1
 IsQuestItem = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\classes\item.lua:391
 0 = <userdata>
 GetClass = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\Poncho-2.0\Poncho-2.0.lua:116
 IsAbstract = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\Ponc
AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  ACP, v3.5.6 
  Altoholic, vr191
  AskMrRobot, v80
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.22
  Bartender4, v4.8.9
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  Carbonite, v@project-version@
  CarboniteInfo, vv8.1.5
  CarboniteNotes, vv8.1.5
  CarboniteQuests, vv8.2.0
  CarboniteSocial, vv8.1.5
  CarboniteWarehouse, v@project-version@
  CarboniteWeekly, vv8.1
  DataStore, vr66
  DataStoreAchievements, vr48
  DataStoreAgenda, vr30
  DataStoreAuctions, vr51
  DataStoreCharacters, vr44
  DataStoreContainers, vr60
  DataStoreCrafts, vr83
  DataStoreCurrencies, vr39
  DataStoreGarrisons, vr25
  DataStoreInventory, vr54
  DataStoreMails, vr53
  DataStorePets, vr45
  DataStoreQuests, vr47
  DataStoreReputations, vr44
  DataStoreSpells, vr33
  DataStoreStats, vr32
  DataStoreTalents, vr62
  DBMArchaeology, v
  DBMCore, v8.2.31
  DBMCountPackHotS, v1.7.4
  DBMCountPackOverwatch, v1.4.8
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  Enchantrix, v8.2.6506 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6507 (SwimmingSeadragon)
  GatherMate2, v1.45.5
  GTFO, v4.51
  GuildGreet, v8.2.0-beta1
  HandyNotes, vv1.5.9
  HandyNotesArgus, v0.20.0
  HandyNotesBattleForAzerothTreasures, v1
  HandyNotesBrokenShore, vv1.31
  HandyNotesLegionTreasures, v1
  HealBot, v8.2.5.8
  HealBotData, v8.2.5.0
  HealBoten, v8.2.5.0
  HealBotOptions, v8.2.5.0
  HealBotTips, v8.2.5.8
  Informant, v8.2.6508 (SwimmingSeadragon)
  LibSharedMedia30, v3.0-112
  MageNuggets, v6.1.1
  MageNuggetsCooldownMonitor, v6.0.2
  MageNuggetsStatMonitor, v6.0.2
  MikScrollingBattleText, v5.7.150
  OmniCC, v8.2.5
  oRA3, vv8.2.5
  Pawn, v2.3.12
  Postal, vv3.6.0
  Prat30, v3.7.45
  Prat30Libraries, v
  Quartz, v3.5.2
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  Stubby, v8.2.6510 (SwimmingSeadragon)
  Titan, v5.18.4.80205
  TitanBag, v5.18.4.80205
  TitanClock, v5.18.4.80205
  TitanGold, v5.18.4.80205
  TitanLocation, v5.18.4.80205
  TitanLootType, v5.18.4.80205
  TitanPerformance, v5.18.4.80205
  TitanRepair, v5.18.4.80205
  TitanVolume, v5.18.4.80205
  TitanXP, v5.18.4.80205
  WeakAuras, v2.15.5
  WorldQuestTracker, v
  BlizRuntimeLib_enUS v8.2.5.80205 <none>
  (ck=a78)

**Comment by leonardopsantos** [comment]
Date: 2019-12-21 17:20:51
ID: 1
Error occured in: Global
Count: 1
Message: ...face\AddOns\Bagnon\common\Wildpants\classes\item.lua line 254:
   attempt to call method 'UpdateTooltip' (a nil value)
Debug:
   [C]: UpdateTooltip()
   ...face\AddOns\Bagnon\common\Wildpants\classes\item.lua:254: func()
   ...mon\Wildpants\libs\MutexDelay-1.0\MutexDelay-1.0.lua:36:
      ...mon\Wildpants\libs\MutexDelay-1.0\MutexDelay-1.0.lua:30
Locals:

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AtlasLootClassic, vv1.4.3
  AtlasLootClassicData, vv1.4.3
  AtlasLootClassicDungeonsAndRaids, vv1.4.3
  BagBrother, v
  Bagnon, v8.2.21
  Bartender4, v4.8.9
  ChatBarClassic, v3.16.1b
  ClassicCastbars, vv1.2.0-hotfix
  ClassicCastbarsOptions, v
  ClassicThreatMeter, v1.10
  DBMCore, v1.13.25
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  GatherMate2, v1.45.5
  Informant, v8.2.6374 (SwimmingSeadragon)
  Questie, v5.4.0
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TitanClassic, v1.1.5.11303
  TitanClassicAmmo, v1.1.5.11303
  TitanClassicBag, v1.1.5.11303
  TitanClassicClock, v1.1.5.11303
  TitanClassicGold, v1.1.5.11303
  TitanClassicLocation, v1.1.5.11303
  TitanClassicLootType, v1.1.5.11303
  TitanClassicPerformance, v1.1.5.11303
  TitanClassicRegen, v1.1.5.11303
  TitanClassicRepair, v1.1.5.11303
  TitanClassicVolume, v1.1.5.11303
  TitanClassicXP, v1.1.5.11303
  TradeSkillMaster, vv4.8.24
  TradeSkillMasterAppHelper, vv4.0.6
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=42a)

**Comment by a2line** [comment]
> how do you "rollback"?

using Twitch on Bagnon in “Versions” tab you can rollback to all previous versions, same for all addons
