### ISSUE TITLE
Up until today's update Bagon worked great, now it's only opening just one bag not all of them.

### ISSUE THREAD

**Issue by XM137** [tullamods/Bagnon#1067]

**Comment by zamis21** [comment]
I have the same problem after updating Bagon a few mins ago.: 
Date: 2019-12-21 18:19:44
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Bagnon_ItemInfo\main.lua line 511:
   Usage: hooksecurefunc([table,] "function", hookfunc)
Debug:
   (tail call): ?
   [C]: hooksecurefunc()
   Bagnon_ItemInfo\main.lua:511: ?()
   ...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:20:
      ...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:18
   ...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:56:
      ...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:53
   [C]: ?
   ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
   ...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:120:
      ...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119
   [C]: ?
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:448: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:567: TimeManager_LoadUI()
   ..\FrameXML\UIParent.lua:1240:
      ..\FrameXML\UIParent.lua:1138
Locals:
None
AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AlreadyKnown, v1.22
  Altoholic, vr191
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  AzeritePowerWeights, v8.2.16
  Bagnon, v8.2.20
  BagnonBoE, v1.0
  BagnonItemInfo, v1.0
  BattlePetBreedID, vr203
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  CrematoriusChatSounds, v7.xx
  DataStore, vr66
  DataStoreAchievements, vr48
  DataStoreAgenda, vr30
  DataStoreAuctions, vr51
  DataStoreCharacters, vr44
  DataStoreContainers, vr60
  DataStoreCrafts, vr83
  DataStoreCurrencies, vr39
  DataStoreGarrisons, vr25
  DataStoreInventory, vr54
  DataStoreMails, vr53
  DataStorePets, vr45
  DataStoreQuests, vr47
  DataStoreReputations, vr44
  DataStoreSpells, vr33
  DataStoreStats, vr32
  DataStoreTalents, vr62
  DBMCore, v8.2.31
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Enchantrix, v8.2.6506 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6507 (SwimmingSeadragon)
  GatherMate2, v1.45.5

**Comment by zamis21** [comment]
Thank you

**Comment by XM137** [comment]
Working again since updating again :)
