### ISSUE TITLE
Issue with auto sort

### ISSUE THREAD

**Issue by simonrcodrington** [tullamods/Bagnon#1068]
Hey guys

When using the 'sort' button on the UI, it sorted all of the bags just fine, but if you have a swiftness potion it gets stuck in a loop where it says 'that item doesn't go in that container'

**Comment by simonrcodrington** [comment]
I've looked again at this and I think it's not the potion but whatever item is in this slot (as seen in the image)

https://ibb.co/QK53bcx

Anything in the 5th slot seems to constantly be moved. The only way I've found to make it go back to normal after sorting is to enter combat and then leave combat

**Comment by turetafr** [comment]
"Clean items" button does not work for me either but I am not sure it's related to swiftness potion. For me, it seems to get stuck on a large venom sac. IDK
