### ISSUE TITLE
Not opening on one toon: error message

### ISSUE THREAD

**Issue by DDnutz** [tullamods/Bagnon#1071]
Click on bags in inventory, and error pops up: 

Date: 2019-12-21 23:47:49
ID: 1
Error occured in: Global
Count: 1
Message: ...Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua line 170:
   attempt to perform arithmetic on field 'count' (a nil value)
Debug:
   [C]: ?
   ...Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:170:
      ...Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:145
   (tail call): ?
   (tail call): ?
   ...rface\AddOns\Bagnon\common\Wildpants\classes\bag.lua:158: Update()
   ...rface\AddOns\Bagnon\common\Wildpants\classes\bag.lua:123: RegisterEvents()
   ...rface\AddOns\Bagnon\common\Wildpants\classes\bag.lua:72:
      ...rface\AddOns\Bagnon\common\Wildpants\classes\bag.lua:17
   (tail call): ?
   ...\AddOns\Bagnon\common\Wildpants\classes\bagGroup.lua:17:
      ...\AddOns\Bagnon\common\Wildpants\classes\bagGroup.lua:11
   (tail call): ?
   Bagnon\addons\main\frame.lua:238: CreateBagGroup()
   Bagnon\addons\main\frame.lua:218: PlaceBagGroup()
   Bagnon\addons\main\frame.lua:86: Layout()
   Bagnon\addons\main\frame.lua:65: Update()
   Bagnon\addons\main\frame.lua:55: RegisterSignals()
   ...ace\AddOns\Bagnon\common\Wildpants\classes\frame.lua:20:
      ...ace\AddOns\Bagnon\common\Wildpants\classes\frame.lua:18
   (tail call): ?
   ...AddOns\Bagnon\common\Wildpants\classes\inventory.lua:21:
      ...AddOns\Bagnon\common\Wildpants\classes\inventory.lua:20
   [C]: Show()
   ...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:85: Show()
   ...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:77:
      ...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:76
   (tail call): ?
   ...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:146: ToggleBackpack()
   [string "TOGGLEBACKPACK"]:1:
      [string "TOGGLEBACKPACK"]:1
Locals:

AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AtlasLootClassic, vv1.4.3
  AtlasLootClassicData, vv1.4.3
  AtlasLootClassicDungeonsAndRaids, vv1.4.3
  BagBrother, v
  Bagnon, v8.2.23
  CharacterStatsClassic, v2.8.1
  CoordsTracking, vv2.12.11302
  DBMCore, v1.13.25
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.6.6
  Details, v
  DetailsTinyThreat, v
  Disenchantor, v1.13.2
  Dismounter, v1.2.1
  GatherMate2, v1.45.5
  GuildBankClassic, v1.0.1
  HonorAssist, v0.9.2
  KHunterTimers, v1.1-classic
  KKonferSK, v7
  Questie, v5.4.0
  RealMobHealth, v2.17
  Stubby, v8.2.6510 (SwimmingSeadragon)
  VendorPrice, v1.3.0
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=2a1)

Unable to open bags in inventory, Bank is no problem.  this is only happening on a lvl 1 that has been created and around for a while.  GuildBank alt.  

I did update through TWITCH - 
Not happening to any other character.

**Comment by d3spwn** [comment]
Same problem. Also on just one character (bank alt)

Date: 2019-12-22 08:29:26
ID: 1
Error occured in: Global
Count: 1
Message: ...Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua line 170:
   attempt to perform arithmetic on field 'count' (a nil value)
Debug:
   ...Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:170:
      ...Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:145
   (tail call): ?
   (tail call): ?
   ...rface\AddOns\Bagnon\common\Wildpants\classes\bag.lua:158: Update()
   ...rface\AddOns\Bagnon\common\Wildpants\classes\bag.lua:123: RegisterEvents()
   ...rface\AddOns\Bagnon\common\Wildpants\classes\bag.lua:72:
      ...rface\AddOns\Bagnon\common\Wildpants\classes\bag.lua:17
   (tail call): ?
   ...\AddOns\Bagnon\common\Wildpants\classes\bagGroup.lua:17:
      ...\AddOns\Bagnon\common\Wildpants\classes\bagGroup.lua:11
   (tail call): ?
   Bagnon\addons\main\frame.lua:238: CreateBagGroup()
   Bagnon\addons\main\frame.lua:218: PlaceBagGroup()
   Bagnon\addons\main\frame.lua:86: Layout()
   Bagnon\addons\main\frame.lua:65: Update()
   Bagnon\addons\main\frame.lua:55: RegisterSignals()
   ...ace\AddOns\Bagnon\common\Wildpants\classes\frame.lua:20:
      ...ace\AddOns\Bagnon\common\Wildpants\classes\frame.lua:18
   (tail call): ?
   ...AddOns\Bagnon\common\Wildpants\classes\inventory.lua:21:
      ...AddOns\Bagnon\common\Wildpants\classes\inventory.lua:20
   [C]: Show()
   ...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:85: Show()
   ...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:77:
      ...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:76
   (tail call): ?
   ...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:161: ToggleBag()
   ..\FrameXML\MainMenuBarBagButtons.lua:21: BagSlotButton_OnClick()
   [string "*:OnClick"]:4:
      [string "*:OnClick"]:1
Locals:
self = <table> {
 IsKeyring = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:375
 IsRetail = false
 GetOwnerID = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:270
 Frames = <table> {
 }
 InBank = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:352
 ItemGroup = <table> {
 }
 RestoreItemData = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:304
 Frame = <table> {
 }
 OptionsToggle = <table> {
 }
 Bag = <table> {
 }
 IsBank = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:379
 RegisterMessage = <function> defined @Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 IsBagCached = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:291
 Base = <table> {
 }
 UnregisterSignal = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:78
 GetOwnerAddress = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:275
 Slash = "bgn"
 sets = <table> {
 }
 OnEnable = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\Wildpants.lua:98
 Name = "Bagnon"
 IterateOwners = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:114
 InGuild = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:360
 SendSignal = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:82
 NewModule = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:68
 RestoreLinkData = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:328
 Item = <table> {
 }
 OwnerSelector = <table> {
 }
 Commands = <table> {
 }
 SortButton = <table> {
 }
 InventoryFrame = <table> {
 }
 profile = <table> {
 }
 Title = <table> {
 }
 BagGroup = <table> {
 }
 SearchToggle = <table> {
 }
 Events = <table> {
 }
 SearchFrame = <table> {
 }
 TooltipCounts = <table> {
 }
 BrokerDisplay = <table> {
 }
 LDB = <table> {
 }
 Tag = "BAGNON_"
 PickupItem = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:250
 IsBackpackBag = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:371
 IsOwnerCached = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:287
 AutoDisplay = <table> {
 }
 UnregisterAllEvents = <function> defined @Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 Sorting = <table> {
 }
 BankFrame = <table> {
 }
 Parented = <table> {
 }
 GetItemID = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:229
 IsReagents = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:387
 IsBankBag = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:383
 Owners = <table> {
 }
 ShowOptions = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\Wildpants.lua:157
 GetBagInfo = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:145
 DropButton = <table> {
 }
 BagToggle = <table> {
 }
 Rules = <table> {
 }
 GetOwnerInfo = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:74
 MoneyFrame = <table> {
 }
 Tipped = <table> {
 }
 RegisterSignal = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:74
 UnregisterAllMessage
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AdvancedInterfaceOptions, v1.3.3
  Atlas, vv1.45.01.11302
  AtlasClassicWoW, vv1.45.00.11302.05
  AtlasLootClassic, vv1.4.3
  AtlasLootClassicData, vv1.4.3
  AtlasLootClassicDungeonsAndRaids, vv1.4.3
  AtlasLootClassicMaps, vv1.0.0
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.23
  Bartender4, v4.8.9
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  ClassicAuraDurations, v
  ClassicCastbars, vv1.2.0-hotfix
  ClassicCastbarsOptions, v
  ClassicSpellActivations, v
  DBMCore, v1.13.25
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DejaClassicStats, v1302r039
  DejaMark, v820r202
  Details, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  Dismounter, v1.2.1
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  FasterLooting, v1.1.2
  GatherMate2, v1.45.5
  GuildTooltip, v2.7.7
  honorspy, v1.6.7
  Immersion, v1.2.2
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  LeatrixMaps, v1.13.40
  MapCoords, v0.32c
  MonkeyBuddy, v
  MonkeyLibrary, v
  MonkeyQuest, v
  MonkeyQuestLog, v
  MonolithDKP, v1.6.2
  OmniCC, v8.3.1
  Prat30, v3.7.45
  Prat30Libraries, v
  Questie, v5.4.0
  RealMobHealth, v2.17
  Scrap, v13.19
  ScrapSpotlight, v13.19
  SkilletClassic, v1.07
  Spy, v1.0.19
  Stubby, v8.2.6376 (SwimmingSeadragon)
  WeakAuras, v2.15.5
  WeaponSwingTimer, v4.1.0
  whoaThickFramesClassic, v1.3.3
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=76d)

**Comment by Keger1804** [comment]
Same here. Did the Twitch update also, getting same error as above. but mine is on a lvl 47 alt.
