### ISSUE TITLE
bags wont load, errormessage

### ISSUE THREAD

**Issue by hwkzor** [tullamods/Bagnon#1073]
Date: 2019-12-22 08:24:32
ID: 1
Error occured in: Global
Count: 1
Message: ...Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua line 170:
   attempt to perform arithmetic on field 'count' (a nil value)
Debug:
   [C]: ?
   ...Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:170:
      ...Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:145
   (tail call): ?
   (tail call): ?
   ...rface\AddOns\Bagnon\common\Wildpants\classes\bag.lua:158: Update()
   ...rface\AddOns\Bagnon\common\Wildpants\classes\bag.lua:123: RegisterEvents()
   ...rface\AddOns\Bagnon\common\Wildpants\classes\bag.lua:72:
      ...rface\AddOns\Bagnon\common\Wildpants\classes\bag.lua:17
   (tail call): ?
   ...\AddOns\Bagnon\common\Wildpants\classes\bagGroup.lua:17:
      ...\AddOns\Bagnon\common\Wildpants\classes\bagGroup.lua:11
   (tail call): ?
   Bagnon\addons\main\frame.lua:238: CreateBagGroup()
   Bagnon\addons\main\frame.lua:218: PlaceBagGroup()
   Bagnon\addons\main\frame.lua:86: Layout()
   Bagnon\addons\main\frame.lua:65: Update()
   Bagnon\addons\main\frame.lua:55: RegisterSignals()
   ...ace\AddOns\Bagnon\common\Wildpants\classes\frame.lua:20:
      ...ace\AddOns\Bagnon\common\Wildpants\classes\frame.lua:18
   (tail call): ?
   ...AddOns\Bagnon\common\Wildpants\classes\inventory.lua:21:
      ...AddOns\Bagnon\common\Wildpants\classes\inventory.lua:20
   [C]: Show()
   ...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:85: Show()
   ...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:77:
      ...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:76
   (tail call): ?
   ...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:146: ToggleBackpack()
   [string "TOGGLEBACKPACK"]:1:
      [string "TOGGLEBACKPACK"]:1
Locals:

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  Atlas, vv1.45.01.11302
  AtlasBattlegrounds, vv1.45.00.11302.00
  AtlasClassicWoW, vv1.45.00.11302.05
  AtlasLootClassic, vv1.4.3
  AtlasLootClassicData, vv1.4.3
  AtlasLootClassicDungeonsAndRaids, vv1.4.3
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  AutoDismount, v1.0.3
  BagBrother, v
  Baggins, vv3.1.9
  Bagnon, v8.2.23
  Bartender4, v4.8.9
  BasicMinimap, vv1-classic
  BiSTracker, v1.4 
  CharacterStatsClassic, v2.8.1
  ClassicAuraDurations, v
  ClassicThreatMeter, v1.10
  DBMCore, v1.13.25
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.6.6
  Details, v
  Dismounter, v1.2.1
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  GatherMate2, v1.45.5
  HealBot, v1.13.3.1
  HealBotData, v1.13.3.0
  HealBoten, v1.13.3.0
  HealBotOptions, v1.13.3.0
  HealBotTips, v1.13.3.1
  HHTD, v2.4.9.4
  HonorAssist, v0.9.2
  honorspy, v1.6.7
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  KHunterTimers, v1.1-classic
  LeatrixMaps, v1.13.40
  LeatrixPlus, v1.13.41
  LortiUIClassic, v1.1.0
  Mapster, v1.8.5
  MoveToolTip, v1.0.6
  NeatPlates, v1.13.3.2
  NeatPlatesAlvara, v5a
  NeatPlatesBlizzardPlates, v1.5
  NeatPlatesClassicPlates, v
  NeatPlatesGraphite, v
  NeatPlatesGrey, v
  NeatPlatesNeon, v
  NeatPlatesQuatre, v
  NeatPlatesRenaitre, vv7.0.3
  NeatPlatesRoth, v
  NeatPlatesSimple, v7.3.0
  NeatPlatesSlimHorizontal, v2.2
  NeatPlatesSlimVertical, v2.2
  NeatPlatesHub, v
  NeatPlatesWidgets, v
  OmniCC, v8.3.1
  Prat30, v3.7.45
  Prat30Libraries, v
  Quartz, v3.5-classic-5
  Questie, v5.4.0
  RCLootCouncilClassic, v0.5.0
  RealMobHealth, v2.17
  ShadowedUnitFrames, vv4.2.1-Classic
  ShowMeMyHeal, v0.6.1
  Spy, v1.0.19
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TargetHealthPercent, v5.0
  TitanClassic, v1.1.5.11303
  TitanClassicAmmo, v1.1.5.11303
  TitanClassicBag, v1.1.5.11303
  TitanClassicClock, v1.1.5.11303
  TitanClassicGold, v1.1.5.11303
  TitanClassicLocation, v1.1.5.11303
  TitanClassicLootType, v1.1.5.11303
  TitanClassicPerformance, v1.1.5.11303
  TitanClassicRegen, v1.1.5.11303
  TitanClassicRepair, v1.1.5.11303
  TitanClassicVolume, v1.1.5.11303
  TitanClassicXP, v1.1.5.11303
  unitscan, v1.0.0
  VendorPrice, v1.3.0
  WeakAuras, v2.15.5
  WeaponSwingTimer, v4.1.0
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=a87)

**Comment by Rasmus321** [comment]
I found a fix. download and install the version 8.2.21 it works for now :) and hopefully the new version will be fixed soon :)
