### ISSUE TITLE
Classic - Missing tooltip info in main bank

### ISSUE THREAD

**Issue by Erzy-sv** [tullamods/Bagnon#1074]
I don't get any tooltips info when hovering over items in the main bank. Items in the additional bag slots in the bank works fine.

Release 8.2.24 on classic client. No error msgs printed in chat.

![Skärmavbild 2019-12-22 kl  11 44 07](https://user-images.githubusercontent.com/59137039/71320785-ad62d180-24b0-11ea-87e8-8322c052ab65.png)

**Comment by okaredotf** [comment]
Exact same issue.  i'm using the latest version bagnon-8.2.24-1.13.3 (classic wow)

**Comment by Rossax** [comment]
Same issue with the latest version it seems that bagnon atm conflics with ElvUi addon many errors pop up when i enable the two together.and disappear when disabling bagnon

**Comment by okaredotf** [comment]
> 
> 
> Same issue with the latest version it seems that bagnon atm conflics with ElvUi addon many errors pop up when i enable the two together.and disappear when disabling bagnon

that might be another issue. because i dont use the ElvUi, and im not getting any error..only this minor issue with the bank tooltip for the main bank bag. the rest works fine

**Comment by darwin604** [comment]
Experiencing the same issue. I run very few other mods and this is not throwing any errors. It appears to be an issue with the tooltip redrawing a blank area over itself. The proper populated tooltip flashes momentarily and the gets redrawn as a blank.

**Comment by Adonhit** [comment]
Exact same issue for me, no errors. I'm on the latest version bagnon-8.2.24-1.13.3 (classic wow).

**Comment by RustyDalek** [comment]
I'm having a similar issue with 8.2.25 classic. it's only affecting the first 24slot bag in my bank. mousing over an item gives me an item count but not a description. All other bags are working as intended. I tried rolling back to 8.2.24 but nothing changes. It's the only addon i updated this morning. all working fine before updating to 8.2.25.
![image](https://user-images.githubusercontent.com/59142110/71323476-882f8c80-24cb-11ea-9fae-020af3147ad6.png)

**Comment by Jaliborc** [comment]
Pretty confident I fixed this internally
