### ISSUE TITLE
22 Dec 19 WoW retail

### ISSUE THREAD

**Issue by nerdyvalkyrie** [tullamods/Bagnon#1075]
Inventory isn't showing in one bagnon window; back to default WoW single bag windows.  Bagnon is loaded on character within interface. Latest 8.2.24-8.2.5 updated this morning before logging into WoW.

![WoWScrnShot_122219_055327](https://user-images.githubusercontent.com/59137202/71320863-84761880-247f-11ea-8c5b-9adb6f13de5e.jpg)

**Comment by ultima98** [comment]
Same issue here.

**Comment by Jaliborc** [comment]
Sorry, not enough information to do anything. Try disabling the out of date plugins
