### ISSUE TITLE
Classic: Keys put back in regular bags after autosort

### ISSUE THREAD

**Issue by Vortigengamer** [tullamods/Bagnon#1076]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.2.24-1.13.3

 **Have you read the changelog? (please don't waste our time)**
 Read

**Describe the bug**
I put my keys manually in the keyring but when I do autosort it puts them back into my regular bags.

**Comment by eaigner** [comment]
Can't sort bags at all with latest updated. It gets in an infinite loop.

Please just exclude every non-regular bag from sort. This already caused so many issues.

**Comment by VulpesHD** [comment]
For me it takes out the keys from the keyring, then It tries to put non key items into the keyring, what it cant do, therefore the sorting function gets into an infinite loop.
