### ISSUE TITLE
8.2.24 Retail - Multiple errors again

### ISSUE THREAD

**Issue by Nillx** [tullamods/Bagnon#1077]
```
1x ...s\Bagnon\common\Wildpants\features\tooltipCounts.lua:179: attempt to index field 'sets' (a nil value)
...s\Bagnon\common\Wildpants\features\tooltipCounts.lua:179: in function `?'
...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0-1.lua:20: in function <...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:18>
...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0-1.lua:56: in function <...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:53>
[C]: ?
...rWeights\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...rWeights\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...rWeights\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:119>
[C]: in function `resume'
WeakAuras\WeakAuras-2.15.5.lua:1580: in function `Login'
WeakAuras\WeakAuras-2.15.5.lua:1661: in function <WeakAuras\WeakAuras.lua:1613>
```

```
1x ...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:70: attempt to index field 'sets' (a nil value)
...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:70: in function `RegisterDisplayEvents'
...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:28: in function `RegisterGameEvents'
...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:13: in function `?'
...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0-1.lua:20: in function <...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:18>
...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0-1.lua:56: in function <...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:53>
[C]: ?
...rWeights\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...rWeights\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...rWeights\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:119>
```

```
1x Bagnon_ItemLevel\main.lua:210: Usage: hooksecurefunc([table,] "function", hookfunc)
[C]: in function `hooksecurefunc'
Bagnon_ItemLevel\main.lua:210: in function `?'
...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0-1.lua:20: in function <...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:18>
...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0-1.lua:56: in function <...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:53>
[C]: ?
...rWeights\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...rWeights\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...rWeights\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:119>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:448: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:491: in function `CombatLog_LoadUI'
FrameXML\UIParent.lua:1242: in function <FrameXML\UIParent.lua:1138>
```

**Comment by micahawitt** [comment]
Same - 

Message: ...terface\AddOns\Bagnon\common\Wildpants\Wildpants.lua:159: attempt to index field 'Options' (a nil value)
Time: Sun Dec 22 06:32:22 2019
Count: 1
Stack: ...terface\AddOns\Bagnon\common\Wildpants\Wildpants.lua:159: attempt to index field 'Options' (a nil value)
[C]: ?
...terface\AddOns\Bagnon\common\Wildpants\Wildpants.lua:159: in function `ShowOptions'
...s\Bagnon\common\Wildpants\features\slashCommands.lua:46: in function `?'
Interface\FrameXML\ChatFrame.lua:4839: in function `ChatEdit_ParseText'
Interface\FrameXML\ChatFrame.lua:4502: in function `ChatEdit_SendText'
Interface\FrameXML\ChatFrame.lua:4538: in function <Interface\FrameXML\ChatFrame.lua:4534>
[C]: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:

**Comment by zamis21** [comment]
Thank you 
: 2019-12-22 06:53:11
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Bagnon_ItemInfo\main.lua line 511:
   Usage: hooksecurefunc([table,] "function", hookfunc)
Debug:
   (tail call): ?
   [C]: hooksecurefunc()
   Bagnon_ItemInfo\main.lua:511: ?()
   ...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:20:
      ...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:18
   ...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:56:
      ...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:53
   [C]: ?
   ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
   ...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:120:
      ...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119
   [C]: ?
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:448: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:567: TimeManager_LoadUI()
   ..\FrameXML\UIParent.lua:1240:
      ..\FrameXML\UIParent.lua:1138
Locals:
None
AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AlreadyKnown, v1.22
  Altoholic, vr191
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  AzeritePowerWeights, v8.2.16
  Bagnon, v8.2.24
  BagnonBoE, v1.0
  BagnonItemInfo, v1.0
  BattlePetBreedID, vr203
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  CrematoriusChatSounds, v7.xx
  DataStore, vr66
  DataStoreAchievements, vr48
  DataStoreAgenda, vr30
  DataStoreAuctions, vr51
  DataStoreCharacters, vr44
  DataStoreContainers, vr60
  DataStoreCrafts, vr83
  DataStoreCurrencies, vr39
  DataStoreGarrisons, vr25
  DataStoreInventory, vr54
  DataStoreMails, vr53
  DataStorePets, vr45
  DataStoreQuests, vr47
  DataStoreReputations, vr44
  DataStoreSpells, vr33
  DataStoreStats, vr32
  DataStoreTalents, vr62
  DBMCore, v8.2.31
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  EnchantrixBarker, v8.2.6507 (SwimmingSeadragon)
  GatherMate2, v1.45.5
  HandyNotes, vv1.5.9
  HandyNotesBattleForAzerothTreasures, v1
  HandyNotesWarfrontRares, v0.5.0
  HealBotData, v8.2.5.0
  HealBoten, v8.2.5.0
  HealBotOptions, v8.2.5.0
  MaxDps, v8.2.8
  PetTracker, v8.2.2
  PetTrackerBreeds, v8.2.2
  PetTrackerSwitcher, v8.2.2
  PetTrackerUpgrades, v8.2.2
  Postal, vv3.6.0
  Recount, vv8.2.5d
  Rematch, v4.9.13
  sellgrey, v8.2.5
  Stubby, v8.2.6510 (SwimmingSeadragon)
  Titan, v5.18.4.80205
  TitanBag, v5.18.4.80205
  TitanClock, v5.18.4.80205
  TitanGold, v5.18.4.80205
  TitanLocation, v5.18.4.80205
  TitanLootType, v5.18.4.80205
  TitanPerformance, v5.18.4.80205
  TitanRepair, v5.18.4.80205
  TitanVolume, v5.18.4.80205
  TitanXP, v5.18.4.80205
  TradeSkillMaster, vv4.8.24
  TradeSkillMasterAppHelper, vv4.0.6
  WeakAuras, v2.15.5
  WorldQuestTracker, v
  BlizRuntimeLib_enUS v8.2.5.80205 <none>
  (ck=811)
