### ISSUE TITLE
Esc key closes bags and opens game menu

### ISSUE THREAD

**Issue by sirzooro** [tullamods/Bagnon#1078]
After last update Esc key closes bags and opens game menu. Before update Esc was closing bags only, and I had to press it one more time to open game menu.

Edit: this is on Retail

**Comment by Vortigengamer** [comment]
Having the same issue after the last update.

**Comment by turetafr** [comment]
Just updated to 8.2.24 and having this same problem. I like to use Esc to close my bags, but its also opening the game menu, so I have to press Esc twice to close my bags.

**Comment by Masumia** [comment]
Same issue here, playing retail.

**Comment by semecan** [comment]
To add to that, ESC is no longer closing the Bank

**Comment by Jaliborc** [comment]
Yeah, can't for the life of me understand how that even used to work...

**Comment by Jaliborc** [comment]
Fixed internally
