### ISSUE TITLE
Key filter in the keychain

### ISSUE THREAD

**Issue by Venturic** [tullamods/Bagnon#1079]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.2.24
 - Server patch: [e.g. Build 8.0.1.27178] Actual wow Classic version

 **Have you read the changelog? (please don't waste our time)**
 I read. 

**Describe the bug**
Key filter in the keychain

Two bizarre behaviors:
1st: the "clean item" puts the key back in the bags, after having moved the key in the keychain.
2nd: I put the key back in the keychain, and in I click on "filter item" = message: "you cannot move this object" and it continues in a loop.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to addon
2. Click on your key put it in keychain. 
3. After click on Iten clean.
4. Key come back in standard bag.
5 Replace de key in kaychain.
6 Reclick on Item clean
7 Error message on loop. (Not always)

(Sorry for my english)

**Expected behaviour**

**Screenshots**
Not screen help

**Error Logs**
/console scriptErrors 1 D'ont show anythongs
**Additional context**
No.

**Comment by turetafr** [comment]
I just updated to 8.2.24 and still have the same problem.
