### ISSUE TITLE
Bagnon errors 12-22-19

### ISSUE THREAD

**Issue by wasaiii** [tullamods/Bagnon#1081]
26x Bagnon\common\Wildpants\Wildpants.lua:159: attempt to index field 'Options' (a nil value)
Bagnon\common\Wildpants\Wildpants.lua:159: in function `ShowOptions'
...s\Bagnon\common\Wildpants\features\slashCommands.lua:46: in function `?'
FrameXML\ChatFrame.lua:4839: in function <FrameXML\ChatFrame.lua:4785>
[C]: in function `ChatEdit_ParseText'
FrameXML\ChatFrame.lua:4502: in function <FrameXML\ChatFrame.lua:4501>
[C]: in function `ChatEdit_SendText'
FrameXML\ChatFrame.lua:4538: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:
self = <table> {
 IsKeyring = <function> defined @Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:374
 IsRetail = true
 GetOwnerID = <function> defined @Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:269
 Frames = <table> {
 }
 BindOnEquip = <table> {
 }
 InBank = <function> defined @Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:351
 ItemGroup = <table> {
 }
 GeneralOptions = <unnamed> {
 }
 RestoreItemData = <function> defined @Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:303
 Frame = <table> {
 }
 OptionsToggle = <table> {
 }
 Bag = <table> {
 }
 IsBank = <function> defined @Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:378
 RegisterMessage = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 IsBagCached = <function> defined @Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:290
 Base = <table> {
 }
 UnregisterSignal = <function> defined @Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:78
 GetOwnerAddress = <function> defined @Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:274
 Slash = "bgn"
 OnEnable = <function> defined @Bagnon_ItemLevel\main.lua:209
 Name = "Bagnon"
 IterateOwners = <function> defined @Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:114
 InGuild = <function> defined @Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:359
 SendSignal = <function> defined @Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:82
 NewModule = <function> defined @Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:68
 RestoreLinkData = <function> defined @Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:327
 GarbageColoring = <table> {
 }
 Item = <table> {
 }
 ColorOptions = <unnamed> {
 }
 OwnerSelector = <table> {
 }
 SendMessage = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 Commands = <table> {
 }
 DisplayOptions = <unnamed> {
 }
 SortButton = <table> {
 }
 OptionsGroup = <table> {
 }
 InventoryFrame = <table> {
 }
 ItemLevel = <table> {
 }
 Title = <table> {
 }
 BagGroup = <table> {
 }
 SearchToggle = <table> {
 }
 Events = <table> {
 }
 SearchFrame = <table> {
 }
 TooltipCounts = <table> {
 }
 BrokerDisplay = <table> {
 }
 LDB = <table> {
 }
 Tag = "BAGNON_"
 PickupItem = <function> defined @Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:249
 IsBackpackBag = <function> defined @Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:370
 IsOwnerCached = <function> defined @Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:286
 AutoDisplay = <table> {
 }
 UnregisterAllEvents = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 Sorting = <table> {
 }
 BankFrame = <table> {
 }
 Parented = <table> {
 }
 GetItemID = <function> defined @Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:228
 IsReagents = <function> defined @Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:386
 IsBankBag = <function> defined @Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:382
 Owners = <table> {
 }
 ShowOptions = <function> defined @Bagnon\common\Wildpants\Wildpants.lua:157
 GetBagInfo = <function> defined @Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:145
 DropButton = <table> {
 }
 BagToggle = <table> {
 }
 Rules = <table> {
 }
 GetOwnerInfo = <function> defin

**Comment by wasaiii** [comment]
It worked as of last night, but didn't work this morning.  I updated it after I saw it wasn't working, but it still doesn't work as intended.

**Comment by Jaliborc** [comment]
Fixed internally
