### ISSUE TITLE
Bagnon 8.2.24 - Tooltip for Bank Items only shows for a split second then disappears

### ISSUE THREAD

**Issue by turetafr** [tullamods/Bagnon#1083]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.2.24
 - Server patch: 1.13.3

 **Have you read the changelog? (please don't waste our time)**
Yes

**Describe the bug**
When pointing at items in your bank, the tooltip disappears after a split second then the tooltip is blank/empty until you mouse off of the item and mouse back over it. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to your bank
2. Point at any item
3. Watch tooltip disappear
4. Mouse off and back on to get tooltip again, but it still disappears fast

**Expected behaviour**
The tooltip for whatever bank item you are pointing at should remain on the screen until the mouse is no longer over that item.

**Comment by turetafr** [comment]
I am not using any tooltip addons BTW

**Comment by tymorrow** [comment]
For me, only the top two rows of the bank menu have this problem.
Hope this info helps narrow down the problem.

**Comment by Masumia** [comment]
Same noted behavior here, retail version.

**Comment by cherry-wave** [comment]
> For me, only the top two rows of the bank menu have this problem.
> Hope this info helps narrow down the problem.

This is correct, it is everything that is in the "normal" bank-"bag".

**Comment by icyzephyr** [comment]
I am having a similar issue, but it is only effecting my Reagent Bank. My other bank tabs display normally.

**Comment by albeecode** [comment]
Same issue here.

**Comment by cherry-wave** [comment]
Hey Jaliborc, could you explain why this was closed? When will the bugfix be uploaded?
