### ISSUE TITLE
Opening Bags error - 100% unusable

### ISSUE THREAD

**Issue by leifashley** [tullamods/Bagnon#1084]
I have 2 toons, warrior and shaman, that see this error. Tried cleaning cache and removing bags, no effect on either.

Date: 2019-12-22 11:47:18
ID: 1
Error occured in: Global
Count: 1
Message: ...Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua line 170:
   attempt to perform arithmetic on field 'count' (a nil value)
Debug:
   [C]: ?
   ...Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:170:
      ...Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:145
   (tail call): ?
   (tail call): ?
   ...rface\AddOns\Bagnon\common\Wildpants\classes\bag.lua:158: Update()
   ...rface\AddOns\Bagnon\common\Wildpants\classes\bag.lua:123: RegisterEvents()
   ...rface\AddOns\Bagnon\common\Wildpants\classes\bag.lua:72:
      ...rface\AddOns\Bagnon\common\Wildpants\classes\bag.lua:17
   (tail call): ?
   ...\AddOns\Bagnon\common\Wildpants\classes\bagGroup.lua:17:
      ...\AddOns\Bagnon\common\Wildpants\classes\bagGroup.lua:11
   (tail call): ?
   Bagnon\addons\main\frame.lua:238: CreateBagGroup()
   Bagnon\addons\main\frame.lua:218: PlaceBagGroup()
   Bagnon\addons\main\frame.lua:86: Layout()
   Bagnon\addons\main\frame.lua:65: Update()
   Bagnon\addons\main\frame.lua:55: RegisterSignals()
   ...ace\AddOns\Bagnon\common\Wildpants\classes\frame.lua:20:
      ...ace\AddOns\Bagnon\common\Wildpants\classes\frame.lua:18
   (tail call): ?
   ...AddOns\Bagnon\common\Wildpants\classes\inventory.lua:21:
      ...AddOns\Bagnon\common\Wildpants\classes\inventory.lua:20
   [C]: Show()
   ...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:85: Show()
   ...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:77:
      ...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:76
   (tail call): ?
   ...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:146: ToggleBackpack()
   [string "TOGGLEBACKPACK"]:1:
      [string "TOGGLEBACKPACK"]:1
Locals:

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AtlasLootClassic, vv1.4.3
  AtlasLootClassicData, vv1.4.3
  AtlasLootClassicDungeonsAndRaids, vv1.4.3
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.23
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  ClassicCastbars, vv1.2.0-hotfix
  ClassicCastbarsOptions, v
  DBMCore, v1.13.25
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  Dominos, v8.2.36
  DominosCast, v
  DominosProgress, v
  DominosRoll, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  ExtendedCharacterStats, v1.5
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  LeatrixPlus, v1.13.41
  MonkeyBuddy, v
  MonkeyLibrary, v
  MonkeyQuest, v
  MonkeyQuestLog, v
  Questie, v5.4.0
  ShadowedUnitFrames, vv4.2.1-Classic
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TitanClassic, v1.1.5.11303
  TitanClassicAmmo, v1.1.5.11303
  TitanClassicBag, v1.1.5.11303
  TitanClassicClock, v1.1.5.11303
  TitanClassicGold, v1.1.5.11303
  TitanClassicLocation, v1.1.5.11303
  TitanClassicLootType, v1.1.5.11303
  TitanClassicPerformance, v1.1.5.11303
  TitanClassicRegen, v1.1.5.11303
  TitanClassicRepair, v1.1.5.11303
  TitanClassicVolume, v1.1.5.11303
  TitanClassicXP, v1.1.5.11303
  TomTom, vv11303-1.0.9
  TradeSkillMaster, vv4.8.24
  TradeSkillMasterAppHelper, vv4.0.6
  WeakAuras, v2.15.5
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=77a)

**Comment by Illaren** [comment]
Same Problem here; but only on one Char: The Alt who holdes my Potions

------------------

Date: 2019-12-22 18:26:15
ID: 1
Error occured in: Global
Count: 1
Message: ...Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua line 170:
   attempt to perform arithmetic on field 'count' (a nil value)
Debug:
   [C]: ?
   ...Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:170:
      ...Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:145
   (tail call): ?
   (tail call): ?
   ...rface\AddOns\Bagnon\common\Wildpants\classes\bag.lua:158: Update()
   ...rface\AddOns\Bagnon\common\Wildpants\classes\bag.lua:123: RegisterEvents()
   ...rface\AddOns\Bagnon\common\Wildpants\classes\bag.lua:72:
      ...rface\AddOns\Bagnon\common\Wildpants\classes\bag.lua:17
   (tail call): ?
   ...\AddOns\Bagnon\common\Wildpants\classes\bagGroup.lua:17:
      ...\AddOns\Bagnon\common\Wildpants\classes\bagGroup.lua:11
   (tail call): ?
   Bagnon\addons\main\frame.lua:238: CreateBagGroup()
   Bagnon\addons\main\frame.lua:218: PlaceBagGroup()
   Bagnon\addons\main\frame.lua:86: Layout()
   Bagnon\addons\main\frame.lua:65: Update()
   Bagnon\addons\main\frame.lua:55: RegisterSignals()
   ...ace\AddOns\Bagnon\common\Wildpants\classes\frame.lua:20:
      ...ace\AddOns\Bagnon\common\Wildpants\classes\frame.lua:18
   (tail call): ?
   ...AddOns\Bagnon\common\Wildpants\classes\inventory.lua:21:
      ...AddOns\Bagnon\common\Wildpants\classes\inventory.lua:20
   [C]: Show()
   ...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:85: Show()
   ...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:77: Toggle()
   ...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:184: ToggleAllBags()
   [string "OPENALLBAGS"]:1:
      [string "OPENALLBAGS"]:1
Locals:

AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  ACP, v3.5.6 
  Adapt, v2.3.0-classic
  AdvancedInterfaceOptions, v1.3.3
  Atlas, vv1.45.01.11302
  AtlasClassicWoW, vv1.45.00.11302.05
  AtlasLootClassic, vv1.4.3
  AtlasLootClassicData, vv1.4.3
  AtlasLootClassicDungeonsAndRaids, vv1.4.3
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.23
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  CharacterStatsClassic, v2.8.1
  ClassicThreatMeter, v1.10
  DBMCore, v1.13.25
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.6.6
  Dismounter, v1.2.1
  Enchantrix, v8.2.6506 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6507 (SwimmingSeadragon)
  FishingBuddy, v0.7 Beta 4
  GatherMate2, v1.45.5
  HealCommClassic, v
  Informant, v8.2.6508 (SwimmingSeadragon)
  ItemRack, v
  LunaUnitFrames, v1.0
  OmniCC, v8.3.1
  Puggle, v2.8
  Questie, v5.4.0
  RealMobHealth, v2.17
  RecipeRadarClassic, v1.0.0.23
  Recount, vv1.13.3a
  Spy, v1.0.19
  Stubby, v8.2.6510 (SwimmingSeadragon)
  TankWarningsClassic, v1.1.2
  TinyTooltip, v8.2.1
  TitanClassic, v1.1.5.11303
  TitanClassicAmmo, v1.1.5.11303
  TitanClassicBag, v1.1.5.11303
  TitanClassicClock, v1.1.5.11303
  TitanClassicGold, v1.1.5.11303
  TitanClassicLocation, v1.1.5.11303
  TitanClassicLootType, v1.1.5.11303
  TitanClassicPerformance, v1.1.5.11303
  TitanClassicRegen, v1.1.5.11303
  TitanClassicRepair, v1.1.5.11303
  TitanClassicVolume, v1.1.5.11303
  TitanClassicXP, v1.1.5.11303
  VendorPrice, v1.3.0
  WeaponSwingTimer, v4.1.0
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=761)

**Comment by leifashley** [comment]
I was on an alt alliance side, and I was posting things with TSM, and as it emptied the inventory, I got this error and now can't open the bags on that toon either.
