### ISSUE TITLE
Latest Build is broken (8.2.24)

### ISSUE THREAD

**Issue by gage22171** [tullamods/Bagnon#1085]
Here is the error when I try to get to the options

Date: 2019-12-22 12:29:12
ID: 14
Error occured in: Global
Count: 1
Message: ...terface\AddOns\Bagnon\common\Wildpants\Wildpants.lua line 159:
   attempt to index field 'Options' (a nil value)
Debug:
   [C]: ?
   ...terface\AddOns\Bagnon\common\Wildpants\Wildpants.lua:159: ShowOptions()
   ...s\Bagnon\common\Wildpants\features\slashCommands.lua:46: ?()
   ..\FrameXML\ChatFrame.lua:4839: ChatEdit_ParseText()
   ..\FrameXML\ChatFrame.lua:4502: ChatEdit_SendText()
   ..\FrameXML\ChatFrame.lua:4538: ChatEdit_OnEnterPressed()
   [string "*:OnEnterPressed"]:1:
      [string "*:OnEnterPressed"]:1
Locals:

AddOns:
  Swatter, v7.3.1 (<%codename%>)
  NPCScanOverlay, v7.3.0.1
  NPCScanOverlayBroker, v1.2.7
  Ace3, v
  AskMrRobot, v80
  AstralKeys, v3.20
  Auctionator, v8.2.0
  AzeritePowerWeights, v8.2.16
  AzeriteTooltip, v2.0.6
  Babylonian, v5.1.DEV.332(/embedded)
  BagBrother, v
  Bagnon, v8.2.24
  BagnonBoE, v1.0
  BagnonConfig, v
  BagnonGarbage, v1.0
  BagnonItemLevel, v1.0
  BagnonReagentBankButton, v1.6
  BattlePetBreedID, vr203
  Configator, v5.1.DEV.431(/embedded)
  CursorTrail, v8.2.5.1
  DBMCore, v8.2.31
  DBMDefaultSkin, v
  DBMInterrupts, v8.1.0
  DBMStatusBarTimers, v
  DBMVPVEM, v10.0.0
  Decursive, v2.7.6.6
  Details, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  EasyScrap, v24
  ExRT, v4110
  FarmHud, v8.3-5-release
  FishingBuddy, v1.10.8.3
  Gatherer, v7.3.1
  GatherMate2, v1.45.5
  GatherMateSharing, vv1.12
  GTFO, v4.51
  HHTD, v2.4.9.4
  InstancePortals, v24
  InterruptAnnouncer, v1.0
  MaxCam, vv2.4.2
  MethodDungeonTools, v2.9.6
  MoveAnything, v17.0.7
  NameplateSCT, v1.17
  NPCScan, v8.0.1.13
  Oilvl, v8.2.1
  OldTab, v
  ParagonReputation, v1.24
  Pawn, v2.3.12
  PetJournalEnhanced, v2.9.30
  PetTracker, v8.2.2
  PetTrackerBreeds, v8.2.2
  PetTrackerJournal, v8.2.2
  PetTrackerSwitcher, v8.2.2
  PetTrackerUpgrades, v8.2.2
  RaiderIO, v8.1.0 (v201912220600)
  RaiderIODBUSA, v
  RaiderIODBUSAR, v
  RaiderIODBUSH, v
  RaiderIODBUSHR, v
  RareScanner, v5.6.6
  Rarity, v1.0 (r693-release)
  RarityOptions, v
  Raven, v
  RazerAnansi, v2.8.0
  RazerNaga, v3.0.7
  RazerNagaCast, v
  RazerNagaConfig, v
  RazerNagaEncounter, v
  RazerNagaXP, v
  Rematch, v4.9.13
  RSA, vr525-release
  RSAPriest, v
  SavedInstances, v8.2.6
  Simulationcraft, v1.12.3
  SlideBar, v7.3.1 (<%codename%>)
  TidyPlates, v6.19.4
  TidyPlatesGraphite, v
  TidyPlatesGrey, v
  TidyPlatesNeon, v
  TidyPlatesQuatre, v
  TidyPlatesHub, v
  TidyPlatesWidgets, v
  TomTom, vv80205-1.0.9
  WarfrontRareTracker, v1.0.9
  WeakAuras, v2.15.5
  WIM, v3.8.4
  WorldQuestTracker, v
  ZygorGuidesViewer, v7.0
  BlizRuntimeLib_enUS v8.2.5.80205 <none>
  (ck=849)

![WoWScrnShot_122219_122903](https://user-images.githubusercontent.com/44704244/71325179-16e5de80-24b7-11ea-9830-8fb057178c02.jpg)

**Comment by tkalfaoglu** [comment]
Yes I reported the same but the issue was just closed. I assume he is working on it

**Comment by LilMissBonkers** [comment]
Same problem here

---

Date: 2019-12-22 20:23:14
ID: 25
Error occured in: Global
Count: 1
Message: ...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua line 66:
   attempt to index field 'profile' (a nil value)
Debug:
   ...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:66: IsEnabled()
   ...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:41: New()
   ...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:81: Show()
   ...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:77: Toggle()
   ...s\Bagnon\common\Wildpants\features\slashCommands.lua:36: ?()
   ..\FrameXML\ChatFrame.lua:4839: ChatEdit_ParseText()
   ..\FrameXML\ChatFrame.lua:4502: ChatEdit_SendText()
   ..\FrameXML\ChatFrame.lua:4538:
      ..\FrameXML\ChatFrame.lua:4534
   [C]: ChatEdit_OnEnterPressed()
   [string "*:OnEnterPressed"]:1:
      [string "*:OnEnterPressed"]:1
Locals:
self = <table> {
 SendSignal = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:82
 RegisterMessage = <function> defined @Interface\AddOns\AddOnSkins\Libs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface\AddOns\AddOnSkins\Libs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 Update = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:72
 NewModule = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:68
 HasBag = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:125
 AreBasicsEnabled = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:58
 UnregisterAllEvents = <function> defined @Interface\AddOns\AddOnSkins\Libs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 ShowBag = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:113
 Toggle = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:76
 SendMessage = <function> defined @Interface\AddOns\AddOnSkins\Libs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 ToggleBag = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:107
 New = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:40
 UnregisterSignal = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:78
 registry = <table> {
 }
 Hide = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:90
 Get = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:50
 RegisterEvent = <function> defined @Interface\AddOns\AddOnSkins\Libs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterAllMessages = <function> defined @Interface\AddOns\AddOnSkins\Libs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 IsShown = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:99
 Iterate = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:54
 Show = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:80
 OnEnable = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:12
 RegisterSignal = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:74
 NewLoader = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:21
 IsEnabled = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:62
 HideBag = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:119
 UnregisterEvent = <function> defined @Interface\AddOns\AddOnSkins\Libs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 Tag = "BAGNON_"
}
id = "inventory"
(*temporary) = nil
(*temporary) = <table> {
 SendSignal = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:82
 RegisterMessage = <function> defined @Interface\AddOns\AddOnSkins\Libs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface\AddOns\AddOnSkins\Libs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 Update = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:72
 NewModule = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:68
 HasBag = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:125
 AreBasicsEnabled = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:58
 UnregisterAllEvents = <function> defined @Interface\AddOns\AddOnSkins\Libs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 ShowBag = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:113
 Toggle = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:76
 SendMessage = <function> defined @Interface\AddOns\AddOnSkins\Libs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua
AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  WorldFlightMapLoader, v8.1.0.0
  ACP, v3.5.6 
  AddOnSkins, v4.39
  AdvancedInterfaceOptions, v1.3.3
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.24
  BagnonBoE, v1.0
  BagnonGarbage, v1.0
  BagnonItemLevel, v1.0
  BagnonScrap, v8.2.0
  Bazooka, vv2.9.5
  BlizzMove, vv1.9.3
  BrokerCalendar, v1.3.4
  BrokerEverything, v3.9.0-release
  BrokerMicroMenu, vv1.6
  BrokerWallet, v8.2.5
  BuyEmAll, v3.5.4
  CaerdonWardrobe, vv2.3.5
  CopyPasta, v1.1.2
  ElvUI, v11.27
  ElvUICombatFeedback, v1.18
  ElvUICustomTweaks, v1.49
  ElvUIDTBars2, v8.1.5.0015
  ElvUIExtraDataTexts, v1.9.2
  ElvUISLE, v3.63
  EnhancedPetBattleUI, v4.12
  Farmer, v2.11.1
  GTFO, v4.51
  HandyNotes, vv1.5.9
  HandyNotesDungeonLocations, v1.49
  HandyNotesTravelGuide, vv2.1.2
  HandyNotesWorldMapButton, v80205.01-Release
  HereBeDragons, v2.02-release
  HereBeDragons10, v2.02-release
  HzFontPack1, v1.1.1-release
  InFlightLoad, v8.2.006
  Informant, v8.2.6508 (SwimmingSeadragon)
  LegionWardrobe, v30
  LibGetFrame10, v1.1.9
  MailMinder, v8.0.1.1
  MapNotes, v6.09.50001
  MapNotesBrowser, vv1.00.50001
  MapNotesIconLib, v1.04.50001
  MapNotesIconLibLegacy, v
  Mapster, v1.8.5
  MountsJournal, vv6.2.2
  MoveAnything, v17.0.7
  NPCScan, v8.0.1.13
  PetTracker, v8.2.2
  PetTrackerBreeds, v8.2.2
  PetTrackerJournal, v8.2.2
  PetTrackerSwitcher, v8.2.2
  PetTrackerUpgrades, v8.2.2
  Postal, vv3.6.0
  RareScanner, v5.6.6
  Rarity, v1.0 (r693-release)
  Rematch, v4.9.13
  RematchElvUISkin, v1.2.2
  Scrap, v8.2.0
  SharedMedia, v3.1.0-191
  SharedMediaCausese, v
  SharedMediaAdditionalFonts, v8.2.5
  SilverDragon, vv4.0.17
  SilverDragonBattleForAzeroth, vv4.0.17
  SilverDragonBurningCrusade, vv4.0.17
  SilverDragonCataclysm, vv4.0.17
  SilverDragonLegion, vv4.0.17
  SilverDragonMists, vv4.0.17
  SilverDragonVanilla, vv4.0.17
  SilverDragonWarlords, vv4.0.17
  SilverDragonWrath, vv4.0.17
  SimpleRareElite, v1.29
  Stubby, v8.2.6510 (SwimmingSeadragon)
  tdBattlePetScript, v80100.01
  tdBattlePetScriptRematch, v80100.01
  TomTom, vv80205-1.0.9
  toomanyaddons, vr47
  TransmogWishList, v8.2.03
  WeakAuras, v2.15.5
  WeakAurasCompanion, v1.0.0
  WIM, v3.8.4
  WIMElvUISkin, v80000.01-Release
  WorldFlightMap, v8.1.0.0
  WorldMapTrackingEnhanced, vv3.04
  WoWGatheringNodes, vBFA-8.2.5-update-v1.0
  Wyr3dIcyVeinsStats, v
  BlizRuntimeLib_enUS v8.2.5.80205 <none>
  (ck=acb)
