### ISSUE TITLE
Mouse over issue again

### ISSUE THREAD

**Issue by bh35601** [tullamods/Bagnon#1086]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.2.24-1.13.3
 - Server patch: [e.g. Build 8.0.1.27178]

 **Have you read the changelog? (please don't waste our time)**
 Mark if read.Yes
**Describe the bug**
When you mouse over an item in your bags it will briefly appear what it is and then it is blank

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the first message (labelled 1/Many) that appeared.

**Additional context**

**Comment by DDnutz** [comment]
Getting this as well on all my toons after the update.  Item picture details disappears.

**Comment by DDnutz** [comment]
Update: found it to be the actual BANK bag that is having this issue.  Bags in the bank dont have this problem.

**Comment by TaliesinWhite** [comment]
Bagnon-8.2.24-1.13  WoW 1.13.3.32836
Confirm, that after last update I have the same problem with the main bank bag as noted above.

**Comment by revar** [comment]
Same problem, BANK bag is bugged when u hover mouse on items, please fix.

**Comment by revar** [comment]
Why closed wtf?
