### ISSUE TITLE
add on not working

### ISSUE THREAD

**Issue by johneballz** [tullamods/Bagnon#1088]
I am using the the addon ElvUI w/ the add of Shadow and light. Since the new lastest patch your add on is not working. I see the default ElvUI bags. I didn't know if you are aware and if you can fix it. It was working prior to the last 2 patches not the ring one but the one before that is when it stopped working

**Comment by filliph** [comment]
```
Message: Interface\AddOns\Bagnon_ItemLevel\main.lua:210: Usage: hooksecurefunc([table,] "function", hookfunc)
Time: Sun Dec 22 19:52:53 2019
Count: 1
Stack: Interface\AddOns\Bagnon_ItemLevel\main.lua:210: Usage: hooksecurefunc([table,] "function", hookfunc)
(tail call): ?
[C]: in function `hooksecurefunc'
Interface\AddOns\Bagnon_ItemLevel\main.lua:210: in function `?'
...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:20: in function <...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:18>
...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:56: in function <...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:53>
[C]: ?
...Tom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29: in function <...Tom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...Tom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: in function `Fire'
...ace\AddOns\TomTom\libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...ace\AddOns\TomTom\libs\AceEvent-3.0\AceEvent-3.0.lua:119>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:448: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:567: in function `TimeManager_LoadUI'
Interface\FrameXML\UIParent.lua:1240: in function <Interface\FrameXML\UIParent.lua:1138>

Locals: <none>
```

**Comment by bargiddle** [comment]
having the same issue, elvui and shadow & light for elv.`2x Bagnon_ItemLevel\main.lua:210: Usage: hooksecurefunc([table,] "function", hookfunc)
[C]: in function `hooksecurefunc'
Bagnon_ItemLevel\main.lua:210: in function `?'
...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0-1.lua:20: in function <...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:18>
...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0-1.lua:56: in function <...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:53>
[C]: ?
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
Ace3\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:448: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:567: in function `TimeManager_LoadUI'
FrameXML\UIParent.lua:1240: in function <FrameXML\UIParent.lua:1138>`

`1x ...s\Bagnon\common\Wildpants\features\tooltipCounts.lua:179: attempt to index field 'sets' (a nil value)
...s\Bagnon\common\Wildpants\features\tooltipCounts.lua:179: in function `?'
...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0-1.lua:20: in function <...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:18>
...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0-1.lua:56: in function <...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:53>
[C]: ?
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
Ace3\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>`

`1x ...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:70: attempt to index field 'sets' (a nil value)
...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:70: in function `RegisterDisplayEvents'
...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:28: in function `RegisterGameEvents'
...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:13: in function `?'
...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0-1.lua:20: in function <...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:18>
...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0-1.lua:56: in function <...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:53>
[C]: ?
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
Ace3\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:448: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:491: in function `CombatLog_LoadUI'
FrameXML\UIParent.lua:1242: in function <FrameXML\UIParent.lua:1138>`

the 3 bagnon related errors i get upon login with latest version Bagnon-8.2.24-8.2.5

**Comment by Jaliborc** [comment]
You're running out of date plugins, nothing I can do

**Comment by filliph** [comment]
@Jaliborc so running the latest version of Bagnon and every other addon (according to Twitch/TukUI) still means we all have outdated plugins? 

Can you direct us to where we can download these updates that don’t appear on any of the sites we all get our addons from?

**Comment by mjuopperi** [comment]
> You're running out of date plugins, nothing I can do

So obviously there's been some breaking changes to Bagnon API. Why not point people to what those are so we can fix them in plugins? It's far from obvious from looking at the changes.

**Comment by bargiddle** [comment]
looking at https://github.com/tullamods/Bagnon/issues/1107  my issum came from BagnonItemLevel, the fix for which i found at [https://github.com/AzeriteTeam/Bagnon_ItemLevel/pull/3/commits/159ea8e59b000110d3592ea32f2edfa0c4a29116](url)
