### ISSUE TITLE
sorting

### ISSUE THREAD

**Issue by miltonbrad** [tullamods/Bagnon#1090]
So when you try to sort the bags with the new bagnon addon it tries spam putting items in the key ring even when you make it so its not shown and just spams sorting through the keys in ur key ring.

**Comment by miltonbrad** [comment]
didnt see others are having problems with this issue.

**Comment by mattfromks** [comment]
Im having the same issue

**Comment by Isabello** [comment]
I am also having this issue. 

It seems to get stuck on Scourge Stones and AV/WSG honor tokens from wins/losses.

It is also throwing keys into the main bag from the keyring.

**Comment by albeecode** [comment]
Having the issue here as well.
