### ISSUE TITLE
Clean Up Error WOW Classic

### ISSUE THREAD

**Issue by ty01119** [tullamods/Bagnon#1091]
* The add on tries to put non-key items into keyring during the clean process. It will cause deadlock and stuck in the sorting process.
* Keys put into bags instead of the keyring when other bags got enough spaces for all keys.

### Please fix it ASAP.

Environment:
OS: macOS Mojave 10.14.6 and macOS Catalina 10.15.4

**Comment by albeecode** [comment]
Having the same issue here.

Environment:
OS: Win 10 1903.
