### ISSUE TITLE
Bagnon will not load

### ISSUE THREAD

**Issue by Bakd5150** [tullamods/Bagnon#1094]
Since the update bagnon no longer loads, I type /bagnon and it gives me the typical choices of bags bank guild vault, options but when you type in /bagnon config or anything else it does nothing. any suggestions? It has worked flawlessly for years until today. no error messages either :/

**Comment by NeyanEU** [comment]
Same issue on my side. Every single version of 8.2.2x will not load. I have to reinstall version 8.2.16. That's the latest (release-)version that works properly.

**Comment by Kizmar** [comment]
Not sure if related, but just updated to current version and I'm getting this on game load:

Lua Error 1/3
```
Message: Interface\AddOns\Bagnon_ItemInfo\main.lua:511: Usage: hooksecurefunc([table,] "function", hookfunc)
Time: Mon Dec 23 08:03:36 2019
Count: 1
Stack: Interface\AddOns\Bagnon_ItemInfo\main.lua:511: Usage: hooksecurefunc([table,] "function", hookfunc)
[C]: in function `hooksecurefunc'
Interface\AddOns\Bagnon_ItemInfo\main.lua:511: in function `?'
...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:20: in function <...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:18>
...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:56: in function <...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:53>
[C]: ?
...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29: in function <...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: in function `Fire'
...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:119>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:448: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:491: in function `CombatLog_LoadUI'
Interface\FrameXML\UIParent.lua:1242: in function <Interface\FrameXML\UIParent.lua:1138>

Locals: <none>
```
Lua Error 2/3
```
Message: ...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:70: attempt to index field 'sets' (a nil value)
Time: Mon Dec 23 08:03:36 2019
Count: 1
Stack: ...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:70: attempt to index field 'sets' (a nil value)
...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:70: in function `RegisterDisplayEvents'
...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:28: in function `RegisterGameEvents'
...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:13: in function `?'
...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:20: in function <...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:18>
...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:56: in function <...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:53>
[C]: ?
...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29: in function <...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: in function `Fire'
...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>
```
Lua Error 3/3
```
Message: ...s\Bagnon\common\Wildpants\features\tooltipCounts.lua:179: attempt to index field 'sets' (a nil value)
Time: Mon Dec 23 08:03:38 2019
Count: 1
Stack: ...s\Bagnon\common\Wildpants\features\tooltipCounts.lua:179: attempt to index field 'sets' (a nil value)
...s\Bagnon\common\Wildpants\features\tooltipCounts.lua:179: in function `?'
...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:20: in function <...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:18>
...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:56: in function <...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:53>
[C]: ?
...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29: in function <...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: in function `Fire'
...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:119>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:448: in function `UIParentLoadAddOn'
Interface\AddOns\Appearances\Main.lua:255: in function <Interface\AddOns\Appearances\Main.lua:254>
Interface\AddOns\Appearances\Libs\LibKjasi\Kjasi.lua:195: in function <Interface\AddOns\Appearances\Libs\LibKjasi\Kjasi.lua:188>

Locals: <none>
```

**Comment by Ayrlaine** [comment]
Same problem - and I see the same log messages.  
Additionally, I'm unable to access the Guild bank at all - it just sits there.  At least I can get into my bank (bag by bag - lol) 
I didn't realize how dependant I am on your app!!

**Comment by bryansray** [comment]
Just as a heads up to those who want to get Bagnon working by itself ... if you disable your Bagnon addons, that should temporarily get you up and running.

Also note that some of the Bagnon addons in the User Interface, are not ordered alphabetically. They are at the bottom of the addon list.

I think one of the most common is the `Bagnon_ItemLevel` addon.

Hopefully Bagnon and the addon authors can get this sorted out soon. I'm going to try and figure it out and submit a PR, but will probably take a while.

**Comment by Wenlocke** [comment]
From this thread https://github.com/AzeriteTeam/Bagnon_ItemLevel/issues/2 it looks like they didn't update a bunch of their plugins to match changes in bagnon.

**Comment by bryansray** [comment]
@Wenlocke I'm trying to trace through some of the code and a lot of it stems from not having access to `Addon.sets` in the Wildpants addon.

I'm having a difficult time following some of the abstractions, but from what I can gather:

1. When a Bagnon Addon calls:

```
function Module:OnEnable()
end
```

Bagnon does some "hooking up" and this apparently causes things to crash. I will report back more as I continue to debug ... hopefully I'm not going down a rabbit hole.

**Comment by bryansray** [comment]
So the addon calls a function:

`hooksecurefunc(Bagnon.ItemSlot, "Update", Update)`

However, `Bagnon.ItemSlot` is now `nil` ... I can't seem to find anything relating to `ItemSlot` in the latest version. Perhaps this was changed? Going to try and dive through some git logs ...

**Comment by bryansray** [comment]
Okay so it looks like [this commit](https://github.com/tullamods/Bagnon/commit/7774486d6f6ac8c1fcf72ed84d4520688f3fc1ea) removed changed `ItemSlot` to `Item` maybe? And the addon should be using that?

**Comment by Jaliborc** [comment]
out of date plugins
