### ISSUE TITLE
Cannot access Guild Vault items

### ISSUE THREAD

**Issue by Alchymysts** [tullamods/Bagnon#1097]
**Running Software (issues missing this information will be deleted):**
 - Addon version:
 - Server patch: [e.g. Build 8.0.1.27178]

 **Have you read the changelog? (please don't waste our time)**
 Mark if read.

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the first message (labelled 1/Many) that appeared.

**Additional context**

**Comment by Alchymysts** [comment]
I have the latest version. 8.2.24-8.2.25.zip
First, Bagnon still doesn't put Reagent Bank items into the Reagent Bank. This has been a continuing problem for several versions. Right click on the reagent item and it goes int the normal bank.
BUT, that is NOT the real problem at hand.
Go to the Guild Vault. Even as Guild Master.
Try to get anything from the vault. You can't click on it, select it or move it.
NO error is reported.
When Bagnon is disabled all access is normal.

**Comment by cogar328** [comment]
having this same problem

**Comment by Modan009** [comment]
Same here... I was able to place an item in the guild vault, however not to a designated slot.  And unable   to retrieve any item.  No errors.

**Comment by cogar328** [comment]
why is this closed without a solution? Are you working on it, if so, I can
wait. thanks

**Comment by Modan009** [comment]
why was this issues posted in another post & both closed?
