### ISSUE TITLE
Bank Tooltip broken

### ISSUE THREAD

**Issue by fnordson** [tullamods/Bagnon#1098]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.2.24-1.13.3 (classic)
 - Server patch: 1.13.3.32836

 **Have you read the changelog? (please don't waste our time)**
Yes (not like there is much to read) 

**Describe the bug**
Tooltip disappears and becomes a black blub in bank

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to bank
2. Hover over any item

**Expected behaviour**
Tooltip should show item information

**Screenshots**
https://i.imgur.com/KOjc82S.png

**Additional context**
Tooltip works in bags without problems:
https://i.imgur.com/BRelXtI.png

**Comment by Laxxboy** [comment]
Also having this issue
![WoWScrnShot_122319_120750](https://user-images.githubusercontent.com/59125019/71378536-f7b18480-257c-11ea-98ea-284109d713a0.jpg)

**Comment by cogar328** [comment]
having same problem

**Comment by Labi132** [comment]
Same problem on retail version 8,2,24-8.2.5

**Comment by schufirefly** [comment]
Same issue as well.. I have disabled bagnon and downloaded adibag.. which let me tell you stinks compared to bagnon.

**Comment by Luzbeliten** [comment]
I have this problem specifically with the "base" bank bag, the first 24 slots. On classic, same version as OP.

**Comment by ImRobGit86** [comment]
I also have this problem specifically in the first 24 slots in the bank and all of the slots in the reagent bag.

**Comment by Laxxboy** [comment]
How is this closed with no update on what was done to fix it?

**Comment by fnordson** [comment]
@Jaliborc Why did you close it?
