### ISSUE TITLE
Sorting no longer works with key bag

### ISSUE THREAD

**Issue by GeStanley** [tullamods/Bagnon#1102]
Since the update the "clean items" function no longer works because it tried to put key items into the key bag.

![image](https://user-images.githubusercontent.com/4439370/71391404-f494b380-25d1-11ea-85d9-57adf9e0cad6.png)

**Comment by cruzcranford** [comment]
I'm having this same issue, it actually soft locks my game where i have to reload the ui as its trying to spam move items that it cant move.  Might be a good idea to implement some kind of item move limit.

**Comment by abomb2000** [comment]
I have the same issue, when I click clean up bags once it reaches a key it just stays on it and spams trying to move it.

**Comment by slappieh** [comment]
Is this fixed?

**Comment by GeStanley** [comment]
I just updated to the most recent version and the bug is still present.
