### ISSUE TITLE
the problem continues

### ISSUE THREAD

**Issue by zerocool145** [tullamods/Bagnon#1106]
addon version: 
Bagnon-8.2.25-8.2.5

**Describe the bug**
even after updating it, the addon still doesn't work

![wow1](https://user-images.githubusercontent.com/53354031/71416099-0bb4bf00-262d-11ea-8054-255ca5300711.png)
[Bagnon 1.txt](https://github.com/tullamods/Bagnon/files/3998477/Bagnon.1.txt)
[Bagnon 2.txt](https://github.com/tullamods/Bagnon/files/3998478/Bagnon.2.txt)

**Comment by Soulst3p** [comment]
Try to disable bagnon plugins, if you have installed any.
For me "Bagnon ItemLevel" caused bagnon not working at all.

**Comment by wmill** [comment]
I delete the plugin directory and reinstalled it, that fixed it for me.
