### ISSUE TITLE
cant see items info in bank bag

### ISSUE THREAD

**Issue by akudokeshi** [tullamods/Bagnon#1108]
the first bag in the bank i cant see any of the items info any of the other bags r fine i turned off bagon and it fixed it turned it back on and the problem came back
![WoWScrnShot_122419_151541](https://user-images.githubusercontent.com/59211690/71426022-07a29480-2661-11ea-8003-6d1acb94e45a.jpg)

**Comment by wmill** [comment]
Same issue, every other addon is disabled. For me it only happens in the Reagent Bank.

![WoWScrnShot_122519_152107](https://user-images.githubusercontent.com/867804/71450177-8283b200-272a-11ea-9b1c-ffdee4747bc1.jpg)

Normal bank items still work

![WoWScrnShot_122519_152113](https://user-images.githubusercontent.com/867804/71450181-8dd6dd80-272a-11ea-8f1d-67da3acecd2d.jpg)
