### ISSUE TITLE
issue with azeritetooltip addon

### ISSUE THREAD

**Issue by zdhar** [tullamods/Bagnon#1109]
azeritetooltip not working while bagnon is active
thank for your works !

Message: Interface\AddOns\AzeriteTooltip\AzeriteTooltip.lua:152: Usage: hooksecurefunc([table,] "function", hookfunc)
Time: Wed Dec 25 16:32:11 2019
Count: 1
Stack: Interface\AddOns\AzeriteTooltip\AzeriteTooltip.lua:152: Usage: hooksecurefunc([table,] "function", hookfunc)
[C]: in function `hooksecurefunc'
Interface\AddOns\AzeriteTooltip\AzeriteTooltip.lua:152: in function <Interface\AddOns\AzeriteTooltip\AzeriteTooltip.lua:146>
[C]: ?
...s\AddOnSkins\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:70: in function <...s\AddOnSkins\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
...s\AddOnSkins\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:527: in function `EnableAddon'
...s\AddOnSkins\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:620: in function <...s\AddOnSkins\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:605>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:448: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:567: in function `TimeManager_LoadUI'
Interface\FrameXML\UIParent.lua:1240: in function <Interface\FrameXML\UIParent.lua:1138>

Locals: <none>

**Comment by Jaliborc** [comment]
Not the developer of the addon
