### ISSUE TITLE
Guild bank won't open

### ISSUE THREAD

**Issue by DenterEdwards** [tullamods/Bagnon#1114]
**Running Software (issues missing this information will be deleted):**
 - Addon version:
 - Server patch: [e.g. Build 8.0.1.27178]

 **Have you read the changelog? (please don't waste our time)**
 Mark if read.

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the first message (labelled 1/Many) that appeared.

**Additional context**

**Comment by DenterEdwards** [comment]
Version: Bagnon-8.2.26-8.25.zip (updated through Twitch)
Read changelog
Clicking on guild bag provides no reaction.
Bags open as with original Blizzard UI. One at a time with the Blizzard style.
Here is the error code received upon clicking the guild bank:  Date: 2019-12-27 12:58:17
ID: 5
Error occured in: Global
Count: 1
Message: ...ace\AddOns\Bagnon\common\Wildpants\classes\frame.lua line 134:
   attempt to index field 'profile' (a nil value)
Debug:
   (tail call): ?
   ...ace\AddOns\Bagnon\common\Wildpants\classes\frame.lua:134: GetBaseProfile()
   Bagnon\addons\main\frame.lua:22: New()
   Bagnon\addons\guild\frame.lua:26: New()
   ...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:44: New()
   ...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:81: Show()
   Bagnon\addons\guild\guild.lua:17: ?()
   ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119:
      ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119
   [C]: ?
   ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: SendMessage()
   ...Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:67:
      ...Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:67
   [C]: ?
   ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
   Ace3\AceEvent-3.0\AceEvent-3.0.lua:120:
      Ace3\AceEvent-3.0\AceEvent-3.0.lua:119
Locals:
None
AddOns:
  LibUIDropDownMenu, vv2.01.8020031429
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AccountantClassic, vv2.11.08
  Ace3, v
  ACP, v3.5.6 
  Altoholic, vr191
  Auctionator, v8.2.0
  AuctionatorMiniFeatures, v8.0v1-release
  Bagnon, v8.2.26
  BagnonCurrencies, v1.0.0
  BagnonGuildBank, v
  BagnonItemLevel, v1.0
  BagnonRequiredLevel, v1.11
  BarrelsOEasy, v1.1.11
  Bartender4, v4.8.9
  BattlePetBattleStats, v1.0.11
  BattlePetBreedID, vr203
  BattlePetTabs, v8.2.0.190810
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  BlizzMove, vv1.9.3
  CritSound, v2.5.4
  DataStore, vr66
  DataStoreAchievements, vr48
  DataStoreAgenda, vr30
  DataStoreAuctions, vr51
  DataStoreCharacters, vr44
  DataStoreContainers, vr60
  DataStoreCrafts, vr83
  DataStoreCurrencies, vr39
  DataStoreGarrisons, vr25
  DataStoreInventory, vr54
  DataStoreMails, vr53
  DataStorePets, vr45
  DataStoreQuests, vr47
  DataStoreReputations, vr44
  DataStoreSpells, vr33
  DataStoreStats, vr32
  DataStoreTalents, vr62
  DBMCore, v8.2.31
  DBMDefaultSkin, v
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  Enchantrix, v8.2.6506 (SwimmingSeadragon)
  FBBroker, v1.37.3.1
  FBMergeDatabase, v1.4w
  FBTitan, v1.0.18
  FBTrackingFrame, v1.10
  FishingBuddy, v1.10.8.3
  GatherMate2, v1.45.5
  Guildtax, v1.20
  HandyNotes, vv1.5.9
  HandyNotesTrainers, v1.7.0
  HereBeDragons, v2.02-release
  HereBeDragons10, v2.02-release
  Informant, v8.2.6508 (SwimmingSeadragon)
  InstancePortals, v24
  LibBabbleSubZone30, v
  LibMapData10, v1.0.0.31
  LibStub, v
  MarketWatcher, v2.21
  MaxDps, v8.2.8
  MinimapButtonFrame, v3.1.10h
  NPCScan, v8.0.1.13
  OmniCC, v8.2.5
  Postal, vv3.6.0
  Quartz, v3.5.2
  QuestCompletist, v109.25
  ReagentRecipeTooltip, v1.5
  RecipesVendor, v0.1
  Recount, vv8.2.5d
  Rematch, v4.9.13
  Skada, v1.7.6
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  smashedlibrary, v8.0.0.1
  Stubby, v8.2.6510 (SwimmingSeadragon)
  Titan, v5.18.4.80205
  TitanBag, v5.18.4.80205
  TitanClock, v5.18.4.80205
  TitanFishing, v4.0.001
  TitanGold, v5.18.4.80205
  TitanLocation, v5.18.4.80205
  TitanLootType, v5.18.4.80205
  TitanPerformance, v5.18.4.80205
  TitanProfessionsMulti, v7.1
  TitanRepair, v5.18.4.80205
  TitanVolume, v5.18.4.80205
  TitanXP, v5.18.4.80205
  TomTom, vv80205-1.0.9
  TradeSkillInfo, vv2.4.4
  TradeSkillMaster, vv4.8.24
  TradeSkillMasterAppHelper, vv4.0.6
  TrinketMenu, v7.3.2
  ZygorGuidesViewer, v7.0
  BlizRuntimeLib_enUS v8.2.5.80205 <none>
  (ck=98f)

**Comment by Jaliborc** [comment]
@DenterEdwards please read issue submission instructions
