### ISSUE TITLE
Update on WoWInterface

### ISSUE THREAD

**Issue by armordecai** [tullamods/Bagnon#1116]
Please don't stop updating Bagnon on WoWInterface.

I've just recently started playing again after several years, and CurseForge is even more of a headache than it used to be. Their website is a mess, logging in through Twitch is an ordeal, and their updater app is incredibly bloated (I don't care about any streaming or social features) and really slow and buggy. By contrast, WoWInterface is just as simple and easy to use as it's always been.

Thanks!

**Comment by Jaliborc** [comment]
Wowinterface does that automatically, not us

**Comment by armordecai** [comment]
I'm not sure how that's set up, but it doesn't seem to be working, as no new versions have been posted there since March.
