### ISSUE TITLE
Error "/bagnon bags" - attempt to index field 'profile' (a nil value)

### ISSUE THREAD

**Issue by PeterGabriel2** [tullamods/Bagnon#1121]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.2.2.7

 **Have you read the changelog? (please don't waste our time)**
Yes

**Describe the bug**
Execution of command "/bagnon bags" cause this error
I have tried this command because after update I don't see bagnon GUI.

**To Reproduce**
1. Shift Enter
2. /bagnon bags
3. Enter

**Expected behaviour**
To be able to see bagnon GUI instead of classic GUI

**Screenshots**

**Error Logs**
Date: 2019-12-28 12:46:28
ID: 13
Error occured in: Global
Count: 1
Message: ...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua line 66:
   attempt to index field 'profile' (a nil value)
Debug:
   ...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:66: IsEnabled()
   ...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:41: New()
   ...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:81: Show()
   ...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:77: Toggle()
   ...s\Bagnon\common\Wildpants\features\slashCommands.lua:36: ?()
   ..\FrameXML\ChatFrame.lua:4839: ChatEdit_ParseText()
   ..\FrameXML\ChatFrame.lua:4502: ChatEdit_SendText()
   ..\FrameXML\ChatFrame.lua:4538: ChatEdit_OnEnterPressed()
   [string "*:OnEnterPressed"]:1:
      [string "*:OnEnterPressed"]:1
Locals:
self = <table> {
 SendSignal = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:82
 RegisterMessage = <function> defined @Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 Update = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:72
 NewModule = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:68
 HasBag = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:125
 AreBasicsEnabled = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:58
 UnregisterAllEvents = <function> defined @Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 ShowBag = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:113
 Toggle = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:76
 SendMessage = <function> defined @Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 ToggleBag = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:107
 New = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:40
 UnregisterSignal = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:78
 registry = <table> {
 }
 Hide = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:90
 Get = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:50
 RegisterEvent = <function> defined @Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterAllMessages = <function> defined @Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 IsShown = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:99
 Iterate = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:54
 Show = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:80
 OnEnable = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:12
 RegisterSignal = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:74
 NewLoader = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:21
 IsEnabled = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:62
 HideBag = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:119
 UnregisterEvent = <function> defined @Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 Tag = "BAGNON_"
}
id = "inventory"
(*temporary) = nil
(*temporary) = <table> {
 SendSignal = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:82
 RegisterMessage = <function> defined @Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 Update = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:72
 NewModule = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:68
 HasBag = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:125
 AreBasicsEnabled = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:58
 UnregisterAllEvents = <function> defined @Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 ShowBag = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:113
 Toggle = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:76
 SendMessage = <function> defined @Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 ToggleBag = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua:107
 New = <funct
AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  Atlas, vv1.45.01
  AtlasBurningCrusade, vv1.45.00
  AtlasCataclysm, vv1.45.00
  AtlasClassicWoW, vv1.45.00
  AtlasDungeonLocs, vv1.45.00
  AtlasMistsofPandaria, vv1.45.00
  AtlasOutdoorRaids, vv1.45.00
  AtlasScenarios, vv1.44.00
  AtlasTransportation, vv1.45.00
  AtlasWarlordsofDraenor, vv1.45.00
  AtlasWrathoftheLichKing, vv1.45.00
  AtlasLoot, vv8.10.00
  AtlasLootBattleforAzeroth, vv8.10.00
  AtlasLootBurningCrusade, vv8.10.00
  AtlasLootCataclysm, vv8.10.00
  AtlasLootClassic, vv8.10.00
  AtlasLootLegion, vv8.10.00
  AtlasLootMistsofPandaria, vv8.10.00
  AtlasLootWarlordsofDraenor, vv8.10.00
  AtlasLootWrathoftheLichKing, vv8.10.00
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucScanData, v8.2.6498 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.27
  BagnonBoE, v1.0
  BagnonFacade, v8.2.0
  BagnonGarbage, v1.0
  Bartender4, v4.8.9
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  Chatter, v1.6.0
  DBMCore, v8.2.31
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Enchantrix, v8.2.6506 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6507 (SwimmingSeadragon)
  Frames, v1.1
  Gatherer, v7.3.1
  Informant, v8.2.6508 (SwimmingSeadragon)
  Masque, v8.2.8
  NeedToKnow, v4.0.28
  Omen, v3.2.2
  Pawn, v2.3.14
  Recount, vv8.2.5d
  Rematch, v4.9.13
  SharedMediaAdditionalFonts, v8.2.5
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  Stubby, v8.2.6510 (SwimmingSeadragon)
  TomTom, vv80205-1.0.9
  VuhDo, v3.109
  VuhDoOptions, v3.109
  WeakAuras, v2.15.5
  BlizRuntimeLib_enUS v8.2.5.80205 <none>
  (ck=75a)

This is on addon load (after gui reload):

Date: 2019-12-28 13:06:35
ID: 1
Error occured in: Global
Count: 1
Message: ...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua line 70:
   attempt to index field 'sets' (a nil value)
Debug:
   ...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:70: RegisterDisplayEvents()
   ...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:28: RegisterGameEvents()
   ...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:13: ?()
   ...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:20:
      ...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:18
   ...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:56:
      ...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:53
   [C]: ?
   ...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
   ...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:120:
      ...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:119
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:448: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:567: TimeManager_LoadUI()
   ..\FrameXML\UIParent.lua:1240:
      ..\FrameXML\UIParent.lua:1138
Locals:
None

**Comment by Lethay** [comment]
Try deleting Bagnon.lua, in World of Warcraft\_classic_\WTF\Account\[ACCCOUNTNAME]\SavedVariables  -- assuming this is classic

**Comment by PeterGabriel2** [comment]
It is not classic but standard WOW. I tried to delete this file but still the same problem.

**Comment by filliph** [comment]
Similar issue:

```
Message: ...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:70: attempt to index field 'sets' (a nil value)
Time: Sat Dec 28 16:19:00 2019
Count: 1
Stack: ...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:70: attempt to index field 'sets' (a nil value)
(tail call): ?
...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:70: in function `RegisterDisplayEvents'
...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:28: in function `RegisterGameEvents'
...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:13: in function `?'
...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:20: in function <...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:18>
...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:56: in function <...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:53>
[C]: ?
...Tom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29: in function <...Tom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...Tom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: in function `Fire'
...ace\AddOns\TomTom\libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...ace\AddOns\TomTom\libs\AceEvent-3.0\AceEvent-3.0.lua:119>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:448: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:567: in function `TimeManager_LoadUI'
Interface\FrameXML\UIParent.lua:1240: in function <Interface\FrameXML\UIParent.lua:1138>

Locals: <none>
```

Deleting Bagnon.lua and Bagnon.lua.bak in SavedVariables does not fix the issue.

**Comment by filliph** [comment]
Similar issue:

```
Message: ...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:70: attempt to index field 'sets' (a nil value)
Time: Sat Dec 28 16:19:00 2019
Count: 1
Stack: ...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:70: attempt to index field 'sets' (a nil value)
(tail call): ?
...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:70: in function `RegisterDisplayEvents'
...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:28: in function `RegisterGameEvents'
...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:13: in function `?'
...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:20: in function <...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:18>
...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:56: in function <...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:53>
[C]: ?
...Tom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29: in function <...Tom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...Tom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: in function `Fire'
...ace\AddOns\TomTom\libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...ace\AddOns\TomTom\libs\AceEvent-3.0\AceEvent-3.0.lua:119>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:448: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:567: in function `TimeManager_LoadUI'
Interface\FrameXML\UIParent.lua:1240: in function <Interface\FrameXML\UIParent.lua:1138>

Locals: <none>
```

Deleting Bagnon.lua and Bagnon.lua.bak in SavedVariables does not fix the issue.

**Comment by cocobella** [comment]
Same here, driving me mad.  Regular WoW, happened when I try /bagnon config

Date: 2019-12-28 10:03:22
ID: 21
Error occured in: Global
Count: 1
Message: ...ace\AddOns\Bagnon\common\Wildpants\config\shared.lua line 37:
   attempt to index field 'sets' (a nil value)
Debug:
   [C]: ?
   ...ace\AddOns\Bagnon\common\Wildpants\config\shared.lua:37: AddCheck()
   ...ce\AddOns\Bagnon\common\Wildpants\config\general.lua:12: Populate()
   ...ace\AddOns\Bagnon\common\Wildpants\config\shared.lua:19: method()
   ...n\Wildpants\libs\Sushi-3.1\classes\core\Callable.lua:52: FireCalls()
   ...on\Wildpants\libs\Sushi-3.1\classes\groups\Group.lua:70:
      ...on\Wildpants\libs\Sushi-3.1\classes\groups\Group.lua:67
   [C]: Show()
   ..\FrameXML\InterfaceOptionsFrame.lua:28: InterfaceOptionsList_DisplayPanel()
   ..\FrameXML\InterfaceOptionsFrame.lua:46: InterfaceOptionsListButton_OnClick()
   ..\FrameXML\InterfaceOptionsFrame.lua:469: InterfaceOptionsFrame_OpenToCategory()
   ...\Wildpants\libs\Sushi-3.1\classes\groups\Options.lua:78: Open()
   ...terface\AddOns\Bagnon\common\Wildpants\Wildpants.lua:159: ShowOptions()
   ...s\Bagnon\common\Wildpants\features\slashCommands.lua:46: ?()
   ..\FrameXML\ChatFrame.lua:4839: ChatEdit_ParseText()
   ..\FrameXML\ChatFrame.lua:4502: ChatEdit_SendText()
   ..\FrameXML\ChatFrame.lua:4538: ChatEdit_OnEnterPressed()
   [string "*:OnEnterPressed"]:1:
      [string "*:OnEnterPressed"]:1
Locals:

AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AllTheThings, v1.9.9c
  Altoholic, vr191
  BagBrother, v
  Bagnon, v8.2.27
  BagnonConfig, v
  BagnonItemLevel, v1.0
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  CanIMogIt, v8.2.5v1.21
  DataStore, vr66
  DataStoreAchievements, vr48
  DataStoreAgenda, vr30
  DataStoreAuctions, vr51
  DataStoreCharacters, vr44
  DataStoreContainers, vr60
  DataStoreCrafts, vr83
  DataStoreCurrencies, vr39
  DataStoreGarrisons, vr25
  DataStoreInventory, vr54
  DataStoreMails, vr53
  DataStorePets, vr45
  DataStoreQuests, vr47
  DataStoreReputations, vr44
  DataStoreSpells, vr33
  DataStoreStats, vr32
  DataStoreTalents, vr62
  DBMCore, v8.2.31
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Dominos, v8.2.36
  DominosCast, v
  DominosConfig, v
  DominosEncounter, v
  DominosProgress, v
  DominosRoll, v
  EasyScrap, v24
  GarrisonMissionManager, vv59
  GarrisonMissionManagerLoadOnLogin, vv1
  GTFO, v4.51
  GuildMemberInfo, v0.2.5
  GuildMemberInfoTradeSkills, v0.4.7
  Identity2, v4.0.4
  Informant, v8.2.6508 (SwimmingSeadragon)
  LegionTreasures, v7.3.5.26822
  LootAppraiser, vv1.9.6
  MapCoords, v0.32
  MapNotes, v6.09.50001
  MapNotesBrowser, vv1.00.50001
  MapNotesIconLib, v1.04.50001
  MapNotesIconLibFancy, v
  MapNotesIconLibLegacy, v
  MapNotesIconLibNeptunia, v
  MapNotesIconLibNumbers, v
  MaxDps, v8.2.8
  MethodDungeonTools, v2.9.6
  MonkStaggerMeter, v1.3.4
  MoveAnything, v17.0.7
  NOP, v09.16 16.12.2018
  Omen, v3.2.2
  Paste, v1.4.10
  prioTarget, v1.3.6
  QuestCompletist, v109.25
  QuickLoot, v0.0.2
  Simulationcraft, v1.12.3
  Skada, v1.7.6
  SkadaForTanks, v3.1.14
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  Stubby, v8.2.6510 (SwimmingSeadragon)
  TargetNameplateIndicator, v1.34
  TomTom, vv80205-1.0.9
  TradeSkillMaster, vv4.8.24
  TradeSkillMasterAppHelper, vv4.0.6
  WeakAuras, v2.15.5
  WorldQuestsList, v91
  BlizRuntimeLib_enUS v8.2.5.80205 <none>
  (ck=782)

**Comment by Pandemoniumus** [comment]
The same problem... Retail WoW. I don't see Bagnon UI instead of classic Bliz UI after update 8.2.27...

Logs:
Message: ...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:70: attempt to index field 'sets' (a nil value)
Time: Sun Dec 29 09:33:04 2019
Count: 1
Stack: ...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:70: attempt to index field 'sets' (a nil value)
(tail call): ?
...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:70: in function `RegisterDisplayEvents'
...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:28: in function `RegisterGameEvents'
...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:13: in function `?'
...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:20: in function <...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:18>
...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:56: in function <...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:53>
[C]: ?
...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29: in function <...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: in function `Fire'
...ccountant_Classic\Libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...ccountant_Classic\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:448: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:567: in function `TimeManager_LoadUI'
Interface\FrameXML\UIParent.lua:1240: in function <Interface\FrameXML\UIParent.lua:1138>

Locals: <none>
Message: ...s\Bagnon\common\Wildpants\features\tooltipCounts.lua:179: attempt to index field 'sets' (a nil value)
Time: Sun Dec 29 09:33:04 2019
Count: 1
Stack: ...s\Bagnon\common\Wildpants\features\tooltipCounts.lua:179: attempt to index field 'sets' (a nil value)
(tail call): ?
...s\Bagnon\common\Wildpants\features\tooltipCounts.lua:179: in function `?'
...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:20: in function <...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:18>
...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:56: in function <...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:53>
[C]: ?
...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29: in function <...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: in function `Fire'
...ccountant_Classic\Libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...ccountant_Classic\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:448: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:491: in function `CombatLog_LoadUI'
Interface\FrameXML\UIParent.lua:1242: in function <Interface\FrameXML\UIParent.lua:1138>

Locals: <none>

Message: ...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:66: attempt to index field 'profile' (a nil value)
Time: Sun Dec 29 09:35:01 2019
Count: 1
Stack: ...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:66: attempt to index field 'profile' (a nil value)
[C]: ?
...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:66: in function `IsEnabled'
...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:41: in function `New'
...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:81: in function `Show'
...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:77: in function `Toggle'
...s\Bagnon\common\Wildpants\features\slashCommands.lua:36: in function `?'
Interface\FrameXML\ChatFrame.lua:4839: in function <Interface\FrameXML\ChatFrame.lua:4785>
[C]: in function `ChatEdit_ParseText'
Interface\FrameXML\ChatFrame.lua:4502: in function <Interface\FrameXML\ChatFrame.lua:4501>
[C]: in function `ChatEdit_SendText'
Interface\FrameXML\ChatFrame.lua:4538: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:
