### ISSUE TITLE
window transparency settings WoW - Classic

### ISSUE THREAD

**Issue by rulezxy** [tullamods/Bagnon#1122]
still cant change the transparency of the border/window frame
you can only take a color but you cant hide the border like before the keyring update
also the color settings are bugged. if you /reload it will be transparent again (not the border but the background) but if you apply on color at settings the background is fully covered again. 

I use this addon since years and I need to hide the border because it looks stupid for my custom UI plus the color settings are buggy too which is kinda annoying. Please fix that ty

**Comment by Jaliborc** [comment]
Fixed internally
