### ISSUE TITLE
Broken after Today

### ISSUE THREAD

**Issue by AldursApprentice** [tullamods/Bagnon#1128]

**Comment by AldursApprentice** [comment]
![WoWScrnShot_123119_200613](https://user-images.githubusercontent.com/16158148/71637460-6f308500-2c09-11ea-9c9b-0f3850c06c41.jpg)
![WoWScrnShot_123119_200632](https://user-images.githubusercontent.com/16158148/71637461-73f53900-2c09-11ea-8093-05f9becc83d8.jpg)
![WoWScrnShot_123119_200454](https://user-images.githubusercontent.com/16158148/71637463-79528380-2c09-11ea-9243-aaf2ba83450f.jpg)
![WoWScrnShot_123119_200458](https://user-images.githubusercontent.com/16158148/71637464-7eafce00-2c09-11ea-8bed-9959dd029b1b.jpg)
![WoWScrnShot_123119_200459](https://user-images.githubusercontent.com/16158148/71637466-853e4580-2c09-11ea-88ba-f7128b1b83e3.jpg)
![WoWScrnShot_123119_200501](https://user-images.githubusercontent.com/16158148/71637468-96875200-2c09-11ea-82a8-5f0c9d640ba9.jpg)

After updating today, Bagnon is non-functional in all aspects. Pics show Bagnon options checked in addon menu, having to open each individual bag, and that there are no options in the interface menu.

**Comment by diegonicacio** [comment]
Had to fully delete the addon +config folder then reinstall to get it back working here

**Comment by Martucho** [comment]
> Had to fully delete the addon +config folder then reinstall to get it back working here

How exactly do you do that? Jan 7th and still not working for me

**Comment by Bjorkenson** [comment]
Deleted bagnon out of my entire pc and reinstalled it from twitch and i still have this issue. i hate blizzard bags so fix this fast please

**Comment by Jaliborc** [comment]
uninstall out of date plugins
