### ISSUE TITLE
Guild Bank issues

### ISSUE THREAD

**Issue by ziboo789** [tullamods/Bagnon#1130]
![WoWScrnShot_010320_204005](https://user-images.githubusercontent.com/59495681/71759996-5cb58600-2e6b-11ea-9b5d-aa87c5f349a2.jpg)
![WoWScrnShot_010320_204101](https://user-images.githubusercontent.com/59495681/71759997-5cb58600-2e6b-11ea-829c-91e7d1204424.jpg)

**Running Software (issues missing this information will be deleted):**
 - Addon version:
 - Server patch: [e.g. Build 8.0.1.27178]

 **Have you read the changelog? (please don't waste our time)**
yes. checking it daily for a fix

**Describe the bug**
Opening the guild bank on any character it appears blank until /reload.  You can move things around add/withdraw items or funds, etc. but splitting stacks is a no go. You get an error message. Once you've touched the add/withdraw funds and close the bank, character won't move other than forward w/o another /reload.

It's not super annoying, but annoying enough, that I'm actually trying to give some info on this bug.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**
Added two screenshots,not sure how helpful they are though.

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the first message (labelled 1/Many) that appeared.

**Additional context**

**Comment by ziboo789** [comment]
After initial opening a /reload will let you use the GB.  You can't split stacks though, but can transfer to inventory, split and return with not errors.

Adding/WD funds still requires a /reload too.

**Comment by semecan** [comment]
Commenting out line 20 in item.lua fixes not being able to split item stacks in the guild bank.
