### ISSUE TITLE
In cached bags or banks, empty item slots have tooltip of last active non-empty item slot.

### ISSUE THREAD

**Issue by LudiusMaximus** [tullamods/Bagnon#1132]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.2.27-8.2.5
 - Server patch: Build 8.2.5.32750

 **Have you read the changelog? (please don't waste our time)**
yes

**Describe the bug**
In cached bags or banks, empty item slots have the tooltip of the last active non-empty item slot.

**To Reproduce**
Open a cached bag (e.g. of another character) or bank (while not at the bank or of another character). Hover with the mouse cursor over a non-empty item slot. Observe that the tooltip shows up as expected. Then hover over a couple of non-empty item slots and obsevere that the same tooltip is still shown.

**Expected behaviour**
Empty item slots should have no mouse-over tooltip.

**Comment by LudiusMaximus** [comment]
Probably related: When you hover with the mouse cursor over an item in a cached bag and close the bag frame (pressing ESC), the tooltip overlay remains visible until you hover over anything else that creates a new game tooltip.

**Comment by Jaliborc** [comment]
fixed
