### ISSUE TITLE
Bagnon fails to run

### ISSUE THREAD

**Issue by inconsistent2** [tullamods/Bagnon#1134]
Bugsack reports

17x ...s\Bagnon\common\Wildpants\features\tooltipCounts.lua:179: attempt to index field 'sets' (a nil value)
...s\Bagnon\common\Wildpants\features\tooltipCounts.lua:179: in function `?'
...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0-1.lua:20: in function <...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:18>
...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0-1.lua:56: in function <...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:53>
[C]: ?
...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
DataStore\libs\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by Jaliborc** [comment]
disable out of date plugins
