### ISSUE TITLE
8.2.29 cannot remove junk coin icon

### ISSUE THREAD

**Issue by wienfuchs** [tullamods/Bagnon#1136]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.2.29
 - Server patch: [e.g. Build 8.2.5.32978]

 **Have you read the changelog? (please don't waste our time)**
Have read changelog

**Describe the bug**
New feature "marks sellable gray items with the default junk coin icon." is not switched off when switching off grelevant config option in colors.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Interface / Addons / Bagnon / Colors'
2. Remove highlight option for grey / unusable items
3. Open your bags => annoying (new) coin symbol still there

**Expected behaviour**
Coin icon not visible when swithiching higlighting to off

**Screenshots**

**Additional context**
Maybe many users want this "highlight" - I don't. I want to get rid of it or have a working configurable option _not_ to show this.

**Comment by vioray** [comment]
agreed, there needs to be a way to disable that annoying coin
