### ISSUE TITLE
Bank shows zero guild bank accesses for me while using the Guild bank addon and can't access but disabling the Guild bank and trying to pull something from the guild bank I am successful.

### ISSUE THREAD

**Issue by rruggles** [tullamods/Bagnon#1137]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.2.29
 - Server patch: [e.g. Build 8.0.1.27178]. 8.2.5.32750

 **Have you read the changelog? (please don't waste our time)**
 Mark if read. yes

**Describe the bug**
Essentially when you open the guild bank it shows that you have so many accesses, in this case one access. Within five seconds it changes to zero. And can't remove items from the bank. When disabling Bagnon Guild Bank I am then allowed to remove an item from the Guild Bank.
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Guild Bank
2. Click on Guild Bank
3. Scroll down to (Not needed)
4. See error No errors showing in BugSack

**Expected behaviour**
What is expected is that I am able to remove an item from the Guild Bank without disabling Bagnon Guild Bank
**Screenshots**
Screenshots added below
**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the first message (labelled 1/Many) that appeared.
As said above, I use BugSack / BugGrabber combo to be able to copy errors from, so the Type `/console scriptErrors 1` is not needed
![Showing Goblin Glider that I am about to remove](https://user-images.githubusercontent.com/9421512/72217132-79e7f580-34f8-11ea-8abb-746e6fa1f8bc.png)
![Showing that Goblin Glider has been removed](https://user-images.githubusercontent.com/9421512/72217133-7a808c00-34f8-11ea-83a4-dc538a67bb5e.png)
![Within 5 secs of opening bank, access has now switched to zero access (without taking anything)](https://user-images.githubusercontent.com/9421512/72217134-7a808c00-34f8-11ea-91dc-d32ae100e02c.png)
![Showing that there is one access available for me right after opening the bank](https://user-images.githubusercontent.com/9421512/72217135-7a808c00-34f8-11ea-88bd-4e79490fa233.png)

**Additional context**
The screenshots are all named with what is going on in them. Cheers!

**Comment by DasReport** [comment]
Here's the error report I got on this:

1x ...faceBagnon\common\Wildpants\classes\item.lua:378: attempt to index local 'link' (a nil value)
...faceBagnon\common\Wildpants\classes\item.lua:378: in function <...faceBagnon\common\Wildpants\classes\item.lua:370>

Locals:
slot = <unnamed> {
 0 = <userdata>
 UpdateTooltip = <function> defined @Bagnon\common\Wildpants\classes\item.lua:370
}
parent = BagnonGuildItem22 {
 0 = <userdata>
 PostOnLoad = <function> defined @FrameXML\ItemButtonTemplate.lua:169
 GetSlotType = <function> defined @Bagnon\common\Wildpants\classes\item.lua:456
 IconOverlay = <unnamed> {
 }
 SlotTypes = <table> {
 }
 Super = <function> defined @Bagnon\common\Wildpants\libs\Poncho-2.0\Poncho-2.0.lua:138
 flashAnim = <unnamed> {
 }
 SetLocked = <function> defined @Bagnon\common\Wildpants\classes\item.lua:275
 GetTemplate = <function> defined @Bagnon\common\Wildpants\libs\Poncho-2.0\Poncho-2.0.lua:89
 ExtendedOverlay = <unnamed> {
 }
 itemContextChangedCallbackIsSet = true
 GetFrame = <function> defined @Bagnon\common\Wildpants\classes\parented.lua:39
 PostOnHide = <function> defined @FrameXML\ItemButtonTemplate.lua:198
 NewItemTexture = <unnamed> {
 }
 IsQuestItem = <function> defined @Bagnon\addons\guild\item.lua:99
 GetBaseProfile = <function> defined @Bagnon\common\Wildpants\classes\parented.lua:27
 RegisterMessage = <function> defined @Bagnon\common\Wildpants\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Bagnon\common\Wildpants\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 Update = <function> defined @Bagnon\common\Wildpants\classes\item.lua:185
 GetInfo = <function> defined @Bagnon\common\Wildpants\classes\item.lua:444
 UpdateItemContextOverlay = <function> defined @FrameXML\ItemButtonTemplate.lua:222
 Count = BagnonGuildItem22Count {
 }
 OnPreClick = <function> defined @Bagnon\common\Wildpants\classes\item.lua:137
 searchOverlay = BagnonGuildItem22SearchOverlay {
 }
 Construct = <function> defined @Bagnon\addons\guild\item.lua:13
 SendSignal = <function> defined @Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:82
 bag = 1
 NewModule = <function> defined @Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:68
 __template = "ContainerFrameItemButtonTemplate"
 Flash = <unnamed> {
 }
 OnItemFlashed = <function> defined @Bagnon\common\Wildpants\classes\item.lua:314
 UpdateUpgradeIcon = <function> defined @Bagnon\common\Wildpants\classes\item.lua:266
 GetSuper = <function> defined @Bagnon\common\Wildpants\libs\Poncho-2.0\Poncho-2.0.lua:85
 GetSlot = <function> defined @Bagnon\addons\guild\item.lua:91
 RegisterCallback = <function> defined @FrameXML\ItemButtonTemplate.lua:175
 UnregisterCallback = <function> defined @FrameXML\ItemButtonTemplate.lua:182
 UnregisterFrameSignal = <function> defined @Bagnon\common\Wildpants\classes\base.lua:19
 Release = <function> defined @Bagnon\common\Wildpants\libs\Poncho-2.0\Poncho-2.0.lua:120
 Cooldown = BagnonGuildItem22Cooldown {
 }
 Tag = "BAGNON_"
 NewClass = <function> defined @Bagnon\common\Wildpants\classes\base.lua:9
 GetOwnerInfo = <function> defined @Bagnon\common\Wildpants\classes\base.lua:32
 IsNew = <function> defined @Bagnon\addons\guild\item.lua:100
 FlashFind = <function> defined @Bagnon\common\Wildpants\classes\item.lua:307
 ExtendedOverlay2 = <unnamed> {
 }
 IsPaid = <function> defined @Bagnon\addons\guild\item.lua:101
 __index = <table> {
 }
 __name = "BagnonGuildItem"
 RegisterSignal = <function> defined @Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:74
 IsActive = <function> defined @Bagnon\common\Wildpants\libs\Poncho-2.0\Poncho-2.0.lua:134
 IsUpgrade = <function> defined @Bagnon\common\Wildpants\classes\item.lua:426
 UpdateFocus = <function> defined @Bagnon\
