### ISSUE TITLE
No Tooltip For Mythic Keystones

### ISSUE THREAD

**Issue by rdkill** [tullamods/Bagnon#1140]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.2.29
 - Server patch: 8.2.5.32978 ? [e.g. Build 8.0.1.27178]

 **Have you read the changelog? (please don't waste our time)**
 Mark if read. I have read

**Describe the bug**
Mythic Keystones no longer display a tooltip. Everything else in bags show tooltips except Mythic Keystones.
**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the first message (labelled 1/Many) that appeared.

**Additional context**

**Comment by Yllelder** [comment]
I don't see the tooltip either.

**Comment by Que04** [comment]
Myself and a friend are having the same issues. No tooltip for keys. We have to link them in chat to see what they are.

**Comment by kexes** [comment]
Not only for keys. I have some battle pets in my inventory, also none of them have item tooltip... Using Bagnon 8.2.29.

**Comment by Labi132** [comment]
Same issue here

**Comment by rgrahamp** [comment]
> Not only for mythic+ keys. I have also some battle pets in my inventory, none of them have item tooltip... Using Bagnon 8.2.29.

up

**Comment by remikzu** [comment]
Not seeing a tooltip too. Any possible fix?

**Comment by darkportal86** [comment]
my errors with the bagbrother item count 

Message: ...rface\AddOns\Bagnon\common\Wildpants\core\owners.lua:88: bad argument #1 to 'unpack' (table expected, got nil)
Time: Thu Jan 16 17:06:24 2020
Count: 1
Stack: ...rface\AddOns\Bagnon\common\Wildpants\core\owners.lua:88: bad argument #1 to 'unpack' (table expected, got nil)
[string "=[C]"]: in function `unpack'
[string "@Interface\AddOns\Bagnon\common\Wildpants\core\owners.lua"]:88: in function `GetOwnerIconString'
[string "@Interface\AddOns\Bagnon\common\Wildpants\features\tooltipCounts.lua"]:127: in function <...s\Bagnon\common\Wildpants\features\tooltipCounts.lua:58>
[string "@Interface\AddOns\Bagnon\common\Wildpants\features\tooltipCounts.lua"]:147: in function <...s\Bagnon\common\Wildpants\features\tooltipCounts.lua:144>
[string "=[C]"]: ?
[string "=[C]"]: in function `SetBagItem'
[string "@Interface\FrameXML\ContainerFrame.lua"]:1413: in function `ContainerFrameItemButton_OnEnter'
[string "@Interface\AddOns\Bagnon\common\Wildpants\components\item.lua"]:379: in function `ShowTooltip'
[string "@Interface\AddOns\Bagnon\common\Wildpants\components\item.lua"]:210: in function <...e\AddOns\Bagnon\common\Wildpants\components\item.lua:203>

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"

**Comment by voidzone** [comment]
@Jaliborc any idea what's causing it? Appears to still be an issue in 8.3.1-8.3.0

**Comment by Beamrgurl** [comment]
Posting 2 pictures when with mouse over a gem, and one with mouse over the key
![WoWScrnShot_011720_140629](https://user-images.githubusercontent.com/9388444/72649605-fc2a4c80-3932-11ea-83b5-4f3abbdb999c.jpg)
![WoWScrnShot_011720_140639](https://user-images.githubusercontent.com/9388444/72649610-ff253d00-3932-11ea-9022-42e3d8805ef7.jpg)

**Comment by Beamrgurl** [comment]
Ive added 2 screenshots one with item info display and then a keystone.
![WoWScrnShot_011720_141154](https://user-images.githubusercontent.com/9388444/72649836-8e325500-3933-11ea-97bc-9fef27288732.jpg)
![WoWScrnShot_011720_141159](https://user-images.githubusercontent.com/9388444/72649839-9094af00-3933-11ea-9e1a-27a7357fe98f.jpg)

**Comment by Jmasb** [comment]
I also have this issue, very annoying.

**Comment by vodwuar** [comment]
i am also having the same issue. ive tried both bagnon and combuctor and they both have the same issue. both updated to 8.3

**Comment by ultima98** [comment]
Same issue. My addon is up-to-date. Very annoying bug.

**Comment by Mays** [comment]
same issue.

**Comment by brentrichardjr** [comment]
Caged battle pets show up as Pet Cage in the guild tab instead of showing what pet is caged. Both the icon showed and the tooltip displayed are for Pet Cage regardless of what actual pet it is. In bags, the icon is correct, but no tooltip.

**Comment by DarkforceNL** [comment]
I dont understand this, another new version and still keystones tooltips r not fixed!!!!!!

**Comment by ocandoe** [comment]
i have the samen issue

**Comment by Doshilol** [comment]
Just updated it to 8.3.3, this issue no longer persists. Thanks!
