### ISSUE TITLE
LUA in Classic

### ISSUE THREAD

**Issue by rbrewer3125** [tullamods/Bagnon#1141]
Message: ...face\AddOns\Bagnon\common\Wildpants\classes\item.lua:378: attempt to index local 'link' (a nil value)
Time: Sun Jan 12 12:03:47 2020
Count: 3
Stack: ...face\AddOns\Bagnon\common\Wildpants\classes\item.lua:378: attempt to index local 'link' (a nil value)
...face\AddOns\Bagnon\common\Wildpants\classes\item.lua:378: in function <...face\AddOns\Bagnon\common\Wildpants\classes\item.lua:370>
[C]: in function `Show'
...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:85: in function `Show'
...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:77: in function <...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:76>
(tail call): ?
...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:146: in function `ToggleBackpack'
[string "TOGGLEBACKPACK"]:1: in function <[string "TOGGLEBACKPACK"]:1>

Locals: slot = <unnamed> {
 0 = <userdata>
 UpdateTooltip = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\classes\item.lua:370
}
parent = ContainerFrame3Item9 {
 0 = <userdata>
 OnEnter = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\classes\item.lua:173
 __super = <table> {
 }
 GetSlotType = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\classes\item.lua:456
 IconOverlay = <unnamed> {
 }
 SlotTypes = <table> {
 }
 UpdateCooldown = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\classes\item.lua:279
 Bind = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\classes\item.lua:101
 IconBorder = <unnamed> {
 }
 flashAnim = <unnamed> {
 }
 SetLocked = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\classes\item.lua:275
 ShowCachedTooltip = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\classes\item.lua:362
 OnShow = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\classes\item.lua:117
 ExtendedOverlay = <unnamed> {
 }
 __type = "Button"
 __count = 80
 GetFrameID = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\classes\parented.lua:19
 GetEmptyItemIcon = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\classes\item.lua:461
 IsQuestItem = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\classes\item.lua:415
 SplitStack = <function> defined @Interface\FrameXML\ContainerFrame.lua:1060
 BagStaticBottom = <unnamed> {
 }
 count = 0
 UpdateLocked = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\classes\item.lua:197
 UnregisterMessage = <function> defined @Interface\AddOns\Tukui\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 Update = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\classes\item.lua:185
 flash = <unnamed> {
 }
 CreateDummy = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\classes\item.lua:369
 RegisterFrameSignal = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\classes\base.lua:15
 GetBlizzard = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\classes\item.lua:88
 UpdateSearch = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\classes\item.lua:291
 info = <table> {
 }
 IsAbstract = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\Poncho-2.0\Poncho-2.0.lua:97
 UnregisterSignal = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:78
 frame = BagnonInventoryFrame1 {
 }
 UnregisterAll = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\classes\base.lua:27
 NewModule = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:68
 GetProfile = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\classes\parented.lua:23
 IconGlow = <unnamed> {
 }
 icon = ContainerFrame3Item9IconTexture {
 }
 GetInfo = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\classes\item.lua:444
 __name = "BagnonItem"
 RegisterSignal = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:74
 Count = ContainerFrame3Item9Count {
 }
 UpdateTooltip = <function> d

**Comment by Jaliborc** [comment]
Fixed internally
