### ISSUE TITLE
Lua error in 8.3 

### ISSUE THREAD

**Issue by Vikirnoff** [tullamods/Bagnon#1144]
Hello! I am getting this error every time i hover over items in my bag.  Thanks. 

28x Bagnon\common\Wildpants\api\owners.lua:90: bad argument #1 to 'unpack' (table expected, got nil)
[string "=[C]"]: in function `unpack'
[string "@Bagnon\common\Wildpants\api\owners.lua"]:90: in function `GetIconString'
[string "@Bagnon\common\Wildpants\features\tooltipCounts.lua"]:126: in function <...s\Bagnon\common\Wildpants\features\tooltipCounts.lua:57>
[string "@Bagnon\common\Wildpants\features\tooltipCounts.lua"]:146: in function <...s\Bagnon\common\Wildpants\features\tooltipCounts.lua:143>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetInventoryItem'
[string "@FrameXML\PaperDollFrame.lua"]:1684: in function `PaperDollItemSlotButton_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"

https://drive.google.com/file/d/19k-eYddA_42kVrse-XQt9hlwwaMtgIEf/view?usp=sharing
https://drive.google.com/file/d/1FN2EnWmiMr_F5GtSGpP_0ljo6_fQ0yXg/view?usp=sharing

**Comment by eckter** [comment]
It comes from this table in Wildpants: https://github.com/tullamods/Wildpants/blob/master/api/owners.lua#L18

The new allied races are missing. 

I don't exactly understand the purpose of this table so I won't open a PR with a proper fix myself, but you can make a temporary fix locally. Just copy paste a line in the table to create a `VULPERA_MALE` (or whatever you need).  It would be in `Bagnon/common/Wildpants/api/owner.api`, line 19.

**Comment by itegumo** [comment]
That table is for the icons that show in the list of Alts in the menu for view alt inventory, and the icon in the top-left corner of Bagnon.
It is currently broken for both Vulpera and Mechagnomes.
