### ISSUE TITLE
Pet information issue

### ISSUE THREAD

**Issue by Kessi999** [tullamods/Bagnon#1145]
Latest version does not show information for pet cages. The screenshots shows 2 different Enchanted Cauldrons, as you can see the freshly created one shows the info but the recently caged one does not. 

I exited the game and only loaded Bagnon when these screenshots were taken.

![WoWScrnShot_011420_182239](https://user-images.githubusercontent.com/59902614/72399433-0530d900-36fb-11ea-831d-645b3c593ab1.jpg)

![WoWScrnShot_011420_182243](https://user-images.githubusercontent.com/59902614/72399441-0a8e2380-36fb-11ea-8ab9-1f23ea0bac1e.jpg)

**Comment by dementiala** [comment]
same problem here

**Comment by Voxxel** [comment]
Same bug here, Bagnon does not show any item info when hovering over any pet cage. This is since Patch 8.3 and with the latest version 8.3.0-1.13.3.

When disabling Bagnon, the game displays the info correctly using the stock bags.

**Comment by Allie82** [comment]
Same issue with caged pets no longer showing tooltip. Pets that have not been learned still have tooltip, but anything caged has nothing on mouseover. 

Works normally when Bagnon deactivated and using standard WoW UI Bags.

**Comment by jrwizzard** [comment]
I have posted issues with auctioneer which contains the informant addon, will post here to. Ditto on the issue, not sure which addon is responsible.

**Comment by Voxxel** [comment]
it's not a question. If you enable only Bagnon it doesn't show the pet tooltip. if you disable bagnon it shows up. Maybe it's a shared issue among a type of addons such as the 3D portrait issue which affects many related addons but this ticket is still valid here on Bagnon's page since there's still a bug with it.

**Comment by WizardOI** [comment]
Same issue here. I turned off every addon i have and then turned them on one by one until the tooltip disappeared with bagnon turned on.
![Screenshot 2020-01-23 11 21 52](https://user-images.githubusercontent.com/60261548/73072844-a0ece280-3e7b-11ea-87ec-e09e6d890883.png)
![Screenshot 2020-01-23 11 23 15](https://user-images.githubusercontent.com/60261548/73072845-a0ece280-3e7b-11ea-9ba4-4b4e020c77ff.png)

**Comment by TheNapTime** [comment]
I've tracked this down to a [commit ](https://github.com/tullamods/Wildpants/commit/1c108c2476ca98296b8101da4f29e78a5d553981)in the Wildpants library. Reverting the relevant parts of this commit does not completely resolve the issue as you'll have to mouse over the caged pet twice before the tooltip shows.

**Comment by TheNapTime** [comment]
This appears to be fixed for me after updating to 8.3.3 today
