### ISSUE TITLE
Can not see inventory of other characters

### ISSUE THREAD

**Issue by jlcampbell001** [tullamods/Bagnon#1147]
Click on the button and the drop down list will show up with the characters.  When I click on a character nothing happens.  It just shows my current character's inventory instead of the one I selected.  This list also stays showing.
It is like the onclick event is not happening.
This is happening since the patch.

**Comment by Ninjabug27** [comment]
Mine isn't even giving me the option to select a different toon. It also won't show my gold amounts for other toons. It will however show my individual items on other toons if I hover over them.

**Comment by Kueckling** [comment]
Holy smokes, i had the same issue - and my combined gold also didnt work. Finally i found out whats the problem. Vulpera!
When bagbrother writes an entry for your vulpera in BagBrother.lua file it somehow corrupts.
Delete the entry and it works just fine after that.

Idk if you have to delete it also in BagBrother.lua.bak - but i did it to be save.

You also can just delete the 2 files and let them rewrite again (then you have to login to all your chars once again to be listed)

**Comment by Ninjabug27** [comment]
Uninstalled the add on and reinstalled it fixed my problem!! Give that a try @jlcampbell001

**Comment by Kueckling** [comment]
@Ninjabug27 please try logging on your vulpera if you happen to have one and see if the bug appears again - i could reproduce it that way. even created another vulpera to confirm

**Comment by Ninjabug27** [comment]
Yep. It sure did. Damn it...

**Comment by Kueckling** [comment]
@Jaliborc Vulperan charakters seem to break somehow the BagBrother Plugin - doesn't let you bring up you character list or your combined gold.
Please see comments above.

thank you for this awesome addon and your continious support for it!

**Comment by jlcampbell001** [comment]
I tried both suggestions.  Deleting the files and then uninstalling and reinstalling.  These did not work.  I still have the issue.
I do not have a Vulperan character and have never made one.
I can bring up the list but clicking on an alt character is not doing anything.

**Comment by jlcampbell001** [comment]
Also the drop down to select which frame you want to set options for in the Frame Setting options screen is also not working for me.
It shows the list of frames but I can not select any of them.

**Comment by itegumo** [comment]
Vulpera and Mechagnomes both break this.

**Comment by Voxxel** [comment]
> When bagbrother writes an entry for your vulpera in BagBrother.lua file it somehow corrupts.

I don't even created any of the allied races in wow and I still have this bug.
