### ISSUE TITLE
Mythic key details not seen

### ISSUE THREAD

**Issue by Beamrgurl** [tullamods/Bagnon#1149]
Everything else is working great for me, when I highlight over my mythic key with my mouse its blank. I actually have to link in say or party chat to read it. When I disable bagnon I can read the key from bag.

**Comment by voidzone** [comment]
https://github.com/tullamods/Bagnon/issues/1140

**Comment by xlxmackxlx** [comment]
i am also having this problem

**Comment by Praybone** [comment]
Same issue for me

**Comment by zooloogorbonos** [comment]
Perhaps the problem is in the languages? Is it normal in English, but is problem in other languages?

**Comment by Praybone** [comment]
i play in english aswell but it still does not work :(

**Comment by xlxmackxlx** [comment]
I am also using English and have also tried the console error code check and no popup box

**Comment by Ghasterly** [comment]
Yeah I am having the same problem, tried a couple of other inventory addons and they are not having this issue..

**Comment by BloodDragon2580** [comment]
It's only at Bagnon. It's very stupid but so I must change to a other addon. Sorry.

**Comment by GoutKing** [comment]
I'm also seeing this issue, along with several of my guildmates.  It's not a deal breaker, but it is annoying.  English language mod.

**Comment by jajamy** [comment]
still the problem...

**Comment by NuggyBear** [comment]
Problem still remaining. Even after 2 updates. As someone who does Mythic keys everyday this is becoming annoying.

**Comment by Aneti11** [comment]
I am having the same problem too... about a week or more...

**Comment by Roneasaurus** [comment]
i have had the same issue since the last patch. have to go back to version 8.2.27 to be able to see the keystones in my bag.
