### ISSUE TITLE
Bagnon Guildbank Crashalong

### ISSUE THREAD

**Issue by EvitiniaOnTwitch** [tullamods/Bagnon#1150]
**Running Software (issues missing this information will be deleted):**
 - Addon version: Bagnon-8.3.1-8.3.0.zip
 - Server patch: 8.3.0.33073
 **Have you read the changelog? (please don't waste our time)**
 Mark if read.

**Describe the bug**
Openening the GB, all icons are invisible, however you can grab the items in there. If you are allowed to move items in the GB doing so will crash your game,

**To Reproduce**
Steps to reproduce the behaviour:
Open GB
If items are invis, grab one, put it on another slot and put a new item in the slot you just freed up,
Results in gamecrash

**Expected behaviour**
Icons should appear, you should be able to move them around!

**Screenshots**
https://youtu.be/S7gjIFgkj7c
Video instead of SC

**Error Logs**
Error logs don't work for me anymore, I somehow killed them altogether in my WoW installation

**Additional context**

**Comment by jrwizzard** [comment]
I usually have to open and close the gbank 3-4 times just to see what is in it. Same with changing tabs, reopen a few times. It is hit or miss if I can actually get anything from it. It has been like this for at least 2 updates of bagnon.
