### ISSUE TITLE
Option to disable gold icon on junk items

### ISSUE THREAD

**Issue by VirtueAvatar** [tullamods/Bagnon#1151]
**Is your feature request related to a problem? Please describe.**
A recent update added a gold icon on grey items, there is no way to turn this off.

**Describe the solution you'd like**
An option to turn off the gold icon, or even one to make it opt-in only.

**Describe alternatives you've considered**
Uninstalling bagnon and using another addon's backpack

**Additional context**
n/a

**Comment by Jaliborc** [comment]
already exitsts
