### ISSUE TITLE
Something about wildpants

### ISSUE THREAD

**Issue by DraconisImperius** [tullamods/Bagnon#1154]
Error code i get whenever i pass over a bag in my ui or the money slot. not sure how to fix.

Message: ...erface\AddOns\Bagnon\common\Wildpants\api\owners.lua:90: bad argument #1 to 'unpack' (table expected, got nil)
Time: Sat Jan 18 15:22:57 2020
Count: 13
Stack: ...erface\AddOns\Bagnon\common\Wildpants\api\owners.lua:90: bad argument #1 to 'unpack' (table expected, got nil)
[string "=[C]"]: in function `unpack'
[string "@Interface\AddOns\Bagnon\common\Wildpants\api\owners.lua"]:90: in function `GetIconString'
[string "@Interface\AddOns\Bagnon\common\Wildpants\features\tooltipCounts.lua"]:126: in function <...s\Bagnon\common\Wildpants\features\tooltipCounts.lua:57>
[string "@Interface\AddOns\Bagnon\common\Wildpants\features\tooltipCounts.lua"]:146: in function <...s\Bagnon\common\Wildpants\features\tooltipCounts.lua:143>
[string "=[C]"]: ?
[string "=[C]"]: in function `SetInventoryItem'
[string "@Interface\FrameXML\MainMenuBarBagButtons.lua"]:79: in function `BagSlotButton_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"

**Comment by alexnaumovich** [comment]
I also get multiple similar errors last few days:

Here's one:

Message: Interface\AddOns\FlashTaskBar\FlashTaskBar.lua:597: table index is nil
Time: Sat Jan 18 22:11:11 2020
Count: 23
Stack: Interface\AddOns\FlashTaskBar\FlashTaskBar.lua:597: table index is nil
[string "@Interface\AddOns\FlashTaskBar\FlashTaskBar.lua"]:597: in function <Interface\AddOns\FlashTaskBar\FlashTaskBar.lua:583>
[string "=[C]"]: ?
[string "@Interface\AddOns\Bagnon\common\Wildpants\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\Bagnon\common\Wildpants\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\Bagnon\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

Here's another one:

Message: Interface\AddOns\PitBull4\Modules\Aggro\Aggro.lua:44: attempt to index field 'db' (a nil value)
Time: Sat Jan 18 22:10:16 2020
Count: 1
Stack: Interface\AddOns\PitBull4\Modules\Aggro\Aggro.lua:44: attempt to index field 'db' (a nil value)
[string "@Interface\AddOns\PitBull4\Modules\Aggro\Aggro.lua"]:44: in function `?'
[string "@Interface\AddOns\PitBull4\Main.lua"]:1037: in function `CallMethodOnModules'
[string "@Interface\AddOns\PitBull4\ModuleHandling\Module.lua"]:112: in function <Interface\AddOns\PitBull4\ModuleHandling\Module.lua:98>
[string "=[C]"]: ?
[string "@Interface\AddOns\Bagnon\common\Wildpants\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\Bagnon\common\Wildpants\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\Bagnon\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

The same problem was also reported in [1142](https://github.com/tullamods/Bagnon/issues/1142).
