### ISSUE TITLE
mythic plus keystone shows no information

### ISSUE THREAD

**Issue by vodwuar** [tullamods/Bagnon#1157]
Since the World of warcraft 8.3 update my bags show all the proper tooltips but the mythic keystone. i mouse over the keystone and no information is displayed at all. when i disable the bagnon addon the correct information is displayed. i tried uninstalling bagnon and trying the classic look version and the same issue is present.

**Comment by yoshimo** [comment]
#1140

**Comment by jrwizzard** [comment]
I posted with auctioneer, which contains the informant addon which is for tooltips, I also posted with angry keystone. Posting here to cover all bases. The M+ keystone is fine when posted to chat and clicked, but in the bag on mouseover there is nothing.

**Comment by beardedgamer96** [comment]
Battle pets are being effected as well

**Comment by NuggyBear** [comment]
It has been broken for so long I would advise moving to another addon. Inventorian works perfectly.

**Comment by yoshimo** [comment]
last commit in the repo is from 7 days ago, far from dead.
