### ISSUE TITLE
Will not load at start-up

### ISSUE THREAD

**Issue by jsey21** [tullamods/Bagnon#1164]
Please see the error message below:

Date: 2020-02-02 17:04:11
ID: 15
Error occured in: Global
Count: 1
Message: ...ace\AddOns\Bagnon\common\Wildpants\config\frames.lua line 13:
   attempt to index field 'profile' (a nil value)
Debug:
   [string "=[C]"]: ?
   [string "@Bagnon\common\Wildpants\config\frames.lua"]:13: Populate()
   [string "@Bagnon\common\Wildpants\config\shared.lua"]:19: method()
   [string "@Bagnon\common\Wildpants\libs\Sushi-3.1\classes\core\Callable.lua"]:52: FireCalls()
   [string "@Bagnon\common\Wildpants\libs\Sushi-3.1\classes\groups\Group.lua"]:70:
      ...on\Wildpants\libs\Sushi-3.1\classes\groups\Group.lua:67
   [string "=[C]"]: Show()
   [string "@..\FrameXML\InterfaceOptionsFrame.lua"]:28: InterfaceOptionsList_DisplayPanel()
   [string "@..\FrameXML\InterfaceOptionsFrame.lua"]:46: InterfaceOptionsListButton_OnClick()
   [string "*:OnClick"]:2:
      [string "*:OnClick"]:1
Locals:

AddOns:
  MoncaiCompare, v7.2.0
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AskMrRobot, v83
  AtlasLoot, vv8.11.00
  AtlasLootBattleforAzeroth, vv8.11.00
  AtlasLootBurningCrusade, vv8.11.00
  AtlasLootCataclysm, vv8.11.00
  AtlasLootClassic, vv8.11.00
  AtlasLootLegion, vv8.11.00
  AtlasLootMistsofPandaria, vv8.11.00
  AtlasLootWarlordsofDraenor, vv8.11.00
  AtlasLootWrathoftheLichKing, vv8.11.00
  Auctionator, v8.2.0
  AutoRepair, v
  BagBrother, v
  Bagnon, v8.3.3
  BagnonChampion, v3.0
  BagnonConfig, v
  BagnonCurrencies, v1.0.0
  BagnonFacade, v8.3.0
  BagnonScrap, v8.3.0
  BlizzBuffsFacade, v8.0.1
  BrokerDualSpec, v8.01
  Buffwatch, v8.17
  Buffy, v3.2.0
  ClassSpecStats, v1.48
  CTCore, v8.3.0.1
  CTLibrary, v8.3.0.1
  CTMailMod, v8.3.0.1
  DBMCore, v8.3.9
  DBMDefaultSkin, v
  DBMInterrupts, v8.2.5
  DBMRaidLeadTools, v
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  Decursive, v2.7.6.6
  GatherMate2, v1.45.5
  GatherMateSharing, vv1.12
  GryphonsRemover, vv8.3.0
  GTFO, v4.52.2
  HealBot, v8.3.0.0
  HealBotData, v8.3.0.0
  HealBoten, v8.3.0.0
  HealBotOptions, v8.3.0.0
  HealBotTips, v8.3.0.0
  Informant, v8.2.6508 (SwimmingSeadragon)
  LibSharedMedia30, v3.0-112
  Masque, v8.2.8
  MasqueAbstract, vwow6.0.2-2.0
  MasqueApathy, v8.2.6
  MasqueAzona, vv1
  MasqueBamboo, v1
  MasqueCainyx, v8.0.0
  MasqueCaith, v8.2.6
  MasqueCards, v6.2.0
  MasqueCirque, v8.2.5
  MasqueCleanIcons, v1.5
  MasqueCleanUI, v8.3.0
  MasqueDark, v3.1.0
  MasqueDarkscail, v1
  MasqueDiabloIII, v1.6
  MasqueDiabolic, v1.0
  MasqueElegance, v6.2.0
  MasqueEleganceLegion, v1.0
  MasqueEleganceLegion2, v1.0
  MasqueElvUIesque, v1.0
  MasqueEntropy, v8.2.5
  MasqueFlatSquares, v1.0.8
  MasqueGears, v8.0.0
  MasqueGmSr, v801-2018081101
  MasqueGoldpaw, v1.0-Release
  MasqueGrunge, v1
  MasqueHelloKitty, v7.0.00
  MasqueImoen, v1.0.1
  MasqueJigsaw, v6.2.0
  MasqueKenzo, v2.0.0
  MasqueLiteStep, v8.0.0
  MasqueMuq, v7.2.1
  MasqueOnyx, v8.0.0
  masqueparabole, v6.0.0.1
  MasqueRaeli, vr20-release
  MasqueRenaitre, vv7.0.3
  MasqueSerenity, v8.0.0
  MasqueShadow, vv6.2.2
  MasqueSimpleSquare, v7.1.0.0
  MasqueSleek, v6.2.0
  MasqueSonata, v1.0.2
  MasqueStylo, vv7.2.0
  MasqueTones, v6.2.0
  MasqueVista, v2.0.4
  MikScrollingBattleText, v5.7.150
  NPCScan, v8.0.1.13
  Omen, v3.2.2
  OPie, vWalnut 6
  OPieMasque, v7.3.5.0
  Outfitter, v5.22.1
  Pawn, v2.3.20
  PersonalLootHelper, v2.21
  QEDungeonTips, v4.9.0
  Recount, vv8.3.0a
  Scrap, v8.3.0
  ScrapConfig, v
  Stubby, v8.2.6510 (SwimmingSeadragon)
  Titan, v5.18.5.80300
  TitanBag, v5.18.5.80300
  TitanClock, v5.18.5.80300
  TitanCoords, v5.0.0.40000
  TitanCurrency, v8.3
  TitanDurability, v1.24
  TitanEmote, v1.0.21.70000
  TitanGold, v5.18.5.80300
  TitanGoldTracker, v4.3.9.40000
  TitanHealBot, v5.3.0.8
  TitanLocation, v5.18.5.80300
  TitanLootType, v5.18.5.80300
  TitanMount, v4.0.0
  TitanPerformance, v5.18.5.80300
  TitanRaidIds, v2.4.71
  TitanReagentTracker, v1.7.1
  TitanRecount, v4.0.0
  TitanRepair, v5.18.5.80300
  TitanRoll, v
  TitanVolume, v5.18.5.80300
  TitanWG, v1.2.1.40000
  TitanXP, v5.18.5.80300
  TrinketMenu, v7.3.2
  XPerlFacade, v4.0.1
  BlizRuntimeLib_enUS v8.3.0.80300 <none>
  (ck=c6a)

**Comment by Jaliborc** [comment]
ID != 1
