### ISSUE TITLE
Can't use items from bag

### ISSUE THREAD

**Issue by Naxterra** [tullamods/Bagnon#1175]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.3.5-8.3.0
 - Server patch: 8.3.0 - 33528

 **Have you read the changelog? (please don't waste our time)**
Yes

**Describe the bug**
When I click on a useable item in my bag, it gives me error, even with heartstone

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Bag
2. Click on Heartstone or a Fish
3. See error

**Expected behaviour**
Expect no error

**Screenshots**
![image](https://user-images.githubusercontent.com/41871948/76709433-eea8fd00-66fe-11ea-8a08-69ea81915c9d.png)

**Error Logs**
Date: 2020-03-15 20:47:06
ID: 2
Error occured in: AddOn: Bagnon
Count: 1
Message: Error: AddOn Bagnon attempted to call a forbidden function (UNKNOWN()) from a tainted execution path.
Debug:
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: UseContainerItem()
   [string "@..\FrameXML\ContainerFrame.lua"]:1332: ContainerFrameItemButton_OnClick()
   [string "*:OnClick"]:12:
      [string "*:OnClick"]:1
   [string "=[C]"]: ?
Locals:
None
AddOns:
  Swatter, v8.3.BETA-4-4 (NzothsFolly)
  ACP, v3.5.7 
  AngryAssignments, vv1.13.0c
  BadBoy, vv8.2.5
  BadBoyCCleaner, vv8.2.0
  BadBoyLevels, vv8.2.1
  BagBrother, v
  Bagnon, v8.3.5
  Bartender4, v4.9.0
  CursorTrail, v8.3.0.2
  DBMArchaeology, v
  DBMCore, v8.3.17
  DBMCountPackHotS, v1.7.6
  DBMCountPackOverwatch, v1.4.10
  DBMDefaultSkin, v
  DBMInterrupts, v8.3.0
  DBMSoundEventsPack, v1.6.5
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  DBMVPVEM, v10.0.1
  FishingBuddy, v1.10.8.8
  GatherMate2, v1.45.5
  GTFO, v4.55
  HandyNotes, vv1.5.9
  HandyNotesAchievements, v0.4.22
  HandyNotesArgus, vv0.15
  HandyNotesAzerothsTopTunes, vv1.2.2
  HandyNotesBattleForAzerothTreasures, v1
  HandyNotesBrokenShore, vv1.33
  HandyNotesDraenorTreasures, v1.21
  HandyNotesDungeonLocations, v1.50
  HandyNotesFieldPhotographer, v8.0.0.0
  HandyNotesHigherLearning, v8.0.0.0
  HandyNotesLegionRaresTreasures, v1.1
  HandyNotesLegionTreasures, v1
  HandyNotesLongForgottenHippogryph, v1
  HandyNotesLunarFestival, vv1.6.2
  HandyNotesPandariaTreasures, v1.06
  HandyNotesTimelessIsleChests, v1.22
  HandyNotesWarfrontRares, v0.5.0
  HandyNotesWellRead, v8.0.0.0
  LeatrixPlus, v8.3.09
  MasterPlanA, vA
  MikScrollingBattleText, v5.7.150
  MoveAnything, v17.1.0
  NPCScan, v8.0.1.13
  Omen, v3.2.2
  OmniCC, v8.3.5
  Overachiever, v1.0.9
  OverachieverCache, v1.0.9
  OverachieverTrade, v1.0.9
  Pawn, v2.3.23
  Postal, vv3.6.2
  Quartz, v3.5.2
  QuestCompletist, v109.27
  RaidAchievement, v
  RaidAchievementOldModules, v
  RaiderIO, v8.1.0 (v202003150600)
  RaiderIODBEUA, v
  RaiderIODBEUAR, v
  RaiderIODBEUH, v
  RaiderIODBEUHR, v
  Recount, vv8.3.0c
  RSA, vr526-release
  RSADemonHunter, v
  SexyMap, vv8.3.0
  ShadowedUnitFrames, vv4.2.9
  TidyPlatesThreatPlates, v9.1.20
  TipTacTalents, v19.03.31
  Titan, v5.18.6.80300
  TitanBag, v5.18.6.80300
  TitanClock, v5.18.6.80300
  TitanGold, v5.18.6.80300
  TitanLocation, v5.18.6.80300
  TitanLootType, v5.18.6.80300
  TitanPerformance, v5.18.6.80300
  TitanRepair, v5.18.6.80300
  TitanVolume, v5.18.6.80300
  TitanXP, v5.18.6.80300
  TomCats, v01.05.00
  TomCatsMechagon, v01.04.06
  TomCatsNazjatar, v01.04.06
  TomCatsNzoth, v1.4.23
  Transcriptor, vv8.3.1
  WeakAuras, v2.16.6
  WorldQuestsList, v92
  BlizRuntimeLib_enUS v8.3.0.80300 <none>
  (ck=8fc)

**Comment by nbspjr** [comment]
Having the same issue, it randomly occurs when right clicking useable items in bags. If it happens, I can't use anything from bags until restart or ui reload. Sometimes the affected item gets "stuck" and cannot be moved until restart (ui reload doesn't help)

```Date: 2020-10-14 10:48:51
ID: 1
Error occured in: AddOn: Bagnon
Count: 2
Message: Error: AddOn Bagnon attempted to call a forbidden function (UNKNOWN()) from a tainted execution path.
Debug:
   [C]: ?
   [C]: UseContainerItem()
   ..\FrameXML\ContainerFrame.lua:1250: ContainerFrameItemButton_OnClick()
   [string "*:OnClick"]:12:
      [string "*:OnClick"]:1
   [C]: ?
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  Announcer, v
  AtlasLootClassic, vv1.5.6
  AtlasLootClassicData, vv1.5.6
  AtlasLootClassicDungeonsAndRaids, vv1.5.6
  AtlasLootClassicMaps, vv1.0.0
  auxaddon, v1.0.5
  BagBrother, v
  Bagnon, v9.0.1
  Bartender4, v4.9.0
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  ccc, v1.1.7
  ClassicCastbars, v1.3.12
  ClassicCastbarsOptions, v
  DBMCore, v1.13.60
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  ExtendedCharacterStats, v2.6.1
  FishingBuddy, v0.7.3 Beta 7
  FloTotemBar, v
  GatherMate2, v1.45.5
  GlobalIgnoreList, v1.13.3
  InFlightLoad, v1.13.005
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  LeatrixPlus, v1.13.80
  MissingTradeSkillsList, v1.13.51
  OPie, vAncient Xe 1a
  Plater, vPlater-1.13.5.91-Classic
  Prat30, v3.8.26
  Prat30Libraries, v
  RCLootCouncilClassic, v0.11.2
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  SortBags, v1.0.3
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TitanClassic, v1.2.4.11305
  TitanClassicAmmo, v1.2.4.11305
  TitanClassicBag, v1.2.4.11305
  TitanClassicClock, v1.2.4.11305
  TitanClassicGold, v1.2.4.11305
  TitanClassicLocation, v1.2.4.11305
  TitanClassicLootType, v1.2.4.11305
  TitanClassicMail, v1.0.0.1
  TitanClassicPerformance, v1.2.4.11305
  TitanClassicRegen, v1.2.4.11305
  TitanClassicRepair, v1.2.4.11305
  TitanClassicVolume, v1.2.4.11305
  TitanClassicXP, v1.2.4.11305
  TitanProfessionsMulti, v1.5.2
  TradeSkillMaster, vv4.10.9
  TradeSkillMasterAppHelper, vv4.0.9
  TranqRotate, v1.4.0
  WeakAuras, v2.18.4
  WeaponSwingTimer, v4.1.0
  ZPerl, v5.9.8
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidFrames, v
  ZPerlRaidHelper, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_enUS v1.13.5.11305 <none>
  (ck=75d)

```
