### ISSUE TITLE
Bagnon's databroker display doesn't show all broker addons anymore

### ISSUE THREAD

**Issue by hisako87** [tullamods/Bagnon#1176]
Addon version 8.3.5
Server patch 8.3.0 (33528) (Release x64)

Yes I always read the changelog...

So I originally put off installing any updates to Bagnon since December because every time I did, there was some kind of problem and bagnon didn't show at all. I'd always have to revert back to the October release (8.2.16). After the WoW 8.3 patch, Bagnon broke and I had to update - anyway, the addon itself works fine.

My issue is the databroker display at the bottom of the inventory. I used to be able to cycle through like 8 broker plugins (pre-8.3), now it only cycles through 2 of them. 

Where does the problem lie? I have other broker display addons like Bazooka and these plugins show up no problem on those. With Bagnon it was just a "set it and forget it" kinda thing where as long as the broker plugin was enabled I could find it in Bagnon's broker display.

**Comment by Spillmaker** [comment]
Got some reports of this on my databroker addon, and this is still an issue with todays version of Bagnon.

It seems to be a bug with the databroker display where the Previous-button (<) bugs out and loops between 2-3 items. But if you use the Next-button (>) it works as expected.

https://user-images.githubusercontent.com/696120/196042847-ce29e01b-c8a8-4ce0-b68d-bdb13db47149.mov

**Comment by Jaliborc** [comment]
This is fixed in the beta version. It was recent, likely  why you havent heard
