### ISSUE TITLE
Addon crash when level up

### ISSUE THREAD

**Issue by Naxterra** [tullamods/Bagnon#1178]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.3.5
 - Server patch: 8.3

 **Have you read the changelog? (please don't waste our time)**
 Mark

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

-Level up while in combat
-Addon gives error

**Error Logs**
Date: 2020-03-24 10:05:40
ID: 1
Error occured in: AddOn: Bagnon
Count: 1
Message: Note: AddOn Bagnon attempted to call a protected function (MainMenuBar:ClearAllPoints()) during combat lockdown.
Debug:
   [string "=[C]"]: ClearAllPoints()
   [string "@..\FrameXML\MainMenuBar.lua"]:43: SetPositionForStatusBars()
   [string "@..\FrameXML\MainMenuBar.lua"]:122:
      ..\FrameXML\MainMenuBar.lua:65
Locals:
None
AddOns:
  Swatter, v8.3.BETA-4-4 (NzothsFolly)
  ACP, v3.5.7 
  AngryAssignments, vv1.13.0c
  BadBoy, vv8.2.5
  BadBoyIgnore, vv8.2.0
  BagBrother, v
  Bagnon, v8.3.5
  Bartender4, v4.9.0
  CursorTrail, v8.3.0.2
  DBMArchaeology, v
  DBMCore, v8.3.18
  DBMCountPackHotS, v1.7.6
  DBMCountPackOverwatch, v1.4.10
  DBMDefaultSkin, v
  DBMInterrupts, v8.3.0
  DBMSoundEventsPack, v1.6.5
  DBMStatusBarTimers, v
  DBMVPVEM, v10.0.1
  FishingBuddy, v1.10.8.8
  GatherMate2, v1.45.5
  Grail, v108
  GrailNPCsretail, v27178
  GrailNPCsretailenUS, v27178
  GrailQuestsretail, v31478
  GrailQuestsretailenUS, v31478
  GTFO, v4.55
  HandyNotes, vv1.5.9
  HandyNotesArgus, vv0.15
  HandyNotesAzerothsTopTunes, vv1.2.2
  HandyNotesBattleForAzerothTreasures, v1
  HandyNotesBrokenShore, vv1.33
  HandyNotesDraenorTreasures, v1.21
  HandyNotesDungeonLocations, v1.50
  HandyNotesFieldPhotographer, v8.0.0.0
  HandyNotesHigherLearning, v8.0.0.0
  HandyNotesLegionTreasures, v1
  HandyNotesLongForgottenHippogryph, v1
  HandyNotesLunarFestival, vv1.6.2
  HandyNotesMechagonAndNazjatar, v13
  HandyNotesSuramarShalAranTelemancy, vv1.23
  HandyNotesTimelessIsleChests, v1.22
  HandyNotesUniversalExplorer, v8.3
  HandyNotesVisionsOfNZoth, v38
  HandyNotesWellRead, v8.0.0.0
  Hekili, vv8.3.0-04-16
  LeatrixPlus, v8.3.10
  MasterPlanA, vA
  MikScrollingBattleText, v5.7.150
  MoveAnything, v17.1.0
  NPCScan, v8.0.1.13
  Omen, v3.2.2
  OmniCC, v8.3.5
  Overachiever, v1.0.9
  OverachieverCache, v1.0.9
  OverachieverTabs, v1.0.9
  OverachieverTrade, v1.0.9
  Pawn, v2.3.24
  Postal, vv3.6.2
  Prat30, v3.7.50
  Prat30Libraries, v
  Quartz, v3.5.2
  QuestCompletist, v109.27
  RaidAchievement, v
  RaidAchievementOldModules, v
  RaiderIO, v8.1.0 (v202003240600)
  RaiderIODBEUA, v
  RaiderIODBEUAR, v
  RaiderIODBEUH, v
  RaiderIODBEUHR, v
  Recount, vv8.3.0c
  RSA, vr526-release
  RSAHunter, v
  SexyMap, vv8.3.0
  ShadowedUnitFrames, vv4.2.9
  TidyPlatesThreatPlates, v9.1.20
  Titan, v5.18.6.80300
  TitanBag, v5.18.6.80300
  TitanClock, v5.18.6.80300
  TitanGold, v5.18.6.80300
  TitanLocation, v5.18.6.80300
  TitanLootType, v5.18.6.80300
  TitanPerformance, v5.18.6.80300
  TitanRepair, v5.18.6.80300
  TitanVolume, v5.18.6.80300
  TitanXP, v5.18.6.80300
  Transcriptor, vv8.3.1
  WeakAuras, v2.16.6
  WorldQuestsList, v92
  BlizRuntimeLib_enUS v8.3.0.80300 <none>
  (ck=929)

**Comment by Pillgar** [comment]
Just noticed this also.

Message: [ADDON_ACTION_BLOCKED] AddOn 'Bagnon' tried to call the protected function 'MainMenuBar:ClearAllPoints()'.
Time: Fri Apr  3 09:44:14 2020
Count: 1
Stack: [ADDON_ACTION_BLOCKED] AddOn 'Bagnon' tried to call the protected function 'MainMenuBar:ClearAllPoints()'.

Locals: <none>
