### ISSUE TITLE
Bagnon currencies support for 8.3.0

### ISSUE THREAD

**Issue by AntonVasserman** [tullamods/Bagnon#1185]
**Is your feature request related to a problem? Please describe.**
Currently Bagnon Currencies doesn't work with game version 8.3.0.

**Describe the solution you'd like**
I would like it to be updated and work with it.

**Describe alternatives you've considered**
Maybe add currency support for Bagnon itself.

**Additional context**
No additional info.

**Comment by Spillmaker** [comment]
Bagnon Currencies author here: This is updated first to 9.0.1 in november last year and now to 9.0.5 so this ticket can be closed.

Also note that this is not the right place to file issues for "Bagnon Currencies" addon. You can use this one instead: https://github.com/Spillmaker/Bagnon_Currencies/issues
