### ISSUE TITLE
Bank Bag won't show bank contents

### ISSUE THREAD

**Issue by aeonabyss** [tullamods/Bagnon#1192]
**Running Software (issues missing this information will be deleted):**
 - Addon version:  Bagnon-8.3.5-1.13.3.zip
 - Server patch: 1.13.4 (34219)

 **Have you read the changelog? (please don't waste our time)**
Yes

**Describe the bug**
Bagnon will not load the items from my bank bag into its bank container panel.
I open bank with all my items in it, then I open the bagnon bank panel, and it just shows a single, empty bank bag.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to bank and open
2. open bank bag (shortcut key)

**Expected behaviour**
The bag panel opens with the contents of my bank.

**Screenshots**
https://i.imgur.com/u46756T.jpg

**Error Logs**
none

**Comment by Heras7** [comment]
Same issue here ....
Downloaded latest version on twitch. 

Go bank and shows bank and bag correctly.
Closed everything.
Open bag and open bank bag with shorcut key and shows empty bank like the photo showed by aeonabyss

**Comment by Iskias** [comment]
any ideas what breaked bank?
only 2 rows is showing and they are empty

**Comment by aeonabyss** [comment]
It seems the functionality of your bank bag has some code in the GUILD BAG / VOID STORAGE addon dependency.  Turn that on in your addons and your guild bank bags should work in Classic...

**Comment by Heras7** [comment]
Could you be more precise? provide some photos It would help me ...

**Comment by Heras7** [comment]
![image](https://user-images.githubusercontent.com/61690241/82469423-47609180-9ac4-11ea-9784-9ecd3f2ed919.png)
I have them turned on but still misssing the bank info.

![image](https://user-images.githubusercontent.com/61690241/82469566-78d95d00-9ac4-11ea-8c79-88889a067572.png)

**Comment by aeonabyss** [comment]
I turned mine on and it started working.
IDK what to say.

**Comment by Heras7** [comment]
No, I do not have this addon, and i cant find it on twitch

**Comment by aeonabyss** [comment]
Sorry, but I can't help any further...
You should post your own bug report as mine is resolved, but not fixed.

**Comment by Heras7** [comment]
Well ... I could fixed.

I dont know why I hadn't bag brother and seems it also have some dependencies.

What I did is remove the addon > disable all addon in the game -> install again bagnon (bagbrother shows) -> enable only bagnon.


That worked, then I just reenabled all others addons ....

**Comment by Iskias** [comment]
finally i figured how to get bank and alts inventory working again

no more 2 row when outside from bank

go to bank and open it, then press bank binded key, and now it save bank normally
