### ISSUE TITLE
WoW Classic Sorting Bug

### ISSUE THREAD

**Issue by PJai** [tullamods/Bagnon#1202]
**Running Software:**
 - Addon version: 8.3.6-1.13.5
 - Server patch: Build 1.13.5.35000

 **Have you read the changelog?**
Yes

**Describe the bug**
The new sorting goes in an infinit loop, when an item with not max stack is at position 1 to n-2 (where n is the number of bag slots used by the item). If the same item are spread across the bag the infinit loops start as soon as all are aligned.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Inventory
2. Put more then two stacks of an item in a line
3. Place the stack with not max quantity on position 1 to n-2 of the line
4. Press Bag sort

**Screenshots**
[https://i.imgur.com/ZxAVmA3.png](https://i.imgur.com/ZxAVmA3.png)
[https://i.imgur.com/ivgL8SW.png](https://i.imgur.com/ivgL8SW.png)

**Comment by PuaDoxx** [comment]
Similar for me.  Sorting the bags since update now puts in infinite loop.  Only way to stop is to logout.
