### ISSUE TITLE
After clean an item move doesn't refresh bag without closing bank

### ISSUE THREAD

**Issue by charlmu** [tullamods/Bagnon#1204]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 1.13.5
 - Server patch: [e.g. Build 8.0.1.27178]

 **Have you read the changelog? (please don't waste our time)**
 Mark if read.

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to bank and open inventory
2. Click on Clean Items
3. Moving any item causes it to be grayed out but doesn't appear at the destination.
4. Close bank
5. Open bank and the item actually did move

**Expected behaviour**
When moving an item from one bag slot to another it should move without closing the bank and reopening.

**Screenshots**

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the message with `ID: 1` (labelled 1/X). This is generally NOT the message that the window shows by default.

**Additional context**

**Comment by GrueFeathermoon** [comment]
same issue here. the bank window is not refreshing when items are placed into it. just updated this addon and the issue came with it.

**Comment by Magchow** [comment]
Having same issue as charlmu Please fix.
