### ISSUE TITLE
Bank doesn't automatically update

### ISSUE THREAD

**Issue by comiluv** [tullamods/Bagnon#1205]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.3.7-8.3.0
 - Server patch: [e.g. Build 8.0.1.27178]
Build 8.3.0.34963

 **Have you read the changelog? (please don't waste our time)**
 Mark if read.
Yes

**Describe the bug**
Putting an item in a bank doesn't automatically update itself

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a bank
2. Right click on any item in a backpack to move it to the bank
3. Item disappears but its actually moved from backpack to bank

**Expected behaviour**
The item does not disappear and shows on bank screen

**Screenshots**

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the message with `ID: 1` (labelled 1/X). This is generally NOT the message that the window shows by default.

**Additional context**
Reverting to 8.3.6 resolves issue

**Comment by comiluv** [comment]
This issue is not identical with but seems related to issue #1204

**Comment by Thargeon** [comment]
If it helps the devs, I recognized one more thing (got the same problem):

Items in the "normal"/first bag and in the material bank slot work fine. Looks like only "additional bank slots" are affected by this. Got some screenshots to see what the problem is. I'll add them in few mins
