### ISSUE TITLE
Is there a way to search for caged battlepets?

### ISSUE THREAD

**Issue by Nukme** [tullamods/Bagnon#1210]
I have this question for a very long time. Is there any way to search for caged battlepets in bags and banks?

I'm in retail wow and using zhCN client, naturally I use Chinese characters as searching keywords. It seems that every other things, including uncaged(unlearned) battlepets, respond well to search. I just don't know how to search for caged pets. They are always dark no matter what I put in search box, names, types, etc.

**Comment by CMcFadyen** [comment]
There isn't a way, and I'm not sure if this will ever be implemented, sadly.  Caged battle pets use a different tooltip, so they don't currently match any search at all.

**Comment by Jaliborc** [comment]
I don't think there is one at the moment, not sure. But you can definitively search the pet name and rarity at the very least, because I remember implementing that recently.

**Comment by CMcFadyen** [comment]
Is there something special you have to do to make that work?  Because searching pet names does not work for me:
https://i.imgur.com/WENVHog.png
https://i.imgur.com/rWk1njZ.png

**Comment by Jaliborc** [comment]
Ah.. I had a new version with that feature for 3 months now and forgot to upload it.
Genius!
