### ISSUE TITLE
Classic: AddOnSkins + Bagnon don't play nice together

### ISSUE THREAD

**Issue by APantelides** [tullamods/Bagnon#1216]
Steps to reproduce:
1. Install bagnon
2. Install AddOnSkins
3. Load both Addons
4. Open bags

Screenshot:
![WoWScrnShot_082620_221114](https://user-images.githubusercontent.com/12740164/91387252-ba775380-e7e9-11ea-98e9-6f100665dc01.jpg)

**Comment by Jaliborc** [comment]
If AddonSkins wants to "skin" Bagnon, it needs to specifically support it. Bagnon **needs** to modify the inventory interface to do anything, so if the other mod is trying to modify the defautl bags, its gonna conflict.
