### ISSUE TITLE
Unable to open bags with Bagnon

### ISSUE THREAD

**Issue by CoeXane** [tullamods/Bagnon#1219]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.3.8
 - Server patch: [Build 8.3.7.35662]

 **Have you read the changelog? (please don't waste our time)**
Yes, I've read it

**Describe the bug**
So basically earlier this week I found that my favorite bag addon wasn't working? I use B to open the bags as normally and there is simply no return.

**To Reproduce**
Steps to reproduce the behaviour:
1. Click "B"
2. No return

**Expected behaviour**
The addon working properly

**Screenshots**
There is simply no bags

**Error Logs**
Typing "/console scriptErrors 1" seems to do nothing either.

**Additional context**
Get it going.

**Comment by goldfox420** [comment]
Did you change your keybinding for the B key?

**Comment by CoeXane** [comment]
I didn't. If this is a memory issue though, you should rewrite the code to go directly to the input.

**Comment by CoeXane** [comment]
It's working now
