### ISSUE TITLE
You just broke the alt-bank checking function in 9.0.0 for classic wow

### ISSUE THREAD

**Issue by alphabitnz** [tullamods/Bagnon#1221]
You just broke the alt-bank checking function in 9.0.0 for classic wow:

5x ...\Wildpants\libs\Sushi-3.1-4\classes\drops\Dropdown.lua:136: Invalid data provided for `:SetBackdrop`
[C]: in function `assert'
...\Wildpants\libs\Sushi-3.1-4\classes\drops\Dropdown.lua:136: in function `SetBackdrop'
...\Wildpants\libs\Sushi-3.1-4\classes\drops\Dropdown.lua:48: in function `New'
...\Wildpants\libs\Sushi-3.1-4\classes\drops\Dropdown.lua:57: in function `Toggle'
...ns\Bagnon\common\Wildpants\classes\ownerSelector.lua:32: in function <...ns\Bagnon\common\Wildpants\classes\ownerSelector.lua:30>

Locals:
(*temporary) = false
(*temporary) = "Invalid data provided for `:SetBackdrop`"

**Comment by audiosmith** [comment]
Reverted to 8.3.8 and it works fine in the old version

**Comment by egorpugin** [comment]
+1

**Comment by Nopemalo** [comment]
I have the same issue, can't view bags from another character since last update (recently i guess last update)

BTW playing classic here.

**Comment by Jaliborc** [comment]
Looking at it. Very unexpected behaviour.

**Comment by Jaliborc** [comment]
Immediatelty figured out what it was. I'm an idiot.
