### ISSUE TITLE
Character Option in Bagnon not able to be opened (bfa)

### ISSUE THREAD

**Issue by friedwillie** [tullamods/Bagnon#1224]
**Running Software (issues missing this information will be deleted):**
 - Addon version:
 - Server patch: [e.g. Build 8.0.1.27178]

 **Have you read the changelog? (please don't waste our time)**
 Mark if read. Ok

**Describe the bug**
Can not open the "Character" option at all despite anything I do. Trying to remove old characters. Not sure the steps to reproduce as all I do I encounter this error of being unable to open and edit the char option.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**
Open char option

**Screenshots**

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the message with `ID: 1` (labelled 1/X). This is generally NOT the message that the window shows by default.

**Additional context**

**Comment by Nopemalo** [comment]
I have the same issue, can't view bags from another character since last update (recently i guess last update)

BTW playing classic here.
