### ISSUE TITLE
no longer able to vieuw bags from another characater

### ISSUE THREAD

**Issue by Moosses** [tullamods/Bagnon#1225]
no longer able to vieuw bags from another character.

getting following error message:

Date: 2020-09-23 18:13:14
ID: 2
Error occured in: Global
Count: 1
Message: ...\Wildpants\libs\Sushi-3.1\classes\drops\Dropdown.lua line 136:
   Invalid data provided for `:SetBackdrop`
Debug:
   [C]: ?
   [C]: assert()
   ...\Wildpants\libs\Sushi-3.1\classes\drops\Dropdown.lua:136: SetBackdrop()
   ...\Wildpants\libs\Sushi-3.1\classes\drops\Dropdown.lua:48: New()
   ...\Wildpants\libs\Sushi-3.1\classes\drops\Dropdown.lua:57: Toggle()
   ...ns\Bagnon\common\Wildpants\classes\ownerSelector.lua:32:
      ...ns\Bagnon\common\Wildpants\classes\ownerSelector.lua:30
Locals:

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AdvancedInterfaceOptions, v1.3.4
  AtlasLootClassic, vv1.5.6
  AtlasLootClassicData, vv1.5.6
  AtlasLootClassicDungeonsAndRaids, vv1.5.6
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v9.0.0
  Bartender4, v4.9.0
  BCT, v1.37
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  CharacterStatsClassic, v3.6.3
  ClassicCastbars, v1.3.12
  ClassicCastbarsOptions, v
  DBMCore, v1.13.60
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.7
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  Dismounter, v1.2.1
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  ExRT, v4160
  GTFO, v4.55
  GuildRosterManager, v1.895
  GuildTooltip, v2.13.15
  Informant, v8.2.6374 (SwimmingSeadragon)
  LibStub, v
  MikScrollingBattleText, v5.7.150
  NovaWorldBuffs, v1.79
  Prat30, v3.8.26
  Prat30Libraries, v
  Questie, v6.0.5
  SexyMap, vv5-classic
  ShadowedUnitFrames, vv4.2.3-Classic
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Spy, v1.1.1
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TitanClassic, v1.2.4.11305
  TitanClassicAmmo, v1.2.4.11305
  TitanClassicBag, v1.2.4.11305
  TitanClassicClock, v1.2.4.11305
  TitanClassicGold, v1.2.4.11305
  TitanClassicLocation, v1.2.4.11305
  TitanClassicLootType, v1.2.4.11305
  TitanClassicPerformance, v1.2.4.11305
  TitanClassicRegen, v1.2.4.11305
  TitanClassicRepair, v1.2.4.11305
  TitanClassicVolume, v1.2.4.11305
  TitanClassicXP, v1.2.4.11305
  WeakAuras, v2.18.4
  Yatabar, v
  BlizRuntimeLib_enUS v1.13.5.11305 <none>
  (ck=779)

Even with all addons off and only bagnon on i cant vieuw.
World of warcraft classic

**Comment by Nopemalo** [comment]
I have the same issue, can't view bags from another character

**Comment by Dirtnap71** [comment]
Same, can't see inventory of other toons, as well as when I mouse over an item to see stock of other toons.
