### ISSUE TITLE
Updated Bagnon For Shadowlands still says out of date

### ISSUE THREAD

**Issue by Titchuba** [tullamods/Bagnon#1230]
I'm sorry, I don't know how to do all that you asked to report the issue.  All that I know is that I have Bagnon installed by Twitch.  It said it was an update for Shadowlands 9.0 but after it was installed Blizzard would not let it load.  It just kept saying "Out of date"  and would not even let you try to load it.  Today is 10/08/20.

**Comment by amiyuy** [comment]
Blizzard changed up the TOC versions this time.

As of 9.0 we need to differentiate between 9.0.1 (Pre-patch) and 9.0.2 (Beta).  It's showing out of date because Bagnon has 9.0.0 which used to work.

**Comment by Qylack** [comment]
It stil shows as out of date. To fix please update the following in you TOC file

_Interface: 90002_ to the following _Interface: 90001_

This solves the isseu of the game not recognizing Bagnon as an up to date addon.

**Comment by kayvanbree** [comment]
> Interface: 90002 to the following Interface: 90001

Can confirm this works
