### ISSUE TITLE
Junk icon failure in 9.0?

### ISSUE THREAD

**Issue by Voxxel** [tullamods/Bagnon#1234]
When I set to show Junk in inventory the addon marks every single empty bag slot with the junk icon instead of marking the grey junk items.

**Comment by raysmith59** [comment]
Same thing here.

**Comment by Masumia** [comment]
Same issue here. See below.

![image](https://user-images.githubusercontent.com/42444089/95944659-536c2900-0dae-11eb-9978-1808224a9dec.png)

![image](https://user-images.githubusercontent.com/42444089/95944732-80b8d700-0dae-11eb-9b21-804ee7e39f0d.png)

**Comment by raysmith59** [comment]
Upside, it does make the empty slots even easier to see... now I kind of want to request a red X or something for empty slots going forward.  :)

**Comment by Voxxel** [comment]
> 
> 
> Upside, it does make the empty slots even easier to see... now I kind of want to request a red X or something for empty slots going forward. :)

You can simply disable the background graphic and set the background color to dark so your eyes wont be tricked by the background graphic of the slots. I use Bagnon without background and there's no way to confuse the empty slots with used ones.

**Comment by melinerunen** [comment]
Same at 9.0.1 
![image](https://user-images.githubusercontent.com/1240420/96058478-b5399b00-0e61-11eb-8a34-d9358127ea43.png)

**Comment by Jaliborc** [comment]
Pretty sure what is causing it. Fixed internally. Can't test right now cause keep getting disconnected on login.

**Comment by melinerunen** [comment]
Solved! you can close this now
