### ISSUE TITLE
9.0 Lua Error on mouse over

### ISSUE THREAD

**Issue by Masumia** [tullamods/Bagnon#1235]
Mousing over any item in the crafting window gives the following error below.

5x ...s\Bagnon\common\Wildpants\features\tooltipCounts.lua:151: Usage: GetRecipeReagentItemLink(recipeID, reagentIndex)
[string "=[C]"]: in function `GetRecipeReagentItemLink'
[string "@Bagnon\common\Wildpants\features\tooltipCounts.lua"]:151: in function <...s\Bagnon\common\Wildpants\features\tooltipCounts.lua:150>
[string "=[C]"]: in function `SetRecipeResultItem'
[string "@Blizzard_TradeSkillUI\Blizzard_TradeSkillDetails.lua"]:743: in function `OnResultMouseEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals:
(*temporary) = 330257
(*temporary) = <table> {
}

**Comment by Masumia** [comment]
Not sure if this is the intended fix, but it seems to be working for me. See below.

\Wildpants\features\tooltipCounts.lua

line 150: local function OnTradeSkill(tooltip, recipeId, reagentIndex)
line 152: AddOwners(tooltip, reagent and C_TradeSkillUI.GetRecipeReagentItemLink(recipeId, reagentIndex) or C_TradeSkillUI.GetRecipeItemLink(recipeId))

**Comment by gaveer** [comment]
I approve this 💯
