### ISSUE TITLE
LUA Error When depositing Anima in Covenant Halls

### ISSUE THREAD

**Issue by Buugar** [tullamods/Bagnon#1249]
**Running Software (issues missing this information will be deleted):**
 - Addon version: Bagnon-9.0.4-1.13.5
 - Server patch: Shadowlands 9.0.2 (36753)

 **Have you read the changelog? (please don't waste our time)**
 Mark if read. 
Yes,

**Describe the bug**
Every time you deposit Anima into your covenant's sanctum, a Lua Error appears. Ive tested this with all my other addons and Bagnon seems to be the culprit.

**To Reproduce**
1. Collect an Anima item in your inventory,
2. Go to your covanent hall and deposit the Anima.
3. Error appears.

**Expected behaviour**
when it works properly, the orb in the new Anima Ui is supposed flash signaling your despoit.

**Screenshots**
![WoWScrnShot_112520_211640](https://user-images.githubusercontent.com/59521243/101279405-ea35e000-3776-11eb-88ca-f14fe1d1e0c7.jpg)

**Error Logs**
Message: Interface\FrameXML\LevelUpDisplay.lua:1497: Usage: GameTooltip:SetHyperlink(link)
Time: Fri Dec  4 23:36:47 2020
Count: 1
Stack: Interface\FrameXML\LevelUpDisplay.lua:1497: Usage: GameTooltip:SetHyperlink(link)
[string "=[C]"]: in function `SetHyperlink'
[string "@Interface\FrameXML\LevelUpDisplay.lua"]:1497: in function <Interface\FrameXML\LevelUpDisplay.lua:1493>

Locals: (*temporary) = GameTooltip {
 0 = <userdata>
 SetText = <function> defined =[C]:-1
 OnBackdropLoaded = <function> defined @Interface\SharedXML\Backdrop.lua:195
 textLeft1Font = "GameTooltipHeaderText"
 shoppingTooltips = <table> {
 }
 ItemTooltip = <unnamed> {
 }
 SetCurrencyToken = <function> defined @Interface\AddOns\Altoholic\Tooltip.lua:725
 SetUnit = <function> defined =[C]:-1
 hasMoney = 1
 TopLeftCorner = <unnamed> {
 }
 RightEdge = <unnamed> {
 }
 comparing = false
 SetFrameLevel = <function> defined =[C]:-1
 TextRight1 = GameTooltipTextRight1 {
 }
 BottomLeftCorner = <unnamed> {
 }
 BottomEdge = <unnamed> {
 }
 SetBackdrop = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\tooltip.lua:2538
 ClearBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:325
 TopOverlay = <unnamed> {
 }
 SetParent = <function> defined =[C]:-1
 GetBackdrop = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\tooltip.lua:2539
 GetBackdropColor = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\tooltip.lua:2540
 SetBackdropBorderColor = <function> defined @Interface\SharedXML\Backdrop.lua:465
 TopRightCorner = <unnamed> {
 }
 AddDoubleLine = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 SetBorderBlendMode = <function> defined @Interface\SharedXML\Backdrop.lua:309
 numMoneyFrames = 1
 __tamedCounts = false
 textRight2Font = "GameTooltipText"
 SetRecipeReagentItem = <function> defined =[C]:-1
 BottomRightCorner = <unnamed> {
 }
 TextLeft1 = GameTooltipTextLeft1 {
 }
 AddLine = <function> defined =[C]:-1
 ApplyBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:337
 Center = <unnamed> {
 }
 OnBackdropSizeChanged = <function> defined @Interface\SharedXML\Backdrop.lua:225
 HasBackdropInfo = <function> defined @Interface\SharedXML\Backdrop.lua:321
 GetBackdropBorderColor = <function> defined @Interface\AddOns\AzeriteUI\back-end\libraries\tooltip.lua:2541
 SetFrameStrata = <function> defined =[C]:-1
 textRight1Font = "GameTooltipHeaderText"
 SetQuestLogItem = <function> defined =[C]:-1
 GetEdgeSize = <function> defined @Interface\SharedXML\Backdrop.lua:231
 updateTooltip = 0.033000
 textLeft2Font = "GameTooltipText"
 TopEdge = <unnamed> {
 }
 TextRight2 = GameTooltipTextRight2 {
 }
 TextLeft2 = GameTooltipTextLeft2 {
 }
 SetupTextureCoordinates = <function> defined @Interface\SharedXML\Backdrop.lua:257
 BottomOverlay = <unnamed> {
 }
 needsReset = true
 SetupPieceVisuals = <function> defined @Interface\SharedXML\Backdrop.lua:289
 SetBackdropColor = <function> defined @Interface\SharedXML\Backdrop.lua:442
 LeftEdge = <unnamed> {
 }
 SetRecipeResultItem = <function> defined @Interface\AddOns\Altoholic\Tooltip.lua:725
}
(*temporary) = nil

**Additional context**
not game breaking in any way, just annoying to pop up every time.

**Comment by Jaliborc** [comment]
Error in Altoholic
