### ISSUE TITLE
Items not appearing and missing from Bag

### ISSUE THREAD

**Issue by GrimGul** [tullamods/Bagnon#1254]
Latest version of Bagnon, new items do not appear in bag. 
Bagnon-9.0.4-9.0.1.zip
WOW Shadowlands
windows 10
Directx 12

**Comment by Jaliborc** [comment]
toggle all bags on

**Comment by GrimGul** [comment]
All bags were toggled on. Did it multiple times. When disablining the Addon then the items appear. Its bugged.
