### ISSUE TITLE
Currencies showing as text instead of icons

### ISSUE THREAD

**Issue by marcuswohlmuth** [tullamods/Bagnon#1283]
I think the screenshot says it all:
![grafik](https://user-images.githubusercontent.com/965113/119232651-45da0700-bb26-11eb-86bd-0dfadded8a5e.png)

am I missing something in the configs or is this a bug?

**Comment by Jaliborc** [comment]
You enabled colorblind mode somewhere in the game my dude.

**Comment by marcuswohlmuth** [comment]
Thanks so much! Is that something that might get changed in the future? I mean the colors of the gold, silver and copper icons are not really that hard to distinguish if you are only partly colorblind and not completely. Or could you also link it to the different colorblindness options?
Anyway, thank you!
