### ISSUE TITLE
BCC Sorting bug - Ammo gets sorted out of ammo bag.

### ISSUE THREAD

**Issue by ERFmama** [tullamods/Bagnon#1305]
**Running Software (issues missing this information will be deleted):**
 - Addon version: Bagnon-9.1.0
 - Server patch: 2.5.1

 **Have you read the changelog? (please don't waste our time)**
 Yes. 

**Describe the bug**
When clicking the sorting button - it's sorting my ammo out of the ammo bag.
I've tried to look in the options but can't find a reason for this or anything to disable. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'your bag'
2. Click on 'bag sorting button'
3. Ammo is sorted into bag and out of Ammo bag. 

**Expected behaviour**
'Ammo' to be sorted and still be inside the designated Ammo Bag where they were already in. 

**Screenshots**
Before sorting, ammo is in ammo bag:
![image](https://user-images.githubusercontent.com/24800030/130271515-8e04856d-08e7-4c9b-b9c5-89e3f4b82622.png)

After sorting, ammo has left the ammo bag during sorting: 
![image](https://user-images.githubusercontent.com/24800030/130271594-18785fd4-a27f-4407-8b94-2c2beed0a51a.png)

**Error Logs**
Bagnon is not showing any ingame error.

**Additional context**

**Comment by kw12xx** [comment]
I'm having the exact same issue and wanted to add to this report. In my case it's specifically the ammo: Warden's Arrow. All other arrows appear to sort normally.

**Comment by Jaliborc** [comment]
Fixed!
