### ISSUE TITLE
Baggon cannot sort Primals into enchanting bags

### ISSUE THREAD

**Issue by capmurrika** [tullamods/Bagnon#1309]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 9.1.0
 - Server patch: Version 2.5.2.40011

 **Have you read the changelog? (please don't waste our time)**
 Yes

**Describe the bug**
The bug occurs when I attempt to sort my items with an enchanting bag equipped in my bank. Apparently, motes and primals can now go in enchanting bags. When I attempt to sort, the process starts correctly and then errors out repeatedly with the message "That item doesn't go in that container." I then cannot move any items until I relog.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'banker', and open your bank.
2. Click on 'Click to clean items.'
3. See error

**Expected behaviour**
I expected my primals and motes to be properly sorted into my enchanting bag.

**Screenshots**
(https://user-images.githubusercontent.com/90012332/131930956-e64a01b5-ab0b-4c7c-8d30-84442de1273d.JPG)

**Error Logs**
will not display

**Additional context**
When I close the bank and reopen the issue still persists. I have to reload UI to get it to stop.

**Comment by ShortStuffz35** [comment]
Likewise, I am having the same issue since the new patch :( thank you for reporting it, hopefully it will get sorted soon >< it's become more of a habit for me to clean bags and it's costing me a relog everytime

**Comment by massibronto** [comment]
Hi, same issue here. I am trying to sort my bank. The sort is never completing because of items getting stuck in the engineering bag. FPS drops to 10.
Also, could you prioritize Primals getting packed into the engineering (or specific profession) bag?

**Comment by FurkanKarakas** [comment]
Is there any progress on this yet? I tried to understand the code base but I'm not very familiar with Lua. Otherwise I could have probably created a pull request.

**Comment by Jaliborc** [comment]
Fixed. The issue was I'm not playing TBC and didn't have a character where I could test the issue on.
Then I realized there is a TBC PTR, and a vendor in Terokkar with bags from different professions.
