### ISSUE TITLE
TBC - clean items infinite loop after latest update

### ISSUE THREAD

**Issue by WolfxUdK** [tullamods/Bagnon#1314]
**Running Software (issues missing this information will be deleted):**
 - Addon version: latest tbc
 - Server patch: [e.g. Build 8.0.1.27178] tbc server no recent updates i think

 **Have you read the changelog? (please don't waste our time)**
 Mark if read. yes read but was unintentional

**Describe the bug**
i press clean items and it starts infinite loop throwing items all over the place

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '...' open bag
2. Click on '....' click clean up bag
3. Scroll down to '....' items start infinite loop reshuffle

**Expected behaviour**
A clear and concise description of what you expected to happen. expected behaviour is items sorted and i can use bags normally

**Screenshots**
If applicable, add screenshots to help explain your problem. its just items flying back and forth and greyed out for sec

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the message with `ID: 1` (labelled 1/X). This is generally NOT the message that the window shows by default. no errors

**Additional context**
Add any other context about the problem here. didnt see other ticket on github. ty for support well played!

**Comment by LokarBOA** [comment]
Getting this as well. When I try to sort my bags I get "That item doesn't go in that container." message spam and I have to reload to break the loop.  I tried moving various items out of my bags but wasn't able to isolate any specific item that was causing it.  There are no hard error messages.
