### ISSUE TITLE
Clean items infinite loop

### ISSUE THREAD

**Issue by Jokaleth** [tullamods/Bagnon#1315]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 9.1.1-2.5.1
 - Server patch: 2.5.2

 **Have you read the changelog? (please don't waste our time)**
 Yes

**Describe the bug**
Item sorting using the clean items button gets stuck in an infinite loop causing lag.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open bags
2. Click clean items button
3. Infinite loop

**Expected behaviour**
Items are sorted quickly in the bags.

**Screenshots**
https://user-images.githubusercontent.com/87456827/134192835-5acd8a6f-2860-4b53-bda4-e5e7f155d4ee.mp4

**Additional context**
I know multiple other people have also reported this issue but I didn't see any of them mentioning that this bug is only happening to profession-specific items such as Skinning Knife, Leather, etc. Whatever was updated in the 9.1.1 version, "TBC: Fixed profession items sorting issue." actually had the opposite effect,

**Comment by Jaliborc** [comment]
It's a bit hard to tell which item is causing that loop, but my guess its the leather. Could you try putting the leather in the bank and see if it persists?
To double check, this is TBC server, correct?

**Comment by Jaliborc** [comment]
You also do not appear to be using any leatherwoking bag. Is that an ammo pouch and a keyring, besides the normal bags?

**Comment by c0mm0n** [comment]
> You also do not appear to be using any leatherwoking bag. Is that an ammo pouch and a keyring, besides the normal bags?

I'm having same issue and skinning knife seems to be the culprit

**Comment by c0mm0n** [comment]
Removed skinning knife => same
Removed drums => same
Remove a few motes => Fixed

So seems the issue could be related to anything that could fit in a profession bag.

I have 0 profession bag, just normal ones

**Comment by Jaliborc** [comment]
Tested with skinning knife and ammo bags. No issue. Can't replicate.

**Comment by TrygveUrdahl** [comment]
Same issue when I try to auto-sort my bags after updating to 9.1.1 on TBC. I believe the motes are causing it, as it looks like they are highlighted when the loop gets stuck. See screenshot for an overview of the items I have in my bag. 
![image](https://user-images.githubusercontent.com/38653456/134229091-e20a411c-6e65-4ae3-a6cb-80e4f581c1a3.png)

**Comment by Jokaleth** [comment]
> You also do not appear to be using any leatherwoking bag. Is that an ammo pouch and a keyring, besides the normal bags?

**Comment by Jokaleth** [comment]
> It's a bit hard to tell which item is causing that loop, but my guess its the leather. Could you try putting the leather in the bank and see if it persists?
> To double check, this is TBC server, correct?

Hi, sorry for delayed response, been out of the house. Unfortunately won't be back for a few more hours so I can't do any more testing.
Yes this is TBC server.
I have 3 normal bags and 1 Gun Ammo bag.
The problem only happens with the profession items, in the video I sent that would be: the Skinning Knife, Leathers/Scales, Patterns, Heavy Armor Kit, and, oddly, Silk Cloth. When I took all profession items out of my inventory before this problem did not happen and it sorted the remaining items with no problem.

**Comment by Veramoz** [comment]
I have been having the exact same issue after updating bagnon this morning. As a hunter on TBC the thing that has been causing it for me is arrows in my quiver.

**Comment by Jokaleth** [comment]
> I have been having the exact same issue after updating bagnon this morning. As a hunter on TBC the thing that has been causing it for me is arrows in my quiver.

That's interesting because I haven't had any problems with the Bullet ammo.

**Comment by theclool** [comment]
I have been having the exact same issue after updating bagnon

**Comment by massibronto** [comment]
I have the same issue with the loop, it hangs on "Runic Spell Thread"
Error message: This item cannot fit into the container.

**Comment by ThrilledPriest** [comment]
I am having the same infinite loop I highlighted the objects that are looping:

![BagLoop](https://user-images.githubusercontent.com/91158912/134242385-3dda3b5e-2938-4cf3-aa36-4ebdc9e2e165.png)

**Comment by PJai** [comment]
Same issue. Also hightlighted the item which is in the sorting loop
![grafik](https://user-images.githubusercontent.com/22389964/134309644-0d774ebc-bbd9-4e2f-9e01-d6a10dda31b1.png)

**Comment by cdubya32** [comment]
Having the same issue with 9.1.2 with no profession bags equipped.

For me it's only when I have any Motes/Primals/Primal Nether in my bags.

But sorting in the bank works fine even with Motes/Primals/Primal Nether present.
![image](https://user-images.githubusercontent.com/91222601/134413897-672bb3f4-cfb8-4a6d-b32a-2963a95f1884.png)

**Comment by denellum** [comment]
![image](https://user-images.githubusercontent.com/10350712/134427215-80ff5cc2-5f42-4248-963f-b7e43e5802cf.png)
For me its looping the motes of fire and earth.

**Comment by disguy2k** [comment]
This is still happening for me. No special bags. Skinning knife, mote of mana, and knothide leather were all items it got stuck on (same as the previous patch)

**Comment by savinedg** [comment]
#1320

**Comment by Feronas** [comment]
Updated Bagnon to 9.1.2-2.5.1 and the same issue is still happening.
![2021-09-23](https://user-images.githubusercontent.com/65334149/134463720-32abbb7d-238a-43d0-a12e-36fefd91112d.png)

**Comment by ajames27** [comment]
It seems like this is an issue related to [this](https://github.com/tullamods/Wildpants/commit/1d1f8d54e6123a55307cb611139d27b342d066ad#diff-7fb9d196a5cc0ff9ca2e4030accf44f74909a0ebeb0b31507bce5126e368a27c) commit in the Wildpants library. Reverting the change fixes the bug.

**Comment by tra8cer** [comment]
> It seems like this is an issue related to [this](https://github.com/tullamods/Wildpants/commit/1d1f8d54e6123a55307cb611139d27b342d066ad#diff-7fb9d196a5cc0ff9ca2e4030accf44f74909a0ebeb0b31507bce5126e368a27c) commit in the Wildpants library. Reverting the change fixes the bug.

Can confirm this fixed issue for me.

**Comment by cdubya32** [comment]
> 
> Can confirm this fixed issue for me.

It does fix the looping issue with sorting, but it prevents the items from going in the profession bags which was the intent of the change. It's nice to have a workaround while it's addressed.

**Comment by c0mm0n** [comment]
Still here for me with 9.1.2

<img width="446" alt="image" src="https://user-images.githubusercontent.com/1181493/134592637-fec2d10c-ffa6-49ef-8d14-7cdc5a8ed24f.png">

**Comment by GiumaSoft** [comment]
https://github.com/tullamods/Bagnon/issues/1323#issuecomment-926070755

**Comment by danno0331** [comment]
> > Can confirm this fixed issue for me.
> 
> It does fix the looping issue with sorting, but it prevents the items from going in the profession bags which was the intent of the change. It's nice to have a workaround while it's addressed.

So I think this is the root of the issue.  When returning Sort:FitsIn I believe the addon needs to use ContainerIDToInventoryID(1) through ContainerIDToInventoryID(4) to make sure that one of the bags is actually equipped.  The sort feature appears to be stuck in a loop of moving the items into a container that is not equipped.

**Comment by Mattaruu95** [comment]
I was able to fix the issue by downloading a previous version of bagnon and replacing the files. Specifically version 9.1.0  https://www.curseforge.com/wow/addons/bagnon/download/3371569
You can find the file location for your addons by clicking the options button 
![image](https://user-images.githubusercontent.com/91383109/134776981-2f6ca334-3e73-47dc-a88d-86d384d598c0.png)
The file path should be something like E:\World of Warcraft\_classic_\Interface\AddOns
So download 9.1.0 then extract to the addons folder and replace all bagnon files. Sort works great again.

**Comment by Blackwidow-sudo** [comment]
Same problem for me🤔

**Comment by Feronas** [comment]
@Jaliborc could you kindly push the Bagnon update 2 versions back which doesn't have the sort feature bug until this is resolved? I(we)'ve been unable to sort our bag properly since then and rely on the addon. Hope I am not asking for too much. Thank you

**Comment by nabernstein** [comment]
@Jaliborc From what I've been able to determine, it seems that it's trying to swap anything where the 4th itemFamily bit (eligible for the Leatherworking bag) is 1 with something in the keyring. Primals/Motes/Essences are a niche case since they can go into so many different profession bags and it's not consistent between the different types. E.G. Primal Life can go in Leatherworking, Herbalism, and Enchanting bags while Primal Fire can go in Leatherworking, Enchanting, Engineering, and Mining bags.

I'm pretty sure that this is because bit.band(8, -2) returns 8 since -2 in binary is 0x1110 (2s compliment) and -2 is the bagID for the keyring. As a result, FitsIn() passes.

TBC-Classic
Bagnon-9.1.2-2.5.1
All normal bags

I used this macro in-game and the common problem items all had the 4th bit as 1 when converted to binary.
`/run for b =0,5 do for s=1,GetContainerNumSlots(b) do local id = GetContainerItemID(b, s); if id ~= nil then n = {GetItemInfo(id)}; print(n[1] .. " " .. n[6] .. " " .. n[7] .. " " .. GetItemFamily(id)); end end end `

This can probably be confirmed if everyone tests it with this macro and removes anything that pops up. If the issues persist but this macro doesn't print anything, something else is the cause.
`/run for b =0,5 do for s=1,GetContainerNumSlots(b) do local id = GetContainerItemID(b, s); if id ~= nil then local f = GetItemFamily(id); if bit.band(8,f) > 0 then local n, _ = GetItemInfo(id); if n ~= nil then print(n) end end end end end`

**Comment by i93sme** [comment]
Ok, if we know keyring bag has 9 as family and no other ever type of bag has 9, let's make this a special case.

I already see we have:

(family == 9 and GetItemFamily(id) == 256) or

which I presume tests for keys.

If that is the case, then family 9 should be forcibly excluded from the part that uses bit.band preventing items that might have that bit set to 'jump' in a keyring bag.

**Comment by nabernstein** [comment]
> If that is the case, then family 9 should be forcibly excluded from the part that uses bit.band preventing items that might have that bit set to 'jump' in a keyring bag.

Since 9 represents the bits that is on for keys, which gets the 256 dec value, I think there are two better options here, both include removing `(family == 9 and GetItemFamily(id) == 256)` from sorting.lua::FitsIn()

- Go through and change the container.family value to be GetItemFamily(<itemID of bag equipped>) and check `bit.band(GetItemFamily(id), family)`
- Change the bit.band() call to `(bit.band(GetItemFamily(id), 2^(family-1)) > 0`

The second one stops the loop for me with Primals, Motes, Light Feathers, and Leather in my bags, but I don't have any profession bags or quivers. Also, another condition in FitsIn() will have to be added for when family == -3 for the Retail Reagent bank.

**Comment by sunaiwa** [comment]
Been having this infinite loop issue since the latest update. Specifically it's with the arrows in my quiver (i'm a hunter). The Warden's Arrows and Adamantite Stingers flash infinitely until i reload.

**Comment by Mara4867** [comment]
I am still having problems with this add on. Please fix.

**Comment by joemckeithen** [comment]
I know the following items definitely cause this for me:  Drums of Battle (with some used charges), light feathers, and skinning knife (similar to other people's reports). For me, Bagnon updates are managed via the Curseforge app and Bagnon is at version 9.1.2-2.5.1.zip.  My bags are the Onyxia Hide Backpack and 3 Imbued Netherweave Bags.
