### ISSUE TITLE
That Item doesn't go in that container. - AGAIN WTF

### ISSUE THREAD

**Issue by Morons** [tullamods/Bagnon#1317]
- Addon version: 9.1.1
![image](https://user-images.githubusercontent.com/22202038/134326064-ae441540-1138-4a54-bceb-75f646e81254.png)
 - Server patch: BCC Version 2.5.2.40260

**Describe the bug**
That Item doesn't go in that container.
And looping with a audiable click on each loop

Simply sort the bags!, It seem only to happen when a Crafting bag is Attached!

![image](https://user-images.githubusercontent.com/22202038/134326648-14c67680-1ff0-42ba-ae8d-269cbd6295ad.png)

**Comment by steven-vonhaus** [comment]
I have exactly the same issue and I don't have a crafting bag

It is like it is not able to sort my primal fire

![WoWScrnShot_092221_122959](https://user-images.githubusercontent.com/22918256/134328325-af839abe-0963-48ba-9fe5-66e39e35c83c.jpg)

**Comment by HakaruShokku** [comment]
This also similarly happens with arrows in a quiver, unable to clean sort my bags for the time being with the newest update. This only started occurring after this latest update, but it was similarly happening in my bank bags with motes or primals in my engineering bag in the previous patch, so what gives here? Why did this break even more?

![bug](https://user-images.githubusercontent.com/32339810/134356490-273416e0-1624-4f92-a2d8-4e0441e1a917.PNG)
.

**Comment by zagzag777** [comment]
Same thing happening on my druid, no crafting bag, doesnt seem to be the keys being the issue either. Reverting back to earlier version fixed the problem. Fwiw, Mote of Fire and Mote of Life seemed to be the items that it got stuck on.

**Comment by skburgart** [comment]
It gets stuck for me on [Light Feather]. Removing it from my bag fixed the issue.

**Comment by jazminite** [comment]
It's the keychain. Just exclude keychain from sort bags feature.

**Comment by Morons** [comment]
NOT fixed!! Made New Issue!
