### ISSUE TITLE
Item Doesn't go into that Container but with no special bags

### ISSUE THREAD

**Issue by CyberNoob94** [tullamods/Bagnon#1319]
I have my backpack and 4 Imbued Netherweave Bags, but there's still a problem with the motes and primals even in 9.1.2
https://gyazo.com/0f7525680d6063bcc48847ba4446cf59

**Comment by Mattaruu95** [comment]
I was able to fix the issue by downloading a previous version of bagnon and replacing the files. Specifically version 9.1.0  https://www.curseforge.com/wow/addons/bagnon/download/3371569
You can find the file location for your addons by clicking the options button 
![image](https://user-images.githubusercontent.com/91383109/134776981-2f6ca334-3e73-47dc-a88d-86d384d598c0.png)
The file path should be something like E:\World of Warcraft\_classic_\Interface\AddOns
So download 9.1.0 then extract to the addons folder and replace all bagnon files. Sort works great again.
