### ISSUE TITLE
Item Doesn't go into that Container

### ISSUE THREAD

**Issue by computerkiller87** [tullamods/Bagnon#1320]
It keep glitching out with the skinning knife and Thick hide Items once I move these to my bank it can sort no issue. I'm on release Bagnon-9.1.2-2.5.1.zip

**Comment by savinedg** [comment]
I have the same issue with Finkle's Skinner, also on 9.1.2 Burning Crusade Classic.

**Comment by OldFart-real** [comment]
Ditto.
9/22  9:53 server time. Freezes on Lessor Astral Essence. 
![bagnon bug](https://user-images.githubusercontent.com/91233494/134444224-caa741d2-2712-4743-ae90-7adb2ced52ee.png)
