### ISSUE TITLE
That Item doesn't go in that container. Not Fixed! in 9.1.2

### ISSUE THREAD

**Issue by Morons** [tullamods/Bagnon#1321]
The problem Still exist on 9.1.2
![image](https://user-images.githubusercontent.com/22202038/134460823-367663cd-2d79-4bc7-945e-20a46aade21c.png)
Someone sugested the Keychain Causing it!
As you can see I have no crafting bags!

**Comment by Feronas** [comment]
The same is still happening for me.
![WoWScrnShot_092321_082951](https://user-images.githubusercontent.com/65334149/134463316-731bd7eb-8272-467f-9f28-7c69b6564752.jpg)

**Comment by Morons** [comment]
It seem to hapen with the Hearthstone - I noticed the space after it and on other toons it sorts below with spaces behind etc!

**Comment by guillaumeramey** [comment]
My bank alt doesn't have hearthstone and the issue is there.

**Comment by viresteelas** [comment]
i wish i could help people figure it out, i've tried many different approaches to trying to nail the issue, but in the end it's just bugged. on the same account i have two characters. 1 works with the sort no problem, hearthstone, no hearthstone, keys, no keys, mats, no mats, doesn't matter. works every time. the other, the exact opposite. i brought it to a point where i literally took out everything but a mana potion and a health potion....and it errored repeatedly. please figure this out. the "sort" function is one of my favorite things

**Comment by skburgart** [comment]
For me, it still happens if I have [Light Feather] in my inventory.

**Comment by sofar** [comment]
Knothide leather scraps as well. Please implement a max sorting swap limit or something like it. The game should never be hindered this much.

**Comment by Mattaruu95** [comment]
I was able to fix the issue by downloading a previous version of bagnon and replacing the files. Specifically version 9.1.0  https://www.curseforge.com/wow/addons/bagnon/download/3371569
You can find the file location for your addons by clicking the options button 
![image](https://user-images.githubusercontent.com/91383109/134776981-2f6ca334-3e73-47dc-a88d-86d384d598c0.png)
The file path should be something like E:\World of Warcraft\_classic_\Interface\AddOns
So download 9.1.0 then extract to the addons folder and replace all bagnon files. Sort works great again.

**Comment by sofar** [comment]
Confirmed. Downgrading to 9.1.0-2.5.1 fixes the issue. Regression.

**Comment by Morons** [comment]
If you are close to the bank and sort it - sometime it stops the loop

**Comment by sofar** [comment]
Hey, I totally understand the frustration with having 20+ dupes, but can you please leave a link to the actual issue? I spent 10 minutes trying to find the non-dupe on my mobile phone, and I still can't find it.  Went through 10+ threads on mobile.
