### ISSUE TITLE
That Item doesn't go in that container. Don't close an issue if it still exists. Validate that it is solved. 

### ISSUE THREAD

**Issue by dorton5963** [tullamods/Bagnon#1325]
**Running Software (issues missing this information will be deleted):**
 - Addon version:
 - Server patch: [e.g. Build 8.0.1.27178]
 - https://www.curseforge.com/wow/addons/bagnon
 - Verision 9.1.2-2.5.1

 **Have you read the changelog? (please don't waste our time)**
 Mark if read.

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**
![image](https://user-images.githubusercontent.com/28635534/134980450-53d6d323-7475-4008-a289-0fa36c879bd8.png)

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the message with `ID: 1` (labelled 1/X). This is generally NOT the message that the window shows by default.

**Additional context**

**Comment by Feronas** [comment]
@dorton5963 Mine was also closed for no reason for the very same issue. Despite being the first to report it as well. It should be at least marked as duplicate if I am not mistaken @Jaliborc ?

**Comment by tbonfim** [comment]
Facing the same problem

**Comment by r3ality1** [comment]
For me it was specific to certain items.  Mainly Mote of Life and Mote of Water.  If I didn't have those in my inventory the bag sort worked fine.

**Comment by Outcoldx** [comment]
mine still is not working when trying to sort my arrows/quiver bag

**Comment by Tronadin** [comment]
Also had this problem, ended up uninstalling and reinstalling the 9.1 version of the addon until a fix is found.
