### ISSUE TITLE
that item doesn't go in that container

### ISSUE THREAD

**Issue by Outcoldx** [tullamods/Bagnon#1326]
constant cycle repeating that for the past week. cannot sort my bags period.

**Comment by Necrotic416** [comment]
for me in the  Light Feathers and either of the Motes or Primal, when I put them in my bag then it will sort

**Comment by Senobiot** [comment]
The same problem. It's appeared yestarday after updating. Random cycle after press 'sort' with notification related 'that item doesn't go in that container'.

**Comment by Rhoxio** [comment]
Noticing the same issue with Rune Thread as well. 

Hitting the sort button then doing a `/reload` stops the infinite loop, by the way. Something about it trying to place non-key items in the keyring slot I'm guessing?

**Comment by SergioT87** [comment]
SOLVED
This addon sort bags correctly
**tdPack2**

**Comment by Selhel96** [comment]
I have the same problem since one or maybe two weeks with the new Arrows. what can i do? its only with the adamantide arrows rest is fine

**Comment by jourada** [comment]
After the new update, it's better, but still has issues with leather in general bags

**Comment by Eereinith1174** [comment]
Specifically having issues with Drums, light feathers, motes and primal elements, all which hang up in the general bag.  Seems the Bank issues are ok but General Bags not so much.  Thank you for developing this addon I have used it for years and enjoy it tremendously however this issue is pretty annoying.

**Comment by redligg** [comment]
I sent a PR to fix this issue. Just need the author to approve. You can see the change here and apply it manually yourselves in the mean time:
https://github.com/tullamods/Wildpants/pull/70/commits/976b565eeaae3f3efe8b5a455a3f1335e9cc34db

**Comment by rebecca10251** [comment]
Does anyone have any idea when this bug will be fixed?
Thank you, R

**Comment by redligg** [comment]
fix is already pending author approval. Just waiting on them
