### ISSUE TITLE
bagnon iteam does not go in container

### ISSUE THREAD

**Issue by rickit29** [tullamods/Bagnon#1329]
**Running Software (issues missing this information will be deleted):**
 - Addon version:
 - Server patch: [e.g. Build 8.0.1.27178]

 **Have you read the changelog? (please don't waste our time)**
 Mark if read.

**Describe the bug**
try to use sort and it says this item does not go in container doing it with all leather e.g light medium and heavy 
**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**
to sort out bag
![WoWScrnShot_100421_104844](https://user-images.githubusercontent.com/91880057/135830665-4ee92ae0-cc77-4571-a269-fb070538d25d.jpg)

**Screenshots**

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the message with `ID: 1` (labelled 1/X). This is generally NOT the message that the window shows by default.

**Additional context**

**Comment by GunPilot17** [comment]
Is this going to get fixed? Been going on too long now....coming up real fast on just uninstalling as it is way more trouble than it's worth.
