### ISSUE TITLE
Incorrect interface number for classic_era toc

### ISSUE THREAD

**Issue by MyTechnoHunter** [tullamods/Bagnon#1331]
**Running Software (issues missing this information will be deleted):**
 - Addon version: latest
 - Server patch: latest

 **Have you read the changelog? (please don't waste our time)**
yes

**Describe the bug**
interface version still shows as 11307 instead of 11400 in all related bagnon .toc files

**Expected behaviour**
in an update dated 2 hours ago (10/4/2021) the toc interface should reflect the current version of the game

**Comment by Jaliborc** [comment]
Ty, hadn't realized the toc numbers changed.
