### ISSUE TITLE
Bug w/ new ZA patch

### ISSUE THREAD

**Issue by KummerTK** [tullamods/Bagnon#1369]
![image](https://user-images.githubusercontent.com/102186937/159569371-fa1377e2-f006-4610-9d88-8daa5965347e.png)

Lua Error upon login. Bag slots showing up blank with yellow exclamation point.

**Comment by KummerTK** [comment]
![image](https://user-images.githubusercontent.com/102186937/159569536-fb179c72-6957-4c7b-aabe-eba08e928978.png)

**Comment by HOYS** [comment]
\_classic_\Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemSearch-1.2\LibItemSearch-1.2.lua

Comment out lines 250 to 262 and bagnon works again

**Comment by PFStein** [comment]
Looks like an 8.0 namespace was added this patch potentially? https://github.com/Jaliborc/LibItemSearch-1.2/blob/316f3a7fdf8dea7c8c8a4813838d16b4de0d339a/LibItemSearch-1.2.lua#L250 only activates if that namespace exists

**Comment by PFStein** [comment]
https://github.com/Jaliborc/LibItemSearch-1.2/pull/6

**Comment by HOYS** [comment]
> [Jaliborc/LibItemSearch-1.2#6](https://github.com/Jaliborc/LibItemSearch-1.2/pull/6)


Looks like the fix is already in the works, nice.

**Comment by robertjpayne** [comment]
For now if you want to fix this go into 

`_classic_\Interface\Addons\Bagnon\common\Wildpants\libs\LibItemSearch-1.2`

open the file `LibItemSearch-1.2.lua`

change code line `250`

`if C_AzeriteItem then` 

to

`if C_AzeriteItem and C_CurrencyInfo.GetAzeriteCurrencyID then`

save the file and you're good to go

**Comment by moondaze** [comment]
This would be a great fix above for people that know where code line 250 is..however for people like me who have no clue..can you just fix it please.

**Comment by robertjpayne** [comment]
@moondaze no need to get aggressive. It's gonna get fixed I was simply writing up a small tutorial on how to fix this by yourself and notepad.

Remember these people writing addons do so for free with no love from people like yourself demanding fixes.

**Comment by moondaze** [comment]
My apologies, didn't mean for it to sound rude and ungrateful.  Thank you for the video.  With that I was able to figure it out on how to find the line that needed correcting and it now works.  Thank you for the workaround

**Comment by boktai1000** [comment]
There also appears to be a bug when I try to shift click on items in the guild bank to grab a stack out. Here is the following LUA error- the workaround above fixes for personal use but seems this is still having issues for me.

![image](https://user-images.githubusercontent.com/9054563/159592977-18d1d322-51d9-4f6e-a6ea-48708df92cf8.png)


```
1x Bagnon\addons\guild\item.lua:35: attempt to call method 'OpenStackSplitFrame' (a nil value)
[string "@Bagnon\addons\guild\item.lua"]:35: in function <Bagnon\addons\guild\item.lua:30>

Locals:
self = BagnonGuildItem49 {
 timeSinceUpgradeCheck = 0
 OnEnter = <function> defined @Bagnon\common\Wildpants\classes\item.lua:179
 __super = <table> {
 }
 GetSlotType = <function> defined @Bagnon\common\Wildpants\classes\item.lua:469
 IconOverlay = <unnamed> {
 }
 SlotTypes = <table> {
 }
 UpdateCooldown = <function> defined @Bagnon\addons\guild\item.lua:85
 Bind = <function> defined @Bagnon\common\Wildpants\classes\item.lua:101
 IconBorder = <unnamed> {
 }
 flashAnim = <unnamed> {
 }
 OnReceiveDrag = <function> defined @Bagnon\addons\guild\item.lua:59
 icon = BagnonGuildItem49IconTexture {
 }
 ShowCachedTooltip = <function> defined @Bagnon\common\Wildpants\classes\item.lua:373
 UpdateTooltip = <function> defined @Bagnon\common\Wildpants\classes\item.lua:335
 ExtendedOverlay = <unnamed> {
 }
 __type = "Button"
 __count = 49
 GetFrameID = <function> defined @Bagnon\common\Wildpants\classes\parented.lua:19
 count = 66
 GetEmptyItemIcon = <function> defined @Bagnon\common\Wildpants\classes\item.lua:474
 IsQuestItem = <function> defined @Bagnon\addons\guild\item.lua:98
 SplitStack = <function> defined @Bagnon\addons\guild\item.lua:80
 frame = BagnonGuildFrame1 {
 }
 BagStaticBottom = <unnamed> {
 }
 info = <table> {
 }
 UpdateLocked = <function> defined @Bagnon\common\Wildpants\classes\item.lua:203
 UnregisterMessage = <function> defined @Details\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 Update = <function> defined @Bagnon\common\Wildpants\classes\item.lua:191
 flash = <unnamed> {
 }
 CreateDummy = <function> defined @Bagnon\common\Wildpants\classes\item.lua:380
 RegisterFrameSignal = <function> defined @Bagnon\common\Wildpants\classes\base.lua:15
 GetTemplate = <function> defined @Bagnon\common\Wildpants\libs\Poncho-2.0\Poncho-2.0.lua:108
 GetBlizzard = <function> defined @Bagnon\addons\guild\item.lua:24
 UpdateSearch = <function> defined @Bagnon\common\Wildpants\classes\item.lua:302
 hasItem = true
 RegisterSignal = <function> defined @Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:74
 SetLocked = <function> defined @Bagnon\common\Wildpants\classes\item.lua:286
 UnregisterSignal = <function> defined @Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:78
 IconGlow = <unnamed> {
 }
 NumInactive = <function> defined @Bagnon\common\Wildpants\libs\Poncho-2.0\Poncho-2.0.lua:124
 OnItemFlashed = <function> defined @Bagnon\common\Wildpants\classes\item.lua:325
 GetProfile = <function> defined @Bagnon\common\Wildpants\classes\parented.lua:23
 UpdateUpgradeIcon = <function> defined @Bagnon\common\Wildpants\classes\item.lua:277
 UnregisterAll = <function> defined @Bagnon\common\Wildpants\classes\base.lua:27
 NewItemTexture = <unnamed> {
 }
 GetClass = <function> defined @Bagnon\common\Wildpants\libs\Poncho-2.0\Poncho-2.0.lua:135
 IsAbstract = <function> defined @Bagnon\common\Wildpants\libs\Poncho-2.0\Poncho-2.0.lua:116
 Count = BagnonGuildItem49Count {
 }
 GetSuper = <function> defined @Bagnon\common\Wildpants\libs\Poncho-2.0\Poncho-2.0.lua:104
 OnPreClick = <function> defined @Bagnon\common\Wildpants\classes\item.lua:143
 searchOverlay = BagnonGuildItem49SearchOverlay {
 }
 Construct = <function> defined @Bagnon\addons\guild\item.lua:13
 OnDragStart = <function> defined @Bagnon\addons\guild\item.lua:53
 IsSlot = <function> defined @Bagnon\common\Wildpants\classes\item.lua:453
 bag = 1
 BattlepayItemTexture = <unnamed> {
 }
 GetOwner = <function> defined @Bagnon\common\Wildpants\classes\parented.lua:31
 Super = <
```

**Comment by rainecheck** [comment]
@boktai1000 that's an old issue, see https://github.com/tullamods/Bagnon/issues/757 https://github.com/tullamods/Bagnon/issues/806 https://github.com/tullamods/Bagnon/issues/860 etc. Even if it were new, you'd be better off opening a new issue not adding it to an unrelated one.

**Comment by boktai1000** [comment]
@rainecheck I wasn't sure if it was also "bug w/ new ZA patch" - thanks for clarifying

**Comment by Hyasiance** [comment]
Date: 2022-03-23 12:17:59
ID: 1
Error occured in: Global
Count: 1
Message: ...ldpants\libs\LibItemSearch-1.2\LibItemSearch-1.2.lua line 252:
   attempt to call field 'GetAzeriteCurrencyID' (a nil value)
Debug:
   [string "@Bagnon\common\Wildpants\libs\LibItemSearch-1.2\LibItemSearch-1.2.lua"]:252: in main chunk
Locals:
Search = <table> {
 OR = "or"
 NOT_MATCH = "not"
 NOT = "Not"
 Find = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\CustomSearch-1.0\CustomSearch-1.0.lua:131
 Match = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\CustomSearch-1.0\CustomSearch-1.0.lua:54
 MatchAny = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\CustomSearch-1.0\CustomSearch-1.0.lua:46
 ACCENTS = <table> {
 }
 MatchAll = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\CustomSearch-1.0\CustomSearch-1.0.lua:36
 UseFilter = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\CustomSearch-1.0\CustomSearch-1.0.lua:121
 Compare = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\CustomSearch-1.0\CustomSearch-1.0.lua:151
 Matches = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\CustomSearch-1.0\CustomSearch-1.0.lua:27
 Filter = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\CustomSearch-1.0\CustomSearch-1.0.lua:99
 Clean = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\CustomSearch-1.0\CustomSearch-1.0.lua:140
}
Unfit = <table> {
 IsItemUnusable = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\Unfit-1.0\Unfit-1.0.lua:111
 IsClassUnusable = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\Unfit-1.0\Unfit-1.0.lua:118
 unusable = <table> {
 }
 cannotDual = true
}
Lib = <table> {
 ForQuest = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemSearch-1.2\LibItemSearch-1.2.lua:36
 InSet = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemSearch-1.2\LibItemSearch-1.2.lua:44
 Tooltip = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemSearch-1.2\LibItemSearch-1.2.lua:28
 Scanner = LibItemSearchTooltipScanner {
 }
 IsReagent = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemSearch-1.2\LibItemSearch-1.2.lua:40
 TooltipLine = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemSearch-1.2\LibItemSearch-1.2.lua:54
 TooltipPhrase = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemSearch-1.2\LibItemSearch-1.2.lua:32
 Matches = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemSearch-1.2\LibItemSearch-1.2.lua:24
 BelongsToSet = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemSearch-1.2\LibItemSearch-1.2.lua:91
 Filters = <table> {
 }
}
(*temporary) = <table> {
 items = <table> {
 }
 type = <table> {
 }
 name = <table> {
 }
 requiredlevel = <table> {
 }
 usable = <table> {
 }
 level = <table> {
 }
 sets = <table> {
 }
 quality = <table> {
 }
}
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to call field 'GetAzeriteCurrencyID' (a nil value)"

AddOns:
  Swatter, v2.5.6773 (SwimmingSeadragon)
  Atlas, vv1.50.04
  AtlasBurningCrusade, vv1.50.02
  AtlasLootClassic, vv2.4.1-bcc
  AtlasLootClassicData, vv2.4.1-bcc
  AtlasLootClassicDungeonsAndRaids, vv2.4.1-bcc
  Attune, v250
  AucAdvanced, v2.5.6733 (SwimmingSeadragon)
  AucFilterBasic, v2.5.6759 (SwimmingSeadragon)
  AucStatHistogram, v2.5.6761 (SwimmingSeadragon)
  AucStatiLevel, v2.5.6765 (SwimmingSeadragon)
  AucStatPurchased, v2.5.6762 (SwimmingSeadragon)
  AucStatSimple, v2.5.6763 (SwimmingSeadragon)
  AucStatStdDev, v2.5.6764 (SwimmingSeadragon)
  AucUtilFixAH, v2.5.6766 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v9.1.4
  SlideBar, v2.5.6771 (SwimmingSeadragon)
  Stubby, v2.5.6772 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v2.5.4.20504 <none>
  (ck=2f

**Comment by hellcat-666** [comment]
I did the work around, but now all is empty :(

**Comment by colonelsevendot** [comment]
> There also appears to be a bug when I try to shift click on items in the guild bank to grab a stack out. Here is the following LUA error- the workaround above fixes for personal use but seems this is still having issues for me.

Please see https://github.com/tullamods/Bagnon/issues/1352 for a workaround/fix for TBC Classic.

**Comment by Jaliborc** [comment]
Anyone still having this issue in **another situation that is not login** with the latest version from a couple of days back? Just checking before I close.
