### ISSUE TITLE
wrong version in TOC file for classic 

### ISSUE THREAD

**Issue by MyTechnoHunter** [tullamods/Bagnon#1370]
**Running Software (issues missing this information will be deleted):**
 - Addon version: latest version
 - Server patch: [e.g. Build 8.0.1.27178]

 **Have you read the changelog? (please don't waste our time)**
 Mark if read. yeas i have read the changelog

**Describe the bug**

the toc file in the classic version of bagnon has 11400

it needs 11402 to load and be CURRENT for the game version

**To Reproduce**
Steps to reproduce the behaviour:

download the latest bagnon from curseforge

**Expected behaviour**

i expected the addon to load without needing to have "load out of date addons" checked for an addon that was updated TODAY

**Screenshots**

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the message with `ID: 1` (labelled 1/X). This is generally NOT the message that the window shows by default.

**Additional context**

thank you guys for updating, and for maintaining the addon but if you are going to update the addon please make sure its correct for the current version needed (since you are updating it anyways)

thanks for doing this!

**Comment by Jaliborc** [comment]
Alright, thanks for the heads up!
