### ISSUE TITLE
Cannot see Vulpera racial bag slots from non Vulpera character

### ISSUE THREAD

**Issue by Pyranthos492** [tullamods/Bagnon#1374]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 9.1.5
 - Server patch: 9.2.0.42979

 **Have you read the changelog? (please don't waste our time)**
 Mark if read.

**Describe the bug**
Can't see the additional slots Vulpera get from their racial when viewing alt inventory from a non Vulpera character

**To Reproduce**
Steps to reproduce the behaviour:
1. Log into a non Vulpera character
2. Open Bag
3. Select Vulpera character alt

**Expected behaviour**
There should be 28 slots in the backpack slot (16 base + 4 from authenticator +8 from vulpera racial)

**Comment by Jaliborc** [comment]
I don't have a vulpera. Just to double check, the racial makes your backpack bigger, correct?

**Comment by Pyranthos492** [comment]
It adds 8 additional slots to the base backpack

**Comment by Jaliborc** [comment]
Fixed
