### ISSUE TITLE
LUA Error & Possible Issue with Minion?

### ISSUE THREAD

**Issue by SanguineHeart85** [tullamods/Bagnon#1388]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.1.9
 - Server patch: Tides of Vengeance (8.1.0)

 **Have you read the changelog? (please don't waste our time)**
 It says "None"

**Describe the bug**
I installed Bagnon through Minion, then logged into WoW and enabled Bagnon. It says it's an out of date addon, so I enabled out of date addons. I login to a toon, any toon, it happens on all of them, and this LUA Error message is immediately displayed. I close it and it pops up again every time I try to open my bags. I've tried the open all function and just clicking on each bag individually. None of the bags open. I went to my bank and tried to open my bank and the error pops up there too, with my bank not opening. I then opened Minion again to see if Bagnon needs an update or something, and it's no longer listed on the installed list, it's completely gone. I've tried installing Bagnon three times and the same thing happens every time. I have other addons for WoW through Minion and they seem to be functioning fine.

Message: Interface\AddOns\Bagnon\components\frame.lua:30: attempt to call method 'SetBackdrop' (a nil value)
Time: Thu Jun  2 18:12:38 2022
Count: 1
Stack: Interface\AddOns\Bagnon\components\frame.lua:30: attempt to call method 'SetBackdrop' (a nil value)
[string "@Interface\AddOns\Bagnon\components\frame.lua"]:30: in function `New'
[string "@Interface\AddOns\Bagnon\external\Wildpants\core\frames.lua"]:14: in function `CreateFrame'
[string "@Interface\AddOns\Bagnon\main.lua"]:11: in function <Interface\AddOns\Bagnon\main.lua:9>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Bagnon\external\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua"]:558: in function `EnableAddon'
[string "@Interface\AddOns\Bagnon\external\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua"]:651: in function <...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:544: in function `UIParentLoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:667: in function `TimeManager_LoadUI'
[string "@Interface\FrameXML\UIParent.lua"]:1454: in function <Interface\FrameXML\UIParent.lua:1337>

Locals: <none>

**Comment by Jaliborc** [comment]
Bagnon isn't distributed on Minion.
