### ISSUE TITLE
9.1.5 Re-released

### ISSUE THREAD

**Issue by NayooZ** [tullamods/Bagnon#1391]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 9.1.5
 - Server patch: 2.5.4

 **Have you read the changelog? (please don't waste our time)**
Read

**Describe the bug**
9.1.5 was re-released on Jul 6 overwriting any fixes from 9.1.6 and 9.2.0

**To Reproduce**
Go to: https://www.curseforge.com/wow/addons/bagnon/files
Newest release is 9.1.5 instead of 9.2.0

**Expected behaviour**
Re-introduced errors that existed, i.e. unable to split items from gbank which was fixed in 9.2.0

**Screenshots**
N/A

**Error Logs**
N/A

**Additional context**
Suggestion to re-release 9.2.0 or newer so addon updaters pickup the fixed version.

**Comment by how2pingu** [comment]
Seconding this. Ignoring updates for the time being in order to stay on the correct version.

**Comment by alphabitnz** [comment]
+1

**Comment by MyTechnoHunter** [comment]
anyone actually looked at this issue since the thing hasnt been assigned to anyone?

**Comment by Jaliborc** [comment]
@NayooZ OK! That explains it. Uploaded 9.2.1 and was super confused as to why the "latest version" was still 9.1.5.

No clue what happened, if it was a curseforge bug, an issue on one of my machines,... I was abroad on the day of the re-upload, so human error wasn't.

**Comment by Jaliborc** [comment]
9.2.1 out, you can update now
