### ISSUE TITLE
LUA Error (within WOW Classic BCC PTR)

### ISSUE THREAD

**Issue by fheathyr** [tullamods/Bagnon#1396]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 9.1.5-2.5.2
 - Server patch: [e.g. Build 8.0.1.27178] Public Test Realm (Classic BCC)

 **Have you read the changelog? (please don't waste our time)**
Read.

**Describe the bug**
Bagnon frequently throws a Lua error 

**To Reproduce**
No steps required, it's just popping up very frequently. 

**Screenshots**
![image](https://user-images.githubusercontent.com/4422716/183269014-92fca853-0638-4a4d-bf4e-9bbff8d94782.png)

**Error Logs**
N/A

**Additional context**

**Comment by mreed** [comment]
As a temp fix for WOTLK classic you can comment out \common\Wildpants\classes\bag.lua line 144
self:RegisterEvent('CURSOR_UPDATE', 'UpdateCursor')

There seems to be a change in the way wotlk handles undefined variables from tbc. To make sort work you need to comment out \common\Wildpants\libs\LibItemSearch-1.2\libItemSearch-1.2.lua lines 234 - 262; you use -- to comment in lua
