### ISSUE TITLE
Implement frame settings profiles

### ISSUE THREAD

**Issue by Tuller** [tullamods/Bagnon#14]
What is the enhancement in mind? How should it look and feel?

a Profile system like the one in Genie (addon to sort bags/banks etc). allows you to have separate settings for all characters (which is the current way bagnon functions), or to have all the same, or different by class, realm, etc

Please provide any additional information below.
my personal preference is to have all bagnon settings the same for all characters; only was to do that as of now is to create hardlinks in windows filesyestem to point all bagnon.lua files to the same master file.

**Comment by Jaliborc** [comment]
Done :D
