### ISSUE TITLE
Error when opening or closing inventory

### ISSUE THREAD

**Issue by addohm** [tullamods/Bagnon#1404]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 9.1.5
 - Server patch: 3.4.0 (45327)

 **Have you read the changelog? (please don't waste our time)**
 Mark if read.

**Describe the bug**
Message: ...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:33: Attempt to register unknown event "CURSOR_UPDATE"
Time: Wed Aug 31 10:03:42 2022
Count: 1
Stack: ...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:33: Attempt to register unknown event "CURSOR_UPDATE"
[string "=[C]"]: in function `RegisterEvent'
[string "@Interface\AddOns\Bagnon\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua"]:33: in function `OnUsed'
[string "@Interface\AddOns\AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:142: in function `RegisterEvent'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\bag.lua"]:144: in function `RegisterEvents'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\bag.lua"]:72: in function <...rface\AddOns\Bagnon\common\Wildpants\classes\bag.lua:17>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\bagGroup.lua"]:17: in function <...\AddOns\Bagnon\common\Wildpants\classes\bagGroup.lua:11>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Bagnon\addons\main\frame.lua"]:239: in function `CreateBagGroup'
[string "@Interface\AddOns\Bagnon\addons\main\frame.lua"]:219: in function `PlaceBagGroup'
[string "@Interface\AddOns\Bagnon\addons\main\frame.lua"]:87: in function `Layout'
[string "@Interface\AddOns\Bagnon\addons\main\frame.lua"]:66: in function `Update'
[string "@Interface\AddOns\Bagnon\addons\main\frame.lua"]:56: in function `RegisterSignals'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\frame.lua"]:19: in function <...ace\AddOns\Bagnon\common\Wildpants\classes\frame.lua:17>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\inventory.lua"]:21: in function <...AddOns\Bagnon\common\Wildpants\classes\inventory.lua:20>
[string "=[C]"]: in function `Show'
[string "@Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua"]:85: in function `Show'
[string "@Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua"]:77: in function <...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:76>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Bagnon\common\Wildpants\features\autoDisplay.lua"]:146: in function `ToggleBackpack'
[string "TOGGLEBACKPACK"]:1: in function <[string "TOGGLEBACKPACK"]:1>

Locals: (*temporary) = AceEvent30Frame {
 0 = <userdata>
}
(*temporary) = "CURSOR_UPDATE"

**To Reproduce**
Steps to reproduce the behaviour:
Opening or closing inventory

**Expected behaviour**
No error

**Screenshots**

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the message with `ID: 1` (labelled 1/X). This is generally NOT the message that the window shows by default.

**Additional context**

**Comment by TGKx** [comment]
As a temporary fix, edit \AddOns\Bagnon\common\Wildpants\classes\bag.lua and replace "CURSOR_UPDATE" with "CURSOR_CHANGED"

**Comment by Dezaku** [comment]
Thank you!
