### ISSUE TITLE
Bagnon issue LK classic open and close bags

### ISSUE THREAD

**Issue by Phoenixrexx** [tullamods/Bagnon#1407]
*Date: 2022-09-01 17:22:48
ID: 7
Error occured in: Global
Count: 1
Message: ...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua line 37:
   Attempt to unregister unknown event "CURSOR_UPDATE"
Debug:
   [string "=[C]"]: UnregisterEvent()
   [string "@Bagnon\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua"]:37: OnUnused()
   [string "@Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:197: UnregisterAllEvents()
   [string "@Bagnon\common\Wildpants\classes\base.lua"]:29:
      ...face\AddOns\Bagnon\common\Wildpants\classes\base.lua:27
   [string "=[C]"]: Hide()
   [string "@Bagnon\common\Wildpants\api\frames.lua"]:94: Hide()
   [string "@Bagnon\addons\main\frame.lua"]:28:
      Bagnon\addons\main\frame.lua:28
Locals:
(*temporary) = AceEvent30Frame {
 0 = <userdata>
}
(*temporary) = "CURSOR_UPDATE"

AddOns:
  Swatter, v2.5.6773 (SwimmingSeadragon)
  Atlas, vv1.51.06
  AtlasLootClassic, vv2.4.4-bcc
  AtlasLootClassicData, vv2.4.4-bcc
  AtlasLootClassicDungeonsAndRaids, vv2.4.4-bcc
  Auctionator, v9.2.30
  BagBrother, v
  Bagnon, v9.1.5
  BeanCounter, v2.5.6767 (SwimmingSeadragon)
  DBMCore, vfa8a9ff
  DBMSoundEventsPack, v1.6.18
  DBMStatusBarTimers, vfa8a9ff
  DBMVPVEM, v6746e8a
  Details, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsVanguard, v
  Dominos, v9.3.4
  DominosCast, v
  DominosEncounter, v
  DominosProgress, v
  DominosRoll, v
  Guidelime, v2.036
  GuidelimePhoenixspeedGuide, v0.001-Beta
  GuidelimeSage, v1.0.2
  HealBot, v3.4.0.0.b8
  HealBotData, v2.5.4.20
  HealBotOptions, v3.4.0.0
  HealBotTips, v3.4.0.0
  HidingBar, vv9.2.14
  Informant, v2.5.6770 (SwimmingSeadragon)
  Omen, v3.2.4
  Pawn, v2.6.0
  Questie, v7.0.1
  RareScanner, v9.2.7
  SlideBar, v2.5.6771 (SwimmingSeadragon)
  SpeedyAutoLoot, v2.1.15
  Stubby, v2.5.6772 (SwimmingSeadragon)
  TitanAttributesMulti, v1.1.1
  TitanClassic, v1.5.3.30400
  TitanClassicAmmo, v1.5.3.30400
  TitanClassicBag, v1.5.3.30400
  TitanClassicClock, v1.5.3.30400
  TitanClassicGold, v1.5.3.30400
  TitanClassicLocation, v1.5.3.30400
  TitanClassicLootType, v1.5.3.30400
  TitanClassicPerformance, v1.5.3.30400
  TitanClassicReagentTracker, v2.5.1.38707
  TitanClassicRegen, v1.5.3.30400
  TitanClassicRepair, v1.5.3.30400
  TitanClassicVolume, v1.5.3.30400
  TitanClassicXP, v1.5.3.30400
  ZPerl, v6.3.3
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidAdmin, v
  ZPerlRaidFrames, v
  ZPerlRaidHelper, v
  ZPerlRaidMonitor, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  ZygorGuidesViewerClassicTBC, v2.1
  BlizRuntimeLib_enUS v3.4.0.30400 <none>
  (ck=71e)

**Comment by Miss7714** [comment]
This is still an issue.....

**Comment by Dezaku** [comment]
Same for me
