### ISSUE TITLE
LUA error on open or closing bags.

### ISSUE THREAD

**Issue by F22Astroturf** [tullamods/Bagnon#1409]
Classic - Each time opening or closing bags after updating to version 9.2.1 I get this - 
Message: ...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0-4.lua:33: Attempt to register unknown event "CURSOR_CHANGED"
Time: Sat Sep  3 11:49:08 2022
Count: 1
Stack: ...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0-4.lua:33: Attempt to register unknown event "CURSOR_CHANGED"
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\bag.lua"]:144: in function `RegisterEvents'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\bag.lua"]:72: in function <...rface\AddOns\Bagnon\common\Wildpants\classes\bag.lua:17>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\bagGroup.lua"]:17: in function <...\AddOns\Bagnon\common\Wildpants\classes\bagGroup.lua:11>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Bagnon\addons\main\frame.lua"]:239: in function `CreateBagGroup'
[string "@Interface\AddOns\Bagnon\addons\main\frame.lua"]:219: in function `PlaceBagGroup'
[string "@Interface\AddOns\Bagnon\addons\main\frame.lua"]:87: in function `Layout'
[string "@Interface\AddOns\Bagnon\addons\main\frame.lua"]:66: in function `Update'
[string "@Interface\AddOns\Bagnon\addons\main\frame.lua"]:56: in function `RegisterSignals'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\frame.lua"]:19: in function <...ace\AddOns\Bagnon\common\Wildpants\classes\frame.lua:17>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\inventory.lua"]:21: in function <...AddOns\Bagnon\common\Wildpants\classes\inventory.lua:20>
[string "=[C]"]: in function `Show'
[string "@Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua"]:85: in function `Show'
[string "@Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua"]:77: in function <...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:76>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Bagnon\common\Wildpants\features\autoDisplay.lua"]:146: in function `ToggleBackpack'
[string "TOGGLEBACKPACK"]:1: in function <[string "TOGGLEBACKPACK"]:1>

Locals: self = <unnamed> {
 FilterIcon = <unnamed> {
 }
 Count = <unnamed> {
 }
 link = "[Runecloth Bag]"
 frame = BagnonInventoryFrame1 {
 }
 Icon = <unnamed> {
 }
 0 = <userdata>
}

**Comment by Jaliborc** [comment]
Please answer the issue questionaire as provided so that I can actually help you.

**Comment by F22Astroturf** [comment]
> Please answer the issue questionaire as provided so that I can actually help you. That is not enought information to go by.

I typed the "/console scriptErrors 1" in the chat as you stated in your questionnaire and reloaded and No errors come up when it reloads, The error only shows when opening or closing bags.

Wow classic Version 1.14.3.44834
Bagnon version 9.2.1
**Have you read the changelog? (please don't waste our time)**
 Mark if read. Yes and didn't find anything I'm not a programmer That's why I gave the only thing it shows when I open or close bags.

**Comment by Jaliborc** [comment]
Now we're talking. 9.2.2 should fix this.
