### ISSUE TITLE
Bank window always shows empty bank in WotLK Classic

### ISSUE THREAD

**Issue by Lightras** [tullamods/Bagnon#1411]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 9.2.2-3.4.0
 - Server patch: 3.4.0.45435

 **Have you read the changelog? (please don't waste our time)**
 Yes

**Describe the bug**
Bank window always shows empty bank in WotLK Classic

**To Reproduce**
Steps to reproduce the behaviour:
1. Open bag
2. Right-click on the Bag Slots button (top left corner)
3. In the Bagnon Frames popup click Bank
4. The bank window opens and all the slots there are empty.

**Expected behaviour**
The bank window should show items you have in your bank.

**Screenshots**
![Screenshot_49](https://user-images.githubusercontent.com/19798282/188546534-604c8cc9-3cda-4b1a-8af6-6f8b52020b45.png)
![Screenshot_50](https://user-images.githubusercontent.com/19798282/188546535-17e2fb0d-4f35-4bb5-a898-fc48c1af41c8.png)

**Error Logs**
No errors appear when reproducing the bug after /console scriptErrors 1 and restart.

**Comment by Jaliborc** [comment]
Have you visited the bank yet?

**Comment by Lightras** [comment]
Sure.
1. I open my bank and see the items. (screenshot 2)
2. I close the bank.
3. I open the Bagnon Bank Window and it’s empty (screenshot 1).

**Comment by Lightras** [comment]
Okay, I've fixed it. Looks like something went wrong during the installation or update via CurseForge app. It said the addon was Modified, although I'm sure I didn't modify it. So after an updating it again via CurseForge it works perfectly.
