### ISSUE TITLE
Latest 3.4.0 beta 9.2.3 update broke the addon

### ISSUE THREAD

**Issue by Nillx** [tullamods/Bagnon#1413]
9.2.3 broke the addon in wotlk. Im getting this error now

```
20x ...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:45: attempt to call field 'GetBackpackCurrencyInfo' (a nil value)
[string "@Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:45: in function `Update'
[string "@Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:39: in function `RegisterEvents'
[string "@Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:25: in function <...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:13>
[string "=(tail call)"]: ?
[string "@Bagnon\addons\main\frame.lua"]:319: in function `PlaceCurrency'
[string "@Bagnon\addons\main\frame.lua"]:97: in function `Layout'
[string "@Bagnon\addons\main\frame.lua"]:66: in function `Update'
[string "@Bagnon\addons\main\frame.lua"]:56: in function `RegisterSignals'
[string "@Bagnon\common\Wildpants\classes\frame.lua"]:19: in function <...aceBagnon\common\Wildpants\classes\frame.lua:17>
[string "=(tail call)"]: ?
[string "@Bagnon\common\Wildpants\classes\inventory.lua"]:21: in function <Bagnon\common\Wildpants\classes\inventory.lua:20>
[string "=[C]"]: in function `Show'
[string "@Bagnon\common\Wildpants\api\frames.lua"]:85: in function `Show'
[string "@Bagnon\common\Wildpants\api\frames.lua"]:77: in function `Toggle'
[string "@Bagnon\common\Wildpants\features\autoDisplay.lua"]:184: in function `ToggleAllBags'
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Locals:
self = <unnamed> {
 0 = <userdata>
 frame = BagnonInventoryFrame1 {
 }
 Text = <unnamed> {
 }
}
v = ""
(for index) = 1
(for limit) = 3
(for step) = 1
i = 1
(*temporary) = nil
(*temporary) = 1
(*temporary) = "attempt to call field 'GetBackpackCurrencyInfo' (a nil value)"
```

**Comment by CalebFringer** [comment]
I too am experiencing this error. From my digging with the /api command, it appears that C_CurrencyInfo.GetBackpackCurrencyInfo() is missing from the WOTLK Classic API.

**Comment by Sepulchre49** [comment]
I managed to get a fix together for this. The C_CurrencyInfo namespace does not exist in WOTLK, so this function as well as SetCurrencyBackpack need to be called globally. The file causing the errors is Bagnon\common\Wildpants\classes\currencyDisplay.lua.

I would like to submit a pull request to fix this, but the file currencyDisplay.lua does not appear in the Wildpants repository (perhaps it was added sometime in the past five days? Please tell me how you'd like me to proceed.

**Comment by Jaliborc** [comment]
Don't worry with a PR, the beta is just a demo for a poll, code is temporary. You can help instead by answering the strawpoll:
https://www.patreon.com/posts/bagnon-currency-71748089

**Comment by Dubbeldrank** [comment]
Currently the add-on is broken and i disabled it, any news on a fix? :)

**Comment by Jaliborc** [comment]
Install release

**Comment by Burdarper** [comment]
Looks like broken beta got relaesed ;-/

Any hints on the fix Sepulchre49 mentioned ?

**Comment by GGDAG** [comment]
If you use curseforge you an easily click your way to versions and install "Bagnon-9.2.2-3.4.0.zip" instead, which works fine for me

**Comment by themistiq2694** [comment]
If you create an empty txt file in that folder with same name. it will work just fine so far from what I have tested.
