### ISSUE TITLE
Bags do not show

### ISSUE THREAD

**Issue by diabolakos** [tullamods/Bagnon#1415]
**Running Software (issues missing this information will be deleted):**
 - Addon version: Bagnon-9.2.38-wrath.zip
 - Server patch: 3.4.0.045572

 **Have you read the changelog? (please don't waste our time)**
 Mark if read.  READ

**Describe the bug**
When you open the bags no personal bags are shown (you hear the sound of open bag but nothing displays) anf get several lua errors

**Error Logs**
1ST LUA ERROR:
`Message:` ...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:45: attempt to call field 'GetBackpackCurrencyInfo' (a nil value)
Time: Wed Sep 14 23:03:33 2022
Count: 1
Stack: ...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:45: attempt to call field 'GetBackpackCurrencyInfo' (a nil value)
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:761: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "=[C]"]: in function `GetBackpackCurrencyInfo'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:45: in function `Update'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:39: in function `RegisterEvents'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:25: in function <...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:13>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Bagnon\addons\main\frame.lua"]:319: in function `PlaceCurrency'
[string "@Interface\AddOns\Bagnon\addons\main\frame.lua"]:97: in function `Layout'
[string "@Interface\AddOns\Bagnon\addons\main\frame.lua"]:66: in function `Update'
[string "@Interface\AddOns\Bagnon\addons\main\frame.lua"]:56: in function `RegisterSignals'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\frame.lua"]:19: in function <...ace\AddOns\Bagnon\common\Wildpants\classes\frame.lua:17>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\inventory.lua"]:21: in function <...AddOns\Bagnon\common\Wildpants\classes\inventory.lua:20>
[string "=[C]"]: in function `Show'
[string "@Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua"]:85: in function `Show'
[string "@Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua"]:77: in function `Toggle'
[string "@Interface\AddOns\Bagnon\common\Wildpants\features\autoDisplay.lua"]:184: in function `ToggleAllBags'
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Locals: errMsg = "...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:45: attempt to call field 'GetBackpackCurrencyInfo' (a nil value)"
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:517
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:355
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:536
 num = 0
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:510
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:478
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:313
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}`

2nd LUA ERROR:
`Message: ...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:45: attempt to call field 'GetBackpackCurrencyInfo' (a nil value)
Time: Wed Sep 14 23:03:33 2022
Count: 1
Stack: ...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:45: attempt to call field 'GetBackpackCurrencyInfo' (a nil value)
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:761: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:45: in function `Update'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:39: in function `RegisterEvents'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:25: in function <...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:13>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Bagnon\addons\main\frame.lua"]:319: in function `PlaceCurrency'
[string "@Interface\AddOns\Bagnon\addons\main\frame.lua"]:97: in function `?'
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `SendMessage'
[string "@Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua"]:83: in function `SendSignal'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\base.lua"]:24: in function `SendFrameSignal'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\itemGroup.lua"]:177: in function `func'
[string "@Interface\AddOns\Bagnon\common\Wildpants\libs\MutexDelay-1.0\MutexDelay-1.0.lua"]:36: in function <...mon\Wildpants\libs\MutexDelay-1.0\MutexDelay-1.0.lua:30>

Locals: <none>`

3rd LUA ERROR:
`Message: ...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:45: attempt to call field 'GetBackpackCurrencyInfo' (a nil value)
Time: Wed Sep 14 23:06:29 2022
Count: 2
Stack: ...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:45: attempt to call field 'GetBackpackCurrencyInfo' (a nil value)
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:761: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "=[C]"]: in function `GetBackpackCurrencyInfo'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:45: in function `Update'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:39: in function <...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:36>
[string "=[C]"]: in function `Show'
[string "@Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua"]:85: in function `Show'
[string "@Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua"]:77: in function `Toggle'
[string "@Interface\AddOns\Bagnon\common\Wildpants\features\autoDisplay.lua"]:184: in function `ToggleAllBags'
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Locals: errMsg = "...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:45: attempt to call field 'GetBackpackCurrencyInfo' (a nil value)"
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:517
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:355
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:536
 num = 0
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:510
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:478
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:313
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}`

4th LUA ERROR:
`Message: ...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:45: attempt to call field 'GetBackpackCurrencyInfo' (a nil value)
Time: Wed Sep 14 23:07:36 2022
Count: 6
Stack: ...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:45: attempt to call field 'GetBackpackCurrencyInfo' (a nil value)
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:761: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:45: in function `?'
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `SendMessage'
[string "@Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua"]:83: in function `SendSignal'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\base.lua"]:24: in function `SendFrameSignal'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\frame.lua"]:138: in function `SetOwner'
[string "@Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua"]:84: in function `Show'
[string "@Interface\AddOns\Bagnon\common\Wildpants\features\autoDisplay.lua"]:82: in function `?'
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>`

5th LUA ERROR:
`Message: ...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:45: attempt to call field 'GetBackpackCurrencyInfo' (a nil value)
Time: Wed Sep 14 23:07:59 2022
Count: 1
Stack: ...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:45: attempt to call field 'GetBackpackCurrencyInfo' (a nil value)
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:761: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "=[C]"]: in function `GetBackpackCurrencyInfo'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:45: in function `Update'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:39: in function `RegisterEvents'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:25: in function <...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:13>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Bagnon\addons\main\frame.lua"]:319: in function `PlaceCurrency'
[string "@Interface\AddOns\Bagnon\addons\main\frame.lua"]:97: in function `Layout'
[string "@Interface\AddOns\Bagnon\addons\main\frame.lua"]:66: in function `Update'
[string "@Interface\AddOns\Bagnon\addons\main\frame.lua"]:56: in function `RegisterSignals'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\frame.lua"]:19: in function <...ace\AddOns\Bagnon\common\Wildpants\classes\frame.lua:17>
[string "=[C]"]: in function `Show'
[string "@Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua"]:85: in function `Show'
[string "@Interface\AddOns\Bagnon\common\Wildpants\features\autoDisplay.lua"]:90: in function `?'
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `SendMessage'
[string "@Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua"]:60: in function <...Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:60>
[string "=[C]"]: ?
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: errMsg = "...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:45: attempt to call field 'GetBackpackCurrencyInfo' (a nil value)"
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:517
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:355
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:536
 num = 0
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:510
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM`

6th LUA ERROR:
`Message: ...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:45: attempt to call field 'GetBackpackCurrencyInfo' (a nil value)
Time: Wed Sep 14 23:07:59 2022
Count: 7
Stack: ...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:45: attempt to call field 'GetBackpackCurrencyInfo' (a nil value)
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:761: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "=[C]"]: in function `GetBackpackCurrencyInfo'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:45: in function `Update'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:39: in function <...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:36>
[string "=[C]"]: in function `Show'
[string "@Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua"]:85: in function `Show'
[string "@Interface\AddOns\Bagnon\common\Wildpants\features\autoDisplay.lua"]:96: in function `?'
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `SendMessage'
[string "@Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua"]:60: in function <...Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:60>
[string "=[C]"]: ?
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: errMsg = "...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:45: attempt to call field 'GetBackpackCurrencyInfo' (a nil value)"
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:517
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:355
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:536
 num = 0
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:510
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:478
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:313
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}`

7th LUA ERROR:
`Message: ...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:45: attempt to call field 'GetBackpackCurrencyInfo' (a nil value)
Time: Wed Sep 14 23:07:59 2022
Count: 1
Stack: ...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:45: attempt to call field 'GetBackpackCurrencyInfo' (a nil value)
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:761: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "=[C]"]: in function `GetBackpackCurrencyInfo'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:45: in function `Update'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:39: in function `RegisterEvents'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:25: in function <...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:13>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Bagnon\addons\main\frame.lua"]:319: in function `PlaceCurrency'
[string "@Interface\AddOns\Bagnon\addons\main\frame.lua"]:97: in function `Layout'
[string "@Interface\AddOns\Bagnon\addons\main\frame.lua"]:66: in function `Update'
[string "@Interface\AddOns\Bagnon\addons\main\frame.lua"]:56: in function `RegisterSignals'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\frame.lua"]:19: in function <...ace\AddOns\Bagnon\common\Wildpants\classes\frame.lua:17>
[string "=(tail call)"]: ?
...
[string "@Interface\AddOns\Bagnon\common\Wildpants\features\autoDisplay.lua"]:96: in function `?'
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `SendMessage'
[string "@Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua"]:60: in function <...Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:60>
[string "=[C]"]: ?
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: errMsg = "...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:45: attempt to call field 'GetBackpackCurrencyInfo' (a nil value)"
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:517
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:355
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:536
 num = 0
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:510
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:478
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined`

**Comment by geezerbahl** [comment]
This... Latest update is broken. Hopefully a fix will be released soon.

**Comment by Jaliborc** [comment]
https://github.com/tullamods/Bagnon/issues/1413
