### ISSUE TITLE
new one dose not open

### ISSUE THREAD

**Issue by healey1153** [tullamods/Bagnon#1417]
**Running Software (issues missing this information will be deleted):**
 - Addon version:
 - Server patch: [e.g. Build 8.0.1.27178]

 **Have you read the changelog? (please don't waste our time)**
 Mark if read.

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the message with `ID: 1` (labelled 1/X). This is generally NOT the message that the window shows by default.

**Additional context**

**Comment by Martijndewin** [comment]
My Lua error when trying to open bag:


Message: ...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:45: attempt to call field 'GetBackpackCurrencyInfo' (a nil value)
Time: Thu Sep 15 11:50:58 2022
Count: 1
Stack: ...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:45: attempt to call field 'GetBackpackCurrencyInfo' (a nil value)
[string "=[C]"]: in function `GetBackpackCurrencyInfo'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:45: in function `Update'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:39: in function `RegisterEvents'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:25: in function <...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:13>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Bagnon\addons\main\frame.lua"]:319: in function `PlaceCurrency'
[string "@Interface\AddOns\Bagnon\addons\main\frame.lua"]:97: in function `Layout'
[string "@Interface\AddOns\Bagnon\addons\main\frame.lua"]:66: in function `Update'
[string "@Interface\AddOns\Bagnon\addons\main\frame.lua"]:56: in function `RegisterSignals'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\frame.lua"]:19: in function <...ace\AddOns\Bagnon\common\Wildpants\classes\frame.lua:17>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\inventory.lua"]:21: in function <...AddOns\Bagnon\common\Wildpants\classes\inventory.lua:20>
[string "=[C]"]: in function `Show'
[string "@Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua"]:85: in function `Show'
[string "@Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua"]:77: in function <...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:76>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Bagnon\common\Wildpants\features\autoDisplay.lua"]:146: in function `ToggleBackpack'
[string "TOGGLEBACKPACK"]:1: in function <[string "TOGGLEBACKPACK"]:1>

Locals:
