### ISSUE TITLE
Bagnon WoW

### ISSUE THREAD

**Issue by 6swayzii** [tullamods/Bagnon#1418]
New update(release date 9/9) of Bagnon does not allow you to open your bags in game. The previous update release date 9/4 does not have the issue.

Thank you,

Sixbbgirl/Swayzii

**Comment by LaurentChardin** [comment]
I think the 9/9 release, aka 9.2.3-3.4.0 is in beta stage in curseforge. You might want to stick to Release state and switch back to the previous version.

**Comment by GeekBoyMN** [comment]
Changed the release type in CurseForge to "release" and now Bagnon works again. FWIW I noticed I could always hear the bag sound, but could never see my bags or bank open or close.
