### ISSUE TITLE
Error from recent update impacting bag use.

### ISSUE THREAD

**Issue by AlucardHSing** [tullamods/Bagnon#1420]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 9.2.2
 - Server patch: 3.4.0.45613

 Read.

**Describe the bug**
Upon logging into a character, attempting to access bags throws error.

**To Reproduce**
Steps to reproduce the behaviour:
1. Log into any character
2. Click on bag icons or use open bag keybind
3. See error

**Expected behaviour**
Open my bag to see contents

**Error Logs**
Date: 2022-09-15 19:33:35
ID: 1
Error occured in: Global
Count: 1
Message: ...\Bagnon\common\Wildpants\classes\currencyDisplay.lua line 45:
   attempt to call field 'GetBackpackCurrencyInfo' (a nil value)
Debug:
   [string "@Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:45: Update()
   [string "@Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:39: RegisterEvents()
   [string "@Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:25:
      ...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:13
   [string "=(tail call)"]: ?
   [string "@Bagnon\addons\main\frame.lua"]:319: PlaceCurrency()
   [string "@Bagnon\addons\main\frame.lua"]:97: Layout()
   [string "@Bagnon\addons\main\frame.lua"]:66: Update()
   [string "@Bagnon\addons\main\frame.lua"]:56: RegisterSignals()
   [string "@Bagnon\common\Wildpants\classes\frame.lua"]:19:
      ...ace\AddOns\Bagnon\common\Wildpants\classes\frame.lua:17
   [string "=(tail call)"]: ?
   [string "@Bagnon\common\Wildpants\classes\inventory.lua"]:21:
      ...AddOns\Bagnon\common\Wildpants\classes\inventory.lua:20
   [string "=[C]"]: Show()
   [string "@Bagnon\common\Wildpants\api\frames.lua"]:85: Show()
   [string "@Bagnon\common\Wildpants\api\frames.lua"]:77:
      ...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:76
   [string "=(tail call)"]: ?
   [string "@Bagnon\common\Wildpants\features\autoDisplay.lua"]:146: ToggleBackpack()
   [string "TOGGLEBACKPACK"]:1:
      [string "TOGGLEBACKPACK"]:1
Locals:
self = <unnamed> {
 0 = <userdata>
 frame = BagnonInventoryFrame1 {
 }
 Text = <unnamed> {
 }
}
v = ""
(for index) = 1
(for limit) = 3
(for step) = 1
i = 1
(*temporary) = nil
(*temporary) = 1
(*temporary) = "attempt to call field 'GetBackpackCurrencyInfo' (a nil value)"

AddOns:
  Swatter, v3.4.6817 (SwimmingSeadragon)
  AtlasLootClassic, vv3.0.2
  AtlasLootClassicData, vv3.0.2
  AtlasLootClassicDungeonsAndRaids, vv3.0.2
  AucAdvanced, v3.4.6825 (SwimmingSeadragon)
  AucFilterBasic, v3.4.6803 (SwimmingSeadragon)
  AucStatHistogram, v3.4.6805 (SwimmingSeadragon)
  AucStatiLevel, v3.4.6809 (SwimmingSeadragon)
  AucStatPurchased, v3.4.6806 (SwimmingSeadragon)
  AucStatSimple, v3.4.6807 (SwimmingSeadragon)
  AucStatStdDev, v3.4.6808 (SwimmingSeadragon)
  AucUtilFixAH, v3.4.6810 (SwimmingSeadragon)
  BadBoy, vv9.2.5
  BagBrother, v
  Bagnon, v9.2.3
  BagnonItemInfo, v1.0.35-Release
  BagnonItemLevel, v1.0.56-Release
  BeanCounter, v3.4.6811 (SwimmingSeadragon)
  BetterVendorPrice, vv1.17.03
  DBMCore, v5dbcb14
  DBMStatusBarTimers, v5dbcb14
  DBMVPVEM, v1b93adf
  Details, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  Enchantrix, v3.4.6821 (SwimmingSeadragon)
  EnchantrixBarker, v3.4.6813 (SwimmingSeadragon)
  GatherMate2, v1.46.3-classic
  Informant, v3.4.6814 (SwimmingSeadragon)
  NovaInstanceTracker, v1.33
  Questie, v7.1.2
  Scrap, v9.2.1
  SlideBar, v3.4.6815 (SwimmingSeadragon)
  Spy, v3.0.1
  Stubby, v3.4.6816 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v3.4.0.30400 <none>
  (ck=50b)

**Comment by Pendraig-HKW** [comment]
Running Bagnon-9.2.3-3.4.0.zip on classic wow.  Just updated a few moments ago.  No LUA errors seen when attempting to access\view contents of consolidated bags, rather the consolidated bag itself simply does not display!

Running Bagnon-9.2.3-9.2.7.zip in retail, no problems whatsoever.

I've had to completely disable bagnon in classic to access the contents of my inventory

**Comment by Doomblaze** [comment]
I have the same issue. When I try to access the consolidated bag, it does not open

**Comment by OasisGaming** [comment]
I'm encountering the same issue. Here's the LUA error I'm getting.

Message: ...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:45: attempt to call field 'GetBackpackCurrencyInfo' (a nil value)
Time: Fri Sep 16 20:43:45 2022
Count: 1
Stack: ...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:45: attempt to call field 'GetBackpackCurrencyInfo' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Bagnon\addons\main\frame.lua"]:319: in function `PlaceCurrency'
[string "@Interface\AddOns\Bagnon\addons\main\frame.lua"]:97: in function `Layout'
[string "@Interface\AddOns\Bagnon\addons\main\frame.lua"]:66: in function `Update'
[string "@Interface\AddOns\Bagnon\addons\main\frame.lua"]:56: in function `RegisterSignals'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\frame.lua"]:19: in function <...ace\AddOns\Bagnon\common\Wildpants\classes\frame.lua:17>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\inventory.lua"]:21: in function <...AddOns\Bagnon\common\Wildpants\classes\inventory.lua:20>
[string "=[C]"]: in function `Show'
[string "@Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua"]:85: in function `Show'
[string "@Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua"]:77: in function <...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:76>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Bagnon\common\Wildpants\features\autoDisplay.lua"]:146: in function <...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:145>
[string "@Interface\AddOns\ZygorGuidesViewerClassicTBC\InventoryManager.lua"]:674: in function `ToggleBackpack'
[string "TOGGLEBACKPACK"]:1: in function <[string "TOGGLEBACKPACK"]:1>

Locals: (*temporary) = "down"
(*temporary) = <function> defined =[C]:-1

**Comment by sfjuocekr** [comment]
Same as OP, bag and bank won't open.

```
10x ...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:45: attempt to call field 'GetBackpackCurrencyInfo' (a nil value)
[string "@Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:45: in function `Update'
[string "@Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:39: in function `RegisterEvents'
[string "@Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:25: in function <...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:13>
[string "=(tail call)"]: ?
[string "@Bagnon\addons\main\frame.lua"]:319: in function `PlaceCurrency'
[string "@Bagnon\addons\main\frame.lua"]:97: in function `Layout'
[string "@Bagnon\addons\main\frame.lua"]:66: in function `Update'
[string "@Bagnon\addons\main\frame.lua"]:56: in function `RegisterSignals'
[string "@Bagnon\common\Wildpants\classes\frame.lua"]:19: in function <...aceBagnon\common\Wildpants\classes\frame.lua:17>
[string "=(tail call)"]: ?
[string "@Bagnon\common\Wildpants\classes\inventory.lua"]:21: in function <Bagnon\common\Wildpants\classes\inventory.lua:20>
[string "=[C]"]: in function `Show'
[string "@Bagnon\common\Wildpants\api\frames.lua"]:85: in function `Show'
[string "@Bagnon\common\Wildpants\api\frames.lua"]:77: in function `Toggle'
[string "@Bagnon\common\Wildpants\features\autoDisplay.lua"]:184: in function `ToggleAllBags'
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Locals:
self = <unnamed> {
 0 = <userdata>
 frame = BagnonInventoryFrame1 {
 }
 Text = <unnamed> {
 }
}
v = ""
(for index) = 1
(for limit) = 3
(for step) = 1
i = 1
(*temporary) = nil
(*temporary) = 1
(*temporary) = "attempt to call field 'GetBackpackCurrencyInfo' (a nil value)"

```

**Comment by leplepv2** [comment]
Hey!  So not a permanent fix but I was having the same issue as mentioned above.  Try going into the settings and turning off "Currencies" for all bag types.

![image](https://user-images.githubusercontent.com/113781880/190860885-7e462de9-8e99-43e6-9b2e-e76b3747b333.png)

**Comment by Doomblaze** [comment]
My issue was fixed in another thread. I found that bagnon was set to “beta” instead of whatever the normal version type is. Switching it back to normal allowed bagnon to work again

**Comment by Jaliborc** [comment]
install release
