### ISSUE TITLE
9.2.3 Beta Classic Non-functional

### ISSUE THREAD

**Issue by alphabitnz** [tullamods/Bagnon#1421]
```
20x ...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:44: 'for' limit must be a number
[string "@Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:44: in function `Update'
[string "@Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:39: in function <...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:36>
[string "=[C]"]: in function `Show'
[string "@Bagnon\common\Wildpants\api\frames.lua"]:85: in function `Show'
[string "@Bagnon\common\Wildpants\api\frames.lua"]:77: in function <Bagnon\common\Wildpants\api\frames.lua:76>
[string "=(tail call)"]: ?
[string "@Bagnon\common\Wildpants\features\autoDisplay.lua"]:146: in function `ToggleBackpack'
[string "TOGGLEBACKPACK"]:1: in function <[string "TOGGLEBACKPACK"]:1>

Locals:
self = <unnamed> {
 0 = <userdata>
 frame = BagnonInventoryFrame1 {
 }
 Text = <unnamed> {
 }
}
v = ""
(for index) = 1
(for limit) = nil
(for step) = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "'for' limit must be a number"
```

**Comment by alphabitnz** [comment]
Same on Wrath Classic:

```
10x ...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:45: attempt to call field 'GetBackpackCurrencyInfo' (a nil value)
[string "@Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:45: in function `Update'
[string "@Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:39: in function <...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:36>
[string "=[C]"]: in function `Show'
[string "@Bagnon\common\Wildpants\api\frames.lua"]:85: in function `Show'
[string "@Bagnon\common\Wildpants\api\frames.lua"]:77: in function <Bagnon\common\Wildpants\api\frames.lua:76>
[string "=(tail call)"]: ?
[string "@Bagnon\common\Wildpants\features\autoDisplay.lua"]:146: in function `ToggleBackpack'
[string "TOGGLEBACKPACK"]:1: in function <[string "TOGGLEBACKPACK"]:1>

Locals:
self = <unnamed> {
 0 = <userdata>
 frame = BagnonInventoryFrame1 {
 }
 Text = <unnamed> {
 }
}
v = ""
(for index) = 1
(for limit) = 3
(for step) = 1
i = 1
(*temporary) = nil
(*temporary) = 1
(*temporary) = "attempt to call field 'GetBackpackCurrencyInfo' (a nil value)"
```

**Comment by Elvara26** [comment]
> Same on Wrath Classic:
> 
> ```
> 10x ...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:45: attempt to call field 'GetBackpackCurrencyInfo' (a nil value)
> [string "@Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:45: in function `Update'
> [string "@Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:39: in function <...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:36>
> [string "=[C]"]: in function `Show'
> [string "@Bagnon\common\Wildpants\api\frames.lua"]:85: in function `Show'
> [string "@Bagnon\common\Wildpants\api\frames.lua"]:77: in function <Bagnon\common\Wildpants\api\frames.lua:76>
> [string "=(tail call)"]: ?
> [string "@Bagnon\common\Wildpants\features\autoDisplay.lua"]:146: in function `ToggleBackpack'
> [string "TOGGLEBACKPACK"]:1: in function <[string "TOGGLEBACKPACK"]:1>
> 
> Locals:
> self = <unnamed> {
>  0 = <userdata>
>  frame = BagnonInventoryFrame1 {
>  }
>  Text = <unnamed> {
>  }
> }
> v = ""
> (for index) = 1
> (for limit) = 3
> (for step) = 1
> i = 1
> (*temporary) = nil
> (*temporary) = 1
> (*temporary) = "attempt to call field 'GetBackpackCurrencyInfo' (a nil value)"
> ```

I'm having the same problem even after install and reinstall, I deleted the saved variables for it and it works again
