### ISSUE TITLE
WotLK Game Version 3.4.0.45613: After patch bag & bank do not open

### ISSUE THREAD

**Issue by Hondu128** [tullamods/Bagnon#1424]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 3.4.0
 - Server patch: Version 3.4.0.45613
 **Have you read the changelog? (please don't waste our time)**
 Mark if read.

**Describe the bug**

After patch bag & mailbox & bank interactions do not open bags

**Expected behaviour**
All bags consolidated view

**Comment by arx-nday** [comment]
Message: ...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:45: attempt to call field 'GetBackpackCurrencyInfo' (a nil value)
Time: Fri Sep 23 12:06:46 2022
Count: 1
Stack: ...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:45: attempt to call field 'GetBackpackCurrencyInfo' (a nil value)
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:45: in function `Update'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:39: in function `RegisterEvents'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:25: in function <...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:13>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Bagnon\addons\main\frame.lua"]:319: in function `PlaceCurrency'
[string "@Interface\AddOns\Bagnon\addons\main\frame.lua"]:97: in function `Layout'
[string "@Interface\AddOns\Bagnon\addons\main\frame.lua"]:66: in function `Update'
[string "@Interface\AddOns\Bagnon\addons\main\frame.lua"]:56: in function `RegisterSignals'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\frame.lua"]:19: in function <...ace\AddOns\Bagnon\common\Wildpants\classes\frame.lua:17>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\inventory.lua"]:21: in function <...AddOns\Bagnon\common\Wildpants\classes\inventory.lua:20>
[string "=[C]"]: in function `Show'
[string "@Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua"]:85: in function `Show'
[string "@Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua"]:77: in function `Toggle'
[string "@Interface\AddOns\Bagnon\common\Wildpants\features\autoDisplay.lua"]:184: in function `ToggleAllBags'
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Locals: self = <unnamed> {
 0 = <userdata>
 frame = BagnonInventoryFrame1 {
 }
 Text = <unnamed> {
 }
}
v = ""
(for index) = 1
(for limit) = 3
(for step) = 1
i = 1
(*temporary) = nil
(*temporary) = 1
(*temporary) = "attempt to call field 'GetBackpackCurrencyInfo' (a nil value)"
Message: ...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:45: attempt to call field 'GetBackpackCurrencyInfo' (a nil value)
Time: Fri Sep 23 12:06:47 2022
Count: 1
Stack: ...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:45: attempt to call field 'GetBackpackCurrencyInfo' (a nil value)
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:45: in function `Update'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:39: in function `RegisterEvents'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:25: in function <...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:13>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Bagnon\addons\main\frame.lua"]:319: in function `PlaceCurrency'
[string "@Interface\AddOns\Bagnon\addons\main\frame.lua"]:97: in function `?'
[string "@Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `SendMessage'
[string "@Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua"]:83: in function `SendSignal'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\base.lua"]:24: in function `SendFrameSignal'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\itemGroup.lua"]:177: in function `func'
[string "@Interface\AddOns\Bagnon\common\Wildpants\libs\MutexDelay-1.0\MutexDelay-1.0.lua"]:36: in function <...mon\Wildpants\libs\MutexDelay-1.0\MutexDelay-1.0.lua:30>

Locals: <none>
