### ISSUE TITLE
Bags not opening

### ISSUE THREAD

**Issue by KarlGrear** [tullamods/Bagnon#1425]
**Running Software (issues missing this information will be deleted):**
 - Addon version: Bagnon-9.2.3-3.4.0.zip
 - Server patch: 3.4.0.45613

 **Have you read the changelog? (please don't waste our time)**
Yes

**Describe the bug**
Bags not opening

**To Reproduce**
Steps to reproduce the behaviour:
1. Type the B key
2. or
3. Click on a Bag

**Expected behaviour**
Bags should open

**Screenshots**
None

**Error Logs**
Date: 2022-09-20 08:46:52
ID: 1
Error occured in: Global
Count: 1
Message: ...\Bagnon\common\Wildpants\classes\currencyDisplay.lua line 45:
   attempt to call field 'GetBackpackCurrencyInfo' (a nil value)
Debug:
   [string "@Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:45: Update()
   [string "@Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:39: RegisterEvents()
   [string "@Bagnon\common\Wildpants\classes\currencyDisplay.lua"]:25:
      ...\Bagnon\common\Wildpants\classes\currencyDisplay.lua:13
   [string "=(tail call)"]: ?
   [string "@Bagnon\addons\main\frame.lua"]:319: PlaceCurrency()
   [string "@Bagnon\addons\main\frame.lua"]:97: Layout()
   [string "@Bagnon\addons\main\frame.lua"]:66: Update()
   [string "@Bagnon\addons\main\frame.lua"]:56: RegisterSignals()
   [string "@Bagnon\common\Wildpants\classes\frame.lua"]:19:
      ...ace\AddOns\Bagnon\common\Wildpants\classes\frame.lua:17
   [string "=(tail call)"]: ?
   [string "@Bagnon\common\Wildpants\classes\inventory.lua"]:21:
      ...AddOns\Bagnon\common\Wildpants\classes\inventory.lua:20
   [string "=[C]"]: Show()
   [string "@Bagnon\common\Wildpants\api\frames.lua"]:85: Show()
   [string "@Bagnon\common\Wildpants\api\frames.lua"]:77:
      ...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:76
   [string "=(tail call)"]: ?
   [string "@Bagnon\common\Wildpants\features\autoDisplay.lua"]:146: ToggleBackpack()
   [string "TOGGLEBACKPACK"]:1:
      [string "TOGGLEBACKPACK"]:1
Locals:
self = <unnamed> {
 0 = <userdata>
 frame = BagnonInventoryFrame1 {
 }
 Text = <unnamed> {
 }
}
v = ""
(for index) = 1
(for limit) = 3
(for step) = 1
i = 1
(*temporary) = nil
(*temporary) = 1
(*temporary) = "attempt to call field 'GetBackpackCurrencyInfo' (a nil value)"

**Comment by Peiling-Ding** [comment]
Met the same issue today.

**Comment by Facett** [comment]
I also can't get my bags to open anymore

**Comment by Gavilaan** [comment]
Same here

**Comment by crypticasden** [comment]
Same issue as well

**Comment by albanianmage** [comment]
I am also having the same issue. been happening for the past week. bags wont open. I would close all my other addons and just have bagnon on. still doesnt work

**Comment by arx-nday** [comment]
**Easiest solution so far!!!!**
Right-click in curseforge addon on bagnon and select **release type: release**
