### ISSUE TITLE
BAGNON NOT LOADING ON ON DRAGONFLIGHT BETA

### ISSUE THREAD

**Issue by lloskka** [tullamods/Bagnon#1435]
**Running Software (issues missing this information will be deleted):**

 - Addon version: 10.0.1 (beta)
 - Server patch: 10.0.2.45969

 **Have you read the changelog? (please don't waste our time)**
 Mark if read.  

> Fixed some bugs with vault and guild bank.
> Fixed issue with databroker positioning in vault.
> Fixed some technical issues with the configuration menu.

**√**

**Describe the bug**

Addon is not loading properly API.lua:20 attempt to call 'GetContainerNumSlots' ( a nil value )

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to https://www.curseforge.com/wow/addons/bagnon/files/4019115

2. Click on https://www.curseforge.com/wow/addons/bagnon/download/4019115

3. Decompress file on \World of Warcraft\_beta_\Interface\AddOns

4. Disable All other Addons.

**Expected behaviour**

Properly use bagnon with all its options, as like previus versions in Shadowlands.

**Screenshots**

![WoWScrnShot_100622_101854](https://user-images.githubusercontent.com/20574132/194261731-939144db-3f79-4d56-af95-17422cfde866.jpg)

**Error Logs**

> ...erface/AddOns/Bagnon/common/Wildpants/api/events.lua:91: attempt to call global 'GetContainerNumSlots' (a nil value)
> [string "@Interface/AddOns/Bagnon/common/Wildpants/libs/WildAddon-1.0/WildAddon-1.0.lua"]:56: in function <...ommon/Wildpants/libs/WildAddon-1.0/WildAddon-1.0.lua:53>
> [string "=[C]"]: ?
> [string "@Interface/AddOns/Bagnon/common/Wildpants/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:29: in function <...nts/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
> [string "@Interface/AddOns/Bagnon/common/Wildpants/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:64: in function `Fire'
> [string "@Interface/AddOns/Bagnon/common/Wildpants/libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <.../common/Wildpants/libs/AceEvent-3.0/AceEvent-3.0.lua:119>
> [string "=[C]"]: in function `LoadAddOn'
> [string "@Interface/FrameXML/UIParent.lua"]:534: in function `UIParentLoadAddOn'
> [string "@Interface/FrameXML/UIParent.lua"]:669: in function `TimeManager_LoadUI'
> [string "@Interface/FrameXML/UIParent.lua"]:1473: in function <Interface/FrameXML/UIParent.lua:1354>

> Interface/AddOns/BagBrother/API.lua:20: attempt to call global 'GetContainerNumSlots' (a nil value)

> ...erface/AddOns/Bagnon/common/Wildpants/api/events.lua:91: attempt to call global 'GetContainerNumSlots' (a nil value)

>  Interface/AddOns/Bagnon/addons/main/brokerPlugin.lua:39: attempt to call global 'GetContainerNumFreeSlots' (a nil value)

**Comment by lloskka** [comment]
Hello.

Question, what is the solution to this issue? its is closed by you 7h ago

You have no pull requests nor new versions, why closing it tho? why paying patreon jailborc then!?

Have a nice week!

Cheers.

**Comment by katur239** [comment]
Still happening after todays release. Seems none of the new C_Container namespace have been updated.

**Comment by Jaliborc** [comment]
Ofc, it doesn't run on beta.

**Comment by katur239** [comment]
Ah That would makes sense then.

Files on Curseforge marked as Release for Game version 10.0.2 implies that it is supposed to be working on beta.  Sorry about that.
