### ISSUE TITLE
CF source link broken? Can't find updates here

### ISSUE THREAD

**Issue by Voxxel** [tullamods/Bagnon#1438]
CurseForge Bagnon page listed the latest Bagnon version as 

`10.0.1-10.0.2.zip | Uploaded 3 days ago | Game Version 10.0.2 | MD5 d6f86bb4a085cdc8bcc8b92c27f873b9`

Meanwhile the latest version here on GitHub is labeled 9.2.4. - 06a31b8 and it is 12 days old.

 Can I find the 3 days old latest version somewhere around here? Since the 'Source' tab on CurseForge page leads to 404.

**Comment by Jaliborc** [comment]
CurseForge is always the correct one

**Comment by Voxxel** [comment]
Ok, but why I can't open the link of the 'Source' tab on CurseForge?

**Comment by Jaliborc** [comment]
Check 'Files' tab

**Comment by Voxxel** [comment]
:D 
I understand you're trying to make replies and stuff compatible, understandable with casuals like me (essentially retard-proofing) but I still wonder why I can't find github updates through the 'Source' tab link (with a browser) that CF doesn't have on 'Files' tab. I badly need those working updates that are available only on Github and not on CF yet.
