### ISSUE TITLE
Inventory not working on ONE of many characters 

### ISSUE THREAD

**Issue by mibe549** [tullamods/Bagnon#1439]
**Running Software (issues missing this information will be deleted):**
 - Addon version: WOTLK Classic
 - Server patch: [e.g. Build 8.0.1.27178] 3.4.0

 **Have you read the changelog? (please don't waste our time)**
 Mark if read.

**Describe the bug**
Bagnon does not open my bags on only ONE character. On every other character it works fine, only on my warrior it does nothing wenn i press B. I also cant open the bags manually by klicking on the actionbar bag icons (they do not highlight so the inventory isnt just invisible). Disabling bagnon will make my inventory show up again wenn pressing B or klicking.
I reinstalled it multiple times now plus "deleted" my warrior in bagnon on my alt character. 
**To Reproduce**

**Expected behaviour**

**Screenshots**

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the message with `ID: 1` (labelled 1/X). This is generally NOT the message that the window shows by default.

**Additional context**

**Comment by rivitor** [comment]
Message: ...\AddOns\Bagnon\common\Wildpants\classes\currency.lua:23: attempt to concatenate field 'iconFileID' (a nil value)
Time: Mon Oct 10 12:31:21 2022
Count: 166
Stack: ...\AddOns\Bagnon\common\Wildpants\classes\currency.lua:23: attempt to concatenate field 'iconFileID' (a nil value)
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\currency.lua"]:23: in function `Set'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\currencyTracker.lua"]:64: in function `Layout'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\currencyTracker.lua"]:42: in function <...\Bagnon\common\Wildpants\classes\currencyTracker.lua:39>
[string "=[C]"]: in function `Show'
[string "@Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua"]:85: in function `Show'
[string "@Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua"]:77: in function <...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:76>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Bagnon\common\Wildpants\features\autoDisplay.lua"]:82: in function `ToggleAllBags'
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Locals: self = <unnamed> {
 0 = <userdata>
 frame = BagnonInventoryFrame1 {
 }
}
data = "Honor Points"
(*temporary) = <function> defined =[C]:-1
(*temporary) = <unnamed> {
 0 = <userdata>
 frame = BagnonInventoryFrame1 {
 }
}
(*temporary) = nil
(*temporary) = "  "
(*temporary) = "attempt to concatenate field 'iconFileID' (a nil value)"
I have the same problem only 1 of my character doesn't open bagnon

**Comment by Jaliborc** [comment]
> **Running Software (issues missing this information will be deleted):**
> 
>     * Addon version: WOTLK Classic
> 
>     * Server patch: [e.g. Build 8.0.1.27178] 3.4.0
> 
> 
> **Have you read the changelog? (please don't waste our time)** Mark if read.
> 
> **Describe the bug** Bagnon does not open my bags on only ONE character. On every other character it works fine, only on my warrior it does nothing wenn i press B. I also cant open the bags manually by klicking on the actionbar bag icons (they do not highlight so the inventory isnt just invisible). Disabling bagnon will make my inventory show up again wenn pressing B or klicking. I reinstalled it multiple times now plus "deleted" my warrior in bagnon on my alt character. **To Reproduce**
> 
> **Expected behaviour** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Error Logs** Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the message with `ID: 1` (labelled 1/X). This is generally NOT the message that the window shows by default.
> 
> **Additional context** Add any other context about the problem here.

I'll need a bug report like your friend there did. You might have the same problem, might not.

**Comment by Jaliborc** [comment]
> Message: ...\AddOns\Bagnon\common\Wildpants\classes\currency.lua:23: attempt to concatenate field 'iconFileID' (a nil value) Time: Mon Oct 10 12:31:21 2022 Count: 166 Stack: ...\AddOns\Bagnon\common\Wildpants\classes\currency.lua:23: attempt to concatenate field 'iconFileID' (a nil value) [string "@interface\AddOns\Bagnon\common\Wildpants\classes\currency.lua"]:23: in function `Set' [string "@Interface\AddOns\Bagnon\common\Wildpants\classes\currencyTracker.lua"]:64: in function `Layout' [string "@interface\AddOns\Bagnon\common\Wildpants\classes\currencyTracker.lua"]:42: in function <...\Bagnon\common\Wildpants\classes\currencyTracker.lua:39> [string "=[C]"]: in function `Show' [string "@Interface\AddOns\Bagnon\common\Wildpants\api\frames.lua"]:85: in function `Show' [string "@interface\AddOns\Bagnon\common\Wildpants\api\frames.lua"]:77: in function <...erface\AddOns\Bagnon\common\Wildpants\api\frames.lua:76> [string "=(tail call)"]: ? [string "@interface\AddOns\Bagnon\common\Wildpants\features\autoDisplay.lua"]:82: in function `ToggleAllBags' [string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>
> 
> Locals: self = { 0 = frame = BagnonInventoryFrame1 { } } data = "Honor Points" (*temporary) = defined =[C]:-1 (*temporary) = { 0 = frame = BagnonInventoryFrame1 { } } (*temporary) = nil (*temporary) = " " (*temporary) = "attempt to concatenate field 'iconFileID' (a nil value)" I have the same problem only 1 of my character doesn't open bagnon

Can you tell me which currencies you're tracking on that character and not on others? Seems like 1 specific currency is bugging out.

**Comment by Spillmaker** [comment]
Honor points are not item-based currencies and needs different logic to display their icons. Use extraCurrencyType to detect that

**Comment by Jaliborc** [comment]
I found no mention of extraCurrencyType anywhere in blizzards API or code. What are you referring to?

**Comment by Spillmaker** [comment]
Its a field which no longer exists. disregard that.

Going trough my own code it looks like the issue in this case is the use of the retail command C_CurrencyInfo.GetCurrencyListInfo where you  have a paramter called iconFileID, but with WOTLK the command GetCurrencyListInfo is used with the parameter "icon"

The honor points still need somewhat different logic on the scaling since they are based on different aspect ratio images than other currencies.

**Comment by Jaliborc** [comment]
Had to buy a lvlboost to test it out in wrath servers, but fixed
