### ISSUE TITLE
Newest Classic build tooltip is transparent

### ISSUE THREAD

**Issue by Trozzzul** [tullamods/Bagnon#1442]
**Running Software (issues missing this information will be deleted):**
 - Addon version: Latest, Today
 - Server patch: [e.g. Build 8.0.1.27178]

 **Have you read the changelog? (please don't waste our time)**
Read. nothing described my issue.

**Describe the bug**
If it helps, i have two monitors and now the tooltip goes further to the right where that monitor is and stuff gets cutoff:
but basically as the image shows its some kind of graphical error
i dont do anything special with bagnon i just simply installed todays build and this happened (if it helps some of my settings were reset like the colums, and showing bags/keys)
i have tried deleting the addon (via curseforge, idk if that deletes every variable saved) and installing the last dated build
![dfgdfsdfgfg](https://user-images.githubusercontent.com/116462044/197360544-35f6a61a-ae18-4cb5-a744-e4a71ea11c84.png)

**To Reproduce**
Steps to reproduce the behaviour:
Open Bagnon basically.

**Expected behaviour**

**Screenshots**
i edited two together so that i can show you it cutting off, assuming thats because of my monitor
left is cut off, right is just when i move further to the left and showing a item.
**Error Logs**
nothing pops up

**Comment by Trozzzul** [comment]
Ugh, i swear i went through my list of addons and double checked to see if something else was the issue. but it ended up being TipTac causing this issue with Bagnon, should i leave this up anyways for the TipTac collide?

**Comment by JosefBud** [comment]
I'm having the same issue and also use TipTac (which hasn't updated since early September). For some reason downgrading Bagnon to the previous version doesn't even fix the issue, which is probably the worst part for me.

**Comment by JosefBud** [comment]
@Jaliborc why is this closed? The issue may only happen for TipTac users but it is caused by the latest update to Bagnon.

**Comment by Jaliborc** [comment]
Because its a TipTac issue

**Comment by JosefBud** [comment]
It's an issue happening to TipTac users, caused by Bagnon. If I disable Bagnon, the issue goes away. If I use another bag addon, the issue goes away. Bagnon seems to be the cause of the issue here.

**Comment by Seventii** [comment]
yea I have this problem too after install the last version of Bagnon

**Comment by Dranni21312** [comment]
I can confirm, this is only happening with Bagnon installed with Tiptac and only after a recent update of Bagnon.

**Comment by Dranni21312** [comment]
Moreover, going back release by release, I can confirm that 9.2.2 is the most recent version where this bug is not present. I will stick to that version until a proper fix is introduced in either project.
