### ISSUE TITLE
Bagnon doesn't work for one specific character?

### ISSUE THREAD

**Issue by DynaLight** [tullamods/Bagnon#1451]
**Running Software (issues missing this information will be deleted):**
 - Addon version: Bagnon-10.0.3-3.4.0.
 - Server patch: 3.4.0

 **Have you read the changelog? (please don't waste our time)**
 Mark if read. : Yes

**Describe the bug**

For an unknown reason, one of my toons is unable to use bagnon to check its bank, other toons bank, or the guild bank. Every other toon is able to use it no issue but when this particular toon tries, it just shows that the bank is empty and doesn't show my total gold.

**To Reproduce**
Steps to reproduce the behaviour:

There is no way to reproduce this.

**Expected behaviour**
When I left click on the icon on the bottom left I expected to see my bank inventory

**Screenshots**
This is what my main toon bagnon looks like vvv
![image](https://user-images.githubusercontent.com/116735934/198045877-3181b954-0d74-4d9f-a55c-77b62cb37b6a.png)

This is what all my other alts bagnon looks like vvv
![image](https://user-images.githubusercontent.com/116735934/198049193-158dc657-f02b-4f40-b249-4c727682629e.png)

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the message with `ID: 1` (labelled 1/X). This is generally NOT the message that the window shows by default.

No messages appeared

**Additional context**

This has been happening since the start of WOTLK Classic
Also interesting thing to note, for some reason it keeps saying that my main toon only has 2g so it seems to have updated once way back when

**Comment by Jaliborc** [comment]
you disabled bagbrother
