### ISSUE TITLE
1.0.0V Error

### ISSUE THREAD

**Issue by zokabazoka85** [tullamods/Bagnon#1455]
35x ...rface/AddOns/Bagnon/common/Wildpants/classes/bag.lua:188: bad argument #1 to 'GetBagSlotFlag' (outside of expected range 0 to 4294967295 - Usage: local isSet = C_Container.GetBagSlotFlag(bagIndex, flag))
[string "=[C]"]: in function `GetBagSlotFlag'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bag.lua"]:188: in function `Update'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bag.lua"]:124: in function `RegisterEvents'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bag.lua"]:73: in function <...rface/AddOns/Bagnon/common/Wildpants/classes/bag.lua:18>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bagGroup.lua"]:17: in function <.../AddOns/Bagnon/common/Wildpants/classes/bagGroup.lua:11>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:285: in function `CreateBagGroup'
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:265: in function `PlaceBagGroup'
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:91: in function `Layout'
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:66: in function `Update'
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:56: in function `RegisterSignals'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/frame.lua"]:19: in function <...ace/AddOns/Bagnon/common/Wildpants/classes/frame.lua:17>
[string "=[C]"]: in function `Show'
[string "@Interface/AddOns/Bagnon/common/Wildpants/api/frames.lua"]:85: in function `Show'
[string "@Interface/AddOns/Bagnon/common/Wildpants/api/frames.lua"]:77: in function <...erface/AddOns/Bagnon/common/Wildpants/api/frames.lua:76>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Bagnon/common/Wildpants/features/autoDisplay.lua"]:82: in function `ToggleBag'
[string "@Interface/FrameXML/MainMenuBarBagButtons.lua"]:76: in function <Interface/FrameXML/MainMenuBarBagButtons.lua:66>
[string "=[C]"]: ?

Locals:
(*temporary) = -1
(*temporary) = 2
(*temporary) = "outside of expected range 0 to 4294967295 - Usage: local isSet = C_Container.GetBagSlotFlag(bagIndex, flag)"

**Comment by neoxz04** [comment]
I got the same error after clicking the Bag Slots icon when visiting my bank.

**Comment by JohnnyType2** [comment]
same here
