### ISSUE TITLE
Bank broken and will not open after wow 10.0.0 update. 

### ISSUE THREAD

**Issue by JohnnyType2** [tullamods/Bagnon#1456]
Bank will not open at all, even though bags are opening on character.

It doesnt error or present anything just doesnt open or happen. 

Disabling the addon fixes the issue.

**Comment by 0bheron** [comment]
Exit WoW
Got to: [Drive letter]:\World of Warcraft\_retail_\WTF\Account\[KHAAN]\SavedVariables
Delete all Bagnon entries
Relaunch game and enable all Bagnon addons, and it will work like a charm

**Comment by TTigress** [comment]
Having the same issue. Tried the proposed fix, couldn't locate any Bagnon entries under the proposed file path (actually had no entries at all for saved variables). Ended up deleting and reinstalling all addons, including Bagnon. At first that seemed to fix the no bags showing at the bank, but after a few minutes I noticed I no longer had a bag slots bar. And after a few more minutes bags at the bank once again stopped showing and I am back to square one with the problem.

BugSack addon is telling me there's definitely an issue that keeps happening - the error text I receive is 

196x ...rface/AddOns/Bagnon/common/Wildpants/classes/bag.lua:188: bad argument #1 to 'GetBagSlotFlag' (outside of expected range 0 to 4294967295 - Usage: local isSet = C_Container.GetBagSlotFlag(bagIndex, flag))
[string "=[C]"]: in function `GetBagSlotFlag'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bag.lua"]:188: in function `Update'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bag.lua"]:124: in function `RegisterEvents'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bag.lua"]:73: in function <...rface/AddOns/Bagnon/common/Wildpants/classes/bag.lua:18>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bagGroup.lua"]:17: in function <.../AddOns/Bagnon/common/Wildpants/classes/bagGroup.lua:11>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:285: in function `CreateBagGroup'
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:265: in function `PlaceBagGroup'
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:91: in function `?'
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:119: in function <...nts/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:29: in function <...nts/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:64: in function `SendMessage'
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/WildAddon-1.0-1/WildAddon-1.0.lua"]:83: in function `SendSignal'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/base.lua"]:24: in function `SendFrameSignal'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bagToggle.lua"]:40: in function <...AddOns/Bagnon/common/Wildpants/classes/bagToggle.lua:35>

**Comment by rorschtnt** [comment]
> Exit WoW Got to: [Drive letter]:\World of Warcraft_retail_\WTF\Account[YOUR ACCOUNT NAME]\SavedVariables Delete all Bagnon entries Relaunch game and enable all Bagnon addons, and it will work like a charm

This works but I couldn't see my bank bags bar. Then when I /reloadUI, the bank stops showing up again. Same issue with guild bank. Just doesn't open window.

**Comment by JohnnyType2** [comment]
This fix worked for me, thanks. If you can't find the path just search for
Bagnon on the file name. The file extension is .lua

Good luck

**Comment by veljkovicm** [comment]
> This works but I couldn't see my bank bags bar. 

Bagnon settings -> Frame settings -> Inventory -> Databroker Plugins

Enabled this and the icon that lets you open the bank showed up.

**Comment by Elrohir3** [comment]
I am having the same problem, and there are no Bagnon related entries in SavedVariables.

Also, when I enable "separate reagents tab," only the reagents tab shows -- no bag bar visible to view the actual bank.

**Comment by ksaper** [comment]
Deleting Saved Variables in the WTF/Account folder worked for me

**Comment by gremlincathe** [comment]
> Exit WoW Got to: [Drive letter]:\World of Warcraft_retail_\WTF\Account[YOUR ACCOUNT NAME]\SavedVariables Delete all Bagnon entries Relaunch game and enable all Bagnon addons, and it will work like a charm

This worked perfectly!! Thank you

**Comment by SnowRevol** [comment]
didn't realy help me finding them to delete, but anyone unable to find thier wtf saved variables to delete, you likely also have/had multiple accounts, and they are saved under the individual accounts wtf folders.

**Comment by JohnnyType2** [comment]
Delete for each account character. Its a folder with a 10+ digit number
name.

It did fix mine.

**Comment by godlike64** [comment]
The proposed fix of removing the Bagnon files under SavedVariables does not work. It worked on my main but when I logged with an alt I still had the issue.

Also, these files are under the main Account folder and not each individual character, at least for me.
