### ISSUE TITLE
Inventory doesn't open

### ISSUE THREAD

**Issue by samscats** [tullamods/Bagnon#1460]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 10.0.3-9.2.7
 - Server patch: 10.0.0.46340

 **Have you read the changelog? (please don't waste our time)**
 Mark if read. Yes

**Describe the bug**
Whenever I open my inventory what is displayed isn't bagnon.  It is wow's bags.  When I open my Bank, both bagnon opens for inventory and bank as well as the wow version opens for each.  

**To Reproduce**
Steps to reproduce the behaviour:
1. I have restarted the game. 
2. I have tried the same steps to open my inventory to show bagnon

**Expected behaviour**
I would think that bagnon would  open my inventory like it does when I go to my bank.

**Screenshots**
![wow](https://user-images.githubusercontent.com/116861602/198500868-6d24f349-6aff-4906-9dcd-73eac2b9e70f.jpg)
![bagnon   wow](https://user-images.githubusercontent.com/116861602/198500867-87009989-1781-4418-bf82-c6a1669567c7.jpg)

**Error Logs**
No error logs

**Additional context**
I have tried completely uninstalling and reinstalling the addon as well as deleting all addons.  Also I have tried removing the wtf & cache folders.

**Comment by Alyy30** [comment]
Did you happen to find a fix for this? I still have the blizzard bags popping up as well and it's terrible!
