### ISSUE TITLE
Unable to use dropdown menu for bags in Bank

### ISSUE THREAD

**Issue by Epidemedabear** [tullamods/Bagnon#1461]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 10.0.3-10.0.2
 - Server patch: 10.0.0.46340

 **Have you read the changelog? (please don't waste our time)**
 Mark if read. Yes

**Describe the bug**
When left clicking the bag icon in the Bank to display the bags nothing happens

**Error Logs**
20x ...rface/AddOns/Bagnon/common/Wildpants/classes/bag.lua:188: bad argument #1 to 'GetBagSlotFlag' (outside of expected range 0 to 4294967295 - Usage: local isSet = C_Container.GetBagSlotFlag(bagIndex, flag))
[string "=[C]"]: in function `GetBagSlotFlag'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bag.lua"]:188: in function `Update'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bag.lua"]:124: in function `RegisterEvents'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bag.lua"]:73: in function <...rface/AddOns/Bagnon/common/Wildpants/classes/bag.lua:18>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bagGroup.lua"]:17: in function <.../AddOns/Bagnon/common/Wildpants/classes/bagGroup.lua:11>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:285: in function `CreateBagGroup'
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:265: in function `PlaceBagGroup'
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:91: in function `Layout'
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:66: in function `Update'
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:56: in function `RegisterSignals'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/frame.lua"]:19: in function <...ace/AddOns/Bagnon/common/Wildpants/classes/frame.lua:17>
[string "=[C]"]: in function `Show'
[string "@Interface/AddOns/Bagnon/common/Wildpants/api/frames.lua"]:85: in function `Show'
[string "@Interface/AddOns/Bagnon/common/Wildpants/features/autoDisplay.lua"]:47: in function <...Ons/Bagnon/common/Wildpants/features/autoDisplay.lua:46>
[string "@Interface/AddOns/Bagnon/common/Wildpants/features/autoDisplay.lua"]:82: in function `ShowFrame'
[string "@Interface/FrameXML/PlayerInteractionFrameManager.lua"]:215: in function <Interface/FrameXML/PlayerInteractionFrameManager.lua:212>

Locals:
(*temporary) = -1
(*temporary) = 2
(*temporary) = "outside of expected range 0 to 4294967295 - Usage: local isSet = C_Container.GetBagSlotFlag(bagIndex, flag)"

**Comment by alphabitnz** [comment]
My bank is also not displaying some bank bag/slots, so this issue prevents accessing the bags display to re-enable that bag's visibility.

**Comment by AtreyuGreen** [comment]
I've found the error on Bagnon/common/Wildpants/classes/bag.lua. In the function Bag:Update() is using:

_**local active = C_Container and (id > NUM_BAG_SLOTS and C_Container.GetBankBagSlotFlag(id - NUM_BAG_SLOTS, 2^i) or C_Container.GetBagSlotFlag(id, 2^i)) or GetBagSlotFlag and (id > NUM_BAG_SLOTS and GetBankBagSlotFlag(id - NUM_BAG_SLOTS, i) or GetBagSlotFlag(id, i))**_

The issue is with **GetBankBagSlotFlag** I dont know if Blizzard disabled this function from C_Container. My solution meanwhile is comment this line and setting active as false

--local active = C_Container and (id > NUM_BAG_SLOTS and C_Container.GetBankBagSlotFlag(id - NUM_BAG_SLOTS, 2^i) or C_Container.GetBagSlotFlag(id, 2^i)) or GetBagSlotFlag and (id > NUM_BAG_SLOTS and GetBankBagSlotFlag(id - NUM_BAG_SLOTS, i) or GetBagSlotFlag(id, i))
local active = false

**Comment by mrlinuxdude** [comment]
I cannot use my bank either no bag is shown

**Comment by Sarkli** [comment]
Same

4x ...rface/AddOns/Bagnon/common/Wildpants/classes/bag.lua:188: bad argument #1 to 'GetBagSlotFlag' (outside of expected range 0 to 4294967295 - Usage: local isSet = C_Container.GetBagSlotFlag(bagIndex, flag))
[string "=[C]"]: in function `GetBagSlotFlag'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bag.lua"]:188: in function `Update'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bag.lua"]:124: in function `RegisterEvents'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bag.lua"]:73: in function <...rface/AddOns/Bagnon/common/Wildpants/classes/bag.lua:18>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bagGroup.lua"]:17: in function <.../AddOns/Bagnon/common/Wildpants/classes/bagGroup.lua:11>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:285: in function `CreateBagGroup'
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:265: in function `PlaceBagGroup'
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:91: in function `Layout'
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:66: in function `Update'
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:56: in function `RegisterSignals'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/frame.lua"]:19: in function <...ace/AddOns/Bagnon/common/Wildpants/classes/frame.lua:17>
[string "=[C]"]: in function `Show'
[string "@Interface/AddOns/Bagnon/common/Wildpants/api/frames.lua"]:85: in function `Show'
[string "@Interface/AddOns/Bagnon/common/Wildpants/features/autoDisplay.lua"]:47: in function <...Ons/Bagnon/common/Wildpants/features/autoDisplay.lua:46>
[string "@Interface/AddOns/Bagnon/common/Wildpants/features/autoDisplay.lua"]:82: in function `ShowFrame'
[string "@Interface/FrameXML/PlayerInteractionFrameManager.lua"]:215: in function <Interface/FrameXML/PlayerInteractionFrameManager.lua:212>

Locals:
(*temporary) = -1
(*temporary) = 2
(*temporary) = "outside of expected range 0 to 4294967295 - Usage: local isSet = C_Container.GetBagSlotFlag(bagIndex, flag)"

**Comment by Exalus** [comment]
I am having this issue as well. Bank wouldn't show up at all but deleting the saved bagnon variables worked to get it back but when I left click to "show the bags display" nothing happens. I do not even get a error popup.

**Comment by alphabitnz** [comment]
> The issue is with **GetBankBagSlotFlag** I dont know if Blizzard disabled this function from C_Container. My solution meanwhile is comment this line and setting active as false
> 
> --local active = C_Container and (id > NUM_BAG_SLOTS and C_Container.GetBankBagSlotFlag(id - NUM_BAG_SLOTS, 2^i) or C_Container.GetBagSlotFlag(id, 2^i)) or GetBagSlotFlag and (id > NUM_BAG_SLOTS and GetBankBagSlotFlag(id - NUM_BAG_SLOTS, i) or GetBagSlotFlag(id, i)) local active = false

Can confirm this works to get bag display showing again
Just be sure to comment out both lines 188 and 189 in bag.lua followed by the `local active = false`

**Comment by Salmanius** [comment]
After a bit more messing, I think I have a solid fix. I pull requested this to the authors but until they accept or implement it themselves another way, you can see the changes necessary here: 
https://github.com/tullamods/Wildpants/pull/85
