### ISSUE TITLE
Error when deposit anima

### ISSUE THREAD

**Issue by Scaver** [tullamods/Bagnon#1462]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 10.0.3-10.0.2
 - Server patch: Build 10.0.0 (46340)

 **Have you read the changelog? (please don't waste our time)**
Yes

**Describe the bug**
I want to deposit anima in my covernants sanctum.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Night Fea sanctum.
2. Go to Tayhad and talk to her
3. Click on 'Deposit'
4. Get error

**Expected behaviour**
The anima should deposit.

**Screenshots**
No

**Error Logs**
1x [ADDON_ACTION_FORBIDDEN] AddOn 'Bagnon' hat versucht die geschützte Funktion 'DepositAnima()' aufzurufen.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `DepositAnima'
[string "@Interface/AddOns/Blizzard_CovenantSanctum/Blizzard_CovenantSanctumUpgrades.lua"]:327: in function `DepositAnima'
[string "*Blizzard_CovenantSanctumUpgrades.xml:594_OnClick"]:1: in function <[string "*Blizzard_CovenantSanctumUpgrades.xml:594_O..."]:1>

**Comment by Silicon14asp** [comment]
Same error as above, so not posting that information, but here is a screen shot of the error 

![bagnon_Anima_Error](https://user-images.githubusercontent.com/116702417/198852702-91971629-4613-4b0a-aca0-010009cedf08.jpg)
