### ISSUE TITLE
Error that prevents opening bank (German Client )

### ISSUE THREAD

**Issue by Lirieth** [tullamods/Bagnon#1464]
Got this here error preventing opening the bank:

Message: ...rface/AddOns/Bagnon/common/Wildpants/classes/bag.lua:188: bad argument #1 to 'GetBagSlotFlag' (outside of expected range 0 to 4294967295 - Usage: local isSet = C_Container.GetBagSlotFlag(bagIndex, flag))
Time: Sun Oct 30 09:10:09 2022
Count: 4
Stack: ...rface/AddOns/Bagnon/common/Wildpants/classes/bag.lua:188: bad argument #1 to 'GetBagSlotFlag' (outside of expected range 0 to 4294967295 - Usage: local isSet = C_Container.GetBagSlotFlag(bagIndex, flag))
[string "=[C]"]: in function `GetBagSlotFlag'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bag.lua"]:188: in function `Update'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bag.lua"]:124: in function <...rface/AddOns/Bagnon/common/Wildpants/classes/bag.lua:123>
[string "=[C]"]: in function `Show'
[string "@Interface/AddOns/Bagnon/common/Wildpants/api/frames.lua"]:85: in function `Show'
[string "@Interface/AddOns/Bagnon/common/Wildpants/features/autoDisplay.lua"]:47: in function <...Ons/Bagnon/common/Wildpants/features/autoDisplay.lua:46>
[string "@Interface/AddOns/Bagnon/common/Wildpants/features/autoDisplay.lua"]:82: in function `ShowFrame'
[string "@Interface/FrameXML/PlayerInteractionFrameManager.lua"]:215: in function <Interface/FrameXML/PlayerInteractionFrameManager.lua:212>

Locals: (*temporary) = -1
(*temporary) = 2
(*temporary) = "outside of expected range 0 to 4294967295 - Usage: local isSet = C_Container.GetBagSlotFlag(bagIndex, flag)"

**Comment by Nillx** [comment]
Its not only the German client, same happens to the EN one. I cant open my bank when Bagnon is enabled. Getting this error

```
8x ...rface/AddOns/Bagnon/common/Wildpants/classes/bag.lua:188: bad argument #1 to 'GetBagSlotFlag' (outside of expected range 0 to 4294967295 - Usage: local isSet = C_Container.GetBagSlotFlag(bagIndex, flag))
[string "=[C]"]: in function `GetBagSlotFlag'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bag.lua"]:188: in function `Update'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bag.lua"]:124: in function `RegisterEvents'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bag.lua"]:73: in function <...rface/AddOns/Bagnon/common/Wildpants/classes/bag.lua:18>
[string "@Interface/AddOns/Bagnon_Masque/Bagnon_Masque.lua"]:63: in function <Interface/AddOns/Bagnon_Masque/Bagnon_Masque.lua:62>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bagGroup.lua"]:17: in function <.../AddOns/Bagnon/common/Wildpants/classes/bagGroup.lua:11>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:285: in function `CreateBagGroup'
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:265: in function `PlaceBagGroup'
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:91: in function `Layout'
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:66: in function `Update'
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:56: in function `RegisterSignals'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/frame.lua"]:19: in function <...ace/AddOns/Bagnon/common/Wildpants/classes/frame.lua:17>
[string "=[C]"]: in function `Show'
[string "@Interface/AddOns/Bagnon/common/Wildpants/api/frames.lua"]:85: in function `Show'
[string "@Interface/AddOns/Bagnon/common/Wildpants/features/autoDisplay.lua"]:47: in function <...Ons/Bagnon/common/Wildpants/features/autoDisplay.lua:46>
[string "@Interface/AddOns/Bagnon/common/Wildpants/features/autoDisplay.lua"]:82: in function `ShowFrame'
[string "@Interface/FrameXML/PlayerInteractionFrameManager.lua"]:215: in function <Interface/FrameXML/PlayerInteractionFrameManager.lua:212>

Locals:
(*temporary) = -1
(*temporary) = 2
(*temporary) = "outside of expected range 0 to 4294967295 - Usage: local isSet = C_Container.GetBagSlotFlag(bagIndex, flag)"
```
