### ISSUE TITLE
Error when trying to display bank bags

### ISSUE THREAD

**Issue by QUYERTH** [tullamods/Bagnon#1465]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 10.0.3
 - Server patch: [e.g. Build 8.0.1.27178]

 **Have you read the changelog? (please don't waste our time)**
 Mark if read. Yes

**Describe the bug**
When selecting "display bags"

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**
Display each of the "bag" types per slot. for selection. Removal or upgrade . Not their contents

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the message with `ID: 1` (labelled 1/X). This is generally NOT the message that the window shows by default.
Swatter error
-----------
Message: ...rface/AddOns/Bagnon/common/Wildpants/classes/bag.lua:188: bad argument #1 to 'GetBagSlotFlag' (outside of expected range 0 to 4294967295 - Usage: local isSet = C_Container.GetBagSlotFlag(bagIndex, flag))
Time: Sun Oct 30 10:58:36 2022
Count: 1
Stack: ...rface/AddOns/Bagnon/common/Wildpants/classes/bag.lua:188: bad argument #1 to 'GetBagSlotFlag' (outside of expected range 0 to 4294967295 - Usage: local isSet = C_Container.GetBagSlotFlag(bagIndex, flag))
[string "=[C]"]: in function `GetBagSlotFlag'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bag.lua"]:188: in function `Update'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bag.lua"]:124: in function `RegisterEvents'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bag.lua"]:73: in function <...rface/AddOns/Bagnon/common/Wildpants/classes/bag.lua:18>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bagGroup.lua"]:17: in function <.../AddOns/Bagnon/common/Wildpants/classes/bagGroup.lua:11>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:285: in function `CreateBagGroup'
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:265: in function `PlaceBagGroup'
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:91: in function `?'
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:119: in function <...nts/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:29: in function <...nts/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:64: in function `SendMessage'
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/WildAddon-1.0/WildAddon-1.0.lua"]:83: in function `SendSignal'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/base.lua"]:24: in function `SendFrameSignal'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bagToggle.lua"]:40: in function <...AddOns/Bagnon/common/Wildpants/classes/bagToggle.lua:35>

Locals: <none>

**Additional context**

**Comment by BradCOnGitHub** [comment]
Same error. Seems to be causing at least one bank bag to not even appear in the UI

**Comment by Nillx** [comment]
You also cannot see your bank bags when clicking on the bags icon.
