### ISSUE TITLE
New items looted do not appear in bag

### ISSUE THREAD

**Issue by jonathanjosephduarte** [tullamods/Bagnon#1478]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 10.0.3
 - Server patch: 10.0.0.46455

 **Have you read the changelog? (please don't waste our time)**
 Mark if read. Yes

**Describe the bug**
When new items are looted, the bagnon item display does not update - so icant see the new items i loot

**To Reproduce**
Steps to reproduce the behaviour:
1. open all bags
2. loot item
3. does not display
4. press "cleanup" 
5. 5. sometimes the items display

**Expected behaviour**
the items display every time without having to click cleanup

**Screenshots**
looted item
![image](https://user-images.githubusercontent.com/49081510/200079791-503a8622-d22e-48fa-93f4-eb614f856bb0.png)
 after "cleanup"
![image](https://user-images.githubusercontent.com/49081510/200079865-d94325aa-d2c4-4f9f-942a-c16ed6907318.png)

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the message with `ID: 1` (labelled 1/X). This is generally NOT the message that the window shows by default.

**Additional context**
this problem seems to only happen on toons created after the 10.0 prepatch update

**Comment by DancingDolphins** [comment]
I can see you didnt enabl
![Uploading snipaste_20221105_080720.jpg…]()
e the left bag

**Comment by jonathanjosephduarte** [comment]
100% correct, im just an idiot thank you
