### ISSUE TITLE
#1 trash addon 

### ISSUE THREAD

**Issue by Bryaniame** [tullamods/Bagnon#1504]
Lazy dev advertising his patreon and paypal while saying its the #1 addon. Yet no update after the second prepatch update. 
Actual lazy trash developer. This addon is now deleted and will never be used anymore. Elvui has a better replacement and more customization. 
Have fun using asmon to advertise to ur shitty addon that you lazy fuck cant even update. 
#1 trash addon. 
#1 lazy developer
#1 sellout trash developer
Insane how many users have now deleted this trash addon. Ur patreon has also been reported. Have fun losing all of ur users trash developer. 

Cya! :)

**Comment by karmalegend** [comment]
God gamer

**Comment by cixel** [comment]
yeah it's weird as fuck to open an issue to complain like this. you don't have to pay or donate. just don't. your github account looks like it was only made to harrass addon authors. that's super weird.

**Comment by jwilliam87** [comment]
While I think this post was extreme to say the least, I am wondering if it will ever be fixed.  It's been unusable for quite a while...

**Comment by teelolws** [comment]
Oh look, its the guy who opened an issue to complain that I'd released my update too early for your region, blaming me because you installed my 10.0.2 patch while it was still 10.0.0 in your region and was rude to me about it.

https://github.com/teelolws/SLMicroMenu/issues/7

**Comment by lloskka** [comment]
After being out of your patreon, this is what got me to answer.

**WE** ( inc. me ) **the community** 90% fixed your addon **before you showing up at all.**

Now you have locked the comments on curse aha! **so you redirected all people to your NEW patreon and all of them they must pay** to have a non updated addon.

Hope the people can **OPEN THEIR EYES** see how much of a **FARSE** is this addon.

Learn your place, TRASH you deserve it.

**Comment by Azerox050** [comment]
A "nr1" addon that is not updated for over a week is trash indeed.
Im gonna remove it and install ArkInventory or AdiBags now.
This dev became a troll unfortunatly.

**Comment by HolgerDKz** [comment]
> After being out of your patreon, this is what got me to answer.
> 
> **WE** ( inc. me ) **the community** 90% fixed your addon for **FREE** **before you showing up at all.**
> 
> Now you have locked the comments on curse aha! **so you redirected all people to your NEW patreon and all of them they must pay** to have a non updated addon.
> 
> Hope the people can **OPEN THEIR EYES** see how much of a **FARSE** is this addon.
> 
> Learn your place, TRASH you deserve it.

Which dev are you referring to - tullamods or jaliborc?

**Comment by AHigi** [comment]
There I fixed it somewhat
Dunno if all functions are working, thus far I have no issues with it
https://mega.nz/file/jIkiBbgR#O428clwKppqMEwfQhc87Hn3vtx2AisI8sgpA5oZbq8g

**Comment by karmalegend** [comment]
> There I fixed it somewhat Dunno if all functions are working, thus far I have no issues with it https://mega.nz/file/jIkiBbgR#O428clwKppqMEwfQhc87Hn3vtx2AisI8sgpA5oZbq8g

Consider opening a pull request :)

**Comment by Razertongue** [comment]
> Oh look, its the guy who opened an issue to complain that I'd released my update too early for your region, blaming me because you installed my 10.0.2 patch while it was still 10.0.0 in your region and was rude to me about it.
> 
> [teelolws/SLMicroMenu#7](https://github.com/teelolws/SLMicroMenu/issues/7)

Says the guy who actively tried to hinder RP addons when he was gifted partial ownership of Altoholic and abused his power. Can only imagine what your addons are riddled with now.

**Comment by jwilliam87** [comment]
That was the old mod. 

Why are you so angry over am adding?
