### ISSUE TITLE
New error 10.0.2

### ISSUE THREAD

**Issue by Mithras2801** [tullamods/Bagnon#1505]
48x ...s/Bagnon/common/Wildpants/features/tooltipCounts.lua:34: QuickKeybindTooltip doesn't have a "OnTooltipSetItem" script
[string "=[C]"]: in function `HookScript'
[string "@Bagnon/common/Wildpants/features/tooltipCounts.lua"]:34: in function `Hook'
[string "@Bagnon/common/Wildpants/features/tooltipCounts.lua"]:25: in function `?'
[string "@Bagnon/common/Wildpants/libs/WildAddon-1.0-1/WildAddon-1.0.lua"]:20: in function <...ommon/Wildpants/libs/WildAddon-1.0/WildAddon-1.0.lua:18>
[string "@Bagnon/common/Wildpants/libs/WildAddon-1.0-1/WildAddon-1.0.lua"]:56: in function <...ommon/Wildpants/libs/WildAddon-1.0/WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:24: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML/UIParent.lua"]:536: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:587: in function `CombatLog_LoadUI'
[string "@FrameXML/UIParent.lua"]:1484: in function <FrameXML/UIParent.lua:1362>
[string "=[C]"]: ?

**Comment by Zurthor** [comment]
These are the 3 errors I got from latest version. 

1x Bagnon/addons/main/brokerPlugin.lua:38: attempt to call global 'GetContainerNumFreeSlots' (a nil value)
[string "@Bagnon/addons/main/brokerPlugin.lua"]:38: in function `?'
[string "@Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:114: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:114>
[string "=[C]"]: ?
[string "@Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:24: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>
------------------------------------------------------------------------------------------------------------------------

2x Bagnon/common/Wildpants/api/events.lua:91: attempt to call global 'GetContainerNumSlots' (a nil value)
[string "@Bagnon/common/Wildpants/api/events.lua"]:91: in function `UpdateSize'
[string "@Bagnon/common/Wildpants/api/events.lua"]:33: in function `?'
[string "@Bagnon/common/Wildpants/libs/WildAddon-1.0-1/WildAddon-1.0.lua"]:20: in function <...ommon/Wildpants/libs/WildAddon-1.0/WildAddon-1.0.lua:18>
[string "@Bagnon/common/Wildpants/libs/WildAddon-1.0-1/WildAddon-1.0.lua"]:56: in function <...ommon/Wildpants/libs/WildAddon-1.0/WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:24: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML/UIParent.lua"]:536: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:587: in function `CombatLog_LoadUI'
[string "@FrameXML/UIParent.lua"]:1484: in function <FrameXML/UIParent.lua:1362>
----------------------------------------------------------------------------------------------------------------------

1x BagBrother/Code/API.lua:20: attempt to call global 'GetContainerNumSlots' (a nil value)
[string "@BagBrother/Code/API.lua"]:20: in function `SaveBag'
[string "@BagBrother/Code/Events.lua"]:27: in function `BAG_UPDATE'
[string "@BagBrother/Code/Startup.lua"]:74: in function `UpdateData'
[string "@BagBrother/Code/Startup.lua"]:30: in function `?'
[string "@BagBrother/Code/Startup.lua"]:20: in function <BagBrother/Code/Startup.lua:20>

Locals:
self = BagBrother {
 BANKFRAME_OPENED = <function> defined @BagBrother/Code/Events.lua:54
 ParseItem = <function> defined @BagBrother/Code/API.lua:47
 SetupEvents = <function> defined @BagBrother/Code/Startup.lua:49
 VOID_STORAGE_CLOSE = <function> defined @BagBrother/Code/Events.lua:80
 PLAYER_INTERACTION_MANAGER_FRAME_HIDE = <function> defined @BagBrother/Code/Events.lua:45
 SaveBag = <function> defined @BagBrother/Code/API.lua:19
 PLAYER_EQUIPMENT_CHANGED = <function> defined @BagBrother/Code/Events.lua:31
 SaveEquip = <function> defined @BagBrother/Code/API.lua:40
 GUILDBANKFRAME_OPENED = <function> defined @BagBrother/Code/Events.lua:95
 Realm = <table> {
 }
 PLAYER_INTERACTION_MANAGER_FRAME_SHOW = <function> defined @BagBrother/Code/Events.lua:39
 PLAYER_MONEY = <function> defined @BagBrother/Code/Events.lua:35
 BANKFRAME_CLOSED = <function> defined @BagBrother/Code/Events.lua:58
 GUILDBANKFRAME_CLOSED = <function> defined @BagBrother/Code/Events.lua:99
 VOID_STORAGE_OPEN = <function> defined @BagBrother/Code/Events.lua:76
 GUILDBANKBAGSLOTS_CHANGED = <function> defined @BagBrother/Code/Events.lua:107
 Player = <table> {
 }
 RemoveEvent = <function> defined @BagBrother/Code/Startup.lua:92
 StartupCache = <function> defined @BagBrother/Code/Startup.lua:33
 0 = <userdata>
 GUILD_ROSTER_UPDATE = <function> defined @BagBrother/Code/Events.lua:103
 UpdateData = <function> defined @BagBrother/Code/Startup.lua:72
 BAG_UPDATE = <function> defined @BagBrother/Code/Events.lua:25
}
bag = 0
onlyItems = true
saveSize = true
(*temporary) = nil
(*temporary) = 0
(*temporary) = "attempt to call global 'GetContainerNumSlots' (a nil value)"

**Comment by mark-nicepants** [comment]
My errors on latest version, hope the stacktraces help ya fix it. Thanks for the addon 👍 

<details>
  <summary>Error 1: GetContainerNumSlots (a nil value)</summary>
Message: ...erface/AddOns/Bagnon/common/Wildpants/api/events.lua:91: attempt to call global 'GetContainerNumSlots' (a nil value)
Time: Thu Nov 24 13:07:06 2022
Count: 1
Stack: ...erface/AddOns/Bagnon/common/Wildpants/api/events.lua:91: attempt to call global 'GetContainerNumSlots' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Bagnon/common/Wildpants/api/events.lua"]:91: in function `UpdateSize'
[string "@Interface/AddOns/Bagnon/common/Wildpants/api/events.lua"]:33: in function `?'
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/WildAddon-1.0/WildAddon-1.0.lua"]:20: in function <...ommon/Wildpants/libs/WildAddon-1.0/WildAddon-1.0.lua:18>
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/WildAddon-1.0/WildAddon-1.0.lua"]:56: in function <...ommon/Wildpants/libs/WildAddon-1.0/WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:29: in function <...nts/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <.../common/Wildpants/libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:536: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:667: in function `TimeManager_LoadUI'
[string "@Interface/FrameXML/UIParent.lua"]:1482: in function <Interface/FrameXML/UIParent.lua:1362>

Locals: <none>

</details>

<details>
  <summary>Error 2: QuickKeybindTooltip doesn't have a "OnTooltipSetItem" script</summary>
Message: ...s/Bagnon/common/Wildpants/features/tooltipCounts.lua:34: QuickKeybindTooltip doesn't have a "OnTooltipSetItem" script
Time: Thu Nov 24 13:07:06 2022
Count: 1
Stack: ...s/Bagnon/common/Wildpants/features/tooltipCounts.lua:34: QuickKeybindTooltip doesn't have a "OnTooltipSetItem" script
[string "=(tail call)"]: ?
[string "=[C]"]: in function `HookScript'
[string "@Interface/AddOns/Bagnon/common/Wildpants/features/tooltipCounts.lua"]:34: in function `Hook'
[string "@Interface/AddOns/Bagnon/common/Wildpants/features/tooltipCounts.lua"]:25: in function `?'
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/WildAddon-1.0/WildAddon-1.0.lua"]:20: in function <...ommon/Wildpants/libs/WildAddon-1.0/WildAddon-1.0.lua:18>
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/WildAddon-1.0/WildAddon-1.0.lua"]:56: in function <...ommon/Wildpants/libs/WildAddon-1.0/WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:29: in function <...nts/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <.../common/Wildpants/libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:536: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:587: in function `CombatLog_LoadUI'
[string "@Interface/FrameXML/UIParent.lua"]:1484: in function <Interface/FrameXML/UIParent.lua:1362>

Locals: <none>
</details>

<details>
  <summary>Error 3: GetContainerNumFreeSlots (a nil value)</summary>
  Message: Interface/AddOns/Bagnon/addons/main/brokerPlugin.lua:38: attempt to call global 'GetContainerNumFreeSlots' (a nil value)
Time: Thu Nov 24 13:07:06 2022
Count: 1
Stack: Interface/AddOns/Bagnon/addons/main/brokerPlugin.lua:38: attempt to call global 'GetContainerNumFreeSlots' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Bagnon/addons/main/brokerPlugin.lua"]:38: in function `?'
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:119: in function <...nts/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:29: in function <...nts/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <.../common/Wildpants/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: <none>
</details>

**Comment by AHigi** [comment]
There I fixed it somewhat
Dunno if all functions are working, thus far I have no issues with it
https://mega.nz/file/jIkiBbgR#O428clwKppqMEwfQhc87Hn3vtx2AisI8sgpA5oZbq8g

**Comment by mark-nicepants** [comment]
Confirmed working here aswell. Maybe you can contribute a PR to this repo with the relevant changes?

**Comment by mark-nicepants** [comment]
Just notices the stacksize indicator is missing.

Can't see that this is a stack of 1000 
<img width="167" alt="image" src="https://user-images.githubusercontent.com/62654433/203826425-211a68ad-83c4-4184-a50e-c9a7acb35b6a.png">

**Comment by AHigi** [comment]
> Just notices the stacksize indicator is missing.
> 
> Can't see that this is a stack of 1000 <img alt="image" width="167" src="https://user-images.githubusercontent.com/62654433/203826425-211a68ad-83c4-4184-a50e-c9a7acb35b6a.png">

Gonna have a look at it

**Comment by AHigi** [comment]
![kép](https://user-images.githubusercontent.com/26726928/203886326-ea06d229-3693-4b27-9e5a-141eb13ab93e.png)
I've got you fam, fixed the border colros too, & void storage aswell
Made PR & posted pull requests for Wildpants, Bagnon & BagBrother

**Comment by Jhalen1** [comment]
> ![kép](https://user-images.githubusercontent.com/26726928/203886326-ea06d229-3693-4b27-9e5a-141eb13ab93e.png) I've got you fam, fixed the border colros too, & void storage aswell Made PR & posted pull requests for Wildpants, Bagnon & BagBrother

Hey, I downloaded your .zip from the Mega link, what do I have to change to get the stacksizes?

**Comment by AHigi** [comment]
> > ![kép](https://user-images.githubusercontent.com/26726928/203886326-ea06d229-3693-4b27-9e5a-141eb13ab93e.png) I've got you fam, fixed the border colros too, & void storage aswell Made PR & posted pull requests for Wildpants, Bagnon & BagBrother
> 
> Hey, I downloaded your .zip from the Mega link, what do I have to change to get the stacksizes?
just download the files from my repo:
https://github.com/AHigi

**Comment by FROlCi** [comment]
Hey 
First of all a big Merci :) Not found any way to easily download the files from your repo, happy to hear / read that I am a clear noob in using github^^

**Comment by AHigi** [comment]
I found another bug, will fix it and create a pull request & post another mega download :)

**Comment by AHigi** [comment]
The latest version
https://mega.nz/file/uUdhgThY#iDxFlTcICmUliwBVKF6yL3iv19TfjsMYDrJIe91hUDo

**Comment by HolgerDKz** [comment]
> The latest version https://mega.nz/file/uUdhgThY#iDxFlTcICmUliwBVKF6yL3iv19TfjsMYDrJIe91hUDo

Works for me, thank you!

**Comment by AHigi** [comment]
> > The latest version https://mega.nz/file/uUdhgThY#iDxFlTcICmUliwBVKF6yL3iv19TfjsMYDrJIe91hUDo
> 
> Works for me, thank you!

Happy to help out

**Comment by yoshimo** [comment]
Which of the changes is responsible for proper item icons for the bags?
My own attempt of forward porting this failed somewhere and i had working bags but no rendered items, just tooltips on seemingly empty slots ;)

**Comment by FROlCi** [comment]
Excellent ! TY !!!

 

De : AHigi ***@***.***> 
Envoyé : vendredi 25 novembre 2022 14:36
À : tullamods/Bagnon ***@***.***>
Cc : FROlCi ***@***.***>; Comment ***@***.***>
Objet : Re: [tullamods/Bagnon] New error 10.0.2 (Issue #1505)

 

The latest version https://mega.nz/file/uUdhgThY#iDxFlTcICmUliwBVKF6yL3iv19TfjsMYDrJIe91hUDo

Works for me, thank you!

Happy to help out

**Comment by Elfykins** [comment]
> > > The latest version https://mega.nz/file/uUdhgThY#iDxFlTcICmUliwBVKF6yL3iv19TfjsMYDrJIe91hUDo
> > 
> > 
> > Works for me, thank you!
> 
> Happy to help out

Works perfectly so far, only issue I have right now is that if you select to mark poor items, all empty spots contain a coin.

The other issue I have, which is a personal one, is I'd like to be able to separate the reagent bag completely, without having to select the option to split bags (eg split only the reagent bag).

**Comment by jwilliam87** [comment]
> > > The latest version https://mega.nz/file/uUdhgThY#iDxFlTcICmUliwBVKF6yL3iv19TfjsMYDrJIe91hUDo
> > 
> > 
> > Works for me, thank you!
> 
> Happy to help out

It's working great!
