### ISSUE TITLE
Bagnon Bugs 10.0.3 - Bags UI not opening (4 errors)

### ISSUE THREAD

**Issue by Felldoh216** [tullamods/Bagnon#1506]
- Addon version: 10.0.3
 - Server patch: 10.0.2.46741

 **Have you read the changelog? (please don't waste our time)**
 Mark if read. Yes

**Describe the bug**
My bag UI won't open using the Bagnon app with 0 mods or plugins installed.

**To Reproduce**
1. Log in to character
2. Click on hotkey for bags (B)
3. Bags don't open
4. See errors

**Expected behavior**
Bags open

**Error Logs**

**_Error 1_**

2x ...s/Bagnon/common/Wildpants/features/tooltipCounts.lua:34: QuickKeybindTooltip doesn't have a "OnTooltipSetItem" script
[string "=[C]"]: in function `HookScript'
[string "@Bagnon/common/Wildpants/features/tooltipCounts.lua"]:34: in function `Hook'
[string "@Bagnon/common/Wildpants/features/tooltipCounts.lua"]:25: in function `?'
[string "@Bagnon/common/Wildpants/libs/WildAddon-1.0-1/WildAddon-1.0.lua"]:20: in function <...ommon/Wildpants/libs/WildAddon-1.0/WildAddon-1.0.lua:18>
[string "@Bagnon/common/Wildpants/libs/WildAddon-1.0-1/WildAddon-1.0.lua"]:56: in function <...ommon/Wildpants/libs/WildAddon-1.0/WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@Bagnon/common/Wildpants/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:29: in function <...nts/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Bagnon/common/Wildpants/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Bagnon/common/Wildpants/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <.../common/Wildpants/libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML/UIParent.lua"]:536: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:587: in function `CombatLog_LoadUI'
[string "@FrameXML/UIParent.lua"]:1484: in function <FrameXML/UIParent.lua:1362>

**_Error 2_**

5x Bagnon/common/Wildpants/api/events.lua:91: attempt to call global 'GetContainerNumSlots' (a nil value)
[string "@Bagnon/common/Wildpants/api/events.lua"]:91: in function `UpdateSize'
[string "@Bagnon/common/Wildpants/api/events.lua"]:33: in function `?'
[string "@Bagnon/common/Wildpants/libs/WildAddon-1.0-1/WildAddon-1.0.lua"]:20: in function <...ommon/Wildpants/libs/WildAddon-1.0/WildAddon-1.0.lua:18>
[string "@Bagnon/common/Wildpants/libs/WildAddon-1.0-1/WildAddon-1.0.lua"]:56: in function <...ommon/Wildpants/libs/WildAddon-1.0/WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@Bagnon/common/Wildpants/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:29: in function <...nts/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Bagnon/common/Wildpants/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Bagnon/common/Wildpants/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <.../common/Wildpants/libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML/UIParent.lua"]:536: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:667: in function `TimeManager_LoadUI'
[string "@FrameXML/UIParent.lua"]:1482: in function <FrameXML/UIParent.lua:1362>

**_Error 3_**

3x Bagnon/addons/main/brokerPlugin.lua:38: attempt to call global 'GetContainerNumFreeSlots' (a nil value)
[string "@Bagnon/addons/main/brokerPlugin.lua"]:38: in function `?'
[string "@Bagnon/common/Wildpants/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:119: in function <...nts/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Bagnon/common/Wildpants/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:29: in function <...nts/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Bagnon/common/Wildpants/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Bagnon/common/Wildpants/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <.../common/Wildpants/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

**_Error 4_**

30x ...Wildpants/libs/LibItemCache-2.0-35/LibItemCache-2.0.lua:178: attempt to call global 'GetContainerNumFreeSlots' (a nil value)
[string "@Bagnon/common/Wildpants/libs/LibItemCache-2.0-35/LibItemCache-2.0.lua"]:178: in function <...Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:160>
[string "=(tail call)"]: ?
[string "@Bagnon/common/Wildpants/classes/frame.lua"]:117: in function <...aceBagnon/common/Wildpants/classes/frame.lua:116>
[string "=(tail call)"]: ?
[string "@Bagnon/common/Wildpants/classes/itemGroup.lua"]:46: in function `RegisterEvents'
[string "@Bagnon/common/Wildpants/classes/itemGroup.lua"]:32: in function `Update'
[string "@Bagnon/common/Wildpants/classes/itemGroup.lua"]:27: in function <Bagnon/common/Wildpants/classes/itemGroup.lua:13>
[string "=(tail call)"]: ?
[string "@Bagnon/addons/main/frame.lua"]:26: in function `New'
[string "@Bagnon/common/Wildpants/api/frames.lua"]:44: in function `New'
[string "@Bagnon/common/Wildpants/api/frames.lua"]:81: in function `Show'
[string "@Bagnon/common/Wildpants/api/frames.lua"]:77: in function <Bagnon/common/Wildpants/api/frames.lua:76>
[string "=(tail call)"]: ?
[string "@Bagnon/common/Wildpants/features/autoDisplay.lua"]:82: in function `ToggleAllBags'
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Locals:
self = <table> {
 IsKeyring = <function> defined @Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:405
 FrameTemplate = "BackdropTemplate"
 IsRetail = true
 GetOwnerID = <function> defined @Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:285
 Frames = <table> {
 }
 Currency = <table> {
 }
 InBank = <function> defined @Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:382
 ItemGroup = <table> {
 }
 RestoreItemData = <function> defined @Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:319
 Frame = <table> {
 }
 OptionsToggle = <table> {
 }
 Bag = <table> {
 }
 IsBank = <function> defined @Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:409
 RegisterMessage = <function> defined @Bagnon/common/Wildpants/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Bagnon/common/Wildpants/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:153
 IsBagCached = <function> defined @Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:306
 Base = <table> {
 }
 UnregisterSignal = <function> defined @Bagnon/common/Wildpants/libs/WildAddon-1.0/WildAddon-1.0.lua:78
 GetOwnerAddress = <function> defined @Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:290
 RegisterEvent = <function> defined @Bagnon/common/Wildpants/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 sets = <table> {
 }
 OnEnable = <function> defined @Bagnon/common/Wildpants/Wildpants.lua:101
 Name = "Bagnon"
 IterateOwners = <function> defined @Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:129
 InGuild = <function> defined @Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:390
 Parented = <table> {
 }
 NewModule = <function> defined @Bagnon/common/Wildpants/libs/WildAddon-1.0/WildAddon-1.0.lua:68
 RestorePetLinkData = <function> defined @Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:373
 Item = <table> {
 }
 IsClassic = false
 OwnerSelector = <table> {
 }
 Commands = <table> {
 }
 profile = <table> {
 }
 SortButton = <table> {
 }
 ItemSlot = <table> {
 }
 InventoryFrame = <table> {
 }
 SearchToggle = <table> {
 }
 SearchFrame = <table> {
 }
 BagGroup = <table> {
 }
 BrokerCarrousel = <table> {
 }
 Events = <table> {
 }
 LDB = <table> {
 }
 TooltipCounts = <table> {
 }
 Title = <table> {
 }
 AutoDisplay = <table> {
 }
 Tag = "BAGNON_"
 GetItemInfo = <function> defined @Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:221
 IsBackpackBag = <function> defined @Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:401
 GetOwnerInfo = <function> defined @Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:89
 PickupItem = <function> defined @Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:265
 ShowOptions = <function> defined @Bagnon/common/Wildpants/Wildpants.lua:159
 UnregisterAllEvents = <function> defined @Bagnon/common/Wildpants/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:174
 BankFrame = <table> {
 }
 DropButton = <table> {
 }
 GetItemID = <function> defined @Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:244
 IsReagents = <function> defined @Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:417
 IsBankBag = <function> defined @Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:413
 Owners = <table> {
 }
 Sorting = <table> {
 }
 GetBagInfo = <function> defined @Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:160
 BagToggle = <table> {
 }
 CurrencyTracker = <table> {
 }
 SendSignal = <fun

**Additional context**

**Comment by StrayerJ** [comment]
Ditto, been this way for a while.

**Comment by davidchangok** [comment]
Exactly the same buggy experience and has been since the 10.0 update, a long time ago.
