### ISSUE TITLE
author may be experiencing issues ..please be patient

### ISSUE THREAD

**Issue by stingray66** [tullamods/Bagnon#1507]
**Running Software (issues missing this information will be deleted):**
 - Addon version:
 - Server patch: [e.g. Build 8.0.1.27178]

 **Have you read the changelog? (please don't waste our time)**
 Mark if read.

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the message with `ID: 1` (labelled 1/X). This is generally NOT the message that the window shows by default.

**Additional context**

**Comment by MoosGames** [comment]
You forgot to include the link to his patreon.

**Comment by lloskka** [comment]
He already locked some comments here too ( as he did on curse ).

Too bad for him, damage is done already.

Everything that happens onward , your fault @Jaliborc , you dont deserve half of your patreons ( hope they can be "more alive" with yoyr fraudulent addons )

Anyway, in the meantime he didnot / wont show... learned by myself to fixed some errors ( solutions were in the locked comments ), but they are in some of the open issues aswell.

@MoosGames no need , he already has his customers robbed :D ( thats why i left sometime ago )

**Comment by s0ftcorn** [comment]
> Everything that happens onward , your fault @Jaliborc , you dont deserve half of your patreons ( hope they can be "more alive" with your fraudulent addons )
> 
> Anyway, in the meantime he didnot / wont show... learned by myself to fixed some errors ( solutions were in the locked comments ), but they are in some of the open issues aswell.
> 
> @MoosGames no need , he already has his customers robbed :D ( thats why i left sometime ago )

Looking at his patron you see that scrap got updated 20 hours ago. Keep in mind he is doing this not for living, not for the money, so in no way you have *any* right to think you are a "customer". Just because you can donate money, it doesnt mean you are a "paying customer". 
Btw you can on his patreon also see, that he closed the (terrible) curseforge comments and started a discord server.
So yeah... Maybe stop the hate speech and just be patient.

**Comment by scryptio** [comment]
What happened?

**Comment by blecaplol** [comment]
he has the cheek to ask for patreon? fuck off. dont ask if u dont fix. dumb fuck author.

**Comment by sirzooro** [comment]
1.5 week passed since 2nd prepatch and author did not say a word why we still have to wait. This is very unprofessional, especially after he cleanup some comments here. We want to know what is going on. I also have to mention that someone else here was able to prepare quick and dirty fix in one day to use new C_Container API instead of old one, what at least partially fixed the addon. Partial official fix is way better than no fix.

**Comment by MoosGames** [comment]
> he has the cheek to ask for patreon? fuck off. dont ask if u dont fix. dumb fuck author.

He gets 360$ per month from his patreons.

I installed ArkInventory meanwhile as it has all the functionality I need - mainly the item count on my alts in the tooltip.

**Comment by Desik** [comment]
Bunch of entitled people here, donations , patreon and any form of "support" don't mean you own the author/maintainer of this software, fork your own copy or install another addon, you are not customers, this is not a service or product

If I was the author I would not update this project at all after viewing how stupid toxic some users are.

**Comment by blecaplol** [comment]
Lol then stfu why uy comm

> Bunch of entitled people here, donations , patreon and any form of "support" don't mean you own the author/maintainer of this software, fork your own copy or install another addon, you are not customers, this is not a service or product
> 
> If I was the author I would not update this project at all after viewing how stupid toxic some users are.

then stfu. and dont update and tell him dont demand donation. entitled my fucking ass. stupid fuck. fuck u and the author. a fucking fan fix his addon and he still taking 2 fucking weeks and counting. what a fucking joke.

**Comment by pablotoledog** [comment]
Apparently he just explained that he was away for a couple of weeks and he just recently came back. He already updated Scrap yesterday according to his Patreon, so it shouldn't be long until he can fix Bagnon. I'm pretty sure he's aware of how useful his addons are, so don't panic, at the very least you could use some other bag addon (there are tons) and then check back for when he's finished fixing this one. 👍

**Comment by pablotoledog** [comment]
Also, in the Community Discord someone just uploaded a temporary fix of the addon, if anyone's interested: https://discord.com/invite/DwAVku4b6x

**Comment by Pheeve** [comment]
what on earth is going on?

**Comment by stingray66** [comment]
I have no idea what is going on with him and it's none of my business or anyone elses. I just heard on a twitch stream the other day about this addon about it not being fixed yet. If he fixes it he fixes it and i will be grateful when he does and if not i will find something else.

**Comment by Gonkers** [comment]
So as a software engineer my opinion (yes, opinions are like a-holes, everyone has one) this repo is not run well.  The author claims to publish their code as GPL3, but doesn't understand what that means.
https://github.com/Jaliborc/BagBrother/blob/master/Code/Interface.lua#L4
> As a special exception, the copyright holders of this addon do not give permission to redistribute and/or modify it.

That' doesn't work, however IANAL (I am not a lawyer), but the [GPL](https://www.gnu.org/licenses/gpl-3.0.en.html) states it's intention

> the GNU General Public License is intended to guarantee your freedom to share and change all versions of a program--to make sure it remains free software for all its users.

You can't publish your works under the GPL and then restrict its core creed.

While there has been a lot of vitriol on this account and repo, I will admit that I don't know what's going on, but there appears to be a LOT of dishonesty going around by all parties.

**Comment by Gonkers** [comment]
> So as a software engineer my opinion (yes, opinions are like a-holes, everyone has one) this repo is not run well. The author claims to publish their code as GPL3, but doesn't understand what that means... 

The more I read about this the more I want to run away.  As an open-source software engineer, I understand how thankless of a job it really is.  However, as an author you should state your intentions and goals for the project. If you really intended it to be open source, etc.  If you didn't intend for this software to be open source @Jaliborc I implore you to tell all of us (directly) to fuck off and make the repo private.

**Comment by sirzooro** [comment]
I agree with all of this. I can understand that author could be away for a few weeks, but he could way better handle this. As a minimum he should publish some info on Curseforge and Github addon pages that he is out. If he could not do this before, he could at least publish some comment after 2nd prepatch went live that he needs more time to publish fixed version. Next thing, he could prepare for this earlier by using PTR server for testing - PTR is open for everyone. It would be event better to test on Beta servers, but they need invitation from Blizz. He probably could get one by asking for it and mentioning that he needs access to update plugins for next WoW version. And last thing, if fix is really difficult, he could try to publish partial fix so at least some addon functionality would work, and deliver full fix later. Unfortunately none of this happened. Instead author choose to keep us in the dark, wondering what on earth is going on. All of this made people unhappy (many already switched to other addons) and fed haters.

**Comment by s0ftcorn** [comment]
> I agree with all of this. I can understand that author could be away for a few weeks, but he could way better handle this. As a minimum he should publish some info on Curseforge and Github addon pages that he is out. If he could not do this before, he could at least publish some comment after 2nd prepatch went live that he needs more time to publish fixed version. Next thing, he could prepare for this earlier by using PTR server for testing - PTR is open for everyone. It would be event better to test on Beta servers, but they need invitation from Blizz. He probably could get one by asking for it and mentioning that he needs access to update plugins for next WoW version. And last thing, if fix is really difficult, he could try to publish partial fix so at least some addon functionality would work, and deliver full fix later. Unfortunately none of this happened. Instead author choose to keep us in the dark, wondering what on earth is going on. All of this made people unhappy (many already switched to other addons) and fed haters.

While i do agreee to some extent, we do have to keep in mind that its hard to keep users of addons in the loop. The curseforge comment section is a mess, there is no way of ingame updates, many people dont even know of the patreon.
I also think that if i would do this for free (and get donations for which i dont ask), i would also not see the need to update users as soon as possible. You cant compare the work of hobby addon devs to companies. And even in a company: your health and other private stuff has priority. 

At this point i am happy the dev is even continuing the work.

**Comment by Terroosh** [comment]
It's a shame the guy who made the addon working again on the curseforge comments doesn't get patreon money.

**Comment by sirzooro** [comment]
> > I agree with all of this. I can understand that author could be away for a few weeks, but he could way better handle this. As a minimum he should publish some info on Curseforge and Github addon pages that he is out. If he could not do this before, he could at least publish some comment after 2nd prepatch went live that he needs more time to publish fixed version. Next thing, he could prepare for this earlier by using PTR server for testing - PTR is open for everyone. It would be event better to test on Beta servers, but they need invitation from Blizz. He probably could get one by asking for it and mentioning that he needs access to update plugins for next WoW version. And last thing, if fix is really difficult, he could try to publish partial fix so at least some addon functionality would work, and deliver full fix later. Unfortunately none of this happened. Instead author choose to keep us in the dark, wondering what on earth is going on. All of this made people unhappy (many already switched to other addons) and fed haters.
> 
> While i do agreee to some extent, we do have to keep in mind that its hard to keep users of addons in the loop. The curseforge comment section is a mess, 

Author can edit addon page, so he could put some big notice on top of curseforge addon page, the same for github.

> there is no way of ingame updates, 

Some addons (e.g. Deadly Boss Mods) sometimes prints information that there is new version available. I am not sure if addon queries external website for this or it gets information in-game from other players who already upgraded that addon. So there is some way to deliver important information to players.

> many people dont even know of the patreon.

True, I know about it, but would newer visit it unless I would like to donate. Out of curiosity I have visited it few moments ago and saw that there are some news added there. To be honest, patreon is the last place where I would expect to read news about addon. Obvious places are curseforge addon page, github addon page, maybe autor website if he has one, some wow forums also looks like a good idea to keep in touch with users, but patreon? This is really bad choice.

> I also think that if i would do this for free (and get donations for which i dont ask), i would also not see the need to update users as soon as possible. You cant compare the work of hobby addon devs to companies. And even in a company: your health and other private stuff has priority.

True. I am fine with waiting for a few days for update. Only some addons have new version ready when prepatch goes live. Most other ones release new version in the next 3-4 days, especially when prepatch broke major functionality. If this is just cosmetic thing or even no changes are needed beside bumping up supported game version, update can wait even for few months. In this case we have popular addon which is completely broken after prepatch, and no communication for more than a week. Communication with your users/customers is very important, I would be fine with short message "I am out and cannot update addon now, sorry. I will return on <date> and start looking how to fix my addons. Sorry again for inconvenience."

**Comment by jwilliam87** [comment]
Author hasn't bothered to communicate anything.

If he had, none of these comments would have happened.

People are frustrated since the addon wasn't working, and Blizzard couldn't be bothered to add the inventory window to the things we can edit.

**Comment by Thaodan** [comment]
> So as a software engineer my opinion (yes, opinions are like a-holes, everyone has one) this repo is not run well. The author claims to publish their code as GPL3, but doesn't understand what that means. https://github.com/Jaliborc/BagBrother/blob/master/Code/Interface.lua#L4
> 
> > As a special exception, the copyright holders of this addon do not give permission to redistribute and/or modify it.
> 
> That' doesn't work, however IANAL (I am not a lawyer), but the [GPL](https://www.gnu.org/licenses/gpl-3.0.en.html) states it's intention
> 
> > the GNU General Public License is intended to guarantee your freedom to share and change all versions of a program--to make sure it remains free software for all its users.
> 
> You can't publish your works under the GPL and then restrict its core creed.
> 
> While there has been a lot of vitriol on this account and repo, I will admit that I don't know what's going on, but there appears to be a LOT of dishonesty going around by all parties.
> 
> EDIT: I just came here looking for an update to a broken WoW addon. This is a dumpster fire.

Last year he removed the mentions of GPL-3.0 from the code. Given he wrote about 95% of of the addon from what the git history tells us but it does look deceptive. Some people contributed to this addon that didn't gave permission?

Given that contributions are still accepted after the change and that Github's terms of service enforce that the user has to allow forks to his repository I'm not sure how contribution to this project should work.
