### ISSUE TITLE
Bagnon Wildpants Tooltip issues

### ISSUE THREAD

**Issue by cisconetdude** [tullamods/Bagnon#1511]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 10.0.3
 
Bug Sack

31x ...s/Bagnon/common/Wildpants/features/tooltipCounts.lua:58: attempt to call method 'GetItem' (a nil value)
[string "@Bagnon/common/Wildpants/features/tooltipCounts.lua"]:58: in function <...s/Bagnon/common/Wildpants/features/tooltipCounts.lua:57>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:60: in function <SharedXML/Tooltip/TooltipDataHandler.lua:55>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:80: in function <SharedXML/Tooltip/TooltipDataHandler.lua:76>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <SharedXML/Tooltip/TooltipDataHandler.lua:106>
[string "=[C]"]: in function `SetAttribute'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:141: in function <SharedXML/Tooltip/TooltipDataHandler.lua:134>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:282: in function <SharedXML/Tooltip/TooltipDataHandler.lua:240>
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:237: in function <SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "=[C]"]: in function `ProcessInfo'
...
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetHyperlink'
[string "@AutoBar/AutoBarClassBasicButton.lua"]:80: in function `TooltipShow'
[string "@AutoBar/AutoBarClassButton.lua"]:247: in function <AutoBar/AutoBarClassButton.lua:236>
[string "=[C]"]: ?
[string "@FrameXML/SecureHandlers.lua"]:266: in function <FrameXML/SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@FrameXML/SecureHandlers.lua"]:322: in function <FrameXML/SecureHandlers.lua:306>
[string "=(tail call)"]: ?

Locals:
tip = ShoppingTooltip1 {
 0 = <userdata>
 SetQuestLogRewardSpell = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 GetBackdropColor = <function> defined @SharedXML/Backdrop.lua:390
 SetHyperlink = <function> defined =[C]:-1
 SetAzeriteEssence = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetVoidDepositItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 AllTheThingsOnTooltipClearedHook = true
 SetSocketGem = <function> defined =[C]:-1
 ClearBackdrop = <function> defined @SharedXML/Backdrop.lua:282
 SetLootCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetLootItem = <function> defined =[C]:-1
 ttGradient = Texture {
 }
 SetQuestLogSpecialItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetRecipeReagentItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetMerchantItem = <function> defined =[C]:-1
 BottomOverlay = Texture {
 }
 SetSocketedRelic = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 ProcessInfo = <function> defined =[C]:-1
 NineSlice = Frame {
 }
 SetInventoryItem = <function> defined =[C]:-1
 TopEdge = Texture {
 }
 SetUnitDebuffByAuraInstanceID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetBagItem = <function> defined =[C]:-1
 SetBackdropColor = <function> defined @TipTac/ttCore.lua:1771
 LeftEdge = Texture {
 }
 SetCurrencyByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetSpellBookItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 textLeft1Font = "GameFontNormalSmall"
 SetShapeshift = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetArtifactPowerByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 textRight2Font = "GameFontHighlightSmall"
 TopOverlay = Texture {
 }
 SetSocketedItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnitDebuff = <function> defined =[C]:-1
 SetMountBySpellID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
 SetToyByItemID = <function> defined =[C]:-1
 TextLeft1 = ShoppingTooltip1TextLeft1 {
 }
 GetTooltipData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:344
 SetLFGDungeonShortageReward = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 SetArtifactItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetPossession = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetAzeriteEssenceSlot = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnitBuffByAuraInstanceID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetConduit = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetupPieceVisuals = <function> defined @SharedXML/Backdrop.lua:246
 SetMinimapMouseover = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestLogCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetRecipeResultItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestPartyProgress = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 ProcessLineData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:303
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 SetPvpTalent = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetRuneforgeResultItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnit = <function> defined =[C]:-1
 SetTotem = <function> defined 
[Bagnon Bugsack.txt](https://github.com/tullamods/Bagnon/files/10097084/Bagnon.Bugsack.txt)

**Comment by Dmeister406** [comment]
Seeing the same core LUA error:

17x ...s/Bagnon/common/Wildpants/features/tooltipCounts.lua:58: attempt to call method 'GetItem' (a nil value)
[string "@Bagnon/common/Wildpants/features/tooltipCounts.lua"]:58: in function <...s/Bagnon/common/Wildpants/features/tooltipCounts.lua:57>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:60: in function <SharedXML/Tooltip/TooltipDataHandler.lua:55>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:80: in function <SharedXML/Tooltip/TooltipDataHandler.lua:76>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <SharedXML/Tooltip/TooltipDataHandler.lua:106>
[string "=[C]"]: in function `SetAttribute'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:141: in function <SharedXML/Tooltip/TooltipDataHandler.lua:134>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:282: in function <SharedXML/Tooltip/TooltipDataHandler.lua:240>
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:237: in function <SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "=[C]"]: in function `ProcessInfo'
...
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:49: in function <SharedXML/Tooltip/TooltipDataHandler.lua:44>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:71: in function <SharedXML/Tooltip/TooltipDataHandler.lua:67>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:135: in function <SharedXML/Tooltip/TooltipDataHandler.lua:134>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:282: in function <SharedXML/Tooltip/TooltipDataHandler.lua:240>
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:237: in function <SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `SetInboxItem'
[string "@FrameXML/MailFrame.lua"]:344: in function `InboxFrameItem_OnEnter'
[string "*MailFrame.xml:158_OnUpdate"]:2: in function <[string "*MailFrame.xml:158_OnUpdate"]:1>

Locals:
tip = ShoppingTooltip1 {
 0 = <userdata>
 SetQuestLogRewardSpell = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestPartyProgress = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 ProcessLineData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:303
 SetPvpTalent = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetExistingSocketGem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetHyperlink = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnit = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetAzeriteEssence = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetVoidDepositItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetVoidWithdrawalItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetInfoBackdropStyle = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:338
 SetSocketGem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetLootCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetSlottedKeystone = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetItemInteractionItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetLootItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetOwnedItemByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestLogSpecialItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetRecipeReagentItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetBuybackItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 hasMoney = 1
 SetWeeklyReward = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetMerchantItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetPvpBrawl = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 shownMoneyFrames = 1
 BottomOverlay = Texture {
 }
 SetSpellByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 numMoneyFrames = 1
 SetSocketedRelic = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 ProcessInfo = <function> defined =[C]:-1
 ProcessLines = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:293
 NineSlice = Frame {
 }
 SetInventoryItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 info = <table> {
 }
 updateTooltipTimer = 0.200000
 SetLootRollItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 InternalProcessInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:240
 SetPossession = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnitDebuffByAuraInstanceID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetBagItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 TextRight1 = ShoppingTooltip1TextRight1 {
 }
 SetAction = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetLineDataAttribute = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:232
 SetAchievementByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetInventoryItemByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetCurrencyByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestLogCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetBagItemChild = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lu

**Comment by gbrlallison** [comment]
Can you confirm you are using addon version: 10.0.3? I ran into the same bug in version 10.0.4 (beta release channel).
The error only triggers when mousing over an equipment item on my inventory and disabling "Tooltip Item Count" in Bagnon options makes it go away.

```
251x ...s/Bagnon/common/Wildpants/features/tooltipCounts.lua:58: attempt to call method 'GetItem' (a nil value)
[string "@Bagnon/common/Wildpants/features/tooltipCounts.lua"]:58: in function <...s/Bagnon/common/Wildpants/features/tooltipCounts.lua:57>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:60: in function <SharedXML/Tooltip/TooltipDataHandler.lua:55>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:80: in function <SharedXML/Tooltip/TooltipDataHandler.lua:76>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <SharedXML/Tooltip/TooltipDataHandler.lua:106>
[string "=[C]"]: in function `SetAttribute'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:141: in function <SharedXML/Tooltip/TooltipDataHandler.lua:134>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:282: in function <SharedXML/Tooltip/TooltipDataHandler.lua:240>
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:237: in function `ProcessInfo'
[string "@SharedXML/Tooltip/TooltipComparisonManager.lua"]:249: in function `SetItemTooltip'
...
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:49: in function <SharedXML/Tooltip/TooltipDataHandler.lua:44>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:71: in function <SharedXML/Tooltip/TooltipDataHandler.lua:67>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:135: in function <SharedXML/Tooltip/TooltipDataHandler.lua:134>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:282: in function <SharedXML/Tooltip/TooltipDataHandler.lua:240>
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:237: in function <SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "=(tail call)"]: ?
[string "@FrameXML/ContainerFrame.lua"]:1504: in function `ContainerFrameItemButton_OnEnter'
[string "@Bagnon/common/Wildpants/classes/item.lua"]:350: in function `UpdateTooltip'
[string "@Bagnon/common/Wildpants/classes/item.lua"]:185: in function <...faceBagnon/common/Wildpants/classes/item.lua:180>

Locals:
tip = ShoppingTooltip1 {
 0 = <userdata>
 SetQuestLogRewardSpell = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestPartyProgress = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 ProcessLineData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:303
 SetPvpTalent = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetExistingSocketGem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetHyperlink = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnit = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetAzeriteEssence = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetVoidDepositItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetVoidWithdrawalItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetInfoBackdropStyle = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:338
 SetSocketGem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetLootCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetSlottedKeystone = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetItemInteractionItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetLootItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetOwnedItemByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestLogSpecialItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetRecipeReagentItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetBuybackItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 hasMoney = 1
 SetWeeklyReward = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetMerchantItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetPvpBrawl = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 shownMoneyFrames = 1
 BottomOverlay = Texture {
 }
 SetSpellByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 numMoneyFrames = 1
 SetSocketedRelic = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 ProcessInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:236
 ProcessLines = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:293
 NineSlice = Frame {
 }
 SetInventoryItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 info = <table> {
 }
 updateTooltipTimer = 0.200000
 SetLootRollItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 InternalProcessInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:240
 SetPossession = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnitDebuffByAuraInstanceID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetBagItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 TextRight1 = ShoppingTooltip1TextRight1 {
 }
 SetAction = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetLineDataAttribute = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:232
 SetAchievementByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetInventoryItemByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetCurrencyByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestLogCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetBagItemChild = <function> defined @I
```

**Comment by Dmeister406** [comment]
https://iili.io/HFpE3aS.png

**Comment by vladimirgluten** [comment]
I was getting the errors and was on the 0.4 beta.  Dropped to the release channel and the tooltip errors went away for me

**Comment by Dmeister406** [comment]
The latest in the release channel is 10.0.3 (for 10.0.0) which was released Nov 1 and is completely non-functional in retail. Am I missing something?

**Comment by vladimirgluten** [comment]
Oh yeah, never mind.  For some reason I had Bagnon set to "alpha release", so when I put it back on what I thought was "Release" channel it showed an update.  I thought 10.0.3 was the newest update and 0.4 was just a beta he was working on.  I guess I just reinstalled the 0.4 beta.  And I'm getting tooltip errors when mousing over stuff in the bags.

**Comment by cisconetdude** [comment]
you are correct, I was on Ver 10.0.4 that was beta.  using 10.0.3 for 10.0.2 from curse no bags works
the beta atleast functioned.  I am pretty sure that 10.0.3 for 10.0.0 is listed as the release version on Curse Forge.


3x ...Wildpants/libs/LibItemCache-2.0-34/LibItemCache-2.0.lua:177: attempt to call global 'GetContainerNumFreeSlots' (a nil value)
[string "@Bagnon/common/Wildpants/libs/LibItemCache-2.0-34/LibItemCache-2.0.lua"]:177: in function <...Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:159>
[string "=(tail call)"]: ?
[string "@Bagnon/common/Wildpants/classes/frame.lua"]:117: in function <...aceBagnon/common/Wildpants/classes/frame.lua:116>
[string "=(tail call)"]: ?
[string "@Bagnon/common/Wildpants/classes/itemGroup.lua"]:46: in function `RegisterEvents'
[string "@Bagnon/common/Wildpants/classes/itemGroup.lua"]:32: in function `Update'
[string "@Bagnon/common/Wildpants/classes/itemGroup.lua"]:27: in function <Bagnon/common/Wildpants/classes/itemGroup.lua:13>
[string "=(tail call)"]: ?
[string "@Bagnon/addons/main/frame.lua"]:26: in function `New'
[string "@Bagnon/common/Wildpants/api/frames.lua"]:44: in function `New'
[string "@Bagnon/common/Wildpants/api/frames.lua"]:81: in function `Show'
[string "@Bagnon/common/Wildpants/api/frames.lua"]:77: in function <Bagnon/common/Wildpants/api/frames.lua:76>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Bagnon/common/Wildpants/features/autoDisplay.lua"]:82: in function `ToggleBackpack'
[string "TOGGLEBACKPACK"]:1: in function <[string "TOGGLEBACKPACK"]:1>

Locals:
self = <table> {
 IsKeyring = <function> defined @Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:404
 FrameTemplate = "BackdropTemplate"
 IsRetail = true
 GetOwnerID = <function> defined @Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:284
 Frames = <table> {
 }
 Bagnon_ItemInfo = <table> {
 }
 Currency = <table> {
 }
 InBank = <function> defined @Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:381
 ItemGroup = <table> {
 }
 GeneralOptions = Frame {
 }
 RestoreItemData = <function> defined @Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:318
 Frame = <table> {
 }
 OptionsToggle = <table> {
 }
 Bag = <table> {
 }
 Bagnon_BoE = <table> {
 }
 IsBank = <function> defined @Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:408
 RegisterMessage = <function> defined @Accountant_Classic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Accountant_Classic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:153
 IsBagCached = <function> defined @Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:305
 Base = <table> {
 }
 UnregisterSignal = <function> defined @Bagnon/common/Wildpants/libs/WildAddon-1.0/WildAddon-1.0.lua:78
 GetOwnerAddress = <function> defined @Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:289
 RegisterEvent = <function> defined @Accountant_Classic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 sets = <table> {
 }
 OnEnable = <function> defined @Bagnon/common/Wildpants/Wildpants.lua:101
 Name = "Bagnon"
 IterateOwners = <function> defined @Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:128
 InGuild = <function> defined @Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:389
 Parented = <table> {
 }
 NewModule = <function> defined @Bagnon/common/Wildpants/libs/WildAddon-1.0/WildAddon-1.0.lua:68
 DisplayOptions = Frame {
 }
 ColorOptions = Frame {
 }
 IsBackpack = <function> defined @Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:396
 RestorePetLinkData = <function> defined @Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:372
 Item = <table> {
 }
 IsClassic = false
 OptionsGroup = <table> {
 }
 profile = <table> {
 }
 Bagnon_Uncollected = <table> {
 }
 OwnerSelector = <table> {
 }
 Bagnon_ItemLevel = <table> {
 }
 Commands = <table> {
 }
 Bagnon_Garbage = <table> {
 }
 SortButton = <table> {
 }
 ItemSlot = <table> {
 }
 InventoryFrame = <table> {
 }
 SearchToggle = <table> {
 }
 SearchFrame = <table> {
 }
 BagGroup = <table> {
 }
 BrokerCarrousel = <table> {
 }
 Events = <table> {
 }
 LDB = <table> {
 }
 TooltipCounts = <table> {
 }
 Title = <table> {
 }
 AutoDisplay = <table> {
 }
 Tag = "BAGNON_"
 GetItemInfo = <function> defined @Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:220
 IsBackpackBag = <function> defined @Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:400
 GetOwnerInfo = <function> defined @Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:88
 PickupItem = <function> defined @Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:264
 ShowOptions = <function> defined @Bagnon/common/Wildpants/Wildpants.lua:159
 UnregisterAllEvents = <function> defined @Accountant_Classic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:174
 BankFrame = <table> {
 }
 DropButton = <table> {
 }
 GetItemID = <function> defined @Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.lua:243
 IsReagents = <function> defined @Bagnon/common/Wildpants/libs/LibItemCache-2.0/LibItemCache-2.0.

**Comment by adavak** [comment]
https://github.com/tullamods/Wildpants/pull/91

try this.

**Comment by Az0na** [comment]
same error here.
41x ...s/Bagnon/common/Wildpants/features/tooltipCounts.lua:58: attempt to call method 'GetItem' (a nil value)
[string "@Bagnon/common/Wildpants/features/tooltipCounts.lua"]:58: in function <...s/Bagnon/common/Wildpants/features/tooltipCounts.lua:57>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:60: in function <SharedXML/Tooltip/TooltipDataHandler.lua:55>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:80: in function <SharedXML/Tooltip/TooltipDataHandler.lua:76>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <SharedXML/Tooltip/TooltipDataHandler.lua:106>
[string "=[C]"]: in function `SetAttribute'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:141: in function <SharedXML/Tooltip/TooltipDataHandler.lua:134>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:282: in function <SharedXML/Tooltip/TooltipDataHandler.lua:240>
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:237: in function <SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "=[C]"]: in function `ProcessInfo'
...
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:237: in function <SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetBagItem'
[string "@FrameXML/ContainerFrame.lua"]:1504: in function `ContainerFrameItemButton_OnEnter'
[string "@Bagnon/common/Wildpants/classes/item.lua"]:350: in function `UpdateTooltip'
[string "@Bagnon/common/Wildpants/classes/item.lua"]:185: in function <...faceBagnon/common/Wildpants/classes/item.lua:180>

**Comment by Revnn** [comment]
> [tullamods/Wildpants#91](https://github.com/tullamods/Wildpants/pull/91)
> 
> try this.

This works. Thanks
