### ISSUE TITLE
LUA Error Bagnon Bank Bags

### ISSUE THREAD

**Issue by Pownsamdi** [tullamods/Bagnon#1515]
**Running Software (issues missing this information will be deleted):**
 - Addon version: Bagnon-10.0.4 for WoW-10.0.2.zip
 - Server patch: 10.0.2 (46741)

 **Have you read the changelog? (please don't waste our time)**
Yes

**Describe the bug**
Right-Clicking Bank Bags (to change the default WoW auto sorting type e.g. Trade Goods, Equipment, etc. causes LUA Error)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Bagnon Bank Window
2. Right Click bag
3. See error

**Expected behaviour**
Being able to change the default blizzard bag types.

**Screenshots**
![Screenshot 2022-11-27 102917](https://user-images.githubusercontent.com/119159177/204128240-4680e635-a0d8-4296-a99d-6a99b159bee6.png)

**Error Logs**
Message: Interface/FrameXML/ContainerFrame.lua:492: attempt to call method 'IsCombinedBagContainer' (a nil value)
Time: Sun Nov 27 10:28:49 2022
Count: 1
Stack: Interface/FrameXML/ContainerFrame.lua:492: attempt to call method 'IsCombinedBagContainer' (a nil value)
[string "@Interface/FrameXML/ContainerFrame.lua"]:492: in function <Interface/FrameXML/ContainerFrame.lua:491>
[string "@Interface/FrameXML/ContainerFrame.lua"]:515: in function `initFunction'
[string "@Interface/SharedXML/UIDropDownMenu.lua"]:78: in function `UIDropDownMenu_Initialize'
[string "@Interface/SharedXML/UIDropDownMenu.lua"]:1164: in function `ToggleDropDownMenu'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bag.lua"]:86: in function <...rface/AddOns/Bagnon/common/Wildpants/classes/bag.lua:81>

Locals: containerFrame = CheckButton {
 FilterIcon = Frame {
 }
 Count = FontString {
 }
 link = "[Lightless Silk Pouch]"
 info = <table> {
 }
 frame = BagnonBankFrame1 {
 }
 Icon = Texture {
 }
 0 = <userdata>
}
level = 1
(*temporary) = nil
(*temporary) = CheckButton {
 FilterIcon = Frame {
 }
 Count = FontString {
 }
 link = "[Lightless Silk Pouch]"
 info = <table> {
 }
 frame = BagnonBankFrame1 {
 }
 Icon = Texture {
 }
 0 = <userdata>
}
(*temporary) = "attempt to call method 'IsCombinedBagContainer' (a nil value)"
ContainerFrame_IsGenericHeldBag = <function> defined @Interface/FrameXML/ContainerFrame.lua:49

**Comment by Jaliborc** [comment]
read changelog...
