### ISSUE TITLE
Separate reagent bag slot from normal bag slots

### ISSUE THREAD

**Issue by zeenk** [tullamods/Bagnon#1518]
Could we possibly get an option to have our reagent bag separated a bit from the other normal bag slots so it's easier to tell which slots are reagent and which are normal?

*pls don't judge my pro paint skills ;)* but something like this maybe?
Current:
![2022-11-27_20-18-33](https://user-images.githubusercontent.com/68170439/204155576-f41ca2bb-79cd-4faf-9647-acd44b53d676.png)

Suggestion:
![asd](https://user-images.githubusercontent.com/68170439/204155583-0fda71c6-d207-4250-9a2d-fbf19d1e2c2c.png)

**Comment by Harmonster** [comment]
I think it'll be enough just to add option to set background color specific for new reagent bag. I wish I could know how

**Comment by zeenk** [comment]
> 

This seem to have been added in latest beta update (or at least working now)
so u can change the color of reagent slots in color settings now.
https://www.curseforge.com/wow/addons/bagnon/files/4120159

**Comment by Veyska** [comment]
FWIW (and I may open a fresh ticket if having a reagent bag attached to my inventory with no easy way to distinguish between them annoys me), this is still a feature I'd love to see added.  I don't show slot backgrounds which means the "Color by Bag Type" does absolutely nothing, far as I can tell.  So while I still want the rest of my inventory (or my non-reagent bank) to be in one group, having the reagent bag(/tab) separated by a line break would be nice.  :-)
