### ISSUE TITLE
FrameXML errors

### ISSUE THREAD

**Issue by Stanzilla** [tullamods/Bagnon#167]
7/19 22:20:01.452  Loading add-on BagBrother
7/19 22:20:01.452  *\* Loading table of contents Interface\AddOns\BagBrother\BagBrother.toc
7/19 22:20:01.452  Error loading Interface\AddOns\BagBrother\Tests.lua
7/19 22:20:01.452  Loading add-on Bagnon
7/19 22:20:01.452  *\* Loading table of contents Interface\AddOns\Bagnon\Bagnon.toc
7/19 22:20:01.452  ++ Loading file Interface\AddOns\Bagnon\libs\libs.xml
7/19 22:20:01.452  Error loading Interface\AddOns\Bagnon\libs\Classy-1.0\Classy-1.0.lua
7/19 22:20:01.452  ++ Loading file Interface\AddOns\Bagnon\libs\LibItemCache-1.0\LibItemCache-1.0.xml
7/19 22:20:01.452  Error loading Interface\AddOns\Bagnon\libs\LibItemCache-1.0\Tests.lua
7/19 22:20:01.452  Error loading Interface\AddOns\Bagnon\libs\LibItemCache-1.0\Caches\BagBrotherTests.lua

**Comment by Sixthly** [comment]
![9d5cca](https://user-images.githubusercontent.com/1381367/42916595-6a7d910e-8b49-11e8-9e75-c397f518e844.png)
This issue has started appearing in-game for me. Any ideas?

**Comment by Stanzilla** [comment]
Those are the new file loading errors, just means the addon is trying to load Tests.lua because it is referenced in XML or TOC but the file is not there. To avoid it, just create an empty file at the place with that name.
