### ISSUE TITLE
Seperate Bank view / reagent bank view

### ISSUE THREAD

**Issue by Hunter-X-** [tullamods/Bagnon#232]
I was wondering if it'd be possible to have a button to toggle your bank view between your bank and your reagent bank?
My bank is full 28 slot bags, and when combined with the reagent bank takes up a vast amount of screen real estate.
I've seen ElvUI separate the two in such a way and was hoping it was something you'd consider.  At least, as an option.

**Comment by Phanx** [comment]
+1

It's just not possible to see everything at once without making the columns *much* wider than I want. I've currently resorted to just disabling the reagent bank "bag" unless I'm specifically looking for something in there, but that's hardly ideal.

**Comment by Jaliborc** [comment]
It's in the roadmap, it's gonna be there!

**Comment by Jaliborc** [comment]
Done, coming soon!
