### ISSUE TITLE
Ignore Bag and Set Bag Type

### ISSUE THREAD

**Issue by apologija** [tullamods/Bagnon#236]
Hello! I was wondering if there is a way, with the new blizzard sort and ignore bag functions, to specifically ignore bags or set them to equipment/tradeskill in bagnon? I love bagnon and the single window view, but I would also like to use the new blizzard functionality with the ability to sort as well as prevent certain bags from sorting. Is this already implemented or do you have plans to implement it?

Any help is appreciated, and thank you very much for this addon and your hard work.

**Comment by cherry-wave** [comment]
So, is this planned?
