### ISSUE TITLE
Request: LDB bag item count

### ISSUE THREAD

**Issue by ceylina** [tullamods/Bagnon#282]
Could you possibly put on a wish list to add a count to the LDB module instead of just "bagnon" in the text"

Using titan panel's bag module as an example/template would work great. The ability to either show free space or used space and total count would be super.

So for free space, let's say you have 100 slots and 20 are filled, it would show 80/100
For used in the same example it would show 20/100

I only ask because I am trying to ween off of titan panel (it's hard!) and I can't find a decent bag broker addon.

Oh last option to make it extra super would be the ability to toggle coloration by amount free (green, yellow, red) or disable coloration and just have it the color of the broker display's color (white, etc).

**Comment by Jaliborc** [comment]
Done
