### ISSUE TITLE
Request: "Manage Bank" Icon Option to Swap L/R-Click

### ISSUE THREAD

**Issue by menace97** [tullamods/Bagnon#304]
i sincerely love bagnon, but one thing i keep doing is left-clicking on "manage bank" icon thinking it would do what left-clicking on that icon in the bags does ("clean up").

i am humbly asking you add an option to flip this functionality. i know i'm not the only one that keeps depositing all my reagents into my bank when i simply meant to "clean up" my bank. it feels completely backward to me - an option so those who like it can leave it how it is would be very nice.

so one would left-click the "manage bank" icon to "clean up" the bank, and right-click the icon to "deposit all reagents."

thank you very much for your consideration. :)

**Comment by Jaliborc** [comment]
They will be separated, so declining this one
