### ISSUE TITLE
Bagnon doesn't place the items in the correct bag

### ISSUE THREAD

**Issue by Delerium69** [tullamods/Bagnon#310]
Hi

Since WoD, Bagnon has started placing all items looted into bag 4 - its driving me crazy :(

Some things i've done to try and fix:

1) I've ensured that no bags are 'assigned' to equipment/consumables/trade goods and that none of them are ignored.
2) I've try physically moving bags to different slots to see if it was bag specific (I have a full set of Royal Satchels).
3) I've exited game, deleted all settings and reinstalled a fresh bagnon and tried again - no success.

Is there a way to get all my loot to drop in the first available bag? Am I missing something incredibly simple here?

Thanks for a great addon.

Del

**Comment by Jaliborc** [comment]
Bagnon does not control it. That's a blizzard option.
