### ISSUE TITLE
missing argument from functions in sets.lua

### ISSUE THREAD

**Issue by Seerah** [tullamods/Bagnon#313]
In Combuctor_Sets\sets.lua, several functions (isUsable and isTradeGood) rely on the item's subType for sorting. However, this arg is not being passed through to the function.

ex.
local function isUsable(player, bagType, name, link, quality, level, ilvl, type)
needs to be
local function isUsable(player, bagType, name, link, quality, level, ilvl, type, **subType**)

**Comment by Seerah** [comment]
And you have two setRule functions named isTradeGood - the second overwrites the first, and you end up with Devices and Explosives on the Trade Goods tab.

**Comment by Jaliborc** [comment]
Good catch. Wrong repo though.

**Comment by Seerah** [comment]
I did notice that it this was the Bagnon repo and was slightly confused. You should probably change the link on the download page if this is not where you want tickets to go. ;)  Thought maybe because they shared the same code-base (at least at one time?) that the tickets were kept together.  /shrug
