### ISSUE TITLE
Items keep disappearing

### ISSUE THREAD

**Issue by Domek97** [tullamods/Bagnon#321]
For only a couple days now, when I open my bags to clean them i notice several rows of my items disappear. They go invisible and can't be touched until I close wow, update the addon, and enter the game again. Very frustrating to have to do every time i come back to town because my items are disappearing. I know this is the addon because its client side, whenever I disable the addon the items reappear in my inventory.

**Comment by medlir** [comment]
Have you tried just reloading the UI rather than restarting WoW?  /script ReloaduI();  I've noticed similar behavior when my video driver has crashed and reloaded... but a UI reload clears it up.

**Comment by Tannx1980** [comment]
Having the same issue with my bags, I have updated to 6.1.5.  My miner's coffee keep disappearing.  I can't get the work around to work like Domek97

**Comment by Tannx1980** [comment]
I just figured out what was happening it was an error on my part you can select which bags that you display at the top when the bags changer is highlighted and it one of my bags wasn't highlighted

**Comment by RainbowK** [comment]
I have this issue on a number of my characters. The first two lines (i have 12 items per row chosen as the default size)  of items are missing, I have to log out, turn off bagnon, log back in, and bring the items to my inventory. Then log out, turn on bagnon and log back in. Once logged back in I can NOT right click items and have them go into the inventory properly. If I right click they disappear, however if I drag them from my bag to my bank I can see them. If not, they seem missing. 

I spoke with Blizzard when my items were missing, (my complete transmog outfit) and they asked me to disable my addons and add them back one and a time, and see what happened. When I got to bagnon, I determined this add on to be the culpret.  Without it on my items showed just find in the bank, with it on, they appear to be missing. 

Please fix this as it can be quite annoying. Thank you
