### ISSUE TITLE
6.0.20 Using a slider under the options throws an error and causes it to display offscreen

### ISSUE THREAD

**Issue by MeatyChunks** [tullamods/Bagnon#326]
Under the Frame Settings, playing with the Item Scale slider throws an error and causes the rest of the menu to display offscreen. Switching from that menu and back will fix it.

Message: ...face\AddOns\Bagnon\libs\Sushi-3.0\Classes\Slider.lua:209: bad argument #1 to 'min' (number expected, got nil)
Time: 02/23/15 05:35:05
Count: 1
Stack: [C]: in function `min'
...face\AddOns\Bagnon\libs\Sushi-3.0\Classes\Slider.lua:209: in function `SetValue'
Interface\AddOns\Bagnon_Config\group.lua:114: in function `CreateInput'
Interface\AddOns\Bagnon_Config\group.lua:87: in function `CreateSlider'
Interface\AddOns\Bagnon_Config\group.lua:75: in function `CreatePercentSlider'
Interface\AddOns\Bagnon_Config\panels.lua:75: in function `call'
...AddOns\Bagnon\libs\Sushi-3.0\Classes\CallHandler.lua:54: in function `FireCall'
...rface\AddOns\Bagnon\libs\Sushi-3.0\Classes\Group.lua:61: in function `UpdateChildren'
...rface\AddOns\Bagnon\libs\Sushi-3.0\Classes\Group.lua:120: in function `call'
...AddOns\Bagnon\libs\Sushi-3.0\Classes\CallHandler.lua:54: in function `FireCall'
...face\AddOns\Bagnon\libs\Sushi-3.0\Classes\Slider.lua:154: in function `Update'
...face\AddOns\Bagnon\libs\Sushi-3.0\Classes\Slider.lua:148: in function <...face\AddOns\Bagnon\libs\Sushi-3.0\Classes\Slider.lua:146>

Locals: (*temporary) = nil
(*temporary) = 100
(*temporary) = "number expected, got nil"

**Comment by Jaliborc** [comment]
Duplicate
