### ISSUE TITLE
6.0.20 using the Columns Slider produces an error and only affect Inventory

### ISSUE THREAD

**Issue by Torsin** [tullamods/Bagnon#327]
When changing the Columns value the following error occurs.  Also adjusting this slider currently only affects the Inventory, attempting to change the Bank Columns actually changes the Inventory:

Date: 2015-02-22 23:08:26
ID: 2
Error occured in: Global
Count: 1
Message: ...face\AddOns\Bagnon\libs\Sushi-3.0\Classes\Slider.lua line 209:
   bad argument #1 to 'min' (number expected, got nil)
Debug:
   [C]: min()
   ...face\AddOns\Bagnon\libs\Sushi-3.0\Classes\Slider.lua:209: SetValue()
   Bagnon_Config\group.lua:114: CreateInput()
   Bagnon_Config\group.lua:87: CreateSlider()
   Bagnon_Config\group.lua:75: CreatePercentSlider()
   Bagnon_Config\panels.lua:75: call()
   ...AddOns\Bagnon\libs\Sushi-3.0\Classes\CallHandler.lua:54: FireCall()
   ...rface\AddOns\Bagnon\libs\Sushi-3.0\Classes\Group.lua:61: UpdateChildren()
   ...rface\AddOns\Bagnon\libs\Sushi-3.0\Classes\Group.lua:120: call()
   ...AddOns\Bagnon\libs\Sushi-3.0\Classes\CallHandler.lua:54: FireCall()
   ...face\AddOns\Bagnon\libs\Sushi-3.0\Classes\Slider.lua:154: Update()
   ...face\AddOns\Bagnon\libs\Sushi-3.0\Classes\Slider.lua:148:
      ...face\AddOns\Bagnon\libs\Sushi-3.0\Classes\Slider.lua:146
Locals:
(*temporary) = nil
(*temporary) = 100
(*temporary) = "number expected, got nil"

AddOns:
  Swatter, v5.21c.5521 (SanctimoniousSwamprat)
  NPCScan, v6.0.3.5
  AskMrRobot, v19
  AucAdvanced, v5.21c.5521 (SanctimoniousSwamprat)
  AucFilterBasic, v5.21c.5521 (SanctimoniousSwamprat)
  AucFilterOutlier, v5.21c.5521.5459(5.21c/embedded)
  AucMatchUndercut, v5.21c.5521.5507(5.21c/embedded)
  AucScanData, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatHistogram, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatiLevel, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatPurchased, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatSales, v5.21c.5521.5476(5.21c/embedded)
  AucStatSimple, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatStdDev, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatWOWEcon, v5.21c.5521.5323(5.21c/embedded)
  AucUtilAHWindowControl, v5.21c.5521.5347(5.21c/embedded)
  AucUtilAppraiser, v5.21c.5521.5495(5.21c/embedded)
  AucUtilAskPrice, v5.21c.5521.5447(5.21c/embedded)
  AucUtilAutoMagic, v5.21c.5521.5443(5.21c/embedded)
  AucUtilCompactUI, v5.21c.5521.5496(5.21c/embedded)
  AucUtilEasyBuyout, v5.21c.5521.5507(5.21c/embedded)
  AucUtilFixAH, v5.21c.5521 (SanctimoniousSwamprat)
  AucUtilItemSuggest, v5.21c.5521.5417(5.21c/embedded)
  AucUtilPriceLevel, v5.21c.5521.5458(5.21c/embedded)
  AucUtilScanButton, v5.21c.5521.5403(5.21c/embedded)
  AucUtilScanFinish, v5.21c.5521.5515(5.21c/embedded)
  AucUtilScanProgress, v5.21c.5521.4979(5.21c/embedded)
  AucUtilScanStart, v5.21c.5521.5347(5.21c/embedded)
  AucUtilSearchUI, v5.21c.5521.5515(5.21c/embedded)
  AucUtilSimpleAuction, v5.21c.5521.5514(5.21c/embedded)
  AucUtilVendMarkup, v5.21c.5521.4828(5.21c/embedded)
  Babylonian, v5.1.DEV.332(/embedded)
  BagBrother, v
  Bagnon, v6.0.20
  BagnonConfig, v6.0.20
  BeanCounter, v5.21c.5521 (SanctimoniousSwamprat)
  BestInSlot, vBeta 6.0.25
  BestInSlotWarlordsOfDraenor, vBeta 6.0.25
  Carbonite, v6.0.1
  CarboniteInfo, v1.0
  CarboniteNotes, v6.0.1
  CarboniteNotesSample, v1.0
  CarboniteQuests, v6.0.1
  CarboniteSocial, v6.0.1
  CarboniteWarehouse, v6.0.1
  CarboniteWeekly, v6.0.1
  Configator, v5.1.DEV.376(/embedded)
  DBMCore, v
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  DraenorTreasures, v
  Enchantrix, v5.21c.5521 (SanctimoniousSwamprat)
  EnchantrixBarker, v5.21c.5521 (SanctimoniousSwamprat)
  GTFO, v4.35.11
  Incognito, v1.4
  Informant, v5.21c.5521 (SanctimoniousSwamprat)
  InterruptSay, v3.5.1
  LibExtraTip, v5.12.DEV.363(/embedded)
  MarkingBar, v2.2.1
  MogIt, v3.4.0
  MyRareFinder, v1.0
  Omen, v3.1.9
  Postal, v3.5.1
  RaidSlackCheck, v1.49
  RazerAnansi, v2.7.0
  RazerNaga, v2.7.2
  RazerNagaCast, v
  RazerNagaConfig, v
  RazerNagaEncounter, v
  RazerNagaXP, v
  SimpleILevel, v3.2.16-alpha
  SimpleILevelGroup, v3.2.16-alpha
  SimpleILevelResilience, v3.2.16-alpha
  SimpleILevelSocial, v3.2.16-alpha
  Skada, vr607
  SlideBar, v5.21c.5521 (SanctimoniousSwamprat)
  Stubby, v5.21c.5521 (SanctimoniousSwamprat)
  TipHelper, v5.12.DEV.351(/embedded)
  TipTac, v15.01.14
  TipTacItemRef, v14.10.16
  TipTacTalents, v14.10.15
  WeakAuras, v2.0.9.9
  BlizRuntimeLib_enUS v6.0.3.60000 <none>
  (ck=c01)

**Comment by Stanzilla** [comment]
Yep, same here

```
1x ...faceBagnon\libs\Sushi-3.0\Classes\Slider.lua:209: bad argument #1 to 'min' (number expected, got nil)
[C]: in function `min'
...faceBagnon\libs\Sushi-3.0\Classes\Slider.lua:209: in function `SetValue'
Bagnon_Config\group-Group.lua:114: in function `CreateInput'
Bagnon_Config\group-Group.lua:87: in function `CreateSlider'
Bagnon_Config\group-Group.lua:75: in function `CreatePercentSlider'
Bagnon_Config\panels.lua:75: in function `call'
Bagnon\libs\Sushi-3.0\Classes\CallHandler.lua:54: in function `FireCall'
...rfaceBagnon\libs\Sushi-3.0\Classes\Group-Group.lua:61: in function `UpdateChildren'
...rfaceBagnon\libs\Sushi-3.0\Classes\Group-Group.lua:120: in function `call'
Bagnon\libs\Sushi-3.0\Classes\CallHandler.lua:54: in function `FireCall'
...faceBagnon\libs\Sushi-3.0\Classes\Slider.lua:154: in function `Update'
...faceBagnon\libs\Sushi-3.0\Classes\Slider.lua:148: in function <...faceBagnon\libs\Sushi-3.0\Classes\Slider.lua:146>

Locals:
self = SushiSlider1 {
 0 = <userdata>
 pattern = "%s"
 Label = SushiSlider1Text {
 }
 High = SushiSlider1High {
 }
 step = 1
 EditBox = <unnamed> {
 }
 Low = SushiSlider1Low {
 }
 EditBG = <unnamed> {
 }
 Prefix = <unnamed> {
 }
 calls = <table> {
 }
 value = 1
 sets = <table> {
 }
 frameCache = <table> {
 }
 Suffix = <unnamed> {
 }
}
value = nil
update = nil
minV = 1
maxV = 100
(*temporary) = <function> defined @Bagnon\libs\Sushi-3.0\Classes\Slider.lua:225
(*temporary) = SushiSlider1 {
 0 = <userdata>
 pattern = "%s"
 Label = SushiSlider1Text {
 }
 High = SushiSlider1High {
 }
 step = 1
 EditBox = <unnamed> {
 }
 Low = SushiSlider1Low {
 }
 EditBG = <unnamed> {
 }
 Prefix = <unnamed> {
 }
 calls = <table> {
 }
 value = 1
 sets = <table> {
 }
 frameCache = <table> {
 }
 Suffix = <unnamed> {
 }
}
(*temporary) = <function> defined =[C]:-1
```

**Comment by ceylina** [comment]
Can also confirm this

```
Message: ...face\AddOns\Bagnon\libs\Sushi-3.0\Classes\Slider.lua:209: bad argument #1 to 'min' (number expected, got nil)
Time: 02/23/15 12:39:46
Count: 1
Stack: [C]: in function `min'
...face\AddOns\Bagnon\libs\Sushi-3.0\Classes\Slider.lua:209: in function `SetValue'
Interface\AddOns\Bagnon_Config\group.lua:114: in function `CreateInput'
Interface\AddOns\Bagnon_Config\group.lua:87: in function `CreateSlider'
Interface\AddOns\Bagnon_Config\group.lua:75: in function `CreatePercentSlider'
Interface\AddOns\Bagnon_Config\panels.lua:75: in function `call'
...AddOns\Bagnon\libs\Sushi-3.0\Classes\CallHandler.lua:54: in function `FireCall'
...rface\AddOns\Bagnon\libs\Sushi-3.0\Classes\Group.lua:61: in function `UpdateChildren'
...rface\AddOns\Bagnon\libs\Sushi-3.0\Classes\Group.lua:120: in function `call'
...AddOns\Bagnon\libs\Sushi-3.0\Classes\CallHandler.lua:54: in function `FireCall'
...face\AddOns\Bagnon\libs\Sushi-3.0\Classes\Slider.lua:154: in function `Update'
...face\AddOns\Bagnon\libs\Sushi-3.0\Classes\Slider.lua:148: in function <...face\AddOns\Bagnon\libs\Sushi-3.0\Classes\Slider.lua:146>

Locals: (*temporary) = nil
(*temporary) = 100
(*temporary) = "number expected, got nil"
```

**Comment by Jaliborc** [comment]
Fixed
