### ISSUE TITLE
Double click to search bags throws error

### ISSUE THREAD

**Issue by slybootz** [tullamods/Bagnon#330]
I have disabled the search spyglass on my bagnon frame, and instead have always double clicked the top of the frame to open up the search text box.  Since the patch, double clicking throws an error, and even though the edit box appears, it's doesn't have focus until I click a third time.

Date: 2015-02-25 19:11:34
ID: 1
Error occured in: Global
Count: 4
Message: ..\AddOns\Bagnon\components\searchFrame.lua line 93:
   attempt to index field 'searchToggle' (a nil value)
Debug:
   [C]: ?
   Bagnon\components\searchFrame.lua:93: UpdateVisibility()
   Bagnon\components\searchFrame.lua:56:
      Bagnon\components\searchFrame.lua:53
   [C]: Show()
   ..\FrameXML\UIParent.lua:3037: UIFrameFade()
   ..\FrameXML\UIParent.lua:3058: UIFrameFadeIn()
   Bagnon\components\searchFrame.lua:85: SetShown()
   Bagnon\components\titleFrame.lua:52:
      Bagnon\components\titleFrame.lua:51
Locals:

AddOns:
  Swatter, v5.21c.5521 (SanctimoniousSwamprat)
  AddonChatMessageHider, v1.11
  Cursor, v6.1.0.1
  NPCScan, v6.1.0.1
  NPCScanOverlay, v6.1.0.1
  ABiggerBag, v
  Altoholic, vr152
  AskMrRobot, v20
  AtlasLoot, vv8.00.00beta7
  Auctionator, v3.2.2
  Aurora, v6.2
  BagBrother, v
  Bagnon, v6.0.21
  Bartender4, v4.6.7
  BattlegroundTargets, v60000-7
  BattlePetBreedID, vv1.3.2
  BigWigs, v4.800
  BigWigsRecordKills, v2.04
  BLCooldown, v3.62
  BuyEmAll, v3.2.3
  Chatter, v1.4.5-1-g3dbf5b9
  Clique, vv60000-1.0.0
  CustomPlayerPowerBarAlt, v1.4.7
  DataStore, vr52
  DataStoreAchievements, vr38
  DataStoreAgenda, vr20
  DataStoreAuctions, v6.0.001
  DataStoreCharacters, vr30
  DataStoreContainers, v6.0.002
  DataStoreCrafts, vr64
  DataStoreCurrencies, v6.0.002
  DataStoreGarrisons, vr8
  DataStoreInventory, vr41
  DataStoreMails, vr40
  DataStorePets, vr36
  DataStoreQuests, vr32
  DataStoreReputations, v6.0.002
  DataStoreSpells, v6.0.002
  DataStoreStats, v6.0.002
  DataStoreTalents, v6.0.002
  ExRT, v3200
  ExtraCD, v1.3
  FishingBuddy, v1.4w
  Fonter, v
  ForteCasting, v
  ForteClass, v
  ForteCooldown, v
  ForteCore, v1.980.8
  ForteHealthstone, v
  ForteSoulstone, v
  ForteSummon, v
  ForteTalent, v
  ForteTimer, v
  GladiatorlosSA, v2.0
  GladiusEx, v
  Gnosis, vv4.45
  Grid2, vr762
  Grid2LDB, vr762
  Grid2RaidDebuffs, vr762
  HandyNotes, vv1.3.3
  HandyNotesTreasureHunter, v1
  hfLootLog, v1.2.4
  hfLootRoll, v1.2.4
  IllusionPreview, v1.1
  LibExtraTip, v5.12.DEV.350(/embedded)
  MacroToolkit, v6.0.3.14
  Mapster, v1.6.2
  Masque, v6.0.0
  MasqueSleek, v6.0.0
  MikScrollingBattleText, v5.7.140
  MogIt, v3.4.0
  MoveAnything, v15.0.9
  MyRareFinder, v1.0
  Omen, v3.1.10
  Overachiever, v0.81
  OverachieverTabs, v0.81
  Paste, v1.4.1
  Peggle, v1.02c
  PetTracker, v6.0.17
  PetTrackerBreeds, v
  PetTrackerConfig, v
  PetTrackerSwitcher, v
  PetTrackerUpgrades, v
  PhoenixStyle, v
  PitBull4, vv4.0.0-beta54-18-g2bf727e
  PitBull4AltPowerBar, vv4.0.0-beta54-18-g2bf727e
  PitBull4Aura, vv4.0.0-beta54-18-g2bf727e
  PitBull4HealthBar, vv4.0.0-beta54-18-g2bf727e
  PitBull4HideBlizzard, vv4.0.0-beta54-18-g2bf727e
  PitBull4LeaderIcon, vv4.0.0-beta54-18-g2bf727e
  PitBull4LuaTexts, vv4.0.0-beta54-18-g2bf727e
  PitBull4MasterLooterIcon, vv4.0.0-beta54-18-g2bf727e
  PitBull4PowerBar, vv4.0.0-beta54-18-g2bf727e
  PitBull4RaidTargetIcon, vv4.0.0-beta54-18-g2bf727e
  PitBull4ReadyCheckIcon, vv4.0.0-beta54-18-g2bf727e
  PitBull4VoiceIcon, vv4.0.0-beta54-18-g2bf727e
  PlateBuffs, v1.18.1
  Postal, v3.5.1
  QuestCompletist, v101
  RaidAchievement, v
  RaidSlackCheck, v1.49
  Raven, vr336
  Reflux, v1.17
  Rhonin, v1.00
  SellJunk, v3.0.11
  SexyMap, v2.4.23
  Skada, v1.4-29
  SkadaCCTracker, v0.1
  SkadaJump, v1.0
  StatBlockDurability, v
  StatBlockLatency, v
  StatBlockCore, v
  StealPurgeDispel, v1.0.6
  SushiSort, v6.0.2.0
  ThogarAssist, v
  TidyPlates, v6.16.Beta9
  TidyPlatesGraphite, v
  TidyPlatesGrey, v
  TidyPlatesNeon, v
  TidyPlatesQuatre, v
  TidyPlatesThreatPlates, v7.013-Alpha
  TidyPlatesHub, v
  TidyPlatesWidgets, v
  TimelessLoot, v1.7.1
  TipTac, v15.01.14
  TipTacItemRef, v14.10.16
  TipTacTalents, v14.10.15
  TomTom, vv60000-1.1.1
  TouchysMedia, v1.0.1
  TradeSkillMaster, vv2.10.16
  TradeSkillMasterAccounting, vv2.4.2
  TradeSkillMasterAuctionDB, vv2.6.3
  TradeSkillMasterAuctioning, vv2.4.3
  TradeSkillMasterDestroying, vv2.1.10
  TradeSkillMasterItemTracker, vv2.1.1
  TradeSkillMasterMailing, vv2.2.10
  TradeSkillMasterShopping, vv2.4.3
  TradeSkillMasterWarehousing, vv2.1.1
  TrufiGCD, v
  WeakAuras, v2.1.0.0
  BlizRuntimeLib_enUS v6.1.0.60100 <none>
  (ck=e30)

**Comment by Jaliborc** [comment]
Invalid
