### ISSUE TITLE
6.0.21 - Settings lost after upgrade

### ISSUE THREAD

**Issue by Phanx** [tullamods/Bagnon#333]
After upgrading to Bagnon 6.0.21 from 6.0.16, all settings were reverted to their default values. It doesn't take that long to reconfigure things, but it also wouldn't be that hard to read the values from the old saved variable and copy them over either.

**Comment by Jaliborc** [comment]
yeah, its intended. Don't want to risk living and bug and corrupting people saved variables, and I don't really have the time right now.

Sorry

**Comment by Phanx** [comment]
Might be good to add a warning to the download page and/or changelog, so people know it's intentional and not a bug.
