### ISSUE TITLE
Global settings

### ISSUE THREAD

**Issue by Phanx** [tullamods/Bagnon#334]
Now that the settings aren't stored in a per-character saved variable, can we finally get an option to use the same settings on all characters?

Currently (in 6.0.21) it actually looks like some settings (eg. which buttons to display on the windows) are being saved globally, but other settings (eg. scale, spacing, number of columns) are not, which is a bit strange.

A full-fledged profile system isn't necessary at all, but just a simple "Use character settings" checkbox like on the default Key Bindings window would do nicely.

**Comment by Stanzilla** [comment]
Yes please.

**Comment by Jaliborc** [comment]
@Phanx @Stanzilla
I was thinking of being able to copy the settings from another character.
Would a "global settings vs character settings" be better or worse than that?
Looking for opinions.

**Comment by Stanzilla** [comment]
Better, I think

**Comment by Phanx** [comment]
Much better. If I make a change on one character, I don't want to have to "copy from" on every other character. At that point the "copy from" feature isn't even saving me any time versus simply making the same change, which is what I want to avoid in the first place by using global settings.

In past versions I just edited the TOC to save the settings globally instead of per-character, and that produced the desired effect, but that isn't possible anymore, so it would be nice to have something official in the addon instead of having to hack on it after every update.

**Comment by Jaliborc** [comment]
Ok, lets go with that then

**Comment by ChloeMarie** [comment]
I want 'per character' settings back. I use different settings based on class/professions. Having some settings change globally is incredibly frustrating.

**Comment by beringtom** [comment]
A tickbox to use a "global setting" then both global and per char would still be usable :)

**Comment by ChloeMarie** [comment]
That would be perfect :)

**Comment by menace97** [comment]
this is a great idea, i agree - having the "best of both worlds" would be ideal. thanks :)

**Comment by Jaliborc** [comment]
Implemented! :D Sorry for the delay.
