### ISSUE TITLE
Double right-click on searchbar creates an LUA error

### ISSUE THREAD

**Issue by Strator** [tullamods/Bagnon#336]
Message: Interface\AddOns\Bagnon\components\searchFrame.lua:93: attempt to index field 'searchToggle' (a nil value)
Time: 02/26/15 18:20:12
Count: 3
Stack: Interface\AddOns\Bagnon\components\searchFrame.lua:93: in function `UpdateVisibility'
Interface\AddOns\Bagnon\components\searchFrame.lua:62: in function <Interface\AddOns\Bagnon\components\searchFrame.lua:61>
[C]: in function `Hide'
Interface\AddOns\Bagnon\components\searchFrame.lua:72: in function <Interface\AddOns\Bagnon\components\searchFrame.lua:71>

Locals: self = <unnamed> {
 0 = <userdata>
 fadeInfo = <table> {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = BagnonFrameinventory {
 frameID = "inventory"
 moneyFrame = BagnonFrameinventoryMoneyFrame {
 }
 itemFrame = <unnamed> {
 }
 searchFrame = <unnamed> {
 }
 shownCount = 1
 width = 156
 profile = <table> {
 }
 closeButton = BagnonFrameinventoryCloseButton {
 }
 titleFrame = <unnamed> {
 }
 height = 60.000001907349
 0 = <userdata>
 menuButtons = <table> {
 }
 bagToggle = <unnamed> {
 }
}
(*temporary) = nil
(*temporary) = "attempt to index field 'searchToggle' (a nil value)"

**Comment by Jaliborc** [comment]
Fixed
