### ISSUE TITLE
Bag item icons overlapping.

### ISSUE THREAD

**Issue by playerlin** [tullamods/Bagnon#340]
When I open my bank and my bag show out the same time(if their frame are overlapping each other), like this screenshot: 
https://sites.google.com/site/playerlin/2015-02-26_00001.jpg

You can see some item icons on bag and bank are overlapping each other and too hard to finger out what's the item is unless I close one frame or make frame smaller, I guess it's because frame priority or something...and in beta versions don't have any of options for that... happens on 6.0.20/6.0.21 and 6.1.0 beta.

**Comment by Jaliborc** [comment]
Fixed
