### ISSUE TITLE
6.1 update problem

### ISSUE THREAD

**Issue by rruggles** [tullamods/Bagnon#341]
ince the 6.1 update when right-clicking on an item to send it to the bank the items fill from the left-to-right, not top-to-bottom like they used to. I disabled Bagnon just in case Blizz changed something but found it goes top-to-bottom in the Blizz guild bank frame.

I also discovered that when clicking on items in the Guild bank to send them to your bags the ore and herbs are not going to their respective bags (I have one of each on my rogue).

Please, please, please change it back to top-to-bottom filling. This left to right filling is for the birds.

Thanks and Cheers!

**Comment by Jaliborc** [comment]
Fixed
