### ISSUE TITLE
Background color alpha ignored

### ISSUE THREAD

**Issue by Phanx** [tullamods/Bagnon#343]
Bagnon 6.0.21. When changing the alpha channel of the background color, the opacity of the frame background does not change accordingly. Happens on both inventory and bank frames.

**Comment by Jaliborc** [comment]
Do you mean 6.1.0?

**Comment by Phanx** [comment]
No, 6.1 wasn't available when I submitted the ticket. I updated today, and assumed the fix for this issue it contained was due to this ticket. :P
