### ISSUE TITLE
bagnon error 02.03.2015

### ISSUE THREAD

**Issue by mking8** [tullamods/Bagnon#348]
Date: 2015-03-02 12:39:31
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Bagnon\common\core\classes.lua line 52:
   attempt to index a nil value
Debug:
   Bagnon\common\core\classes.lua:52: GetFrameID()
   Bagnon_Facade\Bagnon_Facade.lua:30: SetParent()
   Bagnon\common\components\item.lua:202: SetTarget()
   ...erface\AddOns\Bagnon\common\components\itemFrame.lua:142:
      ...erface\AddOns\Bagnon\common\components\itemFrame.lua:108
Locals:
self = BagnonItemSlot1 {
 0 = <userdata>
 BattlepayItemTexture = <unnamed> {
 }
 Border = <unnamed> {
 }
 Flash = <unnamed> {
 }
 IconBorder = <unnamed> {
 }
 flashAnim = <unnamed> {
 }
 icon = BagnonItemSlot1IconTexture {
 }
 JunkIcon = <unnamed> {
 }
 NewItemTexture = <unnamed> {
 }
 QuestBorder = BagnonItemSlot1IconQuestTexture {
 }
 Count = BagnonItemSlot1Count {
 }
 newitemglowAnim = <unnamed> {
 }
 flash = <unnamed> {
 }
 searchOverlay = BagnonItemSlot1SearchOverlay {
 }
 Cooldown = BagnonItemSlot1Cooldown {
 }
 SplitStack = <function> defined @Interface\FrameXML\ContainerFrame.lua:884
}
(*temporary) = nil
(*temporary) = BagnonItemSlot1 {
 0 = <userdata>
 BattlepayItemTexture = <unnamed> {
 }
 Border = <unnamed> {
 }
 Flash = <unnamed> {
 }
 IconBorder = <unnamed> {
 }
 flashAnim = <unnamed> {
 }
 icon = BagnonItemSlot1IconTexture {
 }
 JunkIcon = <unnamed> {
 }
 NewItemTexture = <unnamed> {
 }
 QuestBorder = BagnonItemSlot1IconQuestTexture {
 }
 Count = BagnonItemSlot1Count {
 }
 newitemglowAnim = <unnamed> {
 }
 flash = <unnamed> {
 }
 searchOverlay = BagnonItemSlot1SearchOverlay {
 }
 Cooldown = BagnonItemSlot1Cooldown {
 }
 SplitStack = <function> defined @Interface\FrameXML\ContainerFrame.lua:884
}
(*temporary) = "attempt to index a nil value"

AddOns:
  Swatter, v5.21c.5521 (SanctimoniousSwamprat)
  Cursor, v6.1.0.1
  AskMrRobot, v19
  AtlasLoot, vv8.00.00beta7
  AucAdvanced, v5.21c.5521 (SanctimoniousSwamprat)
  AucFilterBasic, v5.21c.5521 (SanctimoniousSwamprat)
  AucFilterOutlier, v5.21c.5521.5459(5.21c/embedded)
  AucMatchUndercut, v5.21c.5521.5507(5.21c/embedded)
  AucStatHistogram, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatiLevel, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatPurchased, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatSales, v5.21c.5521.5476(5.21c/embedded)
  AucStatSimple, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatStdDev, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatWOWEcon, v5.21c.5521.5323(5.21c/embedded)
  AucUtilAHWindowControl, v5.21c.5521.5347(5.21c/embedded)
  AucUtilAppraiser, v5.21c.5521.5495(5.21c/embedded)
  AucUtilAskPrice, v5.21c.5521.5447(5.21c/embedded)
  AucUtilAutoMagic, v5.21c.5521.5443(5.21c/embedded)
  AucUtilCompactUI, v5.21c.5521.5496(5.21c/embedded)
  AucUtilEasyBuyout, v5.21c.5521.5507(5.21c/embedded)
  AucUtilFixAH, v5.21c.5521 (SanctimoniousSwamprat)
  AucUtilItemSuggest, v5.21c.5521.5417(5.21c/embedded)
  AucUtilPriceLevel, v5.21c.5521.5458(5.21c/embedded)
  AucUtilScanButton, v5.21c.5521.5403(5.21c/embedded)
  AucUtilScanFinish, v5.21c.5521.5515(5.21c/embedded)
  AucUtilScanProgress, v5.21c.5521.4979(5.21c/embedded)
  AucUtilScanStart, v5.21c.5521.5347(5.21c/embedded)
  AucUtilSearchUI, v5.21c.5521.5515(5.21c/embedded)
  AucUtilSimpleAuction, v5.21c.5521.5514(5.21c/embedded)
  AucUtilVendMarkup, v5.21c.5521.4828(5.21c/embedded)
  autoturnin, v4.5.N
  Babylonian, v5.1.DEV.332(/embedded)
  BadBoy, v12.521
  BagBrother, v
  Bagnon, v6.1.1
  BagnonFacade, v13
  BeanCounter, v5.21c.5521 (SanctimoniousSwamprat)
  BigWigs, v4.803
  CLCDK, v6.0.3
  Configator, v5.1.DEV.376(/embedded)
  CurrencySorter, v
  DebuffFilter, v5.4.0.1
  DebugLib, v5.1.DEV.337(/embedded)
  Enchantrix, v5.21c.5521 (SanctimoniousSwamprat)
  EnchantrixBarker, v5.21c.5521 (SanctimoniousSwamprat)
  epgp, vv5.11.6
  epgplootmaster, v0.6.64
  epgplootmasterml, v0.6.64
  ErrorFilter, v2.12
  ExtraCD, v1.3
  gUI4, v4.0.Release-r103
  gUI4ActionBars, v4.0.Release-r90
  gUI4Auras, v4.0.Release-r33
  gUI4CastBars, v4.0.Release-r35
  gUI4Chat, v4.0.Release-r39
  gUI4DevTools, v4.0.Release-r12
  gUI4FontChanger, v4.0.Release-r9
  gUI4Minimap, v4.0.Release-r46
  gUI4Objectives, v4.0.Release-r43
  gUI4Tooltip, v4.0.Release-r40
  gUI4Trade, v4.0.Release-r13
  gUI4UnitFrames, v4.0.Release-r70
  HandyNotes, vv1.3.3
  HandyNotesDraenorTreasures, v1.09b
  HandyNotesHigherLearning, v6.1.0.3
  Informant, v5.21c.5521 (SanctimoniousSwamprat)
  JSHB, vv4.35
  KuiNameplates, v
  KuiNameplatesAuras, v
  LibExtraTip, v5.12.DEV.363(/embedded)
  LibSharedMedia30, v3.0-91
  LootersAid, vv6.0.0.0
  MacroToolkit, v6.0.3.14
  Masque, v6.1.0
  MasqueGoldpaw, v1.0.Release-r2
  MBB, v
  Misspelled, v1.6.0
  oRA3, v
  Postal, v3.5.4
  Prat30, v3.5.14      
  Prat30Libraries, v
  SayMassRez, v2014-10-15
  SharedMedia, v3.0.5-186
  SilverDragon, vv3.1.5
  Skada, v1.4-29
  SkadaForTanks, v50400.1.2
  SlideBar, v5.21c.5521 (SanctimoniousSwamprat)
  StrataFix, v3.5.0
  Stubby, v5.21c.5521 (SanctimoniousSwamprat)
  SuccessfulInterruptAnnouncer, v1.7
  ThogarAssist, v
  TipHelper, v5.12.DEV.351(/embedded)
  TomTom, vv60000-1.1.1
  WeakAuras, v2.1.0.0
  WoWDBProfiler, v
  BlizRuntimeLib_enUS v6.1.0.60100 <none>
  (ck=d48)

**Comment by basten1899** [comment]
6.1.1 still not support Bagnon_Facade
