### ISSUE TITLE
Bank Deposit Issue (v6.1.1)

### ISSUE THREAD

**Issue by Burn64** [tullamods/Bagnon#351]
Hello there,

After I updated to v6.1.1 despite the fact that I had to do all settings again on each character, I noticed a bug when depositing items to bank. I can't see the items deposited in real time. They only show when I re-open bank frame, so each time I move or deposit something in bank/regeant bag I have to re-open it to see the changes. Also I have a few suggestions if you wanna consider them.

1. Adding a button on top (near search and others) to quick switch between normal bank and regeant bank when "Separate Regeant Bank" option is enabled.
2. Adding character profiles, allowing us to choose global settings or individual settings.

**Comment by jacobsenj** [comment]
I can confirm that the bank window is not updating, no matter if you add new items to the bank or move items within the bank. You have to close and reopen the bank to see the updates.

**Comment by Jaliborc** [comment]
Duplicate
