### ISSUE TITLE
Left Click = Right Click and viceversa (6.1.1)

### ISSUE THREAD

**Issue by jacobsenj** [tullamods/Bagnon#353]
It says "Shift-left click to open the chars bank" on the inventary but it opens the config when doing so. Shift-right opens it apparently.

Also the sort button is sorting on left-click instead on right and is storing all materials on right instead of left clicking.

**Comment by Flauschie** [comment]
Was about to report the same...

**Comment by Jaliborc** [comment]
All the behaviour matches the tooltips of the buttons
