### ISSUE TITLE
Guild Bank Tab Settings

### ISSUE THREAD

**Issue by s32ialx** [tullamods/Bagnon#354]
I suggest adding an option to 

1: either turn off the withdrawal limit completely so that the Icons can be shown (covered in text whats the point of setting a custom one)

And or

2: move where the withdrawal limit is located.
![image](https://cloud.githubusercontent.com/assets/1750708/6453020/e23d82a4-c107-11e4-8808-49f032e50e65.png)

**Comment by Jaliborc** [comment]
Declined

**Comment by s32ialx** [comment]
so your add-on is removed as you not only declined a very nice feature but you didn't even have the decency to give an explanation as to why you declined it 'to lazy is the only reason I can see' i'll just go back to OneBag I used the first but I gave you a shot but you're attitude ain't worth giving you anything.
