### ISSUE TITLE
6.1 update bug

### ISSUE THREAD

**Issue by dmdave** [tullamods/Bagnon#355]
Date: 2015-03-02 16:46:24
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Bagnon\components\frame.lua line 121:
   attempt to perform arithmetic on local 'x' (a nil value)
Debug:
   Bagnon\components\frame.lua:121: UpdateScale()
   Bagnon\components\frame.lua:101: Update()
   Bagnon\components\frame.lua:80:
      Bagnon\components\frame.lua:77
   [C]: Show()
   Bagnon\components\frame.lua:61: ShowFrame()
   Bagnon\main.lua:91: ShowFrame()
   Bagnon_GuildBank\main.lua:14: ?()
   ...non\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:147:
      ...non\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:147
   [string "safecall Dispatcher[1]"]:4:
      [string "safecall Dispatcher[1]"]:4
   [C]: ?
   [string "safecall Dispatcher[1]"]:13: ?()
   ...non\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:92: Fire()
   ...ace\AddOns\Bagnon\libs\AceEvent-3.0\AceEvent-3.0.lua:52:
      ...ace\AddOns\Bagnon\libs\AceEvent-3.0\AceEvent-3.0.lua:51
Locals:
self = BagnonFrameguild {
 profile = <table> {
 }
 frameID = "guild"
 shownCount = 1
 0 = <userdata>
}
oldScale = 1.1499999761581
newScale = 1.15
point = "CENTER"
x = nil
y = nil
ratio = 1.0000000207321
(*temporary) = <function> defined @Interface\AddOns\Bagnon\components\frame.lua:165
(*temporary) = BagnonFrameguild {
 profile = <table> {
 }
 frameID = "guild"
 shownCount = 1
 0 = <userdata>
}
(*temporary) = "CENTER"
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on local 'x' (a nil value)"

AddOns:
  Swatter, v5.0.0 (<%codename%>)
  NPCScan, v6.1.0.2
  NPCScanOverlay, v6.1.0.1
  NPCScanOverlayBroker, v1.2.5
  ACP, v3.4.15 
  Auctionator, v3.2.3
  Babylonian, v5.1.DEV.332(/embedded)
  BagBrother, v
  Bagnon, v6.1.1
  BagnonConfig, v6.1.1
  BagnonGuildBank, v6.1.1
  Bartender4, v4.6.7
  BattlegroundTargets, v60100-1
  Configator, v5.1.DEV.376(/embedded)
  Coordinates, v1.18
  DBMBattlefieldBarrens, v
  DBMCore, v
  DBMDefaultSkin, v
  DBMInterrupts, v6.0.0b
  DBMLDB, v
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  DBMVictorySound, v1.10.00b
  Gatherer, v5.0.0
  GathererHUD, v5.0.0
  HealersHaveToDie, v2.3.5
  NugComboBar, v
  NugComboBarGUI, v
  Prat30, v3.5.14      
  Prat30Libraries, v
  PVPSound, v4.0.0
  Skada, v1.4-29
  SkadaCCTracker, v0.1
  SlideBar, v5.0.0 (<%codename%>)
  TipTac, v15.01.14
  TipTacItemRef, v14.10.16
  TipTacTalents, v14.10.15
  BlizRuntimeLib_enUS v6.1.0.60100 <none>
  (ck=38e)

**Comment by Leahira** [comment]
I am also having exactly the same issue.

**Comment by Vikirnoff** [comment]
Same here

**Comment by Jaliborc** [comment]
Fixed
