### ISSUE TITLE
6.1.3 beta Void storage requires opening twice to view items

### ISSUE THREAD

**Issue by ceylina** [tullamods/Bagnon#356]
So when I log into a character and go to use the void storage, I have to open it then close it and open it again to see the contents of my void storage.

Once I have loaded the void storage once, it shows fine until of course, I log out. In the grand scheme of things this is minor but I wanted to report it anyway.

**Comment by Jaliborc** [comment]
Should be fixed in 6.1.4.
Can you confirm @ceylina? I don't experience the issue myself.

**Comment by Steil1** [comment]
Experienced this issue today. In addition, when Ctrl-clicking an item to preview in void storage it picks it up instead.

**Comment by Jaliborc** [comment]
I'm experiencing it myself now as well! Great news, easier to fix!

**Comment by Jaliborc** [comment]
Fixed!
