### ISSUE TITLE
6.1.3 beta settings - guild bank

### ISSUE THREAD

**Issue by ceylina** [tullamods/Bagnon#357]
So opening the guild bank and clicking on settings opens frame settings. The issue is that the pull down menu under "Frame" is not populated but the settings itself are for the guild bank. If you choose "guild bank" in the drop down menu it shows a blank frame settings.

Minor issue

**Comment by Jaliborc** [comment]
Fixed!

**Comment by Jaliborc** [comment]
Thanks for all the feedback so far @ceylina, has been a great help
