### ISSUE TITLE
6.1.3 tooltip behavior doesn't match clicks

### ISSUE THREAD

**Issue by Flauschie** [tullamods/Bagnon#360]
On bank: Leftclick = Sort bank (tooltip = store items) || Rightclick = store items (tooltip =  sort bank)
On bag: shift-leftclick = show configuration menu (tooltip =  show bank) || rightclick = show bank (tooltip =  show configuration menu)

german local

**Comment by Jaliborc** [comment]
German locale is not handled by me and possibly outdated. I don't speak german.

**Comment by Flauschie** [comment]
So did you make the change as noted above? I mean is it intented that the behavior of clicks is so different now?

**Comment by Jaliborc** [comment]
Some behaviour changed

**Comment by Flauschie** [comment]
Alright, thanks for the information. Don't understand why but I try to adapt to it until the locale is fixed... Wish I would have the time, maybe later this day

**Comment by Jaliborc** [comment]
Someone updated it as we speak ;)
