### ISSUE TITLE
Can't access Void Storage after updating to 6.1.4

### ISSUE THREAD

**Issue by Tannx1980** [tullamods/Bagnon#361]
I am still having issue with Void Storage after Updating to 6.1.4.  Here is the error Message I get.
Message: Interface\AddOns\Bagnon\common\components\bag.lua:53: Usage: BagnonBagvault:SetID(ID)
Time: 03/04/15 07:47:56
Count: 2
Stack: [C]: ?
[C]: in function `SetID'
Interface\AddOns\Bagnon\common\components\bag.lua:53: in function `New'
...terface\AddOns\Bagnon\common\components\bagFrame.lua:17: in function `New'
Interface\AddOns\Bagnon\components\frame.lua:405: in function `CreateBagFrame'
Interface\AddOns\Bagnon\components\frame.lua:416: in function `PlaceBagFrame'
Interface\AddOns\Bagnon\components\frame.lua:246: in function `Layout'
Interface\AddOns\Bagnon\components\frame.lua:106: in function `Update'
Interface\AddOns\Bagnon\components\frame.lua:80: in function `OnShow'
...rface\AddOns\Bagnon_VoidStorage\components\frame.lua:20: in function <...rface\AddOns\Bagnon_VoidStorage\components\frame.lua:19>
[C]: in function `Show'
Interface\AddOns\Bagnon\components\frame.lua:61: in function `ShowFrame'
Interface\AddOns\Bagnon\main.lua:91: in function `ShowFrame'
Interface\AddOns\Bagnon_VoidStorage\main.lua:16: in function `?'
...ory\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145: in function <...ory\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...ory\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...ace\AddOns\Bagnon\libs\AceEvent-3.0\AceEvent-3.0.lua:52: in function <...ace\AddOns\Bagnon\libs\AceEvent-3.0\AceEvent-3.0.lua:51>
[C]: in function `TurnOrActionStop'
[string "TURNORACTION"]:4: in function <[string "TURNORACTION"]:1>

Locals: 
Here the addons I use other then Bagon Armory, Auctionator Deadly Boss Mods, Handynotes, Handnotes Draenor Treasures, Recount, Tomtom

**Comment by Jaliborc** [comment]
That button should not be there.... lol. Fixed!
