### ISSUE TITLE
Still not quite right but thank you so much for answering so fast ! :D 

### ISSUE THREAD

**Issue by Vazziera** [tullamods/Bagnon#362]
I am not sure what exactly you did but I still am not able to do what I was doing before. I have attached a screen shot of what I did before ( I would turn off the guild bank part because that would interfere with my OCD officers organization of the guild bank but see what I mean thru the pictures) and I would use the mass the bags together for my personal bank but leaving the inventory bags more alone as seen in the picture. Is there a way to do this through the addon again? I have tried turning each section of bagnon on.. and off and any combination of them inbetween and still can't do what is in the picture unless I completely turn it off. Thanks for any help!
![wowscrnshot_021615_112838](https://cloud.githubusercontent.com/assets/11305400/6489784/da949352-c266-11e4-905e-09a8e6d19f20.jpg)

**Comment by Jaliborc** [comment]
1) Enable "Display Blizzard Frames for Hidden Bags" in general options
2) Open Bagnon bag frame
3) Click on each bag to disable it
4) Close the frame
5) Bags should display as such now

Does this works @Vazziera **on the latest version**?

**Comment by Vazziera** [comment]
It seems to be working! Thank you so much.I want to say what a wonderful addon you have and I didn't quite appreciate how much till I started looking for an alternative if this hadn't worked. As soon as I am able I plan to make a contribution to show my gratitude! Keep up the great work! Thanks so much again. 
 

     On Wednesday, March 4, 2015 11:28 PM, João Cardoso <notifications@github.com> wrote:
   
 

 1) Enable "Display Blizzard Frames for Hidden Bags" in general options
2) Open Bagnon bag frame
3) Click on each bag to disable it
4) Close the frame
5) Bags should display as such nowDoes this works @Vazziera on the latest version?—

**Comment by Jaliborc** [comment]
Ok, great!! :D
