### ISSUE TITLE
Stall during bag sorting

### ISSUE THREAD

**Issue by Gnarfoz** [tullamods/Bagnon#364]
When using the Blizzard "clean up bags" functionality, the game stalls for a moment.
The more there's to do, the longer the stall. A messy bank can take quite a bit.

Because the UI runs in the main render thread, any excessively long actions taken by addons can slow or even stop the rendering, resulting in low fps or stutters/stalls.
This seems to be one such case.

Easy test case:
Swap one of your empty bags with a full one, so the "clean up bags" function actually has something to clean up.

Currently using: 6.1.4
This didn't happen before: 6.0.20.

**Comment by Jaliborc** [comment]
Not handled by Bagnon, handled by item server
