### ISSUE TITLE
Disable for bank?

### ISSUE THREAD

**Issue by neploxo** [tullamods/Bagnon#365]
Today's update appears to have forced Bagnon onto my bank window. I prefer the Blizzard UI for the bank. Why did it force itself on me, and how do I undo that? I previously had the bank option unchecked, but now I do not see it.

**Comment by Jaliborc** [comment]
When someone forces itself onto you, you should report him/her for sexual assault. Just saying.

Jokes aside, fixed any related issues. Just make sure you disable the bank frame on bagnon options.
