### ISSUE TITLE
Errors when opening well bank, bags etc etc

### ISSUE THREAD

**Issue by we-are-borg** [tullamods/Bagnon#369]
Date: 2015-03-08 13:12:10
ID: 1
Error occured in: Global
Count: 1
Message: ...AddOns\Bagnon_AccountSearch\Bagnon_AccountSearch.lua line 187:
   attempt to index field 'FrameSettings' (a nil value)
Debug:
   ...AddOns\Bagnon_AccountSearch\Bagnon_AccountSearch.lua:187: GetBagnonVariableLinks()
   ...AddOns\Bagnon_AccountSearch\Bagnon_AccountSearch.lua:207: UpdateVisibility()
   ...AddOns\Bagnon_AccountSearch\Bagnon_AccountSearch.lua:60: OnHide()
   Bagnon\components\inventory.lua:17:
      Bagnon\components\inventory.lua:16
   [C]: Hide()
   Bagnon\components\frame.lua:69: HideFrame()
   Bagnon\main.lua:102: ?()
   ...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:145:
      ...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:145
   [string "safecall Dispatcher[1]"]:4:
      [string "safecall Dispatcher[1]"]:4
   [C]: ?
   [string "safecall Dispatcher[1]"]:13: ?()
   ...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:92: Fire()
   ...ace\AddOns\TomTom\libs\AceEvent-3.0\AceEvent-3.0.lua:120:
      ...ace\AddOns\TomTom\libs\AceEvent-3.0\AceEvent-3.0.lua:119
   [C]: CloseTradeSkill()
   [string "*:OnHide"]:1:
      [string "*:OnHide"]:1
   [C]: Hide()
   ..\FrameXML\UIParent.lua:2089: SetUIPanel()
   ..\FrameXML\UIParent.lua:2165: HideUIPanel()
   ..\FrameXML\UIParent.lua:1824:
      ..\FrameXML\UIParent.lua:1816
   [C]: SetAttribute()
   ..\FrameXML\UIParent.lua:2595: HideUIPanel()
   ..\SharedXML\SharedUIPanelTemplates.lua:392: HideParentPanel()
   ..\SharedXML\SharedUIPanelTemplates.lua:177:
      ..\SharedXML\SharedUIPanelTemplates.lua:171
Locals:
self = BagnonAccountSearchFrame {
 UpdateVisibility = <function> defined @Interface\AddOns\Bagnon_AccountSearch\Bagnon_AccountSearch.lua:206
 SetFrameLayer = <function> defined @Interface\AddOns\Bagnon_AccountSearch\Bagnon_AccountSearch.lua:164
 GuildBankToggle = <function> defined @Interface\AddOns\Bagnon_AccountSearch\Bagnon_AccountSearch.lua:100
 BagSearch_OnUpdate = <function> defined @Interface\AddOns\Bagnon_AccountSearch\Bagnon_AccountSearch.lua:146
 minFrameSearchStringLength = 2
 ShowSearch = <function> defined @Interface\AddOns\Bagnon_AccountSearch\Bagnon_AccountSearch.lua:684
 GetBagnonVariableLinks = <function> defined @Interface\AddOns\Bagnon_AccountSearch\Bagnon_AccountSearch.lua:184
 New = <function> defined @Interface\AddOns\Bagnon_AccountSearch\Bagnon_AccountSearch.lua:498
 AccountSearch_Toggle = <function> defined @Interface\AddOns\Bagnon_AccountSearch\Bagnon_AccountSearch.lua:120
 CreateItemSlot = <function> defined @Interface\AddOns\Bagnon_AccountSearch\Bagnon_AccountSearch.lua:616
 IsBankSlot = <function> defined @Interface\AddOns\Bagnon_AccountSearch\Bagnon_AccountSearch.lua:156
 items = <table> {
 }
 0 = <userdata>
 AttachToggle = <function> defined @Interface\AddOns\Bagnon_AccountSearch\Bagnon_AccountSearch.lua:112
 Print = <function> defined @Interface\AddOns\Bagnon_AccountSearch\Bagnon_AccountSearch.lua:699
 UpdateItems = <function> defined @Interface\AddOns\Bagnon_AccountSearch\Bagnon_AccountSearch.lua:302
 AddItemName = <function> defined @Interface\AddOns\Bagnon_AccountSearch\Bagnon_AccountSearch.lua:257
 Resize = <function> defined @Interface\AddOns\Bagnon_AccountSearch\Bagnon_AccountSearch.lua:243
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'FrameSettings' (a nil value)"

AddOns:
  Swatter, v5.21c.5521 (SanctimoniousSwamprat)
  NPCScan, v6.1.0.2
  AckisRecipeList, v3.0.17
  AckisRecipeListQuickScan, v6.1.0.1
  Altoholic, vr155
  Arh, v1.4.2
  AucAdvanced, v5.21c.5521 (SanctimoniousSwamprat)
  AucFilterBasic, v5.21c.5521 (SanctimoniousSwamprat)
  AucFilterOutlier, v5.21c.5521.5459(5.21c/embedded)
  AucMatchUndercut, v5.21c.5521.5507(5.21c/embedded)
  AucScanData, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatHistogram, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatiLevel, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatPurchased, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatSale

**Comment by Jaliborc** [comment]
AccountSearch is oputdated and not developed by us
