### ISSUE TITLE
Searching for quality doesn't work

### ISSUE THREAD

**Issue by stijnherreman** [tullamods/Bagnon#370]
Using version 6.1.5 from Curse. Searching for quality, e.g. `epic` gives 0 results.

**Comment by Sethycakes** [comment]
I'm experiencing this too.

**Comment by supmotto** [comment]
Yeap ever since the latest update I can't search via quality

**Comment by axel-dd** [comment]
Same here, highlighting only green items with search syntax does not work since the last update, item level searching works!

**Comment by stijnherreman** [comment]
I took a look at the code (and later found that someone else had already located the issue, see https://github.com/Jaliborc/LibItemSearch-1.2/pull/2).

Open `Interface\AddOns\Bagnon\libs\LibItemSearch-1.2\LibItemSearch-1.2.lua` and go to line 124.
Replace
```Lib.Filters.quality = {```
with
```Lib.Filters.usable = {```

**Comment by Sethycakes** [comment]
That edit works perfectly, thanks!

**Comment by Jaliborc** [comment]
Solved
