### ISSUE TITLE
Gold total bug when viewing another char's items

### ISSUE THREAD

**Issue by houlia** [tullamods/Bagnon#374]
1) Visit a mailbox - you will keep this frame up through all the steps
You should now see **Character A**'s inventory (note the **gold total A**)
2) Use the Bagnon "View another character's items" option and view **Character B**'s inventory (note the **gold total B**)
3) Close the Bagnon bags window, but keep the mailbox open
4) Re-open the bags frame - you will correctly see Character A's inventory, but you will have the gold total from Character B  **Char A Gold B**

Bug? Maybe just a limitation of the API?

**Comment by Jaliborc** [comment]
Fixed
