### ISSUE TITLE
Item count color by class not readable

### ISSUE THREAD

**Issue by ceylina** [tullamods/Bagnon#375]
It sometimes is pretty hard to read the item count on the tooltip for certain classes such as death knights. Would it be possible to disable the coloring these by class for the count number? Perhaps give an option for all white or some neutral color that is easier to read on old eyes? 

Just to clarify, it would be just fine to have the number and not "Bags:" as "silver" so it would still be easy at a glance to differentiate alts.

**Comment by Jaliborc** [comment]
I'll tweak the colors instead so they are readable ;)
If that still, doesnt work, then I'll add the option

**Comment by ceylina** [comment]
Just checked the latest update you posted today and unless you haven't tweaked it yet, it is till very hard to read for some classes like death knights.

If you could lighten the red for death knight to be more of a faded red or add the feature or disable coloring the item count itself, that would be excellent because the class colorization is a nice feature and I don't want to lose it.
