### ISSUE TITLE
Clicking the "Sort" button is not sorting the bag

### ISSUE THREAD

**Issue by framgeld** [tullamods/Bagnon#379]
I can click Sort and it works fine on one of my alts. However, on my main character, sorting will not work. I have 6 empty slots left. Please find below a screen capture of my bag, in case it will help you to diagnose the problem.

![image](https://cloud.githubusercontent.com/assets/11695215/6881384/1de6dbaa-d555-11e4-948f-1441e8ffb7f5.png)

**Comment by Jaliborc** [comment]
@framgeld Do the items appear sorted after you reload the UI?

**Comment by framgeld** [comment]
It was a while ago, I'm afraid... but the gut answer would "no". I am pretty sure that I unloaded Bagnon then reloaded it.



-----Original Message-----

**Comment by Jaliborc** [comment]
Well, then it is a game server issue, which is not handled by Bagnon. The item server was probably unresponsive.
