### ISSUE TITLE
Guildbank - cant read logs

### ISSUE THREAD

**Issue by Ylumina** [tullamods/Bagnon#380]
Error message:

Date: 2015-03-28 18:42:27
ID: 2
Error occured in: Global
Count: 1
Message: ..\SharedXML\SharedUIPanelTemplates.lua line 235:
   attempt to index local 'highlightFrame' (a number value)
Debug:
   ..\SharedXML\SharedUIPanelTemplates.lua:235: FauxScrollFrame_Update()
   ...face\AddOns\Bagnon_GuildBank\components\logFrame.lua:144: UpdateScroll()
   ...face\AddOns\Bagnon_GuildBank\components\logFrame.lua:71: Update()
   ...face\AddOns\Bagnon_GuildBank\components\logFrame.lua:61: Display()
   ...terface\AddOns\Bagnon_GuildBank\components\frame.lua:32: ShowPanel()
   ...ace\AddOns\Bagnon_GuildBank\components\logToggle.lua:61:
      ...ace\AddOns\Bagnon_GuildBank\components\logToggle.lua:60
Locals:
frame = BagnonFrameguildLogFrame {
 0 = <userdata>
 messages = <unnamed> {
 }
 numTransactions = 0
 ScrollBar = BagnonFrameguildLogFrameScrollBar {
 }
 tab = 8
 isMoney = false
 offset = 0
}
numItems = 0
numToDisplay = 24
buttonHeight = 13
button = 95
smallWidth = 95
bigWidth = 95
highlightFrame = 95
smallHighlightWidth = 95
bigHighlightWidth = 95
alwaysShowScrollBar = true
frameName = "BagnonFrameguildLogFrame"
scrollBar = BagnonFrameguildLogFrameScrollBar {
 0 = <userdata>
 ScrollUpButton = BagnonFrameguildLogFrameScrollBarScrollUpButton {
 }
 ScrollDownButton = BagnonFrameguildLogFrameScrollBarScrollDownButton {
 }
}
showScrollBar = 1
scrollChildFrame = BagnonFrameguildLogFrameScrollChildFrame {
 0 = <userdata>
}
scrollUpButton = BagnonFrameguildLogFrameScrollBarScrollUpButton {
 0 = <userdata>
}
scrollDownButton = BagnonFrameguildLogFrameScrollBarScrollDownButton {
 0 = <userdata>
}
scrollFrameHeight = 0
scrollChildHeight = 0
maxRange = 0
(*temporary) = <function> defined =[C]:-1
(*temporary) = 95
(*temporary) = <userdata>
(*temporary) = <userdata>
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'highlightFrame' (a number value)"

AddOns:
  Swatter, v5.21c.5521 (SanctimoniousSwamprat)
  NPCScan, v6.1.0.2
  NPCScanOverlay, v6.1.0.1
  NPCScanOverlayBroker, v1.2.6
  Bagnon, v6.1.5
  BagnonGuildBank, v6.1.5
  Bartender4, v4.6.8
  Coordinates, v1.18
  DBMCore, v
  DBMDefaultSkin, v
  DBMInterrupts, v6.1.0
  DBMRaidLeadTools, v
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  DBMVPCarebear, v1.4
  DBMVPVEM, v1.4.0
  DebuffFilter, v5.4.0.2
  DebugLib, v5.1.DEV.337(/embedded)
  EasyCopy, v5.0.1
  LostTreasures, v3.03
  MasterPlan, v0.33
  Postal, v3.5.4
  QuestHubber, v
  QuestHubberAzeroth, v
  QuestHubberCataclysm, v
  QuestHubberDaily, v
  QuestHubberNorthrend, v
  QuestHubberOutland, v
  QuestHubberPandaria, v
  RCLootCouncil, v1.7.2
  Skada, v1.4-30
  SlideBar, v5.21c.5521 (SanctimoniousSwamprat)
  Stubby, v5.21c.5521 (SanctimoniousSwamprat)
  TomTom, vv60100-1.0.0
  VuhDo, v3.66
  VuhDoOptions, v3.66
  BlizRuntimeLib_enUS v6.1.2.60100 <none>
  (ck=394)

**Comment by Jaliborc** [comment]
Fixed
