### ISSUE TITLE
Questions about general bag sorting + item set color

### ISSUE THREAD

**Issue by voyvoy** [tullamods/Bagnon#381]
I use bagnon with no special sorting, no bags dedicated to certain types of items and no reverse sorting. So whenever I activate Bagnon on one of my alts it looks like this, filling from bottom to top with new items and greys in the first bag which is very fine by me:

![bagnon-b](https://cloud.githubusercontent.com/assets/10220573/6996579/1d0c8dce-db90-11e4-9524-06867b9a4a37.png)

However, on my main it fills the bag(s) from the upside down, no matter that I use the exact same settings as on all my other characters:

![bagnon-a](https://cloud.githubusercontent.com/assets/10220573/6996581/442747fa-db90-11e4-9178-00f2a4d3609a.png)

Changing to reverse sorting switches the bags, but still fills them differently than on my other characters. I was wondering what could cause this. I deleted my main from the bagnon character menu and reopened her, but it had no effect. 

Secondly, is it possible for me to change the color for item sets? Right now it's a dimmed blue-green which not only makes it hard to see, but also easy to mistake for a regular blue item. I'd prefer to change it to something bright and easy to see at first glance.

(Also, since last patch the currency tracker has visual bugs as can be seen on the screenshots, but I guess that's not caused on Bagnon's side, or is it?)

**Comment by Jaliborc** [comment]
Look at the blizzard sorting options. They change the order in which items are sorted, and are probably set differently on different characters,.
