### ISSUE TITLE
Reverse bag order switches on every toon

### ISSUE THREAD

**Issue by Adabella** [tullamods/Bagnon#382]
I've been using Bagnon forever and only recently started having this issue sometime after updating to the latest build.
I always had my items sort in the order filled bag spots --> empty bag spots, on every toon. I signed in one day and my items were sorting in empty slots --> filled bag spots, so I looked in the settings and tried checking "Reverse bag order". That fixed it, great! Except then I signed onto my other toons... those were all sorting backwards. So I checked or unchecked the setting for "Reverse bag order", depending on whether it was previously checked or unchecked. Again, that worked.... on that toon. Every time I log in to another toon, I have to change this setting AGAIN. It's getting really frustrating and I don't have any other bag addons, and I disable ElvUI's bags/bag sorting because I don't like their windows for it. I did even try changing settings in ElvUI and it had no impact.

**Comment by Jaliborc** [comment]
Go to the blizzard default options. There are options there regarding sorting order, you probably have them differently on different characters
