### ISSUE TITLE
How do I open the bag I disabled

### ISSUE THREAD

**Issue by ghost** [tullamods/Bagnon#386]
1) Enable "Display Blizzard Frames for Hidden Bags" in general options ... done
2) Open Bagnon bag frame .... done 
3) Click on each bag to disable it ... done 
4) Close the frame ... done 
5) Bags should display as such now ... done 

 ... ^^ now, tell me, how do I open the bag I disabled ... it works on older version but.   no matter what I do on up todate version I cannot get the bag I disabled to open on its own

**Comment by SultryVixon** [comment]
well you have 'updated' this addon but I still can't get it to work properly
I still cannot open a single bag
I have done the suggestion till I'm blue in the face
