### ISSUE TITLE
Lag when sorting/looting

### ISSUE THREAD

**Issue by Deceited** [tullamods/Bagnon#388]
I'm currently experiencing lag when sorting my inventory/looting multiple items/autoselling items with Dugi. This only happens when I have both Bagnon and Dugi Questing Essentials enabled. If I disable either of the two, the lag is gone.

**Comment by Deceited** [comment]
After some testing, it seems the Highlight Equipment Set Items option in Bagnon conflicts with something in Dugi.

**Comment by Ibglitrbug** [comment]
I have the same problem my screen, locks up completely and i dont have Dugi so i think it is just a bug with bagnon.
