### ISSUE TITLE
reversing orders

### ISSUE THREAD

**Issue by Zanoon-Skywall** [tullamods/Bagnon#391]
on my main, and many of my other toons who have had this addon for what seems like forever, if i have reverse bag order and reverse slot order, everything just goes to the bottom and fills to the top. but then i make new toons and i must uncheck reverse bag order to get the items to go to the bottom. but then when i loot items they fill the bottom of the top bag first and do not go straight to the bottom until i click the sort button. is this a bug? would making separate profiles for characters be easier to fix? Please help, i do not like having to change my addon every time i log on to a different character =(

**Comment by Jaliborc** [comment]
Which version are you using @Zanoon-Skywall ?

**Comment by Zanoon-Skywall** [comment]
I have version 6.1.5, curse says its up to date.

Sent from Yahoo Mail on Android
