### ISSUE TITLE
Reverse Bag Order

### ISSUE THREAD

**Issue by Dude1571** [tullamods/Bagnon#395]
Hello, all my bags are in reverse order.
Other users have reported the same issue in http://www.curse.com/addons/wow/bagnon

Thanks.

**Comment by GaroldB** [comment]
Same problem, but only on the one character. Please fix this!
Can provide screenshots.

**Comment by MasterAries7** [comment]
The blizzard UI has a setting to reverse bag cleanup, that seems to fix it.

Interface -> Controls -> Reverse Clean Up Bags

**Comment by GaroldB** [comment]
YEAH! Thanks, it helped!
