### ISSUE TITLE
Lua crash

### ISSUE THREAD

**Issue by Elesack** [tullamods/Bagnon#399]
This happens after first bag open or bank bag open, EVERY time, and has done for a year. There's also a similar one the first time u try to Search in the bag.

Date: 2015-07-04 16:44:14
ID: 1
Error occured in: Global
Count: 1
Message: ...AddOns\Bagnon_AccountSearch\Bagnon_AccountSearch.lua line 187:
   attempt to index field 'FrameSettings' (a nil value)
Debug:
   [C]: ?
   ...AddOns\Bagnon_AccountSearch\Bagnon_AccountSearch.lua:187: GetBagnonVariableLinks()
   ...AddOns\Bagnon_AccountSearch\Bagnon_AccountSearch.lua:207: UpdateVisibility()
   ...AddOns\Bagnon_AccountSearch\Bagnon_AccountSearch.lua:60: OnHide()
   Bagnon\components\inventory.lua:17:
      Bagnon\components\inventory.lua:16
   [C]: Hide()
   Bagnon\components\frame.lua:67: HideFrame()
   Bagnon\main.lua:102:
      Bagnon\main.lua:99
   (tail call): ?
   (tail call): ?
   Bagnon\main.lua:249: oldToggleBag()
   ...erface\AddOns\ZygorGuidesViewer\InventoryManager.lua:633: ToggleBag()
   ..\FrameXML\MainMenuBarBagButtons.lua:21: BagSlotButton_OnClick()
   [string "*:OnClick"]:4:
      [string "*:OnClick"]:1
Locals:

AddOns:
  Swatter, v5.21e.5566 (SanctimoniousSwamprat)
  NPCScan, v6.2.0.1
  NPCScanOverlay, v6.2.0.1
  Ace3, v
  AchievementsReminder, v
  AllPlayed, v50400-2 $Revision: 296 $
  AskMrRobot, v26
  Atlas, v1.31.01
  AtlasArena, v1.5.06
  AtlasBattlegrounds, v1.31.01
  AtlasBurningCrusade, v1.31.01
  AtlasCataclysm, v1.31.01
  AtlasClassicWoW, v1.31.01
  AtlasDungeonLocs, v1.31.01
  AtlasMistsofPandaria, v1.31.01
  AtlasOutdoorRaids, v1.31.01
  AtlasScenarios, v1.31.01
  AtlasTransportation, v1.31.03
  AtlasWorldEvents, v3.12
  AtlasWrathoftheLichKing, v1.31.01
  AtlasLoot, vv8.00.30
  AtlasMajorCities, vv1.5.3
  AtlasMajorCitiesEnhanced, vv1.07
  AtlasQuest, v4.9.3
  AucAdvanced, v5.21e.5566 (SanctimoniousSwamprat)
  AucFilterBasic, v5.21e.5566 (SanctimoniousSwamprat)
  AucFilterOutlier, v5.21e.5566.5459(5.21e/embedded)
  AucMatchUndercut, v5.21e.5566.5507(5.21e/embedded)
  AucScanData, v5.21e.5566 (SanctimoniousSwamprat)
  AucStatHistogram, v5.21e.5566 (SanctimoniousSwamprat)
  AucStatiLevel, v5.21e.5566 (SanctimoniousSwamprat)
  AucStatPurchased, v5.21e.5566 (SanctimoniousSwamprat)
  AucStatSales, v5.21e.5566.5476(5.21e/embedded)
  AucStatSimple, v5.21e.5566 (SanctimoniousSwamprat)
  AucStatStdDev, v5.21e.5566 (SanctimoniousSwamprat)
  AucStatWOWEcon, v5.21e.5566.5323(5.21e/embedded)
  AucUtilAHWindowControl, v5.21e.5566.5347(5.21e/embedded)
  AucUtilAppraiser, v5.21e.5566.5545(5.21e/embedded)
  AucUtilAskPrice, v5.21e.5566.5447(5.21e/embedded)
  AucUtilAutoMagic, v5.21e.5566.5537(5.21e/embedded)
  AucUtilCompactUI, v5.21e.5566.5550(5.21e/embedded)
  AucUtilEasyBuyout, v5.21e.5566.5507(5.21e/embedded)
  AucUtilFixAH, v5.21e.5566 (SanctimoniousSwamprat)
  AucUtilItemSuggest, v5.21e.5566.5417(5.21e/embedded)
  AucUtilPriceLevel, v5.21e.5566.5535(5.21e/embedded)
  AucUtilScanButton, v5.21e.5566.5403(5.21e/embedded)
  AucUtilScanFinish, v5.21e.5566.5515(5.21e/embedded)
  AucUtilScanProgress, v5.21e.5566.4979(5.21e/embedded)
  AucUtilScanStart, v5.21e.5566.5347(5.21e/embedded)
  AucUtilSearchUI, v5.21e.5566.5556(5.21e/embedded)
  AucUtilSimpleAuction, v5.21e.5566.5531(5.21e/embedded)
  AucUtilVendMarkup, v5.21e.5566.4828(5.21e/embedded)
  Babylonian, v5.1.DEV.332(/embedded)
  BagBrother, v
  Bagnon, v6.2.1
  BagnonAccountSearch, v1.7.0
  BattlePetsCollector, v6.0.3.10
  BeanCounter, v5.21e.5566 (SanctimoniousSwamprat)
  BittensSpellFlashHunter, v60100.201503092107
  BittensSpellFlashLibrary, v60100.201503092107
  BodyGuardAway, v2.2
  Configator, v5.1.DEV.382(/embedded)
  DBMCore, v
  DBMDefaultSkin, v
  DBMGarrisonInvasions, v
  DBMLDB, v
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  DragonHider, v
  EZTrap, v6.2.22
  FishingBuddy, v1.5.4
  FlightMap, v6.1.0.0
  FloAspectBar, v
  GatherMate2, v1.34
  GTFO, v4.37.2
  HandyNotes, vv1.3.3
  HandyNotesDraenorTreasures, v1.14a
  Informant, v5.21e.5566 (SanctimoniousSwamprat)
  LibExtraTip, v5.12.DEV.390(/embedded)
  LibSharedMedia30, v3.0-93
  Mapster, v1.6.3
  MasterPlan, v0.63
  MasterPlanA, v
  MogIt, v3.5.3
  MogItAccessories, v
  MogItHighlighter, vv1.3.2
  Omen, v3.1.11
  OpenAll, v1
  OpenRaid, v2.1
  Overachiever, v0.82
  RaidAchievement, v
  RaidAchievementOldModules, v
  RealmChecker, v
  Recount, vv6.2.0f release
  SavedInstances, v6.2.0
  SkillHelper, v2.2.228
  SlideBar, v5.21e.5566 (SanctimoniousSwamprat)
  SpellFlash, v6.23
  SpellFlashX, v1.0.8 Beta
  SpellFlashCore, v2.0.7
  Stubby, v5.21e.5566 (SanctimoniousSwamprat)
  TipHelper, v5.12.DEV.389(/embedded)
  Titan, v5.6.8.60200
  TitanClock, v5.6.8.60200
  TitanCurrTrack, v1.3.1
  TitanDurability, v1.24
  TitanEasyHonor, v1.11.40300
  TitanGold, v5.6.8.60200
  TitanGuild, v6.0.3.1
  TitanLocation, v5.6.8.60200
  TitanLootType, v5.6.8.60200
  TitanPerformance, v5.6.8.60200
  TitanRecount, v4.0.0
  TitanRepair, v5.6.8.60200
  TitanReputation, v3.8.6
  TitanSocial, v6.1r32
  TitanSpec, v4.1
  TitanSpeed, v6.0.001
  TitanTreasury, v22
  TitanVolume, v5.6.8.60200
  TitanXP, v5.6.8.60200
  TomTom, vv60200-1.0.0
  TradeSkillInfo, vv2.3.6
  TradeSkillMaster, vv2.10.26
  TradeSkillMasterAdditions, vv2.1.5
  TradeSkillMasterAppHelper, vv2.0.3
  TradeSkillMasterCrafting, vv2.6.19
  TradeSkillMasterDestroying, vv2.1.12
  TradeSkillMasterItemTracker, vv2.1.3
  ZygorGuidesViewer, v5.0
  BlizRuntimeLib_enUS v6.2.0.60200 <none>
  (ck=10e8)

**Comment by Jaliborc** [comment]
AccountSearch is not maintained by me nor it has been updated to the latest version.
