### ISSUE TITLE
Guild Bank error

### ISSUE THREAD

**Issue by Avatar190** [tullamods/Bagnon#401]
When I go to open the Guild Bank, I get an error.  Not sure if it's an incompatibility with another Addon, but here is the information:

---------------------------------------------------------------------------------------------------------
Date: 2015-07-27 23:11:42
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\BagBrother\Events.lua line 125:
   attempt to index local 'items' (a nil value)
Debug:
   BagBrother\Events.lua:125: ?()
   BagBrother\Startup.lua:20:
      BagBrother\Startup.lua:20
Locals:
self = BagBrother {
 BANKFRAME_OPENED = <function> defined @Interface\AddOns\BagBrother\Events.lua:55
 ParseItem = <function> defined @Interface\AddOns\BagBrother\API.lua:45
 BAG_UPDATE = <function> defined @Interface\AddOns\BagBrother\Events.lua:32
 VOID_STORAGE_CLOSE = <function> defined @Interface\AddOns\BagBrother\Events.lua:81
 SaveBag = <function> defined @Interface\AddOns\BagBrother\API.lua:19
 SaveEquip = <function> defined @Interface\AddOns\BagBrother\API.lua:38
 GUILDBANKFRAME_OPENED = <function> defined @Interface\AddOns\BagBrother\Events.lua:96
 SetupCharacter = <function> defined @Interface\AddOns\BagBrother\Startup.lua:45
 StartupCache = <function> defined @Interface\AddOns\BagBrother\Startup.lua:33
 PLAYER_MONEY = <function> defined @Interface\AddOns\BagBrother\Events.lua:48
 SetupEvents = <function> defined @Interface\AddOns\BagBrother\Startup.lua:62
 BANKFRAME_CLOSED = <function> defined @Interface\AddOns\BagBrother\Events.lua:59
 GUILDBANKBAGSLOTS_CHANGED = <function> defined @Interface\AddOns\BagBrother\Events.lua:108
 UNIT_INVENTORY_CHANGED = <function> defined @Interface\AddOns\BagBrother\Events.lua:40
 VOID_STORAGE_OPEN = <function> defined @Interface\AddOns\BagBrother\Events.lua:77
 Realm = <table> {
 }
 Player = <table> {
 }
 RemoveEvent = <function> defined @Interface\AddOns\BagBrother\Startup.lua:89
 0 = <userdata>
 GUILDBANKFRAME_CLOSED = <function> defined @Interface\AddOns\BagBrother\Events.lua:100
 GUILD_ROSTER_UPDATE = <function> defined @Interface\AddOns\BagBrother\Events.lua:104
 UpdateData = <function> defined @Interface\AddOns\BagBrother\Startup.lua:79
 atGuild = true
}
id = "Decade*"
tab = 1
tabs = <table> {
}
items = nil
(for index) = 1
(for limit) = 98
(for step) = 1
i = 1
link = nil
_ = nil
count = 0
(*temporary) = nil
(*temporary) = BagBrother {
 BANKFRAME_OPENED = <function> defined @Interface\AddOns\BagBrother\Events.lua:55
 ParseItem = <function> defined @Interface\AddOns\BagBrother\API.lua:45
 BAG_UPDATE = <function> defined @Interface\AddOns\BagBrother\Events.lua:32
 VOID_STORAGE_CLOSE = <function> defined @Interface\AddOns\BagBrother\Events.lua:81
 SaveBag = <function> defined @Interface\AddOns\BagBrother\API.lua:19
 SaveEquip = <function> defined @Interface\AddOns\BagBrother\API.lua:38
 GUILDBANKFRAME_OPENED = <function> defined @Interface\AddOns\BagBrother\Events.lua:96
 SetupCharacter = <function> defined @Interface\AddOns\BagBrother\Startup.lua:45
 StartupCache = <function> defined @Interface\AddOns\BagBrother\Startup.lua:33
 PLAYER_MONEY = <function> defined @Interface\AddOns\BagBrother\Events.lua:48
 SetupEvents = <function> defined @Interface\AddOns\BagBrother\Startup.lua:62
 BANKFRAME_CLOSED = <function> defined @Interface\AddOns\BagBrother\Events.lua:59
 GUILDBANKBAGSLOTS_CHANGED = <function> defined @Interface\AddOns\BagBrother\Events.lua:108
 UNIT_INVENTORY_CHANGED = <function> defined @Interface\AddOns\BagBrother\Events.lua:40
 VOID_STORAGE_OPEN = <function> defined @Interface\AddOns\BagBrother\Events.lua:77
 Realm = <table> {
 }
 Player = <table> {
 }
 RemoveEvent = <function> defined @Interface\AddOns\BagBrother\Startup.lua:89
 0 = <userdata>
 GUILDBANKFRAME_CLOSED = <function> defined @Interface\AddOns\BagBrother\Events.lua:100
 GUILD_ROSTER_UPDATE = <function> defined @Interface\AddOns\BagBrother\Events.lua:104
 UpdateData = <function> defined @Interface\AddOns\BagBrother\Startup.lua:79
 atGuild = true
}
(*temporary) = nil
(*temporary) = 0
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'items' (a nil value)"

AddOns:
  Swatter, v5.21e.5566 (SanctimoniousSwamprat)
  AckisRecipeList, v6.2.0.4
  AckisRecipeListQuickScan, v6.2.0.1
  AucAdvanced, v5.21e.5566 (SanctimoniousSwamprat)
  AucFilterBasic, v5.21e.5566 (SanctimoniousSwamprat)
  AucFilterOutlier, v5.21e.5566.5459(5.21e/embedded)
  AucMatchUndercut, v5.21e.5566.5507(5.21e/embedded)
  AucStatHistogram, v5.21e.5566 (SanctimoniousSwamprat)
  AucStatiLevel, v5.21e.5566 (SanctimoniousSwamprat)
  AucStatPurchased, v5.21e.5566 (SanctimoniousSwamprat)
  AucStatSales, v5.21e.5566.5476(5.21e/embedded)
  AucStatSimple, v5.21e.5566 (SanctimoniousSwamprat)
  AucStatStdDev, v5.21e.5566 (SanctimoniousSwamprat)
  AucStatWOWEcon, v5.21e.5566.5323(5.21e/embedded)
  AucUtilAHWindowControl, v5.21e.5566.5347(5.21e/embedded)
  AucUtilAppraiser, v5.21e.5566.5545(5.21e/embedded)
  AucUtilAskPrice, v5.21e.5566.5447(5.21e/embedded)
  AucUtilAutoMagic, v5.21e.5566.5537(5.21e/embedded)
  AucUtilCompactUI, v5.21e.5566.5550(5.21e/embedded)
  AucUtilEasyBuyout, v5.21e.5566.5507(5.21e/embedded)
  AucUtilFixAH, v5.21e.5566 (SanctimoniousSwamprat)
  AucUtilItemSuggest, v5.21e.5566.5417(5.21e/embedded)
  AucUtilPriceLevel, v5.21e.5566.5535(5.21e/embedded)
  AucUtilScanButton, v5.21e.5566.5403(5.21e/embedded)
  AucUtilScanFinish, v5.21e.5566.5515(5.21e/embedded)
  AucUtilScanProgress, v5.21e.5566.4979(5.21e/embedded)
  AucUtilScanStart, v5.21e.5566.5347(5.21e/embedded)
  AucUtilSearchUI, v5.21e.5566.5556(5.21e/embedded)
  AucUtilSimpleAuction, v5.21e.5566.5531(5.21e/embedded)
  AucUtilVendMarkup, v5.21e.5566.4828(5.21e/embedded)
  Babylonian, v5.1.DEV.332(/embedded)
  BagBrother, v
  Bagnon, v6.2.1
  BagnonGuildBank, v6.2.1
  BeanCounter, v5.21e.5566 (SanctimoniousSwamprat)
  Configator, v5.1.DEV.382(/embedded)
  CrapAway, v
  DebugLib, v5.1.DEV.337(/embedded)
  Enchantrix, v5.21e.5566 (SanctimoniousSwamprat)
  EnchantrixBarker, v5.21e.5566 (SanctimoniousSwamprat)
  FixehTip, v2.7.3
  FixehTipOptions, v2.7.3
  Informant, v5.21e.5566 (SanctimoniousSwamprat)
  LibExtraTip, v5.12.DEV.390(/embedded)
  Postal, v3.5.4
  SlideBar, v5.21e.5566 (SanctimoniousSwamprat)
  Stubby, v5.21e.5566 (SanctimoniousSwamprat)
  TipHelper, v5.12.DEV.389(/embedded)
  VuhDo, v3.68
  VuhDoOptions, v3.68
  WoWDBProfiler, v
  BlizRuntimeLib_enUS v6.2.0.60200 <none>
  (ck=8ea)
---------------------------------------------------------------------------------------------------

**Comment by Jaliborc** [comment]
Fixed
