### ISSUE TITLE
Error when opening mailbox

### ISSUE THREAD

**Issue by Phanx** [tullamods/Bagnon#413]
1. Open the Bagnon inventory and bank frames (doesn't have to be at the same time) and set both to display a character other than the current one.
2. Close both frames.
3. Open the mailbox.

The following error occurs:

````
10x Bagnon\common\core\classes.lua:44: attempt to index a nil value
Bagnon\common\core\classes.lua:44: in function 'GetPlayer'
Bagnon\common\components\item.lua:446: in function 'GetInfo'
Bagnon\common\components\item.lua:266: in function 'IsLocked'
Bagnon\common\components\item.lua:258: in function 'UpdateLocked'
Bagnon\common\components\item.lua:374: in function 'UpdateSearch'
Bagnon\common\components\item.lua:227: in function 'DelayedUpdates'
Bagnon\common\components\item.lua:223: in function <Bagnon\common\components\item.lua:223>
````

It does *not* occur if:

* ...only one frame (inventory or bank, but not both) is displaying another character.

* ...one or both frames are already open when the mailbox is opened.

* ...the Automatic Display >> Display Inventory >> Checking a Mailbox option is **un**checked.

EU live server, English client, Bagnon 6.2.4

**Comment by Jaliborc** [comment]
Thanks, fixed
