### ISSUE TITLE
Unable to open bags or Bank

### ISSUE THREAD

**Issue by Sparkjade** [tullamods/Bagnon#421]
I'm also new and got the latest Bagnon from Curse. It has been unzipped to the Interface>Addon folder and no bags will open, no Config menu. I've been trying for a few weeks now even so far as to erase and reinstall my game. Any other suggestions? This is the errors I get in the log

Message: ...\Bagnon\libs\LibItemSearch-1.2\LibItemSearch-1.2.lua:207: attempt to index global 'TOY' (a nil value)
Time: 11/27/15 19:57:08
Count: 1
Stack: ...\Bagnon\libs\LibItemSearch-1.2\LibItemSearch-1.2.lua:207: in main chunk

Locals: Search = <table> {
 OR = "or"
 NOT_MATCH = "not"
 NOT = "Not"
 Find = <function> defined @Interface\AddOns\Bagnon\libs\CustomSearch-1.0\CustomSearch-1.0.lua:133
 Match = <function> defined @Interface\AddOns\Bagnon\libs\CustomSearch-1.0\CustomSearch-1.0.lua:56
 MatchAny = <function> defined @Interface\AddOns\Bagnon\libs\CustomSearch-1.0\CustomSearch-1.0.lua:48
 ACCENTS = <table> {
 }
 MatchAll = <function> defined @Interface\AddOns\Bagnon\libs\CustomSearch-1.0\CustomSearch-1.0.lua:38
 UseFilter = <function> defined @Interface\AddOns\Bagnon\libs\CustomSearch-1.0\CustomSearch-1.0.lua:123
 Compare = <function> defined @Interface\AddOns\Bagnon\libs\CustomSearch-1.0\CustomSearch-1.0.lua:152
 Matches = <function> defined @Interface\AddOns\Bagnon\libs\CustomSearch-1.0\CustomSearch-1.0.lua:29
 Filter = <function> defined @Interface\AddOns\Bagnon\libs\CustomSearch-1.0\CustomSearch-1.0.lua:101
 Clean = <function> defined @Interface\AddOns\Bagnon\libs\CustomSearch-1.0\CustomSearch-1.0.lua:142
}
Unfit = <table> {
 IsItemUnusable = <function> defined @Interface\AddOns\Bagnon\libs\Unfit-1.0\Unfit-1.0.lua:73
 unusable = <table> {
 }
 IsClassUnusable = <function> defined @Interface\AddOns\Bagnon\libs\Unfit-1.0\Unfit-1.0.lua:80
}
Lib = <table> {
 TooltipPhrase = <function> defined @Interface\AddOns\Bagnon\libs\LibItemSearch-1.2\LibItemSearch-1.2.lua:26
 InSet = <function> defined @Interface\AddOns\Bagnon\libs\LibItemSearch-1.2\LibItemSearch-1.2.lua:30
 Tooltip = <function> defined @Interface\AddOns\Bagnon\libs\LibItemSearch-1.2\LibItemSearch-1.2.lua:22
 Matches = <function> defined @Interface\AddOns\Bagnon\libs\LibItemSearch-1.2\LibItemSearch-1.2.lua:18
 Filters = <table> {
 }
}
qualities = <table> {
 1 = "common"
 2 = "uncommon"
 3 = "rare"
 4 = "epic"
 5 = "legendary"
 6 = "artifact"
 7 = "heirloom"
 0 = "poor"
}
scanner = LibItemSearchTooltipScanner {
 0 = <userdata>
 updateTooltip = 0.2
}
(*temporary) = <table> {
 type = <table> {
 }
 name = <table> {
 }
 requiredlevel = <table> {
 }
 tip = <table> {
 }
 level = <table> {
 }
 usable = <table> {
 }
 quality = <table> {
 }
}
(*temporary) = <table> {
 canSearch = <function> defined @Interface\AddOns\Bagnon\libs\LibItemSearch-1.2\LibItemSearch-1.2.lua:167
 cache = <table> {
 }
 match = <function> defined @Interface\AddOns\Bagnon\libs\LibItemSearch-1.2\LibItemSearch-1.2.lua:171
}
(*temporary) = <table> {
 boa = "Binds to Battle.net account"
 bop = "Binds when picked up"
 soulbound = "Binds when picked up"
 quests = "Quest Item"
 bou = "Binds when used"
 bound = "Binds when picked up"
 Quest = "Quest Item"
 boe = "Binds when equipped"
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "quests"
(*temporary) = "Armor"
(*temporary) = "attempt to index global 'TOY' (a nil value)"

**Comment by Jaliborc** [comment]
Are you on a private server? The addon is made for official servers.

**Comment by Sparkjade** [comment]
I found out what it was. Different versions issue. I got the one I needed
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
This
email has been sent from a virus-free computer protected by Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
