### ISSUE TITLE
Databroker / currency display

### ISSUE THREAD

**Issue by digofrota** [tullamods/Bagnon#423]
Hi.
On my bag i can't find a way to display the Conquest and Honor Points, even though they are set to show up on bag, and i have also downloaded the CurrencyTracked addon that you provide on the description.
A message is displayed: "select databroker plugin"
i don't know whts going on, last time i've done it i had no problem, i just added the currencytracked and it was there...
also one more thing, when i click the arrows to swap whts displayed nothing shows up, just the message.

**Comment by Jaliborc** [comment]
Make sure you have "Show Lua Errors" enabled
