### ISSUE TITLE
Void Storage NOT Tracked with BagSync when using Bagnon Void Storage

### ISSUE THREAD

**Issue by Jayshua83** [tullamods/Bagnon#425]
As title says... Void Storage NOT Tracked with BagSync when using Bagnon Void Storage.

I reported it too him and this is his response.

https://github.com/Xruptor/BagSync/issues/29

"This is the first I hear of this issue. In general Bagnon uses the very same Blizzard API when it grabs the information about Void Storage from the servers. The only way I can think that the Void Storage will not be tracked by BagSync is if Bagnon hijacked the functions required for BagSync to properly work. However, that's highly unlikely because Tuller is very good at how he programs. I'm sure he did what I did and monitored event calls for Void Storage. I don't have an active account right now to test this out. Hopefully someone will take a look at it and provide a fix via GitHub."

**Comment by Jayshua83** [comment]
Hello? Any news?

**Comment by Jaliborc** [comment]
I did double-checked and Bagnon Void Storage is not fiddling with any function, as it should. As an additional point, BagBrother, which works independently, is able to track the void storage.

Note that BagSync tracking is not expected to make items show offline in Bagnon's Void Storage. If that is what you are expecting, then that is not possible. Do you have "Show Lua Errors" enabled?

**Comment by Jayshua83** [comment]
No. What I am expecting to work is what happens if I disable Bagnon Void Storage and visit the Void Storage. My tooltips from BagSync then update to show if I have an item in Void Storage or not and they show up in search for BagSync. If I have Bagnon VS running they never update or now new items are ever added to BagSync from VS. All other parts of Bagnon/BagSync work fine. Very odd. :(

**Comment by Jaliborc** [comment]
Well, then I can only think of a tooltip issue.
Do you have bagnon's item counters enabled?

**Comment by Jayshua83** [comment]
I didn't, but I can try it... I use BagSync for Tooltip counts and ALL of them work WITH Bagnon, GuildBank, AltBanks, My Bank... But NIL on the Void Storage. Its the only thing that doesn't work without disabling Bagnon Void Storage. Once I disable it I get an updated count and then reenabling it lets BagSync and the Tooltips work correctly until I update Void Storage with new items or remove them. Thanks for you input on this issue! Very odd and frustrating...
