### ISSUE TITLE
Incorrect sorting of Darkmoon Cards

### ISSUE THREAD

**Issue by Daugger** [tullamods/Bagnon#427]
I noticed that the auto sorting feature in Bagnon puts the Ace of Iron way before any other darkmoon cards of dreanor. all other darkmoon cards are placed next to each other if they are part of the same deck. They may be out of order but at least grouped next to each other. the ace of iron is the only darkmoon card that seems to be way out of whack and completely in the wrong spot. I should also mention that this happens in the bank bags as well as the inventory bags.

**Comment by Jaliborc** [comment]
Sorting is handled by blizzard
