### ISSUE TITLE
reverse bag order picked up items?

### ISSUE THREAD

**Issue by rakkarage** [tullamods/Bagnon#431]
normally items you pickup start at the end so if your bags are empty and pickup one item it goes at the end.
after turning on reverse bag order and picking up an item it goes in the 20th to last slot?
would it be possible to make newly added loot reverse too somehow maybe as an option or?
thanks

**Comment by rakkarage** [comment]
sorry i guess this is already an option i missed (reverse slot order) sorry thanks

**Comment by Hangkiw** [comment]
have you diferent bags? cuz i do and this happend to me as well, but did you try only Reverse bag?, i mean if you use reverse slot and reverse bag is liek you turn the same thing, that what i did, check reverse  bag, in that way the defaul (16slot bag) is on the bottom, and placed the current items as i wished and all the new ones is getting from top to bottom.

**Comment by Hangkiw** [comment]
have you diferent bags? cuz i do and this happend to me as well, but did you try only Reverse bag?, i mean if you use reverse slot and reverse bag is like you turn the same thing around, i did check reverse bag ONLY, in that way the defaul (16slot bag) is on the bottom, and placed the current items as i wished and all the new ones is getting from top to bottom.
