### ISSUE TITLE
feature request for SORT button

### ISSUE THREAD

**Issue by Nukme** [tullamods/Bagnon#434]
Hi,

I have a alt with Herbalism and hundreds of stacks of old herbs. I want to store some in herb bag, but whenever I left-click SORT button, it moves herbs from herb bag to reagent bank to fill empty slots. So is it possible to make an option to prevent SORT from moving things from herb bag? 

Thanks!

**Comment by Jaliborc** [comment]
Sorting is handled by Blizzard on the server side. Unfortunately we can’t make changes to the sorting algorithm ourselves.
This problem with profession bags bothers me too.
