### ISSUE TITLE
Legion errors

### ISSUE THREAD

**Issue by ceylina** [tullamods/Bagnon#435]
With some of the API changes in legion, some functions are removed or changed. These are the errors when bagnon is enabled

1x Bagnon\common\components\item.lua:15: attempt to call global 'GetAuctionItemClasses' (a nil value)
Bagnon\common\components\item.lua:15: in main chunk

Locals:
ADDON = "Bagnon"
Addon = <table> {
 SetDefaultModuleLibraries = <function> defined @Bagnon\libs\AceAddon-3.0\AceAddon-3.0.lua:381
 ItemSlot = <unnamed> {
 }
 Cache = <table> {
 }
 Enable = <function> defined @Bagnon\libs\AceAddon-3.0\AceAddon-3.0.lua:313
 UnregisterAllEvents = <function> defined @Bagnon\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:202
 BagFrame = <unnamed> {
 }
 EnableModule = <function> defined @Bagnon\libs\AceAddon-3.0\AceAddon-3.0.lua:346
 modules = <table> {
 }
 GetModule = <function> defined @Bagnon\libs\AceAddon-3.0\AceAddon-3.0.lua:230
 IterateEmbeds = <function> defined @Bagnon\libs\AceAddon-3.0\AceAddon-3.0.lua:456
 Bag = <unnamed> {
 }
 GetPlayerColor = <function> defined @Bagnon\common\core\players.lua:38
 defaultModuleLibraries = <table> {
 }
 GetPlayerColorString = <function> defined @Bagnon\common\core\players.lua:30
 GetPlayerIcon = <function> defined @Bagnon\common\core\players.lua:11
 UnregisterChatCommand = <function> defined @Bagnon\libs\AceConsole-3.0\AceConsole-3.0.lua:111
 GetBagFamily = <function> defined @Bagnon\common\core\bags.lua:84
 GetBagSize = <function> defined @Bagnon\common\core\bags.lua:49
 BAG_TYPES = <table> {
 }
 Printf = <function> defined @Bagnon\libs\AceConsole-3.0\AceConsole-3.0.lua:69
 GetSpecificProfile = <function> defined @Bagnon\common\core\settings.lua:147
 GetName = <function> defined @Bagnon\libs\AceAddon-3.0\AceAddon-3.0.lua:298
 GetBagType = <function> defined @Bagnon\common\core\bags.lua:80
 GetArgs = <function> defined @Bagnon\libs\AceConsole-3.0\AceConsole-3.0.lua:144
 IsBagShown = <function> defined @Bagnon\common\core\bags.lua:53
 name = "Bagnon"
 IsBank = <function> defined @Bagnon\common\core\bags.lua:19
 IsEnabled = <function> defined @Bagnon\libs\AceAddon-3.0\AceAddon-3.0.lua:465
 IsReagents = <function> defined @Bagnon\common\core\bags.lua:23
 GetBagInfo = <function> defined @Bagnon\common\core\bags.lua:34
 DisableModule = <function> defined @Bagnon\libs\AceAddon-3.0\AceAddon-3.0.lua:364
 NewClass = <function> defined @Bagnon\common\core\classes.lua:21
 IsBackpackBag = <function> defined @Bagnon\common\core\bags.lua:15
 IsBackpack = <function> defined @Bagnon\common\core\bags.lua:11
 StartupSettings = <function> defined @Bagnon\common\core\settings.lua:74
 RegisterMessage = <function> defined @Bagnon\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:118
 UnregisterMessage = <function> defined @Bagnon\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:181
 Print = <function> defined @Bagnon\libs\AceConsole-3.0\AceConsole-3.0.lua:54
 IsBagCached = <function> defined @Bagnon\common\core\bags.lua:38
 IsBagLocked = <function> defined @Bagnon\common\core\bags.lua:42
 UnregisterEvents = <function> defined @Bagnon\common\core\classes.lua:75
 IsBankBag = <function> defined @Bagnon\common\core\bags.lua:27
 IsModule = <function> defined @Bagnon\libs\AceAddon-3.0\AceAddon-3.0.lua:482
 GetProfile = <function> defined @Bagnon\common\core\settings.lua:143
 SetDefaultModuleState = <function> defined @Bagnon\libs\AceAddon-3.0\AceAddon-3.0.lua:401
 SetProfile = <function> defined @Bagnon\common\core\settings.lua:138
 StartupProfile = <function> defined @Bagnon\common\core\settings.lua:132
 SetEnabledState = <function> defined @Bagnon\libs\AceAddon-3.0\AceAddon-3.0.lua:438
 UpdateSettings = <function> defined @Bagnon\common\core\settings.lua:111
 enabledState = true
 

Second error

1x ...ceBagnon\common\components\tooltipCounts.lua:115: hooksecurefunc(): SetTradeSkillItem is not a function
[C]: in function `hooksecurefunc'
...ceBagnon\common\components\tooltipCounts.lua:115: in function <...ceBagnon\common\components\tooltipCounts.lua:111>
...ceBagnon\common\components\tooltipCounts.lua:131: in function `HookTooltips'
Bagnon\main.lua:24: in function <Bagnon\main.lua:20>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
Bartender4\libs\AceAddon-3.0\AceAddon-3.0-12.lua:558: in function `EnableAddon'
Bartender4\libs\AceAddon-3.0\AceAddon-3.0-12.lua:651: in function <Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:390: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:413: in function `CombatLog_LoadUI'
FrameXML\UIParent.lua:998: in function <FrameXML\UIParent.lua:894>

Locals:
nil

Third error

1x ...\Bagnon\libs\LibItemSearch-1.2\LibItemSearch-1.2-12.lua:205: attempt to call global 'GetAuctionItemClasses' (a nil value)
...\Bagnon\libs\LibItemSearch-1.2\LibItemSearch-1.2-12.lua:205: in main chunk

Locals:
Search = <table> {
 OR = "or"
 NOT_MATCH = "not"
 NOT = "Not"
 Find = <function> defined @Bagnon\libs\CustomSearch-1.0\CustomSearch-1.0.lua:133
 Match = <function> defined @Bagnon\libs\CustomSearch-1.0\CustomSearch-1.0.lua:56
 MatchAny = <function> defined @Bagnon\libs\CustomSearch-1.0\CustomSearch-1.0.lua:48
 ACCENTS = <table> {
 }
 MatchAll = <function> defined @Bagnon\libs\CustomSearch-1.0\CustomSearch-1.0.lua:38
 UseFilter = <function> defined @Bagnon\libs\CustomSearch-1.0\CustomSearch-1.0.lua:123
 Compare = <function> defined @Bagnon\libs\CustomSearch-1.0\CustomSearch-1.0.lua:152
 Matches = <function> defined @Bagnon\libs\CustomSearch-1.0\CustomSearch-1.0.lua:29
 Filter = <function> defined @Bagnon\libs\CustomSearch-1.0\CustomSearch-1.0.lua:101
 Clean = <function> defined @Bagnon\libs\CustomSearch-1.0\CustomSearch-1.0.lua:142
}
Unfit = <table> {
}
Lib = <table> {
 TooltipPhrase = <function> defined @Bagnon\libs\LibItemSearch-1.2\LibItemSearch-1.2.lua:26
 InSet = <function> defined @Bagnon\libs\LibItemSearch-1.2\LibItemSearch-1.2.lua:30
 Tooltip = <function> defined @Bagnon\libs\LibItemSearch-1.2\LibItemSearch-1.2.lua:22
 Matches = <function> defined @Bagnon\libs\LibItemSearch-1.2\LibItemSearch-1.2.lua:18
 Filters = <table> {
 }
}
qualities = <table> {
 1 = "common"
 2 = "uncommon"
 3 = "rare"
 4 = "epic"
 5 = "legendary"
 6 = "artifact"
 7 = "heirloom"
 8 = "wow token"
 0 = "poor"
}
scanner = LibItemSearchTooltipScanner {
 0 = <userdata>
 updateTooltip = 0.2
 needsReset = true
}
(*temporary) = <table> {
 type = <table> {
 }
 name = <table> {
 }
 requiredlevel = <table> {
 }
 tip = <table> {
 }
 level = <table> {
 }
 usable = <table> {
 }
 quality = <table> {
 }
}
(*temporary) = <table> {
 canSearch = <function> defined @Bagnon\libs\LibItemSearch-1.2\LibItemSearch-1.2.lua:167
 cache = <table> {
 }
 match = <function> defined @Bagnon\libs\LibItemSearch-1.2\LibItemSearch-1.2.lua:171
}
(*temporary) = <table> {
 boa = "Binds to Battle.net account"
 bop = "Binds when picked up"
 soulbound = "Binds when picked up"
 bou = "Binds when used"
 bound = "Binds when picked up"
 boe = "Binds when equipped"
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = 10
(*temporary) = nil
(*temporary) = "attempt to call global 'GetAuctionItemClasses' (a nil value)"

Fourth Error

1x Bagnon\libs\Unfit-1.0\Unfit-1.0-7.lua:61: table index is nil
Bagnon\libs\Unfit-1.0\Unfit-1.0-7.lua:61: in main chunk

Locals:
Lib = <table> {
}
_ = "Hunter"
Class = "HUNTER"
Unusable = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 5 = true
 6 = true
}
(for index) = 1
(for limit) = 2
(for step) = 1
class = 1
subs = <table> {
 1 = 0
 2 = 2
 3 = 3
 4 = 4
 5 = 5
 6 = 6
 7 = 7
 8 = 8
 9 = 9
 10 = 10
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = 5
 2 = 6
 3 = 16
}
(for control) = 3
i = 3
subclass = 16
(*temporary) = nil
(*temporary) = 3
(*temporary) = 16
(*temporary) = "table index is nil"

**Comment by ceylina** [comment]
Just wanted to also add that the library unfit.lua is out of date and throwing errors.

**Comment by yoshimo** [comment]
@Jaliborc  @Tuller https://github.com/icyblade/wow_addons/tree/master/Bagnon has fixes for legion
Could you integrate them into Bagnon and release a version that is compatible with 6.2 and 7.x?

**Comment by Jaliborc** [comment]
Not until I have access to legion

**Comment by ceylina** [comment]
Both curse and wowinterface can help you get into beta. Being a developer of so many addons people use, there is no reason you should not be given access

http://www.wowace.com/announcements/wow-legion-beta-invites/
