### ISSUE TITLE
Some Connected Realm characters not showing in Bagnon

### ISSUE THREAD

**Issue by dwig102** [tullamods/Bagnon#440]
Bagnon ver 6.2.7

I've got characters on the two connected realms Azjol-Nerub and Khaz Modan, and I did some testing and found it's almost the same issue as #272 back in 2014; I can see KM characters when I'm on AN, but I cannot see AN characters when I'm on KM. The difference is instead of spaces, it's the dash in Azjol-Nerub causing the realm compare to fail. I've confirmed this through running dumps of GetRealmName() ("Azjol-Nerub" and "Khaz Modan") and GetAutoCompleteRealms() ("AzjolNerub" and "KhazModan"). In my copy of LibItemCahce-1.1\Core.lua Lib:IterateRealms() function, I added a third condition to the realm compare to remove dashes and that has the addon working properly. If you'd like mine I can load it for you, or if you have a more elegant solution, that would probably be better. 

Cheers, and thanks for all the hard work!

**Comment by Jaliborc** [comment]
Fixed in beta version
