### ISSUE TITLE
Legion PTR/Beta Build 22248 - Unfit-1.0 issue

### ISSUE THREAD

**Issue by TheGoofUS** [tullamods/Bagnon#445]
Opened my bags on my hunter.
I'm not sure what is causing this issue, but the Bug Report is below:

```
Date: 2016-07-15 23:29:29
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Bagnon\libs\Unfit-1.0\Unfit-1.0.lua line 125:
   attempt to index field '?' (a nil value)
Debug:
   Bagnon\libs\Unfit-1.0\Unfit-1.0.lua:125:
      Bagnon\libs\Unfit-1.0\Unfit-1.0.lua:123
   (tail call): ?
   Bagnon\common\components\item.lua:367: UpdateBorder()
   Bagnon\common\components\item.lua:399: UpdateSearch()
   Bagnon\common\components\item.lua:251: DelayedUpdates()
   Bagnon\common\components\item.lua:245:
      Bagnon\common\components\item.lua:243
Locals:
self = <table> {
 IsItemUnusable = <function> defined @Interface\AddOns\Bagnon\libs\Unfit-1.0\Unfit-1.0.lua:116
 unusable = <table> {
 }
 IsClassUnusable = <function> defined @Interface\AddOns\Bagnon\libs\Unfit-1.0\Unfit-1.0.lua:123
}
class = 1
subclass = 0
slot = "INVTYPE_BAG"
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
Lib = <table> {
 IsItemUnusable = <function> defined @Interface\AddOns\Bagnon\libs\Unfit-1.0\Unfit-1.0.lua:116
 unusable = <table> {
 }
 IsClassUnusable = <function> defined @Interface\AddOns\Bagnon\libs\Unfit-1.0\Unfit-1.0.lua:123
}

AddOns:
  Swatter, v5.21g.5579 (SanctimoniousSwamprat)
  BagBrother, v
  Bagnon, v7.0.0
  BankItems, v6.2.4.0
  BrokerStartMenu, v0.1.0-beta+r20160514123746
  ClassicQuestLog, v1.2.1
  Details, v
  DetailsChartViewer, v
  DetailsDeathGraphs, v
  DetailsDmgRank, v
  DetailsDpsTuning, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsRaidInfoEmeraldNightmare, v
  DetailsRaidInfoNighthold, v
  DetailsRaidPowerBars, v
  DetailsTargetCaller, v
  DetailsTimeAttack, v
  DetailsTimeLine, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  ElvUI, v10.00
  Foglight, v3.0.1b
  GTFO, v4.38.2
  HandyNotes, vr265
  HandyNotesDraenorTreasures, v1.18a
  HandyNotesLegionRaresTreasures, v0.4
  HealBot, v6.2.3.1
  HereBeDragons10, v1.09-release-13-g8204a65
  IceHUD, v1.10
  MinimapButtonFrame, v3.1.10e
  MinimapButtonFrameSkinPack, v3.0.1b
  Quartz, v3.2.7-6-ge000094
  TomTom, vv60200-2.1.0
  WoWPro, v7.0.3G
  WoWProLeveling, v7.0.3G
  BlizRuntimeLib_enUS v7.0.3.70000 <none>
  (ck=3cb)
````

**Comment by FrogZilla83** [comment]
Came to report the same thing. I did notice it happened with a quest reward of Addie's Ink-Stained Satchel. It is a 26 slot bag. Once I sold that item the error went away. Not sure if it happening with any bag in inventory or just the new one I got on the PTR. Hope that info helps.

**Comment by jsutan** [comment]
Also happening with the Black Temple neck, Blessed Medallion of Karabor:

495x Bagnon\libs\Unfit-1.0\Unfit-1.0-8.lua:125: attempt to index field '?' (a nil value)
Bagnon\libs\Unfit-1.0\Unfit-1.0-8.lua:125: in function <Bagnon\libs\Unfit-1.0\Unfit-1.0.lua:123>
(tail call): ?
Bagnon\common\components\item.lua:367: in function `UpdateBorder'
Bagnon\common\components\item.lua:399: in function `UpdateSearch'
Bagnon\common\components\item.lua:251: in function `DelayedUpdates'
Bagnon\common\components\item.lua:245: in function <Bagnon\common\components\item.lua:243>

Locals:
self = <table> {
 IsItemUnusable = <function> defined @Bagnon\libs\Unfit-1.0\Unfit-1.0.lua:116
 IsClassUnusable = <function> defined @Bagnon\libs\Unfit-1.0\Unfit-1.0.lua:123
 unusable = <table> {
 }
 cannotDual = true
}
class = 12
subclass = 0
slot = "INVTYPE_NECK"
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
Lib = <table> {
 IsItemUnusable = <function> defined @Bagnon\libs\Unfit-1.0\Unfit-1.0.lua:116
 IsClassUnusable = <function> defined @Bagnon\libs\Unfit-1.0\Unfit-1.0.lua:123
 unusable = <table> {
 }
 cannotDual = true
}

**Comment by Torsin** [comment]
This is caused by, among other things, Bag(s) within the your bags.  There is already a proposed fix:

[https://github.com/Jaliborc/Unfit-1.0/pull/3/files](https://github.com/Jaliborc/Unfit-1.0/pull/3/files)
