### ISSUE TITLE
Live pre patch open guild bank error - Fix posted in comments

### ISSUE THREAD

**Issue by ceylina** [tullamods/Bagnon#447]
Version 7.0.0

Just trying to open the guild bank

1x Bagnon_GuildBank\components\tab.lua:62: attempt to call method 'SetToFileData' (a nil value)
Bagnon_GuildBank\components\tab.lua:62: in function `Update'
Bagnon_GuildBank\components\tab.lua:45: in function `RegisterEvents'
Bagnon\common\components\bag.lua:72: in function `New'
Bagnon_GuildBank\components\tab.lua:14: in function `New'
Bagnon\common\components\bagFrame.lua:17: in function `New'
Bagnon\components\frame.lua:407: in function `CreateBagFrame'
Bagnon\components\frame.lua:418: in function `PlaceBagFrame'
Bagnon\components\frame.lua:248: in function `Layout'
Bagnon\components\frame.lua:108: in function `Update'
Bagnon\components\frame.lua:78: in function <Bagnon\components\frame.lua:75>
[C]: in function `Show'
Bagnon\components\frame.lua:59: in function `ShowFrame'
Bagnon\main.lua:94: in function `ShowFrame'
Bagnon_GuildBank\main.lua:14: in function `OnOpen'
Bagnon\main.lua:38: in function `GuildBankFrame_LoadUI'
FrameXML\UIParent.lua:1495: in function <FrameXML\UIParent.lua:891>

Locals:
self = BagnonGuildTab1 {
 0 = <userdata>
 Count = <unnamed> {
 }
 frame = BagnonFrameguild {
 }
 Icon = BagnonGuildTab1IconTexture {
 }
 FilterIcon = <unnamed> {
 }
}
name = "Gear"
icon = 878246
viewable = true
color = 1
iconID = 878246
(*temporary) = nil
(*temporary) = BagnonGuildTab1IconTexture {
 0 = <userdata>
}
(*temporary) = 878246
(*temporary) = "attempt to call method 'SetToFileData' (a nil value)"

**Comment by ceylina** [comment]
Looks like you can just change it to 

self.Icon:SetTexture(iconID)

http://www.wowinterface.com/forums/showthread.php?p=316520

**Comment by Jaliborc** [comment]
Thank you, will release a new version today!
