### ISSUE TITLE
Pre-Expansion Legion Bagnon wont work

### ISSUE THREAD

**Issue by ethan062001** [tullamods/Bagnon#448]
It does let me see anything in my bags at all

**Comment by Pinkachu** [comment]
I can see my bags themselves and my money but not the contents. I had to disable the addon for now.

**Comment by shazzmuzik** [comment]
I also cannot open any Bags in WoW. I can see a small window with Search etc but no actual bags are visible. See attached pic
![wowscrnshot_072016_072321](https://cloud.githubusercontent.com/assets/20545978/16967131/00ec9196-4e4b-11e6-8b7c-3c179980bcd9.jpg)

**Comment by Chimamicita** [comment]
It does not appear that anything is happening for me with this addon. I have updated it both through Curse Client as well as through the zip folder for the 7.0 beta version but neither work. I am not getting error messages I just am able to open my bags one by one in the typical WOW fashion. The addon is loaded but nothing is happening with it

**Comment by Chimamicita** [comment]
Thank you so much for making corrections to this program so rapidly! Works perfectly now!

**Comment by rodrigowa** [comment]
In my account, bagnon works very well in server Goldrinn and dont open bags (how in the picture of shazzmuzik) in Tol Barad server.
