### ISSUE TITLE
Bagnon[BETA]: Tool Tip Comparison Overlay

### ISSUE THREAD

**Issue by adammartin** [tullamods/Bagnon#449]
When using the tooltip comparison with Bagnon active the frames to compare overlay each other.  This makes it impossible to compare items and have bagnon working.
![capture](https://cloud.githubusercontent.com/assets/728069/16971424/416fcbaa-4de9-11e6-86f9-0b7ca029195f.PNG)

**Comment by Jaliborc** [comment]
Duplicate
