### ISSUE TITLE
Error with 7.0.2

### ISSUE THREAD

**Issue by Jeehell** [tullamods/Bagnon#450]
Message: Interface\AddOns\Bagnon\libs\Unfit-1.0\Unfit-1.0.lua:125: attempt to index field '?' (a nil value)
Time: 07/19/16 21:52:08
Count: 1
Stack: Interface\AddOns\Bagnon\libs\Unfit-1.0\Unfit-1.0.lua:125: in function <Interface\AddOns\Bagnon\libs\Unfit-1.0\Unfit-1.0.lua:123>
(tail call): ?
Interface\AddOns\Bagnon\common\components\item.lua:367: in function `UpdateBorder'
Interface\AddOns\Bagnon\common\components\item.lua:399: in function `UpdateSearch'
Interface\AddOns\Bagnon\common\components\item.lua:251: in function `DelayedUpdates'
Interface\AddOns\Bagnon\common\components\item.lua:245: in function <Interface\AddOns\Bagnon\common\components\item.lua:243>

Locals: self = <table> {
 IsItemUnusable = <function> defined @Interface\AddOns\Bagnon\libs\Unfit-1.0\Unfit-1.0.lua:116
 IsClassUnusable = <function> defined @Interface\AddOns\Bagnon\libs\Unfit-1.0\Unfit-1.0.lua:123
 unusable = <table> {
 }
 cannotDual = true
}
class = 1
subclass = 0
slot = "INVTYPE_BAG"
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
Lib = <table> {
 IsItemUnusable = <function> defined @Interface\AddOns\Bagnon\libs\Unfit-1.0\Unfit-1.0.lua:116
 IsClassUnusable = <function> defined @Interface\AddOns\Bagnon\libs\Unfit-1.0\Unfit-1.0.lua:123
 unusable = <table> {
 }
 cannotDual = true
}

Thanks for looking into this...

**Comment by kemayo** [comment]
I have a pull request for Unfit-1.0 that'll fix this: https://github.com/Jaliborc/Unfit-1.0/pull/3

**Comment by Jeehell** [comment]
Many thanks for the fast fix…   All is now good with my bags…

Jean-Luc
(Xylokan, Horde warlock on Frostmourne)
