### ISSUE TITLE
Deleting old character dropdown item data error

### ISSUE THREAD

**Issue by ceylina** [tullamods/Bagnon#453]
I noticed all my pre 7.0 character data had got corrupt where everything was just a clone of my currently logged in character so I decided to open the bags and left click the character button and clear the old alts out. When doing so and after the second one, this error showed up

1x ...eBagnon\common\components\playerDropdown.lua:54: bad argument #2 to 'format' (string expected, got no value)
[C]: in function `format'
...eBagnon\common\components\playerDropdown.lua:54: in function `initFunction'
FrameXML\UIDropDownMenu.lua:69: in function `UIDropDownMenu_Initialize'
FrameXML\UIDropDownMenu.lua:910: in function <FrameXML\UIDropDownMenu.lua:775>
[C]: ?
[C]: ?
[C]: in function `ToggleDropDownMenu'
...eBagnon\common\components\playerDropdown.lua:80: in function `TogglePlayerDropdown'
Bagnon\components\playerSelector.lua:60: in function <Bagnon\components\playerSelector.lua:56>

Locals:
(*temporary) = "|T%s:14:14:-3:0|t"
(*temporary) = "string expected, got no value"

**Comment by ceylina** [comment]
Character button is actually corrupt. Logging into alts clones the current logged in character to all alt drop down lists

**Comment by Jaliborc** [comment]
Fixed
