### ISSUE TITLE
Lua error upon opening guild bank

### ISSUE THREAD

**Issue by sydbarrett74** [tullamods/Bagnon#455]
Using latest version of bagnon addon with WoW 7.0.2 -- text of error in attachment.
[WoW Client Lua error 20160720-04.09.35.txt](https://github.com/tullamods/Bagnon/files/373144/WoW.Client.Lua.error.20160720-04.09.35.txt)

**Comment by Torsin** [comment]
This is caused by, among other things, Bags within the Guild Bank frame.  There is already a proposed fix:

[https://github.com/Jaliborc/Unfit-1.0/pull/3/files](url)

**Comment by ceylina** [comment]
Just tested proposed fix and it indeed fixes it :D

**Comment by sydbarrett74** [comment]
The proposed diff works for me too!

**Comment by Jaliborc** [comment]
Fixed
