### ISSUE TITLE
702 BB & compare frame bugs

### ISSUE THREAD

**Issue by Voxxel** [tullamods/Bagnon#456]
Using the latest 7.0.2. from curseforge I experience a bug when the addon doesn't sort the comparing frames in the reverse direction when it clamps to the right edge of the screen - see the attached sceenshot.

There's another bug on the screenshot with BagBrother but I think that's reported already.

![wowscrnshot_072016_130130](https://cloud.githubusercontent.com/assets/3882152/16984678/d1b1d914-4e7b-11e6-88e8-2509398fae92.jpg)

**Comment by Jaliborc** [comment]
Looking at this

**Comment by tanttr332** [comment]
having the same problem with it doing that

**Comment by Karalum** [comment]
was looking for this :dart:

**Comment by Hangkiw** [comment]
Hey Jailborc, thanks for your work,. so I solved,... in Item.lua --[[ Tooltip ]]-- you setted " >= " and that why comparation doesn't work when the bag is on right site,... changed to " <= " Now works just perfect hehe Thanks again for this amazing addon man.

**Comment by Voxxel** [comment]
Hangkiw, this doesn't change anything for me. Are you saying to change the **line 419** in 
Bagnon/common/components/item.lua in version 7.0.3

from 
`	if self:GetRight() >= (GetScreenWidth() / 2) then`
to
`	if self:GetRight() <= (GetScreenWidth() / 2) then`

Doesn't work for me. Same overlapping as before, even if I enable only the main "Bagnon" component and deleted the .lua from WTF.

**Comment by Hangkiw** [comment]
Yes Voxxel, MY BAD sorry,.. I was excited about making it work, so i forgot that before i deleted the "else case" not need to have an else case because he call that sentence before with <=,... anyhow just set it:
```
function ItemSlot:AnchorTooltip()
	if self:GetRight() <= (GetScreenWidth() / 2) then
		GameTooltip:SetOwner(self, 'ANCHOR_LEFT')
		end
end
```

**Comment by Voxxel** [comment]
This way it works! Thank you. Works different than in past Bagnon / default UI, it anchors item tooltips to the left side while the base tooltip reaches the middle of the screen and anchors to the right when in the left side of the screen.

But it's working, nonetheless, no overlapping, so great job, thanks for the fix!

**Comment by Jaliborc** [comment]
I'm aware of this bug and will fix it ASAP. Unfortunately this week I'm in a conference in Anaheim, so it is almost impossible to come online.

Sorry for the delay. Please be patient.

**Comment by Hangkiw** [comment]
I'am sorry Jailborc i just tried to help a little with this issue while you give us a new update, but ppl just keep posting the same bugs without read the list. Thanks for this great addon tho'.

**Comment by Othra** [comment]
@Hangkiw I read your fix but it did nothing for me, compare frames are still overlapping sadly. Lets wait for the promised fix, this is the only bag addon I use.

**Comment by Hangkiw** [comment]
@Othra hi, did you put the text exactly like i posted? because sometome if you change uppercaps or give extra tabs not work. [HERE IS](https://www.dropbox.com/s/l3zshq4v473htk6/item.lua?dl=0) the item.lua that i use if you like to try it meanwhile.
