### ISSUE TITLE
Bangor giving Fatalities

### ISSUE THREAD

**Issue by shane3547** [tullamods/Bagnon#457]
Here is the bug that keeps coming up overtime I open my bags... and I mean every time.

2x Bagnon\libs\Unfit-1.0\Unfit-1.0-8.lua:125: attempt to index field '?' (a nil value)
Bagnon\libs\Unfit-1.0\Unfit-1.0-8.lua:125: in function <Bagnon\libs\Unfit-1.0\Unfit-1.0.lua:123>
(tail call): ?
Bagnon\common\components\item.lua:367: in function `UpdateBorder'
Bagnon\common\components\item.lua:399: in function `UpdateSearch'
Bagnon\common\components\item.lua:251: in function `DelayedUpdates'
Bagnon\common\components\item.lua:245: in function <Bagnon\common\components\item.lua:243>

Locals:
self = <table> {
 IsItemUnusable = <function> defined @Bagnon\libs\Unfit-1.0\Unfit-1.0.lua:116
 unusable = <table> {
 }
 IsClassUnusable = <function> defined @Bagnon\libs\Unfit-1.0\Unfit-1.0.lua:123
}
class = 1
subclass = 0
slot = "INVTYPE_BAG"
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
Lib = <table> {
 IsItemUnusable = <function> defined @Bagnon\libs\Unfit-1.0\Unfit-1.0.lua:116
 unusable = <table> {
 }
 IsClassUnusable = <function> defined @Bagnon\libs\Unfit-1.0\Unfit-1.0.lua:123
}

**Comment by Torsin** [comment]
This is caused by, among other things, Bag(s) within the your bags.  There is already a proposed fix:

[https://github.com/Jaliborc/Unfit-1.0/pull/3/files](url)

**Comment by shane3547** [comment]
The link you have gives a 404 Page not found.

**Comment by Torsin** [comment]
Fixed the link

**Comment by shane3547** [comment]
Thanks, that's working now... 

Can you please make sure to update the actual file for Curse.

Thanks
