### ISSUE TITLE
User Bank / User Inventory / Legion Patch: Global error occurred while accessing user bank

### ISSUE THREAD

**Issue by ImaintainIt** [tullamods/Bagnon#458]
Date: 2016-07-20 09:11:46
ID: 86
Error occured in: Global
Count: 1
Message: ..\AddOns\Bagnon\libs\Unfit-1.0\Unfit-1.0.lua line 125:
   attempt to index field '?' (a nil value)
Debug:
   Bagnon\libs\Unfit-1.0\Unfit-1.0.lua:125:
      Bagnon\libs\Unfit-1.0\Unfit-1.0.lua:123
   (tail call): ?
   Bagnon\common\components\item.lua:367: UpdateBorder()
   Bagnon\common\components\item.lua:399: UpdateSearch()
   Bagnon\common\components\item.lua:251: DelayedUpdates()
   Bagnon\common\components\item.lua:245:
      Bagnon\common\components\item.lua:243
Locals:
self = <table> {
 IsItemUnusable = <function> defined @Interface\AddOns\Bagnon\libs\Unfit-1.0\Unfit-1.0.lua:116
 unusable = <table> {
 }
 IsClassUnusable = <function> defined @Interface\AddOns\Bagnon\libs\Unfit-1.0\Unfit-1.0.lua:123
}
class = 1
subclass = 0
slot = "INVTYPE_BAG"
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
Lib = <table> {
 IsItemUnusable = <function> defined @Interface\AddOns\Bagnon\libs\Unfit-1.0\Unfit-1.0.lua:116
 unusable = <table> {
 }
 IsClassUnusable = <function> defined @Interface\AddOns\Bagnon\libs\Unfit-1.0\Unfit-1.0.lua:123
}

AddOns:
  Swatter, v5.21f.5579 (SanctimoniousSwamprat)
  AucAdvanced, v5.21f.5579 (SanctimoniousSwamprat)
  AucFilterBasic, v5.21f.5579 (SanctimoniousSwamprat)
  AucFilterOutlier, v5.21f.5579.2531(5.21f/embedded)
  AucMatchUndercut, v5.21f.5579.2531(5.21f/embedded)
  AucStatHistogram, v5.21f.5579 (SanctimoniousSwamprat)
  AucStatiLevel, v5.21f.5579 (SanctimoniousSwamprat)
  AucStatPurchased, v5.21f.5579 (SanctimoniousSwamprat)
  AucStatSales, v5.21f.5579.2842(5.21f/embedded)
  AucStatSimple, v5.21f.5579 (SanctimoniousSwamprat)
  AucStatStdDev, v5.21f.5579 (SanctimoniousSwamprat)
  AucStatWOWEcon, v5.21f.5579.2530(5.21f/embedded)
  AucUtilAHWindowControl, v5.21f.5579.3311(5.21f/embedded)
  AucUtilAppraiser, v5.21f.5579.2530(5.21f/embedded)
  AucUtilAskPrice, v5.21f.5579.3175(5.21f/embedded)
  AucUtilAutoMagic, v5.21f.5579.3142(5.21f/embedded)
  AucUtilCompactUI, v5.21f.5579.2530(5.21f/embedded)
  AucUtilEasyBuyout, v5.21f.5579.3583(5.21f/embedded)
  AucUtilFixAH, v5.21f.5579 (SanctimoniousSwamprat)
  AucUtilItemSuggest, v5.21f.5579.3108(5.21f/embedded)
  AucUtilPriceLevel, v5.21f.5579.2545(5.21f/embedded)
  AucUtilScanButton, v5.21f.5579.2530(5.21f/embedded)
  AucUtilScanFinish, v5.21f.5579.2530(5.21f/embedded)
  AucUtilScanProgress, v5.21f.5579.2530(5.21f/embedded)
  AucUtilScanStart, v5.21f.5579.4784(5.21f/embedded)
  AucUtilSearchUI, v5.21f.5579.5272(5.21f/embedded)
  AucUtilSimpleAuction, v5.21f.5579.4546(5.21f/embedded)
  AucUtilVendMarkup, v5.21f.5579.2530(5.21f/embedded)
  Babylonian, v5.1.DEV.332(/embedded)
  BagBrother, v
  Bagnon, v7.0.2
  Bartender4, v4.7.0
  BeanCounter, v5.21f.5579 (SanctimoniousSwamprat)
  Configator, v5.1.DEV.396(/embedded)
  DebugLib, v5.1.DEV.337(/embedded)
  Enchantrix, v5.21f.5579 (SanctimoniousSwamprat)
  EnchantrixBarker, v5.21f.5579 (SanctimoniousSwamprat)
  LibExtraTip, v5.12.DEV.395(/embedded)
  MikScrollingBattleText, v5.7.143
  Postal, vv3.5.8
  Quartz, v3.3.0
  SlideBar, v5.21f.5579 (SanctimoniousSwamprat)
  Stubby, v5.21f.5579 (SanctimoniousSwamprat)
  TipHelper, v5.12.DEV.389(/embedded)
  Titan, v5.6.34.60200
  TitanBag, v5.6.34.60200
  TitanClock, v5.6.34.60200
  TitanGold, v5.6.34.60200
  TitanLocation, v5.6.34.60200
  TitanLootType, v5.6.34.60200
  TitanPerformance, v5.6.34.60200
  TitanRepair, v5.6.34.60200
  TitanVolume, v5.6.34.60200
  TitanXP, v5.6.34.60200
  ZPerl, v4.3.1
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidAdmin, v
  ZPerlRaidFrames, v
  ZPerlRaidHelper, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_enUS v7.0.3.70000 <none>
  (ck=a4b)

**Comment by tbrown5238** [comment]
I was having the same problem. It seems to happen any time I bring up a bagnon window that includes an item I cannot equip. I unchecked the option to color unequippable items, and haven't seen the error since.

**Comment by Jaliborc** [comment]
Fixed
