### ISSUE TITLE
BagBrother Currency Display clones selected toon's class and money

### ISSUE THREAD

**Issue by KyrosKrane** [tullamods/Bagnon#459]
This issue is similar to others reported here where BagBrother is incorrectly reporting item counts, but it's about currency. When you view the currency window, it shows all other toons as your current class color, and the cash counts are the same for all toons. See the attached mini screenshot. (Toon names blanked out for privacy, but otherwise unaltered.) This is with Bagnon 7.0.2.

![bagbrother](https://cloud.githubusercontent.com/assets/458727/16996013/e80ab4e4-4e74-11e6-93d2-fab963af3b5d.png)

**Comment by HurtPillow** [comment]
This is what the incorrect item count looks like.  I chose an item that I knew for certain was only on one character, yet it counts the same amount on all of my characters, much like the currency issue.
![bagnon2](https://cloud.githubusercontent.com/assets/20564309/16998915/8f74922c-4e89-11e6-8aab-d04f05ba8496.jpg)

**Comment by Jaliborc** [comment]
Ok, I'll look into it.

**Comment by Gatheringofravens** [comment]
Having this issue as well. Very visually distracting and annoying.

**Comment by sirEgghead** [comment]
Same exact issue.  Thanks for all your hard work!

**Comment by Jaliborc** [comment]
Fixed!

**Comment by HurtPillow** [comment]
Thank you! it's perfect now, thanks for all you do!! <3 

----- Original Message -----

**Comment by KyrosKrane** [comment]
Confirmed, thank you!
