### ISSUE TITLE
Mouse Shift Compare bag item to Equipped Not working

### ISSUE THREAD

**Issue by Rothgarzod** [tullamods/Bagnon#461]
The ability to mouse over an item and press shift to compare to an already equipped item is not functioning.  I wasn't sure if this was an add-on issue or WoW issue... I disabled the add-on and the function works fine.  With the add-on enabled, the function does not work.  This is a vital in-game tool.  I expect there are a lot of these creeping up with the new expansion.  Your add-on is awesome and I have loved it ever since finding it.  Thanks for all you do.

**Comment by Jaliborc** [comment]
Fixed
