### ISSUE TITLE
Additional features of the other add-ons

### ISSUE THREAD

**Issue by DogmaTX** [tullamods/Bagnon#462]
Add in the settings (enable / disable) the comparison items without pressing the "SHIFT".

**Comment by DogmaTX** [comment]
[there is a similar add-on](http://mods.curse.com/addons/wow/moncaicompare)

**Comment by DogmaTX** [comment]
[Global highlighting of objects not only shopping bags.](http://www.wowinterface.com/downloads/info7142-oGlow.html)

**Comment by Jaliborc** [comment]
Out of scope of Bagnon
