### ISSUE TITLE
Can't access alt's bags/bank/void storage

### ISSUE THREAD

**Issue by Wayazaexa** [tullamods/Bagnon#464]
From what I've seen it's an issue on merged realms, possibly when you're on realm A, which is merged to realm B and realm B has a " " (space) in its name. The reason I think that's an issue is that I get the error(s) on Nordrassil, but not on Bronze Dragonflight, and they're merged with each other. Also the line 'realm = "Bronze"' in the error, it's just split way too conveniently for it to be a coincident. Third and last reason I think it's related to a space in the realm name is because of what someone reported via your Curse page:
> The interesting thing is that the addon works normally on other servers. On outland and sylvanas it works like a charm but on my main server,Defias Brotherhood who is the combined RP server,I get the afformentioned errors followed by lua errors.This also happens to Ravenholdt realm who is connected to Defias.In addition when I log in I get a lua error.

I can see the item count if I hover over an item the bag of one of my Nordrassil chars, but as soon as I hover with the mouse over my gold or left click the top left icon in the bag interface, I get an error. I also get an error as soon as I log in. Here's a paste of them both: http://pastebin.com/3BCbifdw

Oh, and if I disable BagBrother I don't get the errors, but obviously that removes the functionality I'm after in this case. Reinstalling Bagnon didn't work.

**Comment by Jaliborc** [comment]
Fixed in dev version
