### ISSUE TITLE
BagBrother stops working when using a char from a connected realm

### ISSUE THREAD

**Issue by Takamoko** [tullamods/Bagnon#466]
I installed Bagnon 7.0.3 and deleted all old config files (bagnon.* and bagbrother.*) from WTF\... I log into the realm "EU: Die Silberne Hand" and everything works. I have some chars and BagBrother allows me to view the bags and banks of the other chars. After switching to the connected real "EU: Die ewige Wacht" BagBrother stops working. It's not possible to select other chars from the Bagon-(bag-)window and the tooltip does not show any infos. When I quit WoW and delete the info for the second realm from BagBrother.lua everything works again (for the chars on the first realm).
[BagBrother_example.zip](https://github.com/tullamods/Bagnon/files/380228/BagBrother_example.zip)

Thanks for the addon, I hope this will get fixed in the near future.
Takamoko

**Comment by AbsolutgrndZer0** [comment]
I also am having this issue... basically I need to not use BagBrother on other realms until it's fixed... :(

**Comment by Jaliborc** [comment]
Fixed in dev version
