### ISSUE TITLE
Game freezes when viewing alt's bank/bags

### ISSUE THREAD

**Issue by DrkestShadow** [tullamods/Bagnon#467]
Since patch 7.0 and using Bagnon 7.0.3, every time I try to view any of my alts on the same server, the game freezes and I have to shut it down via Task Manager. I have waited up to 30 mins for it to clear with no luck.

**Comment by DrkestShadow** [comment]
How is this closed? It is still an issue. No update has been posted to my knowledge. No updates on Curse nor Curse Forge.

**Comment by phyber** [comment]
Lots of people saying this happens. It happens to me too. Really, why is this closed? If there's a fix or something we should do, you could at least post that at the same time as closing.
