### ISSUE TITLE
Can't do anything

### ISSUE THREAD

**Issue by RedArsenic** [tullamods/Bagnon#468]
I can't live without this Add :p 
Since the WoW's new version 7.0.3 ; i can't use Bagnon : When i press "b", it opens but i can't see the items in the bags, it doesn't show the places for items. 
What can i do to see it again ? 
Thanks !

![bagnon2](https://cloud.githubusercontent.com/assets/20643182/17104135/d56fa360-5281-11e6-8105-579bb41e6a2c.png)
![bagon](https://cloud.githubusercontent.com/assets/20643182/17104136/d5701c50-5281-11e6-82d1-a5d316ad5dc5.png)

**Comment by Jaliborc** [comment]
Do you have "show lua errors" enabled?
