### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by phantom892** [tullamods/Bagnon#469]
Message: ...s\Bagnon\libs\LibItemCache-1.1\Caches\BagBrother.lua:119: attempt to index field '?' (a nil value)
Time: 07/25/16 17:03:38
Count: 1
Stack: ...s\Bagnon\libs\LibItemCache-1.1\Caches\BagBrother.lua:119: in function <...s\Bagnon\libs\LibItemCache-1.1\Caches\BagBrother.lua:118>
(tail call): ?
(tail call): ?
...terface\AddOns\Bagnon\libs\LibItemCache-1.1\Core.lua:101: in function `IterateAlliedPlayers'
...ce\AddOns\Bagnon\common\components\tooltipCounts.lua:127: in function `HookTooltips'
Interface\AddOns\Bagnon\main.lua:24: in function <Interface\AddOns\Bagnon\main.lua:20>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...ddOns\GatherMate2\Libs\AceAddon-3.0\AceAddon-3.0.lua:558: in function `EnableAddon'
...ddOns\GatherMate2\Libs\AceAddon-3.0\AceAddon-3.0.lua:651: in function <...ddOns\GatherMate2\Libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:391: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:414: in function `CombatLog_LoadUI'
Interface\FrameXML\UIParent.lua:995: in function <Interface\FrameXML\UIParent.lua:891>

Locals: <none>

**Comment by Jaliborc** [comment]
Duplicate
