### ISSUE TITLE
index error

### ISSUE THREAD

**Issue by Arneas** [tullamods/Bagnon#470]
Not sure if you can fix this one, but thought I would post

Date: 2016-07-25 17:53:49
ID: 1
Error occured in: Global
Count: 1
Message: ...s\Bagnon\libs\LibItemCache-1.1\Caches\BagBrother.lua line 119:
   attempt to index field '?' (a nil value)
Debug:
   ...s\Bagnon\libs\LibItemCache-1.1\Caches\BagBrother.lua:119:
      ...s\Bagnon\libs\LibItemCache-1.1\Caches\BagBrother.lua:118
   (tail call): ?
   (tail call): ?
   ...terface\AddOns\Bagnon\libs\LibItemCache-1.1\Core.lua:101: IterateAlliedPlayers()
   ...ce\AddOns\Bagnon\common\components\tooltipCounts.lua:127: 
HookTooltips()
   Bagnon\main.lua:24:
      Bagnon\main.lua:20
   (tail call): ?
   [C]: ?
   [string "safecall Dispatcher[1]"]:9:
      [string "safecall Dispatcher[1]"]:5
   (tail call): ?
   ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:558: EnableAddon()
 ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:651:
      ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:636
   [C]: ?
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:391: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:414: CombatLog_LoadUI()
   ..\FrameXML\UIParent.lua:995:
      ..\FrameXML\UIParent.lua:891
Locals:
None
AddOns:
  MoncaiCompare, v6.2.0
  Swatter, v5.0.0 (<%codename%>)
  NPCScan, v7.0.3.5
  Atlas, v1.33.01
  AtlasBattlegrounds, v1.33.00
  AtlasBurningCrusade, v1.33.00
  AtlasCataclysm, v1.33.00
  AtlasClassicWoW, v1.33.00
  AtlasDungeonLocs, v1.33.01
  AtlasLegion, v1.33.00
  AtlasMistsofPandaria, v1.33.00
  AtlasOutdoorRaids, v1.33.00
 AtlasScenarios, v1.33.00
  AtlasTransportation, v1.33.01
  AtlasWarlordsofDraenor, v1.33.01
  AtlasWorldEvents, v3.15
  AtlasWrathoftheLichKing, v1.33.00
  AtlasLoot, vv8.01.00
  AtlasMajorCitiesEnhanced, vv1.08
  Auctionator, v4.0.4
  AutoRepair, v
  BagBrother, v
 Bagnon, v7.0.3
  DBMCore, v
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
ElvUI, v10.11
  ElvUIExtraActionBars, v2.29
  ElvUIRaidMarkers, v4.24
  GatherMate2, v1.36.1
  GreenWall, v1.7.2
  HandyNotes, vv1.4.7
  HandyNotesDraenorTreasures, v1.19a
  Incognito, v1.4.1
  InFlightLoad, v6.2.001
  MasterPlanA, vA
  MogIt, v3.6.1
  MountFarmHelper, v2.0
  Overachiever, v0.84
  PetBattleMaster, v7.0.2
 PetTracker, v7.0.0
  PetTrackerBreeds, v
  PetTrackerSwitcher, v
  PetTrackerUpgrades, v
  Postal, vv3.5.8
  Recount, vv7.0.3b release
  Scrap, v13.3
  ScrapSpotlight, v13.3
  SexyMap, v2.4.29
  Stubby, v5.21f.5579 (SanctimoniousSwamprat)
  Titan, v5.7.0.70000
  TitanBag, v5.7.0.70000
  TitanClock, v5.7.0.70000
  TitanCurrency, v7.0.3a
  TitanEnchanting, v4.0.001
  TitanGold, v5.7.0.70000
  TitanLocation, v5.7.0.70000
  TitanLootType, v5.7.0.70000
  TitanPerformance, v5.7.0.70000
  TitanRepair, v5.7.0.70000
  TitanVolume, v5.7.0.70000
  TitanXP, v5.7.0.70000
  TomTom, vv70000-1.0.0
  WeakAuras, v2.2.0.8
  BlizRuntimeLib_enUS v7.0.3.70000 <none>
  (ck=697)

**Comment by Jaliborc** [comment]
Fixed
