### ISSUE TITLE
"Shift" compare tooltips overlap at side of screen

### ISSUE THREAD

**Issue by BradCOnGitHub** [tullamods/Bagnon#471]
Attaching some examples

![wowscrnshot_072616_100447](https://cloud.githubusercontent.com/assets/15109073/17143409/c83121f0-5318-11e6-8313-31e9d2677de9.jpg)
![wowscrnshot_072616_100442](https://cloud.githubusercontent.com/assets/15109073/17143407/c82a8b92-5318-11e6-8ffe-f4c2d7b50d76.jpg)
![wowscrnshot_072616_100426](https://cloud.githubusercontent.com/assets/15109073/17143408/c82e4ad4-5318-11e6-8d16-6226d6ab8b9d.jpg)

**Comment by Satirica** [comment]
I came here to report the same bug.  Those screen shots look like mine.

**Comment by 2ndHouse** [comment]
Same here. I figured it was a Blizzard or Tiptac bug.

**Comment by Hangkiw** [comment]
Hi guys, well maybe you should check the issue "**702 BB & compare frame bugs #456**" i posted a fix for that issue while **Jaliborc** give us the oficial fix... (is a 7.0.2 version but works for 7.0.3 too)

**Comment by Jaliborc** [comment]
Duplicate
