### ISSUE TITLE
Shift Compare to equipped merging

### ISSUE THREAD

**Issue by ShadyWizard** [tullamods/Bagnon#473]
Whenever I compare a new item with what I already have the two boxes are merging or you can say that it is not switching to the other side https://drive.google.com/open?id=0B-BrIOpRjQOQeHFOUTBHMW1odzg

**Comment by ShadyWizard** [comment]
https://drive.google.com/open?id=0B-BrIOpRjQOQeHFOUTBHMW1odzg

**Comment by Hangkiw** [comment]
Hi shady, see: 702 BB & compare frame bugs #456
