### ISSUE TITLE
Breaks everytime you open a character in another realm whenever bagbrother is turned on.

### ISSUE THREAD

**Issue by Toeroe** [tullamods/Bagnon#475]
Throws this Lua error:

11x ...s\Bagnon\libs\LibItemCache-1.1-21\Caches\BagBrother.lua:112: attempt to index field '?' (a nil value)
...s\Bagnon\libs\LibItemCache-1.1-21\Caches\BagBrother.lua:112: in function <...s\Bagnon\libs\LibItemCache-1.1\Caches\BagBrother.lua:111>
(tail call): ?
Bagnon\libs\LibItemCache-1.1-21\Core.lua:57: in function `GetPlayerMoney'
Bagnon\components\moneyFrame.lua:63: in function `OnEnter'
Bagnon\components\moneyFrame.lua:23: in function <Bagnon\components\moneyFrame.lua:23>

Locals:
self = <table> {
 GetItemCounts = <function> defined @Bagnon\libs\LibItemCache-1.1\Caches\BagBrother.lua:72
 GetGuild = <function> defined @Bagnon\libs\LibItemCache-1.1\Caches\BagBrother.lua:107
 GetMoney = <function> defined @Bagnon\libs\LibItemCache-1.1\Caches\BagBrother.lua:111
 GetPlayer = <function> defined @Bagnon\libs\LibItemCache-1.1\Caches\BagBrother.lua:118
 GetBag = <function> defined @Bagnon\libs\LibItemCache-1.1\Caches\BagBrother.lua:32
 GetGuildTab = <function> defined @Bagnon\libs\LibItemCache-1.1\Caches\BagBrother.lua:58
 DeletePlayer = <function> defined @Bagnon\libs\LibItemCache-1.1\Caches\BagBrother.lua:125
 GetPlayers = <function> defined @Bagnon\libs\LibItemCache-1.1\Caches\BagBrother.lua:141
 GetRealms = <function> defined @Bagnon\libs\LibItemCache-1.1\Caches\BagBrother.lua:155
 GetNormalBag = <function> defined @Bagnon\libs\LibItemCache-1.1\Caches\BagBrother.lua:65
 GetItem = <function> defined @Bagnon\libs\LibItemCache-1.1\Caches\BagBrother.lua:45
 GetItemCount = <function> defined @Bagnon\libs\LibItemCache-1.1\Caches\BagBrother.lua:90
}
realm = "Thorium"
player = "Chìun"
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"

**Comment by Jaliborc** [comment]
Duplicate
