### ISSUE TITLE
Ignore items when sorting (enhancement)

### ISSUE THREAD

**Issue by FortyOneNY** [tullamods/Bagnon#476]
Would it be possible to have a user created list of items to ignore when using the sort button? I know that it is possible with ElvUI's bags, but I don't know if they are using custom sorting or Blizz's function. I'd really like to be able to keep hearthstones, profession tools, teleport clickies, etc at the top of my bags while everything else gets sorted to the bottom.

**Comment by Jaliborc** [comment]
We're using blizzard's
