### ISSUE TITLE
I get an error when I load a new toon

### ISSUE THREAD

**Issue by Tutonik** [tullamods/Bagnon#477]
My apologies, I didn't realize my issue was the same as the others, I would delete my post...if I could figure out how. 
Message: ...s\Bagnon\libs\LibItemCache-1.1\Caches\BagBrother.lua:119: attempt to index field '?' (a nil value)
Time: 08/01/16 11:30:21
Count: 1
Stack: ...s\Bagnon\libs\LibItemCache-1.1\Caches\BagBrother.lua:119: in function <...s\Bagnon\libs\LibItemCache-1.1\Caches\BagBrother.lua:118>
(tail call): ?
(tail call): ?
...terface\AddOns\Bagnon\libs\LibItemCache-1.1\Core.lua:101: in function `IterateAlliedPlayers'
...ce\AddOns\Bagnon\common\components\tooltipCounts.lua:127: in function `HookTooltips'
Interface\AddOns\Bagnon\main.lua:24: in function <Interface\AddOns\Bagnon\main.lua:20>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...s\AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:558: in function `EnableAddon'
...s\AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:651: in function <...s\AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: ?
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:391: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:482: in function `TimeManager_LoadUI'
Interface\FrameXML\UIParent.lua:993: in function <Interface\FrameXML\UIParent.lua:891>

Locals: <none>

**Comment by Jaliborc** [comment]
Duplicate
