### ISSUE TITLE
Bagnon Inventory data collection doesn't work in all my realms!

### ISSUE THREAD

**Issue by Justbsing** [tullamods/Bagnon#479]
Hello, I have used bagnon for a while now and after the latest Wow patch bagnon will not show the inventory for my main realm characters. It still groups the bags but i can not see the money and like items on my other characters on Coilfang but if i switch to Dark iron that is a linked realm it works perfectly. It also works fine on Anvilmar as well. I tried uninstalling and reinstalling it and going into every characters bags and banks but it still will not work on Coilfang.

**Comment by Jaliborc** [comment]
Fixed
