### ISSUE TITLE
Blocked by Blizzard UI, other issues <Bagnon>

### ISSUE THREAD

**Issue by zoero** [tullamods/Bagnon#482]
Hi, ever since the latest patch I have been having the following issues:
1. "bagnon has been blocked from an action only available to the blizzard ui"
   Options to: Disable / Ignore.
   -Normally a relog disables this popup for a while
   -Only seen it happen while trying to use hearthstones, other people might have it pop up with other items
2. Bagbrother section of bagnon not working.
   -It will not show what items are on other characters while mousing over an item
   -Cannot see bank/other characters bags from bagnon ui

**Comment by vrelk** [comment]
I just ran into this issue today when trying to use a drained blood crystal (http://www.wowhead.com/item=122460/drained-blood-crystal). I got the popup every time I tried to use the item, and finally had to click disable just to use the item.

V. 7.0.4

**Comment by Jaliborc** [comment]
Duplicate
