### ISSUE TITLE
toc file entries

### ISSUE THREAD

**Issue by ceylina** [tullamods/Bagnon#487]
So I noticed this in my FrameXML.log

> 8/19 12:29:06.408  Loading add-on BagBrother
> 
> 8/19 12:29:06.408  *\* Loading table of contents Interface\AddOns\BagBrother\BagBrother.toc
> 8/19 12:29:06.408  Error loading Interface\AddOns\BagBrother\Tests.lua
> 8/19 12:29:06.408  Loading add-on Bagnon
> 8/19 12:29:06.408  *\* Loading table of contents Interface\AddOns\Bagnon\Bagnon.toc
> 8/19 12:29:06.408  ++ Loading file Interface\AddOns\Bagnon\libs\libs.xml
> 8/19 12:29:06.408  ++ Loading file Interface\AddOns\Bagnon\libs\LibItemCache-1.1\LibItemCache-1.1.xml
> 8/19 12:29:06.408  Error loading Interface\AddOns\Bagnon\libs\LibItemCache-1.1\Tests.lua
> 8/19 12:29:06.408  Error loading Interface\AddOns\Bagnon\libs\LibItemCache-1.1\Caches\BagBrotherTests.lua

Seems you have some references in various toc and xml files to files that do not exist in the addon folders.

**Comment by Jaliborc** [comment]
Known and intentional
