### ISSUE TITLE
Feature Request - Currency Tracking

### ISSUE THREAD

**Issue by meganleighwoulffe** [tullamods/Bagnon#494]
It seems Blizzard has added a way to track a selected currency (like cooking tokens, valor, Order Resources, etc) in the default Blizzard bag frames. Is there a way you could add this into Bagnon as well?
![currency tracking](https://cloud.githubusercontent.com/assets/22102446/18393744/e60b1a54-7673-11e6-9080-c2b919a2d0f4.png)

**Comment by Jaliborc** [comment]
Use a libdatabrokerplugin
