### ISSUE TITLE
Bug Vaultkeeper Sarniv <Void Storage>

### ISSUE THREAD

**Issue by serrufs** [tullamods/Bagnon#500]
It does not show tooltip objects in the repository of the abyss (Vaultkeeper Sarniv <Void Storage>). Quite a long time - with the Legion exit.

http://jpegshare.net/fe/73/fe73aef995ab8255a96ecb0d33110d8c.jpg.html

**Comment by Xruptor** [comment]
This seems to be a long time issue.  It also affects BagSync from displaying Tooltip information.  Something is going on when Bagnon VoidStorage displays the items in the grid.  For whatever reason the tooltips just never get displayed.

Previous tickets that are closed are:

https://github.com/tullamods/Bagnon/issues/425

and

https://github.com/tullamods/Bagnon/issues/485

**Comment by serrufs** [comment]
*Fixed issue displaying Void Storage tooltips.*
Thanks it worked
