### ISSUE TITLE
After 7.1 Beta Update, addon doesnt work. (Wont Open) 

### ISSUE THREAD

**Issue by RacerDemon** [tullamods/Bagnon#501]
2x Bagnon\common\core\settings-Settings.lua:113: attempt to perform arithmetic on a nil value
Bagnon\common\core\settings-Settings.lua:113: in function `UpdateSettings'
Bagnon\common\core\settings-Settings.lua:102: in function `StartupSettings'
Bagnon\main.lua:21: in function <Bagnon\main.lua:20>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
Ace3\AceAddon-3.0\AceAddon-3.0-12.lua:558: in function `EnableAddon'
Ace3\AceAddon-3.0\AceAddon-3.0-12.lua:651: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:407: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:430: in function `CombatLog_LoadUI'
FrameXML\UIParent.lua:1012: in function <FrameXML\UIParent.lua:907>

Locals:
nil

**Comment by ceylina** [comment]
Can confirm. Remarking out version checks allows the addon to work.

**Comment by RacerDemon** [comment]
what does "remarking mean?"

**Comment by ceylina** [comment]
aka comment out the offending lines of code to ignore version checks. IF you are not comfortable with Lua code then just stick with 7.0.4 until this gets fixed.

**Comment by ceylina** [comment]
the issue lies in the 7.1.0b designation. As the release number has an alpha character (b) in it and when converted to a number it is returned as nil (0b).

So either they need to use only number designations for versions or parse out the characters that are not numbers before splitting.

**Comment by ceylina** [comment]
One options to catch this is to add just above line 113 this

release = release:gsub('%a','')

This will strip any and all non numbers (alphabet) from the release stripped part of the version number. Unless they decide to add non alphanumeric numbers, this should handle beta designations in the future.

**Comment by fizzymynizzy** [comment]
Same problem here. I didn't get any error message tho. Just 100% not working at all.  I am using 7.1.0 (beta).

**Comment by phant** [comment]
Same error
`
Date: 2016-11-07 18:37:59
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Bagnon\common\core\settings.lua line 113:
   attempt to perform arithmetic on a nil value
Debug:
   Bagnon\common\core\settings.lua:113: UpdateSettings()
   Bagnon\common\core\settings.lua:102: StartupSettings()
   Bagnon\main.lua:21:
      Bagnon\main.lua:20
   (tail call): ?
   [C]: ?
   [string "safecall Dispatcher[1]"]:9:
      [string "safecall Dispatcher[1]"]:5
   (tail call): ?
   ...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:558: EnableAddon()
   ...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:651:
      ...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:636
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:407: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:498: TimeManager_LoadUI()
   ..\FrameXML\UIParent.lua:1010:
      ..\FrameXML\UIParent.lua:907
Locals:
None

`

**Comment by Jaliborc** [comment]
Yeah, I noticed this bug out quickly as well. Fixed the problem in the build pipeline.
