### ISSUE TITLE
Bagnon Guild bank

### ISSUE THREAD

**Issue by Askania** [tullamods/Bagnon#509]
I dont have any error codes or anything but guildbank possibly needs an update, I usually get interface addon bugs from Pet tracker, but this time it is from Bagnon guildbank, in order for my interface actions to work correctly blizz popped up a box advising to disable this part of the bagnon addon, not the whole thing, so it's just a problem with the guild bank feature

**Comment by jdtemple** [comment]
I just turned the guild bank piece of Bagnon back on after today's update, and the guild bank appears to be functioning correctly.
