### ISSUE TITLE
bagnon issue with closing bags with ESC

### ISSUE THREAD

**Issue by wannabeeme** [tullamods/Bagnon#513]
when im trying to lock my bags by pressing ESC i get this error:
pointing to AceConfigDialog-3. Is there a tweak in ACE itself ? if so please fix it and rename it.
73x Bagnon_AccountSearch\Bagnon_AccountSearch-r32.lua:187: attempt to index field 'FrameSettings' (a nil value)
Bagnon_AccountSearch\Bagnon_AccountSearch-r32.lua:187: in function `GetBagnonVariableLinks'
Bagnon_AccountSearch\Bagnon_AccountSearch-r32.lua:207: in function `UpdateVisibility'
Bagnon_AccountSearch\Bagnon_AccountSearch-r32.lua:60: in function `OnHide'
Bagnon\components\inventory.lua:17: in function <Bagnon\components\inventory.lua:16>
[C]: in function `Hide'
FrameXML\UIParent.lua:3025: in function <FrameXML\UIParent.lua:3020>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-1061.lua:1911: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1910>
[C]: in function `securecall'
FrameXML\UIParent.lua:3063: in function `CloseWindows'
FrameXML\UIParent.lua:3091: in function <FrameXML\UIParent.lua:3081>
[C]: in function `securecall'
FrameXML\UIParent.lua:3702: in function `ToggleGameMenu'
[string "TOGGLEGAMEMENU"]:1: in function <[string "TOGGLEGAMEMENU"]:1>

Locals:
self = BagnonAccountSearchFrame {
 UpdateVisibility = <function> defined @Bagnon_AccountSearch\Bagnon_AccountSearch.lua:206
 SetFrameLayer = <function> defined @Bagnon_AccountSearch\Bagnon_AccountSearch.lua:164
 GuildBankToggle = <function> defined @Bagnon_AccountSearch\Bagnon_AccountSearch.lua:100
 BagSearch_OnUpdate = <function> defined @Bagnon_AccountSearch\Bagnon_AccountSearch.lua:146
 minFrameSearchStringLength = 2
 ShowSearch = <function> defined @Bagnon_AccountSearch\Bagnon_AccountSearch.lua:684
 GetBagnonVariableLinks = <function> defined @Bagnon_AccountSearch\Bagnon_AccountSearch.lua:184
 New = <function> defined @Bagnon_AccountSearch\Bagnon_AccountSearch.lua:498
 AccountSearch_Toggle = <function> defined @Bagnon_AccountSearch\Bagnon_AccountSearch.lua:120
 CreateItemSlot = <function> defined @Bagnon_AccountSearch\Bagnon_AccountSearch.lua:616
 IsBankSlot = <function> defined @Bagnon_AccountSearch\Bagnon_AccountSearch.lua:156
 items = <table> {
 }
 0 = <userdata>
 AttachToggle = <function> defined @Bagnon_AccountSearch\Bagnon_AccountSearch.lua:112
 Print = <function> defined @Bagnon_AccountSearch\Bagnon_AccountSearch.lua:699
 UpdateItems = <function> defined @Bagnon_AccountSearch\Bagnon_AccountSearch.lua:302
 AddItemName = <function> defined @Bagnon_AccountSearch\Bagnon_AccountSearch.lua:257
 Resize = <function> defined @Bagnon_AccountSearch\Bagnon_AccountSearch.lua:243
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'FrameSettings' (a nil value)"

**Comment by Tuller** [comment]
Different addon (Bagnon_AccountSearch)
