### ISSUE TITLE
Bagnon_Forever\db.lua:46: bad argument #2 to 'format' (string expected, got nil)

### ISSUE THREAD

**Issue by xEvilgrin** [tullamods/Bagnon#523]
150138x Bagnon_Forever\db.lua:46: bad argument #2 to 'format' (string expected, got nil)
[C]: in function `format'
Bagnon_Forever\db.lua:46: in function <Bagnon_Forever\db.lua:40>
Bagnon_Forever\db.lua:315: in function `GetItemCount'
Bagnon_Tooltips\tooltips.lua:77: in function <Bagnon_Tooltips\tooltips.lua:70>
Bagnon_Tooltips\tooltips.lua:121: in function <Bagnon_Tooltips\tooltips.lua:118>
Bagnon_Tooltips\tooltips.lua:112: in function <Bagnon_Tooltips\tooltips.lua:109>
[C]: in function `OnTooltipSetItem'
Enchantrix\EnxMain.lua:219: in function <Enchantrix\EnxMain.lua:215>
[C]: ?
[C]: ?
[C]: ?
[C]: ?
...
[C]: ?
Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:408: in function <Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:402>
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: in function `SetAuctionItem'
...aceBlizzard_AuctionUI\Blizzard_AuctionUI.lua:1855: in function `AuctionFrameItem_OnEnter'
[string "*:OnEnter"]:2: in function <[string "*:OnEnter"]:1>

Locals:
(*temporary) = "item:%s:%s:%s:%s:%s:%s:%s:%s"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "string expected, got nil"

**Comment by Jaliborc** [comment]
Bagnon Forever has been deprecated centuries ago
