### ISSUE TITLE
Error when opening Guild Bank.

### ISSUE THREAD

**Issue by SargonStarblade** [tullamods/Bagnon#528]
I get this error message when trying to open my guild bank. It slows my computer and then crashes World of Warcraft.

Date: 2017-04-10 05:31:42
ID: 2
Error occured in: Global
Count: 1
Message: ...ace\AddOns\Bagnon_GuildBank\components\itemFrame.lua line 12:
   Usage: RegisterMessage("eventname", "methodname"): 'methodname' - method 'OnShow' not found on self.
Debug:
   [C]: ?
   [C]: ?
   ...Tom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:140: RegisterMessage()
   ...ace\AddOns\Bagnon_GuildBank\components\itemFrame.lua:12: RegisterEvents()
   ...s\Bagnon\external\Wildpants\components\itemFrame.lua:30: Update()
   ...s\Bagnon\external\Wildpants\components\itemFrame.lua:22: New()
   Bagnon\components\frame.lua:323: CreateItemFrame()
   Bagnon\components\frame.lua:317: PlaceItemFrame()
   Bagnon\components\frame.lua:83: Layout()
   Bagnon\components\frame.lua:58: Update()
   Bagnon\components\frame.lua:49: RegisterMessages()
   ...s\Bagnon\external\Wildpants\components\frameBase.lua:18:
      ...s\Bagnon\external\Wildpants\components\frameBase.lua:16
   [C]: Show()
   ..\FrameXML\UIParent.lua:2907: ShowUIPanel()
   ...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:54: ShowFrame()
   Bagnon_GuildBank\main.lua:14: OnOpen()
   Bagnon\main.lua:26: GuildBankFrame_LoadUI()
   ..\FrameXML\UIParent.lua:1585:
      ..\FrameXML\UIParent.lua:953
Locals:

AddOns:
  Swatter, v7.4.5714 (TasmanianThylacine)
  WowheadLooter, v70203
  NPCScanOverlay, v7.1.0.1
  AckisRecipeList, v7.2.0.2
  AckisRecipeListQuickScan, v7.1.0.1
  ACP, v3.4.30 
  Altoholic, vr178
  Atlas, v1.40.04
  AtlasArena, v1.06.05
  AtlasBattlegrounds, v1.39.00
  AtlasBurningCrusade, v1.39.00
  AtlasCataclysm, v1.39.00
  AtlasClassicWoW, v1.39.00
  AtlasClassOrderHalls, v1.39.02
  AtlasDungeonLocs, v1.39.00
  AtlasLegion, v1.40.03
  AtlasMistsofPandaria, v1.39.00
  AtlasOutdoorRaids, v1.39.01
  AtlasScenarios, v1.39.00
  AtlasTransportation, v1.40.00
  AtlasWarlordsofDraenor, v1.39.00
  AtlasWorldEvents, v3.19
  AtlasWrathoftheLichKing, v1.39.00
  AtlasLoot, vv8.03.00
  AtlasLootBurningCrusade, vv8.03.00
  AtlasLootCataclysm, vv8.03.00
  AtlasLootClassic, vv8.03.00
  AtlasLootLegion, vv8.03.00
  AtlasLootMistsofPandaria, vv8.03.00
  AtlasLootWarlordsofDraenor, vv8.03.00
  AtlasLootWrathoftheLichKing, vv8.03.00
  AucAdvanced, v7.4.5714 (TasmanianThylacine)
  AucFilterBasic, v7.4.5714 (TasmanianThylacine)
  AucFilterOutlier, v7.4.5714.5459(7.4/embedded)
  AucMatchUndercut, v7.4.5714.5585(7.4/embedded)
  AucStatHistogram, v7.4.5714 (TasmanianThylacine)
  AucStatiLevel, v7.4.5714 (TasmanianThylacine)
  AucStatPurchased, v7.4.5714 (TasmanianThylacine)
  AucStatSales, v7.4.5714.5598(7.4/embedded)
  AucStatSimple, v7.4.5714 (TasmanianThylacine)
  AucStatStdDev, v7.4.5714 (TasmanianThylacine)
  AucStatWOWEcon, v7.4.5714.5613(7.4/embedded)
  AucUtilAHWindowControl, v7.4.5714.5575(7.4/embedded)
  AucUtilAppraiser, v7.4.5714.5704(7.4/embedded)
  AucUtilAskPrice, v7.4.5714.5599(7.4/embedded)
  AucUtilAutoMagic, v7.4.5714.5686(7.4/embedded)
  AucUtilCompactUI, v7.4.5714.5694(7.4/embedded)
  AucUtilEasyBuyout, v7.4.5714.5576(7.4/embedded)
  AucUtilFixAH, v7.4.5714 (TasmanianThylacine)
  AucUtilItemSuggest, v7.4.5714.5651(7.4/embedded)
  AucUtilPriceLevel, v7.4.5714.5633(7.4/embedded)
  AucUtilScanButton, v7.4.5714.5631(7.4/embedded)
  AucUtilScanFinish, v7.4.5714.5588(7.4/embedded)
  AucUtilScanProgress, v7.4.5714.4979(7.4/embedded)
  AucUtilScanStart, v7.4.5714.5347(7.4/embedded)
  AucUtilSearchUI, v7.4.5714.5710(7.4/embedded)
  AucUtilSimpleAuction, v7.4.5714.5705(7.4/embedded)
  AucUtilVendMarkup, v7.4.5714.4828(7.4/embedded)
  AutoRepair, v
  Babylonian, v5.1.DEV.332(/embedded)
  BagBrother, v
  Bagnon, v7.2.0
  BagnonGuildBank, v7.2.0
  BattlePetBreedID, vr143
  BeanCounter, v7.4.5714 (TasmanianThylacine)
  BuyEmAll, v3.3.5
  CanIMogIt, v7.2.0.01
  ClassicQuestLog, v1.2.10
  Configator, v5.1.DEV.406(/embedded)
  CrossRealmAssist, v0.81 beta
  DailyGlobalCheck, v
  DailyGlobalCheckInstanceLockouts, v
  DailyGlobalCheckLegionWorldQuests, v
  DailyGlobalCheckPetTamers, v
  DailyGlobalCheckProfessions, v
  DailyGlobalCheckWorldBosses, v
  DailyTamerCheck, v
  DataStore, vr62
  DataStoreAchievements, vr45
  DataStoreAgenda, vr25
  DataStoreAuctions, vr47
  DataStoreCharacters, vr38
  DataStoreContainers, vr55
  DataStoreCrafts, vr76
  DataStoreCurrencies, vr34
  DataStoreGarrisons, vr20
  DataStoreInventory, vr48
  DataStoreMails, vr48
  DataStorePets, vr41
  DataStoreQuests, vr40
  DataStoreReputations, vr39
  DataStoreSpells, vr29
  DataStoreStats, vr28
  DataStoreTalents, vr58
  DBMCore, v@project-version@
  DBMDefaultSkin, v
  DBMLDB, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  Enchantrix, v7.4.5714 (TasmanianThylacine)
  EnchantrixBarker, v7.4.5714 (TasmanianThylacine)
  FishingBuddy, v1.7.13
  GarrisonCommanderBroker, v2.18.2 1.1.0
  GFWDiggerAid, v7.0
  GFWFactionFriend, v7.2
  GFWHoverTips, v7.0
  GFWXPVisualizer, v7.0.1
  GFWZippyLighter, v7.0
  HandyNotes, vv1.4.13
  HandyNotesDraenorTreasures, v1.20a
  HandyNotesFieldPhotographer, v7.1.0.0
  HandyNotesHallowsEnd, vv1.2.5
  HandyNotesLegionRaresTreasures, v1.01b
  HandyNotesLorewalkers, v1
  HandyNotesTimelessIsleChests, v1.17
  HandyNotesTimelessTreasures, v1.0.7
  HandyNotesTreasureHunter, v1
  HealBot, v7.2.0.0
  HealBotTips, v7.2.0.0
  Informant, v7.4.5714 (TasmanianThylacine)
  LibExtraTip, v5.12.DEV.423(/embedded)
  LongMacros, vv1.0.12
  MasterPlanA, vA
  mOnArsWardrobeHelper, v1.17
  NPCScan, v7.1.0.5
  Outfitter, v5.18.7
  PetBattleTeams, v3.3.7
  PetJournalEnhanced, v2.9.26
  PetTracker, v7.1.4
  PetTrackerBreeds, v7.1.4
  PetTrackerConfig, v7.1.4
  PetTrackerSwitcher, v7.1.4
  PetTrackerUpgrades, v7.1.4
  Rarity, v1.0
  RarityOptions, v
  Rematch, v4.6.5
  SellOMatic2, va071
  SellOMatic2Destroy, va071
  SellOMatic2Item, va071
  SellOMatic2List, va071
  ServerHop, v7.2.1
  SlideBar, v7.4.5714 (TasmanianThylacine)
  Stubby, v7.4.5714 (TasmanianThylacine)
  TipHelper, v5.12.DEV.405(/embedded)
  Titan, v5.10.8.70200
  TitanBag, v5.10.8.70200
  TitanClock, v5.10.8.70200
  TitanCurrency, v7.1
  TitanGold, v5.10.8.70200
  TitanLocation, v5.10.8.70200
  TitanLootType, v5.10.8.70200
  TitanPerformance, v5.10.8.70200
  TitanRepair, v5.10.8.70200
  TitanVolume, v5.10.8.70200
  TitanXP, v5.10.8.70200
  TomTom, vv70200-1.0.0
  TradeSkillMaster, vv3.6.28
  TradeSkillMasterDestroying, vv3.1.5
  TradeSkillMasterMailing, vv3.0.13
  WorldQuestGroupFinder, v0.22.1
  WorldQuestsList, v31
  BlizRuntimeLib_enUS v7.2.0.70200 <none>
  (ck=1443)

**Comment by Jaliborc** [comment]
GuildBank still not ready for 7.2
