### ISSUE TITLE
Bagnon does not open or close on first key press or bag click when using Game Menu to close bags

### ISSUE THREAD

**Issue by jsutan** [tullamods/Bagnon#529]
Bagnon does not properly open or close when pressing the key bind for Open Bags or when clicking the bag menu on the bag bar after using the "Game Menu" key bind or pressing the "Game Menu" button on the micro bar.

Reproduction Steps:

- Open bags normally (keybind, or bag icon)
- Close bags normally (keybind, or bag icon)
[notice that bags open/close with one press/one click]
- Open bags normally (keybind, or bag icon)
- Close bags with Game Menu keybind (default 'Esc') or Game Menu icon on the Micro bar
- Open bags normally (keybind, or bag icon)
[Note that it may take additional key presses or clicks to open bag]
- Close bags normally (keybind, or bag icon)
[Note that it may take additional key presses or clicks to close bag]

It seems that for each time you hit Game Menu to close something (bags, or otherwise) or hit the Game Menu icon on the micro bar, it takes an additional click or two to open or close bags.

Examples:

- Open bags, close with 'Esc', open bags [bugs], open bags [works] (Original reproduction step above)
- Open bags, close with 'Esc', press 'Esc' to open Game Menu, press 'Esc' again to close Game Menu, open bags [works], close bags [bugs], close bags [works]
[repeat ad infinitum, pressing 'Esc' multiple times before trying to reopen bags and note that it takes an increasingly longer amount of key presses or button clicks to properly open or close bags]

May be related to this previous issue: 

https://github.com/tullamods/Bagnon/issues/513

**Comment by vladimirgluten** [comment]
I am having the same issue.  I've noticed it when I'm at a mailbox and leave, the bags don't close automatically and I have to hit the B key around 5 or 6 times before the bag frame closes.

**Comment by adavis9592** [comment]
I have this as well, and have since 7.2 release. I haven't noticed if it's tied to specific methods of closing bags like the other users above, but I do have a [video reference.](https://gfycat.com/SoggyCoarseErin)

I've noticed whenever it happens, all bags except the backpack are highlighted as if they are open, while backpack remains closed.
