### ISSUE TITLE
7.2.0 - Separate Reagent Bank Option Not Working

### ISSUE THREAD

**Issue by gokieks** [tullamods/Bagnon#531]
In the 7.2.0 beta release, clicking the Reagent Bank slot icon causes it to be added to the bottom of the main bank window, rather than changing to displaying just the Reagent Bank.  Toggling the "Separate Reagent Bank" checkbox in Frame Settings does not appear to make any difference.

**Comment by strangeclouds** [comment]
I also am having an issue with this. Loved seeing reagents on a different page especially on toons that have lots of items in the main bank.

**Comment by Jaliborc** [comment]
@gokieks do you mean the sort button?

**Comment by gokieks** [comment]
No - in the bank frame, it shows all the bags in the bank (and empty slots if there are any), with the last one being for the reagent bank.  The way that it's supposed to work is that clicking any of the bank bags will toggle whether they are displayed within the bank frame, whereas clicking the last bag (reagent bank) will either toggle it as part of the main bank frame, or switch to a bank frame showing ONLY the reagent bank, depending on whether the "Separate Reagent Bank" option is enabled.

In the 7.2.0 (and I assume 7.2.1 - I switched back to 7.1.1 to have it be usable again) beta release, clicking the reagent bank bag will only toggle it, regardless of what the setting is, so there's no easy way to view just the reagent bank (you could toggle every OTHER bag, I suppose, but that's obviously not an actual solution).  As it's a quite large bag, adding it to the bottom of the main bank bags display causes it to become very large, possibly taller than the entire screen, unless you use a large number of columns, which I do not want.

**Comment by gokieks** [comment]
Tested 7.2.2, still having the same problem, so reverting back to 7.1.1 again.

**Comment by Jaliborc** [comment]
Fixed
