### ISSUE TITLE
Bank interface does not always close when walking away.

### ISSUE THREAD

**Issue by SargonStarblade** [tullamods/Bagnon#535]
Ok I'm lazy and normally close the bank by walking away or clicking on the guild bank. It does that once or twice now but then stops closing, requiring you to manually close the interface. You still see your bank, you cannot move items into or out of the bank with out right-clicking on the person again, the interface window prevents you from clicking on things behind it. There is no error log.

I also re-enabled the Guild Bank after it was updated and it is doing the same thing, as well as Void Storage, which I had not tested prior to placing this issue.

**Comment by pfeifenheini** [comment]
I noticed the same bug.

**Comment by Jaliborc** [comment]
Hopefully got this  fixed today
