### ISSUE TITLE
Option to not include stuff in guild bank in tooltip count

### ISSUE THREAD

**Issue by ssateneth** [tullamods/Bagnon#537]
I'd like an option to not include guild bank contents when calculating item count in the hover-over tooltip of an item please.

**Comment by fiddybux** [comment]
I have massive freezing with guild bank and sylevel bagnon, so the only solution for me is to disable Bagnon Guild in add-on character screen. This takes guild bank back to default stock blizzard.

**Comment by ssateneth** [comment]
That is a completely different issue from the one I'm seeing. Please open a seperate issue for that.

**Comment by Jaliborc** [comment]
Duplicate
