### ISSUE TITLE
item search not clearing when editbox loses focus

### ISSUE THREAD

**Issue by ssateneth** [tullamods/Bagnon#538]
Seems like the highlight/greying of items when an item search box is active (clicking <name>'s Inventory on a bagnon frame) doesn't go away when you escape out of the search box, which was the old behavior and was prefered. Now I have to manually delete from the editbox whatever I was searching for so I can actually navigate my bags afterwards

Please change the behavior to automatically clear the search editbox when the editbox loses focus (Previous bagnon behavior). Thank you.

**Comment by Jaliborc** [comment]
Fixed
