### ISSUE TITLE
Lua error when opening Void Storage

### ISSUE THREAD

**Issue by sydbarrett74** [tullamods/Bagnon#539]
Message: Interface\AddOns\Bagnon\common\components\item.lua:479: Usage: IsContainerItemAnUpgrade(index, slot)
Time: 04/27/17 03:28:07
Count: 160
Stack: [C]: in function `IsContainerItemAnUpgrade'
Interface\AddOns\Bagnon\common\components\item.lua:479: in function `IsUpgrade'
Interface\AddOns\Bagnon\common\components\item.lua:305: in function `UpdateUpgradeIcon'
Interface\AddOns\Bagnon\common\components\item.lua:248: in function `?'
Interface\AddOns\Bagnon\common\components\item.lua:509: in function <Interface\AddOns\Bagnon\common\components\item.lua:507>

Locals: (*temporary) = "vault"
(*temporary) = 5

**Comment by sydbarrett74** [comment]
May I ask why this was closed with no comment?

**Comment by Jaliborc** [comment]
The error tells me this is a void storage item. The code in question completely changed meanwhile, and this issue should not happen again.

**Comment by Jaliborc** [comment]
Basically, its fixed
