### ISSUE TITLE
Dark overlay since 7.2

### ISSUE THREAD

**Issue by vekspec** [tullamods/Bagnon#544]
I reported an issue since the 7.2 version of a dark overlay when opening bags on Curse.com. It looks like it hasn't been resolved yet. When opening the bag,, the whole overlay is dark and is hard to see your items. Reverting back to the 7.1.1 version resolves this issue. Please see attachement
![wowscrnshot_050517_220053](https://cloud.githubusercontent.com/assets/3671376/25769068/d2ba6384-31de-11e7-8826-b2a83bf62208.jpg)

**Comment by basten1899** [comment]
PLS also update "ButtonFacade "  ,now can not work on 7.2

**Comment by Jaliborc** [comment]
Duplicate
