### ISSUE TITLE
Bagnon_Facade no longer works since ItemFrame:Layout no longer calls ItemSlot:SetTarget (Fix included).

### ISSUE THREAD

**Issue by christinaa** [tullamods/Bagnon#548]
Yeah title is self explanatory. Dirty fix is hooking `ClearAllPoints` instead, just search for `SetTarget` in `Bagnon_Facade.lua` and replace with `ClearAllPoints`. Didn't seem to cause any taint issues with using items in combat so it seems to be fine as a fix. Don't think it causes any regressions either since it's only called from `ItemSlot:Layout` as far as I could tell.

**Comment by Jaliborc** [comment]
Yeah, I havent updated the plugins yet. Want to make sure Bagnon itself is running tight before.
Thank you for the feedback!

**Comment by Jaliborc** [comment]
Fixed
