### ISSUE TITLE
Bagnon facade please don't have it remove bagnon when uninstalling

### ISSUE THREAD

**Issue by ceylina** [tullamods/Bagnon#551]
Please don't have bagnon_facade remove bagnon when uninstalling it via curse

**Comment by Jaliborc** [comment]
I have no control over that

**Comment by ceylina** [comment]
You do actually. Just remove this

## Dependencies: Bagnon, Masque

It really doesn't need to be there because the mod will simply not work without those two so declaring this dependency doesn't really benefit anything and in fact causes the curse=twitch client to remove bagnon when uninstalling.
