### ISSUE TITLE
7.2.3 - Search completely broken

### ISSUE THREAD

**Issue by voidzone** [tullamods/Bagnon#555]
Whatever you did to fix #543 completely broke search.

**Comment by cexikitin** [comment]
Same here, downgrading to 7.2.2 fixed the issue but still have the query in use after hitting esc

**Comment by frank4g63** [comment]
it still works, you just cant double click on the top (thats what appears to be broken).  The 'click to search' telescope/etc icon works normally.

**Comment by cexikitin** [comment]
Theres two issues:

Search does not automatically start
Search does not clear after pressing enter

**Comment by frank4g63** [comment]
Same

**Comment by SirThrocken** [comment]
Same issue here search is completely shot now, no highlights and won't close unless I close the bank or my bag directly.

**Comment by cexikitin** [comment]
Pressing enter after doing a search still does not clear it, but pressing esc does. This doesn't match the previous behavior.

**Comment by cexikitin** [comment]
Working great now with 7.2.5, thanks!
