### ISSUE TITLE
option is now missing...why?

### ISSUE THREAD

**Issue by bahahamut** [tullamods/Bagnon#558]
the option for 'character specific' settings has been removed - we need this option back because different characters randomly have bags sorted backwards and vice versa. haven't been willing to use this addon since 7.1.1

**Comment by Raxol** [comment]
That has nothing to do with Bagnon. It's a wow specific option. You can access the option with addons like [AdvancedInterfaceOptions](https://mods.curse.com/addons/wow/advancedinterfaceoptions) or you can use this command: `/run SetSortBagsRightToLeft(true)`

**Comment by bahahamut** [comment]
akshully you guys just moved it to a different menu
