### ISSUE TITLE
bagnon not working  with Masque

### ISSUE THREAD

**Issue by Restodruid** [tullamods/Bagnon#560]
Masque was updated and now no longer works with bagnon. Masque  has the following to say in their notes  "API version increased to 70200.
Masque now overrides Border region's SetVertexColor method. Add-on authors who use custom Border coloring can disable this feature at the group level by setting the group's BorderSVC variable to true prior to adding buttons to the group. Alternatively, they can use the new method __MSQ_SetVertexColor." 
No sure if this is the issue but all my bag item borders are green

**Comment by StormFX** [comment]
It does work, but it overrides Bagnon's Border region color. In order to fix this, set the Masque group's `BorderSVC` variable to `true`.

**Comment by StormFX** [comment]
Actually, just ignore this issue for the moment. I should have put more thought into how it was implemented and as such, will be reverting these changes. Instead, add-ons using action buttons will have to explicitly identify themselves as such during group creation. I apologize for the lapse in judgement and temporary annoyance. :/

**Comment by StormFX** [comment]
This has been addressed in the latest version of Masque. Feel free to close this.
