### ISSUE TITLE
Bagnon and items in the guildbank

### ISSUE THREAD

**Issue by scidrov** [tullamods/Bagnon#561]
on all my toons (they are in the same guild) it shows me the same items multiple items so in the end it says that i have a total of XYZ when in reality there are only X in the guild bank
looks like this http://imgur.com/a/gMuyJ

**Comment by voidzone** [comment]
Yes, please give us the option to disable guild bank totals or make it calculate the total based off the guild name rather than for each character you have in the guild.

**Comment by Jaliborc** [comment]
Duplicate
