### ISSUE TITLE
Remote Guild bank display

### ISSUE THREAD

**Issue by LarryGatlin** [tullamods/Bagnon#563]
When you click on inventory bags, right click bag slots and select Guild Bank, is will only show 1 tab of data, if you select a different tab, still shows original.  when you close and then redo the steps, it will show the tab you had last selected, but if you select a different tab, it will not display that tab until you close and redo the steps

EDIT: 7.1.1 was the last update that worked correctly

**Comment by jdtemple** [comment]
I just turned the guild bank piece of Bagnon back on after today's update, and the guild bank appears to be functioning correctly.

**Comment by jdtemple** [comment]
I just turned the guild bank piece of Bagnon back on after today's update, and the guild bank appears to be functioning correctly.
