### ISSUE TITLE
bagnon 

### ISSUE THREAD

**Issue by partolo** [tullamods/Bagnon#575]
so today I logged world of warcraft and suddenly my bags inventory from my bank isn't working
after hours of trying I managed to narrow it down to:
when I have BOTH addons weakauras2 and bagnon activated my bank doesn't show
but when I have either one of them disabled and the other enabled it works and vise versa 
can you please help

**Comment by xethys** [comment]
Same as partolo i had NEVER had a problem with my addons and Bagnon before today (well, almost never) and today Bagnon is not letting me open my bank. I had troubleshooted through ALL my other addons and Bagnon is def the one that is the problem. PLEASE FIX ASAP! can't do without my bagnon!

**Comment by partolo** [comment]
ok so I find out something is that if you change in currse clinet some of the addons to release instead of alpha, It should work

**Comment by Torsin** [comment]
This was duplicated under #576 , my comment relates to a few other addons that updated their Ace3 libraries to the latest Alpha:

I can confirm that if I update the Ace3 libraries contained within Bagnon (Bagnon\external\Wildpants\libs) to the Alpha Ace3 libraries my Bank opens again without issue.

**Comment by Jaliborc** [comment]
Duplicate
