### ISSUE TITLE
Bank doesnt work

### ISSUE THREAD

**Issue by Snowydove** [tullamods/Bagnon#577]
I have no problem with the guild bank, but personal bank,  I have to disable bagnon to access it.

**Comment by cecea** [comment]
me and my boyfriend are having the same problem since last night. is this being worked on??

**Comment by CRENDONH23** [comment]
Hi. I am also having problems opening my bank.

I hope you fix this soon,  i love this addon

**Comment by woodgray** [comment]
Conflict with weakauras2

**Comment by LordGrizzard** [comment]
Hi I had the same problem. So I finally decided to install OneBag and OneBank (and I scould see they're sh*t compared to Bagnon). Suddenly i'm thinking "What If i use Bagnon for my bag, and OneBank for the bank i can't see".
I do that, then suddenly the bank from Bagnon appears (+ OneBank), I disable OneBank, ,and Bagnon is back to normal with its bank.

**Comment by veilsong** [comment]
What a pain in the ass this has been for me the last couple of days. I am not "computer savvy" at all. I thought something was wrong with my game. I filled out two tickets with Blizzard. They finally got back to me after 24 hours to tell me something was wrong with one of my add-ons. Golly I must have over 30 add ons. I tried deleting a few disabling a few. Then I came to Baggon. This was the issue. This is the issue. I cannot get into my personal bank while using this add on. I took LordGrizzard's advice I'm stuck using Onebank and Onebag. Terrible! please fix this so i can have my bag on back!

**Comment by jiataiat** [comment]
I am also having this issue. I got buggrabber and bugsack, but not seeing any errors... how can you tell it is conflicting with weak auras 2?

**Comment by ttdax** [comment]
I confirmed this is a conflict with WeakAuras2. This app was updated two days ago. I disabled WeakAuras2 and Bagnon works again. Please fix this asap.

**Comment by veilsong** [comment]
WeakAuras2? What is that?  Is that an Add-on? Cause I don't believe I have that add on through Curse.

**Comment by ttdax** [comment]
https://mods.curse.com/addons/wow/weakauras-2

**Comment by veilsong** [comment]
hey thanks for posting that link. I checked it out and I don't have WeakAuras 2 in my downloaded curse account. So I guess that means that this isn't the issue? with baggon?

**Comment by LordGrizzard** [comment]
Weird, cause I don't have WeakAuras nor ever heard of it.

**Comment by Lynxtips** [comment]
My personal bank stopped working right after the patch 15 Aug 17, guild bank is fine

**Comment by Torsin** [comment]
Again, it is not just WeakAura 2, it is not just Recount, any Addon that updates their Ace3 embedded libraries to the latest alpha versions of Ace3 will cause other addons that utilize the same libraries to potentially have issues.  In this case Bagnon stopped opening the bank and search is not working properly.  By updating the embedded libraries within Bagnon the issue goes away, I would bet that @Jaliborc @Tuller don't want to update their release Addon with an Alpha version of the embedded libraries.  It would be nice if they did an Alpha themselves, but it is easy enough to copy the affected embedded libraries in manually until they do a release of some sort.

**Comment by Snowydove** [comment]
As suggested, I added onebank3.   I can access my bank with that addon and still have bagnon for my inventory.  This will fix it for now.

**Comment by Snowydove** [comment]
Torsin,   sorry i just dont pay attention to trolling.  Take Care.

**Comment by Torsin** [comment]
Snowydove, no idea what you mean.  Was someone trolling?  Or do you mean I was trolling, because I was not.

**Comment by plutoniumshore** [comment]
@Torsin Is updating the libraries something a layperson (not savvy with programming) is able to do?

Much appreciate the debugging! Good work!

**Comment by Torsin** [comment]
@plutoniumshore Sure, the other thread had a couple good comments, such as:

"You go in your Recount or WeakAura directory, for example "World of Warcraft\Interface\AddOns\Recount\libs", you select the "AceEvent-3.0" directory and copy it ; next you go in the "World of Warcraft\Interface\AddOns\Bagnon\external\Wildpants\libs" directory and paste ; you accept to replace existing files and folders and it's done."

**Comment by Jaliborc** [comment]
Duplicate

**Comment by veilsong** [comment]
I want to thank everyone for there comments . My baggon is working! I don't  know how this happened but  thank you so much.
