### ISSUE TITLE
banks not working

### ISSUE THREAD

**Issue by Sab65** [tullamods/Bagnon#579]
can't open bank

**Comment by Torsin** [comment]
@Sab65 A couple other issues have been opened about this, #575, #576, #577 

One a decent comment about how to workaround the issue:
"You go in your Recount or WeakAura directory, for example "World of Warcraft\Interface\AddOns\Recount\libs", you select the "AceEvent-3.0" directory and copy it ; next you go in the "World of Warcraft\Interface\AddOns\Bagnon\external\Wildpants\libs" directory and paste ; you accept to replace existing files and folders and it's done."

**Comment by Jaliborc** [comment]
Duplicate
