### ISSUE TITLE
Bank Issue and Guild Bank Item Tracker

### ISSUE THREAD

**Issue by Polarthief** [tullamods/Bagnon#581]
Two issues I'd like to report, one major, one minor:

1. I cannot open the bank while Bagnon is activated. My friend also believes it has some kind of reaction with WeakAuras as well but this issue just randomly started happening.

2. As far as I know, there is no option to turn off Guild Bank tracking for items on your characters/alts, and when all of my characters are in the same guild, it's really annoying to see it appear on every single item that is also in the GBank. Please add an option somewhere to turn that functionality off (or just remove it because man is it less helpful than it is annoying).

**Comment by Sparky1105** [comment]
I am also having the same issue.  My personal bank wont open but guild bank will if i have Bagnon enabled.  Please help i dont like any other addons for bags out there!!

**Comment by jjstes15** [comment]
Also having this issue. I have Weakauras installed as well. My boyfriend is not having an issue and does not have Weakauras installed.

**Comment by Torsin** [comment]
A few other issues have been opened about number 1, #575, #576, #577, #579 

One a decent comment about how to workaround the issue:
"You go in your Recount or WeakAura directory, for example "World of Warcraft\Interface\AddOns\Recount\libs", you select the "AceEvent-3.0" directory and copy it ; next you go in the "World of Warcraft\Interface\AddOns\Bagnon\external\Wildpants\libs" directory and paste ; you accept to replace existing files and folders and it's done."

For number 2 this is covered in the issue enhancement:  #542

**Comment by Jaliborc** [comment]
Duplicate
@Torsin ty
