### ISSUE TITLE
Clicking between items

### ISSUE THREAD

**Issue by Polarthief** [tullamods/Bagnon#583]
This has been an issue for a few months now; you're able to click through your inventory if you click between the spacing of items. This is frustrating for a few reasons but the main one being if you use the default Right bars, you'll put items on those bars and swap them out for whatever you had there previously. It's incredibly aggravating!

**Comment by Rynslet** [comment]
Seems to be a similar issue to what I'm having, #574.
And yes, it is aggravating, and I'm hoping something can be done about it.

**Comment by Jaliborc** [comment]
Ok, thats easy to fix. Thank you for the feedback!
