### ISSUE TITLE
Tooltip Item Count

### ISSUE THREAD

**Issue by Nyssiera** [tullamods/Bagnon#584]
When enabling the tooptip item count, I am inundated with the guild bank item count. When disabling it, I don't have this problem, but I can no longer see shared items like food, herbs, etc. on my alts nor am I able to see how many of any given item I have in my personal bank. Maybe I'm missing a simple fix or step, but surely there exists a happy median where I don't have to chose between the two. 

http://i.imgur.com/zLnZWNo.jpg
http://i.imgur.com/kxqpZNX.jpg

BagBrother still works just fine, don't get me wrong -- I'd just like to be able to see my shared items across all of my inventories without being bombarded with guild bank info.

I apologize if this has been brought up and addressed or if I'm just simply missing something, but I appreciate any and all help offered.

Thanks!

**Comment by enderneko** [comment]
Interface\AddOns\Bagnon\external\Wildpants\features\tooltipCounts.lua

Edit line 24 to
```lua
for i = 1, select('#', ...)-1 do
```

I'm pretty sure this is what you want.

**Comment by Nyssiera** [comment]
That works and is exactly what I wanted. Thank you very much!

**Comment by darksikders** [comment]
bugg from bagnon , can't see my items from bank , like enchanting , gears, or reagents stuffs,i ussed to see them , but after a while i don't see them anymore
https://imgur.com/IN8hnoL
