### ISSUE TITLE
7.3 Sound Problem

### ISSUE THREAD

**Issue by yoshimo** [tullamods/Bagnon#585]
Looks like they changed something with the soundsystem:

`Date: 2017-08-26 19:19:33
ID: 8
Error occured in: Global
Count: 1
Message: ...s\Bagnon\external\Wildpants\components\frameBase.lua line 17:
   Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
Debug:
   [C]: PlaySound()
   ...s\Bagnon\external\Wildpants\components\frameBase.lua:17: OnShow()
   ...s\Bagnon\external\Wildpants\components\inventory.lua:12:
      ...s\Bagnon\external\Wildpants\components\inventory.lua:11
   [C]: Show()
   ..\FrameXML\UIParent.lua:2928: ShowUIPanel()
   ...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:54:
      ...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:50
   (tail call): ?
   (tail call): ?
   ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:133:
      ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:131
   [C]: ToggleBag()
   ..\FrameXML\MainMenuBarBagButtons.lua:21: BagSlotButton_OnClick()
   [string "*:OnClick"]:4:
      [string "*:OnClick"]:1
Locals:
(*temporary) = "igBackPackOpen"
`

**Comment by doutrnz** [comment]
And what exactly is the problem? Thank you for just posting a statement. Sarcasm intended.

**Comment by yoshimo** [comment]
the problem is that the addon seems to be not working. 
The only error i have is this.

**Comment by doutrnz** [comment]
Thank you for the clarification.

**Comment by Jaliborc** [comment]
That error is not the first one you had (ID 8 I see). You must scroll back to the first error, only the first is relevant (errors create further errors).

**Comment by Jaliborc** [comment]
Might not even be Bagnon related

**Comment by yoshimo** [comment]
If we disable everything but bagnon and swatter the message still shows.

**Comment by Jaliborc** [comment]
What is the first error?

**Comment by Stanzilla** [comment]
PlaySound no longer takes strings, only ids, so you have to change to them.

https://www.townlong-yak.com/framexml/ptr/SoundKitConstants.lua

**Comment by Torsin** [comment]
First and only error:

Message: ...s\Bagnon\external\Wildpants\components\frameBase.lua:17: Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
Time: 08/28/17 21:24:25
Count: 1
Stack: ...s\Bagnon\external\Wildpants\components\frameBase.lua:17: Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
[C]: ?
[C]: in function `PlaySound'
...s\Bagnon\external\Wildpants\components\frameBase.lua:17: in function `OnShow'
...s\Bagnon\external\Wildpants\components\inventory.lua:12: in function <...s\Bagnon\external\Wildpants\components\inventory.lua:11>
[C]: in function `Show'
Interface\FrameXML\UIParent.lua:2928: in function `ShowUIPanel'
...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:54: in function <...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:50>
(tail call): ?
...s\Bagnon\external\Wildpants\features\autoDisplay.lua:157: in function `ToggleAllBags'
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Locals:

**Comment by Torsin** [comment]
Looks like there are 14 instances of PlaySound across 9 files, a good chunk is in the library Sushi-3.0.

**Comment by Torsin** [comment]
As far as I can tell the 'BAGMENUBUTTONPRESS' (used at line 104 of the bag.lua sound no longer exists in the current sound kit, or if it does it is named something different so I used the Backpack Open sound.

I changed to the following and on the ptr it seems to work fine:

Bagnon\external\Wildpants\components\bag.lua
Line 84:
`			PlaySound(856) -- IG_MAINMENU_OPTION_CHECKBOX_ON`
Line 104:
`		PlaySound(862)	-- IG_BACKPACK_OPEN`
Line 252:
`	PlaySound(850)	-- IG_MAINMENU_OPEN`


Bagnon\external\Wildpants\components\frameBase.lua:
Lines 10 & 11:
`Frame.OpenSound = 862	-- IG_BACKPACK_OPEN`
`Frame.CloseSound = 863	-- IG_BACKPACK_CLOSE`

Bagnon_Config\common\libs\Sushi-3.0\Classes\ButtonBase.lua
Line 23:
`	Button.sound = 856 -- IG_MAINMENU_OPTION_CHECKBOX_ON`

Bagnon_Config\common\libs\Sushi-3.0\Classes\CheckButton.lua
Line 52-54:
`		PlaySound(856) -- IG_MAINMENU_OPTION_CHECKBOX_ON`
`	else`
`		PlaySound(857) -- IG_MAINMENU_OPTION_CHECKBOX_OFF`

Bagnon_Config\common\libs\Sushi-3.0\Classes\ColorPicker.lua
Line 85:
`	PlaySound(856) -- IG_MAINMENU_OPTION_CHECKBOX_ON`

Bagnon_Config\common\libs\Sushi-3.0\Classes\DropdownFrame.lua
Line 124:
`	PlaySound(856) -- IG_MAINMENU_OPTION_CHECKBOX_ON`

Bagnon_Config\common\libs\Sushi-3.0\Classes\TextureDropdown.lua
Line 156:
`	PlaySound(856) -- IG_MAINMENU_OPTION_CHECKBOX_ON`

Bagnon_GuildBank\components\frame.lua
Line 14&15
`Frame.CloseSound = 12189	-- GUILD_VAULT_CLOSE`
`Frame.OpenSound = 12188		-- GUILD_VAULT_OPEN`

Bagnon_GuildBank\components\moneyFrame.lua
Line 38:
`		PlaySound(852)	-- IG_MAINMENU_OPTION`
Line 48:
`			PlaySound(852)	-- IG_MAINMENU_OPTION`

Bagnon_VoidStorage\components\dialogs.lua
Line 18:
`		PlaySound(25711)	-- UI_VOID_STORAGE_UNLOCK`

Bagnon_VoidStorage\components\frame.lua
Line 15&16"
`Frame.OpenSound = 25716		-- UI_ETHEREAL_WINDOW_OPEN`
`Frame.CloseSound = 25717	-- UI_ETHEREAL_WINDOW_CLOSE`

**Comment by voidzone** [comment]
https://us.battle.net/forums/en/wow/topic/20758856637

**Comment by M081L** [comment]
Expanding on @Stanzilla :

**frameBase.lua line 17**

```
Frame.OpenSound = SOUNDKIT.IG_BACKPACK_OPEN
Frame.CloseSound = SOUNDKIT.IG_BACKPACK_CLOSE
```

The playsound function doesn't use strings anymore, so the soundkit file carries their number as a part of the structure. (883 and 884 i think).

Been a while since i've coded. Commented on Curse forums aswell, fixed for me.

**Comment by Torsin** [comment]
Yep, the soundkit. would be the better way (did the fast and easy #'s until @Jaliborc updates it)

**Comment by auddie2015** [comment]
So far, frameBase.lua was the only thing throwing an error for me. I looked up and used the numbers and it works. I will keep your list handy in case I throw more errors so I can grab them as they happen. Too lazy to dig through them all with all these demons to kill!

**Comment by Torsin** [comment]
I hear ya @auddie2015 , seems like most of the other ones surround the settings sounds and the void storage/guild bank.

**Comment by Kanegasi** [comment]
@Torsin
BAGMENUBUTTONPRESS exists. That SOUNDKIT table is nowhere near comprehensive, just a list of common UI sounds in the Blizzard code used by Blizzard for easy conversion. The sound ID is [117](http://www.wowhead.com/sound=117/bagmenubuttonpress). Every sound name PlaySound used to accept can be located in Wowhead's sound list.

**Comment by comp615** [comment]
@Torsin can you submit a PR with your full changes so that @Jaliborc can simply pull it in and release? Would help a lot of people :)

**Comment by theisencr** [comment]
@Torsin @comp615 I'm in the process of doing exactly that, unless Torsin is already working on it.

**Comment by Torsin** [comment]
I would have done a PR, but was pressed for time due to some RL appointments and work.  Looks like @theisencr is doing up some of them.

**Comment by theisencr** [comment]
With the "I am not a WoW addon developer" disclaimer... all of the pull requests have been generated based on @Torsin's comment.

**Comment by yinzara** [comment]
[BagnonPatched.zip](https://github.com/tullamods/Bagnon/files/1262133/BagnonPatched.zip)
Here is a patched version with the changes above applied to the most recent version of Bagnon.  Just unzip in WoWHome/Interface/addons

**Comment by kaleduncan** [comment]
Thank you, @yinzara. That worked perfectly.
I didn't do a code review, though, so I hope it's not logging my keystrokes or something. :)

**Comment by Armydr** [comment]
Also @yinzara  TYVM!!! I did check code, didnt' see any major issues, but not enough to make promises!

**Comment by dmoc9** [comment]
If no-one's doing the PR, I'll do it now

**Comment by dmoc9** [comment]
Thanks @theisencr.. I was about to offer to do it, but realised you're on top of it :)

**Comment by Knaledge** [comment]
@theisencr - looking good for the commons/externals. The next PR would be changes to the Bagnon-specific components themselves (i.e. patching Wildpants, patching Sushi-3.0, and then patching Bagnon itself). 

Once those PRs on Wildpants/Sushi get approved/merged, the packaged version of Bagnon (here) would be updated to include those new versions of Wildpants/Sushi - and then the changes to Bagnon itself committed and merged into that new "branch". That PR gets submitted, approved, merged, and then made public.

**Comment by Torsin** [comment]
@Knaledge pretty sure all those PRs are already there.

**Comment by wtwilson3** [comment]
Awesome.  BagnonPatched.zip fixed the bag problem for me too.

**Comment by voigtan** [comment]
When trying to open the guild bank you will also get an error.

**Comment by Torsin** [comment]
Just realized the zip file done by @yinzara used my comment with the numbers instead of the soundkit.values, also changed to use 117 for the dragging sound then packaged it up:
[Bagnon_73_Ready.zip](https://github.com/tullamods/Bagnon/files/1264452/Bagnon_73_Ready.zip)

**Comment by secondfry** [comment]
Also you can just use https://mods.curse.com/addons/wow/275697-playsound-temporal-fix until your addons are updated.

**Comment by Torsin** [comment]
Looks like the latest update fixed everything, but the Guild Bank:
Bagnon_GuildBank/components/frame.lua

Still has the old OpenSound and CloseSound values in the latest update.
