### ISSUE TITLE
Help! I cant open my bag!!

### ISSUE THREAD

**Issue by blindmaag13** [tullamods/Bagnon#588]
i guess its the new patch but i hit the button, nothing, click the bags, nothing......

Date: 2017-08-29 16:59:29
ID: 1
Error occured in: Global
Count: 1
Message: ...s\Bagnon\external\Wildpants\components\frameBase.lua line 17:
   Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
Debug:
   [C]: ?
   [C]: PlaySound()
   ...s\Bagnon\external\Wildpants\components\frameBase.lua:17: OnShow()
   ...s\Bagnon\external\Wildpants\components\inventory.lua:12:
      ...s\Bagnon\external\Wildpants\components\inventory.lua:11
   [C]: Show()
   ..\FrameXML\UIParent.lua:2928:
      ..\FrameXML\UIParent.lua:2923
   [C]: ShowUIPanel()
   ...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:54:
      ...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:50
   (tail call): ?
   ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:157: ToggleAllBags()
   [string "OPENALLBAGS"]:1:
      [string "OPENALLBAGS"]:1
Locals:

AddOns:
  Swatter, v7.4.5714 (TasmanianThylacine)
  ACP, vr245 
  Altoholic, vr182
  AucAdvanced, v7.4.5714 (TasmanianThylacine)
  AucFilterBasic, v7.4.5714 (TasmanianThylacine)
  AucFilterOutlier, v7.4.5714.5459(7.4/embedded)
  AucMatchUndercut, v7.4.5714.5585(7.4/embedded)
  AucStatHistogram, v7.4.5714 (TasmanianThylacine)
  AucStatiLevel, v7.4.5714 (TasmanianThylacine)
  AucStatPurchased, v7.4.5714 (TasmanianThylacine)
  AucStatSales, v7.4.5714.5598(7.4/embedded)
  AucStatSimple, v7.4.5714 (TasmanianThylacine)
  AucStatStdDev, v7.4.5714 (TasmanianThylacine)
  AucStatWOWEcon, v7.4.5714.5613(7.4/embedded)
  AucUtilAHWindowControl, v7.4.5714.5575(7.4/embedded)
  AucUtilAppraiser, v7.4.5714.5704(7.4/embedded)
  AucUtilAskPrice, v7.4.5714.5599(7.4/embedded)
  AucUtilAutoMagic, v7.4.5714.5686(7.4/embedded)
  AucUtilCompactUI, v7.4.5714.5694(7.4/embedded)
  AucUtilEasyBuyout, v7.4.5714.5576(7.4/embedded)
  AucUtilFixAH, v7.4.5714 (TasmanianThylacine)
  AucUtilItemSuggest, v7.4.5714.5651(7.4/embedded)
  AucUtilPriceLevel, v7.4.5714.5633(7.4/embedded)
  AucUtilScanButton, v7.4.5714.5631(7.4/embedded)
  AucUtilScanFinish, v7.4.5714.5588(7.4/embedded)
  AucUtilScanProgress, v7.4.5714.4979(7.4/embedded)
  AucUtilScanStart, v7.4.5714.5347(7.4/embedded)
  AucUtilSearchUI, v7.4.5714.5710(7.4/embedded)
  AucUtilSimpleAuction, v7.4.5714.5705(7.4/embedded)
  AucUtilVendMarkup, v7.4.5714.4828(7.4/embedded)
  Auctionator, v4.0.17
  Babylonian, v5.1.DEV.332(/embedded)
  BagBrother, v
  Bagnon, v7.2.7
  Bartender4, v4.7.9
  BeanCounter, v7.4.5714 (TasmanianThylacine)
  Configator, v5.1.DEV.406(/embedded)
  DataStore, vr63
  DataStoreAchievements, vr45
  DataStoreAgenda, vr25
  DataStoreAuctions, vr48
  DataStoreCharacters, vr40
  DataStoreContainers, vr56
  DataStoreCrafts, vr77
  DataStoreCurrencies, vr35
  datastoregarrisons, vr21
  DataStoreInventory, vr50
  DataStoreMails, vr49
  DataStorePets, vr42
  DataStoreQuests, vr42
  DataStoreReputations, vr40
  DataStoreSpells, vr30
  DataStoreStats, vr29
  DataStoreTalents, vr59
  DBMCore, v7.3.0
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  Enchantrix, v7.4.5714 (TasmanianThylacine)
  EnchantrixBarker, v7.4.5714 (TasmanianThylacine)
  Factionizer, v6.02.00.13 16.02.02
  HealBot, v7.2.5.0
  HealBotTips, v7.2.5.0
  Informant, v7.4.5714 (TasmanianThylacine)
  LibExtraTip, v5.12.DEV.423(/embedded)
  LibSharedMedia30, v3.0-97
  MillButton, v7.3
  MoveAnything, v16.2.2
  NPCScan, v7.2.0.2
  Overachiever, v0.99.8
  PetBattleTeams, v3.3.9
  PetTracker, v7.1.4
  PetTrackerBreeds, v7.1.4
  PetTrackerConfig, v7.1.4
  PetTrackerJournal, v7.1.4
  PetTrackerSwitcher, v7.1.4
  PetTrackerUpgrades, v7.1.4
  PokemonTrainer, v7.2.0
  Postal, vv3.5.8
  RaidAchieveFilter, v1.9.6
  Rarity, v1.0
  RarityOptions, v
  SellJunk, v3.0.15
  SimpleNotepad, v1.5.1
  SlideBar, v7.4.5714 (TasmanianThylacine)
  Stubby, v7.4.5714 (TasmanianThylacine)
  TipHelper, v5.12.DEV.405(/embedded)
  Titan, v5.12.1.70200
  TitanBag, v5.12.1.70200
  TitanClock, v5.12.1.70200
  TitanGold, v5.12.1.70200
  TitanLocation, v5.12.1.70200
  TitanLootType, v5.12.1.70200
  TitanPerformance, v5.12.1.70200
  TitanQuests, v3.0.12
  TitanRepair, v5.12.1.70200
  TitanVolume, v5.12.1.70200
  TitanXP, v5.12.1.70200
  TomTom, vv70200-1.0.0
  WowPro, v7.2.5T
  WoWProAchievements, v7.0.3N
  WoWProDailies, v7.0.3N
  WoWProLeveling, v7.2.5T
  WowProProfession, v7.0.3N
  WoWProWorldEvents, v7.0.3N
  XToLevel, v7.0.3_46
  BlizRuntimeLib_enUS v7.3.0.70300 <none>
  (ck=dbb)

**Comment by Hyphie24** [comment]
I had the same issue. Going to this post https://github.com/tullamods/Bagnon/issues/585 scroll down to Torsin's Post about the sounds is the issue. I followed all his changes and logged back in bags are now fully functional

**Comment by Cysec2k** [comment]
I've made the changes listed in the aforementioned post and put them in a zip file. I don't have the time to get set up for doing a proper submission to the repository so here it is. 
[Addons.zip](https://github.com/tullamods/Bagnon/files/1262389/Addons.zip)

**Comment by Torsin** [comment]
There is already a pending PR with the changes I believe, I also packaged up my changes(with a slight change on one of them).

[Bagnon_73_Ready.zip](https://github.com/tullamods/Bagnon/files/1264452/Bagnon_73_Ready.zip)

**Comment by blindmaag13** [comment]
Thank you

**Comment by ElOres** [comment]
Could you explain how to fix this in a way that a 5 year old can understand? haha I'm terrible with computers but not having this addon is killing me!

**Comment by Cysec2k** [comment]
Download the Addons.zip and extract to your addons folder, (located in your 'World of Warcraft\interface' folder) when prompted about overwriting click yes.

**Comment by ElOres** [comment]
I figured it out. thank you!!
