### ISSUE TITLE
bag animations when using AH

### ISSUE THREAD

**Issue by CadenceArmor** [tullamods/Bagnon#589]
Date: 2017-08-29 23:39:53
ID: 2
Error occured in: Global
Count: 1
Message: ...s\Bagnon\external\Wildpants\components\frameBase.lua line 22:
   Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
Debug:
   [C]: ?
   [C]: PlaySound()
   ...s\Bagnon\external\Wildpants\components\frameBase.lua:22: OnHide()
   ...s\Bagnon\external\Wildpants\components\inventory.lua:17:
      ...s\Bagnon\external\Wildpants\components\inventory.lua:16
   [C]: Hide()
   ..\FrameXML\UIParent.lua:2944: HideUIPanel()
   ...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:63: ?()
   ...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:143:
      ...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:143
   [string "safecall Dispatcher[1]"]:4:
      [string "safecall Dispatcher[1]"]:4
   [C]: ?
   [string "safecall Dispatcher[1]"]:13: ?()
   ...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: Fire()
   ...xternal\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:120:
      ...xternal\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:119
   [C]: ?
Locals:

AddOns:
  Swatter, v7.0.5 (<%codename%>)
  AngryKeystones, v
  Auctionator, v4.0.17
  AutoQuestTracker, vv1.2
  Babylonian, v5.1.DEV.332(/embedded)
  BagBrother, v
  Bagnon, v7.2.7
  BagnonFacade, v17
  BagnonItemLevel, v1.0
  Configator, v5.1.DEV.406(/embedded)
  DBMCore, v7.3.0
  DBMCountPackHoTS, v1.3
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsRaidInfoEmeraldNightmare, v
  DetailsRaidInfoNighthold, v
  DetailsRaidInfoTombOfSargeras, v
  DetailsRaidInfoTrialOfValor, v
  Gatherer, v7.0.5
  gUI4, v1.1
  gUI4ActionBars, v1.1
  gUI4Auras, v1.1
  gUI4CastBars, v1.1
  gUI4Chat, v1.1
  gUI4DevTools, v1.1
  gUI4FontChanger, v1.1
  gUI4Minimap, v1.1
  gUI4Objectives, v1.1
  gUI4Trade, v1.1
  gUI4UnitFrames, v1.1
  Mapster, v1.7.5.1-1-g6975e72
  Masque, v7.3.0
  MasqueGoldpaw, v1.0
  PitBull4, vv4.1.7
  Quester, v7.2.5.0
  QuickRoutes, v7.2-release
  Routes, vv1.5.7a
  SharedMediaGoldpaw, v1.0
  SlideBar, v7.0.5 (<%codename%>)
  StarCursor, vr2
  TomTom, vv70200-1.0.0
  TradeSkillMaster, vv3.6.32
  TradeSkillMasterAccounting, vv3.0.19
  TradeSkillMasterAuctionDB, vv3.1.17
  TradeSkillMasterAuctioning, vv3.0.15
  TradeSkillMasterCrafting, vv3.2.4
  TradeSkillMasterShopping, vv3.4.6
  WeakAuras, v2.4.18
  Wyr3dIcyVeinsStats, v
  BlizRuntimeLib_enUS v7.3.0.70300 <none>
  (ck=50e)

**Comment by Torsin** [comment]
Just use the following temp patched files, until Bagnon is updated with the same/similar changes, from the original #585 on this issue:

https://github.com/tullamods/Bagnon/files/1262133/BagnonPatched.zip
