### ISSUE TITLE
need a little help! my bags won`t open when i click my bag(patch 7.3 wow)

### ISSUE THREAD

**Issue by yoyoyoyoyoyoyoyoyoyoyoyoyoyoyooyo** [tullamods/Bagnon#590]
Date: 2017-08-30 00:43:44
ID: -1
Error occured in: Global
Count: 1
Message: ..\AddOns\Bartender4\Bartender4.lua line 350:
   Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
Debug:
   [C]: ?
   [C]: PlaySound()
   Bartender4\Bartender4.lua:350:
      Bartender4\Bartender4.lua:350
   [C]: Hide()
   Bartender4\Bartender4.lua:404: HideUnlockDialog()
   Bartender4\Bartender4.lua:420: Lock()
   Bartender4\Bartender4.lua:389:
      Bartender4\Bartender4.lua:388
Locals:

AddOns:
  Swatter, v7.4.5714 (TasmanianThylacine)
  Atlas, vv1.42.05
  AtlasBattlegrounds, vv1.42.00
  AtlasBurningCrusade, vv1.42.02
  AtlasCataclysm, vv1.42.00
  AtlasClassicWoW, vv1.42.01
  AtlasClassOrderHalls, vv1.42.00
  AtlasDungeonLocs, vv1.42.00
  AtlasLegion, vv1.42.01
  AtlasMistsofPandaria, vv1.42.01
  AtlasOutdoorRaids, vv1.42.00
  AtlasScenarios, vv1.42.00
  AtlasTransportation, vv1.42.00
  AtlasWarlordsofDraenor, vv1.42.00
  AtlasWorldEvents, vv3.23
  AtlasWrathoftheLichKing, vv1.42.03
  AtlasLoot, vv8.05.05
  AtlasLootBurningCrusade, vv8.05.05
  AtlasLootCataclysm, vv8.05.05
  AtlasLootClassic, vv8.05.05
  AtlasLootLegion, vv8.05.05
  AtlasLootMistsofPandaria, vv8.05.05
  AtlasLootWarlordsofDraenor, vv8.05.05
  AtlasLootWrathoftheLichKing, vv8.05.05
  AtlasMajorCitiesEnhanced, vv1.15
  AutoLootPlus, v1.2.2
  Babylonian, v5.1.DEV.332(/embedded)
  BagBrother, v
  Bagnon, v7.2.7
  Bartender4, v4.7.9
  BeanCounter, v7.4.5714 (TasmanianThylacine)
  ButtonTimers, v2.6.03
  Castbars, v
  Configator, v5.1.DEV.406(/embedded)
  DBMCore, v7.3.0
  DBMDefaultSkin, v
  DBMLDB, v
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  Decursive, v2.7.5.3
  GarrisonMissionManager, vv55
  HandyNotes, vv1.4.15
  HandyNotesLegionRaresTreasures, v1.01b
  HandyNotesLegionTreasures, v1
  HandyNotesSuramarLeylines, v1
  HandyNotesSuramarTelemancy, v1
  HandyNotesTrainers, v1.7.0
  HandyNotesVendors, v1.7.0
  HandyNotesWorldMapButton, v2.6
  Informant, v7.4.5714 (TasmanianThylacine)
  LibExtraTip, v5.12.DEV.423(/embedded)
  MaxDps, v7.2.6
  MaxDpsDemonHunter, v7.2.5
  MyRareFinder, v1.3
  Recount, vv7.2.5f
  SilverDragon, vv4.0.2
  SilverDragonBurningCrusade, vv4.0.2
  SilverDragonCataclysm, vv4.0.2
  SilverDragonLegion, vv4.0.2
  SilverDragonMists, vv4.0.2
  SilverDragonVanilla, vv4.0.2
  SilverDragonWarlords, vv4.0.2

**Comment by PollyDandy** [comment]
I am having the same issue.  The bags work correctly when I turn the addon off.  I quit playing tonight because I miss my addon!

**Comment by shamaniThrall** [comment]
PlaySound caused the errr
Just comment all lines with PlaySound(...
PlaySound(...)
--PlaySound(..)
or replace this files:
[frameBase.zip](https://github.com/tullamods/Bagnon/files/1262582/frameBase.zip)

**Comment by yoyoyoyoyoyoyoyoyoyoyoyoyoyoyooyo** [comment]
shamani, I`ve never done that before how do I do it and where do I go?

**Comment by shamaniThrall** [comment]
On your hard disc, in the wow Folder "World of Warcraft"
is a subfolder called 
\Interface\AddOns\Bagnon\external\Wildpants\components
unzip the attached zip file and copy the 2 files in this folder(replace the existing ones)

**Comment by blownawayagain** [comment]
I went through the whole folder opened up everything and there is no extra folder to unzip and I can't open my bags

**Comment by blownawayagain** [comment]
I went and unzipped the frameBase.zip and put it in the file still don't work

**Comment by todeshur** [comment]
I was having the same bug, but as of now I am playing without the addon. I hope this gets resolved soon.

**Comment by jerryholt** [comment]
worked great! thanks for my one bag back. you rock!

**Comment by Torsin** [comment]
Or you could use this zip file with all the proper changes, thanks to @yinzara for incorporating my changes into this temporary file:

https://github.com/tullamods/Bagnon/files/1262133/BagnonPatched.zip

**Comment by RKTakami** [comment]
Same problem. Bagnon needs updating to fix the can not open bags issue.

**Comment by PollyDandy** [comment]
The fix worked!  Thanks!

**Comment by jones2888** [comment]
Anyone who worked on the zip files - I love you - nuff said lol

**Comment by sattracer** [comment]
Thank you guys to the ones that posted the way to fix Bagnon myself, it worked and I am very grateful. Unlike another place I tried to share the updated file with, with only the sound calls replaced, no other edits, and very professionally. That place just blew it away and pretty much said Jailborc fixed it 2 days ago (wasn't working) and to be mad at him for it not working.  I'm not mad Jailborc, stuff happens.  I had forgotten the rule about gamers though.  I doubt very seriously if I'll offer any more feedback or solutions after that.

**Comment by PollyDandy** [comment]
I can't play with out Bagnon, plain and simple.  I actually left game last night when it didn't work. I hate trying to figure out which bag I have stuff in.  So again, thank you very much!

**Comment by blownawayagain** [comment]
I am sorry Is there is anyway they are going to fix the main download I can
not get the bags to open on either one of my computers. I am tired of
working on it I don't like patch work If it don't get fix I will leave
everything and I will take a lot with me.

**Comment by Torsin** [comment]
@blownawayagain 
They will make the changes in the addon, when they have time.  Remember the authors have work and lives just like the rest of us.

Or you could use this zip file with all the proper changes:

[Bagnon_73_Ready.zip](https://github.com/tullamods/Bagnon/files/1264452/Bagnon_73_Ready.zip)

The folders (BagBrother, Bagnon, Bagnon_Config, Bagnon_GuildBank, Bagnon_VoidStorage) go directly into your wow Addon folder which has a default location of:  c:\Program Files (x86)\World of Warcraft\Interface\AddOns

**Comment by PollyDandy** [comment]
Actually, I am good.  I was just saying thank you. :)
