### ISSUE TITLE
Bagnon Error When Opening Guild Bank

### ISSUE THREAD

**Issue by KarmaTheBeloved** [tullamods/Bagnon#591]
Patched Bagnon with v7.2.7 this morning, closed out WoW entirely.  Reopened WoW, went to my bank toon, and tried to open the guild bank.   Bank will not open. Received the error message below.

Date: 2017-08-30 10:54:19
ID: 2
Error occured in: Global
Count: 1
Message: ...s\Bagnon\external\Wildpants\components\frameBase.lua line 
22:
Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", 
"Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
Debug:
 [C]: PlaySound()
 ...s\Bagnon\external\Wildpants\components\frameBase.lua:22:
OnHide()
 ...terface\AddOns\Bagnon_GuildBank\components\frame.lua:51:
              ...terface\AddOns\Bagnon_GuildBank\components\frame.lua:50
 [C]: Hide()
 ..\FrameXML\UIParent.lua:3092:
   ..\FrameXML\UIParent.lua:3087
 [C]: securecall()
 ..\FrameXML\UIParent.lua:3130: CloseWindows()
 ..\FrameXML\UIParent.lua:3158:
   ..\FrameXML\UIParent.lua:3148
 [C]: securecall()
  ..\FrameXML\UIParent.lua:3771: ToggleGameMenu()
 [string "TOGGLEGAMEMENU"]:1:
    [string "TOGGLEGAMEMENU"]:1
Locals:
(*temporary) = "GuildVaultClose"

AddOns:
 Swatter, v7.4.5714 (TasmanianThylacine)
 NPCScanOverlay, v7.1.0.1
 NPCScanOverlayBroker, v1.2.7
 AckisRecipeList, v7.3.0.1
 AckisRecipeListQuickScan, v7.2.0.1
 Altoholic, vr182
 AskMrRobot, v52
 AucAdvanced, v7.4.5714 (TasmanianThylacine)
 aucadvancedsearcherpawn, v1.5.8
 auccheapsearcher, v20170811
 AucFilterBasic, v7.4.5714 (TasmanianThylacine)
 AucFilterOutlier, v7.4.5714.5459(7.4/embedded)
 AucMatchUndercut, v7.4.5714.5585(7.4/embedded)
 AucScanData, v7.4.5714 (TasmanianThylacine)
 AucStatHistogram, v7.4.5714 (TasmanianThylacine)
 AucStatiLevel, v7.4.5714 (TasmanianThylacine)
 AucStatPurchased, v7.4.5714 (TasmanianThylacine)
 AucStatSales, v7.4.5714.5598(7.4/embedded)
 AucStatSimple, v7.4.5714 (TasmanianThylacine)
 AucStatStdDev, v7.4.5714 (TasmanianThylacine)
 AucStatWOWEcon, v7.4.5714.5613(7.4/embedded)
 AucUtilAHWindowControl, v7.4.5714.5575(7.4/embedded)
 AucUtilAppraiser, v7.4.5714.5704(7.4/embedded)
 AucUtilAskPrice, v7.4.5714.5599(7.4/embedded)
 AucUtilAutoMagic, v7.4.5714.5686(7.4/embedded)
 AucUtilCompactUI, v7.4.5714.5694(7.4/embedded)
 AucUtilEasyBuyout, v7.4.5714.5576(7.4/embedded)
 AucUtilFixAH, v7.4.5714 (TasmanianThylacine)
 AucUtilItemSuggest, v7.4.5714.5651(7.4/embedded)
 AucUtilPriceLevel, v7.4.5714.5633(7.4/embedded)
 AucUtilScanButton, v7.4.5714.5631(7.4/embedded)
 AucUtilScanFinish, v7.4.5714.5588(7.4/embedded)
 AucUtilScanProgress, v7.4.5714.4979(7.4/embedded)
 AucUtilScanStart, v7.4.5714.5347(7.4/embedded)
 AucUtilSearchUI, v7.4.5714.5710(7.4/embedded)
 AucUtilSimpleAuction, v7.4.5714.5705(7.4/embedded)
 AucUtilVendMarkup, v7.4.5714.4828(7.4/embedded)
 AutoRepair, v
 Babylonian, v5.1.DEV.332(/embedded)
 BagBrother, v
 Bagnon, v7.2.7
 BagnonGuildBank, v7.2.7
 BagnonScrap, v17
 BeanCounter, v7.4.5714 (TasmanianThylacine)
 BigWigs, vv70.1
 BigWigsAutoReply, v1.2
 BigWigsRecordKills, v2.04
 Blitz, v7.2
 CanIMogIt, v7.3.0.01
 Configator, v5.1.DEV.406(/embedded)
 DataStore, vr63
 DataStoreAchievements, vr45
 DataStoreAgenda, vr25
 DataStoreAuctions, vr48
 DataStoreCharacters, vr40
 DataStoreContainers, vr56
 DataStoreCrafts, vr77
 DataStoreCurrencies, vr35
 DataStoreGarrisons, vr21
 DataStoreInventory, vr50
 DataStoreMails, vr49
 DataStorePets, vr42
 DataStoreQuests, vr42
 DataStoreReputations, vr40
 DataStoreSpells, vr30
 DataStoreStats, vr29
 DataStoreTalents, vr59
 DBMCore, v7.3.0
 DBMDefaultSkin, v
 DBMInterrupts, v6.2.0
 DBMLDB, v
 DBMSpellTimers, v
 DBMStatusBarTimers, v
 DCoords, v4.3.20
 DebugLib, v5.1.DEV.337(/embedded)
 EasyLunkerTurnIn, v1.16
 Enchantrix, v7.4.5714 (TasmanianThylacine)
 EnchantrixBarker, v7.4.5714 (TasmanianThylacine)
 ExRT, v3885
 GatherMate2, v1.41
 GTFO, v4.42.18
 HandyNotes, vv1.4.15
 HandyNotesLegionRaresTreasures, v1.01b
 Healium, v
 Informant, v7.4.5714 (TasmanianThylacine)
 IskarAssist, v
 LibExtraTip, v5.12.DEV.423(/embedded)
 LibPeriodicTable31, vv3.3.0.578
 LibSharedMedia30, v3.0-97
 MogIt, v3.8.1
 MogItCloth, v3.8.1
 MogItHighlighter, vv1.3.2
 MogItOneHanded, v3.8.1
 MogItOther, v3.8.1
 MogItRanged, v3.8.1
 MogItTwoHanded, v3.8.1
 MoveAnything, v16.2.2
 NPCScan, v7.2.0.2
 Omen, v3.1.12
 Pawn, v2.2.11
 Postal, vv3.5.8
 Scrap, v13.5
 Skada, v1.7.1
 SkadaRaidRng, v1
 SkadaAvoidanceMitigation, v1.3.4
 SkadaCCTracker, v0.1
 SkadaDmgReductions, v
 SkadaDPSplusHPS, v1.6
 SkadaForTanks, v3.1.14
 SkadaPlayerScore, v1.06
 SkadaScroll, v1.5.3
 SkadaSurvivability, v1.0
 Stubby, v7.4.5714 (TasmanianThylacine)
 TheUndermineJournal, v4.7.20170829
 TipHelper, v5.12.DEV.405(/embedded)
 Transcriptor, vv7.3.0
 WhoLusted, v1.1
 BlizRuntimeLib_enUS v7.3.0.70300 <none>
 (ck=e6c)

**Comment by Torsin** [comment]
Did you try downloading the following zipped up fix for this from the Project Issue #585:

[Bagnon_73_Ready.zip](https://github.com/tullamods/Bagnon/files/1264452/Bagnon_73_Ready.zip)

**Comment by KarmaTheBeloved** [comment]
Thank you - this patch fixed the issue.  Both bank toons can access and display the guild bank correctly and search works as well.  I had used the previous patch to no avail.  Thanks, again.
