### ISSUE TITLE
Patch 7.3

### ISSUE THREAD

**Issue by TYGERLILY425** [tullamods/Bagnon#592]
Please please please update for new patch!!! I want to keep playing but the bags are so harrribleeee without this addon

**Comment by wyngman** [comment]
Bags will not open in-game for some reason. I have all other add-ons turned off but to no avail.

**Comment by jones2888** [comment]
Bagon is broken in 7.3. I copied a macro i found and moved the icon to my toolbar. It will open all the bags, but it won't closed them (use x to close). I hope that this problem is temporary.  I love my bagon!!

/script OpenAllBags()

**Comment by eSkiSo** [comment]
Fixed by replacing **bag.lua** and **frameBase.lua** as referred on this **wildpants** (bagnon component) pull request:


https://github.com/tullamods/Wildpants/pull/7/files

**Comment by Torsin** [comment]
Did you try downloading the following zipped up fix for this from the Project Issue #585:

[Bagnon_73_Ready.zip](https://github.com/tullamods/Bagnon/files/1264452/Bagnon_73_Ready.zip)

**Comment by Bangerznmash** [comment]
I made all of the proper changes with the zip file, but now the tooltips are not working. I can see all of the items, I just don't know what they are now.

**Comment by Torsin** [comment]
That might be something different for the tooltips, they are working fine on my system.  As a test if you disable all your other addons except Bagnon do the tooltips still not show properly?

**Comment by Bangerznmash** [comment]
I disabled it all, and left only Bagnon and related addons active. 
It still didn't work. 
Then I eliminated all and just Bagnon with no related addons running and it worked fine. 
When I enable Bagnon_Forever, then it stops working.

Bagnon_forever/ui/tooltips.lua is the file sending the error message:
**"attempt to index global 'BagnonUtil' (a nil value)"**

**Comment by theisencr** [comment]
Auctionator is indeed busted right now, and will cause issues all throughout your UI if left activated.

**Comment by oscargarcia0101** [comment]
Thank you Torsin! Works perfectly!

If that zip isn't working for someone, then something else is wrong on your end. So far 10+ people in my guild are using the zip Torsin uploaded and its working perfect!

**Comment by l3rahma** [comment]
+5 Internet points to Torsin. I just opened the .zip folder, copied everything inside, pasted them all into my addons folder, clicked replace old with new and it works!

**Comment by Bangerznmash** [comment]
Okay, here is the scoop on Bagnon_Forever.

Originally it was used to handle the tooltips for Bagnon. Now BagBrother is being used to handle the tooltips so Bagnon_Forever has become outdated and just now showed up as a problem with the sound handler being changed.

I deleted the entire Bagnon_Forever folder and all of its contents and now everything works fine.

So, if you have Bagnon_Forever in your AddOns folder it might be prudent to take it out. I am going to test for a bit to make sure it does not affect anything else but as of this writing everything seems to be functioning properly.

**Comment by Jaliborc** [comment]
Bagnon_Forever has been removed from Bagnon probably around 6 years ago

**Comment by narma** [comment]
Guys, what issue with https://github.com/tullamods/Wildpants/pull/7 ? Can we merge it?

**Comment by siniestro1823** [comment]
I did what Torsin requested by DL the zip manually and it works now
