### ISSUE TITLE
bags keep giving me this error

### ISSUE THREAD

**Issue by ender20510** [tullamods/Bagnon#594]
Message: ...s\Bagnon\external\Wildpants\components\frameBase.lua:17: Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
Time: 08/31/17 13:21:49
Count: 1
Stack: ...s\Bagnon\external\Wildpants\components\frameBase.lua:17: Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
[C]: ?
[C]: in function `PlaySound'
...s\Bagnon\external\Wildpants\components\frameBase.lua:17: in function `OnShow'
...s\Bagnon\external\Wildpants\components\inventory.lua:12: in function <...s\Bagnon\external\Wildpants\components\inventory.lua:11>
[C]: in function `Show'
Interface\FrameXML\UIParent.lua:2928: in function <Interface\FrameXML\UIParent.lua:2923>
[C]: in function `ShowUIPanel'
...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:54: in function <...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:50>
(tail call): ?
(tail call): ?
...s\Bagnon\external\Wildpants\features\autoDisplay.lua:117: in function `ToggleBackpack'
[string "TOGGLEBACKPACK"]:1: in function <[string "TOGGLEBACKPACK"]:1>

**Comment by alexas** [comment]
Check the post #592 , it gives a file that will fix it :)
Have a nice day !
