### ISSUE TITLE
bags won't open

### ISSUE THREAD

**Issue by phantom892** [tullamods/Bagnon#596]
deleted all bagon files in addons 
Downloaded n installed 7.3 
Bags won't open unless I disable bagon

**Comment by specs1188** [comment]
Hello, new here.  I'm having the same issue, as is my roommate.  The issue began first login after patch 7.3. 
 
[bagnon_failure_patch7.3.txt](https://github.com/tullamods/Bagnon/files/1268888/bagnon_failure_patch7.3.txt)
I have also uninstalled/reinstalled bagnon, verified all settings in wow, etc.  I will attach the swatter info.

**Comment by tiffygunt** [comment]
I have this issue almost every time a new patch comes out :( I had to disable until it gets updated again.

**Comment by Torsin** [comment]
Did you try downloading the following zipped up fix for this from the Project Issue #585:

[Bagnon_73_Ready.zip](https://github.com/tullamods/Bagnon/files/1264452/Bagnon_73_Ready.zip)

**Comment by tiffygunt** [comment]
Just downloaded the zip and it works!! Thank you!!

**Comment by specs1188** [comment]
Downloaded and unzipped, works perfect!  Thank you very much! :)
