### ISSUE TITLE
Issues with Bagnon

### ISSUE THREAD

**Issue by bigmanstian** [tullamods/Bagnon#598]
Date: 2017-09-01 14:12:47
ID: 5
Error occured in: Global
Count: 1
Message: ...s\Bagnon\external\Wildpants\components\frameBase.lua line 17:
   Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
Debug:
   [C]: PlaySound()
   ...s\Bagnon\external\Wildpants\components\frameBase.lua:17: OnShow()
   ...s\Bagnon\external\Wildpants\components\inventory.lua:12:
      ...s\Bagnon\external\Wildpants\components\inventory.lua:11
   [C]: Show()
   ..\FrameXML\UIParent.lua:2928: ShowUIPanel()
   ...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:54:
      ...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:50
   (tail call): ?
   ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:157: ToggleAllBags()
   [string "OPENALLBAGS"]:1:
      [string "OPENALLBAGS"]:1
Locals:
(*temporary) = "igBackPackOpen"

AddOns:
  Swatter, v7.4.5714 (TasmanianThylacine)
  NPCScanOverlay, v7.1.0.1
  AtlasLoot, vv8.06.00
  AtlasLootBurningCrusade, vv8.06.00
  AtlasLootCataclysm, vv8.06.00
  AtlasLootClassic, vv8.06.00
  AtlasLootLegion, vv8.06.00
  AtlasLootMistsofPandaria, vv8.06.00
  AtlasLootWarlordsofDraenor, vv8.06.00
  AtlasLootWrathoftheLichKing, vv8.06.00
  Babylonian, v5.1.DEV.332(/embedded)
  BagBrother, v
  Bagnon, v7.2.7
  Bartender4, v4.7.10
  Configator, v5.1.DEV.406(/embedded)
  DBMCore, v7.3.1
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  Gatherer, v7.0.5
  GatherMate2, v1.41
  Gladius, v5.1.8
  GTFO, v4.42.18
  HandyNotes, vv1.4.15
  HandyNotesDraenorTreasures, v1.20a
  HealersHaveToDie, v2.4.5-deprecated
  HHTD, v2.4.5
  Informant, v7.4.5714 (TasmanianThylacine)
  LibExtraTip, v5.12.DEV.423(/embedded)
  MikScrollingBattleText, v5.7.147
  MogIt, v3.8.1
  MogItOneHanded, v3.8.1
  MogItOther, v3.8.1
  MogItPlate, v3.8.1
  MogItRanged, v3.8.1
  MogItTwoHanded, v3.8.1
  NPCScan, v7.2.0.2
  Quartz, v3.3.6
  Recount, vv7.2.5f
  SavedInstances, v7.0.8
  sct, v7.00
  SexyMap, vv7.3.0
  SlideBar, v7.4.5714 (TasmanianThylacine)
  SmartTabTarget, v
  Stubby, v7.4.5714 (TasmanianThylacine)
  SuperDuperMacro, v2.4.6
  TidyPlates, v6.18.11
  TidyPlatesGraphite, v
  TidyPlatesGrey, v
  TidyPlatesNeon, v
  TidyPlatesQuatre, v
  TidyPlatesHub, v
  TidyPlatesWidgets, v
  TipHelper, v5.12.DEV.405(/embedded)
  WorldBossStatus, v5.5.2
  BlizRuntimeLib_enUS v7.3.0.70300 <none>
  (ck=5e2)

**Comment by Torsin** [comment]
Did you try downloading the following zipped up fix for this from the Project Issue #585:

[Bagnon_73_Ready.zip](https://github.com/tullamods/Bagnon/files/1264452/Bagnon_73_Ready.zip)

**Comment by secondfry** [comment]
Or use https://wow.curseforge.com/projects/playsound-temporal-fix to fix it for all addons (read description tho).
