### ISSUE TITLE
Please update for 7.3

### ISSUE THREAD

**Issue by JafarSep** [tullamods/Bagnon#599]
Bagnon is not updated for 7.3 and is making me use default blizz bags D=
please send help

**Comment by Torsin** [comment]
Did you try downloading the following zipped up fix for this from the Project Issue #585:

[Bagnon_73_Ready.zip](https://github.com/tullamods/Bagnon/files/1264452/Bagnon_73_Ready.zip)

**Comment by secondfry** [comment]
Or use https://wow.curseforge.com/projects/playsound-temporal-fix to fix it for all addons (read description tho).
