### ISSUE TITLE
Really miss Bagnon - doesn't work with 7.3

### ISSUE THREAD

**Issue by Kedehern** [tullamods/Bagnon#600]
Getting error with new patch.

Date: 2017-09-01 09:15:04
ID: 1
Error occured in: Global
Count: 1
Message: ...s\Bagnon\external\Wildpants\components\frameBase.lua line 17:
   Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
Debug:
   [C]: PlaySound()
   ...s\Bagnon\external\Wildpants\components\frameBase.lua:17: OnShow()
   ...s\Bagnon\external\Wildpants\components\inventory.lua:12:
      ...s\Bagnon\external\Wildpants\components\inventory.lua:11
   [C]: Show()
   ..\FrameXML\UIParent.lua:2928: ShowUIPanel()
   ...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:54:
      ...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:50
   (tail call): ?
   (tail call): ?
   ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:117: ToggleBackpack()
   ..\FrameXML\MainMenuBarBagButtons.lua:54: BackpackButton_OnClick()
   [string "*:OnClick"]:4:
      [string "*:OnClick"]:1
Locals:
(*temporary) = "igBackPackOpen"

AddOns:
  Swatter, v7.4.5714 (TasmanianThylacine)
  AntiPetBattle, v1.2.14
  AucAdvanced, v7.4.5714 (TasmanianThylacine)
  AucFilterBasic, v7.4.5714 (TasmanianThylacine)
  AucFilterOutlier, v7.4.5714.5459(7.4/embedded)
  AucMatchUndercut, v7.4.5714.5585(7.4/embedded)
  AucStatHistogram, v7.4.5714 (TasmanianThylacine)
  AucStatiLevel, v7.4.5714 (TasmanianThylacine)
  AucStatPurchased, v7.4.5714 (TasmanianThylacine)
  AucStatSales, v7.4.5714.5598(7.4/embedded)
  AucStatSimple, v7.4.5714 (TasmanianThylacine)
  AucStatStdDev, v7.4.5714 (TasmanianThylacine)
  AucStatWOWEcon, v7.4.5714.5613(7.4/embedded)
  AucUtilAHWindowControl, v7.4.5714.5575(7.4/embedded)
  AucUtilAppraiser, v7.4.5714.5704(7.4/embedded)
  AucUtilAskPrice, v7.4.5714.5599(7.4/embedded)
  AucUtilAutoMagic, v7.4.5714.5686(7.4/embedded)
  AucUtilCompactUI, v7.4.5714.5694(7.4/embedded)
  AucUtilEasyBuyout, v7.4.5714.5576(7.4/embedded)
  AucUtilFixAH, v7.4.5714 (TasmanianThylacine)
  AucUtilItemSuggest, v7.4.5714.5651(7.4/embedded)
  AucUtilPriceLevel, v7.4.5714.5633(7.4/embedded)
  AucUtilScanButton, v7.4.5714.5631(7.4/embedded)
  AucUtilScanFinish, v7.4.5714.5588(7.4/embedded)
  AucUtilScanProgress, v7.4.5714.4979(7.4/embedded)
  AucUtilScanStart, v7.4.5714.5347(7.4/embedded)
  AucUtilSearchUI, v7.4.5714.5710(7.4/embedded)
  AucUtilSimpleAuction, v7.4.5714.5705(7.4/embedded)
  AucUtilVendMarkup, v7.4.5714.4828(7.4/embedded)
  AutoRepair, v
  Babylonian, v5.1.DEV.332(/embedded)
  Bagnon, v7.2.7
  BeanCounter, v7.4.5714 (TasmanianThylacine)
  ButtonForge, v0.9.47
  Configator, v5.1.DEV.406(/embedded)
  Coordinates, v1.23
  DBMCore, v7.3.1
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  Enchantrix, v7.4.5714 (TasmanianThylacine)
  EnchantrixBarker, v7.4.5714 (TasmanianThylacine)
  FishingBuddy, v1.7.13e
  HandyNotes, vv1.4.15
  HandyNotesDraenorTreasures, v1.20a
  Informant, v7.4.5714 (TasmanianThylacine)
  LibExtraTip, v5.12.DEV.423(/embedded)
  Mapster, v1.7.6
  MasterPlanA, vA
  Postal, vv3.5.8
  RareScanner, v2.5.1
  SellJunk, v3.0.15
  SilverDragon, vv4.0.2
  SilverDragonBurningCrusade, vv4.0.2
  SilverDragonCataclysm, vv4.0.2
  SilverDragonLegion, vv4.0.2
  SilverDragonMists, vv4.0.2
  SilverDragonVanilla, vv4.0.2
  SilverDragonWarlords, vv4.0.2
  SilverDragonWrath, vv4.0.2
  SlideBar, v7.4.5714 (TasmanianThylacine)
  Stubby, v7.4.5714 (TasmanianThylacine)
  TipHelper, v5.12.DEV.405(/embedded)
  BlizRuntimeLib_enUS v7.3.0.70300 <none>
  (ck=9a2)

**Comment by Mystikal-Blackhand** [comment]
Date: 2017-09-01 10:09:49
ID: 3
Error occured in: Global
Count: 1
Message: ...s\Bagnon\external\Wildpants\components\frameBase.lua line 22:
   Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
Debug:
   [C]: ?
   [C]: PlaySound()
   ...s\Bagnon\external\Wildpants\components\frameBase.lua:22: OnHide()
   ...s\Bagnon\external\Wildpants\components\inventory.lua:17:
      ...s\Bagnon\external\Wildpants\components\inventory.lua:16
   [C]: Hide()
   ..\FrameXML\UIParent.lua:2944: HideUIPanel()
   ...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:63:
      ...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:59
   (tail call): ?
   ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:157: ToggleAllBags()
   [string "OPENALLBAGS"]:1:
      [string "OPENALLBAGS"]:1
Locals:

AddOns:
  Swatter, v7.4.5714 (TasmanianThylacine)
  AucAdvanced, v7.4.5714 (TasmanianThylacine)
  AucFilterBasic, v7.4.5714 (TasmanianThylacine)
  AucFilterOutlier, v7.4.5714.5459(7.4/embedded)
  AucMatchUndercut, v7.4.5714.5585(7.4/embedded)
  AucStatHistogram, v7.4.5714 (TasmanianThylacine)
  AucStatiLevel, v7.4.5714 (TasmanianThylacine)
  AucStatPurchased, v7.4.5714 (TasmanianThylacine)
  AucStatSales, v7.4.5714.5598(7.4/embedded)
  AucStatSimple, v7.4.5714 (TasmanianThylacine)
  AucStatStdDev, v7.4.5714 (TasmanianThylacine)
  AucStatWOWEcon, v7.4.5714.5613(7.4/embedded)
  AucUtilAHWindowControl, v7.4.5714.5575(7.4/embedded)
  AucUtilAppraiser, v7.4.5714.5704(7.4/embedded)
  AucUtilAskPrice, v7.4.5714.5599(7.4/embedded)
  AucUtilAutoMagic, v7.4.5714.5686(7.4/embedded)
  AucUtilCompactUI, v7.4.5714.5694(7.4/embedded)
  AucUtilEasyBuyout, v7.4.5714.5576(7.4/embedded)
  AucUtilFixAH, v7.4.5714 (TasmanianThylacine)
  AucUtilItemSuggest, v7.4.5714.5651(7.4/embedded)
  AucUtilPriceLevel, v7.4.5714.5633(7.4/embedded)
  AucUtilScanButton, v7.4.5714.5631(7.4/embedded)
  AucUtilScanFinish, v7.4.5714.5588(7.4/embedded)
  AucUtilScanProgress, v7.4.5714.4979(7.4/embedded)
  AucUtilScanStart, v7.4.5714.5347(7.4/embedded)
  AucUtilSearchUI, v7.4.5714.5710(7.4/embedded)
  AucUtilSimpleAuction, v7.4.5714.5705(7.4/embedded)
  AucUtilVendMarkup, v7.4.5714.4828(7.4/embedded)
  Babylonian, v5.1.DEV.332(/embedded)
  BagBrother, v
  Bagnon, v7.2.7
  Bartender4, v4.7.10
  BeanCounter, v7.4.5714 (TasmanianThylacine)
  Configator, v5.1.DEV.406(/embedded)
  DBMCore, v7.3.1
  DBMDefaultSkin, v
  DBMInterrupts, v6.2.0
  DBMNightholdDBH, v
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  Decursive, v2.7.5.3
  Enchantrix, v7.4.5714 (TasmanianThylacine)
  EnchantrixBarker, v7.4.5714 (TasmanianThylacine)
  ExRT, v3885
  GTFO, v4.42.18
  HandyNotes, vv1.4.15
  HandyNotesLegionTreasures, v1
  HealBot, v7.2.5.0
  HealBotTips, v7.2.5.0
  Informant, v7.4.5714 (TasmanianThylacine)
  LibExtraTip, v5.12.DEV.423(/embedded)
  Pawn, v2.2.13
  Postal, vv3.5.8
  Scrap, v13.5
  ScrapSpotlight, v13.5
  ShadowedUnitFrames, vv4.1.20
  Skada, v1.7.2
  SlideBar, v7.4.5714 (TasmanianThylacine)
  Stubby, v7.4.5714 (TasmanianThylacine)
  TipHelper, v5.12.DEV.405(/embedded)
  TomTom, vv70200-1.0.0
  BlizRuntimeLib_enUS v7.3.0.70300 <none>
  (ck=931)

**Comment by Torsin** [comment]
Did you try downloading the following zipped up fix for this from the Project Issue #585:

[Bagnon_73_Ready.zip](https://github.com/tullamods/Bagnon/files/1264452/Bagnon_73_Ready.zip)

**Comment by Mystikal-Blackhand** [comment]
No I haven't.  Thanks for the link!  I am a casual player and usually just
rely on Curse and wait for updates to fix the issue, but I love bagnon so I
thought I'd at least report the bug.

Much gratitude!
Mystikal-Blackhand

If a man has not discovered something that he will die for, he isn't fit to
live.
-Dr. Martin Luther King Jr.-

**Comment by secondfry** [comment]
Or use https://wow.curseforge.com/projects/playsound-temporal-fix to fix it for all addons (read description tho).
