### ISSUE TITLE
Not working with new patch.

### ISSUE THREAD

**Issue by TimWherry** [tullamods/Bagnon#601]
Date: 2017-09-01 11:23:47
ID: 1
Error occured in: Global
Count: 1
Message: ...s\Bagnon\external\Wildpants\components\frameBase.lua line 17:
   Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
Debug:
   [C]: PlaySound()
   ...s\Bagnon\external\Wildpants\components\frameBase.lua:17: OnShow()
   ...s\Bagnon\external\Wildpants\components\inventory.lua:12:
      ...s\Bagnon\external\Wildpants\components\inventory.lua:11
   [C]: Show()
   ..\FrameXML\UIParent.lua:2928: ShowUIPanel()
   ...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:54:
      ...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:50
   (tail call): ?
   ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:157: ToggleAllBags()
   [string "OPENALLBAGS"]:1:
      [string "OPENALLBAGS"]:1
Locals:
(*temporary) = "igBackPackOpen"

AddOns:
  Swatter, v7.4.5714 (TasmanianThylacine)
  Altoholic, vr182
  AtlasLoot, vv8.06.00
  AtlasLootBurningCrusade, vv8.06.00
  AtlasLootCataclysm, vv8.06.00
  AtlasLootClassic, vv8.06.00
  AtlasLootLegion, vv8.06.00
  AtlasLootMistsofPandaria, vv8.06.00
  AtlasLootWarlordsofDraenor, vv8.06.00
  AtlasLootWrathoftheLichKing, vv8.06.00
  AucAdvanced, v7.4.5714 (TasmanianThylacine)
  AucFilterBasic, v7.4.5714 (TasmanianThylacine)
  AucFilterOutlier, v7.4.5714.5459(7.4/embedded)
  AucMatchUndercut, v7.4.5714.5585(7.4/embedded)
  AucStatHistogram, v7.4.5714 (TasmanianThylacine)
  AucStatiLevel, v7.4.5714 (TasmanianThylacine)
  AucStatPurchased, v7.4.5714 (TasmanianThylacine)
  AucStatSales, v7.4.5714.5598(7.4/embedded)
  AucStatSimple, v7.4.5714 (TasmanianThylacine)
  AucStatStdDev, v7.4.5714 (TasmanianThylacine)
  AucStatWOWEcon, v7.4.5714.5613(7.4/embedded)
  AucUtilAHWindowControl, v7.4.5714.5575(7.4/embedded)
  AucUtilAppraiser, v7.4.5714.5704(7.4/embedded)
  AucUtilAskPrice, v7.4.5714.5599(7.4/embedded)
  AucUtilAutoMagic, v7.4.5714.5686(7.4/embedded)
  AucUtilCompactUI, v7.4.5714.5694(7.4/embedded)
  AucUtilEasyBuyout, v7.4.5714.5576(7.4/embedded)
  AucUtilFixAH, v7.4.5714 (TasmanianThylacine)
  AucUtilItemSuggest, v7.4.5714.5651(7.4/embedded)
  AucUtilPriceLevel, v7.4.5714.5633(7.4/embedded)
  AucUtilScanButton, v7.4.5714.5631(7.4/embedded)
  AucUtilScanFinish, v7.4.5714.5588(7.4/embedded)
  AucUtilScanProgress, v7.4.5714.4979(7.4/embedded)
  AucUtilScanStart, v7.4.5714.5347(7.4/embedded)
  AucUtilSearchUI, v7.4.5714.5710(7.4/embedded)
  AucUtilSimpleAuction, v7.4.5714.5705(7.4/embedded)
  AucUtilVendMarkup, v7.4.5714.4828(7.4/embedded)
  Babylonian, v5.1.DEV.332(/embedded)
  BagBrother, v
  Bagnon, v7.2.7
  Bartender4, v4.7.10
  BeanCounter, v7.4.5714 (TasmanianThylacine)
  Configator, v5.1.DEV.406(/embedded)
  DataStore, vr63
  DataStoreAchievements, vr45
  DataStoreAgenda, vr25
  DataStoreAuctions, vr48
  DataStoreCharacters, vr40
  DataStoreContainers, vr56
  DataStoreCrafts, vr77
  DataStoreCurrencies, vr35
  DataStoreGarrisons, vr21
  DataStoreInventory, vr50
  DataStoreMails, vr49
  DataStorePets, vr42
  DataStoreQuests, vr42
  DataStoreReputations, vr40
  DataStoreSpells, vr30
  DataStoreStats, vr29
  DataStoreTalents, vr59
  DBMCore, v7.3.1
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  Enchantrix, v7.4.5714 (TasmanianThylacine)
  EnchantrixBarker, v7.4.5714 (TasmanianThylacine)
  Immersion, v0.4.4
  Informant, v7.4.5714 (TasmanianThylacine)
  LibExtraTip, v5.12.DEV.423(/embedded)
  MasterPlanA, vA
  Pawn, v2.2.13
  SellJunk, v3.0.15
  SexyMap, vv7.3.0
  Skada, v1.7.2
  SlideBar, v7.4.5714 (TasmanianThylacine)
  Stubby, v7.4.5714 (TasmanianThylacine)
  TidyPlates, v6.18.11
  TidyPlatesGraphite, v
  TidyPlatesGrey, v
  TidyPlatesNeon, v
  TidyPlatesQuatre, v
  TidyPlatesHub, v
  TidyPlatesWidgets, v
  TipHelper, v5.12.DEV.405(/embedded)
  WorldQuestTracker, v
  BlizRuntimeLib_enUS v7.3.0.70300 <none>
  (ck=bb2)

**Comment by Torsin** [comment]
Did you try downloading the following zipped up fix for this from the Project Issue #585:

[Bagnon_73_Ready.zip](https://github.com/tullamods/Bagnon/files/1264452/Bagnon_73_Ready.zip)

**Comment by secondfry** [comment]
Or use https://wow.curseforge.com/projects/playsound-temporal-fix to fix it for all addons (read description tho).

**Comment by ablomberg** [comment]
Zip file worked for me. I wonder why minion doesn't have the fix yet, though...
