### ISSUE TITLE
7.3 Not working

### ISSUE THREAD

**Issue by Ferrd** [tullamods/Bagnon#603]
Date: 2017-09-01 21:22:48
ID: 1
Error occured in: Global
Count: 1
Message: ...s\Bagnon\external\Wildpants\components\frameBase.lua line 17:
   Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
Debug:
   [C]: PlaySound()
   ...s\Bagnon\external\Wildpants\components\frameBase.lua:17: OnShow()
   ...s\Bagnon\external\Wildpants\components\inventory.lua:12:
      ...s\Bagnon\external\Wildpants\components\inventory.lua:11
   [C]: Show()
   ..\FrameXML\UIParent.lua:2928: ShowUIPanel()
   ...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:54:
      ...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:50
   (tail call): ?
   (tail call): ?
   ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:117: ToggleBackpack()
   [string "TOGGLEBACKPACK"]:1:
      [string "TOGGLEBACKPACK"]:1
Locals:
(*temporary) = "igBackPackOpen"

**Comment by Torsin** [comment]
Did you try downloading the following zipped up fix for this from the Project Issue #585:

[Bagnon_73_Ready.zip](https://github.com/tullamods/Bagnon/files/1264452/Bagnon_73_Ready.zip)

**Comment by secondfry** [comment]
Or use https://wow.curseforge.com/projects/playsound-temporal-fix to fix it for all addons (read description tho).
