### ISSUE TITLE
Void Storage Bug

### ISSUE THREAD

**Issue by Crazy-Shinobi** [tullamods/Bagnon#607]
Thanks for updating, but when I try to go into void storage, it throws this error. 

Date: 2017-09-02 22:06:58
ID: 1
Error occured in: Global
Count: 1
Message: ...s\Bagnon\external\Wildpants\components\frameBase.lua line 16:
   Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
Debug:
   [C]: PlaySound()
   ...s\Bagnon\external\Wildpants\components\frameBase.lua:16:
      ...s\Bagnon\external\Wildpants\components\frameBase.lua:15
   [C]: Show()
   ..\FrameXML\UIParent.lua:2928:
      ..\FrameXML\UIParent.lua:2923
   [C]: ShowUIPanel()
   ...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:54: ShowFrame()
   Bagnon_VoidStorage\main.lua:17: OnOpen()
   Bagnon\main.lua:26: VoidStorage_LoadUI()
   ..\FrameXML\UIParent.lua:1724:
      ..\FrameXML\UIParent.lua:980
   [C]: TurnOrActionStop()
   [string "TURNORACTION"]:4:
      [string "TURNORACTION"]:1
Locals:
(*temporary) = "UI_EtherealWindow_Open"

**Comment by Torsin** [comment]
in Bagnon_VoidStorage\components\frame.lua change lines 15 and 16:

Frame.OpenSound = SOUNDKIT.UI_EtherealWindow_Open
Frame.CloseSound = SOUNDKIT.UI_EtherealWindow_Close

**Comment by Jaliborc** [comment]
Yep, I missed those two. Fixed.
