### ISSUE TITLE
All works except for Guild Bank 

### ISSUE THREAD

**Issue by Elle110** [tullamods/Bagnon#608]
Soooooo so happy that you updated Bagnon, I love this addon. I have done the recent updates and I am having issues with the Guild Bank not popping up when I click it. 
I think this is the error it came up with. So I copy/paste it below. I am not sure how to fix this. For now I have disabled the Bagnon Guild Bank plugin, I think they're plugins, you know when you know on the left the Addon button before you log a toon, and you can enable/disable certain addons. I can at least see the guild bank like that, but it is not anywhere near as pleasant as Bagnon.
I am running Windows 10 by the way. 
Look forward to hearing any suggestions you could make. 
Kind regards, 
Elle110

Date: 2017-09-03 17:31:03
ID: 6
Error occured in: Global
Count: 1
Message: ...s\Bagnon\external\Wildpants\components\frameBase.lua line 21:
   Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
Debug:
   [C]: ?
   [C]: PlaySound()
   ...s\Bagnon\external\Wildpants\components\frameBase.lua:21: OnHide()
   ...terface\AddOns\Bagnon_GuildBank\components\frame.lua:51:
      ...terface\AddOns\Bagnon_GuildBank\components\frame.lua:50
   [C]: Hide()
   ..\FrameXML\UIParent.lua:3092:
      ..\FrameXML\UIParent.lua:3087
   [C]: securecall()
   ..\FrameXML\UIParent.lua:3130: CloseWindows()
   ..\FrameXML\UIParent.lua:3158:
      ..\FrameXML\UIParent.lua:3148
   [C]: securecall()
   ..\FrameXML\UIParent.lua:3771: ToggleGameMenu()
   [string "TOGGLEGAMEMENU"]:1:

**Comment by SirFuxxi** [comment]
Change Lines 14 and 15 in \Bagnon_GuildBank\components\frame.lua into the following:

Frame.CloseSound = SOUNDKIT.UI_GuildVaultClose
Frame.OpenSound =  SOUNDKIT.UI_GuildVaultOpen

**Comment by SirFuxxi** [comment]
As i had to fix 2 frame.lua files in the Guildbank and voidstorage part, i like to provide the 2 modified files (until a new update of Bagnon is released).

Hope, it helps.

[bagnon_fixed_files.zip](https://github.com/tullamods/Bagnon/files/1272867/bagnon_fixed_files.zip)

**Comment by Elle110** [comment]
Yes I it works now thank you.Much appreciated



Sent from my Samsung device

-------- Original message --------
