### ISSUE TITLE
guild banks will not open

### ISSUE THREAD

**Issue by nickbus60** [tullamods/Bagnon#610]
i go to my guild bank will not open

**Comment by YuryGerman** [comment]
The same issue

Message: ...s\Bagnon\external\Wildpants\components\frameBase.lua:16: Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
Time: 09/04/17 12:56:38
Count: 2
Stack: ...s\Bagnon\external\Wildpants\components\frameBase.lua:16: Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
...rface\AddOns\TradeSkillMaster\Debug\ErrorHandler.lua:317: in function <...rface\AddOns\TradeSkillMaster\Debug\ErrorHandler.lua:300>
[C]: ?
[C]: in function `PlaySound'
...s\Bagnon\external\Wildpants\components\frameBase.lua:16: in function <...s\Bagnon\external\Wildpants\components\frameBase.lua:15>
[C]: in function `Show'
Interface\FrameXML\UIParent.lua:2928: in function `ShowUIPanel'
...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:54: in function `ShowFrame'
Interface\AddOns\Bagnon_GuildBank\main.lua:16: in function `OnOpen'
Interface\AddOns\Bagnon\main.lua:26: in function `GuildBankFrame_LoadUI'
Interface\FrameXML\UIParent.lua:1620: in function <Interface\FrameXML\UIParent.lua:980>

Locals: errMsg = "...s\Bagnon\external\Wildpants\components\frameBase.lua:16: Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])"
isTSMError = false
tsmErrMsg = nil
AceGUI = <table> {
 objPools = <table> {
 }
 RegisterAsContainer = <function> defined @Interface\AddOns\AskMrRobot\Libs\AceGUI-3.0\AceGUI-3.0.lua:521
 RegisterWidgetType = <function> defined @Interface\AddOns\AskMrRobot\Libs\AceGUI-3.0\AceGUI-3.0.lua:559
 WidgetBase = <table> {
 }
 RegisterAsWidget = <function> defined @Interface\AddOns\AskMrRobot\Libs\AceGUI-3.0\AceGUI-3.0.lua:537
 counts = <table> {
 }
 LayoutRegistry = <table> {
 }
 GetLayout = <function> defined @Interface\AddOns\AskMrRobot\Libs\AceGUI-3.0\AceGUI-3.0.lua:583
 GetWidgetVersion = <function> defined @Interface\AddOns\AskMrRobot\Libs\AceGUI-3.0\AceGUI-3.0.lua:613
 Create = <function> defined @Interface\AddOns\AskMrRobot\Libs\AceGUI-3.0\AceGUI-3.0.lua:172
 GetWidgetCount = <function> defined @Interface\AddOns\AskMrRobot\Libs\AceGUI-3.0\AceGUI-3.0.lua:607
 GetNextWidgetNum = <function> defined @Interface\AddOns\AskMrRobot\Libs\AceGUI-3.0\AceGUI-3.0.lua:596
 WidgetRegistry = <table> {
 }
 WidgetVersions = <table> {
 }
 RegisterLayout = <function> defined @Interface\AddOns\AskMrRobot\Libs\AceGUI-3.0\AceGUI-3.0.lua:573
 Release = <function> defined @Interface\AddOns\AskMrRobot\Libs\AceGUI-3.0\AceGUI-3.0.lua:206
 ClearFocus = <function> defined @Interface\AddOns\AskMrRobot\Libs\AceGUI-3.0\AceGUI-3.0.lua:257
 WidgetContainerBase = <table> {
 }
 SetFocus = <function> defined @Interface\AddOns\AskMrRobot\Libs\AceGUI-3.0\AceGUI-3.0.lua:247
}
TSM = <table> {
 Operations = <table> {
 }
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\AskMrRobot\Libs\AceAddon-3.0\AceAddon-3.0.lua:398
 _author = "Sapu94, Bart39"
 DeleteCustomPriceSource = <function> defined @Interface\AddOns\TradeSkillMaster\CoreAPI\Prices.lua:56
 EnableModule = <function> defined @Interface\AddOns\AskMrRobot\Libs\AceAddon-3.0\AceAddon-3.0.lua:363
 modules = <table> {
 }
 baseName = "TradeSkillMaster"
 IterateEmbeds = <function> defined @Interface\AddOns\AskMrRobot\Libs\AceAddon-3.0\AceAddon-3.0.lua:473
 CreateGroupTree = <function> defined @Interface\AddOns\TradeSkillMaster\GUI\TSMFrames\GroupTree.lua:291
 SecureHookScript = <function> defined @Interface\AddOns\BattlePetCount\Libs\AceHook-3.0\AceHook-3.0.lua:410
 GetAuctionPlayer = <function> defined @Interface\AddOns\TradeSkillMaster\GUI\AuctionFrame.lua:45
 RawHookScript = <function> defined @Interface\AddOns\BattlePetCount\Libs\AceHook-3.0\AceHook-3.0.lua:395
 _desc = "Core addon for the TradeSkillMaster suite. Does nothing without modules installed."
 Printf = <function> defined @Interface\AddOns\TradeSkillMaster\CoreAPI\Modules.lua:147
 SetDefaultModulePrototype = <function> defined @Interfa

**Comment by SaraDragon** [comment]
Same thing is happening to me as well.
