### ISSUE TITLE
Bag List -button doesn't hide

### ISSUE THREAD

**Issue by Qessu** [tullamods/Bagnon#621]
Frame Settings - Display - Bag List, toggle doesn't hide the bag icon. All other options work.

**Comment by Tuller** [comment]
This one is probably a typo.

[Bagnon](https://github.com/tullamods/Bagnon/blob/master/components/frame.lua#L152)
```lua
function Frame:HasBagToggle()
    return self.profile.bagToggle
end
```
[Wildpants Config](https://github.com/tullamods/Wildpants_Config/blob/master/panels.lua#L72)
```lua
if self.frameID ~= 'guild' then
    row:CreateCheck('bagFrame')
    row:CreateCheck('sort')
end
```

**Comment by Jaliborc** [comment]
Yup. Fixed
