### ISSUE TITLE
Special AP item color or sort option?

### ISSUE THREAD

**Issue by Kairiste** [tullamods/Bagnon#628]
Forgive me if I am simply too old to know that this is an easy option already, but I would love a way to be able to sort any item that gives my toons an AP boost easily, whether it's by assigning the background or outline a special color, or being able to sort the bag quickly to pull them all to the top or bottom.  I find it can get fussy when I'm trying to run through dailies and dungeons, and clearing out my bags of sellable items I might randomly find a nice AP boost that would have been helpful before.

**Comment by Torsin** [comment]
Why not use an addon for AP, I use ArtifactPowerUser which adds a clickable button that you move around in wow of your AP tokens.  Allowing you to simply click the button and then if you have an additional AP token it will switch to that until all your tokens are used up.

**Comment by Kairiste** [comment]
I ended up installing that addon exactly, but all things considered I'd
prefer to use less addons - less chances for things to screw up that I have
to turn off individually to find out which one's causing the problem.

**Comment by voidzone** [comment]
Can search for `tt:power` which will display all AP items

**Comment by Jaliborc** [comment]
Added ability to search for "artifact" and "azerite"
