### ISSUE TITLE
How do i remove these from Bagnon

### ISSUE THREAD

**Issue by Quelana** [tullamods/Bagnon#629]
How do i remove these small bag icons from my screen? They are super annoying http://prntscr.com/hlm3xi

**Comment by ColossusTS** [comment]
there's a little bag image abive it that you can click on to hide them

**Comment by Jaliborc** [comment]
Those icons do not appear to come from Bagnon. It looks like you are using some addon that allows you to move the inventory container slots from the bottom menu around.
