### ISSUE TITLE
Cannot open bags in combat

### ISSUE THREAD

**Issue by Wolf-DK** [tullamods/Bagnon#631]
I know it seems silly, but I had a need, and since it has now been an issue I have seen for some time, I guess it is time to report it.

if I am Attacked and goes into Combat, the bag closes, but I am unable to open it again and it gives the following error message:

`Message: [ADDON_ACTION_BLOCKED] AddOn 'Bagnon' tried to call the protected function 'BagnonFrameinventory:Show()'.
Time: 12/27/17 23:39:01
Count: 1
Stack: [ADDON_ACTION_BLOCKED] AddOn 'Bagnon' tried to call the protected function 'BagnonFrameinventory:Show()'.
...face\AddOns\Decursive\Libs\BugGrabber\BugGrabber.lua:573: in function <...face\AddOns\Decursive\Libs\BugGrabber\BugGrabber.lua:573>
[C]: in function `Show'
Interface\FrameXML\UIParent.lua:2943: in function `ShowUIPanel'
...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:54: in function <...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:50>
(tail call): ?
(tail call): ?
...s\Bagnon\external\Wildpants\features\autoDisplay.lua:117: in function `ToggleBackpack'
[string "TOGGLEBACKPACK"]:1: in function <[string "TOGGLEBACKPACK"]:1>

Locals: <none>`

Thanks for this, I like it better than the alternatives.
Regards
Prez@Draenor

**Comment by Tuller** [comment]
I think this one was probably fixed by 8.1
