### ISSUE TITLE
As a user, I'd like the ability to search for all items iLvl <### (or >###)

### ISSUE THREAD

**Issue by ablomberg** [tullamods/Bagnon#632]
Context: I do a lot of old-world content. But, I also off-heal and thus have a bag full of gear. When selling/mailing, I take most advantage of the search functionality to empty my bags quickly.

Problem to Solve: It's difficult to tell which gear items in my bag are trash/DE loot items without examining the iLvl of every piece of gear. 

Observed: Currently, I can type in each individual iLvl, but this is time-consuming. If you try to search for items level '80', you also often get anything that includes '80', such as '880'.

Desired: I would most like to type in '<800' in the search bar and have it highlight only items with item levels that are lower than 800. It may be useful for others to be able to search for greater than.

**Comment by Jaliborc** [comment]
You can do that already. You can even specify whether you are searching based on item level or required level, by typing either "l: <###" or "r: <###".

**Comment by Jaliborc** [comment]
Now, the behavior that typing "< 800" is also showing items with item level 880 is definitively a bug.
