### ISSUE TITLE
The new 7.3.3 beta seems to break all overlay add-ons

### ISSUE THREAD

**Issue by raysmith59** [tullamods/Bagnon#633]
It appears some core functionality has changed that's incompatible with every add-on I have that can overlay Bagnon, including (but maybe not limited to):

* ItemLevelDisplay
* Caerdron Bagnon
* Bagnon iLvl
* Bagnon Artifact Power
* Bagnon BoE

**Comment by Jaliborc** [comment]
Bagnon changed how it represents items internally. These mods will have to be updated to work again with Bagnon. The change is minimal though, so shouldn't be hard to make.

I'm adding a "legacy" trick in the next version, which should make a lot of them work without the need to update.
