### ISSUE TITLE
Wildpants\core\classes.lua:12: Cannot find a library instance of "LibItemCache-1.1". [C]: in function `error'

### ISSUE THREAD

**Issue by Thrumbar** [tullamods/Bagnon#634]
2x ...ceBagnon\external\Wildpants\core\classes.lua:12: Cannot find a library instance of "LibItemCache-1.1".
[C]: in function `error'
Ailo\Libs\LibStub\LibStub.lua:38: in function `LibStub'
...ceBagnon\external\Wildpants\core\classes.lua:12: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "LibItemCache-1.1"."

**Comment by Jaliborc** [comment]
Not the latest development version. If you updated recently, you probably did while the game was running.
