### ISSUE TITLE
.ldpants\libs\LibItemSearch-1.2\LibItemSearch-1.2-14.lua:172: attempt to index local 'link' (a number value)

### ISSUE THREAD

**Issue by Thrumbar** [tullamods/Bagnon#644]
2x ...ldpants\libs\LibItemSearch-1.2\LibItemSearch-1.2-14.lua:172: attempt to index local 'link' (a number value)
...ldpants\libs\LibItemSearch-1.2\LibItemSearch-1.2-14.lua:172: in function `match'
...ldpants\libs\LibItemSearch-1.2\LibItemSearch-1.2-14.lua:27: in function `TooltipPhrase'
Bagnon\external\Wildpants\components\item.lua:149: in function <Bagnon\external\Wildpants\components\item.lua:146>

Locals:
self = <table> {
 keywords = <table> {
 }
 canSearch = <function> defined @Bagnon\external\Wildpants\libs\LibItemSearch-1.2\LibItemSearch-1.2.lua:167
 cache = <table> {
 }
 match = <function> defined @Bagnon\external\Wildpants\libs\LibItemSearch-1.2\LibItemSearch-1.2.lua:171
}
link = 115506
_ = nil
search = "Crafting Reagent"
(*temporary) = nil
(*temporary) = 115506
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'link' (a number value)"
scanner = LibItemSearchTooltipScanner {
 0 = <userdata>
 updateTooltip = 0.2
 needsReset = true
}

**Comment by Jaliborc** [comment]
Thank you. Found the issue and fixed in development code. Will release soon.
