### ISSUE TITLE
Latest update of Bagnon not working at all

### ISSUE THREAD

**Issue by Mathazar** [tullamods/Bagnon#645]
I updated Bagnon from WowMatrix this morning to version 7.3.3 on 1/11/18.  My bags and bank will not open.
Following is the Lua error:

Message: ...ace\AddOns\Bagnon\external\Wildpants\core\owners.lua:27: attempt to index global 'player' (a nil value)
Time: 01/11/18 08:08:20
Count: 1
Stack: ...ace\AddOns\Bagnon\external\Wildpants\core\owners.lua:27: attempt to index global 'player' (a nil value)
[C]: ?
...ace\AddOns\Bagnon\external\Wildpants\core\owners.lua:27: in function `GetOwnerIcon'
Interface\AddOns\Bagnon\components\ownerSelector.lua:61: in function `Update'
Interface\AddOns\Bagnon\components\ownerSelector.lua:21: in function `New'
Interface\AddOns\Bagnon\components\frame.lua:160: in function `CreateOwnerSelector'
Interface\AddOns\Bagnon\components\frame.lua:127: in function `ListMenuButtons'
Interface\AddOns\Bagnon\components\frame.lua:110: in function `PlaceMenuButtons'
Interface\AddOns\Bagnon\components\frame.lua:75: in function `Layout'
Interface\AddOns\Bagnon\components\frame.lua:60: in function `Update'
Interface\AddOns\Bagnon\components\frame.lua:51: in function `RegisterMessages'
...s\Bagnon\external\Wildpants\components\frameBase.lua:18: in function `OnShow'
...s\Bagnon\external\Wildpants\components\inventory.lua:12: in function <...s\Bagnon\external\Wildpants\components\inventory.lua:11>
[C]: in function `Show'
Interface\FrameXML\UIParent.lua:2943: in function `ShowUIPanel'
...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:54: in function <...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:50>
(tail call): ?
(tail call): ?
...s\Bagnon\external\Wildpants\features\autoDisplay.lua:113: in function `ToggleBackpack'
[string "TOGGLEBACKPACK"]:1: in function <[string "TOGGLEBACKPACK"]:1>

**Comment by Mathazar** [comment]
bank and bags open on a different toon, (same computer, same realm, different class).  There is a new Lua error:

Message: ...ace\AddOns\Bagnon\external\Wildpants\core\owners.lua:27: attempt to index global 'player' (a nil value)
Time: 01/11/18 08:31:10
Count: 5
Stack: ...ace\AddOns\Bagnon\external\Wildpants\core\owners.lua:27: attempt to index global 'player' (a nil value)
[C]: ?
...ace\AddOns\Bagnon\external\Wildpants\core\owners.lua:27: in function `GetOwnerIcon'
...Bagnon\external\Wildpants\features\tooltipCounts.lua:115: in function <...Bagnon\external\Wildpants\features\tooltipCounts.lua:57>
...Bagnon\external\Wildpants\features\tooltipCounts.lua:135: in function <...Bagnon\external\Wildpants\features\tooltipCounts.lua:132>
[C]: ?
[C]: ?
[C]: ?
...AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:408: in function <...AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:402>
[C]: in function `SetBagItem'
Interface\FrameXML\ContainerFrame.lua:1149: in function `ContainerFrameItemButton_OnEnter'
...AddOns\Bagnon\external\Wildpants\components\item.lua:399: in function `ShowTooltip'
...AddOns\Bagnon\external\Wildpants\components\item.lua:209: in function <...AddOns\Bagnon\external\Wildpants\components\item.lua:202>

Locals:

**Comment by Jaliborc** [comment]
Thank you! There was a typo there, fixed in development. Will release soon.

**Comment by Mathazar** [comment]
Just got my freshly minted Bagnon 7.3.6 installed via WoWMatrix.  Thanks for that!  My Bank and bags now open as expected, and no Lua errors!!

However, I am noticing that moving items in and out of the bank is not immediately noticed on the bank side.  I have to close the bank and reopen it to see the adjustments.  Not the end of the world, at least it is functioning again.  Thanks.
