### ISSUE TITLE
Bags/bank of other alts missing?

### ISSUE THREAD

**Issue by Addonman** [tullamods/Bagnon#646]
One of options of bagnon i liked was able to see bag or bank of my alts when i am on my main or vice versa.Now it is missing. Is it bug or it was removed. If it was removed can we have it back if posiable?

**Comment by Jaliborc** [comment]
Please make sure you have BagBrother enabled. Also, try to loggin on those characters again. The cached information might be lost.

**Comment by Addonman** [comment]
Bagbrother was enabled and still this option missing. Firsr icon on top left that gave that is also missing that gave this option.Now i only have options to search,sort and and bagslots icon but not first lets call it char icon wher you could switch chars.

**Comment by Addonman** [comment]
Maybe i forgot to say if its not clear -its latest beta version.

**Comment by Jaliborc** [comment]
This might help:
- Make sure you have "Show Lua Errors" enabled in the interface options.
- Try to login on a different character, and see if the problem persists (data loss).
- Try to disable the other addons, and see if the problem persists (addon interference).

**Comment by Addonman** [comment]
Went on server with some alt chars,dissabled all addons except bagnon .Made sure i have something in bags on them and still same result/no first left char icon (icon with class image ) ,no info on whats in bags on other char ,...
