### ISSUE TITLE
Not working anymore with item count

### ISSUE THREAD

**Issue by Vilogity** [tullamods/Bagnon#647]
Hello

THX for this ADDON
I use 7.3.2 an everything is fine so far.
But now with the new version I see nothing....only the normal Bagnon design, not more, i can set rows, style etc.
I dont see in the inventory the count of Food or any thing else for every Char, also no Gold count, there is a "0".
I delete Cache Folder and in the WTF folder the Bagnon entrys and try again.
Log in again with 2 different Chars an see nothing.
got back to Release 7.3.2, and restore my WTF entrys, then I see all "normal" If I have the same Food or Flask on a other char inkl. how mutch etc.... ?!
I use German Client and the 64 Bit Version.

**Comment by Jaliborc** [comment]
Duplicate, working on it
