### ISSUE TITLE
Deleting an obsolete item count

### ISSUE THREAD

**Issue by zulence** [tullamods/Bagnon#649]
Hello! I had recently changed appearance (and renamed) one of my characters. And the item count now displays number of items that were remaining on previous-named character + the correct count on newly-renamed character.
![image](https://user-images.githubusercontent.com/35479298/34972879-72a4a50e-fabf-11e7-89cc-59f6aa7c1e1d.png)
How can i get rid of the count without reinstalling my addon?

**Comment by Jaliborc** [comment]
Theres an option to delete character data
