### ISSUE TITLE
7.3.6: Bagnon tooltips no longer working with BagBrother

### ISSUE THREAD

**Issue by jcadduono** [tullamods/Bagnon#650]
Bagnon is showing my total gold across characters at 0 copper and hovering over items does not show quantities anymore.
I deleted the .lua/bak files from WTF folder regarding Bagnon and Bagbrother and started fresh and still have the issue.
BagBrother is recording items and gold just fine if I look at `BagBrother.lua` in my SavedVariables. Bagnon just appears to be unable to interact with the information now.
Unsure how to debug beyond this.

**Comment by Jaliborc** [comment]
Duplicate
