### ISSUE TITLE
Item count + Bagbrother not working on certain realms

### ISSUE THREAD

**Issue by Eviloverlord1989** [tullamods/Bagnon#653]
All 5 Bagnon addons active on every char, yet on certain realms, Item count and Bagbrother/Character list refuse to work?

Have tried deleting the addon and all character settings twice now: relogging all my chars on realm A makes everything work as normal, on realm B the issue remains.

No character specific settings.

**Comment by Jaliborc** [comment]
Which are the names of these servers? Might be an issue there.

**Comment by Eviloverlord1989** [comment]
Works on Kilrogg EU
Doesn't work on Azjol-Nerub EU
Could be the - that's the issue i guess?

**Comment by Jaliborc** [comment]
Yup, that's what I think. I'll create a couple of characters there and  
test it out.

**Comment by jcadduono** [comment]
Yup explains my issue too. Works on Arthas but not Mal'Ganis (with the ' breaking it I assume)

**Comment by Jaliborc** [comment]
Found the problem. The wow api providing the connected realm name is doing weird things. Fixed it (at least on azjol and quel'thalas)

**Comment by Snibb** [comment]
Hi,
could this still be a problem ? 
I'm on "Der Rat von Dalaran" (EU) and i don't have any item count in my tool tip. I disabled all addons except the bagnon ones but that didn't change anything.
 "Tooltip Item Count" in the bagnon settings is enabled.
The bagnon version is 8.0.2.

**Comment by lukasturcani** [comment]
Same here, works on Ghostlands (EU) but not on Draenor (EU).
