### ISSUE TITLE
No Item Count no Funktion V 7.38

### ISSUE THREAD

**Issue by Vilogity** [tullamods/Bagnon#654]
Hello 
I testet the last Release if this fix my Problem.
Ich delete WoW Cache Folder and WTF entrys of Bagnon and install V 7.38.
Same Problem as before..... No Item Count, total Money "0" and dont see If i have the same Items 
on my Bank or an other Char.
I take a look in the bagbrother.lua and see the Name of my Server and the 2 Char entrys I testet, this looks like in 7.32 but see nothing of this enrys Ingame. 
 

sry..... :-(

**Comment by bobic123** [comment]
Same here, total Money "0" on all chars, it was so usefull with multiple alts, please fix it:(

**Comment by jcadduono** [comment]
yeah the latest commit regarding this didn't do anything for my server Mal'Ganis either

**Comment by Razariel** [comment]
faction related perhaps ? item counts havent worked for my alli chars on Lightbringer with any of the beta versions, but surprisingly they work for my horde chars on Fizzcrank

**Comment by Jaliborc** [comment]
Can you type "/dump GetAutoCompleteRealms()" in chat and post here the result?

**Comment by jcadduono** [comment]
it's an empty table (because my realm isn't connected to any others)
GetRealmName() == "Mal'Ganis"

**Comment by Jaliborc** [comment]
@jcadduono, yes I am aware of the empty table scenario and its already fixed internally. I just want to make sure everyone is having that problem, and not an additional one.

**Comment by Razariel** [comment]
also empty for me

Dump: value=GetAutoCompleteRealms()
[1]={
}

**Comment by Vilogity** [comment]
7.38 /  1 Char on Blackand EUR
I get this after enter /dump GetAutoCompleteRealms()


Dump: value=GetAutoCompleteRealms()
[1]={
}

**Comment by bobic123** [comment]
Silvermoon EU ally

I get this after enter /dump GetAutoCompleteRealms()

Dump: value=GetAutoCompleteRealms()
[1]={
}

**Comment by Vilogity** [comment]
Testet 7.39 and it works for me :-)

**Comment by Jaliborc** [comment]
Anyone still with the issue?
