### ISSUE TITLE
Bank Bags

### ISSUE THREAD

**Issue by harvestmeadow** [tullamods/Bagnon#656]
I may be retarded so please let me know if this is user error.

My husband and I both have this program and he is able to peek into his bank bags while out questing.  When I looked up how to do this I noticed that I don't have the General Settings tab like he does.  I have Frame Settins, Automatic Display, color Settings and Item Rulesets (he doens't have).  Am I missing part of the download? or a necessary addon to enable this?  Or am I just retarded?  Thanks for all the help.

I have added a picture so you can see what I see...I am on the left...the right is a tutorial that has a screen like my husband.

![bagnon](https://user-images.githubusercontent.com/35847215/35453368-8ff35dc6-028f-11e8-89e4-91dceca5b123.jpg)

**Comment by Jaliborc** [comment]
You are using different versions. The one on the right is the current look of the options, the one on the left is very outdated (like 1 or 2 years).
