### ISSUE TITLE
Improper recognition of Allied Races.

### ISSUE THREAD

**Issue by EveryUsernameTaken** [tullamods/Bagnon#658]
Race icons next to characters in item tooltips display a flickering green square when the character is an Allied Race. The addon should be updated with the newer iconography and race IDs.

**Comment by Jaliborc** [comment]
Yes, the problem is I couldn't find yet information on what these IDs are.
I also need to find ingame icons for each one of these races.

@EveryUsernameTaken Can you type "/dump select(2, UnitRace('player'))" in chat while logged in your allied race characters and tell me the result?

**Comment by voidzone** [comment]
```
Dump: value=select(2, UnitRace('player'))
[1]="VoidElf"
```

**Comment by EveryUsernameTaken** [comment]
```
Dump: value=select(2, UnitRace('player'))
[1]="HighmountainTauren"
```

![screen shot 2018-02-03 at 7 31 33 pm](https://user-images.githubusercontent.com/36040085/35766315-4cfab3ee-0919-11e8-89ca-2b242907bf74.png)

**Comment by MisterUIltimo** [comment]
Not experienced in Lua at all but found a fix by looking through all lua files and learning by doing.
This is for Version 7.3.2.
Open \Interface\Bagnon\external\Wildpants\core\players.lua
Look in line 19 for 
`if race ~= 'Worgen' and race ~= 'Goblin' and (race ~= 'Pandaren' or sex == 'Female') then` 
and change to 
`if race ~= 'Worgen' and race ~= 'Goblin' and (race ~= 'Pandaren' or sex == 'Female') and race ~= 'VoidElf' and race ~= 'LightforgedDraenei' and race ~= 'Nightborne' and race ~= 'HighmountainTauren' then`
Works for me. Thanks to voidzone for dumping the 4 race values.
This should work for Version 7.3.9,too. (Not Tested) 
Note that in 7.3.9 the players.lua is now named owners.lua. (Line 27 in owners.lua)

**Comment by Jaliborc** [comment]
Ohhh, that means they have those "not as good" textures for the allied races. Thank you. I'll change that (can't do today, will do tomorrow)

**Comment by aceofrogues** [comment]
Seems to work with 7.3.9

**Comment by voidzone** [comment]
This appears to have been reverted in 8.0.0b
