### ISSUE TITLE
Bagnon not working on Blade's Edge

### ISSUE THREAD

**Issue by Badpull** [tullamods/Bagnon#659]
I have ally toons on both Thunderhorn and Blade's Edge.  Bagnon works fine on Thunderhorn, but not Blade's Edge.  Both are connected servers.

Any fixes?

Thanks,

Badpull

**Comment by Jaliborc** [comment]
Please tell me what shows up in chat when you type "/dump GetAutoCompleteRealms()" while logged in Blade's Edge

**Comment by Badpull** [comment]
I get the following:


[1] =(
   [1] = "Thunderhorn",
   [2] = "Blade'sEdge" (Yes, there is no space in Blade'sEdge as printed on my screen)
}





/dump GetAutoCompleteRealms()




-----Original Message-----

**Comment by Jaliborc** [comment]
Ok, that's the issue. Goddamit Blizzard

**Comment by Badpull** [comment]
Do I need to do anything from my end?



-----Original Message-----

**Comment by Jaliborc** [comment]
It should be working with the version I released yesterday. I created a character on that server and its working.

**Comment by Badpull** [comment]
I had to delete my old version from WOW matrix and download the new one.


It is working now.


Thanks.



-----Original Message-----
