### ISSUE TITLE
Ignoring "Include Guild Banks" option

### ISSUE THREAD

**Issue by leandrodcarvalho** [tullamods/Bagnon#661]
Even if the "Include Guild Banks" option is unchecked, the interface keeps showing Guild information on items that are also in the bag.

**Comment by Jaliborc** [comment]
It's working for me... that's weird.

**Comment by Jaliborc** [comment]
Wait, what version are you running?

**Comment by leandrodcarvalho** [comment]
7.3.2
[image: Imagem inline 1]


[image: Imagem inline 2]

Include Guild Banks is unchecked, but still showing the Guild information.


Leandro Diniz

2018-02-07 17:44 GMT-02:00 João Cardoso <notifications@github.com>:

**Comment by Jaliborc** [comment]
Ahh, ok. More recent versions dont have that issue
