### ISSUE TITLE
Allied race portraits

### ISSUE THREAD

**Issue by The-Optimist** [tullamods/Bagnon#675]
Allied race character portraits currently show up as a blank box on the character list. 

Not an incredibly important issue, and it's one I'm sure you're already working on, but it has been nearly a month since allied races were released.

**Comment by telcus** [comment]
I managed to fix this by modifying players.lua in external/Wildpants/core/ to use the same icon selection as worgen, goblin and male pandaren

Line 19 was:
`	if race ~= 'Worgen' and race ~= 'Goblin' and (race ~= 'Pandaren' or sex == 'Female') then`

Changed to
`	if race ~= 'Worgen' and race ~= 'Goblin' and (race ~= 'Pandaren' or sex == 'Female') and race ~= 'VoidElf' and race ~= 'LightforgedDraenei' and race ~= 'HighmountainTauren' and race ~= 'Nightborne' then`
