### ISSUE TITLE
Set Focus Frame Blocking

### ISSUE THREAD

**Issue by sKMobbin** [tullamods/Bagnon#678]
Been having a new issue with my Bagnon addon, which is currently updated to the latest version available being 7.3.2, blocking my In-Game ability to select a focus target. I do use Z-Perl Unit Frames. During Mythic High Command this last Tuesday, 3/6/18, I started getting error messages from wow saying Bagnon was interfering with this action and I could either Ignore or Disable the addon and reload UI. Of coarse this happens with some addons every now and then most simply requiring UI reloads to fix. This issue with Bagnon hasn't been solvable using the same methods. Nor restarting my Warcraft client completely. Still cant set a focus target at the moment, and I really like using Bagnon so I thought I'd bring this issue here.

Thanks.

**Comment by Tuller** [comment]
This was probably fixed with 8.1
