### ISSUE TITLE
Bagnon_GuildBank\components\item.lua:44: attempt to call method 'IsLocked' (a nil value)

### ISSUE THREAD

**Issue by Thrumbar** [tullamods/Bagnon#679]
2x Bagnon_GuildBank\components\item.lua:44: attempt to call method 'IsLocked' (a nil value)
Bagnon_GuildBank\components\item.lua:44: in function <Bagnon_GuildBank\components\item.lua:38>

Locals:
self = Bagnon_GuildBankItemSlot58 {
 0 = <userdata>
 bag = 1
 BattlepayItemTexture = <unnamed> {
 }
 BagStaticTop = <unnamed> {
 }
 Flash = <unnamed> {
 }
 OrigItemLink = "|cffffffff|Hitem:124119::::::::110:253::::::|h[Big Gamy Ribs]|h|r"
 IconBorder = <unnamed> {
 }
 newitemglowAnim = <unnamed> {
 }
 icon = Bagnon_GuildBankItemSlot58IconTexture {
 }
 ExtendedOverlay = <unnamed> {
 }
 UpgradeIcon = <unnamed> {
 }
 QuestBorder = Bagnon_GuildBankItemSlot58IconQuestTexture {
 }
 Cooldown = Bagnon_GuildBankItemSlot58Cooldown {
 }
 SplitStack = <function> defined @FrameXML\ContainerFrame.lua:1046
 BagStaticBottom = <unnamed> {
 }
 flash = <unnamed> {
 }
 scheduledSecondaryUpdate = false
 ExtendedSlot = <unnamed> {
 }
 ExtendedOverlay2 = <unnamed> {
 }
 hasItem = true
 JunkIcon = <unnamed> {
 }
 OrigItemEquipSlot = ""
 OrigItemClass = "Tradeskill"
 OrigItemQuality = 1
 timeSinceUpgradeCheck = 0
 OrigItemLevel = ""
 Border = <unnamed> {
 }
 count = 47
 ItemLevelFrame = <unnamed> {
 }
 Count = Bagnon_GuildBankItemSlot58Count {
 }
 flashAnim = <unnamed> {
 }
 info = <table> {
 }
 searchOverlay = Bagnon_GuildBankItemSlot58SearchOverlay {
 }
 frame = BagnonFrameguild {
 }
 NewItemTexture = <unnamed> {
 }
}
button = "LeftButton"
(*temporary) = nil
(*temporary) = Bagnon_GuildBankItemSlot58 {
 0 = <userdata>
 bag = 1
 BattlepayItemTexture = <unnamed> {
 }
 BagStaticTop = <unnamed> {
 }
 Flash = <unnamed> {
 }
 OrigItemLink = "|cffffffff|Hitem:124119::::::::110:253::::::|h[Big Gamy Ribs]|h|r"
 IconBorder = <unnamed> {
 }
 newitemglowAnim = <unnamed> {
 }
 icon = Bagnon_GuildBankItemSlot58IconTexture {
 }
 ExtendedOverlay = <unnamed> {
 }
 UpgradeIcon = <unnamed> {
 }
 QuestBorder = Bagnon_GuildBankItemSlot58IconQuestTexture {
 }
 Cooldown = Bagnon_GuildBankItemSlot58Cooldown {
 }
 SplitStack = <function> defined @FrameXML\ContainerFrame.lua:1046
 BagStaticBottom = <unnamed> {
 }
 flash = <unnamed> {
 }
 scheduledSecondaryUpdate = false
 ExtendedSlot = <unnamed> {
 }
 ExtendedOverlay2 = <unnamed> {
 }
 hasItem = true
 JunkIcon = <unnamed> {
 }
 OrigItemEquipSlot = ""
 OrigItemClass = "Tradeskill"
 OrigItemQuality = 1
 timeSinceUpgradeCheck = 0
 OrigItemLevel = ""
 Border = <unnamed> {
 }
 count = 47
 ItemLevelFrame = <unnamed> {
 }
 Count = Bagnon_GuildBankItemSlot58Count {
 }
 flashAnim = <unnamed> {
 }
 info = <table> {
 }
 searchOverlay = Bagnon_GuildBankItemSlot58SearchOverlay {
 }
 frame = BagnonFrameguild {
 }
 NewItemTexture = <unnamed> {
 }
}
(*temporary) = "attempt to call method 'IsLocked' (a nil value)"
ItemSlot = <unnamed> {
 0 = <userdata>
 OnEnter = <function> defined @Bagnon_GuildBank\components\item.lua:77
 __super = <unnamed> {
 }
 IsNew = <function> defined @Bagnon_GuildBank\components\item.lua:122
 UpdateCooldown = <function> defined @Bagnon_GuildBank\components\item.lua:108
 GetBlizzard = <function> defined @Bagnon_GuildBank\components\item.lua:29
 OnDragStart = <function> defined @Bagnon_GuildBank\components\item.lua:65
 OnReceiveDrag = <function> defined @Bagnon_GuildBank\components\item.lua:71
 __index = <unnamed> {
 }
 unused = <table> {
 }
 UpdateTooltip = <function> defined @Bagnon_GuildBank\components\item.lua:87
 Create = <function> defined @Bagnon_GuildBank\components\item.lua:15
 GetBag = <function> defined @Bagnon_GuildBank\components\item.lua:117
 UpdatedLocked = <function> defined @Bagnon_GuildBank\components\item.lua:32
 IsQuestItem = <function> defined @Bagnon_GuildBank\components\item.lua:121
 Name = "GuildItemSlot"
 GetSlot = <function> defined @Bagnon_GuildBank\components\item.lua:113
 nextID = 98
 OnClick = <function> defined @Bagnon_GuildBank\components\item.lua:38
 Construct = <function> defined @Bagnon_GuildBank\components\item.lua:25
 SplitStack = <function> defined @Bagnon_GuildBank\components\item.lua:103
}

**Comment by cipher3010** [comment]
In Bagnon_GuildBank\components\item.lua

**change**

	if IsModifiedClick('SPLITSTACK') then
		if not self:IsLocked() then
			self.SplitStack = ItemSlot.SplitStack -- have no idea why is necessary
			OpenStackSplitFrame(select(2, self:GetInfo()), self, 'BOTTOMLEFT', 'TOPLEFT')
		end
		return
	end
**TO**
	if IsModifiedClick('SPLITSTACK') then
		if not self.IsLocked then
		print (select(2, self:GetInfo()))
			self.SplitStack = ItemSlot.SplitStack -- have no idea why is necessary
			OpenStackSplitFrame(self.count, self, 'BOTTOMLEFT', 'TOPLEFT',1)
		end
		return
	end
