### ISSUE TITLE
Error on Loading into 8.0.1

### ISSUE THREAD

**Issue by GeneralRhinox** [tullamods/Bagnon#700]
Message: Error loading Interface\AddOns\Bagnon\external\Wildpants\libs\LibItemCache-1.1\Tests.lua
Time: Wed Jul 18 08:08:30 2018
Count: 7

**Comment by vladimirgluten** [comment]
I get the same "tests.lua" error with BagBuddy.  That .lua file doesn't exist, so is it something new that Blizz is expecting to see?

So far either one hasn't seemed to affect using the addon (no other errors when opening the windows)

**Comment by Tuller** [comment]
It’s a new message on blizzard’s end meant to help developers know if they forgot to include a file
