### ISSUE TITLE
color boxs

### ISSUE THREAD

**Issue by grilor** [tullamods/Bagnon#707]
when selling items the color of the out line of the item still there and I cant get it to go away unless I do a /reloadui

**Comment by pgdagenais** [comment]
You can also move a different quality item over the colored square and mouse over it and it should remove the empty colored square

**Comment by Jaliborc** [comment]
Can you please disable other addons and see if the issue persists? I cannot replicate

**Comment by Jaliborc** [comment]
I see, Tuller uploaded a broken version 5 days ago. Now it makes sense.
