### ISSUE TITLE
Attempt to register unknown event "ENCOUNTER_STOP"

### ISSUE THREAD

**Issue by adreaver** [tullamods/Bagnon#708]
1x ...xternal\Wildpants\libs\AceEvent-3.0\AceEvent-3.0-4.lua:33: Attempt to register unknown event "ENCOUNTER_STOP"
[C]: in function `RegisterEvent'
...xternal\Wildpants\libs\AceEvent-3.0\AceEvent-3.0-4.lua:33: in function `OnUsed'
...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:168: in function `RegisterEvent'

DynamicCam\Core.lua:1069: in function `?'
Chinchilla\Libs\AceTimer-3.0\AceTimer-3.0-17.lua:55: in function <Chinchilla\Libs\AceTimer-3.0\AceTimer-3.0.lua:50>

Locals:
(*temporary) = AceEvent30Frame {
0 = <userdata>
}
(*temporary) = "ENCOUNTER_STOP"

**Comment by adreaver** [comment]
Actually disregard, this is DynamicCam, not Bagnon - I misread the error.

**Comment by Tuller** [comment]
Looks like that one is another addons doing
  

  
  

  
  
>
