### ISSUE TITLE
Rarity outline colors not working.

### ISSUE THREAD

**Issue by LocutusCPlus** [tullamods/Bagnon#710]
The rarity color outline does not work for most items. This might be squish/item level related.

Additionally, when moving an item that the rarity border color does work on, the border color will remain even if the slot is empty.

If you put a different piece of gear in it's place (no matter the rarity), the color will remain.

**Comment by Jaliborc** [comment]
Cannot replicate. Make sure you have Lua Errors enabled and that you have not installed the addon while the game was running

**Comment by Jaliborc** [comment]
I see, Tuller uploaded a broken version 5 days ago. Now it makes sense.
