### ISSUE TITLE
The Guild Bank Not working fully.

### ISSUE THREAD

**Issue by Sharkeeee** [tullamods/Bagnon#713]
Hi,
Great addon ! I'll start with what appears to be working in the wow game. 
Sorry but i dont know programming code.
I'm not getting any in game error script.
The Charr's inventory bag shows with no issue.
The Charrs Bank shows with no issue 
But...what is not working for me ........
The guild bank
Only 1 page of the guild bank shows but with all blank item spaces for items as if empty.
I can move/deposit an item by right clicking from the Charr's inventory to the guild but the item moved dose not display in the blank spaces on the page,
You can not left click or right click to move items from any of the blank spaces that you know contains an item or items to attempt a transfer from the guild bank.
There is no icon visible to change from one bag to another in/on the guild bank page.
 Wishing you a speedy fix.
Sharky.

**Comment by mixMugz** [comment]
Same

**Comment by edrogona** [comment]
NONE of my Guild bank is working
