### ISSUE TITLE
Inventory characters connected realms no longer showing

### ISSUE THREAD

**Issue by Khealon** [tullamods/Bagnon#715]
Hey,

Since the last update this morning (8.0.0), the inventory of my characters on connected realms are no longer showing properly. 

Normally when you mouseover an item in your bag, it would display how many are of that item on your other characters on that realm AND connected realms. (Defias Brotherhood EU and Sporeggar EU in my case). This doesn't work properly.

When I'm on a Defias Brotherhood toon, I can see the bags/inventory of my Sporeggar Toons. That works fine.
But when I'm on a Sporeggar toon, I CAN'T see the inventory of a Defias Brotherhood toon. When you click on the character button the toon names are still showed (see picture) but in white. When you click on them, their inventory is empty.

I already deleted the SavedVariables of BagBrother, but that doesn't help.

Thanks

![schermafbeelding 2018-07-24 om 20 29 47](https://user-images.githubusercontent.com/41647345/43158633-7184cd06-8f80-11e8-8574-a7c699e3fbd3.png)

**Comment by Khealon** [comment]
I reverted back to 7.3.2 and the issue is also there. 
Might be a WoW patch 8.0.1 related issue.

**Comment by Jaliborc** [comment]
I created dummie characters on both servers, and it is working perfectly. Try deleting your data and disabling other addons.
