### ISSUE TITLE
updated bagnon through twitch

### ISSUE THREAD

**Issue by Arwygnn** [tullamods/Bagnon#716]
Updated bagnon through twitch and now my character bags and my bank bags no longer open as one click. Everything was fine before the update though.

**Comment by Rebosar** [comment]
Same issue. Reverting back to 7.3.11 and restarting the game fixed my issue.

**Comment by Arwygnn** [comment]
Ok thanks for letting me know. Ugg I hate new XPacks!!!

**Comment by Jaliborc** [comment]
Restart the game...
