### ISSUE TITLE
Bank showing current items, but not new/moved/removed items.

### ISSUE THREAD

**Issue by koi224** [tullamods/Bagnon#722]
**Describe the bug**
Whenever I open my bank, the items that were already currently in there show, which is normal. The bug comes in whenever I move items into my bank- the game processes that the item has moved from my bag to my guild bank and the item is even gone from my original bag, however it does not appear in any of my bank tabs. Upon exiting then reopening my bank, only then does the item appear. This also occurs when I move items WITHIN the bank- I will move an item around, only to see that the item icon is still in the same place it once was. Again, I exit then reopen the bank, and only then does the item show to be moved around. Lastly, this occurs when I attempt to take items OUT of my bank- the icon of the item I take out remains in the bank, but the game has processed that the item moved, because when I exit and reopen the bank, the item is gone and now appears in my bag.

**To Reproduce**
1. Go to any bank of your faction.
2. Click on the banker NPC.
3. Transfer an item from your bag into the bank -OR- move an item around in your bank -OR- remove an item from your bank into your bag.
4. See that the item does not immediately show in the bank -OR- see that the item's icon has not moved within the bank -OR- see that the item's icon has not moved from the bank into your bag.

**Expected behavior**
I should be able to transfer items into my bank, and immediately see their icon in the bank and see that it has transferred over. I should be able to move items in my bank, and see that the icon of the item has moved. I should be able to remove an item from my bank, and immediately see that the item's icon has transferred over into my bag. This should all happen without me having to exit/reopen my bank or bag in order to see the item's icon.

**Error Logs**
N/A

**Screenshots**
N/A

**Running Software**
 - Game patch 8.0.1
 - Addon version 8.0.0

**Additional context**
This is 100% NOT latency/lag issue according to my system.

**Comment by Fasteddie315** [comment]
Also having the same issue.

**Comment by m3t0034** [comment]
I concur. Bank frame is borked. Hope it isn't a huge rewrite. Welcome Bliz API overlords.

**Comment by Ayrlaine** [comment]
Me too - I deposit things (or withdraw) but can't see them unless I change tabs and then return - or if I leave the bank and then come back in

**Comment by Jaliborc** [comment]
let me know if the issue persists when the new release comes out

**Comment by m3t0034** [comment]
Thank you!
