### ISSUE TITLE
Profession bag coloring system not working for inventory

### ISSUE THREAD

**Issue by Fasteddie315** [tullamods/Bagnon#723]
**Describe the bug**
In the new Release 8.0.0 the coloring system for profession bags isn't working (in your inventory), I've repaired the game, deleted cache, and cleared out my entire wtf folder. Started the game backup with only bagnon installed (in-case of lua errors or other addons interfering) still nothing. I've installed the 7.3.2 (Release) bagnon and the coloring system shows up.

**To Reproduce**
n/a

**Expected behavior**
When a profession bag is equipped it should have a color tint on the empty slots indicating that it's a profession bag slot.

**Error Logs**
n/a (no lua errors)

**Screenshots**
See Attached Files...
Bagnon 7.3.2 (What it's supposed to look like)
![bagnon 7 3 2](https://user-images.githubusercontent.com/8967675/43219475-6af182fa-9015-11e8-9665-174a42647cd4.PNG)
Bagnon 8.0.0
![bagnon 8 0 0](https://user-images.githubusercontent.com/8967675/43219483-6ffb010e-9015-11e8-87dd-3a0b31883c86.PNG)

**Running Software (please complete the following information):**
 - Game patch 8.0.1 (Build 27165)
 - Addon version 8.0.0

**Additional context**
None.

**Comment by Jaliborc** [comment]
Yes, fixed it meanwhile on the development version. Will release soon.
