### ISSUE TITLE
[Feature] Disabling Race Icons

### ISSUE THREAD

**Issue by vreeland** [tullamods/Bagnon#725]
I saw that a couple of us were requesting this amongst the Curse comments, so I'd thought I would go ahead and make a more formal post. Is there any chance that we could get an option to disable/hide the race icons that were show up alongside character names in item tooltips, gold amount, etc? Since they were implemented, hovering over tooltips has caused a minute but noticeable spike in lag. 

![wowscrnshot_072518_115747](https://user-images.githubusercontent.com/41711079/43235328-41117272-9035-11e8-9333-ed3832b15a94.jpg)

Thanks in advance!

**Comment by Jaliborc** [comment]
The spike in lag its unrelated to the icons
