### ISSUE TITLE
BagBrother doesn't work when realm name contains parentheses

### ISSUE THREAD

**Issue by franciscosucena** [tullamods/Bagnon#731]
**Running Software (please complete the following information):**
 - 8.0.1 game version
 - 8.0.0 bagnon version

**Describe the bug**
BagBrother doesn't work properly when the realm name contains parentheses, e.g. "Aggra (Português)".

**Additional context**
The regex doesn't take parentheses into account. Tested it by including the following code in LibItemCache-2.0 (line 26):
> if realm == 'Aggra(Português)' then
>      Realms[i] = 'Aggra (Português)'
> else ...

There's also another bug, not sure if related to this one.
![a](https://user-images.githubusercontent.com/26909076/43534831-37af4ea4-95b0-11e8-8e42-d05b14a1bae7.png)

Aggra and Grim Batol are connected, however the bags show as empty when I try to check them from the other realm (notice there's no icon for for the other realm characters).

edit: the second bug is already known.

**Comment by Pharozz** [comment]
This could be related to the problem that I have (# 726). I am also on the Aggra server.
