### ISSUE TITLE
wildpants problem?

### ISSUE THREAD

**Issue by JimGiordano2** [tullamods/Bagnon#734]
- Game patch [e.g. Build 8.0.1.27178]
 - Addon version 8.0,1 

Just installed latest version.
I get 14 errors upon logging in a character.

This is the first three errors-

Message: ...e\AddOns\Bagnon\external\Wildpants\core\settings.lua:10: Cannot find a library instance of "LibItemCache-2.0".
Time: Fri Aug  3 08:20:37 2018
Count: 1
Stack: ...e\AddOns\Bagnon\external\Wildpants\core\settings.lua:10: Cannot find a library instance of "LibItemCache-2.0".
[C]: in function `error'
...s\Bagnon\external\Wildpants\libs\LibStub\LibStub.lua:23: in function `LibStub'
...e\AddOns\Bagnon\external\Wildpants\core\settings.lua:10: in main chunk

Locals: (*temporary) = "Cannot find a library instance of "LibItemCache-2.0"."

Message: ...rface\AddOns\Bagnon\external\Wildpants\core\bags.lua:7: Cannot find a library instance of "LibItemCache-2.0".
Time: Fri Aug  3 08:20:37 2018
Count: 1
Stack: ...rface\AddOns\Bagnon\external\Wildpants\core\bags.lua:7: Cannot find a library instance of "LibItemCache-2.0".
[C]: in function `error'
...s\Bagnon\external\Wildpants\libs\LibStub\LibStub.lua:23: in function `LibStub'
...rface\AddOns\Bagnon\external\Wildpants\core\bags.lua:7: in main chunk

Locals: (*temporary) = "Cannot find a library instance of "LibItemCache-2.0"."

Message: ...\Bagnon\external\Wildpants\components\moneyFrame.lua:7: Cannot find a library instance of "LibItemCache-2.0".
Time: Fri Aug  3 08:20:37 2018
Count: 1
Stack: ...\Bagnon\external\Wildpants\components\moneyFrame.lua:7: Cannot find a library instance of "LibItemCache-2.0".
[C]: in function `error'
...s\Bagnon\external\Wildpants\libs\LibStub\LibStub.lua:23: in function `LibStub'
...\Bagnon\external\Wildpants\components\moneyFrame.lua:7: in main chunk

Locals: (*temporary) = "Cannot find a library instance of "LibItemCache-2.0"."

**Comment by KyrosKrane** [comment]
I couldn't reproduce the problem, but I think I may have found the source.

Go into the file:

`Bagnon\external\Wildpants\libs\libs.xml`

Line 12 reads:
`
	<Include file="LibItemCache-2.0\LibItemCache-2.0.lua"/>`

Change it to this:
`
	<Script file="LibItemCache-2.0\LibItemCache-2.0.lua"/>`

**Comment by JimGiordano2** [comment]
That seems to have worked.  Thanks much!

**Comment by cogar328** [comment]
Thanks KryosKrane,
that worked!
