### ISSUE TITLE
Search Function not Detecting Keystones

### ISSUE THREAD

**Issue by Brownieslol** [tullamods/Bagnon#735]
When trying to search for "K" - "Key" - "Keystone" - "Keystone:" It does not highlight the keystone at all. 

![bagnon search function not detecting keystones](https://user-images.githubusercontent.com/42072366/43653869-46052b00-96fe-11e8-8476-3b53a8d0a766.jpg)

**Comment by Qessu** [comment]
This is probably related. Double-Click name to search, next to search-button, stopped working as well.

**Comment by Brownieslol** [comment]
@Qessu "This is probably related. Double-Click name to search, next to search-button, stopped working as well."

Yeah I noticed that to, I never used to use that feature before. But I was messing around with it and noticed if you double click then try and search nothing happens.
