### ISSUE TITLE
Bagbrother Race Icon disable?

### ISSUE THREAD

**Issue by XeeLiao** [tullamods/Bagnon#747]
I looking for a way to disable these Race Icons wich are now there with Bagbrother, as an example Gold Count, in front of each Character Name is now a Race Icon.

![1](https://user-images.githubusercontent.com/41451315/43790920-52122942-9a74-11e8-8bff-bd0e737d4eaa.jpg)

Is there a way to remove them personally or maybe an Option to disable them?

**Comment by Jaliborc** [comment]
No, I really like them.
