### ISSUE TITLE
Bagnon not auto-closing properly

### ISSUE THREAD

**Issue by GnuclearGnome** [tullamods/Bagnon#762]
**Running Software (please complete the following information):**
 - Game patch 8.0.1.27366
 - Addon version 8.0.2

Been using Bagnon since I started playing WoW 8 years ago.  Great addon.  However, Bagnon, once set up in Options for auto-opening, has always auto-closed when you left a vendor, closed the Mail interface, etc. where it was selected to auto-open.  Since the release of BfA though it stays open when you close/leave a vendor or the Mail UI, etc. and has to be closed manually.  No errors are being received.

**Comment by simonjonharding** [comment]
I find this issue is intermittent - sometimes it auto closes, at other times it doesn't.

**Comment by Jaliborc** [comment]
Fixed - the settings were not updating correctly. On the live version, the issue should disappear if you reload the interface after messing with Bagnon options.
