### ISSUE TITLE
Bagnon Equipment 2

### ISSUE THREAD

**Issue by Sadzeih** [tullamods/Bagnon#764]
Hi,
I forked the old Bagnon Equipment plugin that didn't work anymore. I just wanted it, so I fixed it myself.

[Repo](https://github.com/Sadzeih/bagnon-equipment2)

If you want to add it to the offical plugins list, that'd be great!
Otherwise, I just wanted to let you know.

**Comment by Jaliborc** [comment]
Anyone can edit the list. Its a wiki. Feel free to add any plugin you develop.
