### ISSUE TITLE
Only horde chars displayed

### ISSUE THREAD

**Issue by Worgenpaw** [tullamods/Bagnon#768]
**Running Software (please complete the following information):**
 - Game patch [e.g. Build 8.0.1.27377]
 - Addon version 8.0.2

**Describe the bug**
By coincidence my horde and alliance servers are linked, so bagbrothers used to show me money, items etc. from both factions. Now, it only shows one faction - and it's only the horde one. Even on my alliance toons, bagbrother will only show me the amount of items and gold my horde chars have, but not my alliance chars, not even the alliance char being played right now.

**To Reproduce**
1. See screenshot?

**Expected behavior**
Either expected to see both factions, or to see the horde item counts/gold while on horde chars, and the alliance item counts /gold while on alliance chars.

**Screenshots**
http://puu.sh/BhB17/a617163cf1.jpg I have this item on several other alliance chars but as you can see, it only shows horde ones.

**Comment by Worgenpaw** [comment]
I also tried resetting the cache by removing bagbrother files from the WTF folder, but it still only shows me the horde characters I logged in, not my alliance chars.

**Comment by Worgenpaw** [comment]
it seems to be an issue with my alliance char specifically (Zirkel des Cenarius), because I checked another server where I have both alliance and horde chars, and there the addon works, shows data from both factions as it should. Help? (

**Comment by Krakken77** [comment]
I also have a similar problem, but it seems to depend on the realm.
On the realm "Confrérie du Thorium" I cannot see my other toons within this realm (neither total of gold).
On another realm "Kirin Tor" I still can see my other toons within this realm and the total of gold.
