### ISSUE TITLE
Multiple character names

### ISSUE THREAD

**Issue by mateo339** [tullamods/Bagnon#772]
**Running Software (please complete the following information):**
 - Game patch [e.g. Build 8.0.1.27404]
 - Addon version 8.0.2

------

I recently changed my character named twice (it got flagged twice), so now when i hover over an item on my bag, it shows all 3 character names. Is there a way to fix this? I still want to be able to see how many items i have in my Bags and Bank. 

![image](https://user-images.githubusercontent.com/42630947/44503730-7df24980-a65d-11e8-8834-2938ceb464a8.png)

**Comment by TrinitysEnd** [comment]
To delete character data, you would want to go to your character icon in the top left of the bag and click on it. It should bring up a menu of other characters. From there, you hover over the respective character you want to delete and right click. One of the options there will be to delete that entry.
