### ISSUE TITLE
Azerite icon decorations hidden

### ISSUE THREAD

**Issue by yseviel** [tullamods/Bagnon#774]
**Running Software (please complete the following information):**
 - Build 8.0.1.27178
 - 8.0.2

**Describe the bug**
Seems to be an issue with multiple bag addons, including Bagnon and Combuctor. The Azerite icon decorations around Azerite gear don't show up once the addon is loaded.

**Expected behavior**
To be able to see the Azerite icon decoration until or unless a new feature is added to the addon to distinguish them from other gear.

**Comment by Jaliborc** [comment]
Done
