### ISSUE TITLE
Dark Iron race icon is green

### ISSUE THREAD

**Issue by JoostKersjes** [tullamods/Bagnon#780]
**Running Software (please complete the following information):**
 - Game patch [e.g. Build 8.0.1.27178]
 - Addon version

- 8.0.1.27481
- 8.0.2

**Describe the bug**
I just finished the requirement for dark iron dwarves and made one. When I hovered over any of my items or my coin stack, the usual racial icon that is displayed is not there. It is just a green square. It also flickers a bit.

It is kind of an eyesore and stands out way too much. If it is not possible to fix, please make grey or invisible instead of green.

**To Reproduce**
1. Make a dark iron dwarf
2. Hover over any item or the coin stack

**Expected behavior**
I expected it to show an icon for the dark iron race.

**Screenshots**
![image](https://user-images.githubusercontent.com/10849207/44800106-dffb0380-abb5-11e8-86c1-406da994836e.png)
![image](https://user-images.githubusercontent.com/10849207/44800139-f43f0080-abb5-11e8-876f-8b5a6eb8a414.png)

**Comment by mrfantastic1** [comment]
I managed to get this fixed by modifying the owners.lua file in the bagnon>external>wildpants>core file 

you should see a line that goes like this

local ICONLESS_RACES = {
	['Worgen'] = true,
	['Goblin'] = true,
	['VoidElf'] = true,
	['Nightborne'] = true,
	['LightforgedDraenei'] = true,
	['HighmountainTauren'] = true,
}
add this line to the bottom 

['DarkIronDwarf'] = true,

it should look like this when you are done

local ICONLESS_RACES = {
	['Worgen'] = true,
	['Goblin'] = true,
	['VoidElf'] = true,
	['Nightborne'] = true,
	['LightforgedDraenei'] = true,
	['HighmountainTauren'] = true,
	['DarkIronDwarf'] = true,
}

**Comment by Cravick** [comment]
As a note for Mag'har looking for a fix the above also works with `['MagharOrc'] = true`

**Comment by Jaliborc** [comment]
Fixed
