### ISSUE TITLE
Not showing bank items and bags

### ISSUE THREAD

**Issue by WyteEagle** [tullamods/Bagnon#782]
**Running Software (please complete the following information):**
 - Game patch      8.0.1.27547
 - Addon version  8.0.2

**Describe the bug**
When I try and see what's in my bank from right clicking the bagnon icon on my main inventory screen, it brings up the bank tab but shows nothing in my bank along with no bags except the main and materials bag.

**To Reproduce**
1. Go to Inventory
2. Right click on Bagnon icon for bank tab

**Expected behavior**
Bank tab to show what's in my bank along with the bags
**Screenshots**
![wowscrnshot_090118_121727](https://user-images.githubusercontent.com/42896366/44948480-d0f99880-ade3-11e8-8721-4bba9d94830c.jpg)
![wowscrnshot_090118_121845](https://user-images.githubusercontent.com/42896366/44948481-d35bf280-ade3-11e8-856b-eef7a08e1d12.jpg)
![wowscrnshot_090118_121917](https://user-images.githubusercontent.com/42896366/44948482-d525b600-ade3-11e8-8a66-c84514830833.jpg)

Above screenshots from 3 different toons

**Error Logs**
N/A

**Additional context**
N/A

**Comment by inverseparadigm** [comment]
I have also been experiencing this problem since pre patch.
