### ISSUE TITLE
Search fails to find mythic keystones

### ISSUE THREAD

**Issue by xeropresence** [tullamods/Bagnon#785]
**Running Software (please complete the following information):**
 - Game 8.0.1
 - Addon: 8.0.3

**Describe the bug**
Type key, keystone, mythic etc into search, none will match the keystone

https://vgy.me/htmBjY.png

Unsure if related to #779

**Comment by breasoner40** [comment]
I can confirm the same activity for me, disabled bagnon search works fine, enable bagnon search won't find "Key" or "Keystone"

**Comment by Jaliborc** [comment]
Discussion of this issue will be on #779

**Comment by xeropresence** [comment]
I've opened a new issue with more information about the cause of this issue as well as a temporary workaround here https://github.com/Jaliborc/LibItemCache-2.0/pull/12

**Comment by xeropresence** [comment]
@Jaliborc Can you take a look at this for https://github.com/tullamods/Bagnon/projects/2

**Comment by Jaliborc** [comment]
So... the item link is screwing up the tooltip? Do you have any clue as why this is happening.
(good work figuring that out by the way)

**Comment by Jaliborc** [comment]
Yeah, I've been following the project. Really useful.
