### ISSUE TITLE
Guild Bank

### ISSUE THREAD

**Issue by Mykanar** [tullamods/Bagnon#786]
**Running Software (please complete the following information):**
 - Game patch 8.0.1.27602
 - Addon version 8.0.4

**Describe the bug**
Guild Bank not showing up, only the Guild Bank Bar like sort, search and so on

**To Reproduce**
1. Go to Guild Bank and open it
2. nothing happen
3. All Addons deaktivated except Bagnon
4. in Bagnon Config, the activate button is grey
5.all bagnon addons loaded (options, guild, void)

**Expected behavior**

**Screenshots**
![guild bank 1](https://user-images.githubusercontent.com/43072367/45229285-b9c81880-b2c5-11e8-98a6-593b9dfcfc9d.png)
![guild bank config](https://user-images.githubusercontent.com/43072367/45229290-bf256300-b2c5-11e8-82ef-224286e8fe95.png)

**Error Logs**
no error logs

**Additional context**

**Comment by Aeleron** [comment]
Same Issue. Latest update, and guild bank is inaccessible. Just shows the boxes, but no inventory spots.

**Comment by SaltyC** [comment]
1x Bagnon_GuildBank\components\item.lua:26: attempt to concatenate local 'id' (a nil value)
Bagnon_GuildBank\components\item.lua:26: in function `Construct'
Bagnon\external\Wildpants\components\item.lua:37: in function `Create'
Bagnon_GuildBank\components\item.lua:16: in function `Create'
Bagnon\external\Wildpants\components\item.lua:22: in function `New'
...s\Bagnon\external\Wildpants\components\itemFrame.lua:119: in function <...s\Bagnon\external\Wildpants\components\itemFrame.lua:108>

Locals:
self = <unnamed> {
 0 = <userdata>
 OnEnter = <function> defined @Bagnon_GuildBank\components\item.lua:74
 __super = <unnamed> {
 }
 IsNew = <function> defined @Bagnon_GuildBank\components\item.lua:119
 UpdateCooldown = <function> defined @Bagnon_GuildBank\components\item.lua:105
 GetBlizzard = <function> defined @Bagnon_GuildBank\components\item.lua:29
 OnDragStart = <function> defined @Bagnon_GuildBank\components\item.lua:62
 OnReceiveDrag = <function> defined @Bagnon_GuildBank\components\item.lua:68
 __index = <unnamed> {
 }
 unused = <table> {
 }
 UpdateTooltip = <function> defined @Bagnon_GuildBank\components\item.lua:84
 Create = <function> defined @Bagnon_GuildBank\components\item.lua:15
 GetBag = <function> defined @Bagnon_GuildBank\components\item.lua:114
 IsQuestItem = <function> defined @Bagnon_GuildBank\components\item.lua:118
 Name = "GuildItemSlot"
 GetSlot = <function> defined @Bagnon_GuildBank\components\item.lua:110
 nextID = 0
 OnClick = <function> defined @Bagnon_GuildBank\components\item.lua:35
 Construct = <function> defined @Bagnon_GuildBank\components\item.lua:25
 SplitStack = <function> defined @Bagnon_GuildBank\components\item.lua:100
}
id = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = "Button"
(*temporary) = "Bagnon_GuildBank"
(*temporary) = "ItemSlot"
(*temporary) = nil
(*temporary) = "attempt to concatenate local 'id' (a nil value)"
MODULE = "Bagnon_GuildBank"

**Comment by fatexs** [comment]
can confirm gbank broken

**Comment by Mayo77** [comment]
same issue

**Comment by hueyjus** [comment]
same issue, pasting bug report


Date: 2018-09-08 09:23:26
ID: 1
Error occured in: Global
Count: 1
Message: ...nterface\AddOns\Bagnon_GuildBank\components\item.lua line 26:
   attempt to concatenate local 'id' (a nil value)
Debug:
   [C]: ?
   ...nterface\AddOns\Bagnon_GuildBank\components\item.lua:26: Construct()
   ...AddOns\Bagnon\external\Wildpants\components\item.lua:37: Create()
   ...nterface\AddOns\Bagnon_GuildBank\components\item.lua:16: Create()
   ...AddOns\Bagnon\external\Wildpants\components\item.lua:22: New()
   ...s\Bagnon\external\Wildpants\components\itemFrame.lua:119:
      ...s\Bagnon\external\Wildpants\components\itemFrame.lua:108
Locals:

AddOns:
  Swatter, v7.7.6095 (SwimmingSeadragon)
  AngryAssignments, vv1.11.1
  AucAdvanced, v7.7.6112 (SwimmingSeadragon)
  AucFilterBasic, v7.7.6081 (SwimmingSeadragon)
  AucScanData, v7.7.6082 (SwimmingSeadragon)
  AucStatHistogram, v7.7.6083 (SwimmingSeadragon)
  AucStatiLevel, v7.7.6087 (SwimmingSeadragon)
  AucStatPurchased, v7.7.6084 (SwimmingSeadragon)
  AucStatSimple, v7.7.6085 (SwimmingSeadragon)
  AucStatStdDev, v7.7.6086 (SwimmingSeadragon)
  AucUtilFixAH, v7.7.6088 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.0.4
  BagnonGuildBank, v8.0.4
  BeanCounter, v7.7.6110 (SwimmingSeadragon)
  DBMCore, v8.0.6
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.6.1
  Enchantrix, v7.7.6104 (SwimmingSeadragon)
  ExRT, v3940
  Informant, v7.7.6092 (SwimmingSeadragon)
  Omen, v3.2.0
  Pawn, v2.2.28
  RaiderIO, v8.0.1 (v201809070600)
  RaiderIODBUSA, v
  RaiderIODBUSH, v
  Simulationcraft, v1.10.6
  Skada, v1.7.5
  SlideBar, v7.7.6093 (SwimmingSeadragon)
  Stubby, v7.7.6094 (SwimmingSeadragon)
  TomTom, vv80001-1.0.2
  WeakAuras, v2.7.7
  BlizRuntimeLib_enUS v8.0.1.80000 <none>
  (ck=44b)

**Comment by JayJones65** [comment]
+1, reverted to 8.0.3 to  workaround. Also found that GB Settings the Column option is behaving as Rows, not columns. May be related. Other windows Columns in options = columns behavior.
