### ISSUE TITLE
Bag problem with latest patch -- same error for both guild owner and regular guild member

### ISSUE THREAD

**Issue by Epinnoia** [tullamods/Bagnon#789]
This just started happening after I made update on Twitch to the latest version.  I had the version immediately prior, and this issue did not happen.  So it seems reasonable to believe this has occurred as a result of a change made in this latest version.  Note, the bag does open, but none of the slots show content.  It's just showing the top header portion of the guild bank.  

https://i.imgur.com/pn6fN3C.jpg

Date: 2018-09-07 22:30:29
ID: 12
Error occured in: Global
Count: 1
Message: ...nterface\AddOns\Bagnon_GuildBank\components\item.lua line 26:
   attempt to concatenate local 'id' (a nil value)
Debug:
   (tail call): ?
   [C]: ?
   ...nterface\AddOns\Bagnon_GuildBank\components\item.lua:26: Construct()
   ...AddOns\Bagnon\external\Wildpants\components\item.lua:37: Create()
   ...nterface\AddOns\Bagnon_GuildBank\components\item.lua:16: Create()
   ...AddOns\Bagnon\external\Wildpants\components\item.lua:22: New()
   ...s\Bagnon\external\Wildpants\components\itemFrame.lua:119:
      ...s\Bagnon\external\Wildpants\components\itemFrame.lua:108
Locals:
(*temporary) = 0.016000000759959
(*temporary) = <function> defined =[C]:-1

AddOns:
  Swatter, v7.7.6095 (SwimmingSeadragon)
  AccountantClassic, vv2.11.03
  AdvancedInterfaceOptions, v1.2.4
  AtlasLoot, vv8.07.13
  AtlasLootBurningCrusade, vv8.07.13
  AtlasLootCataclysm, vv8.07.13
  AtlasLootClassic, vv8.07.13
  AtlasLootLegion, vv8.07.13
  AtlasLootMistsofPandaria, vv8.07.13
  AtlasLootWarlordsofDraenor, vv8.07.13
  AtlasLootWrathoftheLichKing, vv8.07.13
  AucAdvanced, v7.7.6112 (SwimmingSeadragon)
  AucFilterBasic, v7.7.6081 (SwimmingSeadragon)
  AucStatHistogram, v7.7.6083 (SwimmingSeadragon)
  AucStatiLevel, v7.7.6087 (SwimmingSeadragon)
  AucStatPurchased, v7.7.6084 (SwimmingSeadragon)
  AucStatSimple, v7.7.6085 (SwimmingSeadragon)
  AucStatStdDev, v7.7.6086 (SwimmingSeadragon)
  AucUtilFixAH, v7.7.6088 (SwimmingSeadragon)
  Auctionator, v5.0.5
  AuctionatorMiniFeatures, v8.0v1-release
  BagBrother, v
  Bagnon, v8.0.4
  BagnonGuildBank, v8.0.4
  BattlePetCounter, v
  BelowAverageItems, v1.27
  BigWigs, vv108.1
  BrokerPortals, v1.10.0
  Clique, vv80000-1.0.0
  DBMCore, v8.0.6
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DejaCharacterStats, v800r103
  Details, v
  DetailsDmgRank, v
  DetailsDpsTuning, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTimeAttack, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  Dominos, v8.0.7
  DominosCast, v
  DominosEncounter, v
  DominosProgress, v
  DominosRoll, v
  EasyObliterate, v31
  FollowerLocationInfo, v1.5.2-release
  FollowerLocationInfoJournal, v1.5.2-release
  HandyNotes, vv1.5.3
  HandyNotesAchievements, v0.4.20
  HandyNotesAncientShrines, v2.0
  HandyNotesArgus, vv0.10
  HandyNotesAzerothsTopTunes, vv1.2.2
  HandyNotesBrokenShore, vv1.29
  HandyNotesCamelFigurines, v1.3
  HandyNotesCityGuide, v1.7.1
  HandyNotesDirections, v1
  HandyNotesDraenorTreasures, v1.21
  HandyNotesDungeonLocations, v1.35
  HandyNotesEagleFlightNetwork, v1.0
  HandyNotesEliteBattlePets, v1
  HandyNotesEverShiftingMirror, v1.0.3
  HandyNotesFieldPhotographer, v8.0.0.0
  HandyNotesGuild, v1.10
  HandyNotesHallowsEnd, vv1.3
  HandyNotesHigherDimensionalLearning, v1
  HandyNotesHigherLearning, v8.0.0.0
  HandyNotesKosumoth, v1
  HandyNotesLegionClassOrderHalls, vv1.29
  HandyNotesLegionInstanceWorldQuests, vv1.15
  HandyNotesLegionMagePortals, v1.3
  HandyNotesLegionRaresTreasures, v1.1
  HandyNotesLegionTownPortals, v0.0.1
  HandyNotesLegionTreasures, v1
  HandyNotesLongForgottenHippogryph, v1
  HandyNotesLorewalkers, v1
  HandyNotesLostAndFound, v1
  HandyNotesLunarFestival, vv1.5
  HandyNotesMailboxes, v1
  HandyNotesPandariaTreasures, v1.06
  HandyNotesPetDailies, v
  HandyNotesSpecialNPCsEtc, v1.1.1-Beta
  HandyNotesSummerFestival, vv1.5
  HandyNotesSuramarLeylines, v1
  HandyNotesSuramarLocations, v0.0.1
  HandyNotesSuramarShalAranTelemancy, vv1.19
  HandyNotesSuramarTelemancy, v1
  HandyNotesTimelessIsleRareElites, v2.32
  HandyNotesTimelessIsleChests, v1.20
  HandyNotesTimelessTreasures, v1.0.7
  HandyNotesTrainers, v1.7.0
  HandyNotesTravelGuide, vv1.9.2
  HandyNotesTreasureHunter, v1
  HandyNotesVendors, v1.7.0
  HandyNotesWellRead, v8.0.0.0
  HandyNotesWitheredArmyTraining, v1
  HandyNotesWitheredChests, v1.2
  HealBot, v8.0.1.0
  HealBotTips, v8.0.1.0
  IceHUD, v1.11.5
  ImprovedOptionsFrames, v1.5.6
  InFlightLoad, v8.0.003
  Informant, v7.7.6092 (SwimmingSeadragon)
  InstancePortals, v19
  MarketWatcher, v2.21
  MasterPlanA, vA
  MikScrollingBattleText, v5.7.149
  OPie, vVanilla 7
  Overachiever, v1.0.3
  OverachieverCache, v1.0.3
  OverachieverTabs, v1.0.3
  Pawn, v2.2.28
  PersonalLootHelper, v2.17
  PetBattleFFVictory, vv1.2.6
  PetBattleJunkie, v1.5
  PetBattleMaster, v8.0.0
  PetTracker, v8.0.6
  PetTrackerBreeds, v8.0.6
  PetTrackerJournal, v8.0.6
  PetTrackerSwitcher, v8.0.6
  PetTrackerUpgrades, v8.0.6
  PGFinder, v5.8
  Recount, vv8.0.1b
  SavedInstances, v8.0.5
  SlideBar, v7.7.6093 (SwimmingSeadragon)
  Stubby, v7.7.6094 (SwimmingSeadragon)
  TargetPercent, vv8.0.0
  TellMeWhen, v8.5.3
  Titan, v5.14.7.80000
  TitanBag, v5.14.7.80000
  TitanClock, v5.14.7.80000
  TitanGold, v5.14.7.80000
  TitanLocation, v5.14.7.80000
  TitanLootType, v5.14.7.80000
  TitanPerformance, v5.14.7.80000
  TitanRepair, v5.14.7.80000
  TitanVolume, v5.14.7.80000
  TitanXP, v5.14.7.80000
  TomTom, vv80001-1.0.2
  TradeSkillMaster, vv4.3.1
  TradeSkillMasterAppHelper, vv4.0
  WorldQuestTracker, v
  WoWPro, v8.0.1H
  WoWProAchievements, v8.0.1H
  WoWProDailies, v8.0.1H
  WoWProLeveling, v8.0.1H
  WowProProfession, v8.0.1H
  WoWProWorldEvents, v8.0.1H
  BlizRuntimeLib_enUS v8.0.1.80000 <none>
  (ck=11d2)

**Comment by Epinnoia** [comment]
Did nothing more than DOWNGRADE to 8.0.3 from 8.0.4, and it works again.  So this, I think, demonstrates that something in 8.0.4 is either broken, or conflicting:

https://i.imgur.com/DFSg8Xz.jpg

**Comment by Condor103** [comment]
Hey I found **part of** the issue, in the file item.lua located at "World of Warcraft\Interface\AddOns\Bagnon_GuildBank\components". On **line 26** is the code: **return CreateFrame('Button', MODULE .. 'ItemSlot' .. id, nil, 'ContainerFrameItemButtonTemplate')**. If you remove the **id** in front of "'ItemSlot' .." the guild bank tab will open, but Bagnon will still throw an error, and it appears that the guild bank tab can be viewed, but not interacted with.
