### ISSUE TITLE
Add Scrap-O-Matic 1000 and Shred-Master Mk1 to frames that auto-open and close Bagnon (Issue #781 resubmit)

### ISSUE THREAD

**Issue by GnuclearGnome** [tullamods/Bagnon#793]
Add the Scrapping Frames to the Auto Display Options. Could, perhaps, be added to the "Crafting" option.  This was submitted as Issue #781 which was closed as having been incorporated into version 8.0.4.  However, it still does NOT work with version 8.0.4 installed.  When you click on the scrapping machine, the scrap UI opens but your bags do not.  Conversely, after opening the the scrap machine UI and your bags, closing the scrap machine UI leaves your bags still open.  However, given that your bags are not being auto-opened by Bagnon, the fact that they stay open is not unexpected.  No change to the Bagnon Options for the scrapping machines was added, but I don't know if that was intended or not.

**Comment by wtwilson3** [comment]
Confirmed.  I saw no difference in the latest update after the prior ticket was closed.  If this could be some sort of addon conflict, please let us know what to look for since neither the option menu nor the behavior has changed.

**Comment by wtwilson3** [comment]
I can report that as of the new update today, this feature is now working perfectly.  Thank you so much for this awesome addon.

**Comment by GnuclearGnome** [comment]
Yep, I agree.  Bagnon works flawlessly with the Scrap Machine with the new version and there is a Scrapping Gear checkbox in the Automatic Display options.  Nice job!  :)

**Comment by Jaliborc** [comment]
Cool! Cause I have no way whatsoever to test it. Glad I guessed how it works right.
