### ISSUE TITLE
guild bank problems

### ISSUE THREAD

**Issue by JAD481** [tullamods/Bagnon#794]
**Running Software (please complete the following information):**
 - Game patch [e.g. Build 8.0.1.27178]
 - Addon version
 v8.0.4 just updated.
**Describe the bug**
will add pic

**To Reproduce**

**Expected behavior**

**Screenshots**
![wowscrnshot_090818_171638](https://user-images.githubusercontent.com/43099844/45258786-71276280-b38c-11e8-8569-06433eb91200.jpg)

**Error Logs**
If applicable, add the first error message (labeled 1/Many) that appeared.

**Additional context**
Message: ...nterface\AddOns\Bagnon_GuildBank\components\item.lua:26: attempt to concatenate local 'id' (a nil value)
Time: Sat Sep  8 17:16:16 2018
Count: 1
Stack: ...nterface\AddOns\Bagnon_GuildBank\components\item.lua:26: attempt to concatenate local 'id' (a nil value)
...nterface\AddOns\Bagnon_GuildBank\components\item.lua:26: in function `Construct'
...AddOns\Bagnon\external\Wildpants\components\item.lua:37: in function `Create'
...nterface\AddOns\Bagnon_GuildBank\components\item.lua:16: in function `Create'
...AddOns\Bagnon\external\Wildpants\components\item.lua:22: in function `New'
...s\Bagnon\external\Wildpants\components\itemFrame.lua:119: in function <...s\Bagnon\external\Wildpants\components\itemFrame.lua:108>

Locals: self = <unnamed> {
 0 = <userdata>
 OnEnter = <function> defined @Interface\AddOns\Bagnon_GuildBank\components\item.lua:74
 __super = <unnamed> {
 }
 IsNew = <function> defined @Interface\AddOns\Bagnon_GuildBank\components\item.lua:119
 UpdateCooldown = <function> defined @Interface\AddOns\Bagnon_GuildBank\components\item.lua:105
 GetBlizzard = <function> defined @Interface\AddOns\Bagnon_GuildBank\components\item.lua:29
 OnDragStart = <function> defined @Interface\AddOns\Bagnon_GuildBank\components\item.lua:62
 OnReceiveDrag = <function> defined @Interface\AddOns\Bagnon_GuildBank\components\item.lua:68
 __index = <unnamed> {
 }
 unused = <table> {
 }
 UpdateTooltip = <function> defined @Interface\AddOns\Bagnon_GuildBank\components\item.lua:84
 Create = <function> defined @Interface\AddOns\Bagnon_GuildBank\components\item.lua:15
 GetBag = <function> defined @Interface\AddOns\Bagnon_GuildBank\components\item.lua:114
 IsQuestItem = <function> defined @Interface\AddOns\Bagnon_GuildBank\components\item.lua:118
 Name = "GuildItemSlot"
 GetSlot = <function> defined @Interface\AddOns\Bagnon_GuildBank\components\item.lua:110
 nextID = 0
 OnClick = <function> defined @Interface\AddOns\Bagnon_GuildBank\components\item.lua:35
 Construct = <function> defined @Interface\AddOns\Bagnon_GuildBank\components\item.lua:25
 SplitStack = <function> defined @Interface\AddOns\Bagnon_GuildBank\components\item.lua:100
}
id = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = "Button"
(*temporary) = "Bagnon_GuildBank"
(*temporary) = "ItemSlot"
(*temporary) = nil
(*temporary) = "attempt to concatenate local 'id' (a nil value)"
MODULE = "Bagnon_GuildBank"

**Comment by guran58** [comment]
The guild bank is not opened, only the upper part is visible, the bank itself does not open ... correct

**Comment by guran58** [comment]
....as in the screenshot above

**Comment by thatgeraldguy** [comment]
Game ver.
8.0.1.27602
Addon ver.
8.0.4
Windows ver.
Windows 10 home, up to date.
Description.
When I open the guild bank, I see only the title bar and icons for the different tabs, the actual contents of all tabs are not visible.  All you see is a narrow rectangle where your guild bank contents should be.
To repro.
-Walk up to guild bank
-Click it to open
-Title bar opens, as described above.  No guild bank contents are visible.
Expected.
Able to see what's in the guild bank when I click it.
Actual.
Nothing is visible save for the title bar with icons for the different tabs. 
![guild bank](https://user-images.githubusercontent.com/43104775/45261280-186fbe00-b3bc-11e8-8c92-f9ac4eae9db4.PNG)

**Comment by Shiroma51** [comment]
Same problem here with the addition of only 4 bags showing when there are 6.

**Comment by Vavictus** [comment]
This is the bug i'm getting:


9x Bagnon_GuildBank\components\item.lua:26: attempt to concatenate local 'id' (a nil value)
Bagnon_GuildBank\components\item.lua:26: in function `Construct'
Bagnon\external\Wildpants\components\item.lua:37: in function `Create'
Bagnon_GuildBank\components\item.lua:16: in function `Create'
Bagnon\external\Wildpants\components\item.lua:22: in function `New'
...s\Bagnon\external\Wildpants\components\itemFrame.lua:119: in function <...s\Bagnon\external\Wildpants\components\itemFrame.lua:108>

Locals:
self = <unnamed> {
 0 = <userdata>
 OnEnter = <function> defined @Bagnon_GuildBank\components\item.lua:74
 __super = <unnamed> {
 }
 IsNew = <function> defined @Bagnon_GuildBank\components\item.lua:119
 UpdateCooldown = <function> defined @Bagnon_GuildBank\components\item.lua:105
 GetBlizzard = <function> defined @Bagnon_GuildBank\components\item.lua:29
 OnDragStart = <function> defined @Bagnon_GuildBank\components\item.lua:62
 OnReceiveDrag = <function> defined @Bagnon_GuildBank\components\item.lua:68
 __index = <unnamed> {
 }
 unused = <table> {
 }
 UpdateTooltip = <function> defined @Bagnon_GuildBank\components\item.lua:84
 Create = <function> defined @Bagnon_GuildBank\components\item.lua:15
 GetBag = <function> defined @Bagnon_GuildBank\components\item.lua:114
 IsQuestItem = <function> defined @Bagnon_GuildBank\components\item.lua:118
 Name = "GuildItemSlot"
 GetSlot = <function> defined @Bagnon_GuildBank\components\item.lua:110
 nextID = 0
 OnClick = <function> defined @Bagnon_GuildBank\components\item.lua:35
 Construct = <function> defined @Bagnon_GuildBank\components\item.lua:25
 SplitStack = <function> defined @Bagnon_GuildBank\components\item.lua:100
}
id = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = "Button"
(*temporary) = "Bagnon_GuildBank"
(*temporary) = "ItemSlot"
(*temporary) = nil
(*temporary) = "attempt to concatenate local 'id' (a nil value)"
MODULE = "Bagnon_GuildBank"

**Comment by Jaliborc** [comment]
yup, my bad, new version out
