### ISSUE TITLE
guild bank wont turn off

### ISSUE THREAD

**Issue by gigimdv** [tullamods/Bagnon#796]
This has been an issue I've had for awhile, I'm not sure if it was made this way in an update. But I would like to turn on the bagnon for guild bank. The enable frame for guild back has been permanently turned on and grayed out. I'd like to be able to turn this off again, I have a hard time editing guild bank tabs and all that with bagnon having it turned on.
![gb](https://user-images.githubusercontent.com/30988022/45260876-bbc2d200-b3c0-11e8-94df-fedf4d77e7d1.png)

**Comment by Tisolon** [comment]
Bagnon ist in mehrere Addons unterteilt. Geh einfach ins Spielmenü oder in die Charakterauswahl auf Addons und schalte Bagnon Guild Bank aus.
MfG

**Comment by gigimdv** [comment]
Thank you didn't even realize that was there!

**Comment by Jaliborc** [comment]
lol
