### ISSUE TITLE
Guild Bank not displaying contents

### ISSUE THREAD

**Issue by WizardCity** [tullamods/Bagnon#797]
Hey I am getting the following error report whenever I try to open the Guild Bank :

Date: 2018-09-09 15:21:25
ID: 1
Error occured in: Global
Count: 1
Message: ...nterface\AddOns\Bagnon_GuildBank\components\item.lua line 26:
   attempt to concatenate local 'id' (a nil value)
Debug:
   ...nterface\AddOns\Bagnon_GuildBank\components\item.lua:26: Construct()
   ...AddOns\Bagnon\external\Wildpants\components\item.lua:37: Create()
   ...nterface\AddOns\Bagnon_GuildBank\components\item.lua:16: Create()
   ...AddOns\Bagnon\external\Wildpants\components\item.lua:22: New()
   ...s\Bagnon\external\Wildpants\components\itemFrame.lua:119:
      ...s\Bagnon\external\Wildpants\components\itemFrame.lua:108
Locals:
self = <unnamed> {
 0 = <userdata>
 OnEnter = <function> defined @Interface\AddOns\Bagnon_GuildBank\components\item.lua:74
 __super = <unnamed> {
 }
 IsNew = <function> defined @Interface\AddOns\Bagnon_GuildBank\components\item.lua:119
 UpdateCooldown = <function> defined @Interface\AddOns\Bagnon_GuildBank\components\item.lua:105
 GetBlizzard = <function> defined @Interface\AddOns\Bagnon_GuildBank\components\item.lua:29
 OnDragStart = <function> defined @Interface\AddOns\Bagnon_GuildBank\components\item.lua:62
 OnReceiveDrag = <function> defined @Interface\AddOns\Bagnon_GuildBank\components\item.lua:68
 __index = <unnamed> {
 }
 unused = <table> {
 }
 UpdateTooltip = <function> defined @Interface\AddOns\Bagnon_GuildBank\components\item.lua:84
 Create = <function> defined @Interface\AddOns\Bagnon_GuildBank\components\item.lua:15
 GetBag = <function> defined @Interface\AddOns\Bagnon_GuildBank\components\item.lua:114
 IsQuestItem = <function> defined @Interface\AddOns\Bagnon_GuildBank\components\item.lua:118
 Name = "GuildItemSlot"
 GetSlot = <function> defined @Interface\AddOns\Bagnon_GuildBank\components\item.lua:110
 nextID = 0
 OnClick = <function> defined @Interface\AddOns\Bagnon_GuildBank\components\item.lua:35
 Construct = <function> defined @Interface\AddOns\Bagnon_GuildBank\components\item.lua:25
 SplitStack = <function> defined @Interface\AddOns\Bagnon_GuildBank\components\item.lua:100
}
id = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = "Button"
(*temporary) = "Bagnon_GuildBank"
(*temporary) = "ItemSlot"
(*temporary) = nil
(*temporary) = "attempt to concatenate local 'id' (a nil value)"
MODULE = "Bagnon_GuildBank"

AddOns:
  Swatter, v7.7.6095 (SwimmingSeadragon)
  AucAdvanced, v7.7.6112 (SwimmingSeadragon)
  AucFilterBasic, v7.7.6081 (SwimmingSeadragon)
  AucStatHistogram, v7.7.6083 (SwimmingSeadragon)
  AucStatiLevel, v7.7.6087 (SwimmingSeadragon)
  AucStatPurchased, v7.7.6084 (SwimmingSeadragon)
  AucStatSimple, v7.7.6085 (SwimmingSeadragon)
  AucStatStdDev, v7.7.6086 (SwimmingSeadragon)
  AucUtilFixAH, v7.7.6088 (SwimmingSeadragon)
  AzeriteTooltip, v1.71
  BadBoy, vv8.0.7
  BagBrother, v
  Bagnon, v8.0.4
  BagnonBoE, v1.0
  BagnonCurrencies, v1.0.0
  BagnonGarbage, v1.0
  BagnonGuildBank, v8.0.4
  BagnonScrap, v21
  BeanCounter, v7.7.6110 (SwimmingSeadragon)
  BigWigs, vv109
  CanIMogIt, v8.0.0v1.11
  ChampionCommander, v1.0.3 80000
  DBMCore, v8.0.6
  DBMDefaultSkin, v
  DBMInterrupts, v7.3.0
  DBMStatusBarTimers, v
  DBMVPEnglishfemale, v8.0.4
  Details, v
  DetailsDmgRank, v
  DetailsDpsTuning, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTimeAttack, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  ElvUI, v10.81
  ElvUIBenikUI, v3.471
  ElvUIEnhanced, v3.3.3-beta2
  ElvUIExtraActionBars, v2.34
  ElvUIRaidMarkers, v4.24
  FishingBuddy, v1.9.17
  HandyNotes, vv1.5.3
  HandyNotesArgus, vv0.10
  HandyNotesBattleForAzerothTreasures, v1
  HandyNotesBrokenShore, vv1.29
  HandyNotesCamelFigurines, v1.3
  HandyNotesDraenorTreasures, v1.21
  HandyNotesDungeonLocations, v1.35
  HandyNotesHallowsEnd, vv1.3
  HandyNotesLegionRaresTreasures, v1.1
  HandyNotesLegionTownPortals, v0.0.1
  HandyNotesLegionTreasures, v1
  HandyNotesLongForgottenHippogryph, v1
  HandyNotesPandariaTreasures, v1.06
  HandyNotesSuramarLeylines, v1
  HandyNotesTimelessIsleRareElites, v2.32
  HandyNotesTimelessIsleChests, v1.20
  HandyNotesTravelGuide, vv1.9.2
  HandyNotesWellRead, v8.0.0.0
  HandyNotesWitheredArmyTraining, v1
  Informant, v7.7.6092 (SwimmingSeadragon)
  MinimapButtonFrame, v3.1.10h
  MinimapButtonFrameSkinPack, v3.0.1b
  MoveAnything, v17.0.0
  OmniCC, v8.0.1
  Pawn, v2.2.28
  PersonalLootHelper, v2.17
  Scrap, v13.11
  SexyMap, vv8.0.8
  SlideBar, v7.7.6093 (SwimmingSeadragon)
  Stubby, v7.7.6094 (SwimmingSeadragon)
  TomTom, vv80001-1.0.2
  WeakAuras, v2.7.7
  WorldQuestTracker, v
  BlizRuntimeLib_enUS v8.0.1.80000 <none>
  (ck=8da)

**Comment by Mayo77** [comment]
Having same issue even after recent update. Guild banks still not working properly.
