### ISSUE TITLE
new update still not working right

### ISSUE THREAD

**Issue by bringr1** [tullamods/Bagnon#798]
**Running Software (please complete the following information):**
 - Game patch [e.g. Build 8.0.1.27178]
 - Addon version

update still leaves ! points in each bag slot with a light colored highlight but can't see actual item in each slot

**Comment by JAD481** [comment]
it isd working for me. thanks for the fast fix.

**Comment by Shiroma51** [comment]
Mine was showing 4 of the 6 bank tabs, personal bags working fine. Disabled all addons and just loaded the add and it is still the same 4 of the 6 bags showing. But when i reloaded all addons its cleared and is working as normal. Thank you :)
