### ISSUE TITLE
Guild Bank still not showing properly since newest update.

### ISSUE THREAD

**Issue by Mayo77** [tullamods/Bagnon#802]
**Running Software (please complete the following information):**
 - Game patch - Newest version
 - Addon version - 8.0.6

**Describe the bug**
I open my guild bank tab and it doesnt open up. It shows the icons only but none of the actually inventory opens up.

**To Reproduce**
1. go to guild bank
2 open guild bank

**Expected behavior**
show all my full bags open. 

**There was already a thread on this a few days ago with about 10 people that all reported this, that was closed but it never got fixed, so i re-opened this one.**

**Comment by Jaliborc** [comment]
https://www.patreon.com/posts/looking-for-for-21771493
