### ISSUE TITLE
Can't Split in GBank

### ISSUE THREAD

**Issue by Derankaix** [tullamods/Bagnon#806]
**Running Software (please complete the following information):**
 - Game patch 8.0.1
 - Addon Version 8.0.6

I can use the "Shift + Left click/right click" to split stacks in my own personal bank, and personal bags, But cannot do this in my guild bank?
Nothing happens, I have to take the entire stack of 200 out and put it into my bags, split it in my bags then put it back into the gbank.
If I disable Bagnon it works fine, I cannot find a setting anywhere that would effect it just for the gbank?

Appreciate any solves!

**Comment by skupfer** [comment]
This error occurs

```
88x ...Bagnon\external\Wildpants\features\tooltipCounts.lua:74: attempt to index field '?' (a nil value)
...Bagnon\external\Wildpants\features\tooltipCounts.lua:74: in function <...Bagnon\external\Wildpants\features\tooltipCounts.lua:58>
...Bagnon\external\Wildpants\features\tooltipCounts.lua:136: in function <...Bagnon\external\Wildpants\features\tooltipCounts.lua:133>
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
...faceTradeSkillMaster\Core\Lib\TooltipLib.lua:95: in function <...faceTradeSkillMaster\Core\Lib\TooltipLib.lua:93>
[C]: in function `SetGuildBankItem'
Bagnon_GuildBank\components\item.lua:91: in function `UpdateTooltip'
Bagnon_GuildBank\components\item.lua:77: in function <Bagnon_GuildBank\components\item.lua:74>

Locals:
tooltip = GameTooltip {
 0 = <userdata>
 SetExistingSocketGem = <function> defined =[C]:-1
 SetCurrencyToken = <function> defined @Altoholic\Tooltip.lua:700
 SetGuildBankItem = <function> defined =[C]:-1
 hasMoney = 1
 SetVoidDepositItem = <function> defined =[C]:-1
 Hide = <function> defined =[C]:-1
 template = "Transparent"
 comparing = false
 SetSocketGem = <function> defined =[C]:-1
 TopOverlay = <unnamed> {
 }
 shownMoneyFrames = 1
 SetUnitDebuff = <function> defined =[C]:-1
 SetItemByID = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 SetTrainerService = <function> defined =[C]:-1
 numMoneyFrames = 2
 SetHyperlink = <function> defined =[C]:-1
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 SetVoidItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 SetQuestLogItem = <function> defined =[C]:-1
 SetVoidWithdrawalItem = <function> defined =[C]:-1
 SetTradeTargetItem = <function> defined =[C]:-1
 SetHeirloomByItemID = <function> defined =[C]:-1
 SetTradePlayerItem = <function> defined =[C]:-1
 SetInboxItem = <function> defined =[C]:-1
 SetSendMailItem = <function> defined =[C]:-1
 __tamedCounts = false
 updateTooltip = 0.10899999346584
 SetInventoryItem = <function> defined =[C]:-1
 CIMI_tooltipWritten = false
 SetMerchantCostItem = <function> defined @TradeSkillMaster\Core\Lib\TooltipLib.lua:93
 SetLootRollItem = <function> defined =[C]:-1
 SetUnitAura = <function> defined =[C]:-1
 ignoreUpdates = true
 SetAuctionSellItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 needsReset = true
 BottomOverlay = <unnamed> {
 }
 SetUnitBuff = <function> defined =[C]:-1
 SetRecipeResultItem = <function> defined =[C]:-1
 SetAuctionItem = <function> defined =[C]:-1
}
link = "|cffffffff|Hitem:124105::::::::120:577::::::|h[Starlight Rose]|h|r"
itemID = 124105
players = 0
total = 0
(for generator) = <function> defined @Bagnon\external\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:101
(for state) = nil
(for control) = "® Back vong Hell her"
owner = "® Back vong Hell her"
info = <table> {
 isguild = true
 name = "Back vong Hell her"
 faction = "Horde"
 cached = false
 realm = "Blackhand"
}
color = "|cfffad000%s|r"
(*temporary) = nil
(*temporary) = <table> {
 isguild = true
 name = "Back vong Hell her"
 faction = "Horde"
 cached = false
 realm = "Blackhand"
}
(*temporary) = <table> {
 GetRGB = <function> defined @SharedXML\Util.lua:615
 OnLoad = <function> defined @SharedXML\Util.lua:604
 b = 0
 GenerateHexColorMarkup = <function> defined @SharedXML\Util.lua:646
 WrapTextInColorCode = <function> defined @SharedXML\Util.lua:650
 GenerateHexColor = <function> defined @SharedXML\Util.lua:642
 GetRGBA = <function> defined @SharedXML\Util.lua:623
 IsEqualTo = <function> defined @SharedXML\Util.lua:608
 g = 0.64
 r = 0.77
 SetRGBA = <function> defined @SharedXML\Util.lua:631
 GetRGBAsBytes = <function> defined @SharedXML\Util.lua:619
 SetRGB = <function> defined @SharedXML\Util.lua:638
 GetRGBAAsBytes = <function> defined @SharedXML\Util.lua:627
}
(*temporary) = 1.41
(*temporary) = 325.53191489362
(*temporary) = "|cfffad000%s|r"
(*temporary) = "%s|r"
(*temporary) = 250.65957446809
(*temporary) = 208.34042553191
(*temporary) = 0
(*temporary) = "|cfffad000"
(*temporary) = 255
(*temporary) = 0
(*temporary) = 2
(*temporary) = nil
(*temporary) = 0
(*temporary) = "attempt to index field '?' (a nil value)"
Addon = <table> {
 GetOwnerColorString = <function> defined @Bagnon\external\Wildpants\core\owners.lua:56
 SearchFrame = <unnamed> {
 }
 EnableModule = <function> defined @ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:363
 modules = <table> {
 }
 ToggleFrame = <function> defined @Bagnon\external\Wildpants\core\frames.lua:43
 IterateEm
```

**Comment by Derankaix** [comment]
I don't actually get an error box pop up or anything. Just nothing happens

**Comment by Derankaix** [comment]
still having this problem

**Comment by semecan** [comment]
Check this issue: [https://github.com/tullamods/Bagnon/issues/757](url)

**Comment by raysmith59** [comment]
In case it helps, I just received a different LUA error that I haven't seen before when I accidentally tried splitting the stack in the bank:

1x Bagnon_GuildBank\components\item.lua:43: attempt to call global 'OpenStackSplitFrame' (a nil value)
Bagnon_GuildBank\components\item.lua:43: in function <Bagnon_GuildBank\components\item.lua:35>

Locals:
self = Bagnon_GuildBankItemSlot3 {
 timeSinceUpgradeCheck = 0
 bag = 1
 BattlepayItemTexture = <unnamed> {
 }
 SetItemMatchesItemContext = <function> defined @FrameXML\ItemButtonTemplate.lua:182
 IconOverlay = <unnamed> {
 }
 BagStaticTop = <unnamed> {
 }
 Flash = <unnamed> {
 }
 IconBorder = <unnamed> {
 }
 flashAnim = <unnamed> {
 }
 icon = Bagnon_GuildBankItemSlot3IconTexture {
 }
 ExtendedOverlay = <unnamed> {
 }
 caerdonButton = <unnamed> {
 }
 UpgradeIcon = <unnamed> {
 }
 UpdateItemContextMatching = <function> defined @FrameXML\ItemButtonTemplate.lua:191
 NewItemTexture = <unnamed> {
 }
 Cooldown = Bagnon_GuildBankItemSlot3Cooldown {
 }
 SplitStack = <function> defined @Bagnon_GuildBank\components\item.lua:100
 BagStaticBottom = <unnamed> {
 }
 ItemContextOverlay = <unnamed> {
 }
 flash = <unnamed> {
 }
 GetItemContextMatch = <function> defined @FrameXML\ItemButtonTemplate.lua:187
 scheduledSecondaryUpdate = false
 ExtendedSlot = <unnamed> {
 }
 ExtendedOverlay2 = <unnamed> {
 }
 hasItem = true
 JunkIcon = <unnamed> {
 }
 SetMatchesSearch = <function> defined @FrameXML\ItemButtonTemplate.lua:173
 UpdateItemContextOverlay = <function> defined @FrameXML\ItemButtonTemplate.lua:205
 count = 19
 info = <table> {
 }
 0 = <userdata>
 frame = BagnonFrameguild {
 }
 GetItemLocation = <function> defined @FrameXML\ItemButtonTemplate.lua:168
 Count = Bagnon_GuildBankItemSlot3Count {
 }
 QuestBorder = Bagnon_GuildBankItemSlot3IconQuestTexture {
 }
 newitemglowAnim = <unnamed> {
 }
 GetMatchesSearch = <function> defined @FrameXML\ItemButtonTemplate.lua:178
 IconGlow = <unnamed> {
 }
 searchOverlay = Bagnon_GuildBankItemSlot3SearchOverlay {
 }
}
button = "RightButton"
(*temporary) = nil
(*temporary) = nil
(*temporary) = Bagnon_GuildBankItemSlot3 {
 timeSinceUpgradeCheck = 0
 bag = 1
 BattlepayItemTexture = <unnamed> {
 }
 SetItemMatchesItemContext = <function> defined @FrameXML\ItemButtonTemplate.lua:182
 IconOverlay = <unnamed> {
 }
 BagStaticTop = <unnamed> {
 }
 Flash = <unnamed> {
 }
 IconBorder = <unnamed> {
 }
 flashAnim = <unnamed> {
 }
 icon = Bagnon_GuildBankItemSlot3IconTexture {
 }
 ExtendedOverlay = <unnamed> {
 }
 caerdonButton = <unnamed> {
 }
 UpgradeIcon = <unnamed> {
 }
 UpdateItemContextMatching = <function> defined @FrameXML\ItemButtonTemplate.lua:191
 NewItemTexture = <unnamed> {
 }
 Cooldown = Bagnon_GuildBankItemSlot3Cooldown {
 }
 SplitStack = <function> defined @Bagnon_GuildBank\components\item.lua:100
 BagStaticBottom = <unnamed> {
 }
 ItemContextOverlay = <unnamed> {
 }
 flash = <unnamed> {
 }
 GetItemContextMatch = <function> defined @FrameXML\ItemButtonTemplate.lua:187
 scheduledSecondaryUpdate = false
 ExtendedSlot = <unnamed> {
 }
 ExtendedOverlay2 = <unnamed> {
 }
 hasItem = true
 JunkIcon = <unnamed> {
 }
 SetMatchesSearch = <function> defined @FrameXML\ItemButtonTemplate.lua:173
 UpdateItemContextOverlay = <function> defined @FrameXML\ItemButtonTemplate.lua:205
 count = 19
 info = <table> {
 }
 0 = <userdata>
 frame = BagnonFrameguild {
 }
 GetItemLocation = <function> defined @FrameXML\ItemButtonTemplate.lua:168
 Count = Bagnon_GuildBankItemSlot3Count {
 }
 QuestBorder = Bagnon_GuildBankItemSlot3IconQuestTexture {
 }
 newitemglowAnim = <unnamed> {
 }
 GetMatchesSearch = <function> defined @FrameXML\ItemButtonTemplate.lua:178
 IconGlow = <unnamed> {
 }
 searchOverlay = Bagnon_GuildBankItemSlot3SearchOverlay {
 }
}
(*temporary) = "BOTTOMLEFT"
(*temporary) = "TOPLEFT"
(*temporary) = "attempt to call global 'OpenStackSplitFrame' (a nil value)"
ItemSlot = <unnamed> {
 0 = <userdata>
 OnEnter = <function> defined @Bagnon_GuildBank\components\item.lua:74
 __super = <unnamed> {
 }
 IsNew = <function> defined @Bagnon_GuildBank\components\item.lua:119
 UpdateCooldown = <function> defined @Bagnon_GuildBank\components\item.lua:105
 GetBlizzard = <function> defined @Bag
