### ISSUE TITLE
LUA error when viewing a different toon's main bags

### ISSUE THREAD

**Issue by raysmith59** [tullamods/Bagnon#808]
I don't think I've seen this happen before, I just clicked on a different portrait and got this:

2x Bagnon\external\Wildpants\components\item.lua:267: attempt to compare number with string
Bagnon\external\Wildpants\components\item.lua:267: in function `UpdateBorder'
Bagnon\external\Wildpants\components\item.lua:228: in function <Bagnon\external\Wildpants\components\item.lua:222>
[C]: ?
[C]: ?
[C]: in function `Update'
Bagnon\external\Wildpants\components\item.lua:124: in function <Bagnon\external\Wildpants\components\item.lua:119>
[C]: in function `Show'
Bagnon\external\Wildpants\components\item.lua:30: in function `New'
...s\Bagnon\external\Wildpants\components\itemFrame.lua:119: in function <...s\Bagnon\external\Wildpants\components\itemFrame.lua:108>

Locals:
self = ContainerFrame2Item4 {
 0 = <userdata>
 bag = 1
 BattlepayItemTexture = <unnamed> {
 }
 flashAnim = <unnamed> {
 }
 count = 0
 IconOverlay = <unnamed> {
 }
 BagStaticTop = <unnamed> {
 }
 flash = <unnamed> {
 }
 timeSinceUpgradeCheck = 0
 BagStaticBottom = <unnamed> {
 }
 scheduledSecondaryUpdate = true
 IconBorder = <unnamed> {
 }
 ExtendedOverlay2 = <unnamed> {
 }
 hasItem = true
 icon = ContainerFrame2Item4IconTexture {
 }
 NewItemTexture = <unnamed> {
 }
 JunkIcon = <unnamed> {
 }
 Flash = <unnamed> {
 }
 ExtendedSlot = <unnamed> {
 }
 ExtendedOverlay = <unnamed> {
 }
 caerdonButton = <unnamed> {
 }
 newitemglowAnim = <unnamed> {
 }
 frame = BagnonFrameinventory {
 }
 QuestBorder = ContainerFrame2Item4IconQuestTexture {
 }
 info = <table> {
 }
 UpgradeIcon = <unnamed> {
 }
 IconGlow = <unnamed> {
 }
 Count = ContainerFrame2Item4Count {
 }
 searchOverlay = ContainerFrame2Item4SearchOverlay {
 }
 Cooldown = ContainerFrame2Item4Cooldown {
 }
 SplitStack = <function> defined @FrameXML\ContainerFrame.lua:1086
}
id = "158923"
quality = "2"
new = false
quest = nil
questID = false
paid = false
r = nil
g = nil
b = nil
(*temporary) = true
(*temporary) = <table> {
 Scanner = LibItemSearchTooltipScanner {
 }
 Matches = <function> defined @Bagnon\external\Wildpants\libs\LibItemSearch-1.2\LibItemSearch-1.2.lua:19
 TooltipLine = <function> defined @Bagnon\external\Wildpants\libs\LibItemSearch-1.2\LibItemSearch-1.2.lua:41
 TooltipPhrase = <function> defined @Bagnon\external\Wildpants\libs\LibItemSearch-1.2\LibItemSearch-1.2.lua:27
 InSet = <function> defined @Bagnon\external\Wildpants\libs\LibItemSearch-1.2\LibItemSearch-1.2.lua:31
 Tooltip = <function> defined @Bagnon\external\Wildpants\libs\LibItemSearch-1.2\LibItemSearch-1.2.lua:23
 BelongsToSet = <function> defined @Bagnon\external\Wildpants\libs\LibItemSearch-1.2\LibItemSearch-1.2.lua:78
 Filters = <table> {
 }
}
(*temporary) = "|cff1eff00|Hbattlepet:158923:245:2:9:0:0:0x0|h[158923]|h|r"
(*temporary) = nil
(*temporary) = false
(*temporary) = "|cff1eff00|Hbattlepet:158923:245:2:9:0:0:0x0|h[158923]|h|r"
(*temporary) = "attempt to compare number with string"
Addon = <table> {
 GetOwnerColorString = <function> defined @Bagnon\external\Wildpants\core\owners.lua:56
 SearchFrame = <unnamed> {
 }
 EnableModule = <function> defined @Accountant\Libs\AceAddon-3.0\AceAddon-3.0.lua:363
 modules = <table> {
 }
 ToggleFrame = <function> defined @Bagnon\external\Wildpants\core\frames.lua:43
 IterateEmbeds = <function> defined @Accountant\Libs\AceAddon-3.0\AceAddon-3.0.lua:473
 UpdateFrames = <function> defined @Bagnon\external\Wildpants\core\frames.lua:39
 ShowBag = <function> defined @Bagnon\external\Wildpants\core\frames.lua:83
 SetDefaultModulePrototype = <function> defined @Accountant\Libs\AceAddon-3.0\AceAddon-3.0.lua:440
 defaultModuleState = true
 IsEnabled = <function> defined @Accountant\Libs\AceAddon-3.0\AceAddon-3.0.lua:482
 Frame = <unnamed> {
 }
 OptionsToggle = <unnamed> {
 }
 DisableModule = <function> defined @Accountant\Libs\AceAddon-3.0\AceAddon-3.0.lua:381
 Bag = <unnamed> {
 }
 StartupSettings = <function> defined @Bagnon\external\Wildpants\core\settings.lua:96
 SetCurrentProfile = <function> defined @Bagnon\external\Wildpants\core\settings.lua:152
 UnregisterMessage = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 UpdateSettings = <function> defined @Bagnon\external\Wildpants\core\settings.lua:133
 BagToggle = <unnamed> {
 }
 UnregisterSignal = <function> defined @Bagnon\external\Wildpants\core\classes.lua:23
 ShowFrame = <function> defined @Bagnon\external\Wildpants\core\frames.lua:51
 enabledState = true
 RegisterEvent = <function> defined @DataStore

**Comment by Sibrylla** [comment]
I am getting a similar if not the same error.  I have tried to recreate the problem but so far haven't been able to. (Error Msg is Below)
Also not all the tabs show up 1-4 do but 5-8 sometimes do sometimes don't. 

Message: ...Bagnon\external\Wildpants\features\tooltipCounts.lua:74: attempt to index field '?' (a nil value)
Time: Mon Sep 17 19:45:06 2018
Count: 28
Stack: ...Bagnon\external\Wildpants\features\tooltipCounts.lua:74: attempt to index field '?' (a nil value)

Locals:

**Comment by Jaliborc** [comment]
I seriously doubt that is the error numbered 1, just the snowball effect
