### ISSUE TITLE
Void Storage broken (completely unusable)

### ISSUE THREAD

**Issue by seascape195** [tullamods/Bagnon#811]
**Running Software (please complete the following information):**
 - Game patch [e.g. Build 8.0.1.27178] 8.1.x Current
 - Addon version: Current

**Describe the bug**
When opening Void Storage with Bagnon installed, every slot as of recent update to it, now complete unusable.  Has Exclamation points in every slot.  Had to disable addon in order to use Void Storage again.

**Comment by Phylazian** [comment]
https://github.com/tullamods/Bagnon/issues/800

It is all of Bagnon, unless you somehow got the others to work properly

**Comment by jemmers** [comment]
This happening to me in all instances, bags, bank, guild bank and void storage.  Please fix this.

[https://i.imgur.com/p2RSLHd.png](url)

**Comment by dafergu2** [comment]
I have a temp fix locally.  Here's a link the my reply in another (#804 ).

https://github.com/tullamods/Bagnon/issues/804#issuecomment-422239749

**Comment by jemmers** [comment]
> I have a temp fix locally. Here's a link the my reply in another (#804 ).
> 
> [#804 (comment)](https://github.com/tullamods/Bagnon/issues/804#issuecomment-422239749)

This did not fix my issue, as my issue is with the entire addon showing this way.
