### ISSUE TITLE
Void Storage

### ISSUE THREAD

**Issue by serrufs** [tullamods/Bagnon#816]
http://jpegshare.net/images/58/b1/58b1b462dafe1a23d2a03ea28bd3f7fc.jpg
![default](https://user-images.githubusercontent.com/15975674/45922726-feb29880-bedc-11e8-9c8c-86830e2c3c95.png)

**Comment by DasAoD** [comment]
Same here.

**Comment by serrufs** [comment]
![default](https://user-images.githubusercontent.com/15975674/45922721-d62a9e80-bedc-11e8-9b07-7448f5a76e30.png)

**Comment by jemmers** [comment]
Known issue already, several of us waiting for the update, there is a previous thread where someone suggested a possible solution

**Comment by DasAoD** [comment]
> 
> 
> Known issue already, several of us waiting for the update, there is a previous thread where someone suggested a possible solution
> 
> See Issue 804 and 811

Thanks for the hint.

[#804 (comment)](https://github.com/tullamods/Bagnon/issues/804#issuecomment-422239749)
> I fixed this locally by updating the following file:
> `/Applications/World of Warcraft/Interface/AddOns/Bagnon_VoidStorage/components/item.lua`
> 
> I added this line to the very end:
> 
> `function ItemSlot:IsPaid() end`
This solved the problem with the void storage for me.

**Comment by serrufs** [comment]
> This solved the problem with the void storage for me.

Yes, too, decided to problem

**Comment by darkravin70** [comment]
Can we get someone to pull there heads out of there butts and fix this stupid thing....we are not curing cancer here

**Comment by bradac** [comment]
Still broken in version 8.0.7 surprised this issue has gone on for this long.

**Comment by Tuller** [comment]
I have this in the fork I'm working off of:
https://github.com/tuller/Bagnon_VoidStorage
