### ISSUE TITLE
Dismissing pet

### ISSUE THREAD

**Issue by diogcosta** [tullamods/Bagnon#818]
**Running Software (please complete the following information):**
 - Addon version 8.0.6

**Describe the bug**
Ocasionally, when I try to dismiss my pet, this error appears. To fix it I have to log out and log in again.

**Error Logs**
Date: 2018-09-22 12:49:39
ID: 1
Error occured in: AddOn: Bagnon
Count: 1
Message: Error: AddOn Bagnon attempted to call a forbidden function (CastSpellByID()) from a tainted execution path.
Debug:
   [C]: CastSpellByID()
   ..\FrameXML\UnitPopup.lua:1701: func()
   ..\FrameXML\UIDropDownMenu.lua:935: UIDropDownMenuButton_OnClick()
   [string "*:OnClick"]:1:
      [string "*:OnClick"]:1
Locals:
None
AddOns:
  Swatter, v8.0.6162 (SwimmingSeadragon)
  AngryWorldQuests, v
  AucAdvanced, v8.0.6122 (SwimmingSeadragon)
  AucFilterBasic, v8.0.6149 (SwimmingSeadragon)
  AucScanData, v8.0.6150 (SwimmingSeadragon)
  AucStatHistogram, v8.0.6151 (SwimmingSeadragon)
  AucStatiLevel, v8.0.6155 (SwimmingSeadragon)
  AucStatPurchased, v8.0.6152 (SwimmingSeadragon)
  AucStatSimple, v8.0.6153 (SwimmingSeadragon)
  AucStatStdDev, v8.0.6154 (SwimmingSeadragon)
  AucUtilFixAH, v8.0.6156 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.0.6
  DBMCore, v@project-version@
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DejaCharacterStats, v800b109
  Details, v
  DetailsDmgRank, v
  DetailsDpsTuning, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsRaidInfoEmeraldNightmare, v
  DetailsRaidInfoNighthold, v
  DetailsRaidInfoTombOfSargeras, v
  DetailsRaidInfoTrialOfValor, v
  DetailsStreamer, v
  DetailsTimeAttack, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  EasyScrap, v8
  Enchantrix, v8.0.6158 (SwimmingSeadragon)
  EnchantrixBarker, v7.7.6000 (SwimmingSeadragon)
  Informant, v8.0.6159 (SwimmingSeadragon)
  KHunterTimers, v4.3.1
  LeatrixPlus, v8.0.11
  Omen, v3.2.0
  RCLootCouncil, v2.9.0
  SlideBar, v8.0.6160 (SwimmingSeadragon)
  Stubby, v8.0.6161 (SwimmingSeadragon)
  WorldQuestTracker, v
  BlizRuntimeLib_enUS v8.0.1.80000 <none>
  (ck=53d)

**Comment by Tuller** [comment]
I think this might be resolved by the taint issues Blizzard fixed in 8.1
