### ISSUE TITLE
no access to guild bank tabs 5,6,and 7. possible guild bank tab 8 on mains and alts. 

### ISSUE THREAD

**Issue by Jongar2** [tullamods/Bagnon#820]
**Running Software (please complete the following information):**
 - Game patch [e.g. Build 8.0.1.27178]
 - Addon version

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Error Logs**
If applicable, add the first error message (labeled 1/Many) that appeared.

**Additional context**

**Comment by Jaliborc** [comment]
https://www.patreon.com/posts/looking-for-for-21771493
