### ISSUE TITLE
How to reset bagbrother

### ISSUE THREAD

**Issue by newishjazi** [tullamods/Bagnon#822]
**Running Software (please complete the following information):**
 - Just reinstalled bagnon today to try to fix the problem, so my version should be up to date.

**Describe the bug**
I had a character name change and now my previous name shows up on the item tooltips along with my current name.

**To Reproduce**
It's just in my bags and in my bank on almost every item.

**Expected behavior**
I expected bagnon to show only my current character's items but instead it also shows the exact same items for my previous names

**Screenshots**
I can add a screenshot if needed but I feel like this shouldn't be as difficult to fix as it has been.

**Comment by LudiusMaximus** [comment]
I think it must be this file:
World of Warcraft\WTF\Account\<Your Account>\SavedVariables\BagBrother.lua

Open and edit it to change the name manually.
Or delete the file completely to have it rebuilt.

**Comment by newishjazi** [comment]
Perfect, thank you
