### ISSUE TITLE
Character icon missing and Total gold = 0 on some realms

### ISSUE THREAD

**Issue by REBfrench** [tullamods/Bagnon#825]
Hello,
Thanks for this add-on, but we still can't see the character icon on some realms, for instance Confrérie du Thorium in France, maybe because of the "é".
If others players have the same problem, please list the realms name and country in comment.
Best regards.

**Comment by brotus35** [comment]
Hello,
i have the same problem on all of my chars on the german server area52.

**Comment by Drazielus** [comment]
Hello,
i have the same problem on all of my chars on the french server "Chants éternels".
![2018-10-24 19_02_26-world of warcraft](https://user-images.githubusercontent.com/44444098/47448405-38b6d900-d7c0-11e8-8c96-80d4170b9426.png)
