### ISSUE TITLE
Error Disenchanting item from bag

### ISSUE THREAD

**Issue by DKDninja420** [tullamods/Bagnon#832]
**Running Software (please complete the following information):**
 - Game patch [e.g. Build 8.0.1.27178]
 - Addon version

**Describe the bug**

**To Reproduce**
clicked disenchant, opened bag via bag bar, clicked item to disenchant, error, reloaded UI error not duplicatable at this time

**Expected behavior**

**Screenshots**

**Error Logs**
If applicable, add the first error message (labeled 1/Many) that appeared.
Date: 2018-10-26 13:39:09
ID: 1
Error occured in: AddOn: Bagnon
Count: 1
Message: Error: AddOn Bagnon attempted to call a forbidden function (UNKNOWN()) from a tainted execution path.
Debug:
   [C]: ?
   [C]: ?
   [C]: ?
   [C]: ?
   [C]: UseContainerItem()
   ..\FrameXML\ContainerFrame.lua:1243: ContainerFrameItemButton_OnClick()
   [string "*:OnClick"]:12:
      [string "*:OnClick"]:1
   [C]: ?
Locals:
None
AddOns:
  Swatter, v8.0.6162 (SwimmingSeadragon)
  AceGUI30SelectablePanel, vv1.0-alpha2
  AddOnSkins, v3.93
  Atlas, vv1.44.03
  AtlasArena, vv1.07.02
  AtlasBattlegrounds, vv1.44.00
  AtlasBurningCrusade, vv1.44.00
  AtlasCataclysm, vv1.44.00
  AtlasClassicWoW, vv1.44.00
  AtlasClassOrderHalls, vv1.44.00
  AtlasDungeonLocs, vv1.44.00
  AtlasLegion, vv1.44.00
  AtlasMistsofPandaria, vv1.44.00
  AtlasOutdoorRaids, vv1.44.00
  AtlasScenarios, vv1.44.00
  AtlasTransportation, vv1.44.00
  AtlasWarlordsofDraenor, vv1.44.00
  AtlasWorldEvents, vv3.24
  AtlasWrathoftheLichKing, vv1.44.00
  AtlasLoot, vv8.08.01
  AtlasLootBattleforAzeroth, vv8.08.01
  AtlasLootBurningCrusade, vv8.08.01
  AtlasLootCataclysm, vv8.08.01
  AtlasLootClassic, vv8.08.01
  AtlasLootLegion, vv8.08.01
  AtlasLootMistsofPandaria, vv8.08.01
  AtlasLootWarlordsofDraenor, vv8.08.01
  AtlasLootWrathoftheLichKing, vv8.08.01
  AtlasQuest, v4.11.00
  AucAdvanced, v8.0.6122 (SwimmingSeadragon)
  AucFilterBasic, v8.0.6149 (SwimmingSeadragon)
  AucScanData, v8.0.6150 (SwimmingSeadragon)
  AucStatHistogram, v8.0.6151 (SwimmingSeadragon)
  AucStatiLevel, v8.0.6155 (SwimmingSeadragon)
  AucStatPurchased, v8.0.6152 (SwimmingSeadragon)
  AucStatSimple, v8.0.6153 (SwimmingSeadragon)
  AucStatStdDev, v8.0.6154 (SwimmingSeadragon)
  AucUtilFixAH, v8.0.6156 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.0.7
  Bartender4, v4.8.1
  BeanCounter, v8.0.6157 (SwimmingSeadragon)
  BlizzBuffsFacade, v8.0.1
  CollectionShop, v3.06
  DBMArchaeology, v
  DBMBossSounds, vv1.0
  DBMCore, v8.0.13
  DBMCountdownPackMarioKart, v1.2
  DBMCountPackHoTS, v1.5
  DBMCountPackOverwatch, v1.4.2
  DBMDefaultSkin, v
  DBMInterrupts, v7.3.0
  DBMLegendaryDummy, v2.0
  DBMLootReminder, v1.4
  DBMNightholdDBH, v
  DBMPartyMoP, v
  DBMSMGEventsPack, v1.3
  DBMSoundEventsPack, v1.4
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  DBMVPEnglishfemale, v8.0.5
  DBMVPEnglishmale, v8.0.5
  DBMWorldEvents, v
  Decursive, v2.7.6.1
  Details, v
  DetailsDmgRank, v
  DetailsDpsTuning, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTimeAttack, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  EasyScrap, v18
  ElvUI, v10.82
  ElvUICustomTweaks, v1.38
  ElvUIDataConfig, v1.04
  ElvUIExtraDataTexts, v1.9.3
  ElvUIMicrobar, v1.85
  ElvUISLE, v3.471
  Enchantrix, v8.0.6158 (SwimmingSeadragon)
  Grail, v097
  GrailAchievements, v011
  GrailQuestsenUS, v27178
  GrailReputations, v007
  GSE, v2402
  GSEGUI, v2402
  GSELDB, v2402
  GTFO, v4.46.9
  HandyNotes, vv1.5.3
  HandyNotesAchievements, v0.4.21
  HandyNotesArathi, v0.1.0
  HandyNotesBattleForAzerothAchievments, vv7
  HandyNotesBattleForAzerothTreasures, v1
  HandyNotesBFAHFTracker, v8.0.4
  HandyNotesDirections, v1
  HandyNotesDungeonLocations, v1.43
  HandyNotesHallowsEnd, vv1.4.2
  HandyNotesMoleMachine, v1.1.2
  HandyNotesWarfrontTreasures, v1
  HealBot, v8.0.1.10
  HealBotTips, v8.0.1.10
  Hekili, vv8.0.1-39
  Informant, v8.0.6159 (SwimmingSeadragon)
  KuiMedia, v
  KuiNameplates, v
  KuiNameplatesCore, v
  LootAppraiser, vv1.9.2
  Ludwig, v8.0.0
  Masque, v8.0.1
  MasqueAbstract, vwow6.0.2-2.0
  MasqueApathy, v8.0.0
  MasqueAzerite, v1.0
  MasqueAzona, vv1
  MasqueBamboo, v1
  MasqueCainyx, v8.0.0
  MasqueCaith, v8.0.0
  MasqueCards, v6.2.0
  MasqueCirque, v8.0.0
  MasqueCleanIcons, v1.5
  MasqueCleanUI, v8.0.1
  MasqueDark, v3.1.0
  MasqueDarkscail, v1
  MasqueDiabloIII, v1.6
  MasqueDiabolic, v1.0
  MasqueElegance, v6.2.0
  MasqueEleganceLegion, v1.0
  MasqueEleganceLegion2, v1.0
  MasqueElvUIesque, v1.0
  MasqueEntropy, v8.0.0
  MasqueFlatSquares, v1.0.8
  MasqueGears, v8.0.0
  MasqueGmSr, v801-2018081101
  MasqueGoldpaw, v1.0
  MasqueGrunge, v1
  MasqueHelloKitty, v7.0.00
  MasqueImoen, v1.0.1
  MasqueJigsaw, v6.2.0
  MasqueKenzo, v2.0.0
  MasqueLiteStep, v8.0.0
  MasqueMuq, v7.2.1
  MasqueOnyx, v8.0.0
  masqueparabole, v6.0.0.1
  MasqueRaeli, v9
  MasqueRenaitre, vv7.0.3
  MasqueSerenity, v8.0.0
  MasqueShadow, vv6.2.2
  MasqueSimpleSquare, v7.1.0.0
  MasqueSleek, v6.2.0
  MasqueSonata, v1.0.2
  MasqueStylo, vv7.2.0
  MasqueTones, v6.2.0
  MasqueTrinity, vCentauri-5
  MasqueVista, v2.0.4
  MikScrollingBattleText, v5.7.149
  NPCScan, v8.0.1.13
  OmniCC, v8.0.9
  OPie, vVanilla 7
  OPieMasque, v7.3.5.0
  Pawn, v2.2.30
  ProjectAzilroka, v1.32
  Quartz, v3.4.0
  SexyMap, vv8.0.8
  ShadowedUFFacade, v1.5.3
  ShadowedUnitFrames, vv4.2.1
  SharedMediaAdditionalSounds, v7.0
  SimpleRareElite, v1.29
  Simulationcraft, v1.10.7
  SlideBar, v8.0.6160 (SwimmingSeadragon)
  Stubby, v8.0.6161 (SwimmingSeadragon)
  SubSpec, v2.1.5.0
  SunnArt, v3.79
  SunnArtPack3, v1.22
  SunnArtPack5, v1.22
  TheUndermineJournal, v5.4.20181023
  TradeSkillMaster, vv4.4.6
  TradeSkillMasterAppHelper, vv4.0
  WeakAuras, v2.8.1
  Wholly, v068
  WorldQuestsList, v81
  WorldQuestTracker, v
  XPerlFacade, v4.0.1
  BlizRuntimeLib_enUS v8.0.1.80000 <none>
  (ck=1323)

**Additional context**

**Comment by Tuller** [comment]
I think this one was likely fixed by 8.1
