### ISSUE TITLE
Do not save the number of things stored by the character, if the quality of this thing is "gray".

### ISSUE THREAD

**Issue by Drui7** [tullamods/Bagnon#845]
**Describe the solution you'd like**
Do not store data on the number of gray things. When you hover on a gray object does not display the number of the same for other characters.

**Additional context**
These things always give a trader, do not see the point of wasting resources on calculating and storing data on the "gray" items.

**Comment by Jaliborc** [comment]
Declined. Keeping track of gray items is necessary to accurately display the inventories, banks, etc offline. Quantities are counted on the fly.
