### ISSUE TITLE
Bagnon\external\Wildpants\localization\ru.lua

### ISSUE THREAD

**Issue by Drui7** [tullamods/Bagnon#846]
Variables for localization are not valid, localization does not work.

How does it look in English:
--item tooltips
L.TipCountEquip = 'Equipped: %d'
L.TipCountBags = 'Bags: %d'
L.TipCountBank = 'Bank: %d'
L.TipCountVault = 'Vault: %d'
L.TipCountGuild = 'Guild: %d'
L.TipDelimiter = '|'

It looked wrong in Russian, so English words were included by default. That's right (I made myself and everything works):

L.TipCountEquip = 'Надето: %d'
L.TipCountBags = 'Сумки: %d'
L.TipCountBank = 'Банк: %d'
L.TipCountVault = 'Бездна: %d'
L.TipCountGuild = 'Гильдия: %d'
L.TipDelimiter = '|'

So it was, it does NOT work:
--itemcount tooltips
L.TipCount1 = 'Надето: %d'
L.TipCount2 = 'Сумки: %d'
L.TipCount3 = 'Банк: %d'
L.TipCount4 = 'Бездна: %d'
L.TipDelimiter = '|'

**Comment by JinShepard** [comment]
I get this when I check other chars their bags, sometimes it takes one time to check another char sometimes two but it always happens.

Message: ...AddOns\Bagnon\external\Wildpants\components\item.lua:267: attempt to compare number with string
Time: Tue Dec 18 09:35:59 2018
Count: 1
Stack: ...AddOns\Bagnon\external\Wildpants\components\item.lua:267: attempt to compare number with string
...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:613: in function <...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:575>
[C]: ?
...AddOns\Bagnon\external\Wildpants\components\item.lua:267: in function `UpdateBorder'
...AddOns\Bagnon\external\Wildpants\components\item.lua:228: in function <...AddOns\Bagnon\external\Wildpants\components\item.lua:222>
[C]: in function `Update'
...AddOns\Bagnon\external\Wildpants\components\item.lua:124: in function <...AddOns\Bagnon\external\Wildpants\components\item.lua:119>
[C]: in function `Show'
...AddOns\Bagnon\external\Wildpants\components\item.lua:30: in function `New'
...s\Bagnon\external\Wildpants\components\itemFrame.lua:119: in function <...s\Bagnon\external\Wildpants\components\itemFrame.lua:108>

Locals: errMsg = "...AddOns\Bagnon\external\Wildpants\components\item.lua:267: attempt to compare number with string"
errorTime = 2251436.474500
tsmErrMsg = nil
oldModule = nil
private = <table> {
 AddonBlockedEvent = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:378
 num = 0
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:106
 origErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:295
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:355
 SantizeErrorReportString = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:386
 errorFrame = <unnamed> {
 }
}
MAX_STACK_DEPTH = 50
TSM = <table> {
}

**Comment by Jaliborc** [comment]
Using warcraft variables in composite phrases isn't guaranteed to work on all locales.
Thank you for the locale updates
