### ISSUE TITLE
Bagnon lua error

### ISSUE THREAD

**Issue by Apoxiosis** [tullamods/Bagnon#847]
Bagnon\external\Wildpants\features\tooltipCounts.lua:74: attempt to index field '?' (a nil value)

just kinda happens when im in my character sheet and bags

**Comment by Blixx** [comment]
Message: ...Bagnon\external\Wildpants\features\tooltipCounts.lua:74: attempt to index field '?' (a nil value)
Time: Wed Jan 30 10:02:42 2019
Count: 1
Stack: ...Bagnon\external\Wildpants\features\tooltipCounts.lua:74: attempt to index field '?' (a nil value)
[C]: ?
...Bagnon\external\Wildpants\features\tooltipCounts.lua:74: in function <...Bagnon\external\Wildpants\features\tooltipCounts.lua:58>
...Bagnon\external\Wildpants\features\tooltipCounts.lua:136: in function <...Bagnon\external\Wildpants\features\tooltipCounts.lua:133>
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: in function `SetBagItem'
Interface\FrameXML\ContainerFrame.lua:1373: in function `ContainerFrameItemButton_OnEnter'
...AddOns\Bagnon\external\Wildpants\components\item.lua:374: in function `ShowTooltip'
...AddOns\Bagnon\external\Wildpants\components\item.lua:206: in function <...AddOns\Bagnon\external\Wildpants\components\item.lua:199>

Locals:

**Comment by wienfuchs** [comment]
Reproduced with 8.1.1 and 8.1.2; both do not work for me; both throw this error Bagnon\external\Wildpants\features\tooltipCounts.lua:74: attempt to index field '?' (a nil value)

**Comment by Blixx** [comment]
Getting the same error in ver 8.1.2
Anytime you loot something, mouse over anything in inventory, this error pops up.

Message: ...Bagnon\external\Wildpants\features\tooltipCounts.lua:74: attempt to index field '?' (a nil value)
Time: Sat Feb  2 08:42:04 2019
Count: 7
Stack: ...Bagnon\external\Wildpants\features\tooltipCounts.lua:74: attempt to index field '?' (a nil value)
[C]: ?
...Bagnon\external\Wildpants\features\tooltipCounts.lua:74: in function <...Bagnon\external\Wildpants\features\tooltipCounts.lua:58>
...Bagnon\external\Wildpants\features\tooltipCounts.lua:136: in function <...Bagnon\external\Wildpants\features\tooltipCounts.lua:133>
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: in function `SetBagItem'
Interface\FrameXML\ContainerFrame.lua:1373: in function `ContainerFrameItemButton_OnEnter'
...AddOns\Bagnon\external\Wildpants\components\item.lua:374: in function `ShowTooltip'
...AddOns\Bagnon\external\Wildpants\components\item.lua:206: in function <...AddOns\Bagnon\external\Wildpants\components\item.lua:199>

Locals:

**Comment by Blixx** [comment]
Update: I just loaded TradeSkillMaster addon now the error no longer happens

**Comment by wienfuchs** [comment]
Fixed in 8.1.4 - running smoothly now. Thanks :)

**Comment by Jaliborc** [comment]
Yeah, there was something weird with 8.1.2 and half of my changes didn't go trough. 8.1.3 had a minor issue.

**Comment by Enessim** [comment]
I got this LUA error : 
I hope it will help! :) 
Message: ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:187: hooksecurefunc(): BagSlotButton_UpdateChecked is not a function
Time: Fri Mar 22 20:16:13 2019
Count: 1
Stack: ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:187: hooksecurefunc(): BagSlotButton_UpdateChecked is not a function
[C]: in function `hooksecurefunc'
...s\Bagnon\external\Wildpants\features\autoDisplay.lua:187: in function `HookInterfaceEvents'
...s\Bagnon\external\Wildpants\features\autoDisplay.lua:14: in function <...s\Bagnon\external\Wildpants\features\autoDisplay.lua:12>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:558: in function `EnableAddon'
...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:571: in function `EnableAddon'
...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:651: in function <...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:446: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:489: in function `CombatLog_LoadUI'
Interface\FrameXML\UIParent.lua:1194: in function <Interface\FrameXML\UIParent.lua:1090>

Locals: <none>
