### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xiaoxiaoli66** [tullamods/Bagnon#850]
213x ...Bagnon\external\Wildpants\features\tooltipCounts.lua:74: attempt to index field '?' (a nil value)
...Bagnon\external\Wildpants\features\tooltipCounts.lua:74: in function <...Bagnon\external\Wildpants\features\tooltipCounts.lua:58>
...Bagnon\external\Wildpants\features\tooltipCounts.lua:136: in function <...Bagnon\external\Wildpants\features\tooltipCounts.lua:133>
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: in function `SetGuildBankItem'
Bagnon_GuildBank\components\item.lua:91: in function `UpdateTooltip'
Bagnon_GuildBank\components\item.lua:77: in function <Bagnon_GuildBank\components\item.lua:74>

Locals:
tooltip = GameTooltip {
 0 = <userdata>
 SetCurrencyByID = <function> defined =[C]:-1
 SetPvpTalent = <function> defined =[C]:-1
 SetExistingSocketGem = <function> defined =[C]:-1
 SetHyperlink = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined =[C]:-1
 SetVoidItem = <function> defined =[C]:-1
 SetVoidDepositItem = <function> defined =[C]:-1
 SetOwner = <function> defined =[C]:-1
 SetArtifactPowerByID = <function> defined =[C]:-1
 comparing = false
 SetSocketGem = <function> defined =[C]:-1
 __tamedCounts = false
 TopOverlay = <unnamed> {
 }
 CIMI_tooltipWritten = true
 SetUnitDebuff = <function> defined =[C]:-1
 SetHeirloomByItemID = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 Hide = <function> defined =[C]:-1
 SetToyByItemID = <function> defined =[C]:-1
 SetTrainerService = <function> defined =[C]:-1
 SetVoidWithdrawalItem = <function> defined =[C]:-1
 SetItemByID = <function> defined =[C]:-1
 SetInboxItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 FadeOut = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 SetQuestLogItem = <function> defined =[C]:-1
 SetCurrencyTokenByID = <function> defined =[C]:-1
 SetUnitBuff = <function> defined =[C]:-1
 SetSpellByID = <function> defined =[C]:-1
 SetTradePlayerItem = <function> defined =[C]:-1
 SetCurrencyToken = <function> defined =[C]:-1
 SetSendMailItem = <function> defined =[C]:-1
 SetRecipeRankInfo = <function> defined =[C]:-1
 updateTooltip = 0.110000
 SetInventoryItem = <function> defined =[C]:-1
 SetTalent = <function> defined =[C]:-1
 SetTradeTargetItem = <function> defined =[C]:-1
 SetLootRollItem = <function> defined =[C]:-1
 SetUnitAura = <function> defined =[C]:-1
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetAuctionSellItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 needsReset = false
 SetAction = <function> defined =[C]:-1
 SetRecipeResultItem = <function> defined =[C]:-1
 BottomOverlay = <unnamed> {
 }
 SetAuctionItem = <function> defined =[C]:-1
}
link = "|cff0070dd|Hitem:21804::::::::120:105::::::|h[元素愤怒罩帽]|h|r"
itemID = 21804
players = 0
total = 0
(for generator) = <function> defined @Bagnon\external\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:101
(for state) = nil
(for control) = "® 天下灬"
owner = "® 天下灬"
info = <table> {
 isguild = true
 name = "天下灬"
 faction = "Alliance"
 cached = false
 realm = "安苏"
}
color = "|cfffad000%s|r"
(*temporary) = nil
(*temporary) = <table> {
 isguild = true
 name = "天下灬"
 faction = "Alliance"
 cached = false
 realm = "安苏"
}
(*temporary) = <table> {
 GetRGB = <function> defined @SharedXML\Util.lua:663
 OnLoad = <function> defined @SharedXML\Util.lua:652
 b = 0
 GenerateHexColorMarkup = <function> defined @SharedXML\Util.lua:694
 WrapTextInColorCode = <function> defined @SharedXML\Util.lua:698
 GenerateHexColor = <function> defined @SharedXML\Util.lua:690
 GetRGBA = <function> defined @SharedXML\Util.lua:671
 IsEqualTo = <function> defined @SharedXML\Util.lua:656
 g = 0.640000
 r = 0.770000
 SetRGBA = <function> defined @SharedXML\Util.lua:679
 GetRGBAsBytes = <function> defined @SharedXML\Util.lua:667
 SetRGB = <function> defined @SharedXML\Util.lua:686
 GetRGBAAsBytes = <function> defined @SharedXML\Util.lua:675
}
(*temporary) = 1.410000
(*temporary) = 325.531915
(*temporary) = "|cfffad000%s|r"
(*temporary) = "%s|r"
(*temporary) = 250.659574
(*temporary) = 208.340426
(*temporary) = 0
(*temporary) = "|cfffad000"
(*temporary) = 255
(*temporary) = 0
(*temporary) = 2
(*temporary) = nil
(*temporary) = 0
(*temporary) = "attempt to index field '?' (a nil value)"
Addon = <table> {
 GetOwnerColorString = <function> defined @Bagnon\external\Wildpants\core\owners.lua:56
 SearchFrame = <unnamed> {
 }
 EnableModule = <function> defined @Int

**Comment by Blixx** [comment]
Message: ...Bagnon\external\Wildpants\features\tooltipCounts.lua:74: attempt to index field '?' (a nil value)
Time: Wed Jan 30 10:02:42 2019
Count: 1
Stack: ...Bagnon\external\Wildpants\features\tooltipCounts.lua:74: attempt to index field '?' (a nil value)
[C]: ?
...Bagnon\external\Wildpants\features\tooltipCounts.lua:74: in function <...Bagnon\external\Wildpants\features\tooltipCounts.lua:58>
...Bagnon\external\Wildpants\features\tooltipCounts.lua:136: in function <...Bagnon\external\Wildpants\features\tooltipCounts.lua:133>
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: in function `SetBagItem'
Interface\FrameXML\ContainerFrame.lua:1373: in function `ContainerFrameItemButton_OnEnter'
...AddOns\Bagnon\external\Wildpants\components\item.lua:374: in function `ShowTooltip'
...AddOns\Bagnon\external\Wildpants\components\item.lua:206: in function <...AddOns\Bagnon\external\Wildpants\components\item.lua:199>

Locals:

**Comment by Blixx** [comment]
Gettin the same error in ver 8.1.2
Anytime you loot something, mouse over anything in inventory, this error pops up.

Message: ...Bagnon\external\Wildpants\features\tooltipCounts.lua:74: attempt to index field '?' (a nil value)
Time: Sat Feb  2 08:42:04 2019
Count: 7
Stack: ...Bagnon\external\Wildpants\features\tooltipCounts.lua:74: attempt to index field '?' (a nil value)
[C]: ?
...Bagnon\external\Wildpants\features\tooltipCounts.lua:74: in function <...Bagnon\external\Wildpants\features\tooltipCounts.lua:58>
...Bagnon\external\Wildpants\features\tooltipCounts.lua:136: in function <...Bagnon\external\Wildpants\features\tooltipCounts.lua:133>
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: in function `SetBagItem'
Interface\FrameXML\ContainerFrame.lua:1373: in function `ContainerFrameItemButton_OnEnter'
...AddOns\Bagnon\external\Wildpants\components\item.lua:374: in function `ShowTooltip'
...AddOns\Bagnon\external\Wildpants\components\item.lua:206: in function <...AddOns\Bagnon\external\Wildpants\components\item.lua:199>

Locals:

**Comment by Blixx** [comment]
Update: I loaded TradeSkillMaster addon and the error no longer happens
