### ISSUE TITLE
Bagnon Total Money only not working on my main server

### ISSUE THREAD

**Issue by ShadowJester88** [tullamods/Bagnon#856]
When the bag tab is open, in the bottom corner, where it shows your Server total money, it only doesn't work on my main server, Kil'Jaeden, on every other server ive checked it seems to work fine, I'm not sure if its because its KJ, if its because its my main server or if its because I have allied races on that server for both factions, Idk what it is but its super odd that it only is broken on the server I mainly play on.

Is there any way to fix it?

**Comment by Tuller** [comment]
For server specific weirdness, it’s probably best to track things by grabbing the player’s realm from UnitFullName(“player”). The second return of the function is a realm name formatted the same way as in GetAutocompleteRealms()

**Comment by Jaliborc** [comment]
I just learned something today. had no clue UnitFullName did that. If it does, it makes things much simpler.
