### ISSUE TITLE
gold tooltip shows nothing / missing alt inventories button

### ISSUE THREAD

**Issue by bravetothebone** [tullamods/Bagnon#861]
Switched to all my chars (12x) nothing changed / reloaded / closed game / checked for new uptades / still same

![2019-01-28_232506](https://user-images.githubusercontent.com/47124161/51867603-94ab7380-2354-11e9-8736-2a55909b953f.png)

![2019-01-28_232516](https://user-images.githubusercontent.com/47124161/51867607-983efa80-2354-11e9-9262-bfdfb1cca77c.png)

**Comment by 41k0n** [comment]
Can confirm. Last version it didn't show my total gold for one character, now it's broken for everyone. Is it possible this has something to do with umlaute like Ä, Ö, Ü?

**Comment by jcadduono** [comment]
Temporary fix @ https://github.com/tullamods/Bagnon/issues/862#issuecomment-458428770
