### ISSUE TITLE
Reverse Bag Order and Reverse Slot Order does not change 

### ISSUE THREAD

**Issue by JJahoda** [tullamods/Bagnon#865]
**Running Software (please complete the following information):**
 - Game patch 8.1.0.29139
 - Addon version 8.1.1

**Describe the bug**
When I check or uncheck options Reverse Bag Order or Reverse Slot Order nothing happens. The items in bag does not change. In the previous version (8.1.0) checking or unchecking the options immediately change items in the bag.

**To Reproduce**
1. Open Back by clicking B button
2. Click on the configure button
3. In the Frame Settings - Appearance check or uncheck Reverse Bag Order or Reverse Slot Order.

**Expected behavior**
The same behavior like in version 8.1.0, checking or unchecking the button options, should change the bag item order.

**Screenshots**

**Error Logs**
If applicable, add the first error message (labeled 1/Many) that appeared.

**Additional context**

**Comment by JJahoda** [comment]
It looks like version 8.1.1 works correctly on server Magtheridon (there I have 7 alts), but on server "Chamber of Aspects" it does not work two atls, on others it works corectly (also 7 alts). These two alts was created during Legion expansion (DK and DH), but DH on Magtheridon works correctly (created in the same time like DH on Chamber of Aspects.

**Comment by adonna55** [comment]
I also have the issue - when I log into any character, the order I want my bags is wrong (regardless of reverse order/slot or visa versa), I just have to randomly click the options on and off to finally get it right and it never saves either when you jump from server to server :/ so every time I log on and I have to mess with it. EG. I'll have reverse bag/slot not selected and it's the fine, switch servers/same settings and its backwards. I'm at a loss :/
![wowscrnshot_013019_211740](https://user-images.githubusercontent.com/43224494/52028838-31494f00-24d6-11e9-8935-8469ce2593ee.jpg)
![wowscrnshot_013019_211236](https://user-images.githubusercontent.com/43224494/52028840-31494f00-24d6-11e9-917e-70a5bc4f87a7.jpg)
