### ISSUE TITLE
Number of columns no longer changes from 8 in current version

### ISSUE THREAD

**Issue by raysmith59** [tullamods/Bagnon#866]
Latest version 8.1.1 seems to have broken the ability to change number of columns, I have a handful of toons that use 12 instead of 8 but they have 8 columns (config still shows 12) and changing the config number doesn't actually change number of columns.

Based on a bit of further testing I think it's server-specific, servers with spaces in their names it doesn't work, one-word servers it does.

**Comment by Jaliborc** [comment]
Ok, I'll look into it.
