### ISSUE TITLE
Not showing alts info on bag

### ISSUE THREAD

**Issue by rau090** [tullamods/Bagnon#867]
**Running Software (please complete the following information):**
 - Game patch [e.g. Build 8.1.0.29139]
 - Addon version 8.1.1

**Describe the bug**
The information of alts bags is not showing

**To Reproduce**
1. Go to Bagon
2. Click over gold
3. See error - Total gold is 0

**Expected behavior**
I should show the total amount of gold across my chars

**Screenshots**
![image](https://user-images.githubusercontent.com/702758/52022035-34880f00-24c5-11e9-9001-33be69a381e4.png)

**Comment by Atollie** [comment]
The same here. Bagbrother does not work. I have ElvUI too.

**Comment by Riikah** [comment]
Same issue. I cannot view my alts bags or see my gold totals. I do not have ElvUI.

**Comment by fabiocm** [comment]
> Same issue. I cannot view my alts bags or see my gold totals. I do not have ElvUI.

the same problem and dont have ElvUi 
![wowscrnshot_013119_134627](https://user-images.githubusercontent.com/9159222/52073770-bed08180-255e-11e9-9124-bd7faf564f3a.jpg)

**Comment by Danderfluff** [comment]
+1. Also not showing alts for me. Gold is also 0 when mouseover. Not using ElvUI.
