### ISSUE TITLE
Bagnon 8.1.3 causes lua errors, version 8.1.2 does not

### ISSUE THREAD

**Issue by Benedictum** [tullamods/Bagnon#874]
Since the mod author felt like closing the previous reported issue without any comments or resolution, i figured i would repost the issue. after updating to 8.1.3 bagnon spews lua errors on mouseover of any item. 

Revert the mod to 8.1.2 and the errors disappear.

**Comment by Jaliborc** [comment]
Or you could have just realized 8.1.4 has been out for a while ;)
