### ISSUE TITLE
LUA error related to SetChecked when opening/closing bags in 8.1.5

### ISSUE THREAD

**Issue by raysmith59** [tullamods/Bagnon#882]
**Running Software (please complete the following information):**
 - Game: 8.1.5
 - Bagnon: 8.1.6

**Describe the bug**
LUA errors whenever opening or closing my bags.

**Error Logs**
15x ...s\Bagnon\external\Wildpants\components\inventory.lua:22: attempt to call method 'SetChecked' (a nil value)
...s\Bagnon\external\Wildpants\components\inventory.lua:22: in function `CheckBagButtons'
...s\Bagnon\external\Wildpants\components\inventory.lua:13: in function <...s\Bagnon\external\Wildpants\components\inventory.lua:11>
[C]: ?
[C]: in function `Show'
FrameXML\UIParent.lua:3166: in function <FrameXML\UIParent.lua:3161>
[C]: in function `ShowUIPanel'
...aceBagnon\external\Wildpants\core\frames.lua:55: in function `ShowFrame'
...s\Bagnon\external\Wildpants\features\autoDisplay.lua:166: in function <...s\Bagnon\external\Wildpants\features\autoDisplay.lua:165>
[C]: in function `OpenAllBags'
FrameXML\MailFrame.lua:63: in function <FrameXML\MailFrame.lua:50>
[C]: in function `TurnOrActionStop'
[string "TURNORACTION"]:4: in function <[string "TURNORACTION"]:1>

Locals:
self = BagnonFrameinventory {
 frameID = "inventory"
 searchToggle = <unnamed> {
 }
 moneyFrame = BagnonFrameinventoryMoneyFrame {
 }
 sortButton = <unnamed> {
 }
 searchFrame = <unnamed> {
 }
 brokerDisplay = <unnamed> {
 }
 itemFrame = <unnamed> {
 }
 0 = <userdata>
 profile = <table> {
 }
 closeButton = BagnonFrameinventoryCloseButton {
 }
 optionsToggle = <unnamed> {
 }
 titleFrame = <unnamed> {
 }
 bagToggle = <unnamed> {
 }
 ownerSelector = <unnamed> {
 }
 menuButtons = <table> {
 }
 quality = 0
}
checked = true
(*temporary) = nil
(*temporary) = MainMenuBarBackpackButton {
 0 = <userdata>
 PostOnLoad = <function> defined @FrameXML\ItemButtonTemplate.lua:169
 animIcon = <unnamed> {
 }
 ItemContextOverlay = <unnamed> {
 }
 PostOnShow = <function> defined @FrameXML\ItemButtonTemplate.lua:189
 GetItemContextMatchResult = <function> defined @FrameXML\MainMenuBarBagButtons.lua:5
 IconBorder = <unnamed> {
 }
 Count = MainMenuBarBackpackButtonCount {
 }
 icon = MainMenuBarBackpackButtonIconTexture {
 }
 MAParent = "BagButtonsMover"
 flyin = <unnamed> {
 }
 SetMatchesSearch = <function> defined @FrameXML\ItemButtonTemplate.lua:202
 UpdateItemContextOverlay = <function> defined @FrameXML\ItemButtonTemplate.lua:222
 GetBagID = <function> defined @FrameXML\MainMenuBarBagButtons.lua:9
 itemContextChangedCallbackIsSet = false
 itemContextMatchResult = 3
 itemContextChangedCallback = <function> defined @FrameXML\ItemButtonTemplate.lua:170
 RegisterCallback = <function> defined @FrameXML\ItemButtonTemplate.lua:175
 SlotHighlightTexture = <unnamed> {
 }
 IconOverlay = <unnamed> {
 }
 UnregisterCallback = <function> defined @FrameXML\ItemButtonTemplate.lua:182
 UpdateItemContextMatching = <function> defined @FrameXML\ItemButtonTemplate.lua:211
 searchOverlay = MainMenuBarBackpackButtonSearchOverlay {
 }
 GetMatchesSearch = <function> defined @FrameXML\ItemButtonTemplate.lua:207
 freeSlots = 57
 PostOnHide = <function> defined @FrameXML\ItemButtonTemplate.lua:198
}
(*temporary) = true
(*temporary) = "attempt to call method 'SetChecked' (a nil value)"

**Comment by Hangkiw** [comment]
You can check the [Issue#885](https://github.com/tullamods/Bagnon/issues/885) I posted a "edit/fix" while they release an official fix.

**Comment by raysmith59** [comment]
Yeah, I'd commented out lines 13 and 18 in inventory.lua and 179 and 180 in autoDisplay.LUA but hadn't updated my issues yet, those seem to be working as well for my purposes at least.

**Comment by Hangkiw** [comment]
@raysmith59 button issue? what it is exactly? Clicking the backpack buttons on the main bar menu? with the lines I edited everything is working

**Comment by goldpaw** [comment]
Tuller has a pull request in the Wildpants submodule that fixes any WoW patch 8.1.5 issues. So whenever Jaliborc gets time to review it, Bagnon will be updated for 8.1.5.
