### ISSUE TITLE
LUA Error in 8.1.5 related to BagShotButton_UpdateChecked

### ISSUE THREAD

**Issue by raysmith59** [tullamods/Bagnon#883]
Probably related to the previous one but not entirely sure so reporting it as well.

**Running Software (please complete the following information):**
 - Game patch 8.1.5
 - Addon version 8.1.6

**Describe the bug**
LUA error

**Error Logs**
3x ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:187: hooksecurefunc(): BagSlotButton_UpdateChecked is not a function
[C]: in function `hooksecurefunc'
...s\Bagnon\external\Wildpants\features\autoDisplay.lua:187: in function `HookInterfaceEvents'
...s\Bagnon\external\Wildpants\features\autoDisplay.lua:14: in function <...s\Bagnon\external\Wildpants\features\autoDisplay.lua:12>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
Accountant\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:558: in function `EnableAddon'
Accountant\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:571: in function `EnableAddon'
Accountant\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:651: in function <Accountant\Libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
APIAPIInterface-8.0.02.lua:408: in function <APIAPIInterface.lua:406>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
Accountant\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:558: in function `EnableAddon'
Accountant\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:651: in function <Accountant\Libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:446: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:565: in function `TimeManager_LoadUI'
FrameXML\UIParent.lua:1192: in function <FrameXML\UIParent.lua:1090>

**Comment by Vylithe** [comment]
Same issue

**Comment by nightness** [comment]
Same issue

**Comment by seascape195** [comment]
If okay editing code.. I posted screenshots of exactly what to change (at least as a workaround)

See https://github.com/tullamods/Bagnon/issues/885  <= click here

**Comment by cjmccormick** [comment]
How do I exactly edit it, go to file location edit with notepad or?

**Comment by goldpaw** [comment]
Tuller has a pull request in the Wildpants submodule that fixes any WoW patch 8.1.5 issues. So whenever Jaliborc gets time to review it, Bagnon will be updated for 8.1.5. I recommend just waiting for that instead of editing lines, at least for people unfamiliar with that sort of thing.

**Comment by seascape195** [comment]
> 
> 
> How do I exactly edit it, go to file location edit with notepad or?

I used 'Zeus IDE' editor
