### ISSUE TITLE
8.1.5 Error

### ISSUE THREAD

**Issue by BluespiritWoW** [tullamods/Bagnon#885]
New bug due to the 8.1.5 patch.

45x ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:187: hooksecurefunc(): BagSlotButton_UpdateChecked is not a function
[C]: in function `hooksecurefunc'
...s\Bagnon\external\Wildpants\features\autoDisplay.lua:187: in function `HookInterfaceEvents'
...s\Bagnon\external\Wildpants\features\autoDisplay.lua:14: in function <...s\Bagnon\external\Wildpants\features\autoDisplay.lua:12>
[C]: ?
...ns\AzeriteTooltip\libs\AceAddon-3.0\AceAddon-3.0-12.lua:70: in function <...ns\AzeriteTooltip\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
...ns\AzeriteTooltip\libs\AceAddon-3.0\AceAddon-3.0-12.lua:527: in function `EnableAddon'
...ns\AzeriteTooltip\libs\AceAddon-3.0\AceAddon-3.0-12.lua:540: in function `EnableAddon'
...ns\AzeriteTooltip\libs\AceAddon-3.0\AceAddon-3.0-12.lua:620: in function <...ns\AzeriteTooltip\libs\AceAddon-3.0\AceAddon-3.0.lua:605>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:446: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:565: in function `TimeManager_LoadUI'
FrameXML\UIParent.lua:1192: in function <FrameXML\UIParent.lua:1090>
[C]: ?

**Comment by seascape195** [comment]
Error started today after Blizzard's patch

ID: 1
Error occured in: Global
Count: 1
Message: ...s\Bagnon\external\Wildpants\features\autoDisplay.lua line 187:
   hooksecurefunc(): BagSlotButton_UpdateChecked is not a function
Debug:
   [C]: hooksecurefunc()
   ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:187: HookInterfaceEvents()
   ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:14:
      ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:12
   (tail call): ?
   [C]: ?
   [string "safecall Dispatcher[1]"]:9:
      [string "safecall Dispatcher[1]"]:5
   (tail call): ?
   ...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:558: EnableAddon()
   ...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:571: EnableAddon()
   ...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:651:
      ...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:636
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:446: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:489: CombatLog_LoadUI()
   ..\FrameXML\UIParent.lua:1194:
      ..\FrameXML\UIParent.lua:1090
Locals:
None
  (ck=2fd)

**Comment by syntrixsystems** [comment]
2x ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:187: hooksecurefunc(): BagSlotButton_UpdateChecked is not a function
[C]: in function `hooksecurefunc'
...s\Bagnon\external\Wildpants\features\autoDisplay.lua:187: in function `HookInterfaceEvents'
...s\Bagnon\external\Wildpants\features\autoDisplay.lua:14: in function <...s\Bagnon\external\Wildpants\features\autoDisplay.lua:12>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?

**Comment by Hangkiw** [comment]
Well While they fix it,...
I mean I can't live without this addon so....

In: \Interface\AddOns\Bagnon\external\Wildpants\components\inventory.lua
I deleted all the funtions in down line from 10

In: \Interface\AddOns\Bagnon\external\Wildpants\features\autoDisplay.lua
I deleted all the down lines from 180 (-- checked state) and add an "end" in 179

Done... I been playing like always and not more Lua Errors,...

**Comment by seascape195** [comment]
What editor are you using to get line counts?

**Comment by Hangkiw** [comment]
@seascape195 IntelluaTE 0.5

**Comment by seascape195** [comment]
![Inventory lua](https://user-images.githubusercontent.com/42080647/54252921-bf274980-451a-11e9-83bd-93bc8dd2904e.jpg)

**Comment by Tuller** [comment]
I went ahead and created a PR for this:
https://github.com/tullamods/Wildpants/pull/23

**Comment by seascape195** [comment]
**### It works...** 

\\..\_retail_\Interface\AddOns\Bagnon\external\Wildpants\components\**Inventory.lau**
![Inventory lua (fix)](https://user-images.githubusercontent.com/42080647/54253545-7f159600-451d-11e9-8652-798c28f2f2d5.jpg)
--and--

\\..\_retail_\Interface\AddOns\Bagnon\external\Wildpants\features\**autoDisplay.lau**
![autoDisplay (fix)](https://user-images.githubusercontent.com/42080647/54253562-a5d3cc80-451d-11e9-9358-58e43fe7e541.jpg)

**Comment by Mayron** [comment]
wow, thanks a lot for that @seascape195 !

**Comment by seascape195** [comment]
> 
> 
> wow, thanks a lot for that @seascape195 !

Other's above helped too.. I just visualized it for everyone  :)

**Comment by Mayron** [comment]
@seascape195 Blizzard changed the Bag Items to another new widget type so SetChecked does not exist.

BUT the Blizzard code changed the way the highlight texture is handled, so you could change the "CheckBagButtons" function to:

```lua
function Frame:CheckBagButtons(checked)
	MainMenuBarBackpackButton.SlotHighlightTexture:SetShown(checked)
	CharacterBag0Slot.SlotHighlightTexture:SetShown(checked)
	CharacterBag1Slot.SlotHighlightTexture:SetShown(checked)
	CharacterBag2Slot.SlotHighlightTexture:SetShown(checked)
	CharacterBag3Slot.SlotHighlightTexture:SetShown(checked)
end
```

But I did this and honestly I can't tell the difference...

**Comment by Canidomini** [comment]
@seascape195 re: AutoDisplay.lua - you also need to delete anything else past what you highlighted save the final 'End' statement.

I had both HookSecureFunc and HookInterfaceEvents lines left after pass 1, and they continued to cause an error until removed.

**Comment by seascape195** [comment]
> 
> 
> @seascape195 re: AutoDisplay.lua - you also need to delete anything else past what you highlighted save the final 'End' statement.
> 
> I had both HookSecureFunc and HookInterfaceEvents lines left after pass 1, and they continued to cause an error until removed.
> 
> 1x ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:180: Usage: hooksecurefunc([table,] "function", hookfunc)
> [C]: in function `hooksecurefunc' ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:180: in function `HookInterfaceEvents'
> ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:14: in function <...s\Bagnon\external\Wildpants\features\autoDisplay.lua:12>

Interesting, my copy didn't have any more code after that..

**Comment by konomikitten** [comment]
> I went ahead and created a PR for this:
> [tullamods/Wildpants#23](https://github.com/tullamods/Wildpants/pull/23)

Thanks I patched my Bagon 8.1.6 with your Pull Request and it fixed my Guild Bank Tab being messed up.

**Comment by wienfuchs** [comment]
> 
> 
> I went ahead and created a PR for this:
> [tullamods/Wildpants#23](https://github.com/tullamods/Wildpants/pull/23)

Works great for me!

**Comment by mbecknc** [comment]
Can someone give steps how to d/l and merge these files into my addon?

I'm by no means a IT novice, but unfamiliar w/ GitHub and only basic
knowledge of editing addons - I can't even find a file at the linked page
:-)

Thanks!

**Comment by wienfuchs** [comment]
> Can someone give steps how to d/l and merge these files into my addon? I'm by no means a IT novice, but unfamiliar w/ GitHub and only basic knowledge of editing addons

You need to identify your "interface" - it usually resides in your "World of Warcraft" Program directory, as a subdirectory of "_retail_" - there are all AddOns.
May your path to Bagnon is
C:\Programs (x86)\World of Warcraft\_retail_\Interface\AddOns\Bagnon

The relevant changes need to be manually done in the subseding subdirectories, you need to edit the related files. For example, the [tullamods/Wildpants#23](https://github.com/tullamods/Wildpants/pull/23) changes reside in external/Wildpants directory, the files to be changed are mentioned in "Files changed" - you need to identify the lines (e.g. using an editor like Notepad++ as I use, that shows the line numbers) - red liens are to be removed, green lines are to be added, white lines are to identify unchanged lines nearby.

So there is no "files to download and place" at this stage, morely there are "lines to be changed in existing textfiles" (.lua files are plain text files)

Hope this little description can aid you to success - conside making a copy befor change helps restoring if anything goes wrong.

**Comment by jazz836062** [comment]
I don't know if this will help get to the root of the problem, but I did find this.  They have removed the function BagSlotButton_UpdateChecked entirely.  I am not an expert on coding, but I cannot seem to see an easy substitute/replacement.

[https://www.townlong-yak.com/framexml/ptr/MainMenuBarBagButtons.lua/diff](https://www.townlong-yak.com/framexml/ptr/MainMenuBarBagButtons.lua/diff)

**Comment by pmgower** [comment]
> > Can someone give steps how to d/l and merge these files into my addon? I'm by no means a IT novice, but unfamiliar w/ GitHub and only basic knowledge of editing addons
> 
> You need to identify your "interface" - it usually resides in your "World of Warcraft" Program directory, as a subdirectory of "_retail_" - there are all AddOns.
> May your path to Bagnon is
> C:\Programs (x86)\World of Warcraft_retail_\Interface\AddOns\Bagnon
> 
> The relevant changes need to be manually done in the subseding subdirectories, you need to edit the related files. For example, the [tullamods/Wildpants#23](https://github.com/tullamods/Wildpants/pull/23) changes reside in external/Wildpants directory, the files to be changed are mentioned in "Files changed" - you need to identify the lines (e.g. using an editor like Notepad++ as I use, that shows the line numbers) - red liens are to be removed, green lines are to be added, white lines are to identify unchanged lines nearby.
> 
> So there is no "files to download and place" at this stage, morely there are "lines to be changed in existing textfiles" (.lua files are plain text files)
> 
> Hope this little description can aid you to success - conside making a copy befor change helps restoring if anything goes wrong.

@wienfuchs or @konomikitten Is there a trick to making WoW pickup these manual changes?

Even though I commented out line 187 in the `...s\Bagnon\external\Wildpants\features\autoDisplay.lua` file I am still getting an error when logging into WoW.  I even closed out the battle.net app and reopened it.

**Comment by pmgower** [comment]
Nevermind I figured it out...didn't realize there was a **cached** version in the **_retail_** folder.  Learned something about WoW today! 😄

**Comment by seascape195** [comment]
[inventory.zip](https://github.com/tullamods/Bagnon/files/2964181/inventory.zip)
[autoDisplay.zip](https://github.com/tullamods/Bagnon/files/2964180/autoDisplay.zip)

Assuming this attachment works.. here's replacement copies of:

- Inventory.lau
- autoDisplay.lau

Which are located in different sub-folders of your WoW installed game.

E.g.  Folder Locations to put these files (**AFTER** you've backed up the existing current ones you have there already):
_DriveLetter_:\ [**World of Warcraft**] \ _retail_\Interface\AddOns\Bagnon\external\Wildpants\ **components**\    _Inventory.lau_

_DriveLetter_:\ [**World of Warcraft**] \ _retail_\Interface\AddOns\Bagnon\external\Wildpants\ **features**\     _autoDisplay.lau_

This DID fix mine and several other's issue (bandaid style) for now, but no guaranty it fixes everyones.. as you may have additional add-ons interacting within these too and mine did not -- which is also why I recommend backup existing copy of these two files first.  THEN overwrite with these (assuming they did upload and attach to this post -- sorry if they did not)
