### ISSUE TITLE
Unable to see bag contents - 8.1.5

### ISSUE THREAD

**Issue by GreenGinkgo** [tullamods/Bagnon#886]
Game version: 8.1.5 (29701)
Addon version: 8.1.6

Issue:
When viewing character's bag or bank, the bag icons appear, but not the contents. 

**To Reproduce**
- Disable all addons
- Enable only these addons: BagBrother (required), Bagnon
- Open bags with B key

**Expected behavior**
Bag contents should be visible

Screenshot:
![bagnonbug-8 1 5-01](https://user-images.githubusercontent.com/5168056/54233559-90da4780-44e3-11e9-957c-48f4d187ba96.JPG)

**Error Logs**

These are all four LUA error logs when Bagnon and BagBrother are enabled.

1/4

Message: ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:187: hooksecurefunc(): BagSlotButton_UpdateChecked is not a function
Time: Tue Mar 12 15:45:55 2019
Count: 1
Stack: ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:187: hooksecurefunc(): BagSlotButton_UpdateChecked is not a function
[C]: in function `hooksecurefunc'
...s\Bagnon\external\Wildpants\features\autoDisplay.lua:187: in function `HookInterfaceEvents'
...s\Bagnon\external\Wildpants\features\autoDisplay.lua:14: in function <...s\Bagnon\external\Wildpants\features\autoDisplay.lua:12>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:558: in function `EnableAddon'
...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:571: in function `EnableAddon'
...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:651: in function <...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:446: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:565: in function `TimeManager_LoadUI'
Interface\FrameXML\UIParent.lua:1192: in function <Interface\FrameXML\UIParent.lua:1090>

Locals: <none>

=======================================================
2/4

Message: ...s\Bagnon\external\Wildpants\components\inventory.lua:22: attempt to call method 'SetChecked' (a nil value)
Time: Tue Mar 12 15:46:05 2019
Count: 2
Stack: ...s\Bagnon\external\Wildpants\components\inventory.lua:22: attempt to call method 'SetChecked' (a nil value)
...s\Bagnon\external\Wildpants\components\inventory.lua:22: in function `CheckBagButtons'
...s\Bagnon\external\Wildpants\components\inventory.lua:13: in function <...s\Bagnon\external\Wildpants\components\inventory.lua:11>
[C]: in function `Show'
Interface\FrameXML\UIParent.lua:3166: in function `ShowUIPanel'
...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:55: in function <...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:51>
(tail call): ?
...s\Bagnon\external\Wildpants\features\autoDisplay.lua:174: in function `ToggleAllBags'
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Locals: self = BagnonFrameinventory {
 0 = <userdata>
 itemFrame = <unnamed> {
 }
 searchFrame = <unnamed> {
 }
 titleFrame = <unnamed> {
 }
 bagToggle = <unnamed> {
 }
 quality = 0
 frameID = "inventory"
 searchToggle = <unnamed> {
 }
 moneyFrame = BagnonFrameinventoryMoneyFrame {
 }
 sortButton = <unnamed> {
 }
 bagFrame = <unnamed> {
 }
 profile = <table> {
 }
 closeButton = BagnonFrameinventoryCloseButton {
 }
 manualShown = true
 optionsToggle = <unnamed> {
 }
 ownerSelector = <unnamed> {
 }
 menuButtons = <table> {
 }
 brokerDisplay = <unnamed> {
 }
}
checked = true
(*temporary) = nil
(*temporary) = MainMenuBarBackpackButton {
 0 = <userdata>
 PostOnLoad = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:169
 animIcon = <unnamed> {
 }
 ItemContextOverlay = <unnamed> {
 }
 PostOnShow = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:189
 GetItemContextMatchResult = <function> defined @Interface\FrameXML\MainMenuBarBagButtons.lua:5
 IconBorder = <unnamed> {
 }
 icon = MainMenuBarBackpackButtonIconTexture {
 }
 Count = MainMenuBarBackpackButtonCount {
 }
 flyin = <unnamed> {
 }
 SetMatchesSearch = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:202
 UpdateItemContextOverlay = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:222
 GetBagID = <function> defined @Interface\FrameXML\MainMenuBarBagButtons.lua:9
 itemContextChangedCallbackIsSet = true
 itemContextMatchResult = 3
 itemContextChangedCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:170
 RegisterCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:175
 SlotHighlightTexture = <unnamed> {
 }
 IconOverlay = <unnamed> {
 }
 UnregisterCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:182
 UpdateItemContextMatching = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:211
 searchOverlay = MainMenuBarBackpackButtonSearchOverlay {
 }
 GetMatchesSearch = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:207
 freeSlots = 74
 PostOnHide = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:198
}
(*temporary) = true
(*temporary) = "attempt to call method 'SetChecked' (a nil value)"

=======================================================
3/4

Message: ...AddOns\Bagnon\external\Wildpants\components\item.lua:47: attempt to index field 'IconOverlay' (a nil value)
Time: Tue Mar 12 15:46:05 2019
Count: 2
Stack: ...AddOns\Bagnon\external\Wildpants\components\item.lua:47: attempt to index field 'IconOverlay' (a nil value)
...AddOns\Bagnon\external\Wildpants\components\item.lua:47: in function `Create'
...AddOns\Bagnon\external\Wildpants\components\item.lua:22: in function `New'
...s\Bagnon\external\Wildpants\components\itemFrame.lua:119: in function <...s\Bagnon\external\Wildpants\components\itemFrame.lua:108>

Locals: self = <unnamed> {
 0 = <userdata>
 OnLeave = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:213
 Free = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:109
 UpdateCooldown = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:312
 Bind = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\core\classes.lua:49
 OnDragStart = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:139
 SetLocked = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:308
 UpdateTooltip = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:386
 IsCached = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\core\classes.lua:89
 Create = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:36
 GetFrame = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\core\classes.lua:94
 GetFrameID = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\core\classes.lua:65
 GetEmptyItemIcon = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:436
 IsQuestItem = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:393
 SecondaryUpdate = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:234
 GetBaseProfile = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\core\classes.lua:75
 RegisterMessage = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 UnregisterMessage = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:179
 Update = <function> defined =[C]:-1
 RegisterFrameSignal = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\core\classes.lua:53
 GetBlizzard = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:89
 UpdateSearch = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:324
 Restore = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:105
 UnregisterSignal = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\core\classes.lua:23
 UnregisterSignals = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\core\classes.lua:31
 GetProfile = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\core\classes.lua:70
 Name = "ItemSlot"
 OnPreClick = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:143
 Construct = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:85
 IsSlot = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:416
 OnModifiedClick = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:192
 UnregisterAllEvents = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:200
 UpdateSlotColor = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:287
 ShowTooltip = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:355
 UpdateUpgradeIcon = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.

=======================================================
4/4

Message: ...s\Bagnon\external\Wildpants\components\inventory.lua:22: attempt to call method 'SetChecked' (a nil value)
Time: Tue Mar 12 15:45:56 2019
Count: 1
Stack: ...s\Bagnon\external\Wildpants\components\inventory.lua:22: attempt to call method 'SetChecked' (a nil value)
...s\Bagnon\external\Wildpants\components\inventory.lua:22: in function `CheckBagButtons'
...s\Bagnon\external\Wildpants\components\inventory.lua:18: in function <...s\Bagnon\external\Wildpants\components\inventory.lua:16>
[C]: in function `Hide'
Interface\FrameXML\UIParent.lua:3182: in function `HideUIPanel'
...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:64: in function <...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:60>
(tail call): ?
...s\Bagnon\external\Wildpants\features\autoDisplay.lua:174: in function `ToggleAllBags'
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Locals: self = BagnonFrameinventory {
 0 = <userdata>
 itemFrame = <unnamed> {
 }
 searchFrame = <unnamed> {
 }
 titleFrame = <unnamed> {
 }
 bagToggle = <unnamed> {
 }
 quality = 0
 frameID = "inventory"
 searchToggle = <unnamed> {
 }
 moneyFrame = BagnonFrameinventoryMoneyFrame {
 }
 sortButton = <unnamed> {
 }
 bagFrame = <unnamed> {
 }
 profile = <table> {
 }
 closeButton = BagnonFrameinventoryCloseButton {
 }
 optionsToggle = <unnamed> {
 }
 ownerSelector = <unnamed> {
 }
 menuButtons = <table> {
 }
 brokerDisplay = <unnamed> {
 }
}
checked = false
(*temporary) = nil
(*temporary) = MainMenuBarBackpackButton {
 0 = <userdata>
 PostOnLoad = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:169
 animIcon = <unnamed> {
 }
 ItemContextOverlay = <unnamed> {
 }
 PostOnShow = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:189
 GetItemContextMatchResult = <function> defined @Interface\FrameXML\MainMenuBarBagButtons.lua:5
 IconBorder = <unnamed> {
 }
 icon = MainMenuBarBackpackButtonIconTexture {
 }
 Count = MainMenuBarBackpackButtonCount {
 }
 flyin = <unnamed> {
 }
 SetMatchesSearch = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:202
 UpdateItemContextOverlay = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:222
 GetBagID = <function> defined @Interface\FrameXML\MainMenuBarBagButtons.lua:9
 itemContextChangedCallbackIsSet = true
 itemContextMatchResult = 3
 itemContextChangedCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:170
 RegisterCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:175
 SlotHighlightTexture = <unnamed> {
 }
 IconOverlay = <unnamed> {
 }
 UnregisterCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:182
 UpdateItemContextMatching = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:211
 searchOverlay = MainMenuBarBackpackButtonSearchOverlay {
 }
 GetMatchesSearch = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:207
 freeSlots = 74
 PostOnHide = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:198
}
(*temporary) = false
(*temporary) = "attempt to call method 'SetChecked' (a nil value)"

=======================================================

**Additional context**
I believe the issue centers around error "3/4" as I have a second account using the same WoW install, but I can see bag contents on that account just fine. the 3rd error is the only one that appears on the problematic account.

**Comment by mrkarlo** [comment]
Same - bags won't "open" for view

**Comment by WanderingFox** [comment]
This (and many other) bag addons got bit by a change to the ItemButtonTemplate made in 8.1.5

**Comment by Gatheringofravens** [comment]
Getting one of these errors myself since patch but bags open just fine.

> Date: 2019-03-12 14:28:29
ID: 6
Error occured in: Global
Count: 1
Message: ...s\Bagnon\external\Wildpants\components\inventory.lua line 22:
   attempt to call method 'SetChecked' (a nil value)
Debug:
   ...s\Bagnon\external\Wildpants\components\inventory.lua:22: CheckBagButtons()
   ...s\Bagnon\external\Wildpants\components\inventory.lua:13:
      ...s\Bagnon\external\Wildpants\components\inventory.lua:11
   [C]: Show()
   ..\FrameXML\UIParent.lua:3166: ShowUIPanel()
   ...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:55:
      ...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:51
   (tail call): ?
   ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:174:
      ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:173
   [C]: ToggleAllBags()
   [string "OPENALLBAGS"]:1:
      [string "OPENALLBAGS"]:1
Locals:
self = BagnonFrameinventory {
 0 = <userdata>
 searchToggle = <unnamed> {
 }
 moneyFrame = BagnonFrameinventoryMoneyFrame {
 }
 itemFrame = <unnamed> {
 }
 searchFrame = <unnamed> {
 }
 brokerDisplay = <unnamed> {
 }
 bagToggle = <unnamed> {
 }
 optionsToggle = <unnamed> {
 }
 profile = <table> {
 }
 closeButton = BagnonFrameinventoryCloseButton {
 }
 frameID = "inventory"
 titleFrame = <unnamed> {
 }
 ownerSelector = <unnamed> {
 }
 manualShown = true
 menuButtons = <table> {
 }
 quality = 0
}
checked = true
(*temporary) = nil
(*temporary) = MainMenuBarBackpackButton {
 0 = <userdata>
 PostOnLoad = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:169
 animIcon = <unnamed> {
 }
 ItemContextOverlay = <unnamed> {
 }
 PostOnShow = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:189
 GetItemContextMatchResult = <function> defined @Interface\FrameXML\MainMenuBarBagButtons.lua:5
 IconBorder = <unnamed> {
 }
 Count = MainMenuBarBackpackButtonCount {
 }
 icon = MainMenuBarBackpackButtonIconTexture {
 }
 ClearSetPoint = <function> defined @Interface\AddOns\Bartender4\BagBar.lua:64
 flyin = <unnamed> {
 }
 SetMatchesSearch = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:202
 UpdateItemContextOverlay = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:222
 GetBagID = <function> defined @Interface\FrameXML\MainMenuBarBagButtons.lua:9
 itemContextChangedCallbackIsSet = true
 itemContextMatchResult = 3
 itemContextChangedCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:170
 RegisterCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:175
 SlotHighlightTexture = <unnamed> {
 }
 IconOverlay = <unnamed> {
 }
 UnregisterCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:182
 UpdateItemContextMatching = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:211
 searchOverlay = MainMenuBarBackpackButtonSearchOverlay {
 }
 GetMatchesSearch = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:207
 freeSlots = 17
 PostOnHide = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:198
}
(*temporary) = true
(*temporary) = "attempt to call method 'SetChecked' (a nil value)"

**Comment by Sommerulv** [comment]
I still get the errors, but I can see my bag content again, after i turned off "display blizzard frames for hidden bags" in bagnon settings

**Comment by mbecknc** [comment]
> I still get the errors, but I can see my bag content again, after I turned off "display blizzard frames for hidden bags" in bagnon settings

Same here - awesome - ty for the temp fix until they patch it - I was going crazy trying to relearn default bag ui after 10 years

**Comment by Sharkeeee** [comment]
My bank bags + fame are working. But my guild bags wont open as same, in Greenginko's Screenshot above. Wake up American and fix again please!

**Comment by pgdagenais** [comment]
Same problem, but the fix provided by @Sommerulv doesn't work for me

**Comment by seascape195** [comment]
See https://github.com/tullamods/Bagnon/issues/885  <= Click here if this works for you

**Comment by TiggerOni** [comment]
Latest patch sliced into release seems to have cleared up all the lua errors being thrown.

**Comment by Snorfax** [comment]
There is a setting in Bagnon "display bliz frames for hidden bags" uncheck that
