### ISSUE TITLE
Right-Click Bank Sort Error

### ISSUE THREAD

**Issue by dafluna** [tullamods/Bagnon#887]
**Running Software (please complete the following information):**
 - Game patch Patch 8.1.5
 - Addon version 8.1.6

**Describe the bug**
When ever I right - click on the sort button for the bank, it pops up saying 'item is locked' and will only sort the reagent bag, nothing else. The only change from it working yesterday to today is the new patch was released

**To Reproduce**
1. Go to bank inventory 
2. Right - Click on manage bank
3. See Red message that pops up saying Item Is Locked

**Expected behavior**
It should sort all bags within the bank

**Screenshots**

**Error Logs**
Date: 2019-03-12 21:22:06
ID: 9
Error occured in: Global
Count: 1
Message: ...s\Bagnon\external\Wildpants\features\autoDisplay.lua line 187:
   hooksecurefunc(): BagSlotButton_UpdateChecked is not a function
Debug:
   [C]: hooksecurefunc()
   ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:187: HookInterfaceEvents()
   ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:14:
      ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:12
   [C]: ?
   ...\AtlasLoot_Button\Libs\AceAddon-3.0\AceAddon-3.0.lua:70:
      ...\AtlasLoot_Button\Libs\AceAddon-3.0\AceAddon-3.0.lua:65
   ...\AtlasLoot_Button\Libs\AceAddon-3.0\AceAddon-3.0.lua:527: EnableAddon()
   ...\AtlasLoot_Button\Libs\AceAddon-3.0\AceAddon-3.0.lua:540: EnableAddon()
   ...\AtlasLoot_Button\Libs\AceAddon-3.0\AceAddon-3.0.lua:620:
      ...\AtlasLoot_Button\Libs\AceAddon-3.0\AceAddon-3.0.lua:605
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:446: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:489: CombatLog_LoadUI()
   ..\FrameXML\UIParent.lua:1194:
      ..\FrameXML\UIParent.lua:1090
Locals:
None
AddOns:
  MoncaiCompare, v7.2.0
  Swatter, v8.1.6241 (SwimmingSeadragon)
  NPCScanOverlay, v7.3.0.1
  AtlasLoot, vv8.09.00
  AtlasLootBattleforAzeroth, vv8.09.00
  AtlasLootBurningCrusade, vv8.09.00
  AtlasLootButton, vv1.10
  AtlasLootCataclysm, vv8.09.00
  AtlasLootClassic, vv8.09.00
  AtlasLootLegion, vv8.09.00
  AtlasLootMistsofPandaria, vv8.09.00
  AtlasLootWarlordsofDraenor, vv8.09.00
  AtlasLootWrathoftheLichKing, vv8.09.00
  AucAdvanced, v8.1.6201 (SwimmingSeadragon)
  AucFilterBasic, v8.1.6228 (SwimmingSeadragon)
  AucStatHistogram, v8.1.6230 (SwimmingSeadragon)
  AucStatiLevel, v8.1.6234 (SwimmingSeadragon)
  AucStatPurchased, v8.1.6231 (SwimmingSeadragon)
  AucStatSimple, v8.1.6232 (SwimmingSeadragon)
  AucStatStdDev, v8.1.6233 (SwimmingSeadragon)
  AucUtilFixAH, v8.1.6235 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.1.6
  BagnonCurrencies, v1.0.0
  BagnonItemLevel, v1.0
  BagnonScrap, v8.1.0
  Bartender4, v4.8.2
  BeanCounter, v8.1.6236 (SwimmingSeadragon)
  Coordinates, v2.05
  DBMCore, v8.1.11
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Experiencer, v3.0.5
  Gatherer, v7.3.1
  MaxDps, v8.1.3.1
  NPCScan, v8.0.1.13
  Omen, v3.2.0
  Postal, vv3.6.0
  Recount, vv8.1.0d
  Scrap, v13.15
  SellJunk, v3.0.20
  SexyMap, vv8.0.8
  SlideBar, v8.1.6239 (SwimmingSeadragon)
  Stubby, v8.1.6240 (SwimmingSeadragon)
  TomCats, v1.0.6
  WIM, v586
  WorldQuestTracker, v
  BlizRuntimeLib_enUS v8.1.5.80100 <none>
  (ck=595)

**Additional context**

**Comment by seascape195** [comment]
Here's a workaround (if you are okay editing the code) .. I posted screenshots of exactly what to delete from the LAU's

https://github.com/tullamods/Bagnon/issues/885

**Comment by dafluna** [comment]
I'm not actually familiar with changing code, so that doesn't help me. I also downloaded the recent update of the add on and the issue still occurs.
