### ISSUE TITLE
new update prob;lem

### ISSUE THREAD

**Issue by pcarty36** [tullamods/Bagnon#888]
Date: 2019-03-13 10:21:07
ID: 1
Error occured in: Global
Count: 1
Message: ...s\Bagnon\external\Wildpants\features\autoDisplay.lua line 187:
   hooksecurefunc(): BagSlotButton_UpdateChecked is not a function
Debug:
   [C]: hooksecurefunc()
   ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:187: HookInterfaceEvents()
   ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:14:
      ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:12
   (tail call): ?
   [C]: ?
   [string "safecall Dispatcher[1]"]:9:
      [string "safecall Dispatcher[1]"]:5
   (tail call): ?
   ...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:558: EnableAddon()
   ...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:571: EnableAddon()
   ...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:651:
      ...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:636
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:446: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:565: TimeManager_LoadUI()
   ..\FrameXML\UIParent.lua:1192:
      ..\FrameXML\UIParent.lua:1090
Locals:
None
AddOns:
  Swatter, v8.1.6241 (SwimmingSeadragon)
  AtlasLoot, vv8.09.00
  AtlasLootBattleforAzeroth, vv8.09.00
  AtlasLootBurningCrusade, vv8.09.00
  AtlasLootCataclysm, vv8.09.00
  AtlasLootClassic, vv8.09.00
  AtlasLootLegion, vv8.09.00
  AtlasLootMistsofPandaria, vv8.09.00
  AtlasLootWarlordsofDraenor, vv8.09.00
  AtlasLootWrathoftheLichKing, vv8.09.00
  AucAdvanced, v8.1.6201 (SwimmingSeadragon)
  AucFilterBasic, v8.1.6228 (SwimmingSeadragon)
  AucStatHistogram, v8.1.6230 (SwimmingSeadragon)
  AucStatiLevel, v8.1.6234 (SwimmingSeadragon)
  AucStatPurchased, v8.1.6231 (SwimmingSeadragon)
  AucStatSimple, v8.1.6232 (SwimmingSeadragon)
  AucStatStdDev, v8.1.6233 (SwimmingSeadragon)
  AucUtilFixAH, v8.1.6235 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.1.6
  BeanCounter, v8.1.6236 (SwimmingSeadragon)
  Capping, vv8.1.0
  DBMCore, v8.1.11
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  Gladius, v6.0.6
  Grail, v099
  GrailQuestsenUS, v27178
  GrailReputations, v007
  GTFO, v4.46.17
  GuildRecr, v3.4
  InstancePortals, v21
  NPCScan, v8.0.1.13
  Pawn, v2.2.38
  RaiderIO, v8.1.0 (v201903130600)
  RaiderIODBEUA, v
  RaiderIODBEUAR, v
  RaiderIODBEUH, v
  RaiderIODBEUHR, v
  SlideBar, v8.1.6239 (SwimmingSeadragon)
  Stubby, v8.1.6240 (SwimmingSeadragon)
  SuperGuildInviteReborn, v8.0.0
  TidyPlatesThreatPlates, v9.1.3
  WeakAuras, v2.11.6
  Wholly, v070
  BlizRuntimeLib_enUS v8.1.5.80100 <none>
  (ck=600)

**Comment by pcarty36** [comment]
Date: 2019-03-13 10:21:07
ID: 1
Error occured in: Global
Count: 1
Message: ...s\Bagnon\external\Wildpants\features\autoDisplay.lua line 187:
   hooksecurefunc(): BagSlotButton_UpdateChecked is not a function
Debug:
   [C]: hooksecurefunc()
   ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:187: HookInterfaceEvents()
   ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:14:
      ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:12
   (tail call): ?
   [C]: ?
   [string "safecall Dispatcher[1]"]:9:
      [string "safecall Dispatcher[1]"]:5
   (tail call): ?
   ...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:558: EnableAddon()
   ...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:571: EnableAddon()
   ...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:651:
      ...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:636
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:446: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:565: TimeManager_LoadUI()
   ..\FrameXML\UIParent.lua:1192:
      ..\FrameXML\UIParent.lua:1090
Locals:
None
AddOns:
  Swatter, v8.1.6241 (SwimmingSeadragon)
  AtlasLoot, vv8.09.00
  AtlasLootBattleforAzeroth, vv8.09.00
  AtlasLootBurningCrusade, vv8.09.00
  AtlasLootCataclysm, vv8.09.00
  AtlasLootClassic, vv8.09.00
  AtlasLootLegion, vv8.09.00
  AtlasLootMistsofPandaria, vv8.09.00
  AtlasLootWarlordsofDraenor, vv8.09.00
  AtlasLootWrathoftheLichKing, vv8.09.00
  AucAdvanced, v8.1.6201 (SwimmingSeadragon)
  AucFilterBasic, v8.1.6228 (SwimmingSeadragon)
  AucStatHistogram, v8.1.6230 (SwimmingSeadragon)
  AucStatiLevel, v8.1.6234 (SwimmingSeadragon)
  AucStatPurchased, v8.1.6231 (SwimmingSeadragon)
  AucStatSimple, v8.1.6232 (SwimmingSeadragon)
  AucStatStdDev, v8.1.6233 (SwimmingSeadragon)
  AucUtilFixAH, v8.1.6235 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.1.6
  BeanCounter, v8.1.6236 (SwimmingSeadragon)
  Capping, vv8.1.0
  DBMCore, v8.1.11
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  Gladius, v6.0.6
  Grail, v099
  GrailQuestsenUS, v27178
  GrailReputations, v007
  GTFO, v4.46.17
  GuildRecr, v3.4
  InstancePortals, v21
  NPCScan, v8.0.1.13
  Pawn, v2.2.38
  RaiderIO, v8.1.0 (v201903130600)
  RaiderIODBEUA, v
  RaiderIODBEUAR, v
  RaiderIODBEUH, v
  RaiderIODBEUHR, v
  SlideBar, v8.1.6239 (SwimmingSeadragon)
  Stubby, v8.1.6240 (SwimmingSeadragon)
  SuperGuildInviteReborn, v8.0.0
  TidyPlatesThreatPlates, v9.1.3
  WeakAuras, v2.11.6
  Wholly, v070
  BlizRuntimeLib_enUS v8.1.5.80100 <none>
  (ck=600)

**Comment by FathomsDeep** [comment]
Bagnon panels not showing correctly- appear as tiny bar with only top buttons showing.

**Comment by Mafields** [comment]
Every time i open my bags i get this. I'm using Masque with DiabolicUi mask in it and Goldpaws Bagnon ItemInfo. Disabling both of those gave me 2nd error what seems to be same as above.

Error 1:
Message: ...s\Bagnon\external\Wildpants\components\inventory.lua:22: attempt to call method 'SetChecked' (a nil value)
Time: Wed Mar 13 13:28:34 2019
Count: 1
Stack: ...s\Bagnon\external\Wildpants\components\inventory.lua:22: attempt to call method 'SetChecked' (a nil value)
...s\Bagnon\external\Wildpants\components\inventory.lua:22: in function `CheckBagButtons'
...s\Bagnon\external\Wildpants\components\inventory.lua:18: in function <...s\Bagnon\external\Wildpants\components\inventory.lua:16>
[C]: ?
[C]: in function `Hide'
Interface\FrameXML\UIParent.lua:3324: in function <Interface\FrameXML\UIParent.lua:3319>
[C]: in function `securecall'
Interface\FrameXML\UIParent.lua:3362: in function `CloseWindows'
Interface\FrameXML\UIParent.lua:3387: in function <Interface\FrameXML\UIParent.lua:3377>
[C]: in function `securecall'
Interface\FrameXML\UIParent.lua:4015: in function `ToggleGameMenu'
[string "TOGGLEGAMEMENU"]:1: in function <[string "TOGGLEGAMEMENU"]:1>

Locals: self = BagnonFrameinventory {
 0 = <userdata>
 itemFrame = <unnamed> {
 }
 searchFrame = <unnamed> {
 }
 titleFrame = <unnamed> {
 }
 bagToggle = <unnamed> {
 }
 quality = 0
 frameID = "inventory"
 searchToggle = <unnamed> {
 }
 moneyFrame = BagnonFrameinventoryMoneyFrame {
 }
 sortButton = <unnamed> {
 }
 bagFrame = <unnamed> {
 }
 optionsToggle = <unnamed> {
 }
 profile = <table> {
 }
 closeButton = BagnonFrameinventoryCloseButton {
 }
 manualShown = true
 ownerSelector = <unnamed> {
 }
 focusedBag = false
 menuButtons = <table> {
 }
 brokerDisplay = <unnamed> {
 }
}
checked = false
(*temporary) = nil
(*temporary) = MainMenuBarBackpackButton {
 0 = <userdata>
 PostOnLoad = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:169
 animIcon = <unnamed> {
 }
 ItemContextOverlay = <unnamed> {
 }
 PostOnShow = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:189
 GetItemContextMatchResult = <function> defined @Interface\FrameXML\MainMenuBarBagButtons.lua:5
 IconBorder = <unnamed> {
 }
 icon = MainMenuBarBackpackButtonIconTexture {
 }
 Count = MainMenuBarBackpackButtonCount {
 }
 flyin = <unnamed> {
 }
 SetMatchesSearch = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:202
 UpdateItemContextOverlay = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:222
 GetBagID = <function> defined @Interface\FrameXML\MainMenuBarBagButtons.lua:9
 itemContextChangedCallbackIsSet = false
 itemContextMatchResult = 3
 itemContextChangedCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:170
 RegisterCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:175
 SlotHighlightTexture = <unnamed> {
 }
 IconOverlay = <unnamed> {
 }
 UnregisterCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:182
 UpdateItemContextMatching = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:211
 searchOverlay = MainMenuBarBackpackButtonSearchOverlay {
 }
 GetMatchesSearch = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:207
 freeSlots = 51
 PostOnHide = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:198
}
(*temporary) = false
(*temporary) = "attempt to call method 'SetChecked' (a nil value)"

Error 2:
Message: ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:187: hooksecurefunc(): BagSlotButton_UpdateChecked is not a function
Time: Wed Mar 13 13:36:30 2019
Count: 1
Stack: ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:187: hooksecurefunc(): BagSlotButton_UpdateChecked is not a function
[C]: in function `hooksecurefunc'
...s\Bagnon\external\Wildpants\features\autoDisplay.lua:187: in function `HookInterfaceEvents'
...s\Bagnon\external\Wildpants\features\autoDisplay.lua:14: in function <...s\Bagnon\external\Wildpants\features\autoDisplay.lua:12>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:558: in function `EnableAddon'
...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:571: in function `EnableAddon'
...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:651: in function <...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:446: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:565: in function `TimeManager_LoadUI'
Interface\FrameXML\UIParent.lua:1192: in function <Interface\FrameXML\UIParent.lua:1090>

Locals: <none>

**Comment by seascape195** [comment]
See ticket https://github.com/tullamods/Bagnon/issues/885 <= click here
