### ISSUE TITLE
Bagnon Guildbank

### ISSUE THREAD

**Issue by Askania** [tullamods/Bagnon#890]
Since 8.1.5 release the only issue I am having is that when I select guildbank addon and go to the bank all I see is the tab icons. No bank slots. I am at the moment keeping that addon disabled until a fix but otherwise no issues with any of the other bagnon features.

**Comment by YouTubeNATE** [comment]
I am having the same issue with guild bank contents not showing... The tabs are there, but I'm unable to see the contents of the guild bank no matter what changes to setting that I make.  Until fixed... I'm disabling Bagnon.  /sigh

**Comment by machiavelli020** [comment]
Same problem here, please fix.
Will have to disable for now, but if it takes too long we will have to look for alternatives...

**Comment by Askania** [comment]
Also having same problem with void storage. I rarely use it though.
