### ISSUE TITLE
I get this when i open my bags and close them

### ISSUE THREAD

**Issue by RobertLynch21** [tullamods/Bagnon#894]
Message: ...s\Bagnon\external\Wildpants\components\inventory.lua:22: attempt to call method 'SetChecked' (a nil value)
Time: Wed Mar 13 15:12:31 2019
Count: 1
Stack: ...s\Bagnon\external\Wildpants\components\inventory.lua:22: attempt to call method 'SetChecked' (a nil value)
...s\Bagnon\external\Wildpants\components\inventory.lua:22: in function `CheckBagButtons'
...s\Bagnon\external\Wildpants\components\inventory.lua:13: in function <...s\Bagnon\external\Wildpants\components\inventory.lua:11>
[C]: in function `Show'
Interface\FrameXML\UIParent.lua:3166: in function `ShowUIPanel'
...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:55: in function <...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:51>
(tail call): ?
(tail call): ?
...s\Bagnon\external\Wildpants\features\autoDisplay.lua:134: in function `ToggleBackpack'
Interface\FrameXML\MainMenuBarBagButtons.lua:40: in function `BackpackButton_OnClick'
Interface\FrameXML\MainMenuBarBagButtons.lua:153: in function <Interface\FrameXML\MainMenuBarBagButtons.lua:149>

Locals: self = BagnonFrameinventory {
 0 = <userdata>
 itemFrame = <unnamed> {
 }
 searchFrame = <unnamed> {
 }
 titleFrame = <unnamed> {
 }
 bagToggle = <unnamed> {
 }
 quality = 0
 frameID = "inventory"
 searchToggle = <unnamed> {
 }
 moneyFrame = BagnonFrameinventoryMoneyFrame {
 }
 sortButton = <unnamed> {
 }
 profile = <table> {
 }
 closeButton = BagnonFrameinventoryCloseButton {
 }
 manualShown = true
 optionsToggle = <unnamed> {
 }
 ownerSelector = <unnamed> {
 }
 menuButtons = <table> {
 }
 brokerDisplay = <unnamed> {
 }
}
checked = true
(*temporary) = nil
(*temporary) = MainMenuBarBackpackButton {
 0 = <userdata>
 PostOnLoad = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:169
 animIcon = <unnamed> {
 }
 ItemContextOverlay = <unnamed> {
 }
 PostOnShow = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:189
 GetItemContextMatchResult = <function> defined @Interface\FrameXML\MainMenuBarBagButtons.lua:5
 IconBorder = <unnamed> {
 }
 Count = MainMenuBarBackpackButtonCount {
 }
 icon = MainMenuBarBackpackButtonIconTexture {
 }
 ClearSetPoint = <function> defined @Interface\AddOns\Bartender4\BagBar.lua:64
 flyin = <unnamed> {
 }
 SetMatchesSearch = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:202
 UpdateItemContextOverlay = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:222
 GetBagID = <function> defined @Interface\FrameXML\MainMenuBarBagButtons.lua:9
 itemContextChangedCallbackIsSet = true
 itemContextMatchResult = 3
 itemContextChangedCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:170
 RegisterCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:175
 SlotHighlightTexture = <unnamed> {
 }
 IconOverlay = <unnamed> {
 }
 UnregisterCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:182
 UpdateItemContextMatching = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:211
 searchOverlay = MainMenuBarBackpackButtonSearchOverlay {
 }
 GetMatchesSearch = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:207
 freeSlots = 56
 PostOnHide = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:198
}
(*temporary) = true
(*temporary) = "attempt to call method 'SetChecked' (a nil value)"

**Comment by RobertLynch21** [comment]
I have deleted and reinstalled. No go.

**Comment by artemise1220** [comment]
I also have this same issue. A few other people I know have it as well, and other bag addons such as "AdiBags" had a similar issue that has recently been fixed.
