### ISSUE TITLE
Error on Login

### ISSUE THREAD

**Issue by Fauste** [tullamods/Bagnon#895]
1x ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:187: hooksecurefunc(): BagSlotButton_UpdateChecked is not a function
[C]: in function `hooksecurefunc'
...s\Bagnon\external\Wildpants\features\autoDisplay.lua:187: in function `HookInterfaceEvents'
...s\Bagnon\external\Wildpants\features\autoDisplay.lua:14: in function <...s\Bagnon\external\Wildpants\features\autoDisplay.lua:12>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0-12.lua:558: in function `EnableAddon'
...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0-12.lua:571: in function `EnableAddon'
...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0-12.lua:651: in function <...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:446: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:565: in function `TimeManager_LoadUI'
FrameXML\UIParent.lua:1192: in function <FrameXML\UIParent.lua:1090>

**Comment by Fauste** [comment]
Forgot to mention version 8.1.6. Apologies

**Comment by dwneylonsr** [comment]
I'm getting the same error on login:

Date: 2019-03-14 09:48:45
ID: 1
Error occured in: Global
Count: 1
Message: ...s\Bagnon\external\Wildpants\features\autoDisplay.lua line 187:
   hooksecurefunc(): BagSlotButton_UpdateChecked is not a function
Debug:
   [C]: hooksecurefunc()
   ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:187: HookInterfaceEvents()
   ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:14:
      ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:12
   [C]: ?
   ...s\AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:70:
      ...s\AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:65
   ...s\AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:527: EnableAddon()
   ...s\AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:540: EnableAddon()
   ...s\AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:620:
      ...s\AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:605
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:446: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:565: TimeManager_LoadUI()
   ..\FrameXML\UIParent.lua:1192:
      ..\FrameXML\UIParent.lua:1090
Locals:
None
AddOns:
  Swatter, v8.1.6241 (SwimmingSeadragon)
  AckisRecipeList, v8.1.1
  AdvancedInterfaceOptions, v1.2.9
  AllTheThings, v1.8.6c
  AskMrRobot, v74
  AucAdvanced, v8.1.6201 (SwimmingSeadragon)
  AucFilterBasic, v8.1.6228 (SwimmingSeadragon)
  AucStatHistogram, v8.1.6230 (SwimmingSeadragon)
  AucStatiLevel, v8.1.6234 (SwimmingSeadragon)
  AucStatPurchased, v8.1.6231 (SwimmingSeadragon)
  AucStatSimple, v8.1.6232 (SwimmingSeadragon)
  AucStatStdDev, v8.1.6233 (SwimmingSeadragon)
  AucUtilFixAH, v8.1.6235 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.1.6
  BagnonRequiredLevel, v1.4
  BFAInvasionTimer, vv8.1.5
  BtWQuests, v1.35
  BtWQuestsBattleForAzeroth, v23
  BtWQuestsBattleForAzerothPrologue, v10
  BtWQuestsLegion, v18
  BuyEmAll, v3.5.3
  DBMArchaeology, v
  DBMCore, v8.1.11
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DugisGuideViewerZ, v5.100
  FactionAddict, v1.54
  FishingBuddy, v1.9.27
  GTFO, v4.46.17
  HereBeDragons, v2.01-release
  LegionInvasionTimer, vv8.1.3
  MaxDps, v8.1.3.1
  Overachiever, v1.0.5
  OverachieverCache, v1.0.5
  RaidAchievement, v
  Recount, vv8.1.0d
  SlideBar, v8.1.6239 (SwimmingSeadragon)
  Stubby, v8.1.6240 (SwimmingSeadragon)
  TabardAddict, v2.43
  TasteTheNaimbow, v7.1
  Titan, v5.17.0.80100
  TitanBag, v5.17.0.80100
  TitanClock, v5.17.0.80100
  TitanGold, v5.17.0.80100
  TitanLocation, v5.17.0.80100
  TitanLootType, v5.17.0.80100
  TitanPerformance, v5.17.0.80100
  TitanRepair, v5.17.0.80100
  TitanVolume, v5.17.0.80100
  TitanXP, v5.17.0.80100
  WorldQuestTracker, v
  WoWDBProfiler, v
  WQAchievements, vv8.1.0-10release
  BlizRuntimeLib_enUS v8.1.5.80100 <none>
  (ck=65b)
