### ISSUE TITLE
Bagon not working

### ISSUE THREAD

**Issue by TexasMisha** [tullamods/Bagnon#897]
Date: 2019-03-13 16:11:49
ID: 1
Error occured in: Global
Count: 1
Message: ...s\Bagnon\external\Wildpants\features\autoDisplay.lua line 187:
   hooksecurefunc(): BagSlotButton_UpdateChecked is not a function
Debug:
   (tail call): ?
   [C]: hooksecurefunc()
   ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:187: HookInterfaceEvents()
   ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:14:
      ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:12
   (tail call): ?
   [C]: ?
   [string "safecall Dispatcher[1]"]:9:
      [string "safecall Dispatcher[1]"]:5
   (tail call): ?
   ...AddOns\AutoTurnIn\Libs\AceAddon-3.0\AceAddon-3.0.lua:558: EnableAddon()
   ...AddOns\AutoTurnIn\Libs\AceAddon-3.0\AceAddon-3.0.lua:571: EnableAddon()
   ...AddOns\AutoTurnIn\Libs\AceAddon-3.0\AceAddon-3.0.lua:651:
      ...AddOns\AutoTurnIn\Libs\AceAddon-3.0\AceAddon-3.0.lua:636
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:446: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:565: TimeManager_LoadUI()
   ..\FrameXML\UIParent.lua:1192:
      ..\FrameXML\UIParent.lua:1090
Locals:
None
AddOns:
  Swatter, v8.1.6241 (SwimmingSeadragon)
  AdventureGuideLockouts, v1.2.7
  AucAdvanced, v8.1.6201 (SwimmingSeadragon)
  AucFilterBasic, v8.1.6228 (SwimmingSeadragon)
  AucStatHistogram, v8.1.6230 (SwimmingSeadragon)
  AucStatiLevel, v8.1.6234 (SwimmingSeadragon)
  AucStatPurchased, v8.1.6231 (SwimmingSeadragon)
  AucStatSimple, v8.1.6232 (SwimmingSeadragon)
  AucStatStdDev, v8.1.6233 (SwimmingSeadragon)
  AucUtilFixAH, v8.1.6235 (SwimmingSeadragon)
  AutoTurnIn, v7.0.9
  BagBrother, v
  Bagnon, v8.1.6
  Bartender4, v4.8.2
  BeanCounter, v8.1.6236 (SwimmingSeadragon)
  CollectMe, v2.10.1
  DBMCore, v8.1.11
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  FasterLoot, v1.0
  GTFO, v4.46.17
  Mapster, v1.8.2
  MountJournalEnhanced, v2.2.1
  NPCScan, v8.0.1.13
  Overachiever, v1.0.5
  OverachieverCache, v1.0.5
  Postal, vv3.6.0
  Rarity, v1.0 (r686-release)
  RarityOptions, v
  Recount, vv8.1.0d
  Scrap, v13.15
  ScrapSpotlight, v13.15
  SlideBar, v8.1.6239 (SwimmingSeadragon)
  Stubby, v8.1.6240 (SwimmingSeadragon)
  TradeSkillMaster, vv4.7.5
  WorldQuestTracker, v
  BlizRuntimeLib_enUS v8.1.5.80100 <none>
  (ck=45e)

**Comment by LadyNixie** [comment]
Me too, but mine seems a little different.

Date: 2019-03-13 16:58:36
ID: 2
Error occured in: Global
Count: 1
Message: ...s\Bagnon\external\Wildpants\components\inventory.lua line 22:
   attempt to call method 'SetChecked' (a nil value)
Debug:
   ...s\Bagnon\external\Wildpants\components\inventory.lua:22: CheckBagButtons()
   ...s\Bagnon\external\Wildpants\components\inventory.lua:13:
      ...s\Bagnon\external\Wildpants\components\inventory.lua:11
   [C]: Show_org()
   DugisGuideViewerZ\Professions.lua:140: Show()
   ..\FrameXML\UIParent.lua:3166:
      ..\FrameXML\UIParent.lua:3161
   [C]: ?
   [C]: ?
   [C]: ShowUIPanel()
   ...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:55:
      ...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:51
   (tail call): ?
   ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:174: ToggleAllBags()
   [string "OPENALLBAGS"]:1:
      [string "OPENALLBAGS"]:1
Locals:
self = BagnonFrameinventory {
 0 = <userdata>
 itemFrame = <unnamed> {
 }
 searchFrame = <unnamed> {
 }
 titleFrame = <unnamed> {
 }
 bagToggle = <unnamed> {
 }
 quality = 0
 frameID = "inventory"
 searchToggle = <unnamed> {
 }
 moneyFrame = BagnonFrameinventoryMoneyFrame {
 }
 sortButton = <unnamed> {
 }
 bagFrame = <unnamed> {
 }
 manualShown = true
 Show = <function> defined @Interface\AddOns\DugisGuideViewerZ\Professions.lua:135
 closeButton = BagnonFrameinventoryCloseButton {
 }
 profile = <table> {
 }
 optionsToggle = <unnamed> {
 }
 ownerSelector = <unnamed> {
 }
 Show_org = <function> defined =[C]:-1
 menuButtons = <table> {
 }
 brokerDisplay = <unnamed> {
 }
}
checked = true
(*temporary) = nil
(*temporary) = MainMenuBarBackpackButton {
 0 = <userdata>
 PostOnLoad = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:169
 animIcon = <unnamed> {
 }
 ItemContextOverlay = <unnamed> {
 }
 PostOnShow = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:189
 GetItemContextMatchResult = <function> defined @Interface\FrameXML\MainMenuBarBagButtons.lua:5
 IconBorder = <unnamed> {
 }
 Count = MainMenuBarBackpackButtonCount {
 }
 icon = MainMenuBarBackpackButtonIconTexture {
 }
 ClearSetPoint = <function> defined @Interface\AddOns\Bartender4\BagBar.lua:64
 flyin = <unnamed> {
 }
 SetMatchesSearch = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:202
 UpdateItemContextOverlay = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:222
 GetBagID = <function> defined @Interface\FrameXML\MainMenuBarBagButtons.lua:9
 itemContextChangedCallbackIsSet = true
 itemContextMatchResult = 3
 itemContextChangedCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:170
 RegisterCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:175
 SlotHighlightTexture = <unnamed> {
 }
 IconOverlay = <unnamed> {
 }
 UnregisterCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:182
 UpdateItemContextMatching = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:211
 searchOverlay = MainMenuBarBackpackButtonSearchOverlay {
 }
 GetMatchesSearch = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:207
 freeSlots = 95
 PostOnHide = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:198
}
(*temporary) = true
(*temporary) = "attempt to call method 'SetChecked' (a nil value)"

AddOns:
  Swatter, v8.1.6241 (SwimmingSeadragon)
  Altoholic, vr190
  AucAdvanced, v8.1.6201 (SwimmingSeadragon)
  AucFilterBasic, v8.1.6228 (SwimmingSeadragon)
  AucStatHistogram, v8.1.6230 (SwimmingSeadragon)
  AucStatiLevel, v8.1.6234 (SwimmingSeadragon)
  AucStatPurchased, v8.1.6231 (SwimmingSeadragon)
  AucStatSimple, v8.1.6232 (SwimmingSeadragon)
  AucStatStdDev, v8.1.6233 (SwimmingSeadragon)
  AucUtilFixAH, v8.1.6235 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.1.6
  Bartender4, v4.8.2
  BeanCounter, v8.1.6236 (SwimmingSeadragon)
  DataStore, vr65
  DataStoreAchievements, vr47
  DataStoreAgenda, vr29
  DataStoreAuctions, vr50
  DataStoreCharacters, vr43
  DataStoreContainers, vr59
  DataStoreCrafts, vr82
  DataStoreCurrencies, vr38
  DataStoreGarrisons, vr24
  DataStoreInventory, vr53
  DataStoreMails, vr52
  DataStorePets, vr44
  DataStoreQuests, vr46
  DataStoreReputations, vr43
  DataStoreSpells, vr32
  DataStoreStats, vr31
  DataStoreTalents, vr61
  DBMCore, v8.1.11
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DugisGuideViewerZ, v8.700
  Enchantrix, v8.1.6237 (SwimmingSeadragon)
  GTFO, v4.46.17
  HealBot, v8.1.0.7
  HealBotTips, v8.1.0.7
  Informant, v8.1.6246 (SwimmingSeadragon)
  Recount, vv8.1.0d
  Stubby, v8.1.6240 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v8.1.5.80100 <none>
  (ck=51e)

**Comment by Hugagug45** [comment]
me 2    

Date: 2019-03-14 16:49:53
ID: 2
Error occured in: Global
Count: 1
Message: ...s\Bagnon\external\Wildpants\components\inventory.lua line 22:
   attempt to call method 'SetChecked' (a nil value)
Debug:
   ...s\Bagnon\external\Wildpants\components\inventory.lua:22: CheckBagButtons()
   ...s\Bagnon\external\Wildpants\components\inventory.lua:13:
      ...s\Bagnon\external\Wildpants\components\inventory.lua:11
   [C]: Show()
   ..\FrameXML\UIParent.lua:3166: ShowUIPanel()
   ...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:55:
      ...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:51
   (tail call): ?
   ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:174: ToggleAllBags()
   [string "OPENALLBAGS"]:1:
      [string "OPENALLBAGS"]:1
Locals:
self = BagnonFrameinventory {
 0 = <userdata>
 itemFrame = <unnamed> {
 }
 searchFrame = <unnamed> {
 }
 titleFrame = <unnamed> {
 }
 bagToggle = <unnamed> {
 }
 quality = 0
 frameID = "inventory"
 searchToggle = <unnamed> {
 }
 moneyFrame = BagnonFrameinventoryMoneyFrame {
 }
 sortButton = <unnamed> {
 }
 bagFrame = <unnamed> {
 }
 profile = <table> {
 }
 closeButton = BagnonFrameinventoryCloseButton {
 }
 manualShown = true
 optionsToggle = <unnamed> {
 }
 ownerSelector = <unnamed> {
 }
 menuButtons = <table> {
 }
 brokerDisplay = <unnamed> {
 }
}
checked = true
(*temporary) = nil
(*temporary) = MainMenuBarBackpackButton {
 0 = <userdata>
 PostOnLoad = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:169
 animIcon = <unnamed> {
 }
 ItemContextOverlay = <unnamed> {
 }
 PostOnShow = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:189
 GetItemContextMatchResult = <function> defined @Interface\FrameXML\MainMenuBarBagButtons.lua:5
 IconBorder = <unnamed> {
 }
 icon = MainMenuBarBackpackButtonIconTexture {
 }
 Count = MainMenuBarBackpackButtonCount {
 }
 flyin = <unnamed> {
 }
 SetMatchesSearch = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:202
 UpdateItemContextOverlay = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:222
 GetBagID = <function> defined @Interface\FrameXML\MainMenuBarBagButtons.lua:9
 itemContextChangedCallbackIsSet = true
 itemContextMatchResult = 3
 itemContextChangedCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:170
 RegisterCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:175
 SlotHighlightTexture = <unnamed> {
 }
 IconOverlay = <unnamed> {
 }
 UnregisterCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:182
 UpdateItemContextMatching = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:211
 searchOverlay = MainMenuBarBackpackButtonSearchOverlay {
 }
 GetMatchesSearch = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:207
 freeSlots = 92
 PostOnHide = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:198
}
(*temporary) = true
(*temporary) = "attempt to call method 'SetChecked' (a nil value)"

AddOns:
  Swatter, v8.1.6241 (SwimmingSeadragon)
  AucAdvanced, v8.1.6201 (SwimmingSeadragon)
  AucFilterBasic, v8.1.6228 (SwimmingSeadragon)
  AucStatHistogram, v8.1.6230 (SwimmingSeadragon)
  AucStatiLevel, v8.1.6234 (SwimmingSeadragon)
  AucStatPurchased, v8.1.6231 (SwimmingSeadragon)
  AucStatSimple, v8.1.6232 (SwimmingSeadragon)
  AucStatStdDev, v8.1.6233 (SwimmingSeadragon)
  AucUtilFixAH, v8.1.6235 (SwimmingSeadragon)
  AzerothAutoPilot, v
  BagBrother, v
  Bagnon, v8.1.5
  BeanCounter, v8.1.6236 (SwimmingSeadragon)
  DBMCore, v8.1.11
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Enchantrix, v8.1.6237 (SwimmingSeadragon)
  GTFO, v4.46.17
  HandyNotes, vv1.5.5
  HandyNotesBattleForAzerothTreasures, v1
  HandyNotesLegionRaresTreasures, v1.1
  HealBot, v8.1.0.7
  HealBotTips, v8.1.0.7
  Informant, v8.1.6246 (SwimmingSeadragon)
  NPCScan, v8.0.1.13
  Pawn, v2.2.39
  PersonalLootHelper, v2.19
  Recount, vv8.1.0d
  SavedInstances, v8.1.0
  Simulationcraft, v1.10.11
  Skada, v1.7.5
  SlideBar, v8.1.6239 (SwimmingSeadragon)
  Stubby, v8.1.6240 (SwimmingSeadragon)
  WorldQuestTracker, v
  BlizRuntimeLib_enUS v8.1.5.80100 <none>
  (ck=470)

Date: 2019-03-14 16:49:53
ID: 3
Error occured in: Global
Count: 1
Message: ...AddOns\Bagnon\external\Wildpants\components\item.lua line 47:
   attempt to index field 'IconOverlay' (a nil value)
Debug:
   ...AddOns\Bagnon\external\Wildpants\components\item.lua:47: Create()
   ...AddOns\Bagnon\external\Wildpants\components\item.lua:22: New()
   ...s\Bagnon\external\Wildpants\components\itemFrame.lua:119:
      ...s\Bagnon\external\Wildpants\components\itemFrame.lua:108
Locals:
self = <unnamed> {
 0 = <userdata>
 OnLeave = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:213
 Free = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:109
 UpdateCooldown = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:312
 Bind = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\core\classes.lua:49
 OnDragStart = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:139
 SetLocked = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:308
 UpdateTooltip = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:386
 IsCached = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\core\classes.lua:89
 Create = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:36
 GetFrame = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\core\classes.lua:94
 GetFrameID = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\core\classes.lua:65
 GetEmptyItemIcon = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:436
 IsQuestItem = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:393
 SecondaryUpdate = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:234
 GetBaseProfile = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\core\classes.lua:75
 RegisterMessage = <function> defined @Interface\AddOns\SlideBar\Libs\LibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface\AddOns\SlideBar\Libs\LibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:153
 Update = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:222
 RegisterFrameSignal = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\core\classes.lua:53
 GetBlizzard = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:89
 UpdateSearch = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:324
 Restore = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:105
 UnregisterSignal = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\core\classes.lua:23
 UnregisterSignals = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\core\classes.lua:31
 GetProfile = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\core\classes.lua:70
 Name = "ItemSlot"
 OnPreClick = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:143
 Construct = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:85
 IsSlot = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:416
 OnModifiedClick = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:192
 UnregisterAllEvents = <function> defined @Interface\AddOns\SlideBar\Libs\LibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:174
 UpdateSlotColor = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:287
 ShowTooltip = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:355
 UpdateUpgradeIcon = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:295
 New = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:21
 nextID = 1
 GetDummyBag = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:462
 UnregisterFrameSignal = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\core\classes.lua:57
 AnchorTooltip = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:378
 GetOwnerInfo = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\core\classes.lua:85
 CreateDummySlot = <function> defined @Interface\AddOns\Bagnon\external\Wildpants\components\item.lua:479
 GetDu
AddOns:
  Swatter, v8.1.6241 (SwimmingSeadragon)
  AucAdvanced, v8.1.6201 (SwimmingSeadragon)
  AucFilterBasic, v8.1.6228 (SwimmingSeadragon)
  AucStatHistogram, v8.1.6230 (SwimmingSeadragon)
  AucStatiLevel, v8.1.6234 (SwimmingSeadragon)
  AucStatPurchased, v8.1.6231 (SwimmingSeadragon)
  AucStatSimple, v8.1.6232 (SwimmingSeadragon)
  AucStatStdDev, v8.1.6233 (SwimmingSeadragon)
  AucUtilFixAH, v8.1.6235 (SwimmingSeadragon)
  AzerothAutoPilot, v
  BagBrother, v
  Bagnon, v8.1.5
  BeanCounter, v8.1.6236 (SwimmingSeadragon)
  DBMCore, v8.1.11
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Enchantrix, v8.1.6237 (SwimmingSeadragon)
  GTFO, v4.46.17
  HandyNotes, vv1.5.5
  HandyNotesBattleForAzerothTreasures, v1
  HandyNotesLegionRaresTreasures, v1.1
  HealBot, v8.1.0.7
  HealBotTips, v8.1.0.7
  Informant, v8.1.6246 (SwimmingSeadragon)
  NPCScan, v8.0.1.13
  Pawn, v2.2.39
  PersonalLootHelper, v2.19
  Recount, vv8.1.0d
  SavedInstances, v8.1.0
  Simulationcraft, v1.10.11
  Skada, v1.7.5
  SlideBar, v8.1.6239 (SwimmingSeadragon)
  Stubby, v8.1.6240 (SwimmingSeadragon)
  WorldQuestTracker, v
  BlizRuntimeLib_enUS v8.1.5.80100 <none>
  (ck=470)
