### ISSUE TITLE
LUA errors when opening inventory

### ISSUE THREAD

**Issue by specs1188** [tullamods/Bagnon#899]
Hello, I have two errors to submit for Bagnon.

--First one I get when UI loads once logged in, second error below--

Date: 2019-03-13 21:33:04
ID: 1
Error occured in: Global
Count: 1
Message: ...s\Bagnon\external\Wildpants\features\autoDisplay.lua line 187:
   hooksecurefunc(): BagSlotButton_UpdateChecked is not a function
Debug:
   [C]: hooksecurefunc()
   ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:187: HookInterfaceEvents()
   ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:14:
      ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:12
   (tail call): ?
   [C]: ?
   [string "safecall Dispatcher[1]"]:9:
      [string "safecall Dispatcher[1]"]:5
   (tail call): ?
   ...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:558: EnableAddon()
   ...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:571: EnableAddon()
   ...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:651:
      ...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:636
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:446: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:489: CombatLog_LoadUI()
   ..\FrameXML\UIParent.lua:1194:
      ..\FrameXML\UIParent.lua:1090
Locals:
None
AddOns:
  Swatter, v8.1.6241 (SwimmingSeadragon)
  AucAdvanced, v8.1.6201 (SwimmingSeadragon)
  AucFilterBasic, v8.1.6228 (SwimmingSeadragon)
  AucStatHistogram, v8.1.6230 (SwimmingSeadragon)
  AucStatiLevel, v8.1.6234 (SwimmingSeadragon)
  AucStatPurchased, v8.1.6231 (SwimmingSeadragon)
  AucStatSimple, v8.1.6232 (SwimmingSeadragon)
  AucStatStdDev, v8.1.6233 (SwimmingSeadragon)
  AucUtilFixAH, v8.1.6235 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.1.6
  BeanCounter, v8.1.6236 (SwimmingSeadragon)
  Carbonite, vv8.1.2.1
  CarboniteNotes, vv8.1
  CarboniteQuests, vv8.1.2
  DBMCore, v8.1.11
  DBMDefaultSkin, v
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  EasyDisenchant, v1.1.7
  GatherMate2, v1.43.6
  GTFO, v4.46.17
  HandyNotes, vv1.5.5
  HandyNotesArgus, v0.20.0
  HandyNotesBrokenShore, vv1.30
  HandyNotesLegionRaresTreasures, v1.1
  HandyNotesLegionTreasures, v1
  LootAppraiser, vv1.9.3
  MobInfo2, v8.1.0
  Omen, v3.2.0
  Parrot, vv2.1.4
  Paste, v1.4.10
  RealmHopAssist, vr04 beta
  Recount, vv8.1.0d
  Routes, vv1.6.1
  SellJunk, v3.0.20
  SlideBar, v8.1.6239 (SwimmingSeadragon)
  Stubby, v8.1.6240 (SwimmingSeadragon)
  TomTom, vv80100-1.0.1
  WorldQuestTracker, v
  BlizRuntimeLib_enUS v8.1.5.80100 <none>
  (ck=4c8)
------------------------------------------------------------
--Second error upon opening Inventory--

Date: 2019-03-13 21:33:55
ID: 3
Error occured in: Global
Count: 1
Message: ...s\Bagnon\external\Wildpants\components\inventory.lua line 22:
   attempt to call method 'SetChecked' (a nil value)
Debug:
   ...s\Bagnon\external\Wildpants\components\inventory.lua:22: CheckBagButtons()
   ...s\Bagnon\external\Wildpants\components\inventory.lua:13:
      ...s\Bagnon\external\Wildpants\components\inventory.lua:11
   [C]: Show()
   ..\FrameXML\UIParent.lua:3166: ShowUIPanel()
   ...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:55:
      ...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:51
   (tail call): ?
   ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:174: ToggleAllBags()
   [string "OPENALLBAGS"]:1:
      [string "OPENALLBAGS"]:1
Locals:
self = BagnonFrameinventory {
 0 = <userdata>
 itemFrame = <unnamed> {
 }
 searchFrame = <unnamed> {
 }
 titleFrame = <unnamed> {
 }
 bagToggle = <unnamed> {
 }
 quality = 0
 frameID = "inventory"
 searchToggle = <unnamed> {
 }
 moneyFrame = BagnonFrameinventoryMoneyFrame {
 }
 sortButton = <unnamed> {
 }
 bagFrame = <unnamed> {
 }
 profile = <table> {
 }
 closeButton = BagnonFrameinventoryCloseButton {
 }
 manualShown = true
 optionsToggle = <unnamed> {
 }
 menuButtons = <table> {
 }
 brokerDisplay = <unnamed> {
 }
}
checked = true
(*temporary) = nil
(*temporary) = MainMenuBarBackpackButton {
 0 = <userdata>
 PostOnLoad = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:169
 animIcon = <unnamed> {
 }
 ItemContextOverlay = <unnamed> {
 }
 PostOnShow = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:189
 GetItemContextMatchResult = <function> defined @Interface\FrameXML\MainMenuBarBagButtons.lua:5
 IconBorder = <unnamed> {
 }
 icon = MainMenuBarBackpackButtonIconTexture {
 }
 Count = MainMenuBarBackpackButtonCount {
 }
 flyin = <unnamed> {
 }
 SetMatchesSearch = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:202
 UpdateItemContextOverlay = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:222
 GetBagID = <function> defined @Interface\FrameXML\MainMenuBarBagButtons.lua:9
 itemContextChangedCallbackIsSet = true
 itemContextMatchResult = 3
 itemContextChangedCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:170
 RegisterCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:175
 SlotHighlightTexture = <unnamed> {
 }
 IconOverlay = <unnamed> {
 }
 UnregisterCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:182
 UpdateItemContextMatching = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:211
 searchOverlay = MainMenuBarBackpackButtonSearchOverlay {
 }
 GetMatchesSearch = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:207
 freeSlots = 30
 PostOnHide = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:198
}
(*temporary) = true
(*temporary) = "attempt to call method 'SetChecked' (a nil value)"

AddOns:
  Swatter, v8.1.6241 (SwimmingSeadragon)
  AucAdvanced, v8.1.6201 (SwimmingSeadragon)
  AucFilterBasic, v8.1.6228 (SwimmingSeadragon)
  AucStatHistogram, v8.1.6230 (SwimmingSeadragon)
  AucStatiLevel, v8.1.6234 (SwimmingSeadragon)
  AucStatPurchased, v8.1.6231 (SwimmingSeadragon)
  AucStatSimple, v8.1.6232 (SwimmingSeadragon)
  AucStatStdDev, v8.1.6233 (SwimmingSeadragon)
  AucUtilFixAH, v8.1.6235 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.1.6
  BeanCounter, v8.1.6236 (SwimmingSeadragon)
  Carbonite, vv8.1.2.1
  CarboniteNotes, vv8.1
  CarboniteQuests, vv8.1.2
  DBMCore, v8.1.11
  DBMDefaultSkin, v
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  EasyDisenchant, v1.1.7
  Enchantrix, v8.1.6237 (SwimmingSeadragon)
  GatherMate2, v1.43.6
  GTFO, v4.46.17
  HandyNotes, vv1.5.5
  HandyNotesArgus, v0.20.0
  HandyNotesBrokenShore, vv1.30
  HandyNotesLegionRaresTreasures, v1.1
  HandyNotesLegionTreasures, v1
  Informant, v8.1.6246 (SwimmingSeadragon)
  LootAppraiser, vv1.9.3
  MobInfo2, v8.1.0
  Omen, v3.2.0
  Parrot, vv2.1.4
  Paste, v1.4.10
  RealmHopAssist, vr04 beta
  Recount, vv8.1.0d
  Routes, vv1.6.1
  SellJunk, v3.0.20
  SlideBar, v8.1.6239 (SwimmingSeadragon)
  Stubby, v8.1.6240 (SwimmingSeadragon)
  TomTom, vv80100-1.0.1
  WorldQuestTracker, v
  BlizRuntimeLib_enUS v8.1.5.80100 <none>
  (ck=51f)

Thanks in advance! :)

**Comment by Zarastra** [comment]
I have been getting the error below when I open the mailbox in WoW, which started with the new WoW patch that came out this week and I get the error every time I open my mailbox.

Message: ...s\Bagnon\external\Wildpants\components\inventory.lua:22: attempt to call method 'SetChecked' (a nil value)
Time: Wed Mar 13 23:28:19 2019
Count: 1
Stack: ...s\Bagnon\external\Wildpants\components\inventory.lua:22: attempt to call method 'SetChecked' (a nil value)
...s\Bagnon\external\Wildpants\components\inventory.lua:22: in function `CheckBagButtons'
...s\Bagnon\external\Wildpants\components\inventory.lua:13: in function <...s\Bagnon\external\Wildpants\components\inventory.lua:11>
[C]: in function `Show'
Interface\FrameXML\UIParent.lua:3166: in function `ShowUIPanel'
...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:55: in function `ShowFrame'
...s\Bagnon\external\Wildpants\features\autoDisplay.lua:166: in function `OpenAllBags'
Interface\FrameXML\MailFrame.lua:63: in function <Interface\FrameXML\MailFrame.lua:50>
[C]: in function `TurnOrActionStop'
[string "TURNORACTION"]:4: in function <[string "TURNORACTION"]:1>

Locals: self = BagnonFrameinventory {
 frameID = "inventory"
 searchToggle = <unnamed> {
 }
 moneyFrame = BagnonFrameinventoryMoneyFrame {
 }
 sortButton = <unnamed> {
 }
 searchFrame = <unnamed> {
 }
 brokerDisplay = <unnamed> {
 }
 itemFrame = <unnamed> {
 }
 0 = <userdata>
 profile = <table> {
 }
 closeButton = BagnonFrameinventoryCloseButton {
 }
 optionsToggle = <unnamed> {
 }
 titleFrame = <unnamed> {
 }
 bagToggle = <unnamed> {
 }
 ownerSelector = <unnamed> {
 }
 menuButtons = <table> {
 }
 quality = 0
}
checked = true
(*temporary) = nil
(*temporary) = MainMenuBarBackpackButton {
 0 = <userdata>
 PostOnLoad = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:169
 animIcon = <unnamed> {
 }
 ItemContextOverlay = <unnamed> {
 }
 PostOnShow = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:189
 GetItemContextMatchResult = <function> defined @Interface\FrameXML\MainMenuBarBagButtons.lua:5
 IconBorder = <unnamed> {
 }
 Count = MainMenuBarBackpackButtonCount {
 }
 icon = MainMenuBarBackpackButtonIconTexture {
 }
 ClearSetPoint = <function> defined @Interface\AddOns\Bartender4\BagBar.lua:64
 flyin = <unnamed> {
 }
 SetMatchesSearch = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:202
 UpdateItemContextOverlay = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:222
 GetBagID = <function> defined @Interface\FrameXML\MainMenuBarBagButtons.lua:9
 itemContextChangedCallbackIsSet = true
 itemContextMatchResult = 3
 itemContextChangedCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:170
 RegisterCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:175
 SlotHighlightTexture = <unnamed> {
 }
 IconOverlay = <unnamed> {
 }
 UnregisterCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:182
 UpdateItemContextMatching = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:211
 searchOverlay = MainMenuBarBackpackButtonSearchOverlay {
 }
 GetMatchesSearch = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:207
 freeSlots = 71
 PostOnHide = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:198
}
(*temporary) = true
(*temporary) = "attempt to call method 'SetChecked' (a nil value)"

**Comment by phun-ky** [comment]
Got the same issue here, when first logging into the world, and then every time i open or close the bags

```
Message: ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:187: hooksecurefunc(): BagSlotButton_UpdateChecked is not a function
Time: Thu Mar 14 09:34:31 2019
Count: 1
Stack: ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:187: hooksecurefunc(): BagSlotButton_UpdateChecked is not a function
[C]: in function `hooksecurefunc'
...s\Bagnon\external\Wildpants\features\autoDisplay.lua:187: in function `HookInterfaceEvents'
...s\Bagnon\external\Wildpants\features\autoDisplay.lua:14: in function <...s\Bagnon\external\Wildpants\features\autoDisplay.lua:12>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:558: in function `EnableAddon'
...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:571: in function `EnableAddon'
...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:651: in function <...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:446: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:565: in function `TimeManager_LoadUI'
Interface\FrameXML\UIParent.lua:1192: in function <Interface\FrameXML\UIParent.lua:1090>

Locals: <none>
```

**Comment by twcoolen** [comment]
I think I have the same issue. Not upon first logon but upon first bag opening:

Date: 2019-03-14 15:06:09
ID: 2
Error occured in: Global
Count: 1
Message: ...s\Bagnon\external\Wildpants\components\inventory.lua line 22:
   attempt to call method 'SetChecked' (a nil value)
Debug:
   [C]: SetChecked()
   ...s\Bagnon\external\Wildpants\components\inventory.lua:22: CheckBagButtons()
   ...s\Bagnon\external\Wildpants\components\inventory.lua:13:
      ...s\Bagnon\external\Wildpants\components\inventory.lua:11
   [C]: ?
   [C]: Show()
   ..\FrameXML\UIParent.lua:3166: ShowUIPanel()
   ...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:55:
      ...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:51
   (tail call): ?
   ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:174:
      ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:173
   [C]: ToggleAllBags()
   [string "OPENALLBAGS"]:1:
      [string "OPENALLBAGS"]:1
Locals:

AddOns:
  Swatter, v8.1.6241 (SwimmingSeadragon)
  AucAdvanced, v8.1.6201 (SwimmingSeadragon)
  AucFilterBasic, v8.1.6228 (SwimmingSeadragon)
  AucStatHistogram, v8.1.6230 (SwimmingSeadragon)
  AucStatiLevel, v8.1.6234 (SwimmingSeadragon)
  AucStatPurchased, v8.1.6231 (SwimmingSeadragon)
  AucStatSimple, v8.1.6232 (SwimmingSeadragon)
  AucStatStdDev, v8.1.6233 (SwimmingSeadragon)
  AucUtilFixAH, v8.1.6235 (SwimmingSeadragon)
  Auctionator, v8.1.0
  AzeritePowerWeights, v8.1.11
  AzeriteTooltip, v2.0.2
  BagBrother, v
  Bagnon, v8.1.6
  BagnonConfig, v8.1.6
  BagnonScrap, v8.1.0
  BeanCounter, v8.1.6236 (SwimmingSeadragon)
  DBMCore, v8.1.11
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.6.2
  Enchantrix, v8.1.6237 (SwimmingSeadragon)
  GTFO, v4.46.17
  HandyNotes, vv1.5.5
  HandyNotesBattleForAzerothTreasures, v1
  HandyNotesDungeonLocations, v1.45
  HandyNotesWarfrontRares, v0.5.0
  HandyNotesWarfrontTreasures, v1
  HealBot, v8.1.0.7
  HealBotTips, v8.1.0.7
  Informant, v8.1.6246 (SwimmingSeadragon)
  MaxDps, v8.1.3.1
  Oilvl, v8.0.2
  OmniCC, v8.1.1
  OmniCCConfig, v
  Pawn, v2.2.39
  PersonalLootHelper, v2.19
  Recount, vv8.1.0d
  Scrap, v13.15
  ScrapOptions, v13.15
  Simulationcraft, v1.10.11
  SlideBar, v8.1.6239 (SwimmingSeadragon)
  Stubby, v8.1.6240 (SwimmingSeadragon)
  Titan, v5.17.0.80100
  TitanBag, v5.17.0.80100
  TitanClock, v5.17.0.80100
  TitanCurrenciesMulti, v6.3
  TitanGold, v5.17.0.80100
  TitanLocation, v5.17.0.80100
  TitanLootType, v5.17.0.80100
  TitanPerformance, v5.17.0.80100
  TitanRepair, v5.17.0.80100
  TitanReputation, v3.9.5
  TitanVolume, v5.17.0.80100
  TitanXP, v5.17.0.80100
  WeakAuras, v2.11.6
  WorldQuestTracker, v
  BlizRuntimeLib_enUS v8.1.5.80100 <none>
  (ck=6c2)

**Comment by Zarastra** [comment]
That’s when I get it. Logon is fine, but when I open the mailbox, which opens the bags or just opening the bags, it occurs every time and it started after the new WoW patch that came out earlier this week, so something in the bagnon code is clearly conflicting with the new WoW patch. I’m not a programmer or coder, but I’ve been in IT for 20 years and when something breaks the most recent change is typically the culprit.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DasReport** [comment]
Opening inventory got this Bug Sack:

2x ...s\Bagnon\external\Wildpants\components\inventory.lua:22: attempt to call method 'SetChecked' (a nil value)
...s\Bagnon\external\Wildpants\components\inventory.lua:22: in function `CheckBagButtons'
...s\Bagnon\external\Wildpants\components\inventory.lua:13: in function <...s\Bagnon\external\Wildpants\components\inventory.lua:11>
[C]: in function `Show'
FrameXML\UIParent.lua:3166: in function `ShowUIPanel'
...aceBagnon\external\Wildpants\core\frames.lua:55: in function <...aceBagnon\external\Wildpants\core\frames.lua:51>
(tail call): ?
...s\Bagnon\external\Wildpants\features\autoDisplay.lua:174: in function <...s\Bagnon\external\Wildpants\features\autoDisplay.lua:173>
[C]: in function `ToggleAllBags'
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Locals:
self = BagnonFrameinventory {
 0 = <userdata>
 itemFrame = <unnamed> {
 }
 searchFrame = <unnamed> {
 }
 titleFrame = <unnamed> {
 }
 manualShown = true
 bagToggle = <unnamed> {
 }
 quality = 0
 frameID = "inventory"
 searchToggle = <unnamed> {
 }
 moneyFrame = BagnonFrameinventoryMoneyFrame {
 }
 sortButton = <unnamed> {
 }
 bagFrame = <unnamed> {
 }
 profile = <table> {
 }
 closeButton = BagnonFrameinventoryCloseButton {
 }
 optionsToggle = <unnamed> {
 }
 ownerSelector = <unnamed> {
 }
 menuButtons = <table> {
 }
 brokerDisplay = <unnamed> {
 }
}
checked = true
(*temporary) = nil
(*temporary) = MainMenuBarBackpackButton {
 0 = <userdata>
 PostOnLoad = <function> defined @FrameXML\ItemButtonTemplate.lua:169
 animIcon = <unnamed> {
 }
 ItemContextOverlay = <unnamed> {
 }
 PostOnShow = <function> defined @FrameXML\ItemButtonTemplate.lua:189
 GetItemContextMatchResult = <function> defined @FrameXML\MainMenuBarBagButtons.lua:5
 IconBorder = <unnamed> {
 }
 icon = MainMenuBarBackpackButtonIconTexture {
 }
 Count = MainMenuBarBackpackButtonCount {
 }
 flyin = <unnamed> {
 }
 SetMatchesSearch = <function> defined @FrameXML\ItemButtonTemplate.lua:202
 UpdateItemContextOverlay = <function> defined @FrameXML\ItemButtonTemplate.lua:222
 GetBagID = <function> defined @FrameXML\MainMenuBarBagButtons.lua:9
 itemContextChangedCallbackIsSet = true
 itemContextMatchResult = 3
 itemContextChangedCallback = <function> defined @FrameXML\ItemButtonTemplate.lua:170
 RegisterCallback = <function> defined @FrameXML\ItemButtonTemplate.lua:175
 SlotHighlightTexture = <unnamed> {
 }
 IconOverlay = <unnamed> {
 }
 UnregisterCallback = <function> defined @FrameXML\ItemButtonTemplate.lua:182
 UpdateItemContextMatching = <function> defined @FrameXML\ItemButtonTemplate.lua:211
 searchOverlay = MainMenuBarBackpackButtonSearchOverlay {
 }
 GetMatchesSearch = <function> defined @FrameXML\ItemButtonTemplate.lua:207
 freeSlots = 81
 PostOnHide = <function> defined @FrameXML\ItemButtonTemplate.lua:198
}
(*temporary) = true
(*temporary) = "attempt to call method 'SetChecked' (a nil value)"

**Comment by phun-ky** [comment]
Why close without explanation or a fix?

**Comment by Zarastra** [comment]
Agee, this ticket shouldn’t have been closed without being resolved.


________________________________

**Comment by seascape195** [comment]
This was resolved under other ticket.. looks like they just mass closed a bunch of the duplicate tickets

**Comment by Zarastra** [comment]
But didn’t actually resolve the issue. Now that’s what I call customer no service.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
