### ISSUE TITLE
bagnon not showing any bag slots completely blank

### ISSUE THREAD

**Issue by Wouterdude** [tullamods/Bagnon#900]
Date: 2019-03-10 10:52:48
ID: -13
Error occured in: AddOn: ZygorGuidesViewer
Count: 60
Message: Note: AddOn ZygorGuidesViewer attempted to call a protected function (ZygorGuidesViewerFrame:SetHeight()) during combat lockdown.
Debug:
   [C]: SetHeight()
   ...rface\AddOns\ZygorGuidesViewer\ZygorGuidesViewer.lua:3215:
      ...rface\AddOns\ZygorGuidesViewer\ZygorGuidesViewer.lua:2277
   (tail call): ?
   ...rface\AddOns\ZygorGuidesViewer\ZygorGuidesViewer.lua:1562: FocusStepUnquiet()
   ...rface\AddOns\ZygorGuidesViewer\ZygorGuidesViewer.lua:1473: FocusStep()
   ...rface\AddOns\ZygorGuidesViewer\ZygorGuidesViewer.lua:1722: SkipStep()
   ...rface\AddOns\ZygorGuidesViewer\ZygorGuidesViewer.lua:1974: TryToCompleteStep()
   ZygorGuidesViewer\QuestTracking.lua:406: ?()
   ...rface\AddOns\ZygorGuidesViewer\ZygorGuidesViewer.lua:935: ?()
   ...ibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:119:
      ...ibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:119
   [C]: ?
   ...ibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:29:
      ...ibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:25
   ...ibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:64: Fire()
   ...xternal\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:120:
      ...xternal\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:119
Locals:
None
AddOns:
  Swatter, v8.1.6241 (SwimmingSeadragon)
  AucAdvanced, v8.1.6201 (SwimmingSeadragon)
  AucFilterBasic, v8.1.6228 (SwimmingSeadragon)
  AucScanData, v8.1.6229 (SwimmingSeadragon)
  AucStatHistogram, v8.1.6230 (SwimmingSeadragon)
  AucStatiLevel, v8.1.6234 (SwimmingSeadragon)
  AucStatPurchased, v8.1.6231 (SwimmingSeadragon)
  AucStatSimple, v8.1.6232 (SwimmingSeadragon)
  AucStatStdDev, v8.1.6233 (SwimmingSeadragon)
  AucUtilFixAH, v8.1.6235 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.1.6
  BeanCounter, v8.1.6236 (SwimmingSeadragon)
  DBMCore, v8.1.11
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  Enchantrix, v8.1.6237 (SwimmingSeadragon)
  GatherMate2, v1.43.5
  Grail, v099
  GrailAchievements, v011
  GrailQuestsenUS, v27178
  GrailReputations, v007
  Informant, v8.1.6246 (SwimmingSeadragon)
  Omen, v3.2.0
  SlideBar, v8.1.6239 (SwimmingSeadragon)
  Stubby, v8.1.6240 (SwimmingSeadragon)
  TidyPlates, v6.19.3
  TidyPlatesGraphite, v
  TidyPlatesGrey, v
  TidyPlatesNeon, v
  TidyPlatesQuatre, v
  TidyPlatesHub, v
  TidyPlatesWidgets, v
  WeakAuras, v2.11.6
  Wholly, v070
  ZygorGuidesViewer, v7.0
  BlizRuntimeLib_enUS v8.1.0.80100 <none>
  (ck=508)

**Comment by robertjamesftw** [comment]
Why are you posting an error with ZygorGuidesViewer in the Bagnon issues forum?

**Comment by Wouterdude** [comment]
I do not know why the error message says it is a error with Zygor

The error is with Bagnon, even with zygor guides the bags still show no
slots.
