### ISSUE TITLE
Banks not working

### ISSUE THREAD

**Issue by SilverDragn** [tullamods/Bagnon#904]
![WoWScrnShot_031419_124012](https://user-images.githubusercontent.com/1246277/54386629-a459ef80-4656-11e9-8a6b-1f3366c7154e.jpg)
This is what I see when I open my guild bank and personal bank
![WoWScrnShot_031419_124418](https://user-images.githubusercontent.com/1246277/54386763-ed11a880-4656-11e9-8a84-80670fdbed6e.jpg)
And this is what I see if I disable the bank frame and try to open the bank

Lua Error 1
Message: ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:187: hooksecurefunc(): BagSlotButton_UpdateChecked is not a function
Time: Thu Mar 14 12:38:10 2019
Count: 1
Stack: ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:187: hooksecurefunc(): BagSlotButton_UpdateChecked is not a function
[C]: ?
...dOns\AutoProfitX2\libs\AceAddon-3.0\AceAddon-3.0.lua:70: in function <...dOns\AutoProfitX2\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
...dOns\AutoProfitX2\libs\AceAddon-3.0\AceAddon-3.0.lua:527: in function `EnableAddon'
...dOns\AutoProfitX2\libs\AceAddon-3.0\AceAddon-3.0.lua:540: in function `EnableAddon'
...dOns\AutoProfitX2\libs\AceAddon-3.0\AceAddon-3.0.lua:620: in function <...dOns\AutoProfitX2\libs\AceAddon-3.0\AceAddon-3.0.lua:605>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:446: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:489: in function `CombatLog_LoadUI'
Interface\FrameXML\UIParent.lua:1194: in function <Interface\FrameXML\UIParent.lua:1090>

Locals: <none>

Lua error 2
Message: ...s\Bagnon\external\Wildpants\components\inventory.lua:22: attempt to call method 'SetChecked' (a nil value)
Time: Thu Mar 14 13:48:12 2019
Count: 36
Stack: ...s\Bagnon\external\Wildpants\components\inventory.lua:22: attempt to call method 'SetChecked' (a nil value)

Locals: 

Lua error 3 
Message: ...AddOns\Bagnon\external\Wildpants\components\item.lua:47: attempt to index field 'IconOverlay' (a nil value)
Time: Thu Mar 14 13:47:22 2019
Count: 39
Stack: ...AddOns\Bagnon\external\Wildpants\components\item.lua:47: attempt to index field 'IconOverlay' (a nil value)

Locals:

**Comment by schufirefly** [comment]
I am have a similar issue with banks.. When i click on manage bank tab to clean up.. i get a message that says "item is locked".. i have latest Bagnon.. personal bags work fine. Heres a screenshot.
![wow2](https://user-images.githubusercontent.com/42497606/54387465-dcbaf700-4671-11e9-9a9e-6f58ed6abb97.png)

**Comment by pdiegosilva** [comment]
Same thing happening here. When I go to the bank and try to sort items I get a message saying "Item is locked". What to do? Any workarounds to do on the code?

**Comment by schufirefly** [comment]
No idea personally...

Sent from my iPhone

On Mar 14, 2019, at 4:53 PM, pdiegosilva <notifications@github.com<mailto:notifications@github.com>> wrote:


Same thing happening here. When I go to the bank and try to sort items I get a message saying "Item is locked". What to do? Any workarounds to do on the code?

**Comment by Crowic** [comment]
I am having the same "Item is locked" issue. I cannot tell if it is just a feature I am not familiar with or if it is a bug.
