### ISSUE TITLE
Error post every time a bag is opened in WOW after patch 8.1.5

### ISSUE THREAD

**Issue by NDS1989** [tullamods/Bagnon#906]
World of Warcraft - BFA
 - Game Version - 8.1.5.29732
 - Addon version - 8.1.6

**Describe the bug**
An error is posted every time I open a bag

**To Reproduce**
1. simply open a bag, any bag
2. error will display
3. I have currently disabled the addon to avoid constantly seeing the error (noted in error log section)

**Expected behavior**
Unified Bagnon bag should display.

**Screenshots**
X

**Error Logs**
Message: ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:187: hooksecurefunc(): BagSlotButton_UpdateChecked is not a function
Time: Fri Mar 15 08:13:38 2019
Count: 1
Stack: ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:187: hooksecurefunc(): BagSlotButton_UpdateChecked is not a function
[C]: in function `hooksecurefunc'
...s\Bagnon\external\Wildpants\features\autoDisplay.lua:187: in function `HookInterfaceEvents'
...s\Bagnon\external\Wildpants\features\autoDisplay.lua:14: in function <...s\Bagnon\external\Wildpants\features\autoDisplay.lua:12>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...AddOns\AskMrRobot\Libs\AceAddon-3.0\AceAddon-3.0.lua:558: in function `EnableAddon'
...AddOns\AskMrRobot\Libs\AceAddon-3.0\AceAddon-3.0.lua:571: in function `EnableAddon'
...AddOns\AskMrRobot\Libs\AceAddon-3.0\AceAddon-3.0.lua:651: in function <...AddOns\AskMrRobot\Libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:446: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:489: in function `CombatLog_LoadUI'
Interface\FrameXML\UIParent.lua:1194: in function <Interface\FrameXML\UIParent.lua:1090>

Locals: <none>

---------------------------

NOTE: have to disable the addon to play the game without always having to see the above error keep popping up.

**Comment by dafluna** [comment]
This is the exact same error I have gotten since the recent patch. I posted something but it was closed without a resolution. https://github.com/tullamods/Bagnon/issues/887.

I have even downloaded the latest version of the addon and the issue remains.

**Comment by NDS1989** [comment]
Dafluna, I too uninstalled it and reinstalled but ummmhmmm, this did not heal Bagnon. Either way, hope the devs find what the bug is and fix it quick fast. I've been using Bagnon for the past few years and I love the organization it allows for my bags. Hope this gets fixed soon.

**Comment by seascape195** [comment]
https://github.com/tullamods/Bagnon/issues/885  <= Try this workaround (involved edits to two files, but very accurate screenshots posted for exactly what to delete.  Blizzard made a change to the slotchecker causing the problem

**Comment by dafluna** [comment]
Seascape195, as I put in my closed thread, i'm not comfortable changing code,  so that solution doesn't work for me.

**Comment by seascape195** [comment]
Posting repeatedly won't speed it up.  There's a ton of tickets for the SAME thing (duplicate ticket nightmare).  There was a release via twitch -- did you not run that update?

**Comment by dafluna** [comment]
I haven't been on this morning,  but I installed the latest version last night and the issue remained. When a ticket is closed without a reason given and the issue remains,  that makes it seem the issue is being ignored. I didn't create a new ticket,  but added my experience to one I saw that is still open.

**Comment by NDS1989** [comment]
Good, its closed, anyways, whatever was done worked and now the problem is solved :-) Thanks all
