### ISSUE TITLE
guild bank error 

### ISSUE THREAD

**Issue by Stalkinya** [tullamods/Bagnon#907]
Date: 2019-03-15 08:57:48
ID: 1
Error occured in: Global
Count: 1
Message: ...s\Bagnon\external\Wildpants\features\autoDisplay.lua line 187:
   hooksecurefunc(): BagSlotButton_UpdateChecked is not a function
Debug:
   [C]: hooksecurefunc()
   ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:187: HookInterfaceEvents()
   ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:14:
      ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:12
   [C]: ?
   Ace3\AceAddon-3.0\AceAddon-3.0.lua:70:
      Ace3\AceAddon-3.0\AceAddon-3.0.lua:65
   Ace3\AceAddon-3.0\AceAddon-3.0.lua:527: EnableAddon()
   Ace3\AceAddon-3.0\AceAddon-3.0.lua:540: EnableAddon()
   Ace3\AceAddon-3.0\AceAddon-3.0.lua:620:
      Ace3\AceAddon-3.0\AceAddon-3.0.lua:605
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:446: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:489: CombatLog_LoadUI()
   ..\FrameXML\UIParent.lua:1194:
      ..\FrameXML\UIParent.lua:1090
Locals:
None
AddOns:
  Swatter, v8.1.6241 (SwimmingSeadragon)
  Ace3, v
  ACP, vr259 
  AdvancedInterfaceOptions, v1.2.9
  AskMrRobot, v73
  Auctionator, v8.1.0
  BagBrother, v
  Bagnon, v8.1.6
  Bartender4, v4.8.2
  DBMCore, v8.1.11
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsChartViewer, v
  DetailsDeathGraphs, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsRaidPowerBars, v
  DetailsStreamer, v
  DetailsTargetCaller, v
  DetailsTimeLine, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  FBTrackingFrame, v1.9.1
  FishingBuddy, v1.9.27
  LibSharedMedia30, v3.0-104
  Masque, v8.0.1
  MoveAnything, v17.0.3
  Omen, v3.2.0
  OmniCC, v8.1.1
  oRA3, vv8.1.1
  Outfitter, v5.22.1
  Pawn, v2.2.37
  Postal, vv3.6.0
  PowerAuras, v4.30.2
  Quartz, v3.4.0
  RaidAssist, v
  SavedInstances, v8.1.0
  sellgrey, v8.0.1
  ServerHop, v8.0.1.1
  SexyMap, vv8.0.8
  Simulationcraft, v1.10.11
  SlideBar, v8.1.6239 (SwimmingSeadragon)
  StatBlockFPS, v
  Stubby, v8.1.6240 (SwimmingSeadragon)
  SunnArt, v3.80
  SunnArtPack9, v1.23
  TellMeWhen, v8.6.0
  Titan, v5.17.0.80100
  TitanBag, v5.17.0.80100
  TitanClock, v5.17.0.80100
  TitanCurrenciesMulti, v6.3
  TitanGold, v5.17.0.80100
  TitanHeartofAzeroth, vv1.0.0
  TitanLocation, v5.17.0.80100
  TitanLootType, v5.17.0.80100
  TitanPerformance, v5.17.0.80100
  TitanRepair, v5.17.0.80100
  TitanReputation, v3.9.5
  TitanReputations, vv1.17
  TitanVolume, v5.17.0.80100
  TitanWowToken, v5.14.3.80000
  TitanXP, v5.17.0.80100
  WeakAuras, v2.11.6
  WorldQuestTracker, v
  XPerlFacade, v4.0.1
  ZPerl, v5.7.2
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidAdmin, v
  ZPerlRaidFrames, v
  ZPerlRaidHelper, v
  ZPerlRaidMonitor, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_enUS v8.1.5.80100 <none>
  (ck=749)

**Comment by YouTubeNATE** [comment]
Although the guild bank now appears, the frame settings are jumbled & all screwed up.  It also won't display at the requested 20 columns.

**Comment by Jaliborc** [comment]
@YouTubeNATE It is working fine for me on all the 3 different test guilds. Is the issue new or was it there before 8.1.5

**Comment by Stalkinya** [comment]
guild bank portion worked fine prior to the latest blizzard patch. The tabs show but none of the bank slots area shows 





Michael Cox

 
 

    On Friday, March 15, 2019, 7:34:08 PM CDT, João Cardoso <notifications@github.com> wrote:  
 
 
@YouTubeNATE It is working fine for me on all the 3 different test guilds. Is the issue new or was it there before 8.1.5
