### ISSUE TITLE
Cannot sort/clean up my bank

### ISSUE THREAD

**Issue by Yrlish** [tullamods/Bagnon#908]
**Running Software (please complete the following information):**
 - WoW 8.1.5.29732
 - Bagnon 8.1.7

**Describe the bug**
When I try to clean up the bank bag by right-clicking the sort icon, only the reagents gets cleaned up. The "regular" bank bags does not change at all and an error appears: "Item is locked".

**To Reproduce**
Go to the bank, move some items and try to clean it up by right-clicking the sort icon.

**Expected behavior**
The bank bags should be sorted.

**Comment by Manback** [comment]
I have the same problem.

**Comment by YouTubeNATE** [comment]
Ya... I right click on that bank tab to clean-up, and it says, "It's locked" and alert reads, "Item is locked.".. WTF?  Please fix this issue.

**Comment by Jaliborc** [comment]
Fixed

**Comment by Yrlish** [comment]
@Jaliborc ETA on release? 🙂

**Comment by Jaliborc** [comment]
Yesterday? Version 8.1.8

**Comment by Yrlish** [comment]
Oh, I didn't notice. Whoops! 😋

**Comment by Blackgeckos** [comment]
Hi,

It seems the bug appear again in 9.1.4/9.1.5.
I was selling my item with friend pet (mammoth) then it drop the mammoth as i was selling. The item seems to be bugged (it is greyed) and and can unequip the bag, as the game told me it is not empty. I can't sort inventory, even if I exclude this bag from the sorting.

Best regards,
