### ISSUE TITLE
Bug with bag items not showing as locked when they are put in a new mail message

### ISSUE THREAD

**Issue by nightness** [tullamods/Bagnon#915]
**Running Software (please complete the following information):**
 - 8.1.5
 - 8.1.8

**Describe the bug**
Items don't show as "locked" unless a BAG_UPDATE occurs, but just right clicking them into the mail message, doesn't lock the icon (the grayed out look)...

**To Reproduce**
1. Start a new mail message
2. Start crafting a bunch of new items (something that wont stack, like gear)... This generates bag update events.
3. After the gear is created, add to mail... Do this several times.
4. You will see after a "bag update", the proper grayed look for a locked button is displayed. But it's not happened on the right-click event to add the item to the message,

**Expected behavior**
Proper display of locked status (grayed out, can't pick-up).

**Screenshots**
Not needed

**Error Logs**
None

**Additional context**
None

**Comment by LudiusMaximus** [comment]
While you are waiting for this to be fixed, you can use https://wow.curseforge.com/projects/bagnon-lockeditemsfix.

**Comment by Jaliborc** [comment]
This happens at the mailbox? Ok, that explains why I wasn't able to reproduce.

**Comment by Jaliborc** [comment]
Fixed
