### ISSUE TITLE
Sorting of Reagent Bank

### ISSUE THREAD

**Issue by zaldor29** [tullamods/Bagnon#924]
**Running Software (please complete the following information):**
 - Game patch 8.1.5 (29981) (Release x64)
 - 8.1.9

**Describe the bug**
Some of my characters can sort the reagent bag, but most cannot.  The main bank bags seem to sort ok, but the reagent bag will not.

**To Reproduce**
Right click on manage bank

**Expected behavior**
Grouping of items in reagent bank and sort

**Comment by Slakker** [comment]
I am experiencing the exact same issue as the OP.  Very frustrating.

**Comment by ryooshi** [comment]
Experiencing the same issue as well.  Some characters can sort and some can't.

**Comment by Yrlish** [comment]
Having the same problem. Running the same versions as @zaldor29.
