### ISSUE TITLE
Will Bagnon be released for WOW Classic?

### ISSUE THREAD

**Issue by NoobTaco** [tullamods/Bagnon#925]
I am gathering a list and have always loved Bagnon. Are there any plans to release a Classic version of Bagnon? Granted we still need API information an a beta to test, but is this on the possible backlog?

Thanks

**Comment by Jaliborc** [comment]
Can't 100% guarantee until I see the actual classic build, but yes, I intend to do so.

**Comment by NoobTaco** [comment]
Awesome! Thank you for the information. I will update the list.
