### ISSUE TITLE
Can't make your bag look normal with 32 slot bags

### ISSUE THREAD

**Issue by Redespo** [tullamods/Bagnon#930]
Fix a better customization for the bagnon bag slots cus with the 32 slot bags there is no way in the world you can get a bag that doesnt look retarded kinda like this:

![bild](https://user-images.githubusercontent.com/51249188/58737899-a9337180-8403-11e9-9ed0-3e323784cbb8.png)

**Comment by vodvud** [comment]
What do you mean about better customization?

You may set 10 cells in row:
32 = 10 + 10 + 10 + 2

or if set 11 cells in row:
32 = 11 + 11 + 10

**Comment by Elekayl** [comment]
16 slots wide also would work perfectly, except for the back pack.  (assuming everyone has 20 slot bp now)

**Comment by Elekayl** [comment]
> 52 + 32 + 32 + 32 + 32 = 180 (will be nice if 10 cells in row)

Am I confused, or where does the 52 come from?

**Comment by vodvud** [comment]
> > 52 + 32 + 32 + 32 + 32 = 180 (will be nice if 10 cells in row)
> 
> Am I confused, or where does the 52 come from?

Oh, sorry. My did mistake, I joined first and second bag in one :)

Correct is:
20 + 32 + 32 + 32 + 32 = 148

if set 10 cells per row and join bags to remove gaps will be good. 
Only the last row 8 cells :)

**Comment by Jaliborc** [comment]
As @vodvud pointed out, its a math problem
