### ISSUE TITLE
1 character loots weird 

### ISSUE THREAD

**Issue by SakuraLilly** [tullamods/Bagnon#932]
- Bagnon vbagnon-6-12-07.zip

I use this addon on all my lovely alts. I have 1 alts where the looting behaves weird. I stead of in the bottom of my baggs (like all others) , it sets it all in the same place, behind all old loot. Non of my chars do this. I tried deleting my cache, i deleted the addon and all setting information and lua files. Basically everything. Checked settings, checked and unchecked character specific. Coppied files so recreate working chars to the non working char. Nothing fixed this. 

Loot something. It doens't end up in a empy bag below. It puts it next to my sorted loot. 
I expected it to be in the bottom like on my other chars. 

Screen shot: On loot it goes in the YELLOW section, i expect it in the RED section like on all other characters i own. 

![Schermafdruk 2019-06-15 17 35 53](https://user-images.githubusercontent.com/51858510/59553368-334b1080-8f94-11e9-9d30-790e0a5c0faf.png)

Any help, thoughts would be much appreciated.

**Comment by Sin074** [comment]
whelp you have probably tried this already however in the settings there is a option for "reverse bag order" try to turn this on or off for what ever you have it on now

**Comment by SakuraLilly** [comment]
> 
> 
> whelp you have probably tried this already however in the settings there is a option for "reverse bag order" try to turn this on or off for what ever you have it on now

Not it, :( 
Also tried the char specific on and off. Nothing helps and it's just one char :(

**Comment by SakuraLilly** [comment]
OMG i fixed it. In an old forumpost i found a by blizzard removed setting, but the code still works. For me it was : 
> /run SetInsertItemsLeftToRight(false)
If you want the opposite of me: 
> /run SetInsertItemsLeftToRight(true)

**Comment by Jaliborc** [comment]
I could force the setting to the default, but I'm worried about people using other mods to configure that setting complaining.

**Comment by Jaliborc** [comment]
What you guys think?

**Comment by SakuraLilly** [comment]
I never even thought about it untill it was suddenly different on 1 char. I can't even remember the time it was in Blizzard settings. Maybe it's something to be added as a checkmark option? I can't think of a wow without my Bagnon <3

**Comment by Jaliborc** [comment]
Could add a option in general that controls that setting
