### ISSUE TITLE
Can't open or close bags in combat

### ISSUE THREAD

**Issue by Zarupta** [tullamods/Bagnon#933]
**Running Software (please complete the following information):**
 - 8.2
 - Latest

**Describe the bug**
Cannot open or close the bag window in combat. Pressing the bag button or clicking the icon does nothing while in combat.

**Comment by EvenlyRoasted** [comment]
Yeah, it's the same for a friend and I.

**Comment by Sin074** [comment]
ya same for me, but it actually wouldn't let me open any of my ui in fights until I turned it of then on again then it was only the bags I couldn't open

**Comment by seascape195** [comment]
same for me too, if in combat since 8.2 patch bags will not open.. fix please

**Comment by Nytetears** [comment]
I too have this problem

**Comment by teralux** [comment]
Same here. It says "Interface action failed due to an addon"

**Comment by Tuller** [comment]
@Jaliborc 
HideUIPanel and ShowUIPanel cause issues in combat now.

**Comment by thefowles1** [comment]
This also affects 8.1.9 (non-b), which is the only version remotely usable as it currently stands.
