### ISSUE TITLE
Bags Open separately and the UI Glitches

### ISSUE THREAD

**Issue by Nabarium** [tullamods/Bagnon#934]
**Running Software (please complete the following information):**
 - Game patch - 8.2
 - Addon version - 8.1.9

**Describe the bug**
When opening the bags, they all come up separately. Also when I go into the alchemy crafting menu the bag open into one panel per usual, but if you toggle the bags again, the UI glitches and presents a large image on top of the UI.

**To Reproduce**
1. Open backpack
2. The first issue should be present
3. Open Alchemy crafting menu
4. Toggle backpack
5. Second issue should be present

**Expected behavior**
The backpack and all other bags should open as one panel.

**Screenshots**
![image](https://user-images.githubusercontent.com/52262601/60221457-9d827180-982e-11e9-86f8-40c366c352de.png)

![image](https://user-images.githubusercontent.com/52262601/60221421-6613c500-982e-11e9-8d4e-aa9e7ea7ecbc.png)

**Error Logs**
There was an error message, but I didn't copy it and can't reproduce it.

**Comment by raysmith59** [comment]
Confirmed that the bags no longer consolidate with today's update, I haven't tested it any further than that.

**Comment by FathomsDeep** [comment]
Upon loading, the single-panel bag interface flashes briefly, but when opened, it appears as separate bags.

**Comment by TimCorcoran** [comment]
I am having the exact same problem, with the exact same versions of both game/addon.

Strangely though, the consolidated bag loads perfectly fine when I visit the auctioneer

**Comment by Oddwin** [comment]
Also having this issue.

**Comment by jaedimaster** [comment]
Also having this issue. It was fine until about an hour ago (6:30 pm CST 06/26)

**Comment by KyrosKrane** [comment]
Issue confirmed in Bagnon v8.1.9b

**Comment by MrSinbad45** [comment]
Also to add onto op's post, after the bags become glitched out your normal bags refuse to work and you can no longer see items that are in them.
