### ISSUE TITLE
new version does not work

### ISSUE THREAD

**Issue by mynoob2** [tullamods/Bagnon#936]
**Running Software (please complete the following information):**
 - Game patch [e.g. Build 8.0.1.27178]
 - Addon version

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Error Logs**
If applicable, add the first error message (labeled 1/Many) that appeared.

**Additional context**

**Comment by mynoob2** [comment]
does not work at all

**Comment by Canadian78** [comment]
I second what mynoob2 states! Before the fix Bagnon was working, but now it has shit the bed. There is no aspect of Bagnon working.

**Comment by zaldor29** [comment]
Does not work, for me won't open bags and for a friend doesn't show their inventory.  Also, I hope this version fixes the sort for the reagents bag in the bank, that still does not work.
