### ISSUE TITLE
Newest Update Has Caused Bagnon Not to Work At All :(

### ISSUE THREAD

**Issue by Canadian78** [tullamods/Bagnon#937]
**Running Software (please complete the following information):**
 - Game patch 8.2
 - Addon version 8.1.9b

**Describe the bug**
There is nothing about Bagnon which is working since the latest update. It is there, loaded on my system, but still not working.

**To Reproduce**
Steps to reproduce the behaviour:
1. Try attempting to open any aspect of the addon.

**Expected behaviour**
I expect to see a single bag opened up as I and many have come accustomed to.

**Screenshots**
I feel that there is no need for one as my statement regarding Bagnon not working at all sums everything up.

**Error Logs**
Not receiving any error logs.

**Additional context**
Props for the guys and ladies writing the code for this addon and the many us WoW folk use daily, thank you.

**Comment by Beeeky** [comment]
Same game says Addon is loaded, I can get into the setting and still just the blizzard bags pop up.

**Comment by TyranaWookie** [comment]
I'm also experiencing an issue with the addon.

To detail my experiences, Bug Grabber is not detecting any errors with the Bagnon addon.  Pressing my keybind to open inventory only opens the default blizzard bag UI.

Going to the Interface Options > AddOns > Bagnon > Automatic Display:
I checked, unchecked, and rechecked all of the "Display Inventory" options, then performed a /reload.

**The following does correctly open the Bagnon bag UI:**
- Opening the Character's Bank
- Opening the Guild Bank
- Opening a Crafting Profession UI
- Talking to an Auctioneer
- Opening the Character window
- Trading

**The following does not open the Bagnon bag UI, but the default Blizzard bag UI:**
- Using my inventory keybind (and the default inventory keybind)
- Opening a Mailbox
- Talking to a Vendor
- Scrapping Items (Opens both the blizzard default and Bagnon bag UI's simultaneously)

Other Notes:
Using a method that correctly opens the Bagnon bag UI, then pressing the keybind to open/close inventory results in a strange mess where both the Blizzard default and Bagnon bag UI's are open in a jumbled mess.  Pressing the inventory keybind, then using another method to open the Bagnon bag UI opens both, with the Bagnon UI overlayed neatly.

**Hope this helps!**

![Bagnon Overlayed inventory](https://user-images.githubusercontent.com/52265195/60227999-1e009c80-9846-11e9-8fae-85ef0f42c296.jpg)

**Comment by Harshmage** [comment]
The command still works: /bagnon bags

**Comment by LudiusMaximus** [comment]
When I press "B" the normal wow UI separated bags open as if Bagnon was not installed at all.
When I use "/bagnon bags", I get this error message:

Message: ...Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:184: Usage: GetContainerItemInfo(index, slot)
Time: Thu Jun 27 08:00:58 2019
Count: 56
Stack: ...Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:184: Usage: GetContainerItemInfo(index, slot)
[C]: in function `GetContainerItemInfo'
...Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:184: in function <...Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:167>
(tail call): ?
(tail call): ?
...AddOns\Bagnon\external\Wildpants\components\item.lua:224: in function <...AddOns\Bagnon\external\Wildpants\components\item.lua:223>
[C]: ?
[C]: in function `Update'
...AddOns\Bagnon\external\Wildpants\components\item.lua:125: in function <...AddOns\Bagnon\external\Wildpants\components\item.lua:120>
[C]: in function `SetParent'
...AddOns\Bagnon\external\Wildpants\components\item.lua:23: in function `New'
...s\Bagnon\external\Wildpants\components\itemFrame.lua:119: in function <...s\Bagnon\external\Wildpants\components\itemFrame.lua:108>

Locals: (*temporary) = nil
(*temporary) = 0

**Comment by telsacoil** [comment]
> The command still works: /bagnon bags

I rebound Key Bindings/Other/Bagnon/Toggle Inventory to "B" and now pressing "B" opens up the Bagnon window again.  

Still getting a LUA error upon first open, but the bag function works now.

**Comment by MrYukki** [comment]
I have exact same problem but i made macro with /bagnon bags and key-binded it as b and it works just fine

**Comment by Telrikthebrave** [comment]
Exact same problem as above. I used the /bagnon bags command which opened bags properly, left clicked on the deposit reagent button.. and now my bank is totally rearranged, which I hate more than anything in this game.
