### ISSUE TITLE
Bagnon not working after newest update

### ISSUE THREAD

**Issue by Xvenom82** [tullamods/Bagnon#938]
**Running Software (please complete the following information):**
 - Game patch 8.2
 - Addon version Bagnon 8.1.9b

**Describe the bug**
Each individual bags opening up instead of one big bag

**To Reproduce**
![WoWScrnShot_062619_220244](https://user-images.githubusercontent.com/52265860/60227724-58763380-985e-11e9-8245-c76704c483f9.jpg)

**Expected behavior**
Should open into one big bag

**Screenshots**

**Error Logs**
If applicable, add the first error message (labeled 1/Many) that appeared.

**Additional context**

**Comment by Dalarrus** [comment]
Current work around is to manually bind Bagnon to B via the ingame keybinds menu, in the addons subsection.

**Comment by zaldor29** [comment]
That allows you to access your bags, but causes a multitude of different issues with vendors.
