### ISSUE TITLE
Bagnon not opening when i press B, only way to use it is open it otherway

### ISSUE THREAD

**Issue by Rippeee** [tullamods/Bagnon#939]
Date: 2019-06-27 05:35:51
ID: 1
Error occured in: Global
Count: 1
Message: Error trapped for Processor message 'itemtooltip' in module ItemSuggest:
..\AddOns\Auc-Advanced\CorePost.lua line 547:
   attempt to index upvalue 'ScanTip3' (a nil value)
Debug:
   Auc-Advanced\CoreUtil.lua:917: SendProcessorMessage()
   Auc-Advanced\CoreMain.lua:178:
      Auc-Advanced\CoreMain.lua:56
   (tail call): ?
   ...AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:115:
      ...AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:99
   ...AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:171: h()
   ...AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:480:
      ...AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:476
   [C]: ?
   [C]: ?
   [C]: OnTooltipSetItem()
   Enchantrix\EnxMain.lua:232:
      Enchantrix\EnxMain.lua:228
   [C]: ?
   [C]: ?
   ...AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:408:
      ...AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:402
   ...face\AddOns\TradeSkillMaster\Core\Lib\TooltipLib.lua:78:
      ...face\AddOns\TradeSkillMaster\Core\Lib\TooltipLib.lua:76
   [C]: SetBagItem()
   ..\FrameXML\ContainerFrame.lua:1403: ContainerFrameItemButton_OnEnter()
   [string "*:OnEnter"]:1:
      [string "*:OnEnter"]:1
Locals:
None
AddOns:
  Swatter, v8.1.6241 (SwimmingSeadragon)
  AucAdvanced, v8.1.6201 (SwimmingSeadragon)
  AucFilterBasic, v8.1.6228 (SwimmingSeadragon)
  AucStatHistogram, v8.1.6230 (SwimmingSeadragon)
  AucStatiLevel, v8.1.6234 (SwimmingSeadragon)
  AucStatPurchased, v8.1.6231 (SwimmingSeadragon)
  AucStatSimple, v8.1.6232 (SwimmingSeadragon)
  AucStatStdDev, v8.1.6233 (SwimmingSeadragon)
  AucUtilFixAH, v8.1.6235 (SwimmingSeadragon)
  Auctionator, v8.1.0
  BagBrother, v
  Bagnon, v8.1.9
  BagnonConfig, v8.1.9
  BeanCounter, v8.1.6236 (SwimmingSeadragon)
  DBMCore, v8.2.1
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  Enchantrix, v8.1.6237 (SwimmingSeadragon)
  GatherMate2, v1.43.6
  GTFO, v4.48.3
  HandyNotes, vv1.5.5
  HandyNotesBattleForAzerothTreasures, v1
  HandyNotesDraenorTreasures, v1.21
  HandyNotesDungeonLocations, v1.46
  HandyNotesLegionTreasures, v1
  Informant, v8.1.6246 (SwimmingSeadragon)
  MaxDps, v8.1.3.2
  MaxDpsDemonHunter, v8.1.5.3
  NPCScan, v8.0.1.13
  Pawn, v2.2.42
  RaiderIO, v8.1.0 (v201906260600)
  RaiderIODBEUA, v
  RaiderIODBEUAR, v
  RaiderIODBEUH, v
  RaiderIODBEUHR, v
  Scrap, v13.15
  ScrapOptions, v13.15
  ScrapSpotlight, v13.15
  SlideBar, v8.1.6239 (SwimmingSeadragon)
  Stubby, v8.1.6240 (SwimmingSeadragon)
  TheUndermineJournal, v5.4.20190625
  TomTom, vv80200-1.0.1
  TradeSkillMaster, vv4.7.14
  WeakAuras, v2.13.1
  WorldQuestTracker, v
  BlizRuntimeLib_enUS v8.2.0.80200 <none>
  (ck=5f9)

**Comment by Spacespook** [comment]
Also having this issue.  
Date: 2019-06-26 23:50:49
ID: 1
Error occured in: Global
Count: 1
Message: Error trapped for Processor message 'itemtooltip' in module ItemSuggest:
..\AddOns\Auc-Advanced\CorePost.lua line 547:
   attempt to index upvalue 'ScanTip3' (a nil value)
Debug:
   Auc-Advanced\CoreUtil.lua:887: SendProcessorMessage()
   Auc-Advanced\CoreMain.lua:178:
      Auc-Advanced\CoreMain.lua:56
   (tail call): ?
   ...AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:115:
      ...AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:99
   ...AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:171: h()
   ...AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:480:
      ...AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:476
   [C]: ?
   [C]: ?
   [C]: OnTooltipSetItem()
   Enchantrix\EnxMain.lua:232:
      Enchantrix\EnxMain.lua:228
   [C]: ?
   ...AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:408:
      ...AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:402
   ...face\AddOns\TradeSkillMaster\Core\Lib\TooltipLib.lua:78:
      ...face\AddOns\TradeSkillMaster\Core\Lib\TooltipLib.lua:76
   [C]: SetBagItem()
   ..\FrameXML\ContainerFrame.lua:1403: ContainerFrameItemButton_OnEnter()
   ...AddOns\Bagnon\external\Wildpants\components\item.lua:371: ShowTooltip()
   ...AddOns\Bagnon\external\Wildpants\components\item.lua:207:
      ...AddOns\Bagnon\external\Wildpants\components\item.lua:200
Locals:
None
AddOns:
  Swatter, v8.1.6241 (SwimmingSeadragon)
  AckisRecipeList, v8.2.0.2
  Altoholic, vr190
  AtlasLoot, vv8.09.00
  AtlasLootBattleforAzeroth, vv8.09.00
  AtlasLootBurningCrusade, vv8.09.00
  AtlasLootCataclysm, vv8.09.00
  AtlasLootClassic, vv8.09.00
  AtlasLootLegion, vv8.09.00
  AtlasLootMistsofPandaria, vv8.09.00
  AtlasLootWarlordsofDraenor, vv8.09.00
  AtlasLootWrathoftheLichKing, vv8.09.00
  AucAdvanced, v8.1.6201 (SwimmingSeadragon)
  AucFilterBasic, v8.1.6228 (SwimmingSeadragon)
  AucScanData, v8.1.6229 (SwimmingSeadragon)
  AucStatHistogram, v8.1.6230 (SwimmingSeadragon)
  AucStatiLevel, v8.1.6234 (SwimmingSeadragon)
  AucStatPurchased, v8.1.6231 (SwimmingSeadragon)
  AucStatSimple, v8.1.6232 (SwimmingSeadragon)
  AucStatStdDev, v8.1.6233 (SwimmingSeadragon)
  AucUtilFixAH, v8.1.6235 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.1.9
  Bartender4, v4.8.3
  BeanCounter, v8.1.6236 (SwimmingSeadragon)
  DataStore, vr65
  DataStoreAchievements, vr47
  DataStoreAgenda, vr29
  DataStoreAuctions, vr50
  DataStoreCharacters, vr43
  DataStoreContainers, vr59
  DataStoreCrafts, vr82
  DataStoreCurrencies, vr38
  DataStoreGarrisons, vr24
  DataStoreInventory, vr53
  DataStoreMails, vr52
  DataStorePets, vr44
  DataStoreQuests, vr46
  DataStoreReputations, vr43
  DataStoreSpells, vr32
  DataStoreStats, vr31
  DataStoreTalents, vr61
  DBMCore, v8.2.1
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Enchantrix, v8.1.6237 (SwimmingSeadragon)
  GatherMate2, v1.43.6
  Informant, v8.1.6246 (SwimmingSeadragon)
  NPCScan, v8.0.1.13
  Pawn, v2.2.42
  Recount, vv8.2.0a
  SlideBar, v8.1.6239 (SwimmingSeadragon)
  Stubby, v8.1.6240 (SwimmingSeadragon)
  Titan, v5.17.2.80100
  TitanBag, v5.17.2.80100
  TitanClock, v5.17.2.80100
  TitanGold, v5.17.2.80100
  TitanLocation, v5.17.2.80100
  TitanLootType, v5.17.2.80100
  TitanPerformance, v5.17.2.80100
  TitanRepair, v5.17.2.80100
  TitanVolume, v5.17.2.80100
  TitanXP, v5.17.2.80100
  TradeSkil

**Comment by Dalarrus** [comment]
Work Around, using Bagnon 8.1.9b, Go into the in-game keybinds menu, in the addons tab, you can bind opening the Bagnon window to a key here, B seems to work, but vendors still open the default bags, as a note.
