### ISSUE TITLE
tullamods/Bagnon --update help (sort of: WORKAROUND FOUND)

### ISSUE THREAD

**Issue by seascape195** [tullamods/Bagnon#940]
Since 8.2 patch went live -- Bagnon no longer works correctly

However, if you have bags open and someone opens trade window with you.. it will then show the merged bag **AND** the default blizzard separate bags.

So, this is only someone helpful.. open all bags (Shift+B is what I use) -- then open Trade window with anyone and you'll again see your merged bags screen.  This is the ONLY way I've found to be able to access all your bags/view as one large bag again.

I've tried uninstalling, reinstalling.. deleting WTF/Cache folders.. to then uninstall/reinstalling again.. manually removing bagnon from Addons.txt -- etc.  So far that's the only way that semi works (which is pretty useless overall).

**Comment by seascape195** [comment]
UPDATE 2.0 --- FOUND A WORKAROUND:

OPEN MAIN MENU
GOTO: "KEY BINDINGS"
Select "AddOns"
Check the box (top right): [x] Character Specific Key Bindings
Under **Key 1** | for "Toggle Inventory" click the **Not Bound** (to set it)
Then press:  [Shift] B  -- which should assign Shift key + B to open all bags.
Click okay

You should now be able to once again see your merged bags as once big bag.

**Comment by ShadixBear** [comment]
I found another workaround, I reloaded the old version 8.1.9 since the new 8.1.9b doesn't work right.
The old version still works with the new WoW patch
