### ISSUE TITLE
lua error and separate bags after patch 8.2

### ISSUE THREAD

**Issue by YammYcoding** [tullamods/Bagnon#941]
cannot open consolidated bags after patch 82 release.

Backpacks ignores the consolidation.

Bank bags shows both consolidated and separate bags frames.

no lua errors though.

**Comment by YammYcoding** [comment]
Error happens when i mouse over some filled slot inside a bag.

**Comment by Rawrjay** [comment]
Same here, in addition after the update using "C" on the keyboard with the option enabled does open a consolidated bag, but using "B" to open shows only the individual bags.

**Comment by Shiroma51** [comment]
Downgrade to the previous version till the bug is sorted.  :)

**Comment by Toeroe** [comment]
I'm having the same problem with the bags not consolidating plus there is nothing showing in any of the separate bags until I turn off bagnon. Rolling it back to the previous version seems to work fine.

**Comment by sirzooro** [comment]
I have the same problem - B key opens separate bags. What is interesting, when I open crafting windows I see one big bag. The same when I access bank.

**Comment by YammYcoding** [comment]
On professions the consolitated bag also displays here. It's something wrong at the backpacks and the bank places :)  didnt test the void storage.

**Comment by YammYcoding** [comment]
Indeed, rolled back to version 8.1.9 and issue is gone.   The dev might take a look at what he changed over there ^^

**Comment by sirzooro** [comment]
Bank worked for me, at least when I accessed it from Garrison.

I have noticed one more thing: when I opened bags with B key, only 1st bag had items displayed in (last one which is most to the left). Other bags were displayed as empty.

**Comment by YammYcoding** [comment]
I also see that the addon Bagnon_Equipment also does not work as intended - I can no longer see the set tiny icon over the gears inside bags.  That might be related to bagnon issues.

**Comment by YammYcoding** [comment]
Last patch version 819c actually fixed all issues. Thank you man! :)
