### ISSUE TITLE
Reinstalled old 8.1.9

### ISSUE THREAD

**Issue by manly1138** [tullamods/Bagnon#942]
Used the keybinding work around and when I press B it works as one big bag.  When the app calls the bags up visiting a vendor or repair vendor through another app they all come up as individual bags.  If I hit B to bring up one bag and another call is made to bring up a bag like visiting a vendor then I am presented with a HUGE multicolored display that fills the screen with garbage.  I reinstalled 8.1.9 as that version seems to work great

**Comment by zaldor29** [comment]
Same issue for me too

**Comment by Xvenom82** [comment]
Same with me but my bags dont open at all for one big bag. Only individual bags like I dont have bagnon installed

**Comment by Sathh** [comment]
same

**Comment by jlee1905** [comment]
Same issue for me, bags all open individually plus all but one bag appears empty when they all have stuff in them.

**Comment by Mannic253** [comment]
Same for me there is also times where i am trying to choose the setting and the choices are overlapped.  When i noticed the bags look empty i relogged and the inventory was back, still broken up, but back.  When i went to the guild bank or to my bank it was fine there.  Really love this app PLEASE HELP

**Comment by jdtemple** [comment]
8.1.9c seems to have fixed things up.
