### ISSUE TITLE
elvui and bagnon

### ISSUE THREAD

**Issue by zdhar** [tullamods/Bagnon#943]
hi guys

i use elvui too and it's like bagnon is ignored
i can not get back bagnon

thanks in advance
![bagnong](https://user-images.githubusercontent.com/52300351/60305013-76659600-993b-11e9-82e4-3f5f384fcc1d.png)

**Comment by carlos-efmm** [comment]
Same error to me. Bag option in elvui is disabled

**Comment by Xwife1** [comment]
I had the Same issue, I deleted the Bag module elvui->Modules -> Bag (delete this folder)

Since I don't use ELVui bag it works perfectly.

**Comment by zdhar** [comment]
ty ! i will try this
its not working since elvui 11.14
i posted on their forums too :)
