### ISSUE TITLE
bagnon doesn't work on 8.2 & items disappear (just in bagnon, they come back when you disable it)

### ISSUE THREAD

**Issue by docFord** [tullamods/Bagnon#944]
Bagnon has issue with the new 8.2 patch. It no longer combines all of the bags into one large bag, and occasionally the bags will appear to be empty even though there are items in the bags. A friend and I had to disable Bagnon to see our bags and items so we could hearth or whistle as needed. 

Please fix this as bagnon is one of our favorite addons for managing bag space. Having to go back to the original design is painful.

**Comment by dartraiden** [comment]
https://github.com/tullamods/Bagnon/issues/940
https://github.com/tullamods/Bagnon/issues/934
https://github.com/tullamods/Bagnon/issues/937
https://github.com/tullamods/Bagnon/issues/938
https://github.com/tullamods/Bagnon/issues/941

**Comment by jdtemple** [comment]
8.1.9c seems to have fixed things up.
