### ISSUE TITLE
8.1.9c Interferes with rogue combo point display on character portrait

### ISSUE THREAD

**Issue by Talaan** [tullamods/Bagnon#945]
Tried installing and running 8.1.9c . The Combo point display disappeared of my portrait when playing a rogue. Didn't notice any bag display issues. Reverted back to 8.1.8 and portrait again displays combo points.

Note: I am having no issues with 8.1.8. Haven't noticed anything problematic with it.

**Comment by jdtemple** [comment]
Are you using any other UI mods? I just installed 8.1.9c, my main is an assassin rogue, and my combo points display just fine.

**Comment by Talaan** [comment]
I use Dominos for my bars. Strangely, I just tested out 8.1.9c with Dominos disabled on my rogue. I had combo points. After re-enabling Dominos, I still had combo points. I checked on my feral druid and her combo points were displayed. I can't get the issue to repeat itself. Dunno what happened but seems to be ok now.
