### ISSUE TITLE
Can't open in combat

### ISSUE THREAD

**Issue by Narzz** [tullamods/Bagnon#948]
**Running Software (please complete the following information):**
 - Game patch [e.g. Build 8.2]
 - Addon version: Latest

**Describe the bug**
Can't open bags while in combat, either by pressing B or the macro /bagnon bags. It just does nothing. I'm not sure if this is a WoW issue or not because it does happen with other things too but I've heard about it mostly with bagnon. Any advice?

I'm not getting any errors or anything.

**Comment by DarkWizardFIN** [comment]
I have also that same problem but i even cannot close it when im combat, its just stuck and when i get out combat then its working again fine. Its sometimes really annoying.

**Comment by Autumn0704** [comment]
I am also having the same issue. Cannot open or close while in any type of combat.  No error messages.

**Comment by Angeleob** [comment]
I am having this issue too. I can tell that only fewer people are having the same problem, that I can provide. It started happening like a week ago. It won't allow me to open my inventory neither by clicking the icon, pressing B nor via macro. I have uninstalled the AddOn and installed it back again but it didn't solve the problem. No error messages.

**Comment by Mayron** [comment]
Same

**Comment by ThatGuyJon** [comment]
same issue here, i do get an error Swatter catchs it. next time it happens ill post it here.

**Comment by Fun07** [comment]
Same on Classic with version 8.2.16
Message: Note: AddOn Bagnon attempted to call a protected function (BagnonFrameinventory:Show()) during combat lockdown. Debug: [C]: Show() ...rface\AddOns\Bagnon\common\Wildpants\core\frames.lua:55: ...rface\AddOns\Bagnon\common\Wildpants\core\frames.lua:51 (tail call): ? (tail call): ? ...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:146: ToggleBackpack() [string "TOGGLEBACKPACK"]:1: [string "TOGGLEBACKPACK"]:1
