### ISSUE TITLE
Switch Bank/Mats button

### ISSUE THREAD

**Issue by mixMugz** [tullamods/Bagnon#949]
Please, add button in bank window (like Character/Search/Bags) for switching between Bank and Mats Bank.

Now i need to turn on all BAGS ant switch clicking on Mats bag.

Also, if possible add option to separate space only for mats bag?

**Comment by Jaliborc** [comment]
Already exists. Exclusive reagents

**Comment by mixMugz** [comment]
I dont see separate button. I have only switch bag.
