### ISSUE TITLE
Problem with Bagnon

### ISSUE THREAD

**Issue by krissam** [tullamods/Bagnon#950]
**Running Software (please complete the following information):**
 - Game patch [e.g. Build 8.0.1.27178]
 - Addon version

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Error Logs**
If applicable, add the first error message (labeled 1/Many) that appeared.

**Additional context**
Hello, when i update to the latest version my bags do not load as one bag, they are back to separate and i cannot access anything in them.  When i go back to the older version it works perfectly so i will stay on there until you have a new update and try then.  I hope you can resolve it.  Sorry about not filling the stuff in above i didnt see any of it relevant for this issue as it is just a simple one.  Well i think it is anyway.  Sorry to cause you any inconvenience.

**Comment by Mintenker** [comment]
Nothing like good issue description 🤣
