### ISSUE TITLE
One of bags gets included in bank window.

### ISSUE THREAD

**Issue by ShanKanis** [tullamods/Bagnon#958]
Game patch - Classic WoW
Addon version - 8.2.2

When going to bank, one of bags is merged into bank window. It still appears the whole time in the inventory with no issues.

**Comment by anzz1** [comment]
FIX:
in Bagnon\external\Wildpants\components\bank.lua

`for slot = NUM_BAG_SLOTS, NUM_BAG_SLOTS + NUM_BANKBAGSLOTS do`
replace with:
`for slot = NUM_BAG_SLOTS + 1, NUM_BAG_SLOTS + NUM_BANKBAGSLOTS do`

GG

**Comment by Jaliborc** [comment]
> FIX:
> in Bagnon\external\Wildpants\components\bank.lua
> 
> find line number 20:
> `for slot = NUM_BAG_SLOTS, NUM_BAG_SLOTS + NUM_BANKBAGSLOTS do`
> replace with:
> `for slot = NUM_BAG_SLOTS + 1, NUM_BAG_SLOTS + NUM_BANKBAGSLOTS do`
> 
> GG

Nice catch. Thats the solution

**Comment by Jaliborc** [comment]
Its the miracle of the bag multiplication xD
