### ISSUE TITLE
Just a thank you.

### ISSUE THREAD

**Issue by Forkinator** [tullamods/Bagnon#962]
Was in the middle of leaving a bug report, was literally about to press the submit new issue button and decided to first check the releases to make sure i had the version number correct in the bug report and saw you released an update. 

The issue was with bagnon not opening the bag window when going to a trader, and also not opening the bag window when opening the character menu, but those were fixed. Didn't see any mention of those issues in the notes though.

Thank you for keeping this up to date for classic!

**Comment by Jaliborc** [comment]
Cool!No clue what your issue was, but one less is great.
