### ISSUE TITLE
[Classic] Color by Bag Type does not work with Herb Bag

### ISSUE THREAD

**Issue by abecks** [tullamods/Bagnon#963]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.2.4
 - Server patch: 1.13.2

 **Have you read the changelog? (please don't waste our time)**
Read, don't see any related fixes

**Describe the bug**
The "Color by Bag Type" feature does not seem to working with the Classic 1.13.2 client. I have an Herb Bag equipped and the bag slots remain the default color.

**To Reproduce**
Steps to reproduce the behaviour:
1. Acquire an herb bag
2. Open Bagnon
3. Default settings should color the empty herb bag slots light green
4. Instead will be the default background color (white/no tint)

**Expected behaviour**
Default settings should color the empty herb bag slots light green

**Screenshots**
https://i.imgur.com/2nthbos.png

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the first message (labelled 1/Many) that appeared.

**Additional context**

**Comment by Typ3Castt** [comment]
Can you provide the commit reference that fixed this?
