### ISSUE TITLE
[Classic] - Lack of Bag sorting button

### ISSUE THREAD

**Issue by ShammyLevva** [tullamods/Bagnon#965]
**Is your feature request related to a problem? Please describe.**
Lack of feature in classic - suspect API issue

**Describe the solution you'd like**
A button to sort items in bag thus compacting bags so all free space is at end. (I've not played WoW for about 5 years but I'm sure it used to have this feature.

**Describe alternatives you've considered**
Manually moving items around in bag to make it look less cluttered.

**Comment by nalmeth** [comment]
This now exists. Someone should close this.

**Comment by Jaliborc** [comment]
> This now exists. Someone should close this.

How so? Item sorting didn't exist in classic, and it seems Blizzard kept it that way.

**Comment by nalmeth** [comment]
It's now available in Bagnon Classic. So this is now irrelevant.

**Comment by Jaliborc** [comment]
> It's now available in Bagnon Classic. So this is now irrelevant.

Its not?

**Comment by Jaliborc** [comment]
I would know, cause I develop Bagnon

**Comment by nalmeth** [comment]
I know you do, but I don't understand. I'm using Bagnon Classic, and there's is definitely a sort button.

**Comment by ShammyLevva** [comment]
@Jaliborc sorry can you clarify has this been added to Bagnon or not? The conversation seems to have gone off on a tangent as to whether sorting was in original or not. Irrelevant. 

I’m asking if sorting can be added or if it’s there how do I activate it please.

**Comment by nalmeth** [comment]
@ShammyLevva I'm not sure if Jaliborc is misunderstanding me, but I wasn't referring to sorting being built-in. I was saying the current version of bagnon has a sorting button when used in Classic. I assume that's what you're looking for?

**Comment by Jaliborc** [comment]
@ShammyLevva Sorting HAS NOT been added to Bagnon. It can detect if some other mod implemented sorting though.

I'm currently working on a built-in sorting feature, that will work in bags, bank and even vault.

**Comment by nalmeth** [comment]
@Jaliborc If there's no sorting, then how do you explain my image? _My bank and inventory in Classic, The bright green square is the missing icon for the sort. As noted in the image, clicking the one on the inventory works (as you can see everything is shuffled to the bottom). The bank however does not work, and errors with the ticket I submitted._

This is using Bagnon 8.2.5-8.2.8 installed through Twitch App.

![sorting](https://user-images.githubusercontent.com/978736/64386574-2243f580-cfff-11e9-9d48-e2009df58c62.png)

**Comment by Jaliborc** [comment]
Read my comment again

**Comment by nalmeth** [comment]
If that's a yes, then I wish you'd said that earlier. It was completely unclear that this was not a part of your mod.

**Comment by Jaliborc** [comment]
Yes, that is another mod sorting algorithm being used.

**Comment by Cringely** [comment]
Hi, I see form the commits that sorting functionality was added and the enhancement was closed. But this hasn't hit the twitch/curse channel yet. Thanks for adding the feature!

I'm curious what the general lag time is between submitting code and when it actually gets deployed by Curse? @Jaliborc

**Comment by Jaliborc** [comment]
@Cringely It's already on Twitch, but on a beta version. It's not a simple feature, so it's gonna take a couple of iterations before I'm comfortable with an official release.
