### ISSUE TITLE
Classic: Bagnon Not Working

### ISSUE THREAD

**Issue by Sarkli** [tullamods/Bagnon#967]
I have this installed for Classic. It is updated. It says its compatible but when i log into the game it flags it as 'out of date'. Even when i turn it on regardless of that it still will not even load once in game. There are no errors or anything like that. It doesnt show up in interface addons either. It just simply doesnt work. Let me know if there is anything i can do to help resolve this issue.

I have other addons installed as well that work just fine. Bagnon and OmniCC are the only two that dont work. Thanks

**Comment by Vengetik** [comment]
Same

**Comment by lohmann99** [comment]
Just updated have the same issue on the last 3 versions. says its out of date, no errors just doesn't load

**Comment by nalmeth** [comment]
You might need to check compatibility if you have other addons. Classic version has been working fine for me.

**Comment by joe776** [comment]
Where did you download the addon? It seems like the version on wowinterface.com is severly out of date. curseforge.com has a more recent version which works for me.
@Jaliborc Do you plan on updating the addon on wowinterface? Seems like a lot of people stumble upon this, also for OmniCC.

**Comment by Sarkli** [comment]
I got both the add-ons from the twitch app initially. It's where I've gotten all the rest of the add-ons as well. I also deleted and tried downloading from curseforge and installing manually as well and they still don't work. It was mention as a possible conflict. I will attempt a complete check about that later today but I turned off a couple that would make sense if they conflicted and Bagnon/Omni still doesn't work. A lot of the add-ons I'm using in Classic are ones I use in BfA where I don't have an issue.

**Comment by Sarkli** [comment]
Ok i just tried disabling all addons except for bagnon and it still says out of date and will not even show up in game. I mean its not an urgent need for this addon its just more for convenience of course i would just like to help figure out why in particular its not working at all..

**Comment by CSxxMERLIN** [comment]
same issue. won't work at all. even though twitch app says up to date.

**Comment by nickzelei** [comment]
Same problem. I've yet to get Bagnon working in Classic.

**Comment by BaudRate96** [comment]
I had problems as well but i got it working now by enabling "Load out of date addons" in the top right corner and disabling all other outdated addons (might work with them enabled though)
Latest addon version (8.2.9)
