### ISSUE TITLE
Classic Bagnon not surpressing Blizzard Bags

### ISSUE THREAD

**Issue by LarryGatlin** [tullamods/Bagnon#968]
**Running Software (issues missing this information will be deleted):**
 - Addon version:8.2.4
 - Server patch: Classic

 **Have you read the changelog? (please don't waste our time)**
 Mark if read.

**Describe the bug**
if you hit the backpack it brings up the Blizzard Bags.  This started after a trade window was opened, when it closed the blizz bags were displayed with no contents. If you select the backpack, it displays the Blizzard bag framework. If you hit a button that has bagnon on it, it will bring up the bagnon bag.  If the Blizzard bag framework is open, is messes the bagnon framework. This happens with all Addons disabled. 
**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the first message (labelled 1/Many) that appeared.

**Additional context**

**Comment by xReadyAimMissx** [comment]
I think we are having the same issue. Checkout my report I submitted like at the same time as you. lol
