### ISSUE TITLE
Classic: Bagnon stopped displaying items

### ISSUE THREAD

**Issue by VVlasy** [tullamods/Bagnon#970]
**Running Software:**
 - Addon version: 8.2.5
 - Server patch: Classic 1.13

 **Have you read the changelog?**
 Yes. That is why i waited until 8.2.5

**Describe the bug**
Frame for bagnon opens but does not display any items.

**To Reproduce**
No steps, one day it stopped working 3 days ago and it stayed that way.

**Expected behaviour**
Bagnon frame should display items from bags

**Screenshots**
![Výstřižek](https://user-images.githubusercontent.com/20575526/64073223-0658f080-cc9b-11e9-9bd4-df765265ca8c.PNG)

**Error Logs**
`Message: ...AddOns\Bagnon\external\Wildpants\components\item.lua:86: CreateFrame: Unknown frame type 'ItemButton'
Time: Sun Sep  1 09:26:32 2019
Count: 2
Stack: ...AddOns\Bagnon\external\Wildpants\components\item.lua:86: CreateFrame: Unknown frame type 'ItemButton'
[C]: in function 'CreateFrame'
...AddOns\Bagnon\external\Wildpants\components\item.lua:86: in function 'Construct'
...AddOns\Bagnon\external\Wildpants\components\item.lua:38: in function 'Create'
...AddOns\Bagnon\external\Wildpants\components\item.lua:22: in function 'New'
...s\Bagnon\external\Wildpants\components\itemFrame.lua:124: in function <...s\Bagnon\external\Wildpants\components\itemFrame.lua:112>`

`Locals: (*temporary) = "ItemButton"
(*temporary) = "BagnonItemSlot2"
(*temporary) = nil
(*temporary) = "ContainerFrameItemButtonTemplate"`

**Additional context**
I fixed the problem by going into item.lua in external\Wildpants\components and on line 86 changed ItemButton to Button. I have little experience in using the WoW API. Maybe this is an isolated case...

**Comment by PKM999** [comment]
I've got same issue, I think it starred happening once I switch characters and tried opening bags on it.

**Comment by drikfan** [comment]
Confirmed:
Edit ...AddOns\Bagnon\external\Wildpants\components\item.lua:86 'ItemButton' to 'Button' fixes issue.

**Comment by ShetiPhian** [comment]
Same error happens if you enable the option "Display Blizzard Frames for Hidden Bags"
Changing that line fixes it also.
