### ISSUE TITLE
Mouseover items in classic professions panel doesn't show inventory count

### ISSUE THREAD

**Issue by addohm** [tullamods/Bagnon#972]
![WoWScrnShot_090319_155913](https://user-images.githubusercontent.com/25333107/64154682-eaed1180-ce63-11e9-8e01-19b70603b053.jpg)
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.2.5
 - Server patch: 1.13.2 (31687)

**Describe the bug**
Mouseover of items in inventory shows inventory counts across characters and banks, mouseover of items in professions panels do not.

**Expected behaviour**
I would assume that the same behavior in the bag should exist across all occurrences of mousing over items.

**Comment by Jaliborc** [comment]
![1](https://user-images.githubusercontent.com/442637/64911938-5f5b6680-d728-11e9-8571-4f98103c0b59.PNG)
Just verified that it does.

**Comment by BoojiB** [comment]
> ![1](https://user-images.githubusercontent.com/442637/64911938-5f5b6680-d728-11e9-8571-4f98103c0b59.PNG)
> Just verified that it does.

It does work for some professions, like alchemy and tailoring, but I can also report that the enchanting profession panel does not show the inventory counts.
