### ISSUE TITLE
Item Count tooltip not working for other characters' bank.

### ISSUE THREAD

**Issue by RadvachTsvetkov** [tullamods/Bagnon#975]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.2.2
 - Server patch: WoW Classic - 1.13.2 ( 31727 ( release x64) sep 3 2019

 **Have you read the changelog? (please don't waste our time)**
 Mark if read. How to mark.

**Describe the bug**
Item count tooltip:
For 8.2.9 version i see items count ONLY for current character same realm.
For this version 8.2.2 ( i tried old one to check if works). I cannot see item count for other characters BANK items.
current - 1 in bag | 7 in bank
someOtherChar  - 7 in bag ( no matter if i have in bank it will not show, ever, i opened my bank multiple times with both characters )

**To Reproduce**
Steps to reproduce the behaviour:
(4.) See error

**Expected behaviour**
To SEE and COUNT number of the item pointing with mouse that are INSIDE OTHER character's BANK

**Screenshots**

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the first message (labelled 1/Many) that appeared.
No such

**Additional context**
...World of Warcraft\_classic_\Interface\AddOns\Bagnon\external\Wildpants\features\tooltipCounts.lua:line89,90,91

					for i = FIRST_BANK_SLOT, LAST_BANK_SLOT do
						bank = bank + FindItemCount(owner, i, itemID)
					end
the above code is working in behaviur: NEVER showing OTHER character's ITEM COUNT in BANK

Modified for test:
					for i = FIRST_BANK_SLOT, LAST_BANK_SLOT do
						bank = 666 --bank + FindItemCount(owner, i, itemID)
					end
the above code is working in behaviur: ALWAYS showing OTHER character's ITEM COUNT in BANK to be 666

Didn't have time to check the actual problem, never programmed on lua, I rather playing wow.
On addon version 8.2.9 i never see ANY item count info for OTHER characters. Sorry for not telling full info for 8.2.9 bug like i did for 8.2.2 bug. Big test was on 8.2.2

**Comment by fnordson** [comment]
I have a similar issue.  
The items are being showed but only sometimes. 
Some items may be missing. Others not. It makes the count pretty unreliable. 

Unsing the newest version: **8.2.9**

**Comment by Jaliborc** [comment]
Fixed

**Comment by fnordson** [comment]
> Fixed

Do I have to do something? 
Delete saved data? 
Is it live in the version from 2 days ago?
