### ISSUE TITLE
Sort does not work with specialty bags (ammo, quiver, etc...)

### ISSUE THREAD

**Issue by D34d3nd** [tullamods/Bagnon#977]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.2.10
 - Server patch: 1.13.2 (31727)

 **Have you read the changelog? (please don't waste our time)**
 Yes, always read the changelog.

**Describe the bug**
With a specialty bag (ammo pouch), sorting does not work. Blizzard warning message "Only bullets can be placed in that"

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Bagnon pressing the 'b' or whatever button is mapped to open bags
2. Make sure you have an ammo pouch with bullets. Full slot or missing slots in the ammo pouch does not matter. Have not tested with quiver or soul shard bag for locks.
3. Click on the 'broom' icon to sort

**Expected behaviour**
Bags sorted including sorting of ammo pouch

**Screenshots**
![2019-09-09_19-24-48](https://user-images.githubusercontent.com/4047717/64575376-1a56bf00-d339-11e9-92b6-7346c63aee8e.png)

**Error Logs**
No error logs

**Additional context**
Nothing additional

**Comment by Jaliborc** [comment]
Can you send a screenshot of your bags? because it is working for me

**Comment by Jaliborc** [comment]
If you get rid of one of the bullet stacks (putting it at the bank, using, deleting). Does the issue still happen?

**Comment by D34d3nd** [comment]
Works just fine after I put all my arrows and quiver in the bank. Sorting works.

So, a couple things have changed since yesterday.

- I no longer have an ammo pouch and ammo. I have a quiver and arrows. Same issue though but I get "Only arrows can go in that"

- I am no longer using the starter ammo pouch for dwarves. See last bullet-point where I say I now have a quiver.

- I have tried different options in Bagnon like 'Reverse Bag Order', 'Bag Break', and 'Reverse Slot Order'. Each one or any combination seems to have the same effect where it will refuse to sort.

- I have tried placing the ammo pouch from before and now the quiver in different bag slots to see if it made a difference. No difference. Same error message. 

Also, I have noticed, after I get the Blizzard red error message that only bullets or arrows can be placed in that, every time I manually move something in my bag, I see the message again. Its almost like the process is still running maybe?

Is there some type of debug or verbose logging that I can enable to possibly catch the output when I run this? I have tried '/console scriptErrors 1' and then a reload of the UI, but it does not seem to be throwing any LUA error popups.

**Comment by D34d3nd** [comment]
One other note. I have just tried disabling all addons 1 by 1 so the only addons enable are Bagnon, Bagnon Config, Bagnon Guild Bank, and Bagnon Void Storage.

Issue persists. This did not help.

**Comment by Jaliborc** [comment]
Could you try depositing items other than bullets/arrows in the bank one by one and see if one of them causes the issue?
Might be trying to put a specific item in the specialized bag.

**Comment by Jaliborc** [comment]
I think I figured it out. It was the enchant reagents that it was trying to place in the ammo bag.

**Comment by D34d3nd** [comment]
Awesome, thanks for all the work. I will check it out once you post an update.

**Comment by BjarkeM** [comment]
This is still a bug on version 9.1.0 for TBC classic 2.5.1

any pointers as for where I can look to fix this in the code?
