### ISSUE TITLE
Frame Layer "High" doesn't go over tooltip window in Classic wow

### ISSUE THREAD

**Issue by PlastKladd** [tullamods/Bagnon#979]
This is for the Classic version 8.2.9 if that makes any difference.

The option Frame Layer "High" doesn't make the bag window overlap the tooltip when mousing over players etc. 
Can't see anything in bag unless I reset tooltip by mousing over something in my bag, or moving the entire bag to another location on my screen.

**Comment by Jaliborc** [comment]
I mean... it's not suppose to. Tooltips have a frame layer above HIGH called TOOLTIP, so that they are always above everything.
