### ISSUE TITLE
Bank not visible and stack counts missing (Classic)

### ISSUE THREAD

**Issue by Benflag** [tullamods/Bagnon#982]
Since the last update in Classic:

-the stack count doesn't show in tooltip anymore (to show how many of an item you have in bags and in bank
-the bank is empty when right clicking to toggle your bank when you are out in the world

**Comment by addohm** [comment]
+1 Here.  I thought it might have been related to all the garbage that Auctioneer adds to the tooltip, but it doesnt seem to be the case.  Just don't have any inventory counts anymore.

**Comment by Jaliborc** [comment]
Enable BagBrother

**Comment by phyber** [comment]
I have this issue too, and BagBrother is enabled.
