### ISSUE TITLE
Unable to right click on any bag

### ISSUE THREAD

**Issue by Master-85** [tullamods/Bagnon#983]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.2.9
 - Server patch: 8.0.2

 **Have you read the changelog? (please don't waste our time)**
 Mark if read.  - I've read it.

**Describe the bug**

Whenever you right click one of the bags you get a .lua error.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Bags'
2. Right click on any bag '....'
3. See error

**Expected behaviour**

Not get a .lua error

**Screenshots**

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the first message (labelled 1/Many) that appeared.

The Error:
Date: 2019-09-13 20:42:52
ID: 1
Error occured in: Global
Count: 1
Message: ...ce\AddOns\Bagnon\common\Wildpants\components\bag.lua line 83:
   attempt to index global 'ContainerFrame1FilterDropDown' (a nil value)
Debug:
   ...ce\AddOns\Bagnon\common\Wildpants\components\bag.lua:83:
      ...ce\AddOns\Bagnon\common\Wildpants\components\bag.lua:80
Locals:
self = BagnonBag0 {
 0 = <userdata>
 Count = <unnamed> {
 }
 frame = BagnonFrameinventory {
 }
 Icon = BagnonBag0IconTexture {
 }
 FilterIcon = <unnamed> {
 }
}
button = "RightButton"
(*temporary) = nil
(*temporary) = nil
(*temporary) = false
(*temporary) = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:367
 IsRetail = false
 SearchFrame = <unnamed> {
 }
 EnableModule = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 ToggleFrame = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\core\frames.lua:43
 IterateEmbeds = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:442
 UpdateFrames = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\core\frames.lua:39
 GetOwnerIconString = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\core\owners.lua:86
 ShowBag = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\core\frames.lua:83
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:409
 defaultModuleState = true
 IsEnabled = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:451
 Frame = <unnamed> {
 }
 OptionsToggle = <unnamed> {
 }
 DisableModule = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:350
 Bag = <unnamed> {
 }
 IsBank = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\core\bags.lua:23
 RegisterMessage = <function> defined @Interface\AddOns\AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 IsBackpack = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\core\bags.lua:15
 UpdateSettings = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\core\settings.lua:135
 BagToggle = <unnamed> {
 }
 SetEnabledState = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 ShowFrame = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\core\frames.lua:51
 UnregisterSignals = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\core\classes.lua:34
 RegisterEvent = <function> defined @Interface\AddOns\AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 sets = <table> {
 }
 IterateModules = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:437
 UnregisterAllEvents = <function> defined @Interface\AddOns\AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 baseName = "Bagnon"
 IsFrameEnabled = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\core\frames.lua:27
 BrokerDisplay = <unnamed> {
 }
 SendSignal = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\core\classes.lua:30
 SortButton = <unnamed> {
 }
 ShowOptions = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\features\commands.lua:77
 ItemFrame = <unnamed> {
 }
 Enable = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:294
 NewModule = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:235
 CreateOptionsLoader = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\features\commands.lua:71
 PrintHelp = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\features\commands.lua:53
 IterateFrames = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\core\frames.lua:23
 GetModule = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:210
 OnSlashCommand = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\features\commands.lua:33
 TitleFrame = <unnamed> {
 }
 BankFrame = <unnamed> {
 }
 defaultModuleLibraries = <table> {
 }
 RegisterSignal = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\core\classes.lua:22
 OwnerSelector = <unnamed> {
 }
 IsBankBag = <function> defin
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AdvancedInterfaceOptions, v1.3.2
  AtlasLootClassic, vv1.1.9-beta
  BagBrother, v
  Bagnon, v8.2.9
  Bartender4, v4.8.7
  BeanCounter, v8.2.6381 (SwimmingSeadragon)
  ClassicCastbars, vv1.0.5
  ClassicCastbarsOptions, v
  DBMCore, v1.13.7
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  GTFO, v4.49.2
  Informant, v8.2.6374 (SwimmingSeadragon)
  LeatrixPlus, v1.13.30
  MapCoords, v0.31c
  Recount, vv1.13.2b
  ShadowedUnitFrames, vv4.2-Classic-Beta7
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  VendorPrice, v1.2.4
  WeakAuras, v2.14.6
  ZygorGuidesViewerClassic, v1.0
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=2b5)

**Additional context**

**Comment by Jaliborc** [comment]
Fixed

**Comment by Master-85** [comment]
Fixed as in a future update or? It's still happening after uninstall and
reinstall manually of the addon.

**Comment by Jaliborc** [comment]
Future update
