### ISSUE TITLE
Faster Sort (Classic)

### ISSUE THREAD

**Issue by Zottelchen** [tullamods/Bagnon#993]
**Is your feature request related to a problem? Please describe.**
The sort is annoyingly slow.

**Describe the solution you'd like**
I used Bagnon + https://github.com/shirsig/SortBags before and there the sort was very fast. Only difference was the missing texture for the sort button in Bagnon. Also sort worked better and the easy way to put materials into the bank worked.

Thank you in advance!

**Comment by Jaliborc** [comment]
Then use SortBags. Bagnon supports external sorting addons.
