### ISSUE TITLE
Sorting Options [Classic]

### ISSUE THREAD

**Issue by Frazzer951** [tullamods/Bagnon#994]
**Is your feature request related to a problem? Please describe.**
When you use the sort button in classic it just moves everything to the top of the bag in a set way and there is no way of changing how you want the items to be sorted.

**Describe the solution you'd like**
An option in the addon settings where you can set how you want things to be sorted. Like I can set that I want quest items to be sorted to the bottom left of the bag. Consumables like food, water, and potions, on the bottom left. Things like that.

**Describe alternatives you've considered**
Just manually sorting my bags and ignoring the sort button.

**Additional context**

**Comment by Jaliborc** [comment]
I have no plans to add configuration for sorting. I recommend installing a sorting mod like tdpack or SortBags for more complex sorting options.
