### ISSUE TITLE
Feature Request: Item Rulesets Explanatory Label

### ISSUE THREAD

**Issue by fireundubh** [tullamods/Bagnon#998]
> Github issues are for bug reports and feature requests only.

Can you add a label to the Item Rulesets page of the options menu that describes what item rulesets are and what they do?

**Comment by Tuller** [comment]
I've blocked fireundubh for harassment beyond github. 

I would probably suggest just dropping the rules panel from Bagnon, as as far as I'm aware its not really used in the addon.

**Comment by Jaliborc** [comment]
@Tuller just haven't had the time to implement it as an option in Bagnon. Plan to have it disabled by default, but some users might like it.
